### ISSUE TITLE
Why use the "androidx.activity" beta version?

### ISSUE THREAD

**Issue by Joslyn-Chen** [InsertKoinIO/koin#1001]
**Describe the bug**
 `koin-core version 2.2.2` use `androidx.activity:activity:1.2.0-beta01` , 
but I am using the official version 1.1.0,
ContextAware is conflicting.

**To Reproduce**
 See error:
`Cannot access 'androidx.activity.contextaware.ContextAware' which is a supertype of 'BaseActivity'. Check your module classpath for missing or conflicting dependencies`

**Expected behavior**
I think the official version of Koin should not be the beta version of other libraries.

**Koin project used and used version (please complete the following information):**
 `koin-core version 2.2.2`

**Additional moduleDefinition**
Version conflict.

**Comment by arnaudgiuliani** [comment]
Configuration updated in Koin 3.0.1 with latest stable ktx: `1.2.0`. Backport on 2.3.0 will be done
