### ISSUE TITLE
Add support for watchosX64 target

### ISSUE THREAD

**Issue by Ornolfr** [InsertKoinIO/koin#1005]
Kotlin Native 1.4.30 introduced support for the new Apple Watch simulator. When koin is built for this target, the build errors out.

**Comment by RdeWilde** [comment]
Any clue on what needs to be done for this? Or any workaround atm, other than use another simulator?

**Comment by arnaudgiuliani** [comment]
solved in https://github.com/InsertKoinIO/koin/pull/1091
