### ISSUE TITLE
2.2.1 -> 2.2.2 regression: No definition found for SavedStateHandle

### ISSUE THREAD

**Issue by gmk57** [InsertKoinIO/koin#1009]
**Describe the bug**
I'm injecting ViewModel with SavedStateHandle, as described in [the docs](https://insert-koin.io/docs/reference/koin-android/viewmodel/#viewmodel-and-state-bundle) and [the blog post about new API in Koin 2.2](https://medium.com/koin-developers/whats-next-with-koin-2-2-3-0-releases-6c5464ae5e3d):
```
class MyStateViewModel(val state: SavedStateHandle) : ViewModel()

val appModule = module {
    viewModel { MyStateViewModel(get()) }
}

class MainActivity : AppCompatActivity(R.layout.activity_main) {
    val myStateVM: MyStateViewModel by viewModel()
}
```
This works in Koin **2.2.1**, but in **2.2.2** it crashes with `NoBeanDefFoundException: No definition found for class:'androidx.lifecycle.SavedStateHandle'. Check your definitions!`

**To Reproduce**
Check out [my sample project](https://github.com/gmk57/TestKoinSavedState)

**Koin project used and used version:**
`koin-androidx-viewmodel version 2.2.2`

This bug is already mentioned in [other](https://github.com/InsertKoinIO/koin/issues/963#issuecomment-765408255) [issues](https://github.com/InsertKoinIO/koin/issues/996#issuecomment-769313454) related to 2.1 -> 2.2 migration, but i think it deserves a thread of its own.

**Side note:** [changelog](https://github.com/InsertKoinIO/koin/blob/master/CHANGELOG.md) is missing for 2.2.* versions.

**Comment by DJDarkByte** [comment]
Just ran into this problem as well. I think the problem is in `ViewModelResolver.kt`:

```
private fun <T : ViewModel> Scope.pickFactory(
        viewModelParameters: ViewModelParameter<T>,
): ViewModelProvider.Factory {
    return when {
        viewModelParameters.registryOwner != null && viewModelParameters.initialState != null -> StateViewModelFactory(this, viewModelParameters)
        else -> DefaultViewModelFactory(this, viewModelParameters)
    }
}
```

I tried setting an initial state with `emptyState()` to make sure that `viewModelParameters.initialState != null`, and that fixed it. The documentation doesn't mention this though.

The check for `viewModelParameters.initialState` was added in commit c2633dd but wasn't there previously.

**Comment by hoc081098** [comment]
https://github.com/Kotlin-Android-Open-Source/MVI-Coroutines-Flow/blob/2419ff9e533fdf3d6e42ebdb82b563ac051d66ea/feature-add/src/main/java/com/hoc/flowmvi/ui/add/AddModule.kt#L15

**Comment by rewgoes** [comment]
@arnaudgiuliani, can you please check this issue? Is there any change that was not documented or this is an actual issue on version 2.2.2?

**Comment by rewgoes** [comment]
> https://github.com/Kotlin-Android-Open-Source/MVI-Coroutines-Flow/blob/2419ff9e533fdf3d6e42ebdb82b563ac051d66ea/feature-add/src/main/java/com/hoc/flowmvi/ui/add/AddModule.kt#L15
> I have used `it.get()` instead 😃 and it works
> 
> ```kotlin
> viewModel {
>     AddVM(
>       addUser = get(),
>       savedStateHandle = it.get(),
>     )
>   }
> ```

That didn't work for me! :expressionless:

**Comment by arnaudgiuliani** [comment]
Koin 2.3.0 will bring back separated API for StateViewModel. Documentation is a bit out of date. Just need to finish website and maven central migration.

**Comment by arnaudgiuliani** [comment]
> @arnaudgiuliani, can you please check this issue? Is there any change that was not documented or this is an actual issue on version 2.2.2?

Try to use injected parameters like: `{params -> MyViewModel(params.get())}`, to resolve injected params.

Koin 3.0.1 will restore a consistent `saveStateViewModel()` API

**Comment by arnaudgiuliani** [comment]
Koin 2.3.0 will backport new APIs from 3.0.1 to 2.2.x branch

**Comment by bartoliniii** [comment]
Hi, I'm looking for workaround and I'm not able to find any.
Using it.get() cause me a little different error (on both 2.2.2 and 2.2.1 versions):

`org.koin.core.error.DefinitionParameterException: No value found for type 'androidx.lifecycle.SavedStateHandle'`

Is there any way to make it working?

**Comment by arnaudgiuliani** [comment]
for now, we don't expect to fix 2.x. Koin 3.x will be eligible for `LTS` support.

**Comment by arnaudgiuliani** [comment]
If you need more help, come here: https://github.com/InsertKoinIO/koin/issues/1212
