### ISSUE TITLE
Check if a Koin instance exists on Ktor install

### ISSUE THREAD

**Issue by auguwu** [InsertKoinIO/koin#1010]
**Describe the bug**
The ktor package for Koin doesn't check if there is an instantiated Koin instance. Leading to an error saying there is one instance already running. In the project I'm creating, we need a internal API and Ktor is being used; since we instantiate a Koin instance before-hand, it won't be used.

**To Reproduce**
1. Create a project or using an existing one
2. Create a new Koin instance *first*
3. Bootstrap Ktor with `install(Koin)`
4. Error occurs

**Expected behavior**
The ktor package should use an existing Koin instance than creating a new one.

**Koin project used and used version (please complete the following information):**
- koin-core: v2.2.2
- koin-ktor: v2.2.2

**Comment by arnaudgiuliani** [comment]
Merged in koin 3.0.1. Will be ported for 2.3.0
