### ISSUE TITLE
koin:koin-androidx-viewmodel not compatibility with android-lifecycle-2.3.0

### ISSUE THREAD

**Issue by JajaComp** [InsertKoinIO/koin#1012]
Koin version: 2.2.2
Issue with sync project:
```
   > Could not find androidx.lifecycle:lifecycle-extensions:2.3.0.
     Required by:
         project :features:tasks
   > Could not find androidx.lifecycle:lifecycle-extensions:2.3.0.
     Required by:
         project :features:tasks > org.koin:koin-androidx-viewmodel:2.2.2
```

Module androidx.lifecycle:lifecycle-extensions was deleted

**Comment by ganesh3s3** [comment]
I have the same issue too.. How to fix this?

**Comment by ganesh3s3** [comment]
Hi, as you said `lifecycle-extensions` was removed and it was split into different modules so you can choose what you want for your project. Just replace the dependency with the new dependency modules you want from here: [https://developer.android.com/jetpack/androidx/releases/lifecycle](https://developer.android.com/jetpack/androidx/releases/lifecycle)

    dependencies {
    def lifecycle_version = "2.3.0"
    def arch_version = "2.1.0"

    // ViewModel
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    // LiveData
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycle_version"
    // Lifecycles only (without ViewModel or LiveData)
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycle_version"

    // Saved state module for ViewModel
    implementation "androidx.lifecycle:lifecycle-viewmodel-savedstate:$lifecycle_version"

    // Jetpack Compose Integration for ViewModel
    implementation "androidx.lifecycle:lifecycle-viewmodel-compose:1.0.0-alpha01"

    // Annotation processor
    kapt "androidx.lifecycle:lifecycle-compiler:$lifecycle_version"
    // alternately - if using Java8, use the following instead of lifecycle-compiler
    implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycle_version"

    // optional - helpers for implementing LifecycleOwner in a Service
    implementation "androidx.lifecycle:lifecycle-service:$lifecycle_version"

    // optional - ProcessLifecycleOwner provides a lifecycle for the whole application process
    implementation "androidx.lifecycle:lifecycle-process:$lifecycle_version"

    // optional - ReactiveStreams support for LiveData
    implementation "androidx.lifecycle:lifecycle-reactivestreams-ktx:$lifecycle_version"

    // optional - Test helpers for LiveData
    testImplementation "androidx.arch.core:core-testing:$arch_version"
    }

**Comment by JajaComp** [comment]
> Hi, as you said `lifecycle-extensions` was removed and it was split into different modules so you can choose what you want for your project. Just replace the dependency with the new dependency modules you want from here: https://developer.android.com/jetpack/androidx/releases/lifecycle
> 
> ```
> dependencies {
> def lifecycle_version = "2.3.0"
> def arch_version = "2.1.0"
> 
> // ViewModel
> implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
> // LiveData
> implementation "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycle_version"
> // Lifecycles only (without ViewModel or LiveData)
> implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycle_version"
> 
> // Saved state module for ViewModel
> implementation "androidx.lifecycle:lifecycle-viewmodel-savedstate:$lifecycle_version"
> 
> // Jetpack Compose Integration for ViewModel
> implementation "androidx.lifecycle:lifecycle-viewmodel-compose:1.0.0-alpha01"
> 
> // Annotation processor
> kapt "androidx.lifecycle:lifecycle-compiler:$lifecycle_version"
> // alternately - if using Java8, use the following instead of lifecycle-compiler
> implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycle_version"
> 
> // optional - helpers for implementing LifecycleOwner in a Service
> implementation "androidx.lifecycle:lifecycle-service:$lifecycle_version"
> 
> // optional - ProcessLifecycleOwner provides a lifecycle for the whole application process
> implementation "androidx.lifecycle:lifecycle-process:$lifecycle_version"
> 
> // optional - ReactiveStreams support for LiveData
> implementation "androidx.lifecycle:lifecycle-reactivestreams-ktx:$lifecycle_version"
> 
> // optional - Test helpers for LiveData
> testImplementation "androidx.arch.core:core-testing:$arch_version"
> }
> ```

I'am not use lifecycle-extensions. It's dependency from Koin.

**Comment by ganesh3s3** [comment]
I am using 2.2.2 too and it works fine after I did the fix I've mentioned above. 

Make sure you don't have 
`implementation "androidx.lifecycle:lifecycle-extensions:*.*.*"` 
anywhere in your build.gradle (app). I personally replaced that line with 

     // ViewModel
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycleVersion"
     // LiveData
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycleVersion"
    // Lifecycles only (without ViewModel or LiveData)
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycleVersion"
    // Annotation processor
    implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycleVersion"`

So try that.

**Comment by JajaComp** [comment]
Sorry. You are right!!

**Comment by ganesh3s3** [comment]
Glad to be of help. Please close this issue unless you have anything else you have to talk about regarding this problem. Thanks.
