### ISSUE TITLE
Dependency is null when trying to access it on abstract class property initialisation

### ISSUE THREAD

**Issue by mgoyanes** [InsertKoinIO/koin#1026]
Filling this as a bug but don't know if it is a bug.

My `ProductsViewModel` implements the abstract class `AbstractProductsViewModel`.
I'm passing some dependencies to the `ProductsViewModel` and when the `AbstractProductsViewModel` is being created, one of its properties triggers a method in `ProductsViewModel`.

```
open val product: LiveData<Product> =  { 
        // gets the product from the database and calls method in ProductsViewModel
        generateProduct(product)
    }
```

I'm getting the error:

```
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.lifecycle.LiveData com.XXX.repository.ProductsRepository.getProductNumber()' on a null object reference
        at com.XXX.ProductsViewModel.generateProduct(ProductsViewModel.kt:82)
        at com.XXX.AbstractProductsViewModel.<init>(AbstractProductsViewModel.kt:54)
        at com.XXX.ProductsViewModel.<init>(ProductsViewModel.kt:35)
```

`ProductsRepository` is being passed in the constructor and while I'm debugging I can see that it is not null but when I try to access it is null.
I put a breakpoint just before trying to access the `ProductsRepository` in the `generateProduct` product method and in there, it is null but if I go up in the debugger "frames" I can see it is not null.

![image](https://user-images.githubusercontent.com/5049948/109475000-0e027c80-7a6d-11eb-8e2a-a84b7436d514.png)

Any idea why and How can I overcome this?

**Comment by androks** [comment]
I did face the very same issue
