### ISSUE TITLE
Bintray responds with 401 for 3.0.1-alpha-5

### ISSUE THREAD

**Issue by headsvk** [InsertKoinIO/koin#1027]
**Describe the bug**
I tried updating to Koin multiplatform 3.0.1-alpha-5 but Bintray requires credentials for this version.
Is this related to Bintray closing down?

Gradle error with ekito:
```
Could not GET 'https://dl.bintray.com/ekito/koin/org/koin/koin-core-jvm/3.0.1-alpha-5/koin-core-jvm-3.0.1-alpha-5.pom'. 
Received status code 401 from server: Unauthorized
```

Gradle error with jcenter:
```
Could not find org.koin:koin-core-iosarm64:3.0.1-alpha-5.
Searched in the following locations:
  - https://jcenter.bintray.com/org/koin/koin-core-iosarm64/3.0.1-alpha-5/koin-core-iosarm64-3.0.1-alpha-5.pom
  ```

**To Reproduce**
1. Go to https://dl.bintray.com/ekito/koin/org/koin/koin-core-jvm/3.0.1-alpha-5/koin-core-jvm-3.0.1-alpha-5.pom
2. Bintray asks for credentials

**Expected behavior**
Koin version listed in [docs](https://insert-koin.io/docs/setup/unstable/) is publicly available.

**Koin project used and used version (please complete the following information):**
`koin-core version 3.0.1-alpha-5`

**Additional moduleDefinition**
none

**Comment by jfreeley** [comment]
@headsvk the dependency names have changed recently from e.g. `org.koin:koin-core:$koin_version` to `io.insert-koin:koin-core:$koin_version". Not sure if that's what might be causing it maybe?

**Comment by arnaudgiuliani** [comment]
Yes, bintray won't be updated anymore. The new group id is `io.insert-koin` instead of `org.koin`

**Comment by arnaudgiuliani** [comment]
You can check latest version: https://search.maven.org/search?q=io.insert-koin

**Comment by headsvk** [comment]
@jfreeley @arnaudgiuliani thank you, that was an unexpected change.
I see that the change is higlighted in readme now
```
// New group id moved from `org.koin` to `io.insert-koin`
koin_version = '3.0.1-beta-1'
```
that should help others like me 👍

**Comment by Deishelon** [comment]
Are there stable versions on maven?
