### ISSUE TITLE
Simplified beans definition

### ISSUE THREAD

**Issue by qwert2603** [InsertKoinIO/koin#1029]
Hello!

### Motivation
One of the advantages of annotations-based DI is that it does not require to edit DI-related code, when parameters are added or removed from `@Inject` constructor. For example, Daggers consumes such changes automatically. It would be great to add such possibility to Koin.

### Solution
One of the possible solutions may look like this:
```kotlin
import org.koin.core.definition.BeanDefinition
import org.koin.core.module.Module
import org.koin.core.qualifier.Qualifier
import org.koin.dsl.module

inline fun <reified T> Module.single(
    crossinline creator: () -> T,
    qualifier: Qualifier? = null,
    createdAtStart: Boolean = false,
    override: Boolean = false,
): BeanDefinition<T> = single(qualifier, createdAtStart, override) {
    creator()
}

inline fun <reified P0, reified T> Module.single(
    crossinline creator: (P0) -> T,
    qualifier: Qualifier? = null,
    createdAtStart: Boolean = false,
    override: Boolean = false,
): BeanDefinition<T> = single(qualifier, createdAtStart, override) {
    creator(get())
}

inline fun <reified P0, reified P1, reified T> Module.single(
    crossinline creator: (P0, P1) -> T,
    qualifier: Qualifier? = null,
    createdAtStart: Boolean = false,
    override: Boolean = false,
): BeanDefinition<T> = single(qualifier, createdAtStart, override) {
    creator(get(), get())
}

class SomeRepo(val argumentOne: Int)

val someModule = module {
    single(::SomeRepo)
}
```

With such approach we can remove `argumentOne` from `SomeRepo`'s constructor or add `argumentTwo` without any changes in Koin's module definition.

The same can be applied to `factory`, `scoped` and other `BeanDefinition` creators. Moreover, it works well with any method references, not only with constructors.

### Limitations
But there are limitations. There is no easy way to specify `DefinitionParameters` or `Qualifier` of individual dependency of the bean.

### Feedback is welcome.
In comments.

**Comment by arnaudgiuliani** [comment]
Closing this, as another PR is fixing it
