### ISSUE TITLE
Incorrect implementation of DefinitionParameters#set

### ISSUE THREAD

**Issue by Antimonit** [InsertKoinIO/koin#1044]
**Describe the bug**
Not really a bug but an incorrect implementation.

In `core/koin-core/src/commonMain/kotlin/org/koin/core/parameter/DefinitionParameters.kt` you can find a `set` method.

```kotlin
open class DefinitionParameters(val values: List<Any?> = listOf()) {
    ...
    fun <T> set(i: Int, t: T) {
        values.toMutableList()[i] = t as Any
    }
    ...
```

`toMutableList()` creates a _copy_ of the original collection. Then we assign a value to the _copy_ and finally discard the _copy_. This implementation is a no-op.

---

Verified this behavior in a scratch file:
```kotlin
val values: List<Any?> = ArrayList<Any?>().apply {
    add("one")
    add("two")
    add("three")
}

fun <T> set(i: Int, t: T) {
    values.toMutableList()[i] = t as Any
}

set(1, "Whatever")

println(values)
```
prints
> [one, two, three]

**To Reproduce**
N/A

**Expected behavior**
N/A

**Koin project used and used version (please complete the following information):**
`koin-core version 3.0.1`

**Additional moduleDefinition**
N/A

**Comment by arnaudgiuliani** [comment]
Fixed in 3.0.2
