### ISSUE TITLE
How to update retrofit 'baseurl' at a runtime using koin (Recreate or update value)?

### ISSUE THREAD

**Issue by birkanfirat** [InsertKoinIO/koin#1048]
Hello, I have code like below but after changing the baseurl, the request I made goes with the old baseurl again. Where am I making a mistake?

https://github.com/InsertKoinIO/koin/issues/384 ->This issue I send a comment but I could not get an answer so I'm recreating it.

Koin version:
Screen Shot 2021-03-12 at 11 43 16

Network module:

val networkModule = module(override = true) {
scope(named("baseURL")) { scoped { provideBaseUrlHolder() } }
factory { authInterceptor(get()) }
factory { provideOkHttpClient(get()) }
factory { provideRetrofitFor(get()) }
single(override = true) { provideApi(get()) }

}

fun provideOkHttpClient(authInterceptor: AuthInterceptor): OkHttpClient {
return OkHttpClient().newBuilder().connectTimeout(180, TimeUnit.SECONDS)
    .writeTimeout(180, TimeUnit.SECONDS)
    .readTimeout(180, TimeUnit.SECONDS).addInterceptor(authInterceptor)
    .build()

}

fun provideRetrofitFor(okHttpClient: OkHttpClient): Retrofit {
val scope = getKoin().getOrCreateScope(
    "baseUrlId", named("baseURL"))
val baseUrl = scope.getScope("baseUrlId").get<String>()
val gson = GsonBuilder().setLenient().create()
return Retrofit.Builder().baseUrl(baseUrl).client(okHttpClient)
    .addConverterFactory(ScalarsConverterFactory.create())
    .addConverterFactory(GsonConverterFactory.create(gson)).build()

}

fun provideApi(retrofit: Retrofit): Api = retrofit.create(Api::class.java)

fun provideBaseUrlHolder() = Constants.BASE_URL
Application Class:

fun startKoins() {
   startKoin {
        androidLogger()
        androidContext(this@App)
        modules(listOf(networkModule, repositoryModule, viewModelModule))
    }
   scope =  getKoin().getOrCreateScope("baseUrlId", named("baseURL"))

}

fun refreshScope() {
    scope?.close()
    scope = getKoin().getOrCreateScope("baseUrlId", named("baseURL"))
    provideBaseUrlHolder()
  
/*     provideRetrofitFor(get())
    stopKoin()
    startKoins() // I've also tried these functions but they don't work
*/

}
Login Class:
Calling login API and after getting successful response of login api change baseurl to

Constants.BASE_URL = it.baseUrl
getBaseApplication().refreshScope()

**Comment by birkanfirat** [comment]
![image](https://user-images.githubusercontent.com/26115864/111270838-6c208980-8641-11eb-8c33-7338a0825301.png)

I also updated my Koin version but still couldn't

**Comment by francescogatto** [comment]
did you resolved?

**Comment by francescogatto** [comment]
@arnaudgiuliani can you help us to solve this? it will be useful to tons of devs

**Comment by nazirjon-1997** [comment]
did you resolved?

**Comment by nazirjon-1997** [comment]
did you resolved?

**Comment by MoustafaElsaghier** [comment]
any updates please?

**Comment by arnaudgiuliani** [comment]
can you update your code blocks with the code formater to help read it please? 🙏

**Comment by BenjyTec** [comment]
Has anybody found a working solution for this?

**Comment by arnaudgiuliani** [comment]
few ways to handle this case:
- load/unload all for Koin config
- use Scopes

The first one is ok and less complex than scopes, as all your app is tied by your HTTP client configuration.
