### ISSUE TITLE
Update koin-android-viewmodel to use androidx library version only

### ISSUE THREAD

**Issue by ptornhult** [InsertKoinIO/koin#1058]
**Is your feature request related to a problem? Please describe.**
We're trying to get rid of Jetifier, but it looks like the koin-android-viewmodel:222 dependency still imports android dependencies instead of androidx

**Describe the solution you'd like**
Update the dependencies to be fully Jetpack / AndroidX compatible

**Describe alternatives you've considered**
Migrate to Hilt?

**Target Koin project**
koin-android-viewmodel:2.2.2

**Comment by ptornhult** [comment]
This might be helpful to run a quick check: https://adambennett.dev/2020/08/disabling-jetifier/

**Comment by cezaryece** [comment]
"Update the dependencies to be fully Jetpack / AndroidX compatible" vote for this with all hands and even legs.
It is very hard to build old example project depends on Koin.

**Comment by ptornhult** [comment]
I didn't realize that there is also a koin-androidx-viewmodel dependency that we could use (solved it for us)
