### ISSUE TITLE
Bug on using latest Kotlin MutableStateFlow 

### ISSUE THREAD

**Issue by johnjake** [InsertKoinIO/koin#1069]
**Describe the bug**
Hi everyone good day! I am migrating to MutableStateFlow and StateFlow on my ViewModel it works perfectly fine using MutableLiveData, however if I replace the MutableLiveData with MutableStateFlow it will only observe once, when I call / execute the second time it does not work. 

**To Reproduce**

RepoModule:

      `val repositoryModule = module {
          factory { Repository(userDao = get(), mapper = get()) }
      }`

ViewModelModule:

    `val viewModelLogin = module {
        viewModel { LoginViewModel(repository = get()) }
    }`

ViewModel: 

          `class LoginViewModel(private val repository: Repository): ViewModel() {
                  private var stateJob: Job? = null
                  private val userFlow = MutableLiveData<State<User?>>(State.Empty)
          
              fun authenticateUser(userName: String, password: String) {
                 stateJob = viewModelScope.launch(Dispatchers.Main) {
                      val data = repository.getUserByCredential(userName, password)
                      val stateData = State.Data(data)
                      userFlow.value = stateData
                  }
              }
              val userState = userFlow
          
              override fun onCleared() {
                  super.onCleared()
                  stateJob?.cancel()
              }
          }`

OnFragment:
 
      `private val viewModel: LoginViewModel by inject()

         override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
              super.onViewCreated(view, savedInstanceState)
           
             viewModel.userState.observe(viewLifecycleOwner) { state ->
                  handleStateFlow(state)
              }
          }
      
          override fun onActivityCreated(savedInstanceState: Bundle?) {
              super.onActivityCreated(savedInstanceState)
                binding?.userLoginButton?.setOnClickListener {
                val username = binding?.email?.text.toString()
                val password = binding?.password?.text.toString()
                viewModel.authenticateUser(username, password)
             }
        }`
 
    
The issue is the same weather I use `MutableStateFlow` coupled with `StateFlow` its the same it can only observe once, replacing it with livedata the login will work. Anyone having this issues? I'll appreciate if someone can give an insight.    

**Expected behavior**

**Koin project used and used version (please complete the following information):**
  ` implementation("org.koin:koin-android:2.0.1")
    implementation ("org.koin:koin-androidx-viewmodel:2.0.1")
    implementation ("org.koin:koin-androidx-scope:2.0.1")`

**Comment by skoric** [comment]
`StateFlow` ignores repeated values. I'm assuming you push the same data every time and that's why you only get it once. See this post for all the details: https://proandroiddev.com/should-we-choose-kotlins-stateflow-or-sharedflow-to-substitute-for-android-s-livedata-2d69f2bd6fa5

Unless I missed something, I don't think this is a Koin issue.

**Comment by johnjake** [comment]
@skoric thank you for the clarification.

Best Regards 
Jake
