### ISSUE TITLE
Unresolved reference: stateViewModel

### ISSUE THREAD

**Issue by wojiaoliushe** [InsertKoinIO/koin#1070]
i can use by viewModel() well, but cant use by stateViewModel()

did i miss any dependencies?

here is my impletations:

    def koin_version = '2.2.2'
    implementation "org.koin:koin-android:$koin_version"
    implementation "org.koin:koin-android-viewmodel:$koin_version"
    implementation "org.koin:koin-android-scope:$koin_version"
    implementation "org.koin:koin-android-ext:$koin_version"
    implementation "org.koin:koin-core:$koin_version"
    implementation "org.koin:koin-core-ext:$koin_version"

![image](https://user-images.githubusercontent.com/35270067/115849878-e7066c80-a457-11eb-9a8c-561ed2ba0176.png)

Appreciate!

**Comment by wojiaoliushe** [comment]
i use this statement in a fragment

**Comment by tonisives** [comment]
I have the same issue
```
    implementation("io.insert-koin:koin-android:2.2.2")
    implementation("io.insert-koin:koin-androidx-viewmodel:2.2.2")
    implementation("io.insert-koin:koin-androidx-scope:2.2.2")
    implementation("io.insert-koin:koin-androidx-ext:2.2.2")
    implementation("io.insert-koin:koin-androidx-fragment:2.2.2")
```

Tried to import from previous locations

```
import org.koin.androidx.viewmodel.ext.android.stateViewModel
import org.koin.androidx.viewmodel.scope.stateViewModel
```

But they don't exist in 2.2.2. They existed in 2.1.5.

**Comment by gautamadavi** [comment]
As of Koin 2.2.2 there is no need to include the extra keyword for stateViewModel

`// simply inject
   val myStateVM : MyStateViewModel by viewModel()`

https://medium.com/koin-developers/whats-next-with-koin-2-2-3-0-releases-6c5464ae5e3d

**Comment by tonisives** [comment]
Thanks for the info. 

Should this should be updated in the [docs](https://insert-koin.io/docs/reference/koin-android/viewmodel) also? 

Also, would it make sense to deprecate API-s, not remove them? It takes considerable effort to research the problem and make a bug report like this. @arnaudgiuliani 

---

I now tried added the library `"io.insert-koin:koin-android-ext:3.0.1"` only, and used viewModel() to get the ViewModel with SavedStateHandle. It crashes with 

```
No definition found for class:'androidx.lifecycle.SavedStateHandle'
```

```
class App : Application() {
    private val viewModelModule = module {
        viewModel { MainViewModel(get()) }
    }

    override fun onCreate() {
        super.onCreate()

        startKoin {
            androidLogger()
            androidContext(this@App)
            modules(listOf(viewModelModule))
        }
    }
}

class MainViewModel(handle: SavedStateHandle) : ViewModel() {
    init {
        println("hello")
    }
}
```

```
class MainActivity : AppCompatActivity() {
    private val viewModel: MainViewModel by viewModel()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        viewModel.hashCode()
    }
}
```

I'll resolve to not using the SavedStateHandle for now.
test project: [koin-statehandle-test.zip](https://github.com/InsertKoinIO/koin/files/6381375/koin-statehandle-test.zip)

**Comment by irgaly** [comment]
There is same error in koin 3.0.2 + io.insert-koin:koin-androidx-viewmodel 2.2.3

```
E/[Koin]: Instance creation error : could not create instance for [Factory:'....MyViewModel']: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'androidx.lifecycle.SavedStateHandle'. Check your definitions!
```

viewmodel

```
class MyViewModel(
    private val logger: Logger,
    private val savedStateHandle: SavedStateHandle,
    ...
```

module

```
import org.koin.androidx.experimental.dsl.viewModel
val myModule = module {
    viewModel<MyViewModel>()
    ...
```

Fragment

```
import org.koin.androidx.viewmodel.ext.android.viewModel

class MyFragment: Fragment(R.layout.my_layout) {
     private val viewModel: MyViewModel by viewModel()
    ...
```

**Comment by arnaudgiuliani** [comment]
Koin 3.0.2 bring back `stateViewModel` keywork. Just use `koin-android` module in 3.x ... as it has been merged in main koin android module.

**Comment by irgaly** [comment]
Ok,  I removed  io.insert-koin:koin-androidx-viewmodel dependency.

I defined io.insert-koin:koin-android-ext:3.0.2, and It works fine with `by stateViewModel()`.
The important thing is savedStateHandle parameter must be first parameter of ViewModel constructor.

ViewModel: this is OK.

```
class MyViewModel(
    private val savedStateHandle: SavedStateHandle,
    private val logger: Logger,
    ...
```

**Comment by arnaudgiuliani** [comment]
in 3.0.2 you don"t need to have SavedStateHandle in first parameter. You can do `viewModel { params -> MyViewModel(params.get(),get())}`

**Comment by irgaly** [comment]
I'm using reflection extension ( see this comment's module https://github.com/InsertKoinIO/koin/issues/1070#issuecomment-843765499 ), and it crashes when savedStateHandle parameter is not first parameter.
