### ISSUE TITLE
Jetpack compose DefaultPreview fails

### ISSUE THREAD

**Issue by BulatMukhutdinov** [InsertKoinIO/koin#1072]
Using viewModel inside Composable funcions causes exception `java.lang.IllegalStateException: KoinApplication has not been started`.

I am injecting viewModel like this
```
@Composable
    private fun MyInfo(viewModel: MyInfoViewModel = getViewModel()) 
```

Koin version: 3.0.1

**Comment by arnaudgiuliani** [comment]
Could be intersting to see ho we can avoid that. Can you specify a "dumb" ViewModel for preview?

**Comment by jumaallan** [comment]
@arnaudgiuliani Any code samples? I am also facing the same issue

**Comment by tamtom** [comment]
same issue 
Render problem 
`java.lang.IllegalStateException: KoinApplication has not been started   at org.koin.core.context.GlobalContext.get(GlobalContext.kt:36)   at org.koin.androidx.viewmodel.ext.android.ViewModelStoreOwnerExtKt.getViewModel(`

**Comment by SirFilbido** [comment]
I'm having the same problem and the way I'm using it is in accordance with Koin's [documentation](https://insert-koin.io/docs/reference/koin-compose/compose).

```
@Composable
fun MyScreen(navController: NavController) {

    val viewModel = koinViewModel<MyViewModel>()

```

`java.lang.IllegalStateException: KoinApplication has not been started
`

Is there already a solution that doesn't use external libraries?
