### ISSUE TITLE
 java.lang.NoSuchMethodError: No virtual method elapsedNow-UwyO8pc()D in class Lkotlin/time/TimeMark

### ISSUE THREAD

**Issue by ligi** [InsertKoinIO/koin#1076]
**Describe the bug**

After updating to Kotlin 1.5.0 I am getting this runtime error:

```
04-27 15:37:54.756  6429  6429 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method elapsedNow-UwyO8pc()D in class Lkotlin/time/TimeMark; or its super classes (declaration of 'kotlin.time.TimeMark' appears in /data/app/org.walleth-rBcMmS3wfGt-FnuS1dhI1g==/base.apk)
04-27 15:37:54.756  6429  6429 E AndroidRuntime: 	at org.koin.core.time.MeasureKt.measureDuration(Measure.kt:63)
04-27 15:37:54.756  6429  6429 E AndroidRuntime: 	at org.koin.core.KoinApplication.modules(KoinApplication.kt:63)
04-27 15:37:54.756  6429  6429 E AndroidRuntime: 	at org.walleth.App$onCreate$1.invoke(App.kt:142)
04-27 15:37:54.756  6429  6429 E AndroidRuntime: 	at org.walleth.App$onCreate$1.invoke(App.kt:139)
04-27 15:37:54.756  6429  6429 E AndroidRuntime: 	at org.koin.core.context.GlobalContext.startKoin(GlobalContext.kt:65)
04-27 15:37:54.756  6429  6429 E AndroidRuntime: 	at org.koin.core.context.DefaultContextExtKt.startKoin(DefaultContextExt.kt:31)
04-27 15:37:54.756  6429  6429 E AndroidRuntime: 	at org.walleth.App.onCreate(App.kt:139)
04-27 15:37:54.756  6429  6429 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
04-27 15:37:54.756  6429  6429 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
04-27 15:37:54.756  6429  6429 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
04-27 15:37:54.756  6429  6429 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
04-27 15:37:54.756  6429  6429 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-27 15:37:54.756  6429  6429 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
04-27 15:37:54.756  6429  6429 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
04-27 15:37:54.756  6429  6429 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-27 15:37:54.756  6429  6429 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
04-27 15:37:54.756  6429  6429 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

happens with koin 3.0.1

**Comment by Makzimalist** [comment]
I have the same issue, but without updating to Koltin 1.5.0, but with update `org.jetbrains.kotlinx:kotlinx-serialization-core` to 1.2.0
`koin = "3.0.1"
kotlin = "1.4.32"
kotlinxSerialization = "1.2.0"`

**Comment by trashkalmar** [comment]
As a temp workaround you should set your `KoinApplication.logger()` to `Level.ERROR` or `Level.NONE`.
Or just do not configure logger at all.

**Comment by almozavr** [comment]
I believe this is critical as more and more people will jump in `1.5.0` kotlin

**Comment by guillaume-tgl** [comment]
Is there any workaround when I'm not using Koin directly in my Android app but when it's one of my dependencies that use Koin? It seems like the default log level is set to Info for Android applications.

**Comment by sipersso** [comment]
I am also using a dependency that has Koin and this isn't the first time this happens unfortunately. Right now this issue makes my app crash for all users reaching out for support :/

**Comment by digrec** [comment]
Can a fix for this also be added to upcoming Koin 2.3 milestone?

We are still using Koin v2 in app. While we could update app to v3 soon (already tried), but we also use a 3rd party dependency that still uses Koin v2 - and this of course fails to build due to duplicate Koin classes from v2 and v3 packages.

**Comment by arnaudgiuliani** [comment]
yep, this is the same source problem with Time API from Kotlin that remains inconsistent :/

**Comment by arnaudgiuliani** [comment]
> Can a fix for this also be added to upcoming Koin 2.3 milestone?
> 
> We are still using Koin v2 in app. While we could update app to v3 soon (already tried), but we also use a 3rd party dependency that still uses Koin v2 - and this of course fails to build due to duplicate Koin classes from v2 and v3 packages.

Yep a 2.2.3 will appear soonly

**Comment by digrec** [comment]
> > Can a fix for this also be added to upcoming Koin 2.3 milestone?
> > We are still using Koin v2 in app. While we could update app to v3 soon (already tried), but we also use a 3rd party dependency that still uses Koin v2 - and this of course fails to build due to duplicate Koin classes from v2 and v3 packages.
> 
> Yep a 2.2.3 will appear soonly

Great! Thank you!

**Comment by arnaudgiuliani** [comment]
Deployment done for 3.0.2 & 2.2.3 🎉

**Comment by arkon** [comment]
Is there supposed to be new versions of all modules? `io.insert-koin:koin-androidx-compose:3.0.2` doesn't seem to exist.

**Comment by arnaudgiuliani** [comment]
compose can't be compiled with Kotlin 1.5 for now. We need to wait for a next update.

**Comment by digrec** [comment]
> Deployment done for 3.0.2 & 2.2.3 🎉

Where can I get `org.koin:koin-android:2.2.3`?

[Maven Central](https://mvnrepository.com/artifact/io.insert-koin/koin-android) only has the new `io.insert-koin:koin-android:2.2.3` which conflicts with 3rd party lib that depends on `org.koin:koin-android:2.2.2` from JCenter:

`Duplicate class org.koin.android.BuildConfig found in modules jetified-koin-android-2.2.2-runtime (org.koin:koin-android:2.2.2) and jetified-koin-android-2.2.3-runtime (io.insert-koin:koin-android:2.2.3) ...`

Any ideas how to go about this? Or the only option is to wait for 3rd party lib to update to `io.insert-koin:koin-android:2.2.3`?

**Comment by ligi** [comment]
Thanks - I can confirm the fix works!

@digrec don't think this will be possible - jcenter is discontinued and does not accept new artefacts - you will need to push your 3rd party lib to switch.

**Comment by digrec** [comment]
@ligi I'm aware of JCenter EOL and read only mode. I'll wait then, thanks!

**Comment by arnaudgiuliani** [comment]
@digrec Can you reopen a new issue?

**Comment by digrec** [comment]
> @digrec Can you reopen a new issue?

The 3rd party lib did migrate to `io.insert-koin:koin-android` in the mean time and I was also able to upgrade my app to v3 today. All good now, thanks!

**Comment by arnaudgiuliani** [comment]
yes, migrate to maven central artifacts. This is the sure way 👍

**Comment by sherden** [comment]
> [Maven Central](https://mvnrepository.com/artifact/io.insert-koin/koin-android) only has the new `io.insert-koin:koin-android:2.2.3` which conflicts with 3rd party lib that depends on `org.koin:koin-android:2.2.2` from JCenter:
> 
> `Duplicate class org.koin.android.BuildConfig found in modules jetified-koin-android-2.2.2-runtime (org.koin:koin-android:2.2.2) and jetified-koin-android-2.2.3-runtime (io.insert-koin:koin-android:2.2.3) ...`
> 
> Any ideas how to go about this? Or the only option is to wait for 3rd party lib to update to `io.insert-koin:koin-android:2.2.3`?

For those facing with this problem, you can use dependencySubstitution in gradle (you can use any compatible version):

`configurations.all {
    resolutionStrategy {
        dependencySubstitution {
            substitute module('org.koin:koin-android:2.2.2') using module("io.insert-koin:koin-android:2.2.3")
        }
    }
}`
