### ISSUE TITLE
Koin 3.0.1 + Jetpack Compose Navigation - getViewModel() create new ViewModel instance instead of return existing one

### ISSUE THREAD

**Issue by glush** [InsertKoinIO/koin#1079]
I'd try to use Koin 3.0.1 with new Jetpack Compose Navigation component. I'd pass ViewModel instance to Composable function using "composabe way" - 

@Composable
fun ComposableFun(viewmodel: MyViewModel = getViewModel()) {...}

If I'm not using Jetpack Compose Navigation Koin works as expected - getViewModel() returns existing ViewModel instance.

When app navigation use Jetpack Compose Navigation component getViewModel() creates new ViewModel instance every time at composable function enter. Same behavior if 

val vm : MainViewModel by viewModel()

used inside composable fun.

**To Reproduce**
Here is repo.
https://gitlab.com/gLush/koinwithnavigation
Initial commit - working sample w/o Navigation component.
Last commit - Navigation Component implementation with problem described. You can see how random viewModel stamp changes on screen change. Logcat also shows new VM instance creation.

**Expected behavior**
viewModel: ViewModelType = getViewModel() should return existing ViewModel instance.

**Koin project used and used version (please complete the following information):**
    implementation ("io.insert-koin:koin-android-ext:3.0.1")
    implementation ("io.insert-koin:koin-androidx-compose:3.0.1")

**Additional moduleDefinition**
Add any other moduleDefinition about the problem here.
implementation ("androidx.navigation:navigation-compose:1.0.0-alpha10")

**Comment by hungyanbin** [comment]
I have the same problem, provide my temporary solution, just write a custom extension function that replace LocalViewModelStoreOwner:

### Koin Version: 3.0.2
### Compose version:  1.0.0-beta08
### navigation version:  2.4.0-alpha02
 
```
public fun NavGraphBuilder.scopedComposable(
    route: String,
    arguments: List<NamedNavArgument> = emptyList(),
    deepLinks: List<NavDeepLink> = emptyList(),
    content: @Composable (NavBackStackEntry) -> Unit
) {
    val viewModelStore = ViewModelStore()
    val viewModelStoreOwner = ViewModelStoreOwner { viewModelStore }
    composable(route, arguments, deepLinks) { navBackStackEntry ->
        CompositionLocalProvider(LocalViewModelStoreOwner provides viewModelStoreOwner) {
            content(navBackStackEntry)
        }

        DisposableEffect(key1 = route) {
            onDispose {
                viewModelStore.clear()
            }
        }
    }
}

@Composable
inline fun <reified VM : ViewModel> scopedViewModel(
    qualifier: Qualifier? = null,
    noinline parameters: ParametersDefinition? = null
): VM {
    val viewModelStoreOwner = LocalViewModelStoreOwner.current!!
    val store = viewModelStoreOwner.viewModelStore
    return KoinJavaComponent.getKoin()
        .getViewModel(ViewModelParameter(VM::class, qualifier, parameters, null, store, null))
}
```

Replace your original `Composable()` with `scopedComposable()` in NavGraphBuilder, and replace `viewModel()` with `scopedViewModel()`

**Comment by jakobmann** [comment]
Got the exact same issue with:
```
implementation ("io.insert-koin:koin-android-ext:3.1.2")
implementation ("io.insert-koin:koin-androidx-compose:3.1.2")

implementation ("androidx.navigation:navigation-compose:2.4.0-alpha04")
```

**Comment by raghavpai** [comment]
Is there any update on this issue?

**Comment by leungandrew** [comment]
I've worked around this by following suit on how Hilt handles scoping ViewModels to a nav graph.  They essentially us a `NavBackstackEntry` as their `ViewModelStoreOwner`.

So I created the following function:
```
@Composable
inline fun <reified VM : ViewModel> getNavGraphViewModel(
    qualifier: Qualifier? = null,
    noinline parameters: ParametersDefinition? = null,
    backStackEntry: NavBackStackEntry
): VM {
    return remember(qualifier,parameters) {
        backStackEntry.getViewModel(qualifier, parameters)
    }
}
```

And you would pass something like `navController.getBackStackEntry("your-root-route-like-the-route-of-your-nav-host")`

**Comment by burnoo** [comment]
I've released a library - cokoin, which supports Compose Navigation . It is an alternative to `org.koin:koin-androidx-compose`.
### [Library Migration Guide](https://github.com/burnoo/cokoin/wiki/Migration-from-org.koin:koin-androidx-compose)
### Use Cokoin with Compose Navigation
1. Add dependency:
```gradle
implementation {
    implementation "dev.burnoo:cokoin-jetpack-navigation:0.1.8"
}
```
2. Replace `NavHost` with `KoinNavHost`:
```kotlin
KoinNavHost(navController, startDestination = "1") {
    composable("1") {
        Screen1()
    }
}
```
3. Use `getNavController` and `getNavViewModel` inside composables.
```kotlin
@Composable
fun Screen1() {
    val navController = getNavController()
    Button(onClick = { navController.navigate("2") }) {
        val navViewModel = getNavViewModel<MainViewModel>()
        //...
    }
}
```

**Comment by wafer-li** [comment]
Update solution from https://github.com/InsertKoinIO/koin/issues/1079#issuecomment-902215765

At `koin 3.1.3` above, there is no `backStackEntry.getViewModel(qualifier, parameters)`, so the solution above doesn't work.

After looking into the source code of koin, I found that the `getViewModel()` method from `koin 3.1.3` use `LocalViewModelStoreOwner`. 

https://github.com/InsertKoinIO/koin/blob/master/android-compose/koin-androidx-compose/src/main/java/org/koin/androidx/compose/ViewModelComposeExt.kt#L49


Therefore, we could use the `CompositionLocal` to provide the `NavBackStackEntry` as `ViewModelStoreOwner`

```kt
composable(Home) { navBackStackEntry ->
    CompositionLocalProvider(LocalViewModelStoreOwner provides navBackStackEntry) {
        HomeScreen(navController = navController, homeViewModel = getViewModel())
    }
}
```

**Comment by arnaudgiuliani** [comment]
Last update bring `owner` param to the getViewModel function:

```kotlin
inline fun <reified T : ViewModel> getViewModel(
    qualifier: Qualifier? = null,
    owner: ViewModelOwner = getComposeViewModelOwner(),
    scope: Scope = GlobalContext.get().scopeRegistry.rootScope,
    noinline parameters: ParametersDefinition? = null,
)
```

Where ViewModelOwner can be used to pass StoreOwner:

```kotlin
@Composable
fun getComposeViewModelOwner(): ViewModelOwner {
    return ViewModelOwner.from(
        LocalViewModelStoreOwner.current!!,
        LocalSavedStateRegistryOwner.current
    )
}
```

**Comment by arnaudgiuliani** [comment]
Documentation need to be updated also.

**Comment by luangs7** [comment]
Same problem with `3.2.0-beta-1`

**Comment by arnaudgiuliani** [comment]
there some fixes about VM API that are coming in 3.1.6. It should realign ViewModel API on Google ones

**Comment by svenjacobs** [comment]
I'm a bit confused since there are multiple solutions posted here. With Koin 3.2.0 what is the current solution to get a `ViewModel` instance that is bound to the current `NavBackStackEntry` when using [Navigation Compose](https://developer.android.com/jetpack/compose/navigation)? Does it work out of the box?

By the way, the documentation [here](https://insert-koin.io/docs/reference/koin-android/compose/) is outdated for Koin 3.2.0 as it still mentions `ViewModelOwner` in `getViewModel()`. This has been replaced with `ViewModelStoreOwner`.

**Comment by svenjacobs** [comment]
It seems this works out of the box with Koin 3.2.0 since `LocalViewModelStoreOwner` inside the [composable](https://developer.android.com/reference/kotlin/androidx/navigation/compose/package-summary#(androidx.navigation.NavGraphBuilder).composable(kotlin.String,kotlin.collections.List,kotlin.collections.List,kotlin.Function1)) function of Navigation Compose provides the current `NavBackStackEntry`.

**Comment by danieldaeschle** [comment]
I still have this problem and don't know how to solve it.

**Comment by arnaudgiuliani** [comment]
what version have you @danieldaeschle ?

**Comment by danieldaeschle** [comment]
Latest koin-androidx-compose 3.4.2

**Comment by jdavisAR** [comment]
> Latest koin-androidx-compose 3.4.2

I'm also experiencing this issue when trying to pass a parameter to a ViewModel.

**Comment by arnaudgiuliani** [comment]
do you use `koinViewModel` fucntion?

**Comment by aungkhanthtoo** [comment]
Add "io.insert-koin:koin-androidx-compose-navigation:3.4.5" and use koinNavViewModel() function. It works!

**Comment by kepper104** [comment]
Ran into same problem, using koin-androidx-compose:3.4.6 and compose-destinations:core:1.9.42-beta for navigation, koinNavViewModel() doesn't change anything, everything just returns new instances of my ViewModel

**Comment by scottyab** [comment]
I'm seeing the same behaviour a ViewModel is created each time. Even after switching to use `koinNavViewModel` from koin-androidx-compose-navigation v3.4.6

**Comment by vivek-modi** [comment]
I want to use share same viewmodel instance in koin in jetpack compose navigation. I know there is a function in koinViewModel() to get instance of viewModel. I recently saw a [Koin Documentation](https://insert-koin.io/docs/setup/koin) have separate koin-androidx-compose-navigation which gives a koinNavViewModel() function.

build.gradle.kts

dependencies {

    implementation("androidx.core:core-ktx:1.12.0")

    implementation("io.insert-koin:koin-android:3.4.0")
    implementation("io.insert-koin:koin-androidx-workmanager:3.4.0")
    implementation("io.insert-koin:koin-androidx-compose:3.4.6")
    implementation("io.insert-koin:koin-androidx-compose-navigation:3.4.6")

    implementation(platform("androidx.compose:compose-bom:2023.06.01"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.foundation:foundation")
    implementation("androidx.compose.foundation:foundation-layout")
    implementation("androidx.compose.material:material")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.runtime:runtime")
    implementation("androidx.compose.runtime:runtime-livedata")
    implementation("androidx.compose.ui:ui-tooling")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose")
    implementation("androidx.activity:activity-compose:1.7.0")
    implementation("androidx.lifecycle:lifecycle-runtime-compose:$2.6.2")
    implementation("androidx.navigation:navigation-compose:$2.6.0")

    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test.ext:junit:1.1.5")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.5.1")
    androidTestImplementation(platform("androidx.compose:compose-bom:2023.08.00"))
    androidTestImplementation("androidx.compose.ui:ui-test-junit4")
    debugImplementation("androidx.compose.ui:ui-tooling")
    debugImplementation("androidx.compose.ui:ui-test-manifest")
}
Now I am trying to make a use of One viewmodel to different screens. When I get some data in viewmodel, I stored in SharedFlow and navigate to another screen with same viewmodel instance it gives me variable null.

MainActivity.kt

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            SimpleComposeNavigationTheme {
                SimpleNavigation()
            }
        }
    }
}
SimpleNavigation

@Composable
fun SimpleNavigation(navController: NavHostController = rememberNavController()) {

    NavHost(
        navController = navController,
        startDestination = navController.currentBackStackEntry?.destination?.route ?: "first_screen"
    ) {
        composable("first_screen") {
            val viewModel: FirstViewModel = koinNavViewModel()
            Surface {
                Column(Modifier.fillMaxSize()) {
                    Button(onClick = { viewModel.updateName("Hello world") }) {
                        Text(text = "Add Name")
                    }
                   Button(onClick = {
                        navController.navigate("second_screen") {
                            popUpTo(navController.graph.findStartDestination().id) {
                                saveState = true
                            }
                            // Avoid multiple copies of the same destination when
                            // reselecting the same item
                            launchSingleTop = true
                            // Restore state when reselecting a previously selected item
                            restoreState = true
                        }
                    }) {
                        Text(text = "Next Screen")
                    }
                }
            }
        }
        composable("second_screen") {
            val viewModel: FirstViewModel = koinNavViewModel()
            val firstName by viewModel.firstName.collectAsState()
            LaunchedEffect(firstName){
                println(">> $firstName")
            }
            Surface {
                Column(Modifier.fillMaxSize()) {
                    firstName?.let { name -> Text(text = name) }
                }
            }
        }
    }
}
FirstViewModel.kt

class FirstViewModel : ViewModel() {
    private val _firstName = MutableStateFlow<String?>(null)
    val firstName: StateFlow<String?> = _firstName.asStateFlow()

    fun updateName(name: String) {
        _firstName.value = name
    }
}

**Comment by sanskar-kumar** [comment]
@vivek-modi Did you found a solution to this?
