### ISSUE TITLE
Bring back ViewModelOwner to SharedViewModel in v3

### ISSUE THREAD

**Issue by jkwiecien** [InsertKoinIO/koin#1086]
Looks like it's gone again.

**Comment by arnaudgiuliani** [comment]
It's accessible directly by extension now: 

![image](https://user-images.githubusercontent.com/2360688/119315180-dd9a3b00-bc75-11eb-8178-5b866239ead3.png)

**Comment by cirnoftw** [comment]
But what about usage in child fragments? Before it was possible to have an instance of SharedViewModel in child fragments passing parent's ViewModelOwner to have scoped SharedViewModel istances. Now it's only possible to reference parent's SharedViewModel instance via casting, which is less convenient.
