### ISSUE TITLE
ScopeJVM.kt has no package

### ISSUE THREAD

**Issue by asapha** [InsertKoinIO/koin#1094]
**Describe the bug**
ScopeJVM.kt has no package entry.
When using Java 9 Modules with koin 3.0.1, this error is raised:
```java
java.lang.module.FindException: Unable to derive module descriptor for [...]/koin-core-jvm-3.0.1.jar
Caused by: java.lang.module.InvalidModuleDescriptorException: ScopeJVMKt.class found in top-level directory (unnamed package not allowed in module)
```

**To Reproduce**
Add `requires koin.core.jvm;` to a `module-info.java` file

**Expected behavior**
`ScopeJVM.kt` should probably have `package org.koin.core.scope` .

**Koin project used and used version (please complete the following information):**
`koin-core version 3.0.1`

**Comment by arnaudgiuliani** [comment]
Fixed on master - `9ed06ff50e788e637bacd362daa41d252309b77f`
