### ISSUE TITLE
Missing `io.insert-koin:koin-androidx-ex` & `io.insert-koin:koin-androidx-viewmodel` v3.0.2

### ISSUE THREAD

**Issue by mohsenoid** [InsertKoinIO/koin#1100]
is there going to be a v3.0.2 release for `io.insert-koin:koin-androidx-ex` and `io.insert-koin:koin-androidx-viewmodel` the same as `io.insert-koin:koin-core`?

**Comment by lukasvalkovic** [comment]
Android modules were reduced in [3.0.1](https://medium.com/koin-developers/koin-3-0-1-release-2-x-redeploy-856c2cc6edec) and there is no `koin-androidx-viewmodel` module anymore.

**Comment by richanshah** [comment]
how to resolve this?:

**Comment by lukasvalkovic** [comment]
You need only `koin-android` module(or `koin-android-ex` for experimental extensions). All previous android modules were merged into that.

**Comment by arnaudgiuliani** [comment]
Exact, main stable features (ViewModel, Scope, Fragment) are merged in the main `koin-android` module 👍
