### ISSUE TITLE
Can't resolve koin package org.koin

### ISSUE THREAD

**Issue by bpappin** [InsertKoinIO/koin#1107]
**Describe the bug**
The maven central repository does not have the original package, as described by the koin documentation, and fails the build.

The package as descrived in the setup documentation for 2.2.3 is:
- classpath "org.koin:koin-gradle-plugin:2.2.3"

however that does not resolve. Checking the repository, you find that the version of koin is using the new package for koin 3.
- classpath "io.insert-koin:koin-gradle-plugin:2.2.3"

**Expected behaviour**
The documented package should resolve, so as not to break everyone's code, and match the documentation.

**Comment by bpappin** [comment]
FYI this is what is resolving:

https://search.maven.org/artifact/io.insert-koin/koin-gradle-plugin

**Comment by arnaudgiuliani** [comment]
yep, website is updated
