### ISSUE TITLE
single<> declaration not thread safe

### ISSUE THREAD

**Issue by cesquivias** [InsertKoinIO/koin#1110]
**Describe the bug**
A singleton class I declare using `single<>` that must be only be instantiated once (or else an exception is thrown) is instantiated twice. They are being created on separate threads. One is on the main thread originating from a object being created in the `Application` class while another is created in a worker class via the `koin-androidx-workmanager` project.

**To Reproduce**
1. Declare singleton with `single { Singleton() }` declaration
2. Depend on the singleton with a class that will be instantiated on the main thread that will be created every time the app starts: `single { Main(singleton = get()) }`
3. Depend on the singleton in a Worker class `worker { Worker(singleton = get()) }`
4. Trigger the worker to start

**Expected behavior**
The second thread waits until the first thread is done creating the `single` dependency and uses it.

**Koin project used and used version (please complete the following information):**
`koin-core version 3.0.1`
`koin-core-ext version 3.0.1`
`koin-android version 3.0.1`
`koin-androidx-workmanager version 3.0.1`

**Comment by prfarlow1** [comment]
@arnaudgiuliani what's expected behavior here?
