### ISSUE TITLE
Koin 3.0.2 can't resolve org.koin.androidx.viewmodel.compat 

### ISSUE THREAD

**Issue by AlanChienYL** [InsertKoinIO/koin#1111]
**Describe the bug**

**To Reproduce**
1. migrate from 2.2.2 to 3.0.2
2. Use `viewModel` in java file
3. can't resolve `import static org.koin.androidx.viewmodel.compat.ViewModelCompat.viewModel;`

**Expected behavior**
Resolve `import static org.koin.androidx.viewmodel.compat.ViewModelCompat.viewModel;`
Need this extension in java.

**Koin project used and used version (please complete the following information):**
`io.insert-koin:koin-core:3.0.2`
`io.insert-koin:koin-android:3.0.2`
`io.insert-koin:koin-android-ext:3.0.2`

**Additional moduleDefinition**

Many thanks for your help.

**Comment by arnaudgiuliani** [comment]
it has been moved recently into `koin-android-compat`.
