### ISSUE TITLE
How to inject a viewModel into a Jetpack Compose Preview

### ISSUE THREAD

**Issue by FredericoNoce** [InsertKoinIO/koin#1119]
**Describe the bug**
I need to inject a Viewmodel into a composable function preview.

@Preview
    @Composable
    private fun PreviewHomeContent() {
        MyTheme {
            HomeContent(getViewModel())
        }
    }

java.lang.IllegalStateException: KoinApplication has not been started

@Preview
    @Composable
    private fun PreviewHomeContent() {
        **KoinComponent.initContext(LocalContext.current)**
        MyTheme {
            HomeContent(getViewModel())
        }
    }

**java.lang.IllegalStateException: Your activity is not yet attached to the Application instance. You can't request ViewModel before onCreate call.**

**Koin project used and used version (please complete the following information):**
org.koin:koin-android:2.2.0
org.koin:koin-androidx-viewmodel:2.2.0

**Comment by headsvk** [comment]
Build your compose views in a way so they are testable without relying on view models.
See how Google does it https://developer.android.com/jetpack/compose/state#viewmodel-state
Then they can simply preview `HelloContent` with any parameters.

**Comment by FredericoNoce** [comment]
Cool, I created a composable HomeContent method, in which it receives the viewmodel as a parameter. But he is injected by koin. With that, when I try to use the compose preview he has to "up" the context for him to be able to solve the injection, that would be my problem. @headsvk

**Comment by burnoo** [comment]
I've released a library - cokoin, which supports Koin in `@Preview` . It is an alternative to `org.koin:koin-androidx-compose`.
### [Library Migration Guide](https://github.com/burnoo/cokoin/wiki/Migration-from-org.koin:koin-androidx-compose)
### Cokoin With `@Preview`
Wrap Preview Composable with `@Composable` Koin:
```kotlin
@Composable
fun Hello() {
     val hello = get<Hello>()
     Text(hello.text)
}

val previewModule = module {
     factory { Hello(text = "preview hello text") }
}

@Preview
@Composable
fun HelloPreview() {
    Koin(appDeclaration = { modules(previewModule) }) {
        Hello()
    }
}
```

**Comment by Drjacky** [comment]
@headsvk I've created that extra `BlahContent` to use in the Preview but, the IDE didn't generate the UI.
P.S I use `hiltViewModel()`.
