### ISSUE TITLE
CheckModulesTest fails to resolve dependencies for parameters in version 3.1.0

### ISSUE THREAD

**Issue by pallavijoshi44** [InsertKoinIO/koin#1123]
**Describe the bug**

After upgrading to version 3.1.0, we encountered the following bug in CheckModulesTest listed here : 

While resolving parameters using it.get(), the checkModulesTest fails with the following  error : 

```
org.koin.core.error.BrokenDefinitionException: Definition is broken: [Factory:'com.koin.test.MainActivityViewModel'] 
- due to error: org.koin.core.error.DefinitionParameterException: No value found for type 'java.lang.Boolean'
```
   **To Reproduce**

Inject dependency with parameters like this: 
```
val parameterReceivingClass: ParameterReceivingClass by inject { parametersOf(true) }
```
Provide dependency like this: 
```
factory { ParameterReceivingClass(it.get()) }
```
Class declaration: 
```
class ParameterReceivingClass(isParameterFromFragment: Boolean)

```
Run CheckModulesTest 

Here is the content of the test: 
```
@Category(CheckModuleTest::class)
class CheckModulesTest : KoinTest {

    @Test
    fun checkAllModules() {
        checkModules {
            androidContext(mockk())
            modules(appModule)
        }
        stopKoin()
    }
}
```
**Expected behavior**
The test should pass.

**Koin project used and used version**
`koin-core version 3.1.0`

**Workaround**
By providing the class in the allowedMocks, the test passes. 

```
   @Test
    fun checkAllModules() {
        checkModules(
            allowedMocks = listOf(
                Boolean::class            )
        ) {
            androidContext(mockk())
            modules(appModule)
        }
        stopKoin()
    }
```

After putting the class in the allowed mocks, the test also passes if we miss to provide a parameter while injecting the dependency. For example, it will still pass if we inject the dependency like this (note that I did not provide the parameters here)
```
private val parameterReceivingClass: ParameterReceivingClass by inject()
```
Hence, there are two questions: 

1. Why do we have to provide the classes in the list of allowedMocks? In a bigger project, the list will become very big and difficult to maintain. 
2.  Why does the test still passes instead of failing when the correct dependencies are not provided? 

Thank you for addressing these queries :)

**Comment by arnaudgiuliani** [comment]
CheckModules API reverted in 3.1.1
