### ISSUE TITLE
Not possible to differentiate between order of parameters of same primitive type in version 3.1.0

### ISSUE THREAD

**Issue by pallavijoshi44** [InsertKoinIO/koin#1125]
**Describe the bug**

While resolving parameters of same types using it.get(),  it cannot differentiate at runtime the order of the parameters and provides the last matched value. 

**Steps to reproduce**

Inject dependency with parameters like this:

```
val twoParametersReceivingClass: TwoParametersWithSameTypeReceivingClass by inject { parametersOf(true, false) }
```

Provide dependency like this:

```
factory { TwoParametersWithSameTypeReceivingClass(it.get(), it.get()) }
```
Class declaration

```
class TwoParametersWithSameTypeReceivingClass(private val isFirstParameter: Boolean, private val isSecondParameter: Boolean) 
```
**Expected behavior**

At runtime, the class TwoParametersWithSameTypeReceivingClass should receive the first parameter as true and the second parameter as false. 

**Actual behavior**

At runtime, the class TwoParametersWithSameTypeReceivingClass receives both the parameters as false.

**Koin project used and used version**
koin-core version 3.1.0

Can you please let me know how to avoid this behaviour ? Is the way to retrieve those parameters correct or should there be a different syntax?

**Comment by Antimonit** [comment]
I believe you can use:
```kotlin
factory { TwoParametersWithSameTypeReceivingClass(it[0], it[1]) }
```
or a destructing declaration like
```kotlin
factory { (first: Boolean, second: Boolean) -> TwoParametersWithSameTypeReceivingClass(first, second) }
```

**Comment by pallavijoshi44** [comment]
@Antimonit  Thanks for your response. Indeed, the ways that you mention are working for this scenario. But, destructured declaration is now deprecated - so shoudn't it be fixed properly within the koin framework?

**Comment by arnaudgiuliani** [comment]
destructured declaration is back in 3.1.1, it should help continue with such expression
