### ISSUE TITLE
SavedStateHandle unable to resolve state automatically in version 3.1.0

### ISSUE THREAD

**Issue by pallavijoshi44** [InsertKoinIO/koin#1127]
**Describe the bug**

The savedStateHandle in a state view model should be resolved automatically instead of resolving through the parameter using it.get()

**To Reproduce**
Inject dependency like this: 
````
val savedStateSameTypeReceivingClass: SavedStateSampleViewModel by stateViewModel()
````

Provide dependency like this: 
```
viewModel {  SavedStateSampleViewModel(get()) }
```

Here is the class declaration:
```
class SavedStateSampleViewModel(private val stateHandle: SavedStateHandle) : ViewModel() {
```

Run the CheckModulesTest: 

```

@Category(CheckModuleTest::class)
class CheckModulesTestWithWorkaround : KoinTest {

    @get:Rule
    val mockProvider = MockProviderRule.create { clazz ->
        mockkClass(clazz)
    }

    @Test
    fun checkAllModules() {
        checkModules(
            allowedMocks = listOf(
                androidx.lifecycle.SavedStateHandle::class
            )
        ) {
            androidContext(mockk())
            modules(appModule)
        }
        stopKoin()
    }
}
```
**Expected behavior**
The dependency should be resolved and checkmodules test should pass.  Also, there should ideally be no need of providing the SavedStateHandle in the allowed mocks. 

**Koin project used and used version (please complete the following information):**
`koin-core version 3.1.0`

**Workaround**
By providing the dependency like this, the test passes: 

```
viewModel {  SavedStateSampleViewModel(it.get()) }

````
Hence two questions: 
1. Can we avoid to provide the the SavedStateHandle class in allowed mocks? 
2. How can we resolve the savedStateHandle automatically instead of using it.get() ?

Thanks for addressing the queries.

**Comment by arnaudgiuliani** [comment]
Fixed back in 3.1.1
