### ISSUE TITLE
Koin 3.0.1 is not backward compatible

### ISSUE THREAD

**Issue by perihanmirkelam** [InsertKoinIO/koin#1130]
**Describe the bug**
I'm using two libraries that have dependencies on two different versions of Koin.

One of the library has org.koin:koin-android:2.0.1 and the other has io.insert-koin:koin-android:3.0.1 dependencies.

At compile time I got tons of Duplicate class errors:

<pre><code>Duplicate class org.koin.android.BuildConfig found in modules jetified-koin-android-2.0.1-runtime (org.koin:koin-android:2.0.1) and jetified-koin-android-3.0.1-runtime (io.insert-koin:koin-android:3.0.1)
Duplicate class org.koin.android.ext.koin.KoinExtKt$androidContext$1 found in modules jetified-koin-android-2.0.1-runtime (org.koin:koin-android:2.0.1) and jetified-koin-android-3.0.1-runtime (io.insert-koin:koin-android:3.0.1)
Duplicate class org.koin.core.scope.Scope$injectOrNull$1 found in modules jetified-koin-core-2.0.1 (org.koin:koin-core:2.0.1) and jetified-koin-core-jvm-3.0.1 (io.insert-koin:koin-core-jvm:3.0.1)
Duplicate class org.koin.java.KoinJavaComponent$inject$1 found in modules jetified-koin-core-jvm-3.0.1 (io.insert-koin:koin-core-jvm:3.0.1) and jetified-koin-java-2.0.1 (org.koin:koin-java:2.0.1)
... </code></pre>

When I try to exclude one of them as below,

<pre><code>configurations {
    all { 
        exclude group: "io.insert-koin", module: "koin-android"
        exclude group: "io.insert-koin", module: "koin-core-jvm"
    }
}</code></pre>

<pre><code>configurations {
    all { 
        exclude group: "org.koin", module: "koin-core"
        exclude group: "org.koin", module: "koin-android"
        exclude group: "org.koin", module: "koin-java"
    }
}</code></pre>

Each time, I got NoClassDefFoundError at runtime on the relevant one:

- When excluding Koin 2.0.1 (org.koin)

<pre><code>Caused by: java.lang.ClassNotFoundException: Didn't find class "org.koin.core.KoinComponent" on path: DexPathList[[zip file "/data/app/...</code></pre>

- When excluding Koin 3.0.1 (io.insert-koin)

<pre><code>Caused by: java.lang.ClassNotFoundException: Didn't find class "org.koin.core.component.KoinComponent" on path: DexPathList[[zip file "/data/app/...</code></pre>

As you see above, **the path of the KoinComponent has changed** like
**org.koin.core.KoinComponent** -> **org.koin.core.component.KoinComponent**
In this case, how can I use both libraries while I can not use both versions of Koin at runtime?

**To Reproduce**
Create a project
Implement [AirWatch SDK](https://github.com/vmware-samples/workspace-ONE-SDK-integration-samples/blob/main/IntegrationGuideForAndroid/Guides/03BaseIntegration/WorkspaceONE_Android_BaseIntegration.md) (or any library that has Koin 2.0.1 dependency)
Implement [Netmera Library](https://developer.netmera.com/en/Android/quick-start) (or any library that has Koin 3.0.1 dependency)
Rebuild project
Many "Duplicate class" errors will appear
Try to exclude Koin 2.0.1 
<pre><code>configurations {
        all { 
            exclude group: "org.koin", module: "koin-android"
            ...
        }
    } </code></pre>
Then run project on a device
NoClassDefFoundError will appeared when app crashed.

**Expected behavior**
I would expect the ClassNotFoundException error to not occur when excluding org.koin:koin-android:2.0.1. 
I mean, I would expect Koin 3.0.1 to work compatible with the library that implements Koin 2.0.1.

**Koin project used and used version:**
 `koin-core version 2.0.1` and `koin-core version 3.0.1`

**Comment by pedrofsn** [comment]
I'm facing same problem too with other libraries.

**Comment by pedrofsn** [comment]
Sadly, it's true. I upgraded koin version inside libraries to match same version on application, the problem mentioned here was solved.
