### ISSUE TITLE
savedStateHandled of stateViewModel has no intent extra

### ISSUE THREAD

**Issue by yoonah5959** [InsertKoinIO/koin#1140]
**Describe the bug**

  ```kotlin

//in Activity, 
viewModel = getStateViewModel()

//in module
 viewModel { ScheduleViewModel(get(), get()) }

class ScheduleViewModel(
    private val repository: Repository,
    private val savedStateHandle: SavedStateHandle
) : BaseViewModel() {

    init {
        val id: Int? = savedStateHandle.get(EXTRA_SCHEDULE_ID)
    }
}
```
id is always null.
savedStateHandle was created but has no intent extra 
Did I do something wrong? 
I used savedSateHandle with hilt. But It worked well.
I want to use savedSateHandle with koin. 

**Gradle stuff** 
  kotlin_version = '1.4.32'
  koin_version= "3.1.2"
    // Koin
   api "io.insert-koin:koin-core:$koin_version"
   api "io.insert-koin:koin-test:$koin_version"
   api "io.insert-koin:koin-test-junit4:$koin_version"
   api "io.insert-koin:koin-test-junit5:$koin_version"
   api "io.insert-koin:koin-android:$koin_version"
   api "io.insert-koin:koin-android-compat:$koin_version"

**Comment by tamashalcyon** [comment]
stateViewModel seems not to work for me neither in version 3.1.2. I'm using the delegate: `by stateViewModel`. The stateHandle received in the VM seems empty every time.

**Comment by hotmule** [comment]
I have similar problem with injecting SavedStateHandle into SampleViewModel, which inherited from abstract BaseViewModel, app crashes with org.koin.core.error.InstanceCreationException, SampleViewModel, inherited from standard ViewModel works fine

**Comment by rolfwessels** [comment]
Having the same issue. Expected SavedStateHandle based on NavController route parameters being set. 

I ended up using the following workaround (hope it help someone).

```kotlin
// in module
viewModel { (bundle : Bundle) ->  DetailViewModel(bundle) }
// in Activity, 
val vm: DetailViewModel =  getViewModel(parameters = { parametersOf(navController.currentBackStackEntry?.arguments) })
// Changed the SavedStateHandle to a bundle
class DetailViewModel(arguments: Bundle) : ViewModel() {
```

**Comment by StephanSchuster** [comment]
Same problem here with Jetpack Compose. Not sure if it's a bug or if I am missing something.

```
val myModule = module {
    viewModel { MyViewModel(get()) }
}

class MyViewModel(
    private val savedState: SavedStateHandle
) : ViewModel() {

   private fun loadMyEnum() =
        savedState.get<MyEnum>("myEnum") ?: MyEnum.VALUE_X

    private fun storeMyEnum(myEnum: MyEnum) =
        savedState.set("myEnum", myEnum)

    ...
}

@Composable
fun MyComposable(viewModel: MyViewModel = getStateViewModel()) {
    ...
}

<activity android:name=".MainActivity"  ...  android:stateNotNeeded="false" />
```

With a debugger attached, I see that during runtime the savedState/myEnum changed successfully. But on restart  `loadMyEnum()` always returns null/VALUE_X.

Not sure if I am using this correctly. Do I need to pass something to `getStateViewModel(state = ...)` in my composable? Is the default `emptyState()` my problem? If yes, how do I pass the correct state here in Compose?

```
@Composable
inline fun <reified T : ViewModel> getStateViewModel(
    qualifier: Qualifier? = null,
    noinline state: BundleDefinition = emptyState(),
    noinline parameters: ParametersDefinition? = null,
): T {
    val owner = LocalSavedStateRegistryOwner.current
    return remember(qualifier,parameters) {
        owner.getStateViewModel(qualifier, state, parameters)
    }
}
```

**Comment by StephanSchuster** [comment]
Still there with compose 1.1.0-beta02 and koin 3.1.3

@arnaudgiuliani: Would it be possible for you to quickly check if I am doing something wrong or if this is really related to a bug in Koin.

**Comment by pynnie** [comment]
works now with version 3.4.0

**Comment by manan-singhal2407** [comment]
Hi @pynnie, I am still getting null values only with $koin_version = 3.4.0.
Can you share the code that is giving you values using savedStateHandle in ViewModel?

Or anyone have any idea how to get arguments value in ViewModel using Koin as DI?
