### ISSUE TITLE
Trying to get a simple viewModel injection to work on Jetpack compose 1.0.0 Beta 09

### ISSUE THREAD

**Issue by sismith999** [InsertKoinIO/koin#1145]
**Describe the bug**
Trying to get a simple viewModel injection to work on Jetpack compose 1.0.0 Beta 09
but crashes with 
No interface method startReplaceableGroup(ILjava/lang/String;)V in class Landroidx/compose/runtime/Composer;

**To Reproduce**
package com.example.kointest

import android.app.Application
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.material.MaterialTheme
import androidx.compose.material.Surface
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.tooling.preview.Preview
import androidx.lifecycle.ViewModel
import com.example.kointest.ui.theme.KoinTestTheme
import org.koin.androidx.compose.getViewModel
import org.koin.androidx.viewmodel.dsl.viewModel
import org.koin.core.context.startKoin
import org.koin.dsl.module

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            KoinTestTheme {
                // A surface container using the 'background' color from the theme
                Surface(color = MaterialTheme.colors.background) {
                    Greeting("Android")
                }
            }
        }
    }
}
@Composable
fun Greeting(name: String) {
    val vm = getViewModel<ExampleViewModel>()
    Text(text = "Hello $name!")
}
@Preview(showBackground = true)
@Composable
fun DefaultPreview() {
    KoinTestTheme {
        Greeting("Android")
    }
}

class ExampleViewModel : ViewModel()
class KoinTest : Application() { //Added custom application startup for eth but handy for initializing, also need to add in manifest this name.
    override fun onCreate() {
        super.onCreate()
        startKoin {
            modules(
                module {
                    viewModel { ExampleViewModel() }
                }
            )
        }
    }
}

**Koin project used and used version (please complete the following information):**
    def koin_version= "3.1.1"  //  koin_version = '3.0.1'
    // Koin main features for Android (Scope,ViewModel ...)
    implementation "io.insert-koin:koin-android:$koin_version"
    // Koin Android - experimental builder extensions
    //implementation "io.insert-koin:koin-android-ext:$koin_version"
    // Koin for Jetpack WorkManager
    implementation "io.insert-koin:koin-androidx-workmanager:$koin_version"
    // Koin for Jetpack Compose (unstable version)
    implementation "io.insert-koin:koin-androidx-compose:$koin_version"

**Comment by leomarques** [comment]
same happens to me, tried on compose 1.0.0-rc02

**Comment by leomarques** [comment]
I'm using it like this for now:
```
val repository: Repository = get()
val homeViewModel = remember { HomeViewModel(repository) }
```

**Comment by cleemansen** [comment]
Also crashing with `androidx.compose.ui:ui:1.0.1` in combination with `io.insert-koin:koin-androidx-compose:3.1.2`.
