### ISSUE TITLE
androidx-compose  example can't build

### ISSUE THREAD

**Issue by vitaviva** [InsertKoinIO/koin#1148]
**Is your feature request related to a problem? Please describe.**
The current androidx-compose example has build error cause some APIs used in example out of date with the latest version of compose. 

**Describe the solution you'd like**
After updating the APIs, although the compilation passed, there was an error at runtime. And it needs to upgrade the dependency library version of Koin-androidx-compose：

lifecycle-viewmodel-compose: 1.0.0-alpha02 => 1.0.0-alpha07

**Comment by mochadwi** [comment]
does it still occurred in the latest version?
