### ISSUE TITLE
Error with KoinJavaComponent

### ISSUE THREAD

**Issue by pedrofsn** [InsertKoinIO/koin#1153]
I'm getting error with KoinJavaComponent in Java classes when I build project.
Using import `import org.koin.java.KoinJavaComponent;` and koin in version `3.1.2`.

Eg.: `Storage storage = KoinJavaComponent.inject(Storage.class).getValue();`
Error: 

> error: incompatible types: Object cannot be converted to Storage
        Storage storage = KoinJavaComponent.inject(Storage.class).getValue();
                                                                          ^

**Comment by prfarlow1** [comment]
@pedrofsn did you solve this by casting the result of the call to `Storage`? Running into the same issue with `KoinJavaComponent.get()`.
