### ISSUE TITLE
Failed to resolve: io.insert-koin:koin-android-viewmodel:3.1.2

### ISSUE THREAD

**Issue by hoangduchuu** [InsertKoinIO/koin#1158]
**Describe the bug**
Get the failed when sync gradle
**To Reproduce**

Build with this dependency
https://gist.github.com/hoangduchuu/c0f0a4ce92dbd300d9e6f1b587e33445

`Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find io.insert-koin:koin-android-viewmodel:3.1.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/insert-koin/koin-android-viewmodel/3.1.2/koin-android-viewmodel-3.1.2.pom
       - https://jcenter.bintray.com/io/insert-koin/koin-android-viewmodel/3.1.2/koin-android-viewmodel-3.1.2.pom
       - https://repo.maven.apache.org/maven2/io/insert-koin/koin-android-viewmodel/3.1.2/koin-android-viewmodel-3.1.2.pom
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

`

**Expected behavior**
Failed to resolve: io.insert-koin:koin-android-viewmodel:3.1.2

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core version 3.1.2`

**Comment by Dohmanlechx** [comment]
Same problem here. Bumped the Koin version and this error occurred.
`Could not find io.insert-koin:koin-android-viewmodel:3.1.2.`

**Comment by Dohmanlechx** [comment]
Solved it, the dependency was actually not needed - it was already merged in the `koin-android` dependency.

See this for reference:
https://github.com/InsertKoinIO/koin/issues/1100
