### ISSUE TITLE
Autoresolve for constructor to avoid boilerplate

### ISSUE THREAD

**Issue by krottv** [InsertKoinIO/koin#1159]
**Is your feature request related to a problem? Please describe.**
It is frustrating when you have a lot of this: 
```
factory {
     FreeWeeklyTemplatesNotificationManager(get(), get(), get(), get(), get())
}
```

**Describe the solution you'd like**
IOS DI framework swinject has a nice solution - https://github.com/Swinject/SwinjectAutoregistration
It would look like:
`factoryAutoregister(FreeWeeklyTemplatesNotificationManager::class)`

**Comment by wujek-srujek** [comment]
Isn't this what you are after? https://insert-koin.io/docs/reference/koin-core/dsl-update

**Comment by krottv** [comment]
@wujek-srujek Yes. The only thing is that I would like to have codegen solution instead of reflection.

**Comment by wujek-srujek** [comment]
True that, but I read somewhere that it will come when Koin starts using KSP (can't remember where I saw it, but I think it was a comment by one of the maintainers of Koin).

**Comment by arnaudgiuliani** [comment]
yep, KSP Compiler is coming. Also better DSL improvements
