### ISSUE TITLE
how do I set ViewModelOwnerDefinition for the owner param when injecting viewModel

### ISSUE THREAD

**Issue by radekstasiak** [InsertKoinIO/koin#1161]
Hi,

Im trying to inject viewModel() for my custom scope shared between fragments. Got to the point where Im trying to run
` by fragmentScope.viewModel(owner = ViewModelOwner.from(findNavController().getViewModelStoreOwner(R.navigation.train_navigation)))`

however this won't compile as owner suppose to be ViewModelOwnerDefinition, but Im struggling to create one. Could you help me with that?

using Koin for Android v3.1.2
and kotlin 1.5.21

**Comment by aadityapaliwal94** [comment]
Same issues with koin v.3.1.3

**Comment by aadityapaliwal94** [comment]
I tried below and it seems fix to me - 

> 	val owner = findNavController().getViewModelStoreOwner(navGraphId)
	val ownerDefination : ViewModelOwnerDefinition = { ViewModelOwner.from(owner) }
