### ISSUE TITLE
Koin Compose Viewmodel is not usable with latest Android Compose Navigation version Viewmodel instance not retained.

### ISSUE THREAD

**Issue by raghavpai** [InsertKoinIO/koin#1163]
**Describe the bug**
Koin Compose Viewmodel is not usable with latest Android Compose Navigation version Viewmodel instance not retained.

**Expected behavior**
Viewmodel instance should persist during recomposition
**Koin project used and used version (please complete the following information):**
All versions of koin compose viewmodel

**Comment by leungandrew** [comment]
I can reproduce the issue as above.  When using Compose Navigation, I can see that everytime `getViewModel()` is called, it is returning a brand new instance of the ViewModel.

```
@Composable
fun MyComponent(viewModel: MyViewModel = getViewModel()) {
  val state = viewModel.someLiveData.observeAsState() // This live data is a new instance each time this composable is instantiated (due to viewModel being reinstantiated each time)
}
```

`getViewModel()` in the function param always returns a new instance of the view model WHEN this Composable is within a NavHost.

I vaguely remember before in Koin Compose the library had issues when injecting in regular Jetpack Navigation before, and I imagine the current bug is similar in nature but with respect to Jetpack Compose Navigation.

**Comment by carterhudson** [comment]
This is a pretty big issue. Kind of defeats the purpose of using Koin for ViewModels.
