### ISSUE TITLE
Add new inject way (without `get()`) into tutorial docs

### ISSUE THREAD

**Issue by wiryadev** [InsertKoinIO/koin#1168]
**Is your feature request related to a problem? Please describe.**
Not a technical problem/issue.

**Describe the solution you'd like**
Add [this way](https://twitter.com/insertkoin_io/status/1403333736092123137?s=20) of doing injection inside docs tutorial section in addition of traditional `get()`. Currently this only exists in [DSL 3.1.x updates](https://insert-koin.io/docs/reference/koin-core/dsl-update) section. I think it would be nice to be able to see this new approach right in the quickstart.

![image](https://user-images.githubusercontent.com/26060382/129336083-88f7481e-321e-46d7-a9b2-394a8c343bde.png)

**Comment by arnaudgiuliani** [comment]
Yes, let's see what's coming with KSP and others DSL improvements. Starters need an update yep 👍

**Comment by arnaudgiuliani** [comment]
Koin annotations project is started - https://github.com/InsertKoinIO/koin-annotations
Also new DSL has been updated with `singleOf` ... operators

**Comment by arnaudgiuliani** [comment]
Will check getting started to add use of new DSL

**Comment by wiryadev** [comment]
> Koin annotations project is started - https://github.com/InsertKoinIO/koin-annotations Also new DSL has been updated with `singleOf` ... operators

Looking forward to that, been teased since you showed it in droidcon iirc
