### ISSUE TITLE
Shared ViewModel when using Jetpack Compose + Navigation Component

### ISSUE THREAD

**Issue by hortobagyibalazs** [InsertKoinIO/koin#1174]
I'm having trouble implementing a master-detail flow for my Android application. There's 'Screen A' where I have a list which takes the user to 'Screen B' upon clicking a list item. When I navigate to 'Screen B' I have to pass a complex object that can't be put into a bundle. 'Screen B' has a bunch of UI controls that lets that user make changes to the object represented as the list item. When the user navigates back to 'Screen A', these changes have to visible there too.

My first idea was to create a ViewModel for each screen and inject the second one into the first one:

```

class ScreenAViewModel(
    val navigateToScreenB: () -> Unit,
    val screenBViewModel: ScreenBViewModel
) : ViewModel() {
  val listDataFlow: StateFlow<List<SuperComplexData>> = ...

  init {
      viewModelScope.launch {
          screenBViewModel.editingItem.collect {
              // Item update propagated to master view, update list to reflect changes
          }
      }
  }

  fun onListItemClick(index: Int) {
      screenBViewModel.editingItem = ...
      navigateToScreenB()
  }
}

class ScreenBViewModel(
    val navigateBack: () -> Unit
) : ViewModel() {
    val editingItem: MutableStateFlow<SuperComplexData> = ...

    fun updateItemInfoInSomeWay() {
        editingItem.value = ...
    }
}

```
The I implemented the navigation part this way:

```
// NavGraphBuilder.composable for 'Screen A'
this.composable(
   route = ...,
   content = {
       val screenBViewModel = getViewModel<ScrenBViewModel() { parametersOf({...} } )
       val viewModel = getViewModel<ScreenAViewModel>() { parametersOf(
           {/**Navigate to Screen B*/},
           screenBViewModel
       )}

       ScreenAContent(viewModel)
   }
)

// NavGraphBuilder.composable for 'Screen B'
this.composable(
   route = ...,
   content = {
       val viewModel = getViewModel<ScreenBViewModel>() { parametersOf({...})}
       ScreenBContent(viewModel)
   }
)


```
What happened of course was that 'ScreenAViewModel' and 'ScreenB' had instances of 'ScreenBViewModel' that were completely unrelated. But I want 'ScreenBViewModel' to be associated with the "parent" 'ScreenAViewModel'. Is there a way to achieve what I want with Koin?

**Comment by wujek-srujek** [comment]
What we did is:

```kotlin
inline fun <reified VM : ViewModel> NavController.routeViewModel(
    route: String? = null,
    qualifier: Qualifier? = null,
    noinline parameters: ParametersDefinition? = null,
): VM {
    val owner = if (route != null)
        getBackStackEntry(route)
    else
        currentBackStackEntry!!

    return owner.getViewModel(
        qualifier,
        parameters,
    )
}
```

You use it like this (somewhere in the navigation graph builder):

```kotlin
val viewModel: MyViewModel = remember { navController.routeViewModel() }
```
or
```kotlin
val viewModel: MyViewModel = remember { navController.routeViewModel("someRouteOnTheStack") }
```
It also supports qualifiers and parameters.

Does this help?

**Comment by MarcelReiter** [comment]
Not related to koin, but to your original issue:
Best practice would be the following:

- make sure `SuperComplexData` has an id
- use a repository or similar to hold `Flow<List<SuperComplexData>>`
- ScreenA displays that flow. On click, you launch ScreenB & add id as a parameter via compose navigation
- ScreenB uses the id to query the repository for `SuperComplexData`
