### ISSUE TITLE
Support apple silicon for koin multiplatform

### ISSUE THREAD

**Issue by micHar** [InsertKoinIO/koin#1179]
**Is your feature request related to a problem? Please describe.**
Kotlin 1.5.30 brings support for apple silicon, e.g. `iosSimulatorArm64` targets. Every library used by the project needs to be compatible, otherwise the target will not compile. 

**Describe the solution you'd like**
A similar solution may be found in other libs, e.g. https://github.com/touchlab/Stately/commit/ee92f8f5cafce50fc7be18930e06dc8910ff1229. It should not be much harder than updating kotlin to 1.5.30 and adding new native targets to https://github.com/InsertKoinIO/koin/blob/master/core/koin-core/build.gradle.

**Target Koin project**
koin-core

**Comment by batuypn** [comment]
+1

**Comment by Benoye** [comment]
+1

**Comment by micHar** [comment]
Seems to be contributed here https://github.com/InsertKoinIO/koin/pull/1192/files. And afaiu, should be added soon https://kotlinlang.slack.com/archives/CRF31N2HW/p1635503245007300?thread_ts=1633420278.023500&cid=CRF31N2HW

**Comment by Reedyuk** [comment]
Its not appearing in maven central, any ETA when this will?
https://mvnrepository.com/artifact/io.insert-koin?p=3
