### ISSUE TITLE
 To deal with lifecycle problem,How to use  "by viewModel()" In koin V3.x   just like " val viewModel: LoginViewModel by viewModel()" in koin-V2.x

### ISSUE THREAD

**Issue by elyding** [InsertKoinIO/koin#1182]
How to use  "by viewModel()" In koin V3.x   just like " val viewModel: LoginViewModel by viewModel()"
to deal with lifecycle problem

In koin-V3.x  Reports error on using "by viewModel()

 i can't find   the extension : androidx.activity.ComponentActivity.viewModel which in koin V2.x

(1) In koin-V2.x  ,The "by viewModel()"  exists in the org.koin:koin-androidx-viewmodel -> ext.android.ActivityExtKt.class 
As below 
inline fun <reified T : ViewModel> ComponentActivity.viewModel(
        qualifier: Qualifier? = null,
        noinline state: BundleDefinition? = null,
        noinline owner: ViewModelOwnerDefinition = { from(this, this) },
        noinline parameters: ParametersDefinition? = null,
): Lazy<T> {
    return lazy(LazyThreadSafetyMode.NONE) {
        getViewModel(qualifier, state, owner, parameters)
    }
}

(2) I know  that koin-androidx-fragment, koin-androidx-viewmodel or koin-androidx-scope  are all merged  into koin-android module in koin-V3.x

(3) In my module build.gradle i wrote the "implementation io.insert-koin:koin-android:3.1.2"  

But, unresolved  "viewModel()"

How to use "by viewModel()" in  koin V3.x    . Thanks a lot

**Comment by philos3** [comment]
had you solve this problem
