### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method makeOptions(ZZ)Lorg/koin/core/definition/Options; in class Lorg/koin/core/module/Module; or its super classes (declaration of 'org.koin.core.module.Module' appears in /data/app/~~

### ISSUE THREAD

**Issue by kaizer1** [InsertKoinIO/koin#1183]
**Describe the bug**
I am rewriting the old implementation of the coin to the new version : 

    implementation "io.insert-koin:koin-core:3.1.2"
    implementation "io.insert-koin:koin-core-ext:2.2.3"
    testImplementation "io.insert-koin:koin-test:3.1.2"
    //implementation "io.insert-koin:koin-androidx-scope:2.2.3"
    implementation "io.insert-koin:koin-androidx-viewmodel:2.2.3" 

at startup, I called this function and everything started and work fine 

 fun Application.startDi() = startKoin(
    androidContext = this,
    modules = listOf(module()),
    logger = EmptyLogger()
) 

but after updating the entire project (including gradle and so on) :
      startKoin{
            androidLogger(Level.ERROR)
            androidContext(this@App)
           modules(myModule())
        }

This error began to appear : 
       java.lang.NoSuchMethodError: No virtual method makeOptions(ZZ)Lorg/koin/core/definition/Options; in class Lorg/koin/core/module/Module; or its super classes (declaration of 'org.koin.core.module.Module' appears in /data/app/~~mvG--Yu0RYl7MBIjMag6mg==/com.github.gpspilot-DogV4sPkOJlRqkfL_1AgLQ==/base.apk!classes7.dex)
        at org.koin.android.ext.koin.KoinExtKt$androidContext$1.invoke(KoinExt.kt:109)
        at org.koin.android.ext.koin.KoinExtKt$androidContext$1.invoke(KoinExt.kt:57)

Who can tell you what the problem is or how to solve it? Thank you in advance

**Comment by bpappin** [comment]
I'm having a similar issue, and I have an even simpler setup.

Running on jdk 17+
Dependencies using Maven:

I have version 3.1.3 throughout. 
- koin-core
- koin-core-jvm
- koin-core-test

Exception is:

Exception in thread "main" java.lang.NoSuchMethodError: 'org.koin.core.definition.Options org.koin.core.module.Module.makeOptions(boolean, boolean)'
	at panacea.service.KoinModulesKt$repositoryModules$1.invoke(KoinModules.kt:31)
	at panacea.service.KoinModulesKt$repositoryModules$1.invoke(KoinModules.kt:14)
	at org.koin.dsl.ModuleKt.module(Module.kt:31)
	at org.koin.dsl.ModuleKt.module$default(Module.kt:29)
	at panacea.service.KoinModulesKt.<clinit>(KoinModules.kt:14)
	
Calling code looks like:
```
 startKoin {
            // use Koin logger
            printLogger()
            // declare modules
            modules(repositoryModules)
        }
```

**Comment by bpappin** [comment]
Another clue, although I have the version set to 3.1.3 throughout my project in maven, when I click through on the source the source loads from 3.0.1, which *does* appear have the missing function (signature maybe different).

It turns out that intelliJ was overriding the version with its own copy someone through a different classpath mechanism.

**Comment by boylenssen** [comment]
I had the same error and then I took a closer look and wasn't importing this one:

implementation "io.insert-koin:koin-android:$koin_version"
