### ISSUE TITLE
Auto resolve constructors with no reflection

### ISSUE THREAD

**Issue by marcellogalhardo** [InsertKoinIO/koin#1185]
**Is your feature request related to a problem? Please describe.**
I started to work last week as a consultant on a project which is 2 years old and was built with Koin. The project is relatively big and has tons of bindings, modules, and `get` method. I believe the current API to resolve dependencies is not very maintainable and has a lor of boilerplate. Any constructor change means we also need to change a binding. We can do better, auto resolving an instance by leveraging Kotlin's compiler.

**Describe the solution you'd like**
By combining `reified` with constructor reference we can come up with a solution for the `get` without using reflection (which isn't a good option for Android). I would even argue that it makes completely redundant the reflection solution.

That is how it looks like today:

```kotlin
val myModule = module {
    viewModel {
        MyViewModel(
            dep1 = get(),
            dep2 = get(),
            dep3 = get(),
            dep4 = get()
        )
    }
```

And here is how it can look like:

```kotlin
val myModule = module {
    viewModel { resolve(::MyViewModel) }
}
```

The main advantages here are:
1. No need to boilerplate with `get()` functions.
2. No reflection, resolved at compile time.
3. Adding new parameters to a class does not require changing bindings.
4. Easy to find your bindings (search for `resolve(::YourDependency)`).
5. Compact, straightforward, and optional.

The code to make it work is very simple (I have been using it locally without issues):

```kotlin
inline fun <reified R, reified T1> Scope.resolve(
    constructor: (T1) -> R,
): R = constructor(get())

inline fun <reified R, reified T1, reified T2> Scope.resolve(
    constructor: (T1, T2) -> R,
): R = constructor(get(), get())

// other versions of it, up to 20 parameters.
```

Side-note: suggestions for the `resolve` function name are welcomed.

@arnaudgiuliani if you agree, I already submitted a PR with the changes - it is very straightforward.

Thank you.

**Comment by wiryadev** [comment]
I think Koin is making separate things for compile-time-injection in others project which can be found [here](https://github.com/InsertKoinIO/koin-compiler-playground).

**Comment by marcellogalhardo** [comment]
Hey, thank you for your feedback.

I don't know a lot about the compile time injection project, but reading the link you sent, I believe the proposal here is an alternative to the current reflection API Koin offers today by using inline functions at compile time instead - but it does not really generate code like the compile time injection project.

**Comment by arnaudgiuliani** [comment]
I close this ticket, as the proposal is evolving in PR
