### ISSUE TITLE
Overriding component on module throws `DefinitionOverrideException`

### ISSUE THREAD

**Issue by Whathecode** [InsertKoinIO/koin#1189]
**Is your feature request related to a problem? Please describe.**
I recently upgraded to a new version of Koin. One of the [introduced API changes after 3.1.0 is the removal of `override`](https://insert-koin.io/docs/reference/koin-core/modules#overriding-definition-or-module-before-310). These changes were seemingly made [in the "wip clean API" commit](https://github.com/InsertKoinIO/koin/commit/2b56f9edcae3341413747858c631fd6b12d89aba).

Upgrading for the most part was easy: just removing `override = true` from various calls. However, in one location a component was being overridden within a module, as opposed to one module overriding some components defined in another module. Since the API update, this is no longer supported (since the `override` option is no longer there), [and this will result in a `DefinitionOverrideException`](https://github.com/InsertKoinIO/koin/blob/master/core/koin-core/src/commonMain/kotlin/org/koin/core/module/Module.kt#L89).

**Describe the solution you'd like**
At first, I thought this was a bug, given that my understanding was override was enabled by default now. But, I soon realized that's only the case within the scope of `KoinApplication`. Then, I thought possibly this behavior is by design, i.e., override is not supported within a module, but this seems undocumented.

Furthermore, what would the rationale be behind such a design? Seemingly a module is mutable and additional modules can be added after it's creation; the DSL seems mostly syntactic sugar and is not something akin to a builder pattern of immutable objects, which I expected it to be at first. If module is mutable, why not allow overriding components?

**Describe alternatives you've considered**
I currently override simply by defining two separate modules and load both. This works. This is more a question about API intent/clarity. I'd expect either `Module` to be mutable (to protect from potential race conditions, ensure the library works as intended, etc.), or to support `override` on a module level.

**Target Koin project**: 3.1.2

**Comment by arnaudgiuliani** [comment]
did you tried `includes` function to incmlude other modules and avoid unwanted overrides?
