### ISSUE TITLE
Using Koin for android tests

### ISSUE THREAD

**Issue by AntoineJaury** [InsertKoinIO/koin#119]
Searching for a solution to mock one of my repositories used as a Koin Module for instrumented tests, I finally found a way to mock it.

If you want to mock one of the Koin Modules for your instrumented test, you need to call the `loadKoinModules` method passing it a list of Koin Modules you want to override. 

The problem here is that if the Koin Module you want override is already injected inside the components you want to test, then the `loadKoinModules` won't have any effect on these components. So you have to make sure the Koin Module is not injected in your components before mocking it. 

A workaround I found is to override the `ActivityTestRule` you defined in your test class and to mock your Koin Module during the `beforeActivityLaunched`of the `ActivityTestRule`.

This way, the Koin module will be mocked before activity is launched. As the module was injected once the Activity was created in my side, this solved the problem.

Here is my Test class including this solution:
```
@RunWith(AndroidJUnit4::class)
class LoginTest {

    val mockedUserRepository = Mockito.mock(UserDataSource::class.java)

    @Rule
    @JvmField
    val rule = object: ActivityTestRule<LoginActivity>(LoginActivity::class.java) {
        override fun beforeActivityLaunched() {
            super.beforeActivityLaunched()

            // This will replace the UserDataSource module previously defined 
            // in the Application class creation before the activity is launched
            // Otherwise ... components won't be reloaded
            val mockedUserModule = applicationContext {
                bean { mockedUserRepository as UserDataSource }
            }
            loadKoinModules(listOf(mockedUserModule))
        }
    }
   
   @Test
   fun loginWithUnactivatedAccount() {
        // Here the new module is loaded with all application components
        // and you can interact with the mockedUserRepository 
        ... 
   }
}
```

It would be great to have such example inside the documentation :)

**Comment by patrice-conil** [comment]
Hi all,
I confirm that testing activity is a pain when we need to inject mock instances.
I think that an @MockBean annotation as in spring would be of great help. 
In spring this annotation replaces the corresponding bean by the annotated mock.
This simplify greatly the test writing.
Patrice

**Comment by arnaudgiuliani** [comment]
Hi @patrice-conil,

could be interesting to tell to Koin that we want mocks for given types 👍

**Comment by arnaudgiuliani** [comment]
In the snippet above, we can replace the snippet:

```
val mockedUserRepository = Mockito.mock(UserDataSource::class.java)

    @Rule
    @JvmField
    val rule = object: ActivityTestRule<LoginActivity>(LoginActivity::class.java) {
        override fun beforeActivityLaunched() {
            super.beforeActivityLaunched()

            // This will replace the UserDataSource module previously defined 
            // in the Application class creation before the activity is launched
            // Otherwise ... components won't be reloaded
            val mockedUserModule = applicationContext {
                bean { mockedUserRepository as UserDataSource }
            }
            loadKoinModules(listOf(mockedUserModule))
        }
    }
```

with:

```
 val rule = object: ActivityTestRule<LoginActivity>(LoginActivity::class.java) {
        override fun beforeActivityLaunched() {
            super.beforeActivityLaunched()

            // This will replace the UserDataSource module previously defined 
            // in the Application class creation before the activity is launched
           createMock<UserDataSource>()
        }
    }
```

I've just added `createMock()` function in `koin-test`

**Comment by arnaudgiuliani** [comment]
Check https://github.com/Ekito/koin/issues/151

**Comment by po10cio** [comment]
Can not see the createMock() function in koin test

**Comment by arnaudgiuliani** [comment]
Sorry, it's has been renamed `declareMock` (createMock was conflicting with other API).
