### ISSUE TITLE
Pass koinAppDeclaration to checkKoinModules

### ISSUE THREAD

**Issue by cho0o0** [InsertKoinIO/koin#1194]
**Is your feature request related to a problem? Please describe.**
Since 3.1.3, `checkModules` [is deprecated](https://github.com/InsertKoinIO/koin/blob/master/core/koin-test/src/commonMain/kotlin/org/koin/test/check/CheckModules.kt#L42) in favor of `checkKoinModules`. But I noticed that `checkKoinModules` always [uses `null`](https://github.com/InsertKoinIO/koin/blob/db6b9ff9166e926b400570dd0e1c8bdfa6cf0a67/core/koin-test/src/commonMain/kotlin/org/koin/test/check/CheckModules.kt#L50) as its KoinAppDeclaration. It seems to be difficult to configure the settings before checking the modules. For instance, I use the code below to setup environment variables since they are required in the module definition.

```kotlin
    @Test
    fun checkAppModules() = checkModules {
        fileProperties("/test.properties")
        modules(modules)
    }
```

**Describe the solution you'd like**
Allowing `KoinAppDeclaration` being passed as an argument in `checkKoinModules` maybe a straightforward solution.

**Describe alternatives you've considered**
I've no idea. But if there is any workaround to solve the problem, maybe no changes are required.

**Target Koin project**
koin-test

**Comment by arnaudgiuliani** [comment]
let me update some stuff to help
