### ISSUE TITLE
Module Grouping

### ISSUE THREAD

**Issue by marcellogalhardo** [InsertKoinIO/koin#1196]
**Is your feature request related to a problem? Please describe.**

When working on large projects, you normally have a nested package structure. Ideally, instead of having a single module that provides all dependencies, it would be nice to "compose" those modules into a single one.

Today you can do that by creating a list of modules, and connecting it in the "start Koin".

```kotlin
startKoin {
    modules(featureModule1 + featureModule2 + anotherModule)
}

val moduleCollection1 = listOf(featureDomainModule, featureDataModule, featurePresentationModule)

private featureDomainModule = module {}
private featureDataModule = module {}
private featurePresentationModule = module {}
```

The solution has some problems:
1. If you have multiple collections, you need to use the sum operator which will create a lot of unnecessary new lists behind the scenes.
2. If you have a collection of modules and singular modules, you need to concatenate those.
3. Add one by one in a larger project can easily become disorganized with developers choosing different approaches.

**Describe the solution you'd like**

It would be nice to have built-in support from within the Koin library. It would look somehow like the following:

```kotlin
startKoin {
    modules(featureModule, featureModule2)
}

// Only exposed module, connected to `startKoin`
val featureModule = module {
    includes(featureDomainModule, featureDataModule, featurePresentationModule)
    // another name might be "dependsOn"
}

private featureDomainModule = module {}
private featureDataModule = module {}
private featurePresentationModule = module {}
```

The implementation idea here is that Koin would "automatically plug" all modules that are included when `modules` are called. That would favor more composition of modules and logical grouping by package.

Note: the solution would still create an internal list of "included modules", and we would need to recursively go down in the "included modules" as a module might include another module and so on...

What do you think?

**Comment by marcellogalhardo** [comment]
Hey @arnaudgiuliani - should we close the issue now that #1226 and Koin 3.2.x are around the corner? 😄

**Comment by arnaudgiuliani** [comment]
Yep. A good feature 👌
