### ISSUE TITLE
Support multiple parameters with checkModules

### ISSUE THREAD

**Issue by cketti** [InsertKoinIO/koin#1197]
**Is your feature request related to a problem? Please describe.**
`ParametersBinding.create()` variants are deprecated. However, `ParametersBinding.withParameter()` variants only seems to support a single parameter.

I'm looking for a non-deprecated way to replace code similar to the following snippet:
```kotlin
getKoin().checkModules {
    create<MyClass> { parametersOf("one", 2) }
}
```

**Describe the solution you'd like**
I guess `withParameters` functions that work exactly like the deprecated `create` functions would do.

**Describe alternatives you've considered**
For now I'm still using one of the deprecated `create()` functions :disappointed: 

**Target Koin project**
koin-test

**Comment by arnaudgiuliani** [comment]
Yep, good to fix in next patch 👍
