### ISSUE TITLE
Make compose artifact accessible for Desktop

### ISSUE THREAD

**Issue by malachid** [InsertKoinIO/koin#1208]
**Is your feature request related to a problem? Please describe.**
As the current compose artifact is published as an AAR, it will not work with Jetpack Compose for Desktop. (see https://github.com/JetBrains/compose-jb )

**Describe the solution you'd like**
I have verified that using the ComposeExt.kt within the compose-jb/templates/desktop-template works.
I think as a short term solution, we could just publish that class as an additional JAR artifact to enable it's use.

**Describe alternatives you've considered**
I have temporarily copied that file into my project to get past this, but I assume others will run into it as well.

**Target Koin project**
android-compose

**Comment by arnaudgiuliani** [comment]
Hi there,

yes, the plan is to bring more Compose API for koin, and a dedicated project: https://github.com/InsertKoinIO/koin-compose

The `koin-compose` project will gather related projects about Compose world.

**Comment by arnaudgiuliani** [comment]
From Koin 3.2, Compose projects are on their own track

**Comment by xsveda** [comment]
Anyway, there is no need to ship `koin-android` dependency as Android AAR, it could be a simple JAR.

We have many modules in our Android project that could be JVM modules that are much faster to compile, but as they have dependency on `koin-android` they must be declared as "full" Android modules.

**Comment by arnaudgiuliani** [comment]
Interesting 🤔

**Comment by arnaudgiuliani** [comment]
Is it a new ticket then?

**Comment by xsveda** [comment]
Sorry, I was wrong. I have looked through the code in the `koin-android` module and its dependencies and unfortunately I have to admit that the current AAR format is necessary. Even the `androidx.viewmodel` itself is shared as AAR and although the `koin-android` module contains only Kotlin code, because of its dependencies it is not worth trying to isolate it into a JAR library.

**Comment by Hronom** [comment]
Need koin in order to use voyager on desktop https://voyager.adriel.cafe/screenmodel/koin-integration

**Comment by kazemcodes** [comment]
it would be great if koin support desktop as well

**Comment by arnaudgiuliani** [comment]
sure, it's in the pipeline of new features to come 👍

**Comment by hoc081098** [comment]
+1 point. Koin should support Jetbrains Multiplatform Compose

**Comment by arnaudgiuliani** [comment]
koin-compose 1.0 is coming ...

**Comment by arnaudgiuliani** [comment]
Stay tuned for maven central 👍

**Comment by joreilly** [comment]
Looks like https://voyager.adriel.cafe/setup van be updated now to remove "missing support" entry?
