### ISSUE TITLE
Breaking change with 3.1.0

### ISSUE THREAD

**Issue by AlixBou** [InsertKoinIO/koin#1211]
**Describe the bug**
We are trying to update KOIN from 3.0.2 to 3.1.0, but getSource() is no longer available. 
We obviously also have an issue with scope.setSource(this) in our Activity and Fragment declarations. We were registering them during their initialization then injecting them through our module files.

How can we replace it on our Module declaration files? 

**Example of code no longer working**
To get the activity
```
object SomeModule {
    val module = module {
         scope<RootActivity> {
   			 scoped { MyService(getSource() /* used to get a reference to the activity */) }
		}
	}
}
```

To get a view model, even outside a fragment
```
scope<MyFragment> {
      scoped { Interactor (getSource<MyFragment>().getSharedViewModel()) }
}
```

**Expected behavior**
Have getSource working in those use cases or replace them in a simple way

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-android version 3.0.2 -> 3.1.0`

**Comment by MaxenceLeroy** [comment]
We succeeded using the `ActivityProvider` advised [here](https://github.com/InsertKoinIO/koin/issues/428#issuecomment-484521921).
For the view model, since it is scoped in the activity, we can get the shared view model this way
```
get<Activity>().getViewModel()
```

**Comment by arnaudgiuliani** [comment]
Yes, you can have the same behavior as `getSource()` with `get()`, which directly resolve the expose type of the Scope.

**Comment by arnaudgiuliani** [comment]
Backported in e5c3880e9779497cde121c8360d1b4643534880a
