### ISSUE TITLE
Set initial viewmodel state

### ISSUE THREAD

**Issue by JeremiahStephenson** [InsertKoinIO/koin#1214]
Prior to 3.1.3 you could set an initial state for a ViewModel by doing the following:
`private val viewModel by stateViewModel<ViewModel>(state = { arguments ?: Bundle.EMPTY })`
You can still do that with 3.1.3 but now the state parameter is ignored. Switching over to `by viewModel` doesn't have a way to set the initial state. What is the alternative?

**Comment by arnaudgiuliani** [comment]
in 3.1.3 we propose to use injected parameters. In fact, we have 2 mechanisms that are to help initiate your ViewModel state: state bundle & parameter injection. 

By using `viewModel { parametersOf(<your params here>) }` you can pass easily arguments around. 

https://insert-koin.io/docs/reference/koin-android/viewmodel#viewmodel-and-injection-parameters

`stateViewModel` is just deprecated.

**Comment by crocsandcoffee** [comment]
@arnaudgiuliani I think there may be a potential oversight with the `stateViewModel` deprecation. I could have sworn when I looked at the source code, the passed in `state` bundle is basically ignored. `stateViewModel` under the hood basically calls to the updated `getViewModel` APIs and doesn't do anything with the `state` bundle passed in. So the workaround right now with consumers of `3.1.3` is to break down their default bundle into parameters like your first option suggestion. I think it would be good to still expose a way to pass a default bundle to the `viewModel` APIs which will set the default bundle passed through `SavedStateHandle`...

**Comment by arnaudgiuliani** [comment]
yes, deprecation is a bit hard here in patch. Let me rollback it.
