### ISSUE TITLE
upgrading to 3.1.3

### ISSUE THREAD

**Issue by zinouzl** [InsertKoinIO/koin#1217]
Hello,
When I try to upgrade Koin from  2.2.2 to  3.1.3 on my Android App  I encounter some behavior change like for example the  override function onCreateAnimation on my home Fragment will not be triggered. 
when I downgraded the version to 2.2.2 the function would be called I still dont understand how this is linked, maybe you have some explanation on this ?
Thanks in advance

**Comment by egorikftp** [comment]
As an option koin 2.2.2 uses old version androidx.fragment dependency and after migration to 3.1.3 everything broken

**Comment by arnaudgiuliani** [comment]
Koin 3.1.3 is updated to those libraries:
* androidx_activity_version = "1.3.1"
* androidx_fragment_version = "1.3.6"

be sure to check around those android lib upgrade before going.
