### ISSUE TITLE
Optional parameter injection

### ISSUE THREAD

**Issue by osrl** [InsertKoinIO/koin#1219]
Is it possible to make parameters optional? 

Currently I'm using like this:
```
    factory { (a: Param?) ->
        Foo( a ?: get() )
    }

val foo: Foo by inject { parametersOf(null) }
```
It would be great if I could provide a default parameter, and don't add null parameter to inject.

**Comment by arnaudgiuliani** [comment]
you can use `getOrNull()` even for parameter. they are passed like regular dependencies in the graph
