### ISSUE TITLE
Add `KoinDelicateApi` and flag dangerous APIs

### ISSUE THREAD

**Issue by marcellogalhardo** [InsertKoinIO/koin#1221]
**Is your feature request related to a problem? Please describe.**

We can get inspired by Kotlin's Coroutines `@CoroutineDelicateApi`, and mark the APIs that can be potentially dangerous or should not be "abused of" while using.

From [Coroutines docs](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-delicate-coroutines-api/):

> Marks declarations in the coroutines that are delicate - they have limited use-case and shall be used with care in general code. Any use of a delicate declaration has to be carefully reviewed to make sure it is properly used and does not create problems like memory and resource leaks. Carefully read the documentation of any declaration marked as DelicateApi.

**Describe the solution you'd like**

The goal would be to introduce a `@KoinDelicateApi`, together with the already in place `@KoinInternalApi` and `@KoinExperimentalApi` - and we would try to figure out what are the APIs that aren't recommended to heavy usage and could be problematic.

An example of such API in my opinion would be the `KoinComponent` but other people more experienced in the library might want to collaborate with other APIs too.

**List of known delicate APIs:**
- `KoinComponent`

**Comment by arnaudgiuliani** [comment]
I remember having proposed an annotation for `KoinComponent` in 2.2, and people complaining about that :/ 
I must admit that the first shot was putting it in error if you didn't optIn (a bit hard). I put it back in warning, and then remove it. 

But yes, somewhere I agree with you on it 👍

**Comment by arnaudgiuliani** [comment]
For now I continue to use @KoinInternalAPI for any kind of API that is not intended to be use. KoinComponent interface is still a component where I would propose some annotation like your proposal ... let see over time again.
