### ISSUE TITLE
Seems like two or more KoinApplication being created simultaneously, share instances.

### ISSUE THREAD

**Issue by caeus** [InsertKoinIO/koin#1222]
**Describe the bug**
I've got a method that produces an application:
```kotlin
fun application(overridesModule: Module = module {}) = koinApplication {
    modules(
        ConfigModule,
        OrdersModule,
        HealthModule,
        HttpModule,
        PubsubModule,
        SerializationModule,
        AlertingModule,
        VersionModule,
        OrchestrationModule,
        overridesModule
    )
}
```
I use this method to produce my production application, but also to produce applications for test. I just pass a module that overrides multiple instances with mocks or stubs.

I've got two different tests that use this method.
If I run each test individually, they pass, but if I run all tests, one of them fail because the instances were not overriden.

How to reproduce? I'm trying to come up with a way to reproduce it, but it seems very specific to my project. Still, there's no doubt. It's like somehow each application (koinApplication) is sharing the instance registry? Still... I'm checking the code and there's no shared global state.

Using koin 3.1.2

**Comment by caeus** [comment]
Yep. Solved the issue. It seems modules do share memory.
If I create an app that uses a given module, and get one of the instances that such module know how to build, and THEN I create another app that overrides that, but I request one of the component (singleton) that uses the overriden service, it will return the instance that already has the non overriden thing. I think I can create a way to reproduce the error

**Comment by caeus** [comment]
Ok, so I managed to reproduce the error:

```kotlin

data class Greeting(val value: String)

test("reproduceError") {
        val sharedModule = module {
            single {
                "World"
            }
            single {
                Greeting("Hello ${get<String>()}")
            }
        }
        val app1 = koinApplication {
            modules(sharedModule)
        }
        app1.koin.get<Greeting>()
        val app2 = koinApplication {
            modules(sharedModule, module {
                single {
                    "Earth"
                }
            })
        }
        assertEquals("Hello Earth", app2.koin.get<Greeting>().value)
    }
```

That test would fail

**Comment by arnaudgiuliani** [comment]
Good question. Once you have declared a `Module` value, its resources are allocated (definitions and instance factories). In your case you can fix this by having a function that return your shared definition:

```kotin
fun sharedModule() = module {
            single {
                "World"
            }
            single {
                Greeting("Hello ${get<String>()}")
            }
        }
```

This way you can share your definitions, but won't keep factories.

**Comment by caeus** [comment]
At the end I fixed it that way.
Still, it should either work the other way, or be documented that modules can't be shared among applications. (they are not threadsafe)

**Comment by arnaudgiuliani** [comment]
perhaps documentation should be more explicit on allocations under the hood yes.
