### ISSUE TITLE
[Documentation] Koin v3 & Quickstart Android Viewmodel : outdated gradle setup line

### ISSUE THREAD

**Issue by eucalypto** [InsertKoinIO/koin#1231]
In the Quickstart Android Viewmodel Documentation, contains the following line for gradle setup

`implementation "io.insert-koin:koin-android-viewmodel:$koin_version"`

https://github.com/InsertKoinIO/koin/blob/382bdbc3789c4d9bfee078cd8477dbba9d9533fa/docs/quickstart/android-viewmodel.md?plain=1#L26

But in the Koin v3  Setup guide it says that this line is deprecated:
https://insert-koin.io/docs/setup/v3

https://github.com/InsertKoinIO/koin/blob/382bdbc3789c4d9bfee078cd8477dbba9d9533fa/docs/setup/v3.md?plain=1#L56

Should the Quicktstart guide from above be updated? Or extended to include setups for v2 and v3?

**Comment by arnaudgiuliani** [comment]
sure, it's outdated and you just need `koin-android`.
