### ISSUE TITLE
Koin 3.1.3 Android crashes

### ISSUE THREAD

**Issue by VikiBDev** [InsertKoinIO/koin#1232]
**Describe the bug**
I started noticing `KoinApplication has not been started` and `Scope '_' is closed` after upgrading to Koin 3 (more specifically, 3.1.3) in my Android app. The Koin initialisation code and the code injection code has barely changed during the migration (I just had to update a few view model injections, but those aren't affected by these bugs anyway). All these crashes seem to be related to the Android app lifecycle, since they happen either when an activity is being resumed or when a push notification is received when the app is in the background.

Focusing on the `KoinApplication has not been started`, it happens very rarely when an activity is being resumed, and it tries to create an object via the `factory` method. 

**To Reproduce**

I wasn't able to reproduce the crash, it happens quite rarely on a big user base. I'll update the issue if I manage to reproduce it.

**Expected behavior**
I expect the standard DSL methods (`single {}` , `factory {}`) to work as long as the Android application is alive and hasn't been killed by the OS. I do nothing fancy with module definitions, just using the two methods I mentioned above and keeping everything inside a single `applicationModule`.

**Koin project used and used version (please complete the following information):**
   "io.insert-koin:koin-core:$koin_version"
   "io.insert-koin:koin-android:$koin_version"
   "io.insert-koin:koin-android-compat:$koin_version"

**Additional moduleDefinition**

Just to add some context, I do nothing fancy during Koin initialisation, just a simple:

```       
 startKoin {
            androidLogger()
            androidContext(this@KryApplication)
            modules(applicationModule)
        }
```

In the application's onCreate method.

**Comment by arnaudgiuliani** [comment]
Hello,

one thing also you could check is the behavior with android/ktx dependencies upgrade. Koin updates with one of the latest. It can explain more some "side" behavior, on Android side.

But let's try to reproduce.

**Comment by VikiBDev** [comment]
Hi! Thank you for checking this. I'm not sure I understand what you mean when you say `check is the behavior with android/ktx dependencies upgrade`. 

Let me know if you need more info or if there's anything you'd like me to try in order to reproduce the issue.

**Comment by arnaudgiuliani** [comment]
behind Koin 3.1.x, there are some android libs update:
- androidx.appcompat:appcompat:1.3.1
- androidx.lifecycle:lifecycle-viewmodel-savedstate:2.3.1
- androidx.activity:activity-ktx:1.3.1
- androidx.fragment:fragment-ktx:1.3.6

this could induce new behavior on Android side

**Comment by arnaudgiuliani** [comment]
let us know if you other thing
