### ISSUE TITLE
binds arrayOf() no longer working

### ISSUE THREAD

**Issue by cdekok** [InsertKoinIO/koin#1235]
**Describe the bug**
When upgrading to 3.1.4 from 3.1.3 binding to multiple interfaces stops working.

**To Reproduce**

```
   single {
        FooBar(
            dao = get()
        )
    } binds arrayOf(
        Foo::class,
        Bar::class
    )
```

**Expected behavior**

That it compiles as with 3.1.3 currently it errors on:
> Not enough information to infer type variable T

**Koin project used and used version (please complete the following information):**
`koin-core version 3.1.4`

**Comment by arnaudgiuliani** [comment]
I don't see any API breaking on this operator. Please let me know if you can find out.
