### ISSUE TITLE
Surprisingly Koin crash at start Android app

### ISSUE THREAD

**Issue by glush** [InsertKoinIO/koin#1237]
**Describe the bug**
App crash at start due Koin 3.1.4 components creation. Change nothing with deps. Yesterday works fine,

                 [Koin]  I  [init] declare Android Context
         AndroidRuntime  D  Shutting down VM
                         E  FATAL EXCEPTION: main
                         E  Process: com.a2raco.crown.debug, PID: 7080
                         E  java.lang.NoSuchMethodError: No static method toDouble-impl(JLjava/util/concurrent/TimeUnit;)D in class Lkotlin/time/Duration; or its super classes (declaration of 'kotlin.time.Duration' appears in /data/app/com.a2raco.crown.debug-2/base.apk:classes15.dex)
                         E      at org.koin.core.time.MeasureKt.measureDuration(Measure.kt:32)
                         E      at org.koin.core.KoinApplication.modules(KoinApplication.kt:59)
                         E      at org.koin.core.KoinApplication.modules(KoinApplication.kt:42)
                         E      at com.a2raco.crown.CrownApplication$onCreate$1.invoke(CrownApplication.kt:26)

Downgrade to Koin 3.1.3 and 3.1.2 change nothing. Some hidden API change?

**Comment by beiertu-mms** [comment]
@glush this looks like the same issue describe in #1188.
there is a workaround described [in that issue](https://github.com/InsertKoinIO/koin/issues/1188#issuecomment-970240532).

**Comment by nphau** [comment]
> **Describe the bug** App crash at start due Koin 3.1.4 components creation. Change nothing with deps. Yesterday works fine,
> 
> ```
>              [Koin]  I  [init] declare Android Context
>      AndroidRuntime  D  Shutting down VM
>                      E  FATAL EXCEPTION: main
>                      E  Process: com.a2raco.crown.debug, PID: 7080
>                      E  java.lang.NoSuchMethodError: No static method toDouble-impl(JLjava/util/concurrent/TimeUnit;)D in class Lkotlin/time/Duration; or its super classes (declaration of 'kotlin.time.Duration' appears in /data/app/com.a2raco.crown.debug-2/base.apk:classes15.dex)
>                      E      at org.koin.core.time.MeasureKt.measureDuration(Measure.kt:32)
>                      E      at org.koin.core.KoinApplication.modules(KoinApplication.kt:59)
>                      E      at org.koin.core.KoinApplication.modules(KoinApplication.kt:42)
>                      E      at com.a2raco.crown.CrownApplication$onCreate$1.invoke(CrownApplication.kt:26)
> ```
> 
> Downgrade to Koin 3.1.3 and 3.1.2 change nothing. Some hidden API change?

Here is workaround solution: https://github.com/InsertKoinIO/koin/issues/1188
