### ISSUE TITLE
Does the koin has a plugin for IntelliJ?

### ISSUE THREAD

**Issue by Kolyall** [InsertKoinIO/koin#1239]
Does the koin lib has a plugin for IntelliJ like this one for Dagger?
https://github.com/square/dagger-intellij-plugin

**Comment by arnaudgiuliani** [comment]
yeah, would be great :)

**Comment by Kolyall** [comment]
Reopen pls

**Comment by arnaudgiuliani** [comment]
What would you like this plugin to do?

**Comment by Kolyall** [comment]
Fast navigation from instance of obj to implementation

**Comment by minenhle-lipapayments** [comment]
Would also like this. Especially for cases where you have something like
```
factory { (p0: String, p1: Int) -> Config(p0, p1) }
```

Then injecting via
```
val config = get<Config>{ paramsOf("Hello", 1) }
```

It becomes difficult to trace this when trying to add a param to config and finding the instances that use it.
