### ISSUE TITLE
java.lang.NoSuchMethodError with kotlin 1.6

### ISSUE THREAD

**Issue by krottv** [InsertKoinIO/koin#1242]
**Describe the bug**
```
java.lang.NoSuchMethodError:
No static method toDouble-impl(JLjava/util/concurrent/TimeUnit;)D in class Lkotlin/time/Duration; or its super classes (declaration of 'kotlin.time.Duration' appears in
```

**To Reproduce**
1. Set kotlin 1.6 in project
2. Call 

```
    startKoin {

            if (BuildConfig.DEBUG)
                androidLogger()
                
            // declare modules
            androidContext(this@App)
            modules(...)
     }
```

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core version 3.1.4`

**Comment by egorikftp** [comment]
Duplicate of https://github.com/InsertKoinIO/koin/issues/1188

**Comment by Jesil-OT** [comment]
works for me, Thanks

**Comment by Jesil-OT** [comment]
works for me, Thanks

**Comment by tomtaila** [comment]
Yeah I have the same issue

**Comment by Arman10000** [comment]
The method helped me
`startKoin { androidLogger(Level.ERROR) }`
Or not to use `androidLogger()`

**Comment by arnaudgiuliani** [comment]
is outdated with Koin 3.2.0.

**Comment by vuuygur** [comment]
add where ?

**Comment by arnaudgiuliani** [comment]
Time API has been ported back. Since Koin 3.2 we are less impacted by Kotlin upgrades
