### ISSUE TITLE
kotlin.native.concurrent.InvalidMutabilityException: mutation attempt of frozen

### ISSUE THREAD

**Issue by Reedyuk** [InsertKoinIO/koin#1244]
**Describe the bug**
When using the new memory model from Kotlin, i am getting the following error
```
kotlin.native.concurrent.InvalidMutabilityException: mutation attempt of frozen me.andrewreed.BrokenViewModel@2cdc340
```

**To Reproduce**

1. Checkout https://github.com/Reedyuk/MutabilityIssue
2. Run ./gradlew iosSimulatorArm64Test

**Expected behavior**
I would expect it to be fine, no error and return the dependancy.

**Koin project used and used version (please complete the following information):**
`koin-core version 3.1.4`
`kotlin: 1.6.0`

**Additional moduleDefinition**
Checkout the sample at https://github.com/Reedyuk/MutabilityIssue

**Comment by mirjalal** [comment]
Did you fix your problem?

**Comment by mirjalal** [comment]
Have you fixed the problem?
