### ISSUE TITLE
Changed behaviour within startKoin between 3.0.2 and 3.1.4

### ISSUE THREAD

**Issue by stuebingerb** [InsertKoinIO/koin#1248]
**Describe the bug**
I am currently upgrading our koin setup and noticed a changed behaviour within `startKoin`, to be concrete: Now the order between properties and modules seems to matter. Since I could not find any documentation regarding that change I assume this was unintended.

**To Reproduce**
Consider the following test case:

```
import org.koin.core.component.KoinComponent
import org.koin.core.context.startKoin
import org.koin.dsl.module
import kotlin.test.Test
import kotlin.test.assertEquals

class Reproducer {
    @Test
    fun `works with koin 2_2_3 and koin 3_0_2, breaks with koin 3_1_4`() {
        startKoin {
            modules(module {
                single(createdAtStart = true) { InjectionTarget() }
            })
            properties(
                mapOf(
                    "foo" to "bar"
                )
            )
        }
    }
    @Test
    fun `works with all versions of koin`() {
        startKoin {
            properties(
                mapOf(
                    "foo" to "bar"
                )
            )
            modules(module {
                single(createdAtStart = true) { InjectionTarget() }
            })
        }
    }
}

class InjectionTarget : KoinComponent {
    init {
        assertEquals("bar", getKoin().getProperty<String>("foo"))
    }
}
```

The first variant (module section before properties section) worked with koin 2.2.3 and 3.0.2 but fails now with koin 3.1.4, the second variant (properties section before module section) works in all versions.

**Expected behavior**
I would expect that the order of sections within `startKoin` does not matter, i.e. the first variant should work in koin 3.1.4 as well.

**Koin project used and used version (please complete the following information):**
`koin-core version 3.1.4`, Kotlin running on Java 17

**Additional moduleDefinition**
-

**Comment by arnaudgiuliani** [comment]
Yes, interesting. the `createdAtStart = true` seems to start directly new instances

**Comment by arnaudgiuliani** [comment]
yes, eager instances were created at end of koinApp lambda.

**Comment by stuebingerb** [comment]
Thank you for the quick fix!

**Comment by monosoul** [comment]
After this change `createdAtStart = true` has stopped working for me, the beans are not created at start anymore

**Comment by monosoul** [comment]
Actually, it seems like not `createdAtStart = true` has stopped working, but dynamic module loading. If I try to call `loadModules()` after the app has started, and then try to get a bean from the modules, I get `NoBeanDefFoundException`

**Comment by arnaudgiuliani** [comment]
in 3.1.5?

**Comment by monosoul** [comment]
Yep, in 3.1.5.  We are using `org.koin.dsl.KoinApplicationKt#koinApplication` to create a context and in contrast to `org.koin.core.context.GlobalContext#startKoin` it doesn't have `koinApplication.createEagerInstances()` call

**Comment by monosoul** [comment]
Probably it's on purpose, but I didn't expect `createdAtStart = true` to stop working after a minor version update :sweat_smile:

**Comment by arnaudgiuliani** [comment]
yes, behavior has been updated to help optimize module loading. Let me check if I can provide retrocompat API

**Comment by arnaudgiuliani** [comment]
fixed 👍
