### ISSUE TITLE
Koin Plugin Does Not Work With Ktor 2.0

### ISSUE THREAD

**Issue by AlexandreBrown** [InsertKoinIO/koin#1257]
**Describe the bug**
Some breaking changes were introduced in ktor 2.0.  
Ktor "features" were renamed to "plugins" and this causes Koin Feature to be incompatible with Ktor 2.0.
More information about this change can be found [here](https://ktor.io/docs/eap/migrating-2.html#feature-plugin).

**To Reproduce**
1. Create a Ktor 2.0 project
2. Add Koin ktor dependency : `implementation("io.insert-koin:koin-ktor:3.1.4")`
3. Try to install the Koin Plugin  
```kotlin
import io.ktor.server.application.Application
import org.koin.ktor.ext.Koin

fun Application.installPlugins() {
	install(Koin)
}
```
4. See error, the Koin Plugin cannot be installed.  
![image](https://user-images.githubusercontent.com/26939775/147251034-2a897aec-5503-44b7-90a1-5da85deb739b.png)
```kotlin
Type mismatch.
    Required:
        Plugin<TypeVariable(P), TypeVariable(B), TypeVariable(F)>
    Found:
        Koin.Feature
```

**Expected behavior**
The Koin Plugin can be installed.

**Koin project used and used version:**
`koin-ktor version 3.1.4`

**Additional moduleDefinition**
`io.ktor:ktor-server-core:2.0.0-beta-1`

**Comment by phucynwa** [comment]
I got the same problem. Please try this.

```kotlin
object KoinPlugin : ApplicationPlugin<Application, KoinApplication, Koin> {

    override val key: AttributeKey<Koin>
        get() = AttributeKey("Koin")

    override fun install(
        pipeline: Application,
        configure: KoinApplication.() -> Unit
    ): Koin {
        val monitor = pipeline.environment.monitor
        val koinApplication = startKoin(appDeclaration = configure)
        monitor.raise(KoinApplicationStarted, koinApplication)

        monitor.subscribe(ApplicationStopping) {
            monitor.raise(KoinApplicationStopPreparing, koinApplication)
            stopKoin()
            monitor.raise(KoinApplicationStopped, koinApplication)
        }

        return Koin(koinApplication)
    }
}
```

https://gist.github.com/phucynwa/bc29d8e5dc9b0f1eacd2dc6101dbb0b6

**Comment by AlexandreBrown** [comment]
Thanks @phucynwa , I will keep this issue opened until Koin adds the plugin in the official repo (perhaps consider making a PR?)

**Comment by phucynwa** [comment]
@AlexandreBrown Ok, I've just create a PR #1266

**Comment by tonisives** [comment]
There is another issue, 

```
package org.koin.ktor.ext
```

defines

```
public inline fun <reified T : kotlin.Any> io.ktor.application.Application.inject(qualifier: org.koin.core.qualifier.Qualifier? /* = compiled code */, noinline parameters: org.koin.core.parameter.ParametersDefinition? /* = (() -> org.koin.core.parameter.ParametersHolder)? */ /* = compiled code */): kotlin.Lazy<T> { /* compiled code */ }
```

but in 2.0.0 the ktor Application has different path:

```
import io.ktor.server.application.*
```
<img width="974" alt="Screenshot 2022-01-10 at 09 16 23" src="https://user-images.githubusercontent.com/1083534/148711323-2a28e692-24a6-4e1b-ad64-4c1e95464417.png">

**Comment by phucynwa** [comment]
@tonisives Check `KoinApplicationExt.kt` in #1266, I just add `inject` method for this.

**Comment by sidvenu** [comment]
Any update on this?

**Comment by phucynwa** [comment]
@sidvenu Hope it will be compatible in version 3.1.6 or 3.2.0. Please vote for my PR #1266 guy.

**Comment by sidvenu** [comment]
That's amazing. Pressed thumbs up (hope that's what you mean).

**Comment by Morons** [comment]
![Error Screenshot](https://user-images.githubusercontent.com/22202038/166437172-c071297b-ed25-4249-87c9-312719c02459.png)
**OOPS ! Bummer**
ktor_version=2.0.1
kotlin_version=1.6.21
logback_version=1.2.11
koin_version=3.1.6

IntelliJ IDEA 2022.1 (Ultimate Edition)
Build #IU-221.5080.210, built on April 12, 2022
https://gist.github.com/phucynwa/bc29d8e5dc9b0f1eacd2dc6101dbb0b6?permalink_comment_id=4152880#gistcomment-4152880

**Comment by arnaudgiuliani** [comment]
Koin for Ktor 2.0 is now ready in https://github.com/InsertKoinIO/koin-ktor

**Comment by AYastrebov** [comment]
> Koin for Ktor 2.0 is now ready in https://github.com/InsertKoinIO/koin-ktor

Thank you! Any eta on release `3.2.0-beta-2`?
