### ISSUE TITLE
Jetpack Compose: Load/unload module for specific Composable function.

### ISSUE THREAD

**Issue by Festak** [InsertKoinIO/koin#1265]
I couldn't understand how to load/unload the koin module for a specific composable function. 
Let's say I have a view model injection inside the composable.

This case will reload koin modules each recomposition

@Composable
fun Test() {

NavHost() {
composable(route = "ScreenA"){
loadKoinModules(screenAModule)
val viewModel = getViewModel<ScreenAViewModel>().
}
}
}

// This case won't call load/unload modules and getViewModel will be called much earlier
@Composable
fun Test() {
NavHost() {
composable(route = "ScreenA"){
  DisposableEffect(key1 = Unit) {
                                loadKoinModules(screenAModule)
                                onDispose {
                                    unloadKoinModules(screenAModule)
                                }
                            }

val viewModel = getViewModel<ScreenAViewModel>().
}
}
}

 
Instead of loading all the modules in the Application file, I want to load/unload only the related view model module with its use cases and etc only inside the specific Composable function.

**Comment by Dzmitry-Lakisau** [comment]
Have you solved this issue?
