### ISSUE TITLE
Use KType (or something more powerful) instead of KClass for indexing singletons and factories

### ISSUE THREAD

**Issue by caeus** [InsertKoinIO/koin#1269]
Currently I'm trying to inject multiple different instances of the same class, BUT with different generics.

Let's assume something like 
```
interface Producer<out T>{ fun create():T }
``` 

And I want to be able to inject different Producers of different instances

```
module{
single<Producer<String>> {
  object: Producer<String>{...}
}
single<Producer<Int>> {
  object: Producer<Int>{...}
}
```

Yet that's not possible :(

**Comment by arnaudgiuliani** [comment]
Yes I know the interest of `KType`. Need to check performances impact.

**Comment by caeus** [comment]
Moved to kodein for this reason

**Comment by arnaudgiuliani** [comment]
I won't say never, but for now it's impacting a lot the performances. To see in Koin 4.0 how we can add it or not
