### ISSUE TITLE
Cannot inject dependency in a Composable function

### ISSUE THREAD

**Issue by svprdga** [InsertKoinIO/koin#1273]
**Describe the bug**
I can't obtain an instance of a dependency within a Composable function by following the [official guide](https://insert-koin.io/docs/reference/koin-android/compose/).

It is a KMM project. All the dependencies in the shared module can be obtained without problems.
All the view model dependencies in the android module can be obtained without problems.

The setup is exactly as the one shown in the official docs.

**To Reproduce**
1. Create an Android application that uses Jetpack Compose as a UI framework
2. Try to obtan a koin dependency within a Composable function

**Expected behavior**
By using `val myService = get<MyService>()` one can get the given dependency.

**Actual behaviour**
I can't compile if I use `val myService = get<MyService>()` because of the following error:

> e: [...]MainScreen.kt: (120, 34): No value passed for parameter 'clazz'

**Koin project used and used version (please complete the following information):**
`koin-core version 3.1.4`
`koin-android version 3.1.4`

**Comment by TheHolisticDev** [comment]
Had the same issue and solved it according to this post: https://stackoverflow.com/questions/71662424/koin-inject-viewmodel-into-composable

**implementation("io.insert-koin:koin-androidx-compose:$koinVersion")** dependency was missing to get the **org.koin.androidx.compose.get** import.

Koin docs should be updated to hint at the additional import for compose.
