### ISSUE TITLE
SavedStateRegistryOwner.getStateViewModel throws ClassCastException

### ISSUE THREAD

**Issue by headsvk** [InsertKoinIO/koin#1278]
**Describe the bug**
In Koin 3.1.3 `fun SavedStateRegistryOwner.getStateViewModel(...)` was changed to not check if this `SavedStateRegistryOwner` implements `ComponentCallbacks` interface. It leads to a crash if you try to use the method with [NavBackStackEntry](https://developer.android.com/reference/androidx/navigation/NavBackStackEntry) as the class doesn't implement `ComponentCallbacks`.

**To Reproduce**
Calling `getStateViewModel` on `NavBackStackEntry` throws:
```
java.lang.ClassCastException: androidx.navigation.NavBackStackEntry cannot be cast to android.content.ComponentCallbacks
  at org.koin.androidx.viewmodel.ext.android.SavedStateRegistryOwnerExtKt.getStateViewModel(SavedStateRegistryOwnerExt.kt:72)
```

**Expected behavior**
Calling `getStateViewModel` returns `ViewModel` for the root scope.

**Comment by arnaudgiuliani** [comment]
Please use the `by koinNavGraphViewModel()` function that will handle NavBackStackEntry case ViewModel hosting. It's located in `koin-androidx-navigation`

**Comment by headsvk** [comment]
@arnaudgiuliani I have seen that method but it's only available for `Fragment` and I have a single `Activity` with Compose. The use case was getting a parent `ViewModel` for a nested navigation graph and I don't see how to do it anymore, see https://stackoverflow.com/a/69643625.

**Comment by arnaudgiuliani** [comment]
In latest Koin-androidx-compose 3.2.0-beta-1 we have added the possibility to ass the owner: 

```kotlin
inline fun <reified T : ViewModel> getViewModel(
    qualifier: Qualifier? = null,
    owner: ViewModelStoreOwner? = null,
    scope: Scope = GlobalContext.get().scopeRegistry.rootScope,
    noinline parameters: ParametersDefinition? = null,
): T {
    val storeOwner = owner?.let { ViewModelOwner.from(it) } ?: getComposeViewModelOwner()
    return remember(qualifier, parameters) {
        scope.getViewModel(qualifier, { storeOwner }, parameters)
    }
}
```
