### ISSUE TITLE
WorkManager Version 2.7.0 is required for apps targeting Android 12 (S).

### ISSUE THREAD

**Issue by mbt-anhtuan-m** [InsertKoinIO/koin#1279]
**Describe the bug**
The latest version of Koin 3.1.5 is with WorkManager 2.6.0. But WorkManager 2.7.0 is required for Android 12

**Comment by Yazazzello** [comment]
Yeah, that gives the infamous `java.lang.IllegalArgumentException: %your_package%: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.`
but you can specify explicitly version of work manager in _dependencies_ section in gradle
