### ISSUE TITLE
Unresolved reference: setFragmentResult while upgrading to 3.1.5

### ISSUE THREAD

**Issue by vicmosin** [InsertKoinIO/koin#1280]
**Describe the bug**
Upgrading from `3.1.4` to `3.1.5` makes `androidx.fragment.app.setFragmentResult` be unknown

**To Reproduce**
1. Add simple project with any usage of `androidx.fragment.app.setFragmentResult` and following dependencies:
```
   implementation "io.insert-koin:koin-core:3.1.4"
   implementation "io.insert-koin:koin-android:3.1.4"
```
2. Compile to make sure it works
3. Upgrade koin version to 3.1.5
4. Recompile and see error `Unresolved reference: setFragmentResult`

**Expected behavior**

**Koin project used and used version (please complete the following information):**
`koin-core version 3.1.5`, `koin-android version 3.1.5`

**Comment by arnaudgiuliani** [comment]
Koin 3.1.5 relies on `androidx.activity:activity-ktx:1.3.1`

if we follow this: https://github.com/xamarin/AndroidX/issues/165

Please check to add fragment-ktx on your side.
