### ISSUE TITLE
v3.1.4 getViewModel IllegalStateException: Method addObserver must be called on the main thread 

### ISSUE THREAD

**Issue by CWJamieson** [InsertKoinIO/koin#1281]
**Describe the bug**
Calling `by viewModel()` on a background thread in android causes an `IllegalStateException` on v3.1.4 and v3.1.5, but not v3.1.2. Based on the error, it seems that `by viewModel()` now requires adding an observer. Is this an intended change, or a regression? In my case, this dependency graph is quite extensive, so doing it on the main thread will impact performance.

The stack trace:
`FATAL EXCEPTION: DefaultDispatcher-worker-2 Process: {APP_PACKAGE}, PID: 32629 java.lang.IllegalStateException: `
`Method addObserver must be called on the main thread at androidx.lifecycle.r.e(LifecycleRegistry.java:3) at `
`androidx.lifecycle.r.a(LifecycleRegistry.java:1) at `
`androidx.lifecycle.SavedStateHandleController.c(SavedStateHandleController.java:3) at `
`androidx.lifecycle.SavedStateHandleController.d(SavedStateHandleController.java:15) at `
`androidx.lifecycle.a.b(AbstractSavedStateViewModelFactory.java:1) at androidx.lifecycle.l0.b(ViewModelProvider.kt:7) at `
`androidx.lifecycle.l0.a(ViewModelProvider.kt:2) at o00.a.b(ScopeExt.kt:17) at `
`jw.a.g(AlternateFormatsCountryCodeSet.java:2) at `
`{ACTIVITY}$special$$inlined$viewModel$default$2.invoke(ComponentCallbackExt.kt:3) at `
`{ACTIVITY}$special$$inlined$viewModel$default$2.invoke(ComponentCallbackExt.kt:1) at `
`kotlin.UnsafeLazyImpl.getValue(Lazy.kt:2) at `
`{ACTIVITY}.getActivationViewModel({ACTIVITY}.kt:1) at`

**To Reproduce**
1. Use Koin v3.1.4
2. Define a `class A` that injects a viewModel with `by viewModel()`
3. Initialize an instance of `class A` on a non-main thread
4. See crash

**Expected behavior**
I would expect this behaviour to be consistent with v3.1.2, and not crash

**Koin project used and used version (please complete the following information):**
koin-android:3.1.2 works
koin-android:3.1.4 exhibits the issue

**Additional moduleDefinition**

**Comment by MarinaShaposhnikova** [comment]
Hello, is it any update on this issue?
I face it as well, although downgrade to 3.1.2 is not an option due to another bug.
https://github.com/InsertKoinIO/koin/issues/1149

**Comment by MarinaShaposhnikova** [comment]
@arnaudgiuliani May you please take a look at it?

**Comment by arnaudgiuliani** [comment]
> Calling by viewModel() on a background thread in android 

Latest Android API is forced on main thread. Else perhaps think to inject another kind of component than ViewModel
