### ISSUE TITLE
IntelliJ tip : live template for Koin

### ISSUE THREAD

**Issue by jmfayard** [InsertKoinIO/koin#1289]
**Describe the bug**
Not a bug, just sharing something handy :)

![koin](https://user-images.githubusercontent.com/459464/153399294-e099352d-9bd1-4b49-ab22-af27df073757.gif)

**To Reproduce**

- Add a **Live Template** (Preferences > Editor > Live Templates) 
- abbreviated by `inject` or `inj`
- with template text private `val $NAME$ by inject<$TYPE$>()`
- with **first** variable being TYPE with expression `completeSmart()`
- with **second** variable being NAME with expression `kotlinAnyVariable() `

**Comment by arnaudgiuliani** [comment]
Could be something we add on the insert-koin.io website
