### ISSUE TITLE
[Question] Is it possible to define the Koin module using Java?

### ISSUE THREAD

**Issue by erikskauch** [InsertKoinIO/koin#1290]
**Describe the question**
I've been struggling a few days trying to write the module definition in pure Java ([seeing at the documentation that some integration is possible](https://insert-koin.io/docs/quickstart/android-java/)) but it starts to seem Koin doesn't allow it. What in Kotlin is like this

```
@JvmField
val appModule = module {
    single { MyApiAdapter(get()) }
}
```

I only got in Java to something similar to:
```
public final class AppModuleKt {
    @JvmField
    @NotNull
    public static final Module appModule;

    static {
        appModule = ModuleKt.module(true, null )
    }
}
```

Being the first parameter a createdAtStart flag and the second (null at the example) the Module Declarations (which stand for these function Module.() -> Unit). I've tried to instantiate directly on the module() call and also trying to add declarations to appModule in the next line but neither of both options seem to work.

Thanks for any help or confirmation it's not possible.

**Comment by marcellogalhardo** [comment]
Hey, @erikskauch - can you give more details on "why" you are trying to do that? Maybe there is an alternative way to solve your problem... 🤔

**Comment by erikskauch** [comment]
Hi @marcellogalhardo , it's more curiosity than anything else. It would be the only part in my code that would be in Kotlin (the rest is all Java) and I was trying to avoid having two different compilations. As a workaround I'm using it in Kotlin for the moment and it works but i'm curious about if it's the only thing in Koin non-writable in Java.
