### ISSUE TITLE
Fix typo in docs

### ISSUE THREAD

**Issue by pedrofsn** [InsertKoinIO/koin#1294]
**Describe the bug**
Deleting `x` from word `Anxdroid`.

**To Reproduce**
Search for `Anxdroid` in `docs/reference/koin-android/dsl-update.md`.

**Koin project used and used version**
`koin-android version 3.2`
 
 **Fixed here**
https://github.com/InsertKoinIO/koin/pull/1293

**Comment by arnaudgiuliani** [comment]
can be clsoe then
