### ISSUE TITLE
Insert module in another module

### ISSUE THREAD

**Issue by aaf-dev** [InsertKoinIO/koin#1297]
Hello! I tried to google it, but I can't find any solution.
Is it possible to inject some local module into global module?

Just to make a `modules()` in a `startKoin` with less code

For example (this version isn't working now):

```
val localModule = module {
   single { SomeSingleClass(get()) }
}

val anotherLocalModule = module { ... }

val globalModule = module {
   module { localModule }
   module { anotherLocalModule }
   single { AnotherSingleClass() }
}

startKoin {
    ...
    modules(..., globalModule)
}
```

**Comment by marcellogalhardo** [comment]
Not yey but soon! We bave been working in a new feature which allows you to include a module in another by calling the method `includes`. It is availabld on Koin 3.2 Beta (you can test it out if you want - feel free to send us feedback!) and should hit stable in the next fea weeks.

**Comment by marcellogalhardo** [comment]
@aaf-dev with the release of Koin 3.2, including a module in another module is now supported by the function `includes`:

```kotlin
val localModule = module {
   single { SomeSingleClass(get()) }
}

val anotherLocalModule = module { ... }

val globalModule = module {
   includes(localModule)
   includes(anotherLocalModule)
   single { AnotherSingleClass() }
}

startKoin {
    modules(globalModule)
}
```

@arnaudgiuliani I believe you can close this issue.
