### ISSUE TITLE
singleOf unresolved reference in module

### ISSUE THREAD

**Issue by mikezliu** [InsertKoinIO/koin#1299]
In the koin front page, the second example uses singleOf: https://insert-koin.io/

This results in a unresolved reference since Module does not have a method called singleOf

**Comment by marcellogalhardo** [comment]
@mikezliu what Koin version are you using? These functions are only available in the current beta version (3.2).

**Comment by mikezliu** [comment]
Ok that's probably why. I was using the latest non-beta version
