### ISSUE TITLE
Could not resolve io.insert-koin:koin-ktor:3.2.0-beta-1

### ISSUE THREAD

**Issue by ronjunevaldoz** [InsertKoinIO/koin#1300]
Having an issue using koin-ktor:3.2.0-beta-1 Could not resolve io.insert-koin:koin-ktor:3.2.0-beta-1

## Gradle
```kotlin
repositories {
    mavenCentral()
    maven { url = uri("https://maven.pkg.jetbrains.space/public/p/ktor/eap") }
}
dependencies {
    // Koin 
    implementation("io.insert-koin:koin-ktor:$koinVersion")
    implementation("io.insert-koin:koin-logger-slf4j:$koinVersion")
}
```

## gradle.properties
`koinVersion=3.2.0-beta-1`

**Comment by JerryPreissler** [comment]
I just ran into the same error message. My problem was that I had quotation marks around the value for the Koin version in my gradle.properties. Once I replaced
`koin_version= "3.2.0-beta-1"`
with
`koin_version= 3.2.0-beta-1`
I got my build running. 
Looking at your samples I see one difference to by code. I have the Koin dependencies as
`    implementation "io.insert-koin:koin-ktor:$koin_version" // Koin for Ktor
    implementation "io.insert-koin:koin-logger-slf4j:$koin_version" // SLF4J Logger`
(note the missing parentheses). Maybe give it a try?

**Comment by duruer** [comment]
Same issue here:
`implementation("io.insert-koin:koin-logger-slf4j:3.1.5")` works
`implementation("io.insert-koin:koin-logger-slf4j:3.2.0-beta-1")` doesn't work

**Comment by akexorcist** [comment]
In my case, I got an error that my project use Java 1.8 compatibility but this library doesn't supports it. So I removed Java 1.8 compatibility in `build.gradle` and run the project with Java 11 or higher and it worked.

**Comment by chrisjenx** [comment]
Thank you was targeting Java 8

**Comment by arnaudgiuliani** [comment]
thanks for your feedback, I will check #1437 to fix this 👍
