### ISSUE TITLE
Passing Parameters not work - NoParameterFoundException

### ISSUE THREAD

**Issue by LeaveX007** [InsertKoinIO/koin#1303]
Hy,

i have a class something like that

`class MyClassImpl(id:Long) { }`

my scope is that
`
scope(named("MyClass")) {
        scoped<MyClassImpl> { (id: Long) -> BotServiceImpl(id) }
    }
`

I create a instance for thes Scope like that:
`
val scope = getKoin().createScope("MyScope", named("MyClass"))
`
`val MyClassImpl by scope.inject<MyClassImpl>{parametersOf(100L)}`

If the code is starting, then i get an Error
`... Can't get injected parameter #0 from DefinitionParameters[] for type 'java.lang.Long'`

I don´t know why. Can anyone help me please? Thank you.

Br
Mike

**Comment by arnaudgiuliani** [comment]
Not reproduced in 3.2.0. I can pass parameter to scoped definition:

```kotlin
        val scopeId = "user_scope"
        val scopeKey = named("KEY")
        val koin = koinApplication {
            modules(
                module {
                    scope(scopeKey) {
                        scoped { (id : Int) -> Simple.MySingle(id) }
                    }
                }
            )
        }.koin

        val scope = koin.createScope(scopeId, scopeKey)
        val id = 42
        val single by scope.inject<Simple.MySingle> { parametersOf(id) }
        assertEquals(id, single.id)
        scope.close()
```
