### ISSUE TITLE
Koin Annotation not generating binded interfaces that recides in other (project) modules

### ISSUE THREAD

**Issue by LiewJunTung** [InsertKoinIO/koin#1310]
I'm trying out Koin Annotation with the quickstart project that resides in this repository. I tried to move one of the interfaces, "Heater" that was supposed to bind "ElectricHeater" class into another module.  

## Expected Behavior:
```kotlin
...
single(qualifier=null) { org.koin.sample.coffee.component.ElectricHeater() } bind(org.koin.sample.coffee.component.Heater::class)
```
## Actual
![image](https://user-images.githubusercontent.com/4220976/157906866-be8ea278-43e6-4f4d-97cb-4ff4e3e5fadc.png)

**Comment by arnaudgiuliani** [comment]
please on a ticket in https://github.com/InsertKoinIO/koin-annotations project. 

is it a duplicate of this https://github.com/InsertKoinIO/koin-annotations/issues/7?

**Comment by LiewJunTung** [comment]
Indeed! I'll close this issue
