### ISSUE TITLE
singleOf don't work with KoinScopeComponent

### ISSUE THREAD

**Issue by aviadmini** [InsertKoinIO/koin#1324]
**Is your feature request related to a problem? Please describe.**
Using `singleOf` overloads for a class that implements `KoinScopeComponent` doesn't work (`Caused by: org.koin.core.error.NoBeanDefFoundException: |- No definition found for class:'org.koin.core.scope.Scope'. Check your definitions!`)
v3.2.0-beta-1 here

**Describe the solution you'd like**
Ability to use `singleOf` for `KoinScopeComponent`

**Describe alternatives you've considered**
Currently using `single` works because it supplies scope in receiver lambda

**Target Koin project**
Core

**Comment by aviadmini** [comment]
I've checked it, and it looks like it's not applicable for `single` scope, only separately created scopes.

**Comment by arnaudgiuliani** [comment]
yes, as `KoinScopeComponent` won't work with root scope ... just use Koin instance
