### ISSUE TITLE
Fragment scope not automatically linked to activity scope when Activity gets restored

### ISSUE THREAD

**Issue by bmesing** [InsertKoinIO/koin#1328]
**Describe the bug**
This is a follow up on #1087. While the current implementation with the lifecycleScopeDelegate does work, when the activity creates its fragment in "normal" flow it does not work, when the activity is recreated when the application was destroyed in the background. You can reproduce the problem by enabling the "Do not keep activities" toggle in the Dev settings.

The reason is, that on recreation of activities, the order of calling on create is different (first Fragment.onCreate is called and only then Activity.onCreate. This leads again to the situation, that the fragment scope is not linked to the activity scope leading to a crash in my case.
(Android actually does not guarantee any order between onCreate of Fragment and Activity: https://stackoverflow.com/questions/30297978/why-fragments-oncreate-is-sometimes-called-prior-to-activitys-oncreate)

**To Reproduce**
1. Enable "Do not keep activities" toggle in the Dev settings
2. Open activity with fragment
3. Put app to background
4. Bring back to foreground
5. fragment scope not linked to activity scope

**Expected behavior**
fragment scope linked to activity scope

**Workaround**
Link fragment scope to activity scope in onViewCreated

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        // this is a workaround
        val activityScope = (activity as? AndroidScopeComponent)?.scope
        if (activityScope != null) {
            scope.linkTo(activityScope)
        }
    }

**Koin project used and used version (please complete the following information):**
 koin-android version 3.1.5

**Comment by bmesing** [comment]
Note that every app relying on the activity/fragment scope linking will see problems/crashes due to this issue.

**Comment by arnaudgiuliani** [comment]
see resolution in https://github.com/InsertKoinIO/koin/issues/1356
