### ISSUE TITLE
NoBeanDefFoundException when running multiple tests which start and stop koin

### ISSUE THREAD

**Issue by cholwell** [InsertKoinIO/koin#1331]
**Describe the bug**
I have multiple ktor tests which call startKoin and stopKoin in the before and after methods respectively. When run individually there are no problems. When attempting to run all the tests using Gradle / IDE only the first test which calls startKoin actually uses the definitions in the provided modules. All further tests error with:

`org.koin.core.error.NoBeanDefFoundException: |- No definition found for class:'SomeClass'. Check your definitions!`

**To Reproduce**
The following code shows the set-up of the tests.

 `
 
    open class ApplicationTest(private val ktorModules: Application.() -> Unit = {}) {

    private lateinit var server: NettyApplicationEngine
    lateinit var db: MongoDb

    @Container
    val mongo = MongoDBContainer(DockerImageName.parse("mongo:4.2"))

    @Before
    fun setup() {
        mongo.start()
        startKoin {
            load(coreModule, featureModule)
        }
        val env = applicationEngineEnvironment {
            module {
                database(
                    connectionDetails = DatabaseConnectionDetails(
                        mongo.host,
                        mongo.firstMappedPort
                    )
                )
                this@ApplicationTest.ktorModules
            }
            connector {
                host = "127.0.0.1"
                port = 8080
            }
        }
        server = embeddedServer(Netty, env).start(false)
        db = KMongo.createClient("mongodb://${mongo.host}:${mongo.firstMappedPort}").coroutine.getDatabase("db")
    }

    @After
    fun teardown() {
        mongo.stop()
        stopKoin()
        server.stop(1000, 10000)
    }
    }
`

**Expected behaviour**
Koin applications are distinct between tests and modules are loaded correctly.

**Koin project used and used version :**
 io.insert-koin:koin-core:3.2.0-beta-1

**Comment by VikiBDev** [comment]
Getting the exact same issue on Koin 3.1.6, would be great to get some pointers
