### ISSUE TITLE
[QUESTION] Is there a sample of how to setup && use the framework with Ktor 2.0.1?

### ISSUE THREAD

**Issue by dodalovic** [InsertKoinIO/koin#1334]
Thank you 🙂

**Comment by ESchouten** [comment]
For now you need to update the ktor plugin yourself.
Example: https://github.com/ESchouten/CleanArchitecture

**Comment by arnaudgiuliani** [comment]
https://github.com/InsertKoinIO/koin-getting-started/tree/main/getting-started-koin-ktor
