### ISSUE TITLE
LeakCanary integration?!

### ISSUE THREAD

**Issue by valeriyo** [InsertKoinIO/koin#1335]
**Is your feature request related to a problem? Please describe.**
I'd like to use LeakCanary on Android (https://square.github.io/leakcanary/) to watch objects created by Koin (single/scoped or factory) so that all those objects are garbage-collected when the corresponding scope is closed.

**Describe the solution you'd like**
Ideally, there is an integration library that would be sufficient to include in a gradle file.

**Describe alternatives you've considered**
I've implemented this by overloading ScopeDSL to capture all instances into a WeakReference collection, which I go through when the scope is closed and add existing objects to LeakCanary to watch.

**Comment by arnaudgiuliani** [comment]
And just using it in your app doesn't help you?
