### ISSUE TITLE
Use Kotlin's scope control for module DSL (@DslMarker)

### ISSUE THREAD

**Issue by valeriyo** [InsertKoinIO/koin#1338]
**Describe the solution you'd like**
@DslMarker should be used to prevent unsupported usage of Koin's module DSL (e.g. putting `scope` inside of another `scope`)... See https://kotlinlang.org/docs/type-safe-builders.html#scope-control-dslmarker

**Comment by Pfoerd** [comment]
I just wanted to open a similar feature request :) . We would really like to see this DSL marker support too as this would make all the "deprecated" functions to avoid misuse of the DSL obsolete.
We have a lot of custom DSL extensions so it would be nice if the DSL marker was open to use outside of the library too!

**Comment by Pfoerd** [comment]
@arnaudgiuliani could you please re-open this one. I think it is still on on the roadmap for 3.3.0, isn't it?

**Comment by arnaudgiuliani** [comment]
added to koin 3.3 👍 91397a91ea6e2f56b8e59e9c59d4bb7ddd754092
