### ISSUE TITLE
Migration from koin 3.1.5 to 3.1.6: an extension ComponentCallbacks.getViewModel no more exists?

### ISSUE THREAD

**Issue by nordovento** [InsertKoinIO/koin#1340]
Hello, 
Thank you so much for your library.

I've updated Koin from 3.1.5 to 3.1.6 and I cannot use anymore the following fun:
`inline fun <reified T : ViewModel> ComponentCallbacks.getViewModel(
        qualifier: Qualifier? = null,
        noinline owner : ViewModelOwnerDefinition = { ViewModelOwner.from(this as ViewModelStoreOwner, this as? SavedStateRegistryOwner) },
        noinline parameters: ParametersDefinition? = null,
): T {
        return getViewModel(qualifier, T::class, owner,  parameters = parameters)
}`
Does this extension anymore exists? What is supposed to use instead?

Thanks !

**Comment by thadcodes** [comment]
I think the only thing you can do is `viewModel(qualifier, owner, parameters).value`. Or at least that's what I'm doing for the same problem

**Comment by arnaudgiuliani** [comment]
getViewModel are tied to Activity/fragment, else API under the hood is not working well
