### ISSUE TITLE
Add singleOf for `11..22` params

### ISSUE THREAD

**Issue by hoc081098** [InsertKoinIO/koin#1342]
I use `singleOf(::MyClass)`, but `MyClass` constructor has 11 params.
Version 3.2 has provided `singleOf` with below 11 params

**Comment by egorikftp** [comment]
You are crazy :)

It's not a problem to create your own extension. It's just a few changes + import.

**Comment by hoc081098** [comment]
@egorikftp I have created that extension functions, but I think it will be better if they are defined in this library itself

**Comment by hoc081098** [comment]
and Kotlin stdlib has 0 to 22 params functional type (https://github.com/JetBrains/kotlin/blob/master/spec-docs/function-types.md#functions-with-022-parameters-at-runtime), so why not provides 0 to 22 params `singleOf` :))

**Comment by marcellogalhardo** [comment]
The original design was up to 22 exactly to be consistent with the Kotlin STD Lib but after discussing with @arnaudgiuliani we decided to reduce it to 10. You can see the public discussion [here](https://github.com/InsertKoinIO/koin/pull/1186#issuecomment-954498319).

As for now, I would say the way to go is to introduce extension functions and handle them by yourself.

If more people have similar use cases, maybe we can revisit the discussion with @arnaudgiuliani approval.

**Comment by JajaComp** [comment]
I am forced to copy extensions to each of my projects due to the fact that each has classes with 10+ dependencies.  Usually these are reports or synchronization modules.  Too bad it's not in the library.

**Comment by arnaudgiuliani** [comment]
Yeah really something I can consider :) I remember our conversation @marcellogalhardo :D

**Comment by arnaudgiuliani** [comment]
we will update the `new` oeprator to avoid not over perturbate all the API: 

```kotlin
single { new(::YourBigBigClass) }
```
