### ISSUE TITLE
Cannot inject to fragment with ScopeActivity

### ISSUE THREAD

**Issue by aleksey-ho** [InsertKoinIO/koin#1356]
I'm trying to inject some dependency to both activity and fragment using Koin and I expect it to live as long as activity lives, but it turned out a headache for me. 

I managed to create a module that resolves MainRouter, inject it into an activity, but it doesn't work for a fragment.

    val appModule = module {
        scope<MainActivity> {
            scoped { MainRouter() }
        }
    }

MainActivity extends ScopeActivity, MyFragment extends ScopeFragment.

in MainActivity `private val router : MainRouter by inject()` works fine, but in MyFragment it throws org.koin.core.error.**NoBeanDefFoundException**: No definition found for class:'com.example.app.MainRouter'. Check your definitions!

Finally I managed to inject, but it doesn't look pretty

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        val scopeId = scopeActivity!!.getScopeId()
        scope.linkTo(getKoin().getScope(scopeId))
        mainRouter = get()
        ...

I also don't like that `scopeActivity` can't be accessed in the init method. Does this mean that activity scoped dependencies cannot be resolved in fragment using `by inject()`?

**Comment by aballano** [comment]
This started happening to me as well after updating from `3.2.0-beta-1` to `3.2.0`, same case as above

To workaround it I used a similar approach as above:

```
override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        //...
        scopeActivity?.scope?.let {
            scope.linkTo(it)
        }
        //...
}
```

**Comment by mast-eso** [comment]
We're facing the same issue which is really blocking at the moment. The solution @Pfoerd has proposed sounds good to me.

**Comment by arnaudgiuliani** [comment]
@Pfoerd ok, interesting 👌

**Comment by arnaudgiuliani** [comment]
also link to https://github.com/InsertKoinIO/koin/issues/1328

**Comment by arnaudgiuliani** [comment]
After rethinking about the solution and checking with your feedback, I have a proposal for 3.2.1: a simpler API more than lazy delegates (harder to use and follow for lifecycle).

The only breaking result in`AndroidScopeComponent`:

```kotlin
interface AndroidScopeComponent {
    var scope: Scope?
    fun requireScope() : Scope = scope ?: error("Trying to access Android Scope on '$this' but scope is not created")
}
```

The idea is to have clear and simple API to use: create a scope and bind it when we need it.

For Scope Android classes, the implementation will become:

```kotlin
abstract class ScopeActivity(
    @LayoutRes contentLayoutId: Int = 0,
) : AppCompatActivity(contentLayoutId), AndroidScopeComponent {


    override var scope: Scope? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        createActivityScope()
    }
}
```

```kotlin
abstract class RetainedScopeActivity(
    @LayoutRes contentLayoutId: Int = 0,
) : AppCompatActivity(contentLayoutId), AndroidScopeComponent {

    override var scope: Scope? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        createActivityRetainedScope()
    }
}
```

```kotlin
abstract class ScopeFragment(
    @LayoutRes contentLayoutId: Int = 0,
) : Fragment(contentLayoutId) , AndroidScopeComponent {

    override var scope: Scope? = null

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        createFragmentScope()
    }
}
```

The idea is to provide the following API:
- `createActivityScope()` create, bind to lifecycle and set scope to `scope` field (Activity as scope source)
- `createActivityRetainedScope()` create, back to ViewModel support and set scope to `scope` field (no source to avoid leak)
- `createFragmentScope()` create, bind to lifecycle and set scope to `scope` field (Fragment as scope source). Link to parent Activity scope is also done 

One good thing is that Injection API (ViewModel ...) now take care to resolve the current scope in a lazy way.

Lazy delegates API are deprecated. Please now use those new API.
