### ISSUE TITLE
`Scope.refreshScopeInstance` is not documented and is not well-behaved

### ISSUE THREAD

**Issue by valeriyo** [InsertKoinIO/koin#1357]
1. There is no mention of the `Scope.refreshScopeInstance` method in official docs (https://insert-koin.io/docs/reference/koin-core/scopes)

2. `Scope.refreshScopeInstance` has no effect if the instance of the scoped class does not exist. As a workaround, I call `scope.get<Foo>()` before calling `scope.refreshScopeInstance(clazz = Foo:class, instance = Foo("bar"))` - creating a "throw-away" instance of `Foo`, which may be costly and is unnecessary.

Q: Is it the only way how I can customize a scope instance? I need each scope instance to return a unique instance of scoped `Foo` class.

**Comment by arnaudgiuliani** [comment]
this function will be deprecate and closed for next releases
