### ISSUE TITLE
activity.getViewModel(named("XXX")) is returning wrong viewmodel after Koin 3.1.5

### ISSUE THREAD

**Issue by SeanBlahovici** [InsertKoinIO/koin#1364]
So I tried updating to 3.2.0 from Koin 2.x and I found an obscure bug. I reverted to lower versions until the problem was no longer present, which is **version 3.1.5. Meaning the bug was introduced in 3.1.6**.

I have two subtypes of an abstract viewModel that are scoped to my MainActivity. I first load the first type using a named qualifier (using the extension function activity.getViewModel() - This is from a non activity or fragment class. But after this,  I try getting an instance of the other subtype using a differently named qualifier, but end up receiving the previously loaded type. This only happens after 3.1.5.

**To Reproduce**
1. Define two implementations of an abstract viewModel in a koin module. Example:
`    viewModel<AbstractViewModel>(named("First type")) { ConcreteViewModel1(get(), get(), get()) }
    viewModel<AbstractViewModel>(named("Second type")) { ConcreteViewModel2(get(), get(), get()) }`

2. Pass an activity instance to platform agnostic class.
3. On that instance, call the extension function getViewModel(named("First type")). It should return the correct type (ConcreteViewModel1)
4. After that, try calling activity.getViewModel(named("Second type")). Notice the type returned is the wrong type, still ConcreteViewModel1

**Koin project used and used version (please complete the following information):**
 koin-android 3.1.6 & koin-android 3.2.0

**Comment by ronaldkieft** [comment]
If experience the same problem when using 3.1.6. I do however only experience the problem when retrieving named view models that are scoped to a navigation graph. When retrieving view models in the regular way (using the default ViewModelOwner) the named qualifier works still as expected in 3.1.6.

**Comment by arnaudgiuliani** [comment]
Google ViewModel API doesn't allow as we use it right now doesn't allow to use qualifier as we were using it.

Koin 3.3.0 bring a great rework on ViewModel API, let's fix it on this version then

**Comment by arnaudgiuliani** [comment]
ViewModel API has been fixed is available in `koin-android` 3.3.0 👍 
https://github.com/InsertKoinIO/koin/pull/1459

**Comment by Wirling** [comment]
@arnaudgiuliani this problem still doesn't seem to be fixed in version 3.3.0. I can still reproduce it as described by @SeanBlahovici. I also encounter this problem with koinNavGraphViewModel.

**Comment by Hungon** [comment]
I've also encountered the same problem even in v3.3.0.

**Comment by irgaly** [comment]
@arnaudgiuliani @SeanBlahovici
Is this problem fixed? If it is not fixed, please reopen this issue for tracking this problem.
