### ISSUE TITLE
NPE when declaring scope after ViewModel after migration from `3.1.5` to `3.2.0`

### ISSUE THREAD

**Issue by vtiahotenkov-beat** [InsertKoinIO/koin#1370]
Hello! Our team faced an issue after migrating from Koin `3.5.1` to `3.2.0`

**Describe the bug**
**given**
`Activity`, implementing `AndroidScopeComponent` (providing scope by either `activityScope` or `activityRetainedScope`) and also injecting `ViewModel` by `viewModel` delegate

**when**
`scope` is declared **_after_** `viewModel`

**then**
NPE is observed:
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.koin.core.scope.Scope org.koin.androidx.scope.LifecycleScopeDelegate.getValue(androidx.lifecycle.LifecycleOwner, kotlin.reflect.KProperty)' on a null object reference
```

When downgraded back to `3.5.1` everything works as expected

**To Reproduce**
A sample project illustrating the problem is available [here](https://github.com/vtiahotenkov-beat/KoinTest)

**Expected behavior**
`Scope` and `ViewModel` declaration order doesn't matter

**Koin project used and used version (please complete the following information):**
`koin-core:3.2.0`, `koin-android:3.2.0`

**Comment by arnaudgiuliani** [comment]
Yes, in your `onCreate` part you should resolve the `scope` before accessing the ViewModel.  This is a workaround for you. check the `ScopeActivity` class for more details: https://github.com/InsertKoinIO/koin/blob/main/android/koin-android/src/main/java/org/koin/androidx/scope/ScopeActivity.kt

A better Scope/VM API need to be rework for later.
