### ISSUE TITLE
scope viewmodel to parent

### ISSUE THREAD

**Issue by periva101** [InsertKoinIO/koin#1376]
**Is your feature request related to a problem? Please describe.**
I want to share a ViewModel between sets of fragment, tow cases
1. after fragment A is opened the ViewModel keeps alive in the flow a>c>d , until a is pop
2. fragment A is opened , and I can define a set of fragments that will share the same ViewModel, like bottom sheets... 

**Target Koin project**
koin core

![image](https://user-images.githubusercontent.com/52367616/177474935-78932edb-55b8-4603-9d37-15843daa945d.png)

**Comment by bmesing** [comment]
You might take a look at my ticket:
https://github.com/InsertKoinIO/koin/issues/1385
Maybe our approach can help you a bit with what you are trying to achieve

**Comment by arnaudgiuliani** [comment]
Did you tried to share ViewModel and specify the right owner? 

also can be good to check @bmesing ticket with #1385 👍
