### ISSUE TITLE
3.2.0 what?

### ISSUE THREAD

**Issue by valeriyo** [InsertKoinIO/koin#1379]
The README says, that 3.2.0 is available:

<img width="408" alt="image" src="https://user-images.githubusercontent.com/7052801/177930825-c18739cd-356f-453a-af25-c29d9937b605.png">

However, there is no such tag (or release):

<img width="368" alt="image" src="https://user-images.githubusercontent.com/7052801/177930903-0c202ed8-adfb-44e6-ba32-78a0fdc33a23.png">

**Comment by nachtien** [comment]
It would be really helpful if Github releases were used.

**Comment by arnaudgiuliani** [comment]
yep, will be updated soon on tags & changelog 👍
