### ISSUE TITLE
NoBeanDefFoundException but scope is already defined

### ISSUE THREAD

**Issue by gabhernandes** [InsertKoinIO/koin#1381]
I'm trying to solve this issue: I'm receiving a crash whenever i try to click on a push notification in a fragment, that would redirect me to another fragment in the app.

I defined my module like this: 

    scope(named<MainActivity>()) {
                factory<DetailContract.Presenter> { (view: DetailContract.View) ->
                    DetailPresenter(
                        view = view,
                        monitoring = get(),
                        api = get(),
                        storage = get(),
                        imageProvider = get()
                    )
                }
            }

In my fragment i did this:  

    private val presenter: DetailContract.Presenter by lazy {
            scope.get {
                parametersOf(this)
            }
        }
 

    override val scope: Scope by fragmentScope()

And in my activity i did like this:  

     private val presenter: MainContract.Presenter by inject {
                parametersOf(this)
            }
    
        override val scope: Scope by activityScope()

However it isn't working even though i'm using activity scope. Before i wasn't using and it didn't work also. Do you guys have any ideas?

This is the crash i'm receiving:

    Caused by: org.koin.core.error.NoBeanDefFoundException: |- No definition found for class:'br.example.detail.DetailContract$Presenter'. Check your definitions!
            at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:304)
            at org.koin.core.scope.Scope.resolveValue(Scope.kt:274)
            at org.koin.core.scope.Scope.resolveInstance(Scope.kt:241)
            at org.koin.core.scope.Scope.get(Scope.kt:204)

Koin version is 3.1.6

**Comment by wax911** [comment]
Just out of curiosity, isn't this happening because you scoped `DetailContract.Presenter` to `MainActivity` which intern means that `activityScope` in `MainActivity` will resolve the bean definition. In the case of the fragment you used `fragmentScope` which resolves bean definitions that match `scope(named<FRAGMENT_NAME>())`.

I might be mistaken in saying this but I believe that you might need to have a shared scope for both your activity and fragment that way you can access `DetailContract.Presenter`, however managing how you create this scope and handle its lifecycle would be completely up to you. (a quick and dirty way would be to resolve your parent activity scope, if your parent activity is MainActivity from your fragment and use that to fetch your presenter instead of using fragmentScope)

> Something to look out for in addition to this is the fact that you're passing in a view to your presenter via it's constructor, if you decide to create a shared scope between your activity and fragment this might prove to be an issue, depending what you use `view` is

**Comment by arnaudgiuliani** [comment]
First question: why do you need a scope here, as you are creating 2 different instances?

Which scope is failing? can you check which one is failing?

**Comment by gabhernandes** [comment]
Hi Arnauld. I don't really know which scope it is. The only thing is now is that is something with `DetailContract$Presenter` and MainActivity is his parent Activity.

**Comment by gabhernandes** [comment]
Before i defined my module like this but same issue happened: 
 ```
factory<DetailContract.Presenter> { (view: DetailContract.View) ->
                DetailPresenter(
                    view = view,
                    monitoring = get(),
                    api = get(),
                    storage = get(),
                    imageProvider = get()
                )
            }
        }
```

**Comment by gabhernandes** [comment]
> Just out of curiosity, isn't this happening because you scoped `DetailContract.Presenter` to `MainActivity` which intern means that `activityScope` in `MainActivity` will resolve the bean definition. In the case of the fragment you used `fragmentScope` which resolves bean definitions that match `scope(named<FRAGMENT_NAME>())`.
> 
> I might be mistaken in saying this but I believe that you might need to have a shared scope for both your activity and fragment that way you can access `DetailContract.Presenter`, however managing how you create this scope and handle its lifecycle would be completely up to you. (a quick and dirty way would be to resolve your parent activity scope, if your parent activity is MainActivity from your fragment and use that to fetch your presenter instead of using fragmentScope)
> 
> > Something to look out for in addition to this is the fact that you're passing in a view to your presenter via it's constructor, if you decide to create a shared scope between your activity and fragment this might prove to be an issue, depending what you use `view` is

Before i used without activity scope and same issue happened :(

**Comment by gabhernandes** [comment]
> wax911

I tried to use requireActivityScope() instead of fragmentScope() but same error happened

**Comment by gabhernandes** [comment]
When the Fragment was called by deeplink it wasn't loading the modules, because it doesn't call the feature's activity, so it wasn't loading the `loadKoinModules` that was in the activity. To solve this issue i called `loadKoinModules` inside the Fragment
