### ISSUE TITLE
Question: Classic DSL vs. Constructor DSL

### ISSUE THREAD

**Issue by StephanSchuster** [InsertKoinIO/koin#1383]
A short question about a subtle difference I encountered between the old "Classical DSL" and the new "Contructor DSL":

[In your docs](https://insert-koin.io/docs/quickstart/kotlin#declaring-dependencies) you basically say ... 

```
single { HelloServiceImpl(get()) as HelloService }   // Classic DSL variant 1
single<HelloService> { HelloServiceImpl(get()) }     // Classic DSL variant 2
```
is the same as
```
singleOf(::HelloServiceImpl) { bind<HelloService>() }   // Constructor DSL
```

BUT:
* The old/classic expression will match type `HelloService` ONLY (as stated [here](https://insert-koin.io/docs/reference/koin-core/definitions#definition-binding-an-interface))
* The new/constructor expression will match BOTH types, `HelloService` AND `HelloServiceImpl`

Is this understanding correct?
Is this behavior intended?

Thanks for clarifying.

**Comment by arnaudgiuliani** [comment]
> Is this understanding correct?
Yes

> Is this behavior intended?
Yes, no problem here. But yes, we could imagine something to help bind both types 🤔
