### ISSUE TITLE
`by fragmentScope()` could automatically set the Fragment as source

### ISSUE THREAD

**Issue by bmesing** [InsertKoinIO/koin#1385]
**Is your feature request related to a problem? Please describe.**
`Fragment.fragmentScope()` does not automatically set the Fragment as the `source` of the created scope. Due to this, the fragment cannot be resolved from within the scope. This is different from the `ComponentActivity.activityScope()` where the activity is automatically set as the `source`.

Our use case is to have an integrator fragment controlling the navigation flow of a use case that acts in a similar way as the activity. This pattern works perfectly fine when the activity is controlling the navigation but not if it is a fragment (we call it IntegratorFragment).

```
internal val myUseCaseModule = module {
    scope<MyIntegratorFragment> {
        fun getCoordinator(scope: Scope) : MyCoordinator = scope.get<MyIntegratorFragment>().coordinator

       // view model controlling the use case navigation, tied to the integrator fragment.
        viewModel<MyCoordinator> {
            MyCoordinator()
        }

      // view model of a single screen within the use case
        viewModel<MyViewModel> {
                val coordinator = getCoordinator(this)
                MyModelImpl(
                    onNavigationTriggered = coordinator::navigateTo,
                )
        }
    }
}
```

Inside the screen fragment (i.e. MyFragment) we call:
```
    protected fun linkToAllParentFragmentScopes() {
        var parentFragment = this.parentFragment
        while (parentFragment != null) {
            if (parentFragment is AndroidScopeComponent) {
                scope.linkTo(parentFragment.scope)
            }
            parentFragment = parentFragment.parentFragment
        }
    }
```

**Describe the solution you'd like**
`by fragmentScope()` could automatically set the Fragment as source. We have created our own extension function to do that.

```
/**
 * Provide scope tied to Fragment.
 *
 * In addition to koin fragmentScope this initializer also sets Fragment as "source" for the scope, allowing to
 * get<>() the fragment itself within its scope.
 */
fun Fragment.myFragmentScope() = LifecycleScopeDelegate<Fragment>(this,this.getKoin()){ koin: Koin ->
    val scope = koin.createScope(scopeId = getScopeId(), qualifier = getScopeName(), source = this)
    val activityScope = activity?.getScopeOrNull()
    activityScope?.let { scope.linkTo(it) }
    scope
}
```

**Target Koin project**
Koin Android

**Comment by arnaudgiuliani** [comment]
duplicate with https://github.com/InsertKoinIO/koin/issues/1328
