### ISSUE TITLE
SavedStateHandle is not "reinjected" in a stateViewModel on system-initiated process death

### ISSUE THREAD

**Issue by Narayane** [InsertKoinIO/koin#1386]
**Describe the bug**
StateViewModel SavedStateHandle attribute is always null after a [system-initiated process death](https://developer.android.com/topic/libraries/architecture/saving-states#options)

```
class InsuranceOnboardingWorkflowActivity : BaseActivity() {

    private val viewModel by stateViewModel<InsuranceOnboardingWorkflowActivityViewModel>(state = { intent.extras!! })

    companion object {

        fun getIntent(context: Context, source: AppSource, insuranceId: String? = null): Intent {
            return Intent(context, InsuranceOnboardingWorkflowActivity::class.java).apply {
                putExtra(InsuranceOnboardingWorkflowActivityViewModel.EXTRA_SOURCE, source.name)
                insuranceId?.let {
                    putExtra(InsuranceOnboardingWorkflowActivityViewModel.EXTRA_INSURANCE_ID, it)
                }
            }
        }
    }
```
```
val insuranceModule = module {

    viewModel { InsuranceOnboardingWorkflowActivityViewModel(get(), get(), get(), get(), get()) }
```
```
class InsuranceOnboardingWorkflowActivityViewModel(
    stateHandle: SavedStateHandle,
    internal val logRepository: LogRepository,
    internal val insuranceRepository: InsuranceRepository,
    internal val premiumRepository: PremiumRepository,
    internal val userRepository: UserRepository
) : LRViewModel() {

    var source: AppSource = AppSource.valueOf(stateHandle.get<String>(EXTRA_SOURCE)!!)
```
**To Reproduce**
1. from AS, run app and start relative activity
2. put app in background
3. in AS, into logcat tab, click on Terminate App button (to simulate system-initiated process death)
4. onto relative device, click on app "window" in "app carrousel" to "restore" app

**Expected behavior**
On app "restoration", viewmodel SavedStateHandle attribute should not be null

**Koin project used and used version (please complete the following information):**
 - `koin-core version 3.1.2`
 - `androidx.lifecycle:lifecycle-viewmodel-savedstate version 2.4.1`

**Comment by arnaudgiuliani** [comment]
thanks for you feedback

**Comment by Rayhan-kh** [comment]
On app "restoration", getting null for SavedStateHandle attributes 

```
private val viewModel: PaxViewModel by stateViewModel(owner = {
        findNavController().getViewModelStoreOwner(
            R.id.pax_graph
        )
    })
```
```
class PaxViewModel(private val stateHandle: SavedStateHandle) : ViewModel() {

    var surName: String = stateHandle["surName"] ?: ""
    var givenName: String = stateHandle["givenName"] ?: ""

    init {
        Log.d("surName", stateHandle["surName"] ?: "")
        Log.d("givenName", stateHandle["givenName"] ?: "")
    }

    fun saveState() {
        stateHandle["surName"] = surName
        stateHandle["givenName"] = givenName
    }

    fun clearSavedState() {
        stateHandle["surName"] = null
        stateHandle["givenName"] = null
    }
}

```


### Koin project used and used version (please complete the following information):


   - koin-core version 3.2.0
    androidx.lifecycle:lifecycle-viewmodel-savedstate version 2.5.1

**Comment by mrmike** [comment]
> Google has reworked SavedState instance creation API and how it's passing around for ViewModels.

Could you elaborate more on what has changed? 

Thanks

**Comment by arnaudgiuliani** [comment]
The VIewModel API has been revamped with the latest lifecycle library in 2.5.1. This implies that `SavedStateHandle` is created with the right extras (thanks to the lifecycle library update in 2.5.1). You can have a look to the full PR https://github.com/InsertKoinIO/koin/pull/1459

More details on Google API: https://developer.android.com/jetpack/androidx/releases/lifecycle#2.5.1

Don't hesitate to give feedback on `koin-android` 3.3.0 🙏
