### ISSUE TITLE
Backport 2.1.x APIs in 3.1.x

### ISSUE THREAD

**Issue by paristote** [InsertKoinIO/koin#1387]
**Describe the bug**
Few APIs from Koin 2.1.6 are still missing in 3.1.6 and are affecting our migration to the latest Koin version.

**To Reproduce**
1. Update the Koin library groupID, artifactID and version in build.gradle
2. Build project
3. See error

```
Cannot find a parameter with this name: override
Unresolved reference: viewmodel
Type mismatch: inferred type is ParametersDefinition? /* = (() -> ParametersHolder)? / but ParametersDefinition? / = (() -> DefinitionParameters)? */ was expected
```

**Expected behavior**
Following-up on #1212, we want to backport the missing APIs to the 3.1.x line (or 3.2.x if you prefer) so we can easily update the Koin library. We would then be able to make the transition to the new APIs progressively.

**Koin project used and used version (please complete the following information):**
`koin-androidx-viewmodel version 2.1.6`

**Comment by paristote** [comment]
Thanks @arnaudgiuliani , I'll keep updating this ticket if we find more APIs missing in 3.1.x.

**Comment by arnaudgiuliani** [comment]
this is also a breaking API, can you check more in details to fix those new kind of params?

**Comment by paristote** [comment]
@arnaudgiuliani please add https://github.com/fpr0001 as a participant, he should be able to take over from me.

**Comment by arnaudgiuliani** [comment]
he can freely propose a PR or open an issue. What's the problem here? 🤔

**Comment by arnaudgiuliani** [comment]
Lack of activity here. Please reopen a ticket if you need.
