### ISSUE TITLE
get all binds with annotation

### ISSUE THREAD

**Issue by alessandroToninelli** [InsertKoinIO/koin#1388]
there's a way to get all object that bind same type with koin annotation 1.0.1?

```

@Single(binds = [Base::class])
class DerivedA(): Base(){
}

@Single(binds = [Base::class])
class DerivedB(): Base(){
  
}

@Single
class DerivedManager(vararg val base:  Base){

    fun print(){

        base.forEach {
            println(it)
        }
    }

}

```

i get only the last one

**Comment by arnaudgiuliani** [comment]
yes, there is a current proposal for that https://github.com/InsertKoinIO/koin-annotations/pull/38 👍

**Comment by alessandroToninelli** [comment]
also think about setting a dependency injection order when I use getAll. In the example above if I wanted to instantiate the DerivedB class first I can't. This case can happen in the case in the DerivedB class instance dependencies that serve the DerivedA class

**Comment by arnaudgiuliani** [comment]
you mean, ordering by type names?
