### ISSUE TITLE
Add qualifier support to koinNavGraphViewModel() extension

### ISSUE THREAD

**Issue by ronaldkieft** [InsertKoinIO/koin#1396]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Recently the koinNavGraphViewModel() extension was extended with support for parameters. It would however be nice when the extension function also supports qualifiers.

**Describe alternatives you've considered**
Currently I use my own variant of the extension function which does support qualifiers. It would however be better if I could just use the koinNavGraphViewModel() extension function.

**Target Koin project**
koin-androidx-navigation

**Comment by arnaudgiuliani** [comment]
fixed by #1397
