### ISSUE TITLE
allowOverride(false) is not enforced when the override is in a different (linked) scope.

### ISSUE THREAD

**Issue by valeriyo** [InsertKoinIO/koin#1398]
**Describe the bug**
I initialize Koin with `allowOverride(false)` for safety, and in the most basic scenarios, it works:
```
    startKoin {
      allowOverride(false)
      modules(
        module {
          single { "String" }
          single { "String" } // -> throws DefinitionOverrideException: Already existing definition...
        },
      )
    }
```
AND
```
    startKoin {
      allowOverride(false)
      modules(
        module {
          scope(named("foo")) {
            scoped { "String" }
            scoped { "String" } // -> throws DefinitionOverrideException: Already existing definition...
          }
        },
      )
    }
```

However, the `allowOverride(false)` becomes useless across scopes:

```
    startKoin {
      allowOverride(false)
      modules(
        module {
          single { "String" }
          scope(named("scope")) {
            scoped { "String" } // --> Should throw, but it doesn't.
          }
        },
      )
    }
```

When scope instances are created and linked (using `linkTo`) -- the `allowOverride(false)`  also doesn't work.

**Expected behavior**
I expect `allowOverride(false)` to enforce "no redefinitions" rule when scopes are linked with linkTo (either explicitly, or implicitly for the root scope)

**Koin project used and used version:**
`3.2.0`

**Comment by arnaudgiuliani** [comment]
a more delicate case here 🤔 it's not override but shadowing ... let me check

**Comment by arnaudgiuliani** [comment]
Linking is a dynamic behaviour where allowing override is a protecting you at start. AS I said, here it"s a more a shadowing aspect of scope, where it will find the closest definition first.

**Comment by pablichjenkov** [comment]
I feel like, if the Definitions belong to separate scopes, it shouldn't throw. Each scope will provide them independently, I don't see why it should be throw in such a case.

**Comment by arnaudgiuliani** [comment]
It's more about a definition overriding another one, not about instances.
