### ISSUE TITLE
[Android] activityRetainedScope is broken for multiple instances of the same Activity class

### ISSUE THREAD

**Issue by Pfoerd** [InsertKoinIO/koin#1399]
**Describe the bug**
If there are multiple Activities of the same class on the task stacks - e.g. because one started the same Activity multiple times - all of them share the same activityRetainedScope.

**To Reproduce**
1. Open an Activity that uses activityRetainedScope and injects a `single` type
2. Send an Intent that opens the same Activity again
3. The first and the second instance of the activity share the same instance of the `single` type

**Expected behavior**
All Activties of the same Activity class on the task stack should have their own instance of activityRetainedScope and therefore don't share e.g. any `single`s.

**Koin project used and used version (please complete the following information):**
`Koin 3.2`

**Detailed Analysis and Proposed solution**
At [this point of LifecycleViewModelScopeDelegate](https://github.com/InsertKoinIO/koin/blob/c954e53959cf982725ca33c9680acb650c63da52/android/koin-android/src/main/java/org/koin/androidx/scope/LifecycleViewModelScopeDelegate.kt#L49) (and [here](https://github.com/InsertKoinIO/koin/blob/c954e53959cf982725ca33c9680acb650c63da52/android/koin-android/src/main/java/org/koin/androidx/scope/LifecycleViewModelScopeDelegate.kt#L29) too, see below) the current implementation will always return the same scope for all instances of an Activity type as it checks it "by class name". Instead, the `ScopeHandlerViewModel` should be checked if there is yet an existing retained scope for this activity. 

Please also have a look at the cached `_scope` too as it is currently set in the `init` block and therefore the check in `getValue` will always return the cached one.

**Comment by Pfoerd** [comment]
@arnaudgiuliani could you please have a look on this regression? Would be great if it made it in 3.2.1 as it currently prevents us from using activityRetainedScope.

**Comment by gustavobarbosab** [comment]
I had a problem like that but in my case, I am using the same module for two instances of the same activity. I load and unload this module in onCreate and onDestroy respectively. 

Then, when I kill the first activity and call the second, the unloadKoinModule of the first activity is called after the loadKoinModule of the second activity, therefore when I try to retrieve a new bean in the second activity the process crashes because the module was unloaded.

**Comment by arnaudgiuliani** [comment]
ok, let me check

**Comment by arnaudgiuliani** [comment]
yes fix for https://github.com/InsertKoinIO/koin/issues/1356 will put `getKoinScope()` inside the lazy block avoiding to try to resolve scopes too earlier. Scope links will be solved too.
