### ISSUE TITLE
KoinApplication.createEagerInstances ("createdAtStart = true") can throw ConcurrentModificationException

### ISSUE THREAD

**Issue by valeriyo** [InsertKoinIO/koin#1400]
**Describe the bug**
Eager instances can be either skipped (not created) or can cause an exception.

**To Reproduce**
Run this test:
```
package com.example

import assertk.assertThat
import assertk.assertions.isEqualTo
import org.junit.Test
import org.koin.core.context.startKoin
import org.koin.dsl.module

class KoinTest {

  @Test
  fun test() {

    var instanceCount = 0
    val koinApp = startKoin { }

    koinApp.modules(
      module {
        single(createdAtStart = true) {
          instanceCount += 1

          koinApp.modules(
            module {
              single(createdAtStart = true) {
                instanceCount += 1
                "String"
              }
            }
          )
        }

        single(createdAtStart = true) {
          instanceCount += 1
          123
        }
      }
    )

    koinApp.createEagerInstances()
    assertThat(instanceCount).isEqualTo(3)
  }
}
```

The result is `java.util.ConcurrentModificationException`

If the two top level `single` declarations are swapped, the test fails with `org.opentest4j.AssertionFailedError: expected:<[3]> but was:<[2]>` (the "String" instance is not created)

**Expected behavior**
test passes

**Koin version:**
`io.insert-koin:koin-core:3.2.0`

**Additional info**
The problem is in `InstanceRegistry.kt`:

```
    internal fun createAllEagerInstances() {
        createEagerInstances(eagerInstances)
        eagerInstances.clear()
    }
    
    private fun createEagerInstances(eagerInstances: HashSet<SingleInstanceFactory<*>>) {
        if (eagerInstances.isNotEmpty()) {
            if (_koin.logger.isAt(Level.DEBUG)) {
                _koin.logger.debug("Creating eager instances ...")
            }
            val defaultContext = InstanceContext(_koin, _koin.scopeRegistry.rootScope)
            eagerInstances.forEach { factory ->
                factory.get(defaultContext)
            }
        }
    }
```

The fix would be something like this (without logging):

```
    internal fun createAllEagerInstances() {
        val defaultContext = InstanceContext(_koin, _koin.scopeRegistry.rootScope)
        while (eagerInstances.isNotEmpty()) {
            eagerInstances.toList()
               .also { eagerInstances.clear() }
               .forEach { it.get(defaultContext) }
        }
    }
```

**Comment by arnaudgiuliani** [comment]
not sure about your case to loop over several `koinApp.modules` 🤔

**Comment by valeriyo** [comment]
The need to loop over several `koinApp.modules` becomes necessary if some `single(createdAtStart = true)` objects when initialized, load more Koin modules.

I'm using dynamic feature modules (https://developer.android.com/guide/playcore/feature-delivery), where a root-scoped `single` DfmManager initializes installed dynamic modules, which in turn load their Koin modules. The dynamically loaded module is represented by this inner expression:

```
          koinApp.modules(
            module {
              single(createdAtStart = true) {
                instanceCount += 1
                "String"
              }
            }
          )
```

Of course, in "real" code, this would be in separate source file(s). The code sample is the shortest I could come up with to reproduce the problem.

Are there any concerns to make the code resistant to concurrent modifications? The performance overhead is making a list copy with `.toList()`. But if `eagerInstances` was a `var` instead of a `val`, a zero-overhead solution would be possible:

```
    internal fun createAllEagerInstances() {
        val defaultContext = InstanceContext(_koin, _koin.scopeRegistry.rootScope)
        while (eagerInstances.isNotEmpty()) {
            eagerInstances.also {
               eagerInstances = mutableListOf()
               it.forEach { it.get(defaultContext) }
            }
        }
    }
 ```

**Comment by arnaudgiuliani** [comment]
Yes I see. This is something that can be part of internal engine work for Koin 4.0. Let's keep it then 👍

**Comment by valeriyo** [comment]
Thanks @arnaudgiuliani

I believe the fix in 3.x would be low-risk -- should I submit a PR?

**Comment by arnaudgiuliani** [comment]
rescheduled for 3.4.1 fixes

**Comment by arnaudgiuliani** [comment]
@valeriyo sorry for the delay. It's an important fix, do you have time for a PR?

**Comment by arnaudgiuliani** [comment]
Can't reproduce `ConcurrentModificationException` in 3.4.1 :/ Let's reopen it if you see something else

**Comment by valeriyo** [comment]
With 3.5.0 the test is still failing:
```
expected:<[3]> but was:<[2]>
Expected :[3]
Actual   :[2]
```

So, wishful thinking doesn't work.

**Comment by valeriyo** [comment]
@arnaudgiuliani put up https://github.com/InsertKoinIO/koin/pull/1663 for review
