### ISSUE TITLE
Special-casing ROOT scope from "regular" scopes is harmful.

### ISSUE THREAD

**Issue by valeriyo** [InsertKoinIO/koin#1401]
Treating "root" scope differently from sub-scopes is the biggest problem with Koin, in my opinion, and I've used Koin on Android for 3+ years. If I squint really hard, I could see where that's coming from - but that "conceptual" distinction causes many practical problems, where the DSL is more complicated than it should be, and/or things don't work as expected in sub-scopes vs root scope. Even the basic DSL "single" vs "scoped" is really strange. The root-scoped "single" is not a *true* singleton, it's scoped to the KoinApplication instance - so all singletons are scoped (to something). In my view, Koin would be greatly improved if:
 - root scope was just the top-most scope, with same DSL and behaviors of regular sub-scopes.
 - the sub-scopes could form a tree (in the DSL) with automatic `linkTo` relationship with the parent.

**Comment by arnaudgiuliani** [comment]
yes this has been some design implementation trying to ditch around root as special scope or not. I believe this could be a good consideration for next major version. 

But this would also break the DSL 🤔
