### ISSUE TITLE
Can't find getViewModel with clazz: KClass<T>

### ISSUE THREAD

**Issue by dongnh311** [InsertKoinIO/koin#1402]
I am using version 3.2.0-beta-1. And when i update to 3.2.0 last version, i can't find method ComponentCallbacks.getViewModel with KClass<T>.
I very need this function to create base Fragment and base Activity.
This is method in 3.2.0-beta-1 : 

@OptIn(KoinInternalApi::class)
fun <T : ViewModel> ComponentCallbacks.getViewModel(
          &emsp;qualifier: Qualifier? = null,
          &emsp;clazz: KClass<T>,
          &emsp;owner : ViewModelOwnerDefinition = { 
               &emsp;&emsp;ViewModelOwner.from(this as ViewModelStoreOwner, this as? 
               &emsp;&emsp;SavedStateRegistryOwner) },
        &emsp;parameters: ParametersDefinition? = null,
): T {
          &emsp;val scope = getKoinScope()
          &emsp;return scope.getViewModel(qualifier, owner, clazz, parameters = parameters)
}

**Comment by arnaudgiuliani** [comment]
For `3.2.1` get back KClass API:

```kotlin
fun <T : ViewModel> ComponentActivity.viewModelForClass(
        clazz: KClass<T>,
        qualifier: Qualifier? = null,
        owner : ViewModelStoreOwner = this,
        state: BundleDefinition? = null,
        parameters: ParametersDefinition? = null,
): Lazy<T> {
        return ViewModelLazy(clazz, { owner.viewModelStore }) {
                getViewModelFactory(owner, clazz ,qualifier, parameters, state, getKoinScope())
        }
}
```

```kotlin
fun <T : ViewModel> Fragment.viewModelForClass(
    clazz: KClass<T>,
    qualifier: Qualifier? = null,
    owner : ViewModelStoreOwner = this,
    state: BundleDefinition? = null,
    parameters: ParametersDefinition? = null,
): Lazy<T> {
    return ViewModelLazy(clazz, { owner.viewModelStore }) {
        getViewModelFactory(owner, clazz ,qualifier, parameters, state, getKoinScope())
    }
}
```

and more generic:

```kotlin
fun <T : ViewModel> getLazyViewModelForClass(
    clazz: KClass<T>,
    owner : ViewModelStoreOwner,
    scope : Scope,
    qualifier: Qualifier? = null,
    state: BundleDefinition? = null,
    parameters: ParametersDefinition? = null,
): Lazy<T> {
    return ViewModelLazy(clazz, { owner.viewModelStore }) {
        getViewModelFactory(owner, clazz ,qualifier, parameters, state, scope)
    }
}
```

**Comment by aytajde** [comment]
Hello, can someone give me an example how to use the getLazyViewModelForClass method?

**Comment by dongnh311** [comment]
> 

First, You need method get Kclass to Class : https://stackoverflow.com/a/1901275/719212
Second : getLazyViewModelForClass() with 3 param like :
getLazyViewModelForClass(
  kclass = method on step 1,
  owner = ViewModelStoreOwner,
  scope = ???
)
