### ISSUE TITLE
NoBeanDefFoundException for SavedStateHandle when upgrading koin-android from `3.1.5` to `3.2.0`

### ISSUE THREAD

**Issue by nikita-bushuev** [InsertKoinIO/koin#1407]
**Describe the bug**
Updating koin-android from `3.1.5` to `3.2.0` causes app crash with `NoBeanDefFoundException` for `SavedStateHandle`. It appears if you define `ViewModel` with `SavedStateHandle` parameter in constructor and retrieve `ViewModel` with `getViewModel()` call (or `by viewModel()`).

**To Reproduce**
I created [sample project](https://github.com/nikita-bushuev/koin-bug-savedstatehandle) to reproduce the bug, but you can also follow these steps:
1. Create basic Android application with koin-android `3.2.0`.
2. Create `ViewModel` class with `SavedStateHandle` parameter in constructor:
```kotlin
class MainViewModel(savedStateHandle: SavedStateHandle) : ViewModel()
``` 
3. Define `ViewModel` in module:
```kotlin
val mainModule = module {
    viewModel { MainViewModel(get()) }
}
```
4. [Start Koin](https://insert-koin.io/docs/quickstart/android/#start-koin) in Application class
3. Retrieve `ViewModel` in Activity's `onCreate`:
```kotlin
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        val viewModel = getViewModel<MainViewModel>()
    }
}
```
5. See error: 
`Caused by: org.koin.core.error.NoBeanDefFoundException: |- No definition found for class:'androidx.lifecycle.SavedStateHandle'. Check your definitions!`

**Expected behavior**
App launches without a crash. For some reason everything works if you replace `getViewModel` with `getStateViewModel` call. 

**Koin project used and used version (please complete the following information):**
no-crash version: `koin-android version 3.1.5`
crash version: `koin-android version 3.2.0`

**Comment by wax911** [comment]
I actually get this exception message on 3.1.6

**Comment by arnaudgiuliani** [comment]
Here you are using `getViewModel<MainViewModel>()` which doesn't trigger SavedStateHandle injection. You need to use the `getStateViewModel()' API instead

**Comment by svenjacobs** [comment]
@arnaudgiuliani Thanks for the clarification. However `getStateViewModel()`  is marked as deprecated in Koin 3.2.0 with the message

```
getStateViewModel will be merged to sharedViewModel - no need anymore of state parameter
```

However I don't find any `getSharedViewModel()` or `getSharedStateViewModel()` function in the Compose artifact of Koin. What am I supposed to do? 🤔

**Comment by arnaudgiuliani** [comment]
no problem for this, I just removed the warning. 

However I will bring a clearer viewModel API, as the current one is getting complex I believe.

**Comment by SiavashB** [comment]
Hi what if we want a viewModel that is NOT shared, but does need SavedStateHandle?
