### ISSUE TITLE
LifecycleScopeDelegate createScope override bug with lifecycle.getScopeId

### ISSUE THREAD

**Issue by tlevavasseur-decathlon** [InsertKoinIO/koin#1414]
**Describe the bug**

LifecycleScopeDelegate constructor let us provide a custom `val createScope` BUT the `private fun createScope()` still uses the default `lifecycle.getScopeId()` which can lead to a bug (infinite scope.links recursion).

**To Reproduce**

the private version checks if there already is a scope before creating it : 
```
    private fun createScope() {
        if (_scope == null) {
            koin.logger.debug("Create scope: $_scope for $lifecycleOwner")
            val scopeId = lifecycleOwner.getScopeId()
            _scope = koin.getScopeOrNull(scopeId) ?: createScope(koin)
        }
    }
```

if I want to define something new, like a scope available for all my activities : 

```
scope<MyAbstractActivity> { /* with some definitions available for all */ }
scope<MyActivity1> { /* with some definitions available just for this one */ }
```

and use it like this : 

```
abstract class MyAbstractActivity : AppCompatActivity(), KoinScopeComponent {
    private val _scope by abstractActivityScope()
    override val scope by activityScope()
    override fun onCreate(savedInstanceState: Bundle?) {
         scope.linkTo(_scope)
    }
}
```

with this custom utility method : 

```
inline fun <reified A : ComponentActivity> A.abstractActivityScope() =
    LifecycleScopeDelegate<A>(this, getKoin()) { koin ->
        koin.createScope(
            scopeId = A::class.qualifiedName + "@" + this.hashCode(),
            qualifier = TypeQualifier(A::class),
            source = this
        )
    }
```

then I'll face an infinite recursion because when I'll call `scope.linkTo(_scope)` : 

1. `scope` initialisation will check `getScopeOrNull(lifecycleOwner.getScopeId())`, will get null and then will create the scope
2.`_scope` initialisation will check `getScopeOrNull(lifecycleOwner.getScopeId())`, will get `scope` and then will link `scope` to itself

**Expected behavior**

LifecycleScopeDelegate should let us override the way to get the scope id in addition of the custom `createScope()`.

maybe something like : 
```
class LifecycleScopeDelegate<T>(
    val lifecycleOwner: LifecycleOwner,
    private val koin: Koin,
    val getScopeId: () -> String = { lifecycleOwner.getScopeId() },
    val getScopeName: () -> String = { lifecycleOwner.getScopeName() },
    private val createScope: LifecycleScopeDelegate.(Koin) -> Scope = { koin: Koin ->
        koin.createScope(
            getScopeId(),
            getScopeName(),
            lifecycleOwner as T
        )
    },
) : ReadOnlyProperty<LifecycleOwner, Scope> {

  // ...

  private fun createScope() {
      if (_scope == null) {
          koin.logger.debug("Create scope: $_scope for $lifecycleOwner")
          _scope = koin.getScopeOrNull(getScopeId()) ?: createScope(koin)
      }
  }
```

**Koin project used and used version (please complete the following information):**
    implementation "io.insert-koin:koin-android:3.2.0"

**Comment by arnaudgiuliani** [comment]
I propose to switch to a more direct API to help avoid weird usage. follow https://github.com/InsertKoinIO/koin/issues/1356
