### ISSUE TITLE
Unresolve reference viewModule() when updating from 3.1.5 to 3.1.6+  

### ISSUE THREAD

**Issue by andrey2ag** [InsertKoinIO/koin#1416]
**Describe the bug**
After updating from v3.1.5 to v3.1.6 lazy initialization `by viewModel()` shows an error.
The error still shows up in version 3.2.0.

![Screen Shot 2022-08-22 at 10 27 46](https://user-images.githubusercontent.com/12824425/185975038-ae6f7dcc-0e14-4809-8786-6c32783e1e0b.png)

**To Reproduce**
1. Update Project's Koin library from v3.1.5 to v3.1.6

**Expected behavior**
Delegate initialization to not be recognized as an error.

**Koin project used and used version (please complete the following information):**

**Working Fine**
```
implementation "io.insert-koin:koin-android:3.1.5" 
```
**Showing error**
```
implementation "io.insert-koin:koin-android:3.1.6" // Issue Introduced
implementation "io.insert-koin:koin-android:3.2.0" // Still Existing
```

**Additional moduleDefinition**
Add any other moduleDefinition about the problem here.
```
module {
    viewModel {
        SignUpViewModel(Dependencies(get(), get()))
    }
}
```

**Comment by arnaudgiuliani** [comment]
Did you try import the extension? Seems to be an IDE thing 🤔

**Comment by andrey2ag** [comment]
yes the extension is imported, this is happening in any project instance and for other people in my team - We did check but it's weird to see that behavior by doing a minor lib update. 3.1.5 -> 3.1.6 or 3.1.5 -> 3.2.0

I'll check again but do you have any other insight about it?

**Comment by drawers** [comment]
I was able to replicate this behavior after I added Koin as a dependency to a project that was halfway underway. It seems to be fixed by performing an Invalidate caches/Restart. After I did that, I was able to import the `viewModel()` extension function.

**Comment by jt-gilkeson** [comment]
This may be related to this bug in AndroidStudio/IntelliJ: https://issuetracker.google.com/u/1/issues/178403178#comment17 somehow AndroidStudio gets confused about the Fragment (if you have a large project with various dependencies) unless you do the resolution strategy outlined in the comment which seems to fix the warnings.

**Comment by arnaudgiuliani** [comment]
Great, thanks @jt-gilkeson 👍
