### ISSUE TITLE
How to write a global ViewModel?

### ISSUE THREAD

**Issue by Joslyn-Chen** [InsertKoinIO/koin#1419]
How to write a global ViewModel?
use AndroidViewModel？

**Comment by arnaudgiuliani** [comment]
with NavGraphViewModel or main root Activity ViewModel

**Comment by Joslyn-Chen** [comment]
@arnaudgiuliani 
Hi, thanks for your reply. However, this method has limitations and does not really achieve the overall effect. For example, how to share the same ViewModel between multiple Activity?
