### ISSUE TITLE
[question] How to pass named beans to singleOf(::MyClass)

### ISSUE THREAD

**Issue by shalva97** [InsertKoinIO/koin#1421]
Is there a way to tell Koin which class to pass? 

I have `DataStore<T>` interface and 2 different variants. I know I can pass those arguments manually with get(qualifier = named("blah")` but singleOf seems much cleaner...

**Comment by arnaudgiuliani** [comment]
you can open `{ }` code just behind: 

```kotlin
singleOf(::MyClass) {
    named("a_qualifier")
}
```

https://insert-koin.io/docs/reference/koin-core/dsl-update#dsl-options 👍

**Comment by shalva97** [comment]
Thanks for response. As I understood the `named("")` gives name to `MyClass`, but I had a different case.

okay I will provide more info, and lets forget about `MyClass`, will just copy my code here. so I have a class like this:
```kotlin
class JellyFinServerRepo constructor(
    private val jellyFin: Jellyfin,
    private val recentServersStore: DataStore<Set<JellyFinServer>>, // this is what I want to inject
)

class JellyFinAuthRepo constructor(
    private val apiClient: ApiClient,
    private val loginDataStore: DataStore<LogInState> // also this should be injected
)
```
and here are the definitons of `DataStore<T>`:
```kotlin
val recentServerDataStoreModule = module {
    single(named(RECENT_SERVERS)) { get<Context>().recentServerDataStore } // this type is DataStore<Set<JellyFinServer>>
}

val userDataDatastoreModule = module {
    single(named(USER_DATA)) { get<Context>().userData } // this type is DataStore<LogInState>
}
```

I wanted to know if there was a way to tell Koin which DataStore<T> to inject. Ofcourse I do not want `DataStore<LogInState>` for `JellyFinServerRepo` which has nothing to do with authentication. I tried like this

```kotlin
val jellyFinModule = module {
    singleOf(::JellyFinServerRepo)
    singleOf(::JellyFinAuthRepo)
}
```

But that fails with BeanNotFoundException. 

If I remove `named()` from DataStore definitions then the app crashes with `ClassCastException: com.shalva97.core.models.LogInState$NotLoggedIn cannot be cast to java.lang.Iterable`. My guess here is that Koin tried to inject wrong class but the cast to `Set` was failed, or what ever the type is of `Set<JellyFinServer>`

So my question is how to pass named definitons to `singleOf(::JellyFinServerRepo)`? writting `singleOf(::JellyFinServerRepo) { named(RECENT_SERVERS) }`  gives name to the definiton itself...

**Comment by ageorgousakis** [comment]
As I can see in the [documentation](https://insert-koin.io/docs/reference/koin-core/dsl-update)  this is not supported using Constructor DSL

> NOTE
> If you need to retrieve a "named" definition, you need to use the standard DSL with lambda and get() to specify the qualifier

**Comment by arnaudgiuliani** [comment]
yes, Constructor DSL helps you to target implicitly all components, like filling with `get()` everywhere. This is why explicit usages like qualifier or nullable dependency are not detected. For this, I would suggest to use Koin annotations if you want to go further: https://insert-koin.io/docs/reference/koin-annotations/start
