### ISSUE TITLE
use parametersOf not work

### ISSUE THREAD

**Issue by ckenergy** [InsertKoinIO/koin#1422]
**Describe the bug**
in module i create 
```
a module {
    single { "ssssqqqq" }
}
```
when i use  **parametersOf("test")** to create **FactoryPresenter(val id: String, val service: SimpleService)** 
but **factoryPresenter.id** = "ssssqqqq" 

![image](https://user-images.githubusercontent.com/13145703/187630304-32f9b6de-33a5-4750-b21e-d0073dce878e.png)

why koin don't use i provider parameters first
 `koin version 3.2.0`

**Comment by ckenergy** [comment]
when i use **Scope.get** to find a instance, first find in **_koin.instanceRegistry.resolveInstance** , second find in **_parameterStack** , so **single** is first find

![image](https://user-images.githubusercontent.com/13145703/187650344-27cf602d-a290-48d5-8e5e-550b9c9ec494.png)

**Comment by arnaudgiuliani** [comment]
it's a fallback from the function approach. At first, we should write `single { params -> MySingle(params) }`

As the first usecase, the default behavior is to take a look at dependencies and then fallback into potential injected parameters.
