### ISSUE TITLE
`kfun:kotlinx.datetime.UtcOffset.Companion#ofSeconds(kotlin.Int){}kotlinx.datetime.UtcOffset:

### ISSUE THREAD

**Issue by periva101** [InsertKoinIO/koin#1423]
**Describe the bug**
A clear and concise description of what the bug is.`kfun:kotlinx.datetime.UtcOffset.Companion#ofSeconds(kotlin.Int){}kotlinx.datetime.UtcOffset:

**To Reproduce**
1. Go to the kmm exmaple
2. add kotilnX datetime
3. run 

**Expected behavior**

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core version 3.2.0`

**Additional moduleDefinition**
fun initKoinX1() =
    startKoin {

    }

**Comment by arnaudgiuliani** [comment]
Need to check if there is a conflict somewhere with lib.

**Comment by arnaudgiuliani** [comment]
couldn't reproduce it in kmm getting started app. Perhaps a conflict with something else?
