### ISSUE TITLE
The line to edit this doc is broken

### ISSUE THREAD

**Issue by md-touhid** [InsertKoinIO/koin#1424]
<img width="819" alt="Screen Shot 2022-09-02 at 2 10 25 PM" src="https://user-images.githubusercontent.com/89835450/188093857-e188cca4-18ee-4aca-85af-9ac4307d49e5.png">

**To Reproduce**
1. Go to (https://insert-koin.io/docs/reference/koin-core/definitions)
2. Click on 'Edit This Page'
3. See error

<img width="1217" alt="Screen Shot 2022-09-02 at 2 08 47 PM" src="https://user-images.githubusercontent.com/89835450/188094557-af8ff8f2-47a8-45c4-b5ce-678fcdb48e6e.png">

**Comment by arnaudgiuliani** [comment]
yes, need to fix that 👍
