### ISSUE TITLE
Scope.factoryOf fails to provide bean definition

### ISSUE THREAD

**Issue by ChumachenkoRoman** [InsertKoinIO/koin#1426]
**Describe the bug**
In our project we have a module with a scope. When I use `factoryOf` inside aforementioned scope I get a runtime exception:
Whilst `scope(...) { factory { MyDependency() } }` works just great. 

**To Reproduce**
1. Create a module
2. Define a scope
3. In scope definition lambda define dependency via `factoryOf`
4. Consume dependency
5. Run app
6. Observe crash with exception:
```
NoBeanDefFoundException: |- No definition found for class:'MyDepndency'. Check your definitions! 
```

**Expected behavior**
App runs without crashes (as with `factory {}` or `scopedOf` definitions).

**Koin project used and used version:**
`io.insert-koin:koin-android:3.2.0`

**Additional moduleDefinition**
```
val moduleToBeIncludedIntoAnotherOne = module {
   scope(named(COOL_SCOPE)) {
      factoryOf(::MyDependency)
   }
}
```

**Comment by arnaudgiuliani** [comment]
Couldn't reproduce your case. Please try next 3.3.0 version
