### ISSUE TITLE
Scope.kt no definition found for SavedStateHandle

### ISSUE THREAD

**Issue by tommybart** [InsertKoinIO/koin#1428]
**Describe the bug**
ViewModels that depend on the SavedStateHandle crash on rare occasions:

```
Caused by gv.e |- No definition found for class:'androidx.lifecycle.n0'. Check your definitions!
org.koin.core.scope.Scope.throwDefinitionNotFound (Scope.kt:304)
org.koin.core.scope.Scope.resolveValue (Scope.kt:274)
org.koin.core.scope.Scope.resolveInstance (Scope.kt:241)
org.koin.core.scope.Scope.get (Scope.kt:204)
```

Usage:
```
private val viewModel: MyViewModel by stateViewModel()
```

```
class MyViewModel(
    application: Application,
    ...
    private val savedStateHandle: SavedStateHandle
    ...
) : AndroidViewModel(application)
```
```
viewModel {
    MyViewModel(
        application = get(),
        ...
        savedStateHandle = get(),
        ...
    )
}
```

We also see this issue when using this extension for ViewModels scoped to a nav graph:
```
inline fun <reified VM : ViewModel> Fragment.navGraphStateViewModel(
    @IdRes navGraphId: Int,
    qualifier: Qualifier? = null,
    noinline state: BundleDefinition = emptyState(),
    noinline parameters: ParametersDefinition? = null
): Lazy<VM> {
    return stateViewModel(
        qualifier = qualifier,
        state = state,
        owner = {
            ViewModelOwner.from(
                storeOwner = findNavController().getViewModelStoreOwner(navGraphId),
                stateRegistry = this
            )
        },
        parameters = parameters
    )
}
```

**To Reproduce**
We're unable to reproduce the issue using the `Don't keep activities` developer option. When the process is destroyed this way, the ViewModel & state is restored as expected.

**Koin project used and used version**
```
io.insert-koin:koin-core:3.1.6
io.insert-koin:koin-android-compat:3.1.6
io.insert-koin:koin-androidx-workmanager:3.1.6
io.insert-koin:koin-androidx-compose:3.1.6
```
We also observed this issue on version `3.1.4` using `by viewModel()` to inject these ViewModels. Migrating to  `3.1.6` and using `by stateViewModel()` didn't appear to make a difference.

**Comment by arnaudgiuliani** [comment]
Hello,

please update koin-android in 3.3.0. This update brings fixes for that. Here is the announce: https://blog.kotzilla.io/koin-android-stronger-viewmodel-api/

**Comment by sudansh** [comment]
with 3.3.0 also it crashes in release buildType

> 
> minifyEnabled true
> shrinkResources true

**Comment by nickbw2003** [comment]
Seems like this is happening due to obfuscation. In order to work around this while having  `minifyEnabled = true`, add this line to your `proguard-rules.pro` file:
```
-keep class androidx.lifecycle.SavedStateHandle { *; }
```
