### ISSUE TITLE
Unable to access module { viewModel{} } from shared module after adding `io.insert-koin:koin-android` to the shared module dependencies

### ISSUE THREAD

**Issue by sodiqOladeni** [InsertKoinIO/koin#1429]
I'm using Koin with [moko-mvvm](https://github.com/icerockdev/moko-mvvm) for Kotlin Multiplatform project, I need to declare the ViewModel classes as common components but I'm unable to use the dsl `module { viewModel{} }` in the shared file even after i have added the koin-android to the common dependencies

I also got this error while trying to access in compose using viewModel() or inject()
Type mismatch.Required:EmailInputScreenViewModelFound:Lazy<???>

I will appreciate if i can be pointed to a resources that integrate Koin +[moko-mvvm](https://github.com/icerockdev/moko-mvvm) + compose

![Screenshot 2022-09-13 at 6 16 41 PM](https://user-images.githubusercontent.com/25503978/189965504-0d41349a-a142-49bd-a1f4-0dd2c6bfe120.png)

**Comment by arnaudgiuliani** [comment]
Interesting question. `koin-android` is jvm/android project only for now. I would recommend to go with an `expect` type and provide the right implementation in jvm module
