### ISSUE TITLE
ViewModel is not completly lazy

### ISSUE THREAD

**Issue by nshekhovtsov** [InsertKoinIO/koin#1430]
As I can see in the documents the vm is initialized like this:
```
inline fun <reified T : ViewModel> ComponentActivity.viewModel(
        qualifier: Qualifier? = null,
        owner : ViewModelStoreOwner = this,
        noinline parameters: ParametersDefinition? = null
): Lazy<T> {
        val scope = getKoinScope()
        return viewModels {
                getViewModelFactory<T>(owner, qualifier, parameters, scope = scope)
        }
}
```

When I try to add viewModel to the activity, I have a `KoinIsNotStarted exception` (at this moment the Koin is not realy initialized)
This happens in `getKoinScope()` method, in the `get()` function.

The current solution of this problem is simple:
```
val vm by lazy { viewModel<ViewModel>() }
```

But, I want to use it like a real lazy value instead of this. I cannot it reproduce on the 2.0 versions. Only on 3.2

**Comment by arnaudgiuliani** [comment]
Hello,
please update koin-android in 3.3.0. This update brings fixes for that. Here is the announce: https://blog.kotzilla.io/koin-android-stronger-viewmodel-api/
