### ISSUE TITLE
io.insert-koin:koin-androidx-compose is not updated to 3.2.1

### ISSUE THREAD

**Issue by WebTiger89** [InsertKoinIO/koin#1431]
Just wanna mention that  you forgot to update _io.insert-koin:koin-androidx-compose_ artifact to 3.2.1 like the other artifacts.

**Comment by MGaetan89** [comment]
Now `koin-androidx-compose` 3.2.1 is available, but not version 3.2.2

**Comment by p-fischer** [comment]
This seems intentional. I started a discussion here: https://github.com/InsertKoinIO/koin/discussions/1442
