### ISSUE TITLE
Crashes when using the constructor reference of the 3.2.x Koin version

### ISSUE THREAD

**Issue by xogon** [InsertKoinIO/koin#1435]
## Bug Description

After upgrading to the 3.2.x version of Koin and changing the

```
single { Class(get(), get(), get(), ... }
```

to the lovely syntax of `singleOf(::Class)`, I have found several crashes at runtime crashes with the following error:

```
org.koin.core.error.NoBeanDefFoundException: |- No definition found for class:'...'. Check your definitions!
```

I don't manage to understand if this is a problem of the current Koin version or a problem in our project, but I would guess it's more likely to be a Koin issue as the v2 notation worked smoothly.

## To Reproduce:
Move all `v2` definitions of singletons and factories using `get(), get(), get(), ...` to the constructor reference of the `v3` using `singleOf` and `factoryOf` functions.

## Expected behaviour:
No changes in the functionality of the application

## Koin project used and used version: 
Before: `v2.2.3`
After: `v3.2.0`

## Acknowledgments:
Awesome work with this library Arnaud! I love the path you are trying to follow in building a neat DSL leveraging some Kotlin syntactic sugar

**Comment by arnaudgiuliani** [comment]
A missing definition here. I would suggest converting modules 1 by 1, with the latest Koin version. Then proceed to constructor DSL 👍 

Also look at check module API to help you: https://insert-koin.io/docs/reference/koin-test/checkmodules

**Comment by xogon** [comment]
Thanks for your tips! 😄 We don't currently have tests for the module files and we should clearly add them. I will try both adding these tests and carefully migrate to the new DSL before closing this entry. 

I am really looking forward to have our module files with the neat `v3` syntax
