### ISSUE TITLE
Multiple independent instances of Koin

### ISSUE THREAD

**Issue by jbruchanov** [InsertKoinIO/koin#1440]
**Is your feature request related to a problem? Please describe.**
I'd like to build a 3rd party library and use koin without potential problems if a consumer using the library & koin as well.

**Describe the solution you'd like**
I think it would be good if koin was able to completely separate multiple independent instances. 
For example `GlobalContext.get()` could have something like `GlobalContext.get(appId:String? = null)` so it wouldn't be a breaking change, but I as a developer, I'd have completely separated DI tree for my own 3rd party lib. Similarly of course `startApp` and other setup functions.

For example
```
startKoin("myLib") {
        loadKoinModules(...)
}

//..and in code potentially use 
getKoin("myLib").get<Xyz>()
val xyz by inject<Xyz>(appId = "myLib")
```

There would be some hassle for some extension functions like to provide a ViewModel or the KotlinComponent.

- in case of `viewModel()`, `inject()` or similar I can think of own similar extension functions like `myLibViewModel()` where I could hardcode "myLib" as a DI key. I think that's small price to pay for a such a feature and would be acceptable (potentially some lint rule for explicit check that everywhere when necessary the key is used would be nice, unnecessary though due to similar crash like invalid/missing koin setup).

- Similarly if one uses `KoinComponent`, there can be just simple overriden "subinterface" returning expected Koin instance instead of default one.

btw.
my background comes from android dev, where most of 3rd party lib has some
`Lib.start(context)` where would the init happen

**Comment by arnaudgiuliani** [comment]
Did you check the "Context Isolation" topic? https://insert-koin.io/docs/reference/koin-core/context-isolation

This helps setup separated Koin instances, and help you build SDK for example.

**Comment by jbruchanov** [comment]
@arnaudgiuliani 
Ah nice one, that might help. Thanks a lot...

**Comment by arnaudgiuliani** [comment]
feel free to reopen a ticket if needed 👍
