### ISSUE TITLE
[Koin Annotation] Gradle sync failed after upgrade Android Gradle Plugin 7.3.0

### ISSUE THREAD

**Issue by ekoo** [InsertKoinIO/koin#1444]
**Describe the bug**
Gradle sync broken after upgrade to  AGP 7.3.0

**To Reproduce**
1. Use AGP 7.3.0
2. Setup Koin Annotation here https://insert-koin.io/docs/setup/ka_1.0
3. Sync with Gradle

![Screenshot from 2022-09-28 14-25-48](https://user-images.githubusercontent.com/35864865/192715331-befec8ca-8baf-4e6a-9c71-0599104680b6.png)

**Expected behavior**
Gradle sync success in latest AGP version

**Koin project used and used version (please complete the following information):**
`koin-annotation version 1.0.1`
`koin-ksp-compiler version 1.0.1`

**Comment by arnaudgiuliani** [comment]
version `1.0.3` has been release since. I will check
