### ISSUE TITLE
SharedViewModelCompat pass wrong owner

### ISSUE THREAD

**Issue by Jovandine** [InsertKoinIO/koin#1445]
Hello
Here you should pass owner parameter like
fragment.requireActivity()
Now this function creates new viewModel instead of reusing shared viewModel.

https://github.com/InsertKoinIO/koin/blob/044bc02a2aa75774aaa3c356aecfdf26f855f133/android/koin-android-compat/src/main/java/org/koin/android/compat/SharedViewModelCompat.kt#L50

**Comment by arnaudgiuliani** [comment]
I think it's outdated on your side. Current code is

```kotlin
@OptIn(KoinInternalApi::class)
@MainThread
fun <T : ViewModel> Fragment.viewModelForClass(
    clazz: KClass<T>,
    qualifier: Qualifier? = null,
    owner: () -> ViewModelStoreOwner = { this },
    state: BundleDefinition? = null,
    key: String? = null,
    parameters: ParametersDefinition? = null,
): Lazy<T> {
    return lazy(LazyThreadSafetyMode.NONE) {
        val ownerEager = owner()
        val viewModelStore = ownerEager.viewModelStore
        resolveViewModel(
            clazz,
            viewModelStore,
            extras = state?.invoke()?.toExtras(ownerEager) ?: CreationExtras.Empty,
            qualifier = qualifier,
            parameters = parameters,
            key = key,
            scope = getKoinScope()
        )
    }
}
```

**Comment by tomas-kovacs** [comment]
@arnaudgiuliani this is an issue at the `SharedViewModelCompat.getSharedViewModel` method:

    @OptIn(KoinInternalApi::class)
    @JvmOverloads
    @MainThread
    fun <T : ViewModel> getSharedViewModel(
        fragment: Fragment,
        clazz: Class<T>,
        qualifier: Qualifier? = null,
        parameters: ParametersDefinition? = null,
    ): T {
        return resolveViewModelCompat(
            clazz,
            fragment.viewModelStore,
            extras = CreationExtras.Empty,
            qualifier = qualifier,
            parameters = parameters,
            scope = GlobalContext.get().scopeRegistry.rootScope
        )
    }
    
See how the `resolveViewModelCompat` is taking the `viewModelStore` of the Fragment instead of the `viewModelStore` of the Activity.

**Comment by 594238813** [comment]
I also found this  

2.2.2        activity viewModelStore
```
fragment.getSharedViewModel(qualifier, null, { from(fragment.requireActivity().viewModelStore) },
            clazz.kotlin,
            parameters)
```

3.0  fragment  viewModelStore

**Comment by chrisnkrueger** [comment]
The comment in `SharedViewModelCompat.getSharedViewModel` says 
> Get a shared viewModel instance from underlying Activity

This is wrong, because it's using the ViewModelStore from the Fragment as @tomas-kovacs mentioned.
It should be using `fragment.requireActivity().viewModelStore` instead.

**Comment by arnaudgiuliani** [comment]
> @arnaudgiuliani this is an issue at the `SharedViewModelCompat.getSharedViewModel` method:
> 
> ```
> @OptIn(KoinInternalApi::class)
> @JvmOverloads
> @MainThread
> fun <T : ViewModel> getSharedViewModel(
>     fragment: Fragment,
>     clazz: Class<T>,
>     qualifier: Qualifier? = null,
>     parameters: ParametersDefinition? = null,
> ): T {
>     return resolveViewModelCompat(
>         clazz,
>         fragment.viewModelStore,
>         extras = CreationExtras.Empty,
>         qualifier = qualifier,
>         parameters = parameters,
>         scope = GlobalContext.get().scopeRegistry.rootScope
>     )
> }
> ```
> 
> See how the `resolveViewModelCompat` is taking the `viewModelStore` of the Fragment instead of the `viewModelStore` of the Activity.

thanks

**Comment by arnaudgiuliani** [comment]
Will be release in koin-android 3.3.3
