### ISSUE TITLE
Crash on koinNavGraphViewModel after 3.2.2 update

### ISSUE THREAD

**Issue by LipeDuoli** [InsertKoinIO/koin#1446]
**Describe the bug**
I tried to update my project from version 3.2.0 to 3.2.2.
After migrate to the new [android scope](https://insert-koin.io/docs/reference/koin-android/scope#android-scope-classes) from the previous lazy delegate to the new `createFragmentScope()` All my calls to `by koinNavGraphViewModel` is crashing with the error
```
Trying to access Android Scope on 'HomeFragment{c1f0992} (aeee074c-3115-41a1-b87f-84b9bfb93494)' but scope is not created
```
my code is
```
private val viewModel: HomeViewModel by koinNavGraphViewModel(R.id.navGraph)
```
And if I change to 
```
private val viewModel: HomeViewModel by viewModel()
```
the code do not crash anymore

Other places that I use just `by viewModel()`, continue to work fine

**To Reproduce**
1. Create an fragment with the new android scope implementation (`createFragmentScope()`)
2. Inject an viewModel using `by koinNavGraphViewModel`

**Expected behavior**
scope to be inicialized when `koinNavGraphViewModel` is used

**Koin project used and used version (please complete the following information):**
_Before:_
`koin-android:3.2.0`
`koin-androidx-workmanager:3.2.0`
`koin-androidx-navigation:3.2.0`
`koin-android-compat:3.2.0`

_After:_
`koin-android:3.2.2`
`koin-androidx-workmanager:3.2.2`
`koin-androidx-navigation:3.2.2`
`koin-android-compat:3.2.2`

**Comment by arnaudgiuliani** [comment]
Scope resolution has been fixed 👍
