### ISSUE TITLE
wrong (empty) savedstatehandle is provided (does not contain navigation arguments)

### ISSUE THREAD

**Issue by marekdef** [InsertKoinIO/koin#1447]
**Describe the bug**
So If I use navigation component (and possibly a safeargs plugin), when I navigate and specify the argument  with navdirection then those arguments should be available from viewmodel via savedStateHandle. 

If I use `by android.app.Fragment.viewModels()` I have access to the argument passed immediately via `savedState.getLiveData("argument").

But If I use koin's `org.koin.androidx.viewmodel.ext.android.sharedStateViewModel` then this savedStateHandle does not have this argument.

**To Reproduce**
1. Go to https://github.com/marekdef/InsertKoinSavedStateHandle
2. Build and run
3.Press the button to navigate 
4. It crashes

**Expected behavior**
The "message" parameter should be available from savedStateHandle.

If you go to DetailFragment.kt and comment out `viewModel` (which is koin injected) and use viewModel2 then you will see the message on detail fragment.

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-android: 3.2.2`

I think this bug was similar 
https://github.com/InsertKoinIO/koin/issues/1350
but for compose.

**Comment by arnaudgiuliani** [comment]
Hello,
please update koin-android in 3.3.0. This update brings fixes for that. Here is the announce: https://blog.kotzilla.io/koin-android-stronger-viewmodel-api/
