### ISSUE TITLE
[Android] lifecycle scopes are broken: using injected components in onCreate throws IllegalStateException

### ISSUE THREAD

**Issue by Pfoerd** [InsertKoinIO/koin#1448]
**Describe the bug**
`java.lang.IllegalStateException: can't get Scope for FooActivity - LifecycleOwner is not Active` is thrown when using any component injected from an Android lifcycle scope like activityScope/activityRetainedScope/FragmentScope in onCreate.

**To Reproduce**
```
class FooActivity : AppCompatActivity(), AndroidScopeComponent {

    override var scope: Scope? = null

    private val foo: Foo by inject()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        createActivityRetainedScope()
        foo.toString() // Exception is thrown here
    }
```

**Expected behavior**
Using injected components of Android lifecycle scopes in onCreate is possible

**Koin project used and used version (please complete the following information):**
`3.2.2`

**Detailed Analysis and Proposed solution**
At [this point of LifecycleViewModelScopeDelegate](https://github.com/InsertKoinIO/koin/blob/main/android/koin-android/src/main/java/org/koin/androidx/scope/LifecycleViewModelScopeDelegate.kt#L25) ` _scope = koin.getScopeOrNull(scopeId) ?: createScope(koin)` was removed (as part of [this fix](https://github.com/InsertKoinIO/koin/issues/1399)). So there is no cached instance of the lifecycle scope that can be used in the [getValue](https://github.com/InsertKoinIO/koin/blob/main/android/koin-android/src/main/java/org/koin/androidx/scope/LifecycleViewModelScopeDelegate.kt#L37) call and as lifecycle component is in `onCreate` state the `if (!thisRef.isActive())` returns false.

**Comment by Pfoerd** [comment]
@arnaudgiuliani could you please have a look at this? This again blocks us from using Koin Android scopes :(

**Comment by arnaudgiuliani** [comment]
Scope API has been reverted and fixed to not conflict anymore 👍
It should be better
