### ISSUE TITLE
Typos in official guide website

### ISSUE THREAD

**Issue by jinaiyuanbaojie** [InsertKoinIO/koin#1458]
Hi team. I found some typos in your official website. Not sure if it is ok to raise ticket here.

In your Quickstart Projects. The view model should be injected is UserViewModel, but the demo codes show the typo one **MyViewModel**.

**Comment by sschuberth** [comment]
And unfortunately https://github.com/InsertKoinIO/koin/issues/1462 makes it unnecessary hard to fix those typos as a contributor.

**Comment by arnaudgiuliani** [comment]
yep, let's follow on #1462
