### ISSUE TITLE
Using constructor DSL to bind multiple classes via lambdas to the same interface does not work

### ISSUE THREAD

**Issue by sschuberth** [InsertKoinIO/koin#1463]
**Describe the bug**

The code

```
module {
    singleOf(::CsvExporter) { bind<Exporter>() }
    singleOf(::ExcelExporter) { bind<Exporter>() }
}
```

throws `org.koin.core.error.DefinitionOverrideException: Already existing definition for [Singleton:'dev.schuberth.stan.exporters.ExcelExporter',binds:dev.schuberth.stan.exporters.Exporter] at dev.schuberth.stan.exporters.Exporter::_root_`.

Note that using the alternative operator-syntax

```
module {
    singleOf(::CsvExporter) bind Exporter::class
    singleOf(::ExcelExporter) bind Exporter::class
}
```

works.

**To Reproduce**

Just use above code snippets.

**Expected behavior**

`{ bind<Exporter>() }` syntax should work just like `bind Exporter::class` syntax.

**Koin project used and used version (please complete the following information):**

`koin-core version 3.2.2`

**Additional moduleDefinition**

n/a

**Comment by 1gravity** [comment]
IMO 
```
module {
    singleOf(::CsvExporter) bind Exporter::class
    singleOf(::ExcelExporter) bind Exporter::class
}
```
should also throw a `DefinitionOverrideException` because you're binding two implementations to the same interface and Koin doesn't know which one to inject. It seems to pick the second one but 1) that's not a documented behavior and 2) it makes the first bind obsolete so why add it in the first place (ok I know what you're trying to do but outside of your use case, having these two binds in one module doesn't make sense)?

**Comment by sschuberth** [comment]
> ok I know what you're trying to do but outside of your use case, having these two binds in one module doesn't make sense

Yes, as you know from my [SO question](https://stackoverflow.com/questions/74254878/use-koin-instead-of-serviceloader-for-plugin-discovery) I'm looking at Koin from a Service Locator / plugin registry perspective. And there, it makes sense to be able to bind multiple implementations to the same interface, so all plugin instances could be retrieved via `app.koin.getAll<Exporter>()`. If that shouldn't be allowed, what's the purpose of the `getAll()` API call after all?

**Comment by 1gravity** [comment]
> > ok I know what you're trying to do but outside of your use case, having these two binds in one module doesn't make sense
> 
> Yes, as you know from my [SO question](https://stackoverflow.com/questions/74254878/use-koin-instead-of-serviceloader-for-plugin-discovery) I'm looking at Koin from a Service Locator / plugin registry perspective. And there, it makes sense to be able to bind multiple implementations to the same interface, so all plugin instances could be retrieved via `app.koin.getAll<Exporter>()`. If that shouldn't be allowed, what's the purpose of the `getAll()` API call after all?

Yes you're right, I didn't understand that Koin indeed allows to inject multiple implementations that can be retrieved into a list .

**Comment by arnaudgiuliani** [comment]
I fixed it back, to allow bind() for 2 same type
