### ISSUE TITLE
Unable to inject retrofit from one module to another

### ISSUE THREAD

**Issue by MrShtein** [InsertKoinIO/koin#1470]
**Describe the bug**
There are two modules. The :app module contains the entire application, and the :core:network module contains the retrofit lib. When gradle tries to build a project, an error occurs. 

```
app/src/main/java/ru/mrshtein/work_with_network/FirstFragment.kt: (43, 45): Cannot access class 'retrofit2.Response'. Check your module classpath for missing or conflicting dependencies
```

**To Reproduce**
1. Clone the test project - https://github.com/MrShtein/NetworkTest.
2. Try to build it.

**Expected behavior**
The project must be built.

**Koin project used and used version (please complete the following information):**
 `(io.insert-koin:koin-android:3.2.0)`

**Additional moduleDefinition**
When in the build.gradle of the network module, I use the api configuration (api 'com.squareup.retrofit2:retrofit:2.9.0') instead of the implementation, everything works, but if I understand correctly using the koin, it should also work with the implementation.

**Comment by arnaudgiuliani** [comment]
are you linking retrofit implementation until your fragment?
