### ISSUE TITLE
remove Jcenter, Can't resolve lifecycleScope.inject

### ISSUE THREAD

**Issue by khichi0104** [InsertKoinIO/koin#1474]
After remove Jcenter, change to mavencentral
and change from implementation 'org.koin:koin-androidx-scope:2.1.6' to "io.insert-koin:koin-core:3.0.1"

>"Presenter by lifecycleScope.inject" can't resolve

Old code
` class SubscriptionPackageActivity : BaseActivity(), SubscriptionPackageContractor.View {

    private lateinit var binding: ActivitySubscriptionPackageBinding
    private val viewModel: SubscriptionPackageViewModel by viewModel()
    private val presenter: SubscriptionPackageContractor.Presenter by lifecycleScope.inject {
        parametersOf(this, viewModel)
    }

    private val packageAdapter = PackageAdapter()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = DataBindingUtil.setContentView(this, R.layout.activity_subscription_package)
        binding.lifecycleOwner = this
}
}`
with
>import org.koin.androidx.scope.lifecycleScope
import org.koin.androidx.viewmodel.ext.android.viewModel
import org.koin.core.parameter.parametersOf

After remove jcenter, "Presenter by lifecycleScope.inject" can't resolve then I try to import another package

New Code
`private val presenter: SubscriptionOrderContractor.Presenter by inject 
{
        parametersOf(this, viewModel)
    }
`
with
>import org.koin.android.ext.android.inject
import org.koin.androidx.viewmodel.ext.android.viewModel
import org.koin.core.parameter.parametersOf

Error
java.lang.RuntimeException: Unable to start activity ComponentInfo{xxxx.insurance.subscription.listpackage.view.SubscriptionPackageActivity}: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'xxxx.insurance.subscription.listpackage.presenter.SubscriptionPackageContractor$Presenter'. Check your definitions!

Help me What should I solve?

**Comment by arnaudgiuliani** [comment]
do you try to migrate Scope API from Koin 2.x?
