### ISSUE TITLE
Unable to inject ViewModel impl with SavedStateHandle if it extends abstract ViewModel

### ISSUE THREAD

**Issue by Lucchetto** [InsertKoinIO/koin#1480]
**Describe the bug**
Given a ViewModelImpl with savedStateHandle as first constructor param that extends abstract ViewModel without any constructor param, SavedStateHandle won't be injected

`
class ViewModelImpl(savedStateHandle: SavedStateHandle) : AbstractViewModel()
`

`
abstract class AbstractViewModel : ViewModel()
`

`
val viewModelModule = module {
    viewModel<AbstractViewModel> { ViewModelImpl(get()) }
}
`

**To Reproduce**
Please see code above

**Expected behavior**
SavedStateHandle should be injected, but it seems like that koin tries to obtain constructor params from `AbstractViewModel` so it doesn't work

**Koin project used and used version:**
"io.insert-koin:koin-core:3.2.0"
"io.insert-koin:koin-androidx:3.3.0"
"io.insert-koin:koin-androidx-compose:3.3.0"

**Comment by arnaudgiuliani** [comment]
do you have any stacktrace?

**Comment by Lucchetto** [comment]
Here it is

[injection_crash.txt](https://github.com/InsertKoinIO/koin/files/10395492/injection_crash.txt)

**Comment by arnaudgiuliani** [comment]
please first update in io.insert-koin:koin-androidx-compose:3.4.1

I believe your coimpose implementation is not getting the right VM factory

**Comment by sudansh** [comment]
I am on 3.4.1 only and it doesn't work.

**Comment by arnaudgiuliani** [comment]
The underlying VM factory implementation seems not right. Can extract a sample project to share and reproduce?

**Comment by julienbm** [comment]
Hello @arnaudgiuliani, I have the exact same problem starting 3.2.x (was working pretty well with 3.1.6). I made a sample project so you can easily reproduce it. Let me know how I could help :) 
https://github.com/JulienDev/koin-savedstatehandle/tree/main/app/src/main/java/juliendev/koin/savedstatehandle

**Comment by arnaudgiuliani** [comment]
@julienbm thanks, I'll take a look 👍

**Comment by arnaudgiuliani** [comment]
I got the issue will work on it for Koin 3.4. To avoid it for now you need to inject the concrete class that is using the SavedStateHnadle injection. The workaround consist in injecting it, and cast it later in the desired type.

```kotlin
class ViewModelImpl(savedStateHandle: SavedStateHandle) : AbstractViewModel()

private val viewModel by viewModel<ViewModelImpl>()
```

This way `ViewModelImpl` will be injected with the created SavedStateHnadle

**Comment by julienbm** [comment]
Thank you Arnaud!
