### ISSUE TITLE
declared mock not used when injected object is passed as a parameter in ktor route

### ISSUE THREAD

**Issue by kroikie** [InsertKoinIO/koin#1482]
**Describe the bug**
1st: Koin is pretty cool, I'm enjoying using it!

With Ktor I'm using the [group by definitions](https://ktor.io/docs/structuring-applications.html#group_routing_definitions) approach. I'm able to inject an ObjectA into my route and use it in production. However when I declareMock<ObjectB> which is used by ObjectA the mock is ignored *if* the injected ObjectA is passed as a parameter to my Route.handler methods. If I don't pass the injected ObjectA as a parameter the mock works just fine.

**To Reproduce**
1. Define @Single objects as follows ObjectA requires ObjectB in its constructor:

```
interface ObjectB {
    fun doSomething(): Int
}

@Single
class ObjectBMysql : ObjectB {
    override fun doSomething(): Int {
        return 8
    }
}

@Single
class ObjectA(private val objectB: ObjectB) {
    fun doSomethingElse(): String {
        val int = objectB.doSomething()
        return "i am working $int"
    }
}
```

2. Inject ObjectA in route using the [group by definition](https://ktor.io/docs/structuring-applications.html#group_routing_definitions) approach:

```
fun Application.configureRouting() {
    routing {
        val objectA : ObjectA by inject()
        defaultEndpoint(objectA)
        // other endpoints that would use the admin service 
    }
}

private fun Route.defaultEndpoint(objectA: ObjectA) {
    get("/") {
        call.respond(objectA.doSomethingElse())
    }
}
```
3. Define a test mocking ObjectB and set the return value of `doSomething`:
```
class ApplicationTest : KoinTest {
    @get:Rule
    val mockProvider = MockProviderRule.create {clazz ->
        Mockito.mock(clazz.java)
    }

    @Test
    fun testRoot() = testApplication {
        application {
            val objectBMock = declareMock<ObjectB>()
            given(objectBMock.doSomething()).will { 1 }
            configureRouting()
        }
        client.get("/").apply {
            assertEquals("i am working 1", bodyAsText())
        }
    }
}
```
4. Run ApplicationTest suite and note that test fails:
```
expected:<i am working [1]> but was:<i am working [8]>
Expected :i am working 1
Actual   :i am working 8
```

**Expected behavior**
I would expect that the mock of ObjectB would be used even when the injected ObjectA reference is passed to `Route.defaultEndpoint`.

If the injected ObjectA is injected in `Route.defaultEndpoint` the mock is used in the test as expected and the above test passes.
```
private fun Route.defaultEndpoint() {
    val objectA : ObjectA by inject()
    get("/") {
        call.respond(objectA.doSomethingElse())
    }
}
```
However in this way I would have to inject ObjectA for every endpoint handler and I would like to avoid that if possible.

If I don't use the [group by definition](https://ktor.io/docs/structuring-applications.html#group_routing_definitions) approach and handle all endpoints together:
```
fun Application.configureRouting() {
    routing {
        val objectA : ObjectA by inject()
        get("/") {
            call.respond(objectA.doSomethingElse())
        }
        // other endpoints that would use the admin service 
    }
}
```
then I'm able to use the single injected ObjectA in each route handler and again the tests pass but I would prefer use the group by definition approach.

Any recommendations/assistance/scolding :) would be appreciated.

**Koin project used and used version (please complete the following information):**
koin_version=3.2.2
koin_annotations_version=1.0.3
ktor_version=2.1.3
kotlin_version=1.7.20
mockito-core=4.9.0
mockito-inline=4.9.0
mockito-kotlin=4.1.0

**Comment by arnaudgiuliani** [comment]
need to check what's going on with the `routing` section

**Comment by arnaudgiuliani** [comment]
Are you using `declareMock` in the right place? Here is an example:

![image](https://github.com/InsertKoinIO/koin/assets/2360688/43649412-3306-4059-883b-6caf29436968)

**Comment by kroikie** [comment]
Finally got around to trying this again. I've bumped both my versions of ktor and Koin to the latest versions as of today. My tests are working as expected so I'm not sure what did it but I'll report in a separate issue if I experience something like this again.
