### ISSUE TITLE
Cant generate instance of class if class is in package named "interface"

### ISSUE THREAD

**Issue by tyczj** [InsertKoinIO/koin#1485]
**Describe the bug**
When a class is in a package that has the name `interface` koin throws an error when generating the instances with the error

"Name expected"

**To Reproduce**
1. Create a class in a package called "interface"
2. Try to build
3. Build errors with "Name expected" in the koin generated module class
4. 
![image](https://user-images.githubusercontent.com/1816052/206755683-5b41c489-9ea6-4674-bcd6-f834d928fcf8.png)

**Expected behavior**

**Koin project used and used version (please complete the following information):**
 `koin-annotations v 1.0.3`
 `koin-android v 3.3.0`

Renaming the package fixes the issue

**Comment by arnaudgiuliani** [comment]
Hello,

yes, forbidden keyword shouldn't be in the package name. Can you push this to the Koin Annotations Repo? https://github.com/InsertKoinIO/koin-annotations

**Comment by tyczj** [comment]
reopened over there
