### ISSUE TITLE
koin-logger-slf4j 3.2.2 incompatible with koin-core 3.3.0

### ISSUE THREAD

**Issue by nielsvanvelzen** [InsertKoinIO/koin#1489]
**Describe the bug**
The recent update of Koin 3.3.0 broke it's slf4j logger.

```
Exception in thread "main" java.lang.IncompatibleClassChangeError: class org.koin.logger.SLF4JLogger overrides final method org.koin.core.logger.Logger.log(Lorg/koin/core/logger/Level;Ljava/lang/String;)V
```

**To Reproduce**
1. Use the latest version of the sl4fj logger and core in a project
2. Use the slf4j logger
3. See error

**Expected behavior**
No crash, ideally the logger should also not be a part of the Ktor module so it's always updated with core.

**Koin project used and used version (please complete the following information):**
```
koin-core = "3.3.0"
koin-ktor = "3.2.2"
```

**Additional moduleDefinition**
Nothing special

**Comment by arnaudgiuliani** [comment]
check for ktor 3.3.0. It has been deployed

**Comment by arnaudgiuliani** [comment]
Interesting suggestion. Do you use it without ktor?

**Comment by nielsvanvelzen** [comment]
Yes, we use Koin as our dependency injection library and slf4j for logging in all our projects. Some of them are CLI tools or only communicate via message brokers.

**Comment by arnaudgiuliani** [comment]
ok, interesting. Something we can move on, in 3.4 milestone

**Comment by arnaudgiuliani** [comment]
The version track is now compatible with all 3.4. I keep slf4j in ktor project for now 👍 I'll check out for any incoming issue like this
