### ISSUE TITLE
viewModelOf constructor DSL functions for 10+ parameters were removed

### ISSUE THREAD

**Issue by xsveda** [InsertKoinIO/koin#1494]
viewModelOf constructor DSL functions for 10+ parameters introduced on Dec 13
https://github.com/InsertKoinIO/koin/commit/e5bd2d92970b245eba6c3f775f15a5eda61b2d92#diff-b76c02b40b7312b21ceedf04bde2261f77a8e584f37743a86bb3b3ae74e55733
seems to be removed accidentally on Dec 14
https://github.com/InsertKoinIO/koin/commit/91397a91ea6e2f56b8e59e9c59d4bb7ddd754092#diff-b76c02b40b7312b21ceedf04bde2261f77a8e584f37743a86bb3b3ae74e55733

**Comment by arnaudgiuliani** [comment]
argh, sorry :/

**Comment by arnaudgiuliani** [comment]
wait for new patch.

**Comment by arnaudgiuliani** [comment]
Will be release in koin-android 3.3.3
