### ISSUE TITLE
Undocumented breaking change in scoped {} 

### ISSUE THREAD

**Issue by Nek-12** [InsertKoinIO/koin#1495]
**Describe the bug**
Koin 3.3.1 update introduced a compile-time error when using singleOf() inside the scope<>() function.
An undocumented change (not in CHANGELOG.md) was to change singleOf() to scopedOf()
However, using scopedOf() results in DefinitionNotFound exception in runtime now.

**Expected behavior**
No breaking api changes are introduced in minor version update (x.x.Y)

**Koin project used and used version (please complete the following information):**
Koin 3.3.1

**Additional moduleDefinition**
```
scope<MainActivity> {
        scopedOf(::Formatters) { // was singleOf() and failed
            createdAtStart()
        }
    }
```

**Comment by arnaudgiuliani** [comment]
singleOf() has always been kindof "blocked", but not enough. 3.3.x introduced DSL checking. singleOf in scope should work, as a singleton should access a scope area.
