### ISSUE TITLE
Android Studio complains that by viewModel is an unresolved reference

### ISSUE THREAD

**Issue by Nattle** [InsertKoinIO/koin#1498]
Android studio reports an error in the code when using `by viewModel()` in an AppCompatActivity

**To Reproduce**
See attached snip of our app. 
Simply creating an activity which extends AppCompatActivity reports a compilation error. 
Note that the project compiles just fine.

This occurs on several versions of Android Studio, currently using a mix of Chipmonk, Dolphin, and Eel. 

**Expected behavior**
Android studio doesn't report and error. 

**Koin project used and used version (please complete the following information):**
```ext.koin_version = '3.2.2'
implementation "io.insert-koin:koin-core:$koin_version"
```

![Screen Shot 2022-12-12 at 12 45 59 PM](https://user-images.githubusercontent.com/2287972/210587953-e50a7991-5e0e-47fd-a007-fc64b2742e84.png)

![Screen Shot 2023-01-04 at 10 25 50 AM](https://user-images.githubusercontent.com/2287972/210589330-f989b606-9cf7-4ba1-b44f-b2515ff56159.png)

**Comment by arnaudgiuliani** [comment]
can you extract your ViewModel class declaration outside, to check?

**Comment by Nattle** [comment]
Do you mean to a separate file? The bulk of our view models are defined in different files or rarely other gradle modules. You can see in the first file that the view model is declared in another file. 

It doesn't complain that the view model is the wrong type, since in Fragments I can use the same VM class. It's only activities which show this error.

**Comment by arnaudgiuliani** [comment]
really weird 🤔 

Is it a project config issue? Can you try checkout this tutorial: https://insert-koin.io/docs/quickstart/android-viewmodel

**Comment by ForceTower** [comment]
I have the same issue, but I'm using the vanilla by viewModels from androidx.

I think this is an android studio bug. If I move my implementation dependencies a bit the issue disappears...

**Comment by plugowskidroids** [comment]
Same problem here, code works fine but AS reports error 😞 @ForceTower what do you mean by moving implementation dependencies?

**Comment by ForceTower** [comment]
Sometimes l just need to go to my grade file and move the dependencies around and that fixes the issue...

**Comment by Nattle** [comment]
Seems to have resolved with current versions of android studio.

**Comment by nogi1** [comment]
encountered the same issue with newest version of android studio, code works fine, application runs, it just reports the error, moving around implementations doesn't do anything.

![Image](https://github.com/user-attachments/assets/1af3d61c-af4b-43be-af85-3a0ffefd2083)

![Image](https://github.com/user-attachments/assets/bd0a0895-f8b6-4634-b8b3-5a2207dd4d3d)

**Comment by adityawibisana** [comment]
I have the exact same problem. 
Code run + compiled just fine. 

Using Android Studio Meerkat Feature Drop.
I am using AppCompatActivity.

![Image](https://github.com/user-attachments/assets/e50c2ff2-d2c2-4972-84a9-c093262e8060)
![Image](https://github.com/user-attachments/assets/5309a16a-b3a7-47a8-9c37-15684ecda0bb)
