### ISSUE TITLE
ActivityViewModel with SavedStateHandle doesn't work

### ISSUE THREAD

**Issue by oh-naoki** [InsertKoinIO/koin#1508]
**Describe the bug**
ActivityViewModel with SavedStateHandle doesn't work.

**To Reproduce**
We define an ActivityViewModel that uses SavedStateHandle on a screen with several Fragments based on Activity. 
When I performed the following steps with Don't keep Activities On, I could not retrieve the saved data from the SavedStateHandle

1. Fragment A: save some user inputs  to SavedStateHandle
2. Fragment B: Draw user inputs from SavedStateHandle
3. Close app 
4. Reopen app but SavedStateHandle has been cleared. (Draw empty user inputs)

**Expected behavior**
SavedStateHandle is not cleared.

**Koin project used and used version (please complete the following information):**
`koin-android version 3.3.0`

I apologize for my poor English. 🙏

**Comment by arnaudgiuliani** [comment]
Hello, can you try with in koin-android 3.3.2?

**Comment by cryptowizard** [comment]
I have the same problem in version 3.3.3

**Comment by arnaudgiuliani** [comment]
SSH injection should work in the latest 3.4.3 I guess 🤔

**Comment by ryohey** [comment]
@arnaudgiuliani Hi, Thanks for your hard work on this project! I'm facing the same issue. It seems the problem persists even in version 3.4.3. I've created a sample project to reproduce this issue; would you mind taking a look? 
https://github.com/ryohey/savedstatehandle-inject-example

In this sample project, there's a `MainFragment` with a count-up button. This fragment asks a `ParentViewModel` with a `SavedStateHandle` to retain its value. When you press the "Next" button, the `ResultFragment` fetches and displays this count from the `ParentViewModel`. If you press the count-up button a few times and then navigate to the `ResultFragment` using the "Next" button, you'll see the updated count. However, when the "Don't keep activities" option is enabled, and you press the home button and then return to the app, the count resets to zero. Interestingly, this issue doesn't occur in the `MainFragment`. Also, switching from `private val parentViewModel: ParentViewModel by activityViewModel()` to either `sharedStateViewModel()` or `koinNavGraphViewModel(R.id.main_navigation)` results in the same issue.

**Comment by arnaudgiuliani** [comment]
sure, for taking time to prepare this sample project 👍

**Comment by arnaudgiuliani** [comment]
Hello,
played with your sample project but couldn't reproduce the loss of state. One time I've seen the app completely killed, but else ... 🤔 
[Screen_recording_20230907_135413.webm](https://github.com/InsertKoinIO/koin/assets/2360688/cac40cd7-5bd3-40a4-91cf-4418fbbe67f0)

**Comment by ryohey** [comment]
@arnaudgiuliani Thank you for trying it, could you try it on the screen with the Back button that appears when you press Next instead of the screen with the Count up button?

**Comment by arnaudgiuliani** [comment]
The same using the back button

**Comment by ryohey** [comment]
@arnaudgiuliani I have taken a capture of when the problem is reproduced, could you please check it?

Pixel 4a (Android 13)

https://github.com/InsertKoinIO/koin/assets/5355966/229a2717-5afd-4cfc-9837-79322e3a4a90


Emulator (Android 11)

https://github.com/InsertKoinIO/koin/assets/5355966/73aafbe3-d5c9-4a6a-ad8c-96cc11e13135

**Comment by arnaudgiuliani** [comment]
can you reproduce it on a emulator?

**Comment by ryohey** [comment]
@arnaudgiuliani Yes, I have also attached a screen capture of the emulator to my recent comment.
However, I tried today with 3.5.2-RC2 and this problem seems to be resolved! It occurs with 3.5.0.
Thanks for updating the library.

**Comment by arnaudgiuliani** [comment]
Great 👍
