### ISSUE TITLE
Configuration check `verify()` doesn't seem to check constructor of implementation class of interface, behavior intended?

### ISSUE THREAD

**Issue by omtians9425** [InsertKoinIO/koin#1509]
Hi, thanks for this useful library!

**Describe the bug**
In unit tests, `verify` passes even if the constructor of the implementation class of the interface cannot be resolved.

**To Reproduce**
Given the following module without a constructor DSL,
```kt
val sampleModule = module {
    single<SampleRepository> { 
        SampleRepositoryImpl(sampleService = get())
    }
    single { 
        SampleService()
    }
}
```

`verify` passes expectedly.
```kt
@Test
fun `verify sample module`() {
    sampleModule.verify()
}
```

However, if I remove `SampleService` from the module, the test still passes even though the impl class cannot be resolved.
```kt
val sampleModule = module {
    single<SampleRepository> { 
        SampleRepositoryImpl(sampleService = get())
    }
//    single { 
//        SampleService()
//    }
}
```

**Expected behavior**
I would expect the test to fail when I removed `SampleService`.

I know the following patterns make the test fail, 
```kt
// 1
val sampleModule = module {
    single {
        SampleRepositoryImpl(sampleService = get())
    }
//    single {
//        SampleService()
//    }
}

// 2
val sampleModule = module {
    singleOf(::SampleRepositoryImpl) {
        bind<SampleRepository>()
    }
//    single {
//        SampleService()
//    }
}
```

but if I only want to get the interface type, it becomes a problem:
- Pattern 1: We cannot get() the interface type
- Pattern 2: We can get() the interface type but impl class becomes unnecessarily obtainable

**Koin project used and used version (please complete the following information):**
- `koin-android version 3.3.1`

**Comment by arnaudgiuliani** [comment]
When you write: 

```kotlin
single<SampleRepository> { 
        SampleRepositoryImpl(sampleService = get())
    }
```

Koin will only see type `SampleRepository`. To allow verify() function to go through your code, you need "explicit" binding:

```kotlin
single { 
        SampleRepositoryImpl(sampleService = get())
    } bind SampleRepository::class
```

or even

```kotlin
singleOf(SampleRepositoryImpl) { 
       bind<SampleRepository>()
    }
```

The idea is to go through your Koin configurations, not scan for all class constructors.

**Comment by omtians9425** [comment]
@arnaudgiuliani 
> you need "explicit" binding:

Then what about [Retrofit](https://square.github.io/retrofit/)'s Service interface? The implementing classes of these interfaces are not accessible from our code. Does it mean that these are not unit testable?

**Comment by arnaudgiuliani** [comment]
> Then what about [Retrofit](https://square.github.io/retrofit/)'s Service interface? The implementing classes of these interfaces are not accessible from our code. Does it mean that these are not unit testable? 👀

this is Kotlin expression. Yes there is something to do 🤔

**Comment by arnaudgiuliani** [comment]
Verify() API is quite limited as we don't have access to reflection metadata from underlying DSL function. Koin annotations will have a better solution to fully cover all of this :/

**Comment by arnaudgiuliani** [comment]
For now either use checkModules or verify depending how you want to test. But those tools are quite limited in terms of type access.

**Comment by pedrofsn** [comment]
> When you write:
> 
> ```kotlin
> single<SampleRepository> { 
>         SampleRepositoryImpl(sampleService = get())
>     }
> ```
> 
> Koin will only see type `SampleRepository`. To allow verify() function to go through your code, you need "explicit" binding:
> 
> ```kotlin
> single { 
>         SampleRepositoryImpl(sampleService = get())
>     } bind SampleRepository::class
> ```
> 
> or even
> 
> ```kotlin
> singleOf(::SampleRepositoryImpl) { 
>        bind<SampleRepository>()
>     }
> ```
> 
> The idea is to go through your Koin configurations, not scan for all class constructors.

The [documentation](https://insert-koin.io/docs/reference/koin-test/checkmodules#koin-configuration-check-with-verify---jvm-only-33) and API doesn't warning us about the deep check not works without explicitly binding.

@arnaudgiuliani, shall we add this information in code and documentation? If yes, I could open a pull request with a suggestion, of course.
