### ISSUE TITLE
Order of onClose calls

### ISSUE THREAD

**Issue by smichovan** [InsertKoinIO/koin#1510]
### Discussed in https://github.com/InsertKoinIO/koin/discussions/1507

<div type='discussions-op-text'>

<sup>Originally posted by **smichovan** January 20, 2023</sup>
Is there a way how to change order in witch the onClose methods of components are called?

Lets have two services where the latter is dependent of the former: 

val appModule = module {
    single { Database() } onClose {it?.closeConnectionPool()} 
    single { ServiceUsingDb(get()) } onClose {it?.useDatabaseForCleanup()}
}

Database component maintains a connection to some DB and the second component accesses the DB through the first component. The "ServiceUsingDb" needs to have DB available in onClose method. As the "ServiceUsingDb" is actually dependent on "Database" I would expect Koin to ensure the right closing order. 

I made some research in the Koin code and if I understand it well, the components (instances, mappings) are stored in HashMap, means no specific order is guaranteed. In my case, it may (and does) happen that when ServiceUsingDb onClose is called, the DB is already closed and the cleanup fails. 

Have I missed anything? Is there any way how to influence the onClose methods order?
</div>

**Comment by arnaudgiuliani** [comment]
Yes, Koin will unload things in order of its index. The onClose function could be predicted to a common component to help you clear resources.

A scope closure could help you trigger one function to close your resources. 

I imagine here, more a shutdown process for the overall Koin app, no? 🤔

**Comment by alturkovic** [comment]
I am running into the same problem as @smichovan where services are closed in no specific order. What is the recommended way to close services in the example that @smichovan provided? A short code example would be greatly appreciated.

**Comment by jacekgajek** [comment]
Aboud predicting of order I'm also out in blue. My code is as follows:

```
fun Application.configureKoin() {
	install(Koin) {
			configureSqs
			configureSns
			configureConsumer
	}
}
```
Each of them registers a `onClose` handler which executes a `println`. The output in the console is consistent and always looks like this:
```
SQS closing
Consumer closing
SNS closing
```
It doesn't change if I switch order of `configure` statements.
