### ISSUE TITLE
Error is being logged in logs if a bean is found in scope, but not found on the '_root_' scope. Is it by design?

### ISSUE THREAD

**Issue by gary0707** [InsertKoinIO/koin#1512]
**Describe the bug**
Some of my beans are defined only in scopes, different than the root scope. At runtime, those beans are properly resolved and created by Koin, but in LogCat I can see Koin's Error:
`[Koin]     E  * No instance found for com.my.package.LoginInteractor on scope ['_root_']`

There were no error printed in version before < 3.x

**To Reproduce**
Create any bean definition in scope, but not in root. Run the app and observe the logcat.

**Expected behavior**
No errors in Logs in case dependencies are resolved properly.

**Koin project used and used version (please complete the following information):**
`koin-core version 3.3.2, constructor DSL`

**Additional moduleDefinition**
```kotlin
val myKoinModule = module {

    scope<LoginFragment> {
        scopedOf(::LoginInteractor)
        scopedOf(::LoginPresenter) { bind<Presenter>() }
    }
}
```

**Comment by arnaudgiuliani** [comment]
Yes, seems like a log improvement issue 👍 No real error, just engine looking at the needed instance.
