### ISSUE TITLE
ViewModel lazy injection using generic API

### ISSUE THREAD

**Issue by Wrakor** [InsertKoinIO/koin#1516]
**Describe the bug**
IllegalStateException: Your activity is not yet attached to the Application instance. You can't request ViewModel before onCreate call.

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/2973191/217036938-78cc0c5f-96fa-4522-ab16-2e7d3527f1af.png">

**To Reproduce**
Try to use method on a base activity class variable:

```
open class MvvmActivity<T : ViewDataBinding, V : BaseViewModel>(bindingInflater: BindingInflater<T>, clazz: KClass<V>) : AppCompatActivity() {

protected val viewModel: V by viewModelForClass(clazz)
(...)
}
```

**Expected behavior**
Lazy method shouldn't prevent class initialization.

**Koin project used and used version (please complete the following information):**
io.insert-koin:koin-android:3.3.2

**Comment by arnaudgiuliani** [comment]
It's an Android ViewModel thing, don't try to access it before Activity is initialized. Delegate some parts of your component elsewhere, else perhaps the ViewModel is not the kind of instance you need.

**Comment by logickoder** [comment]
@Wrakor I had the same issue and I was able to bypass it by making my viewmodel a lazy instance

`
val viewModel: V by lazy {
        // the reason for this is that doing this directly will result in a crash because of
        // accessing viewmodel before onCreate, so making it a lazy instance is a nice hack
        val v by viewModelForClass(clazz)
        v
    }
`

**Comment by Lokesh-30** [comment]
I am facing a similar kind of issue

**Comment by arnaudgiuliani** [comment]
what version?
