### ISSUE TITLE
What is the real usage scenario for shared koin modules API?

### ISSUE THREAD

**Issue by gary0707** [InsertKoinIO/koin#1517]
Hi,

I am trying to understand what is the proper usage scenario for 
https://insert-koin.io/docs/reference/koin-core/modules#sharing-modules

If I have an Android App with 4 Gradle modules:

- `app` (having its own `val mainAppModule = module { ... }`)
- `featureA` (having its own `val featureAModule = module { ... }`)
- `featureB` (having its own `val featureBModule = module { ... }`)
- `commonStuff`(having its own `val commonModule = module { ... }`)

then  I load those 4 koin modules when the application starts like:
```kotlin
startKoin {
      modules(
          mainAppModule,
          featureAModule,
          featureBModule,
          commonModule,
      )
}
```

Is there any difference in the Koin behavior (timing/resources) when I would declare the `commonModule` as `fun`:
```kotlin
fun commonModule() = module { ... }
```

**Comment by arnaudgiuliani** [comment]
Not sure this is still relevant 🤔  writing `fun commonModule() = module { ... }` allows sharing the same code but avoids reusing the module allocated index.

**Comment by gary0707** [comment]
Hi @arnaudgiuliani ,
Thanks for addressing this and my other issues/questions. 

I am not sure that I follow you regarding "reusing the module allocated index". Which part of the Koin doc refers to that index? I would like to understand your answer above :D

**Comment by arnaudgiuliani** [comment]
I'm afraid that the only doc for that is the code 😅  In short

Module -> Koin indexes

Indexes are used for our definition search

**Comment by gary0707** [comment]
Thank you. I will have a look for better understanding. The issue can be closed.
