### ISSUE TITLE
Importing Maven BOMs

### ISSUE THREAD

**Issue by softartdev** [InsertKoinIO/koin#1519]
I always get frustrated when I [can't install one version for all](https://github.com/softartdev/NoteDelight/blob/3ac65e56b8a0b4acf088ae61e8e14a674eeaf0a4/gradle/libs.versions.toml#L65) modules of a library.

Why can't you just publish all modules on every version update? Maybe there is a reason, I don't know.

How about a [Maven BoM (Bill of Materials) import](https://docs.gradle.org/current/userguide/platforms.html#sub:bom_import)? It is just designed to solve such problems. I see a few years ago [there was one attempt](https://github.com/InsertKoinIO/koin/pull/925), but for some reason the PR did not merge.

BoM allows developers to manage all versions of library by specifying only one version, the BoM version. It is already used in libraries like [Firebase](https://firebase.google.com/docs/android/learn-more#bom), [OkHttp](https://github.com/square/okhttp#releases) and many more.

**Comment by arnaudgiuliani** [comment]
General Koin project (core,test,android,ktor and androidx-compose) follow the same track number. There was a gap, and 3.4 will realign all libraries on 3.4.x track. This means that Q1 & Q2 2023 you will have Koin 3.4.x in all libraries

Also depends on what you are using?

**Comment by arnaudgiuliani** [comment]
Will be deployed with Koin 3.5.0
