### ISSUE TITLE
Does Koin support generic types?

### ISSUE THREAD

**Issue by ninja-** [InsertKoinIO/koin#1521]
**Is your feature request related to a problem? Please describe.**

Guice uses generic types to create qualifiers, so for example
`Repository<User>` and `Repository<Post>` are two different objects.
(if Repository is a singleton, then I believe two seperate singletons are created for User and Post)

No such logic seems to exist in Koin to read generics at all.
I guess it only makes a difference if such classes are scoped or singletoned in any way.
Looking over my usage of generic classes, none of them are scoped, so probably it won't block migration from Guice in the short-term...

**Describe the solution you'd like**
Replicate Guice trick used to fight type erasure, integrate with Qualifier system, and update possible toString() methods
to render generic info in `<` `>`

```
inline fun <T> inject() =
    inject(qualifier = object : TypeLiteral<T>() {}))
```

**Describe alternatives you've considered**
Refactoring project not to depend on generics in DI.

**Target Koin project**
koin-core

**Comment by ninja-** [comment]
Just noticed it's a known limitation: https://insert-koin.io/docs/reference/koin-core/definitions#dealing-with-generics

**Comment by arnaudgiuliani** [comment]
yea, for now it's still a limitation. We should use `KType` of Kotlin to understand generic type but performances are not really the same.

**Comment by ninja-** [comment]
yes I've read there is a now stable `typeOf()` function that works similiar to TypeLiteral. 
I've also read that Kotlin compiler does a pretty good job at optimizing it.

**Comment by dalewking** [comment]
Kodein also supports differentiating on non-erased types if you need to see how it can be done. This limitation makes Koin a non-starter on our project.

**Comment by arnaudgiuliani** [comment]
still keeping this

**Comment by volo-droid** [comment]
@arnaudgiuliani would it be possible to make KType usage optional and thus isolate the performance hit only for cases where generic types are actually used? (maybe by introducing explicit methods, i.e. `singleType`)
