### ISSUE TITLE
Logging org.koin.core.error.NoBeanDefFoundException: No definition found for class:'org.koin.core.logger.Logger' q:''. Check your definitions!

### ISSUE THREAD

**Issue by Artrosis** [InsertKoinIO/koin#1523]
I'm trying to connect Koin to my project. I need logging. But when I start the application I get an error: **org.koin.core.error.NoBeanDefFoundException: No definition found for class:'org.koin.core.logger.Logger' q:''. Check your definitions!**

I have little experience with Kain so I can't figure out if I'm doing something wrong or if it's a Koin error.

I have attached an archive with a project to reproduce the error. I tried using SLF4J Logger, and PrintLogger.

[kotlin-koin.zip](https://github.com/InsertKoinIO/koin/files/10740427/kotlin-koin.zip)

**Comment by Artrosis** [comment]
I took an example https://github.com/InsertKoinIO/koin-getting-started/tree/main/kotlin
added dependency
`implementation("io.insert-koin:koin-logger-slf4j:3.3.1")`
in gradle.kts
and changed UserApplication.kt:

```
class UserApplication : KoinComponent {

    val userService: UserService by inject()
    val logger: Logger by inject()

    init {
        userService.saveDefaultUsers()
    }
    fun sayHello() {
        val user = userService.getDefaultUser()
        val message = "Hello '$user'!"
        logger.info(message)
        println(message)
    }
}

fun main() {
    startKoin {
        //logger(SLF4JLogger())
        logger(PrintLogger())
        modules(appModule)
    }

    UserApplication().sayHello()
}
```

**Comment by Artrosis** [comment]
it looks like the logger(Print Logger()) function does not do what I expected from it. Based on the experience of using Spring and DI in .Net I expect the blogger() function to add the corresponding logger to the container as a dependency.
I have read the documentation and looked at the examples from https://github.com/InsertKoinIO/koin-getting-started and it seems to me that this feature should be reflected either in the documentation or add examples with the configuration of the logger. For the server Side on JVM, it's probably worth adding an example with the SLF4J Logger() setup.

**Comment by arnaudgiuliani** [comment]
Logger, defined from Koin start configuration is not "accessible" from your DI configuration. LSF4J is used with Ktor app here.

**Comment by Artrosis** [comment]
I solved this problem by adding a logger manually in the module:

```
import org.koin.core.logger.Logger
import org.koin.dsl.module
import org.koin.logger.SLF4JLogger

val MainModule = module {
    single<Logger>{ SLF4JLogger() }
}
```

**Comment by Artrosis** [comment]
perhaps this example should be added in tutorial
