### ISSUE TITLE
Documentation about context isolation is unclear

### ISSUE THREAD

**Issue by mecoFarid** [InsertKoinIO/koin#1524]
I have checked the documentation about [Context Isolation](https://insert-koin.io/docs/reference/koin-core/context-isolation)

It is quite confusing, There are two snippets with:

```
// Register the Koin context
MyKoinContext.koinApp = KoinApp
```

```
// Register the Koin context
MyKoinContext.koinApp = myApp
```
 
I mean you can't initialize `MyKoinContext.koinApp = ` twice, right?!

It would be awesome if we had a bit clearer instructions.

**Comment by arnaudgiuliani** [comment]
updated in 63e49216e0f5dc2bf297caed38e89175f9bad386
