### ISSUE TITLE
[Bug] hashCode() collision can lead to eager singletons being silently ignored

### ISSUE THREAD

**Issue by ninja-** [InsertKoinIO/koin#1525]
**Describe the bug**
A recent code change introduced a bug here: https://github.com/InsertKoinIO/koin/blob/9cab9bc7329bed405377739bb4858ed752fb98ce/core/koin-core/src/commonMain/kotlin/org/koin/core/registry/InstanceRegistry.kt#L59

Assuming two hashCodes() can collide for these factories, the previous one will be silently discarded and instance will not be created on start.

**Expected behavior**

Use a HashSet or HashMap<SingleInstanceFactory, True>

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core version 0.9.2`

**Additional moduleDefinition**
Add any other moduleDefinition about the problem here.

**Comment by arnaudgiuliani** [comment]
this is wanted, to allow a factory to "override" another at start

**Comment by ninja-** [comment]
noo that still has a rare(but still!) mathematical chance of hashCode collision with a factory that's _completely unrelated_ and of _different type_ :(

what you could do instead to achieve your goal is

```
    private val eagerInstances = setOf<SingleInstanceFactory<*>>()
    
              eagerInstances.remove(factory);
               eagerInstances.add(factory);
```

**Comment by arnaudgiuliani** [comment]
let's reopen it if needed
