### ISSUE TITLE
Please add support for android jetpack

### ISSUE THREAD

**Issue by leodeleon22** [InsertKoinIO/koin#153]
**Is your feature request related to a problem? Please describe.**
Yes. If you try to use the new android package system androidx the koin extensions won't reconize the new classes 

**Describe the solution you'd like**
Add support for the new androidx package naming on the koin extensions

**Describe alternatives you've considered**
I tried changing the extensions myself but some mehtods are private

**Target Koin project**
https://github.com/leodeleon22/PopularMovies

**Comment by arnaudgiuliani** [comment]
Hello,

Hello, new androidx packages integration is already "in".

You can already try: `koin-androidx-viewmodel:1.0.0-beta-1` gradle package.  We have mentioned here the new packages: https://github.com/InsertKoinIO/koin/issues/144

**Comment by BlackHornet** [comment]
Hello,

after adding androidx-viewmodel i got following sync error:

Failed to resolve: org.koin:koin-reflect:1.0.0-beta-1


Not sure where it comes from :/

Regards

**Comment by arnaudgiuliani** [comment]
yep, sorry. `beta-2` have just been published to fix this.

**Comment by BlackHornet** [comment]
awesome responsivity 1.000.000x :+1:
