### ISSUE TITLE
viewModelOf in the commom shared

### ISSUE THREAD

**Issue by taymiyyah** [InsertKoinIO/koin#1530]
the issue:
we are using koin for kmm, it is pretty good except with view models  , each time we add a view model we have to declare that in the ios main package 
```
  val provideUserBookingViewModel: UserBookingViewModel = UserBookingViewModel(
        fetchAllBookingsUseCase = get(),
        saveBookingUseCase = get(),
        lostBookingIdUseCase = get()
    )
```

the solution:
we want to have something like `viewModelOf` in the shared module so we can make our viewmodels dependences common , we really want to use viewModelOf to avoid m.leak and we really want to stop the issue above

**Target Koin project**
KMM

**Comment by ninja-** [comment]
I am pretty sure you can get this done with current API, but I can't give you 100% exact code without seeing full code.
However, try to start with that:

Module:

```
factoryOf(::UserBookingViewModel) 
```

You might need to apply some scopes to these factories, I am not very familiar with the scope system in Koin.

Code:
```val provideUserBookingViewModel = get()```

**Comment by taymiyyah** [comment]
@ninja-  factoryOf(::UserBookingViewModel) // or singleOf for singleton this will make a lot of m.leak

**Comment by izadiegizabal** [comment]
now that the ViewModel is [KMP compatible](https://developer.android.com/jetpack/androidx/releases/lifecycle#2.8.0) (for iOS/Android), maybe it would be nice to have this back? for now `factoryOf` gets the job done but it could be nice to have the options of `viewModelOf` :)

**Comment by rrocav3** [comment]
I think what @izadiegizabal could be cool, now I'm using factoryOf or viewModel
