### ISSUE TITLE
`Module.verify()` fails due to definitions that don't use the class constructor

### ISSUE THREAD

**Issue by damianogiusti** [InsertKoinIO/koin#1538]
**Describe the bug**

When using `Module.verify()` to verify the module configuration, it fails with a `Missing type <T> for class <C>` error when a dependency is declared in a module and its definition is not created by calling the constructor.

For example, given the following configuration:

```kotlin
class DependencyA

class DependencyB

class Main(
    val dependencyA: DependencyA,
    val dependencyB: DependencyB
) {
    companion object {
        fun create() = Main(DependencyA(), DependencyB())
    }
}

val module = module {
    factory { Main.create() }
}
```

the `verify` function fails with the following error:

```
* ----- > Missing type 'com.package.DependencyA' for class 'com.package.Main' in definition '[Factory:'com.package.Main']'
Fix your Koin configuration or add extraTypes parameter: verify(extraTypes = listOf(com.package.DependencyA::class))
```

While at runtime the configuration is correct because the `Main` class can be instantiated thanks to the `create()` factory method.

This issue is clearer when using an external library and manually creating the definition of a class of that library that has a public constructor but is instantiated using a static factory method or another factory class.

**To Reproduce**

Run this unit test:

```kotlin
class DependencyResolutionTest {

    @Test
    fun `module verification accepts factory methods`() {
        val module = module {
            factory { Main.create() }
        }

        module.verify()
    }
}
```

**Expected behavior**

The test should pass.

**Koin project used and used version (please complete the following information):**
- `koin-core version 3.3.3`
- `koin-test version 3.3.3`
- `koin-android version 3.3.3`

**Comment by arnaudgiuliani** [comment]
yes, this is a current limitation. Need to provide improvements for builder API.

**Comment by arnaudgiuliani** [comment]
it's a limitation we can't handle with verify() API, is about detecting default values in the constructor. Koin annotations will bring such support 👍 

But sorry, verify() can't solve that for now.  Take a look at `checkModules` instead.
