### ISSUE TITLE
How can multiple fragment on a single activity share the same viewmodel

### ISSUE THREAD

**Issue by BaiMingxu** [InsertKoinIO/koin#1539]
Multiple fragment share the same viewmodel and get the same data in it all the time

**Comment by marcellogalhardo** [comment]
@BaiMingxu you can host the view model in the `Activity`, and request them from your Fragments.

```
class Fragment1 : Fragment() {
  val vm by activityViewModel<SharedViewModel>()
}

class Fragment2 : Fragment() {
  val vm by activityViewModel<SharedViewModel>()
}
```

For more details, see Koin's docs: [Activity Shared ViewModel](https://insert-koin.io/docs/reference/koin-android/viewmodel/#activity-shared-viewmodel).

**Comment by BaiMingxu** [comment]
thanks
