### ISSUE TITLE
Parameters stack clears when definition not found

### ISSUE THREAD

**Issue by Merseyside** [InsertKoinIO/koin#1544]
**Describe the bug**
I have a trouble when trying to get not existing instance with getOrNull(). If there is no definition in whole koin context, parameters stack cleared for some reason. I found this code in Scope.kt, resolveValue method:

```
?: run {
            KoinPlatformTools.synchronized(this@Scope) {
                _parameterStack.clear()
            }
            _koin.logger.debug("|- << parameters" )
            throwDefinitionNotFound(qualifier, clazz)
        })
```

**To Reproduce**
Try to getOrNull() for not existing instance. Then get() method won't work because parameters stack was cleared.

**Expected behavior**
Stack is not cleared.

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core version 3.3.2`

**Comment by arnaudgiuliani** [comment]
fixed in 3.4.3
