### ISSUE TITLE
Update to 3.3.3 to 3.4.0 -> NoBeanDefFoundException: No definition found for class:'androidx.activity.ComponentActivity 

### ISSUE THREAD

**Issue by BenAtJambit** [InsertKoinIO/koin#1546]
Hi,
I'm not sure, it's a bug. But maybe a breaking change, or .... Hope, you can explain to me why this happens...

I just updated to Kotlin Core 3.4.0 and can't start the app anymore. If I downgrade back to 3.3.3, everything works fine.

As described in the title I get a 'NoBeanDefFoundException' exception if Koin tries to initialize a class that requires 'ComponentActivity' as an argument.

Following Class:
class CmpManager(
    private val activity: ComponentActivity,
    private val preferencesManager: PreferencesManager,
    private val config: CmpConfig,
) { ... }

My Module has the following line of code: 'singleOf(::CmpManager)'
Is this now a bug in the latest version of Koin, or a breaking change? What do I need to do to bring it back to work?

Thanks
Ben

Ps:
Originally I initialize it with scope:
scope<MainActivity> {
        scopedOf(::CmpManager)
}
But I thought, maybe that could be the reason and changed it to singleOf, but as said without success.

**Comment by arnaudgiuliani** [comment]
Could you have a small sample project? could help me go faster in reproducing it 🙏

**Comment by kvn-stgl** [comment]
Well ... the fix is simple:
```
    scope<MainActivity> {
        scoped { CmpManager(get<MainActivity>()) }
    }
```

**Comment by arnaudgiuliani** [comment]
seems ok to be closed then 👍
