### ISSUE TITLE
I can’t add (io.insert-koin:koin-compose:1.0.0) in Multiplatform project

### ISSUE THREAD

**Issue by ahmadhassan5** [InsertKoinIO/koin#1547]
Logs:
`A problem occurred configuring project ':shared'.
> Could not resolve all dependencies for configuration ':shared:iosArm64CompileKlibraries'.
   > Could not resolve io.insert-koin:koin-compose:1.0.0.
     Required by:
         project :shared
      > No matching variant of io.insert-koin:koin-compose:1.0.0 was found. The consumer was configured to find a library for use during 'kotlin-api', preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native', attribute 'org.jetbrains.kotlin.native.target' with value 'ios_arm64' but:
          - Variant 'jsApiElements-published' capability io.insert-koin:koin-compose:1.0.0 declares a library for use during 'kotlin-api':
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_arm64')
          - Variant 'jsRuntimeElements-published' capability io.insert-koin:koin-compose:1.0.0 declares a library:
              - Incompatible because this component declares a component for use during 'kotlin-runtime', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js' and the consumer needed a component for use during 'kotlin-api', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_arm64')`

**Comment by dimkinware** [comment]
Have the same problem. Maybe there are some experimental release with support of ios target?

**Comment by wman1980** [comment]
same issue as @Nailik

**Comment by arnaudgiuliani** [comment]
seems duplicated with https://github.com/InsertKoinIO/koin/issues/1567
