### ISSUE TITLE
startKoin from java

### ISSUE THREAD

**Issue by saied89** [InsertKoinIO/koin#155]
My application is java but I want to use Koin in my Kotlin Code.
I have found this PR
https://github.com/InsertKoinIO/koin/pull/25
It states that could be done like
`AndroidExtKt.startKoin(this, this, modules, properties);`

But how is the modules defined?

**Comment by saied89** [comment]
I needed to pass 2 null args
`AndroidExtKt.startKoin(this,this ,Arrays.asList(Api_moduleKt.getApiModule()), null, null);`

**Comment by saied89** [comment]
My question was how to start Koin from java. Its more a question of Kotlin interop but I think it is fairly common so please consider putting it in the docs.
The solution looks sth like this.
`AndroidExtKt.startKoin(this,this ,Arrays.asList(Api_moduleKt.getApiModule(), App_moduleKt.getApp_module()), MapsKt.<String, Object>emptyMap(),new AndroidLogger());`

**Comment by arnaudgiuliani** [comment]
The best is that you wait the `koin-java` project that will help you on this topic.
Beta will be published in next days.

**Comment by arnaudgiuliani** [comment]
Here is all you need for java: https://beta.insert-koin.io/docs/1.0/quick-references/koin-java/

**Comment by PanSmolniy** [comment]
this lags as hell
