### ISSUE TITLE
Annotations: Module with no components (yet) fails build - fix requires clean build

### ISSUE THREAD

**Issue by eekboom** [InsertKoinIO/koin#1562]
**Describe the bug**
When there is an annotated koin module class `AppModule`, for which no components exist yet, then no module source code is generated for it and the build fails if it tries to use `AppModule().module`. The error message is not helpful at all..

Even adding annotated components does not fix the build, then, unless gradle `clean` task is executed. I consider this a second bug.

This happened to me when I tried to get started with annotations in a project. I nearly gave up on koin in the process.

**To Reproduce**
I made an example project to reproduce these bug: https://github.com/eekboom/koin-ktor-test
1. Clone the project
2. Execute the run task (from IDEA or command line `.\gradlew run`)
3. Build should work, but it fails with
```
> Task :app:compileKotlin FAILED
e: file:///C:/dev/dev/github/eekboom/koin-ktor-test/app/src/main/kotlin/de/eekboom/koin_ktor_test/Main.kt:18:17 Unresolved reference: ksp
e: file:///C:/dev/dev/github/eekboom/koin-ktor-test/app/src/main/kotlin/de/eekboom/koin_ktor_test/Main.kt:25:37 Unresolved reference: module
```
Also, IDEA shows the package for generated sources is missing:
![bild](https://user-images.githubusercontent.com/717179/232823223-7ec1ca11-f439-4867-825f-0245f824d237.png)

5. Let's try to fix it. Go to class GreetingsService and remove the comment marker before `@Single`:
![bild](https://user-images.githubusercontent.com/717179/232823673-ce9012e6-42fa-4f8a-a7f1-fcb9980033d0.png)

6. Execute the run task (from IDEA or command line `.\gradlew run`)
7. Build should again work and now the application should even start correctly. Instead I get a different error:
```
> Task :app:compileKotlin FAILED
2 actionable tasks: 2 executed
e: file:///C:/dev/dev/github/eekboom/koin-ktor-test/app/src/main/kotlin/de/eekboom/koin_ktor_test/Main.kt:18:31 Unresolved reference: module
e: file:///C:/dev/dev/github/eekboom/koin-ktor-test/app/src/main/kotlin/de/eekboom/koin_ktor_test/Main.kt:25:37 Unresolved reference: module
```
![bild](https://user-images.githubusercontent.com/717179/232829245-ff3da949-bddc-44bc-b1a6-12ecd732278a.png)

8. Execute gradle tasks `clean` and `run` => Application builds and starts.

**Expected behavior**
Even if the module is "empty" (component scan gives no components) a source file should be generated for the module.
(Maybe a compiler warning like "no component found for module" would be nice.)
After adding a component it should be picked up without requiring a clean build.

**Koin project used and used version (please complete the following information):**

* `koin-core version 3.4.0`
* `koin annotation version 1.2.0`

**Comment by eekboom** [comment]
Thanks, here it is: https://github.com/InsertKoinIO/koin-annotations/issues/80

**Comment by dmccabe** [comment]
Appreciate the write up on this @eekboom! I'm new to Koin and hit this exact issue, I was just as confused. The steps you outlined resolved the problem for me too.
