### ISSUE TITLE
koin annotations cause compiler warning

### ISSUE THREAD

**Issue by eekboom** [InsertKoinIO/koin#1563]
I like to have my build configured to fail on warnings (`-Werror` or `compilerOptions { allWarningsAsErrors = true }` in gradle).

Unfortunately, using koin annotations causes compiler warnings and it is tricky in gradle to set the compiler up to ignore warnings only in the generated code.

Here is the warning:

```
> Task :app:compileKotlin
w: file://~/dev/github/acme/foobar/app/build/generated/ksp/main/kotlin/org/koin/ksp/generated/KoinAppModuleGende$acme$foobar.kt:7:6 Variable 'moduleInstance' is never used
```

The source of the generated module file looks like this
```
public val de_acme_foobar_KoinAppModule = module {
	val moduleInstance = de.acme.foobar.KoinAppModule()
	single(qualifier=null) { de.acme.foobar.user.UserService(get()) } 
	...
```
and moduleInstance is indeed unused.

Could you make the code so that it does not cause any compiler warnings?
Even just adding `@Suppress("UNUSED_VARIABLE") ` would be fine.

koin 3.4.0
koin-annotations 1.2.0

**Comment by arnaudgiuliani** [comment]
can you reopen an issue in the right github repo? https://github.com/InsertKoinIO/koin-annotations/issues

**Comment by eekboom** [comment]
See https://github.com/InsertKoinIO/koin-annotations/issues/79
