### ISSUE TITLE
Annotations setup in multi-module Gradle architecture

### ISSUE THREAD

**Issue by bogdanzurac** [InsertKoinIO/koin#1566]
**Is your feature request related to a problem? Please describe.**
When using Koin Annotations in a multi-module Gradle architecture, we need to declare a Koin module per each individual Gradle module in order to pick up the components from that particular Gradle module. That means that even for Gradle modules that have simple setups with maybe only 1 component, we still need to manually declare a Koin module.

**Describe the solution you'd like**
In a similar architecture, Dagger doesn't require a separate Dagger module to be defined for each Gradle module. That simplifies the setup a lot, especially for projects with hundreds of Gradle modules. Would it be possible to automatically add components from *any* Gradle module to the `defaultModule` definition from the main Gradle module that calls the `startKoin` method?

**Comment by arnaudgiuliani** [comment]
Good question, but wrong repo 😅  Can you reopen it on https://github.com/InsertKoinIO/koin-annotations/issues ?
🙏
