### ISSUE TITLE
Support for Multiplatform Compose - iOS

### ISSUE THREAD

**Issue by hm-tamim** [InsertKoinIO/koin#1567]
Now that Compose has Alpha support on iOS. Any plan to add support to it?

Tried using implementation("io.insert-koin:koin-compose:1.0.1")

Getting this error:
Could not find io.insert-koin:koin-compose-iosarm64:1.0.1.

**Comment by arnaudgiuliani** [comment]
ok 👍

**Comment by arnaudgiuliani** [comment]
finally found that the CI doesn't produce it. Repushing it: 761221cd7252e3f78b6d2878aa765c8e9dc8f433

**Comment by arnaudgiuliani** [comment]
Full republication is done. Check with compose-1.0.2 👍
