### ISSUE TITLE
Duplicate class found build error with koin-core-coroutines Android

### ISSUE THREAD

**Issue by tyczj** [InsertKoinIO/koin#1568]
I wanted to try out the new lazyModules but when I add the dependency `koin-core-coroutines` I get a build error saying

`Duplicate class org.koin.core.context.DefaultContextExtKt found in modules koin-core-coroutines-jvm-3.4.0 (io.insert-koin:koin-core-coroutines-jvm:3.4.0) and koin-core-jvm-3.4.0 (io.insert-koin:koin-core-jvm:3.4.0)`

**To Reproduce**
1. Add dependencies to build.gradle (version used is 3.4.0)
    koin-android
    koin-android-compat
    koin-androidx-workmanager
    koin-ksp-compiler
    koin-core-coroutines

2. Build and run

**Comment by arnaudgiuliani** [comment]
fixed in 3.4.1
