### ISSUE TITLE
Injecting into Worker class from WorkManager

### ISSUE THREAD

**Issue by sriramr98** [InsertKoinIO/koin#157]
We need to be able to inject classes into the new Worker class from WorkManager API's. This will be useful if we need to inject NetworkRepo's or LocalDbRepo's etc..

**Target Koin project**
https://github.com/sriramr98/Wally

**Comment by arnaudgiuliani** [comment]
Hi @sriramr98 , I'll check that 👍

**Comment by sockeqwe** [comment]
You can access `applicationContext` from Worker, isn't it enough?

**Comment by sriramr98** [comment]
@sockeqwe How do you inject a class using the applicationContext ?

**Comment by stasbar** [comment]
You can make your `Worker` class implement `KoinComponent` interface
then simply in doWork() you can call 
```kotlin
    val networkRepo: NetworkRepo by inject()
```

**Comment by sriramr98** [comment]
Thanks, @stasbar. Works perfectly

**Comment by mochadwi** [comment]
> You can make your `Worker` class implement `KoinComponent` interface
> then simply in `doWork()` you can call
> 
> ```kotlin
>     override fun doWork(): Result {
>         val networkRepo: NetworkRepo by inject()
>         ...
>     }
> ```

nice works perfectly as well!!!
