### ISSUE TITLE
Annotations should allow to not automatically bind the component's parent interface

### ISSUE THREAD

**Issue by bogdanzurac** [InsertKoinIO/koin#1572]
**Is your feature request related to a problem? Please describe.**
The following setup is given:

```
interface Animal

@Single
class Dog : Animal

@Single
class Cat : Animal

@Module
@ComponentScan
class AnimalModule {

    @Single
    fun animal(cat: Cat, dog: Dog): Animal = if (randomBoolean()) cat else dog
}
```
We'd like to choose dynamically at runtime which implementation of the `Animal` interface we want to inject. However, the default behaviour of the `Single` annotation will automatically bind each of the 2 `Animal` implementations to the `Animal` class, which is wrong and adds unpredictability towards which of the 2 classes will be actually injected at runtime.

**Describe the solution you'd like**
There should be a way to turn off this behaviour and thus allow both 1) the injection of the individual implementations, such that they can still be injected in the `AnimalModule` as well as 2) the ability to bind ourselves manually which implementation we want to the `Animal` interface.

**Comment by arnaudgiuliani** [comment]
interesting, but can you move this issue on https://github.com/InsertKoinIO/koin-annotations/issues?

thanks 🙏
