### ISSUE TITLE
New viewmodel instances are not provided when different parameters are specified during injection

### ISSUE THREAD

**Issue by snaum47** [InsertKoinIO/koin#1578]
**Describe the bug**
Inside our fragment we inject viewmodels with different parameters provided each time. 
The 1st instance with its parameters is provided on all future injections of the viewmodel in the same fragment.

**To Reproduce**
```
// the module
fun appModule() = module {
  viewModel { parameters ->
    SomeViewModel(parameters.get())
  }
}

// the viewmodel
class SomeViewModel(
  val id: UUID
): ViewModel() {

  fun printId() {
    println("Printing SomeViewModel $id")
  }

}
class SomeFragment : Fragment() {
  override fun onResume() {
    super.onResume()
    initialize()
    initialize()
  }

  private fun initialize() {
    val viewModel: SomeViewModel by viewModel {
      parametersOf(UUID.randomUUID())
    }
    viewModel.printId()
  }
}
```
What will be printed is:
```
Printing SomeViewModel 2e7d1d81-3506-49c6-845b-6f926ab8fa86
Printing SomeViewModel 2e7d1d81-3506-49c6-845b-6f926ab8fa86
```

**Expected behavior**
What's expected is that there should be a new viewmodel instance for the 2nd initialize call. The UUID for the 2nd print should be different. 

**Koin project used and used version (please complete the following information):**
 `koin-android version 3.4.0`

**Additional moduleDefinition**
Add any other moduleDefinition about the problem here.

**Comment by arnaudgiuliani** [comment]
yes, it's intended here as we don't have an identifier depending on parameters:
![image](https://github.com/InsertKoinIO/koin/assets/2360688/21954973-79ba-4fc7-b363-8044dcde338c)

the ViewModel is held by WM Lifecycle API.  Before getting into patch consideration, look on your side if VM is the right definition of support. You could use factory to do what you want here.

**Comment by p-fischer** [comment]
From a user point of view, parameters in the `viewModel{}`construct are most likely used as constructor argument of a view model constructor. A view model constructor parameter is scoped to the lifetime of the view model instance. 
So I'd expect that the `viewModel{}` construct would create/resolve different view model instance for different parameters.

Would it make sense to treat `parameters` just like the `key` parameter?
Otherwise we'd need to always pass our parameter to `key` redundantly.
In case of multiple parameters, we'd need to map them to a single value to pass them to the `key` parameter.

Are there case, where parameters shouldn't create a different view model instance?

**Comment by snaum47** [comment]
> yes, it's intended here as we don't have an identifier depending on parameters: ![image](https://user-images.githubusercontent.com/2360688/238721502-21954973-79ba-4fc7-b363-8044dcde338c.png)
> 
> the ViewModel is held by WM Lifecycle API. Before getting into patch consideration, look on your side if VM is the right definition of support. You could use factory to do what you want here.

Injecting it using `by inject()` instead of `by viewModel()` will not do the job on our side, since there will be memory leaks as the viewmodel will not be cleared when the fragment is about to be destroyed. 
I think an identifier based on the parameters would be nice to have.

**Comment by arnaudgiuliani** [comment]
Ok, it's more a "new" feature to help. Perhaps an identifier generated from ParametersDefinition. But need to check the risk of memory leak 👍

**Comment by arnaudgiuliani** [comment]
duplicated with https://github.com/InsertKoinIO/koin/pull/1592

**Comment by snaum47** [comment]
One thing to note, these merged changes would not the fix the issue we are facing, mainly because using "by viewmodel" does not have an option to provide the key as a parameter. Can you provide any guidance on this?
