### ISSUE TITLE
SharedViewModelCompat.getSharedViewModel is no longer static for Java

### ISSUE THREAD

**Issue by ZackOPP** [InsertKoinIO/koin#1579]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
As of [this commit](https://github.com/InsertKoinIO/koin/commit/341b5f88a86cffe342f6e0e9d365ad7087e9f5d1), not all overloads of `SharedViewModelCompat.getSharedViewModel` are static. It would be nice to add it back.

**Describe alternatives you've considered**
N/A

**Target Koin project**
koin-android-compat

**Comment by arnaudgiuliani** [comment]
Fixed in related commit
