### ISSUE TITLE
Broken workerOf overloads

### ISSUE THREAD

**Issue by janseeger** [InsertKoinIO/koin#1581]
**Describe the bug**
Some workerOf overloads are named viewModelOf, which has been introduced with https://github.com/InsertKoinIO/koin/pull/1359

**To Reproduce**
None, see code

**Expected behavior**
All of the overloads are reachable via viewModelOf

**Koin project used and used version (please complete the following information):**
3.4.0 (broken since 3.3.0)

**Comment by arnaudgiuliani** [comment]
duplicate with https://github.com/InsertKoinIO/koin/issues/1554
