### ISSUE TITLE
Creating Api Services using Retrofit

### ISSUE THREAD

**Issue by timplifier** [InsertKoinIO/koin#1583]
**Is your feature request related to a problem? Please describe.**
I faced a kinda problem:
I created a class like that:
`
class NetworkClient(
    authenticator: TokenAuthenticator,
    authorizationInterceptor: AuthInterceptor
) {

    private val retrofit = provideRetrofit(
        provideOkHttpClientBuilder().apply {
            authenticator(authenticator)
            addInterceptor(authorizationInterceptor)
        }.build()
    )

    fun generateMyBusinessProfileApiService() =
        retrofit.createAnApi<MyBusinessProfileApiService>()
        
        private inline fun <reified T : Any> Retrofit.createAnApi(): T = create(T::class.java)
        `
}
I want to create a MyBusinessProfileApiService definition as followed :
`
retrofitApiServiceOf<MyBusinessProfileApiService> {
      getRetrofit()
}
`

**Describe the solution you'd like**
I want Koin framework to have a solution to create an opportunity to create Retrofit Api Services ( Interfaces ).

**Describe alternatives you've considered**
`
single { ApiService(retrofit = get(named("WithoutAuth"))) }
`
`
single { get<NetworkClient>().generateUserApiService() }
`

**Target Koin project**
Koin core / Koin Andorid

**Comment by arnaudgiuliani** [comment]
what's the problem here? just use your class in the DSL?
