### ISSUE TITLE
Can't inject SavedStateViewModels in Java

### ISSUE THREAD

**Issue by ZackOPP** [InsertKoinIO/koin#1584]
**Describe the bug**
None of the Koin's ViewModelCompat functions are able to retrieve a SavedStateViewModel because they're using `CreationExtras.Empty` by default, while the Kotlin variations either allow to provide `CreationExtras` as a parameter or use `defaultViewModelCreationExtras` when it's null

**To Reproduce**
* Declare a ViewModel as follows:
```kotlin
viewModel {
    MyViewModel(
        savedStateHandle = get()
    )
}
```
* Use any of the Koin's ViewModelCompat functions available for Java. It will crash with the following exception:
```
IllegalArgumentException: CreationExtras must have a value by `SAVED_STATE_REGISTRY_OWNER_KEY`
```

**Expected behavior**
Be able to fetch SavedStateViewModels with Koin from Java classes

**Koin project used and used version (please complete the following information):**
`koin-android-compat version 3.4.0`

**Comment by p1nkydev** [comment]
Java is dead, make peace with it :)

**Comment by arnaudgiuliani** [comment]
Yep, the Java Compat API is simply propagating default APIs. I need to review it 👍

**Comment by arnaudgiuliani** [comment]
Please check android-3.5.0 for fix update
