### ISSUE TITLE
Could not find io.insert-koin:koin-compose:1.0.2.

### ISSUE THREAD

**Issue by arindoghosh** [InsertKoinIO/koin#1588]
**koin-compose:1.0.2**
Could not find io.insert-koin:koin-compose:1.0.2.

**Comment by guerrerorodrigo** [comment]
I have the same issue. With `1.0.1` I get this error:
```
Could not find io.insert-koin:koin-compose-iosarm64:1.0.1.
```

I tried updating to `1.0.2` but it can't be found.

**Comment by mz-efento** [comment]
The lib `1.0.3` is now available

**Comment by arindoghosh** [comment]
It's working now, thanks for for fixing the issue.
