### ISSUE TITLE
ktor plugin doesn't allow for context isolation

### ISSUE THREAD

**Issue by zakhenry** [InsertKoinIO/koin#1589]
**Is your feature request related to a problem? Please describe.**
Yes, I want to be able to run my tests concurrently with kotest

**Describe the solution you'd like**
I want to be able to defined an isolated Koin instance such that concurrent instances don't reference the same GlobalContext

**Describe alternatives you've considered**
I've tried a few gross hacks like replacing members at runtime with reflection but the main culprit is `fun Application.getKoin(): Koin = GlobalContext.get()` which cannot be overridden to 

**Target Koin project**
ktor plugin

I'm going to try remove the plugin and come up with a workable solution without it, and I will report back here if I find a useful strategy

**Comment by zakhenry** [comment]
okay yes confirmed I have a solution, but it isn't a workaround - instead I needed to replace the whole `io.insert-koin:koin-ktor` dependency with a fork that changes where koin is stored from global context to the pipeline attributes.


the relevant gist of it is as follows:

```kotlin
val koinKey = AttributeKey<Koin>("KoinKey")

val KoinIsolated = createApplicationPlugin(name = "KoinIsolated", createConfiguration = { koinApplication() }) {
    val monitor = environment?.monitor
    val koinApplication = pluginConfig

    application.attributes.put(koinKey, koinApplication.koin)

    monitor?.subscribe(ApplicationStopping) {
        koinApplication.close()
    }

}

fun Application.getKoin(): Koin = attributes.get(koinKey)
```

I can raise this change as a PR if interested?

I believe this will also close #780

**Comment by arnaudgiuliani** [comment]
you can add a proposal, but here we need a smart way to solve it. There is 2 thing : 
- context isolation: 2 ktor starts doesn't trigger the same Koin context
- default context setup: allow to setup a context or not

is it to solve the first case, to avoid collision between Koin context?

**Comment by arnaudgiuliani** [comment]
PR https://github.com/InsertKoinIO/koin/pull/1593 has been merged back to fix context isolation
