### ISSUE TITLE
Consider adding `linuxArm64` target

### ISSUE THREAD

**Issue by nicolasfara** [InsertKoinIO/koin#1590]
**Is your feature request related to a problem? Please describe.**
Recently, the `kotlinx.coroutines` has added support for the `linuxArm64` target.
I love using Koin in my framework but I'm currently limited in enabling the Linux ARM target because Koin does not support it.

**Describe the solution you'd like**
Add the `linuxArm64` target.

**Describe alternatives you've considered**
No alternatives (unfortunately).

**Target Koin project**
Initially `koin-core` would be sufficient, but expanding the support to as many modules as possible could be beneficial.

**Comment by arnaudgiuliani** [comment]
ok, something we can add in 3.5

**Comment by InsanusMokrassar** [comment]
+ Need it too
