### ISSUE TITLE
Fail to resolve dependency

### ISSUE THREAD

**Issue by giangpham96** [InsertKoinIO/koin#1595]
**Describe the bug**
#1503 changes the behavior of the scope.
Previously, `scope<AClazz> {}` declaration automatically binds the instance of `AClazz` to any inherited superclass or implemented interface.
With the introduced changes, it no longer works that way

**To Reproduce**
1. Declare classes
```
abstract class A

class B : A()

class C(private val a: A)
```

2. Declare the module
```
val module = module {
    scope<B> {
        scopedOf(::C)
    }
}
startKoin {
    modules(module)
}
```

3. Resolve the dependency
```
val c: C by inject()
```

**Expected behavior**
c should be successfully resolved but it wasn't

**Koin project used and used version (please complete the following information):**
`koin-core version 3.4.0`

**Comment by arnaudgiuliani** [comment]
ok, let's see how is it going 👍

**Comment by arnaudgiuliani** [comment]
yes, with the linked issue we need to find a global way to fit with the scope source. It could go before root instance resolution 🤔

**Comment by arnaudgiuliani** [comment]
yep, I will revert it and trace more about ctx resolution: https://github.com/InsertKoinIO/koin/pull/1503#issuecomment-1705523066
