### ISSUE TITLE
Is there a performance penalty for using KoinComponent?

### ISSUE THREAD

**Issue by seokchan-kwon** [InsertKoinIO/koin#160]
I am trying to inject Instance into ViewModel.

I would like to use by inject () with KoinComponent, although injecting via the constructor is possible, as in the example.

Is there a problem with this method?

thank you!!

**Comment by arnaudgiuliani** [comment]
Hello,

No performance penalty but rather some software design penalty: you will inject into properties and link yourself to the Koin container. Whereas if you inject by constructor, no dependency against the container technology.

**Comment by seokchan-kwon** [comment]
Thank you for your kind reply.
