### ISSUE TITLE
rememberKoinInject() not working when used with parameters [koin-compose:1.0.3]

### ISSUE THREAD

**Issue by mz-efento** [InsertKoinIO/koin#1601]
- The problem:

In the example below, the `coroutineScope` is created in the `SomeScreen()` context, and then it is used as a parameter for koin injection. Even though the same `coroutineScope` is used in all recompositions, `rememberKoinInject()` returns new instance of `SomeViewModel` every time. (model is not actually remembered)

```
@Composable
fun SomeScreen() {
    val coroutineScope = rememberCoroutineScope()
    val viewModel = rememberKoinInject<SomeViewModel> { parametersOf(coroutineScope) }
    ...
}
```

- The (probable) cause:

`coroutineScope ` parameter is wrapped into a lambda behind the scenes, and then then the newly created lambda is passed down the chain to composable `remember` method as a key for evaluation. The lambda is different each time so evaluation will be re-run reglardless if provided parameter is the same or not.
 
```
val viewModel = rememberKoinInject<SomeViewModel> { parametersOf(coroutineScope) }
is eqal to
val viewModel = rememberKoinInject<SomeViewModel>(parameters = { parametersOf(coroutineScope) }) //lambda!
```

- The workaround:
As for now, the workaround is to remember the whole lambda with parameter, and pass the exact same lambda to `rememberKoinInject` function:
```
@Composable
fun SomeScreen() {
    val coroutineScope = rememberCoroutineScope()
    val parametersOf: () -> ParametersHolder = remember {
        { parametersOf(coroutineScope) }
    }
    val viewModel = rememberKoinInject<SomeViewModel>(parameters = parametersOf)
    ...
```

- The fix
Providing a working solution that will utilize default `rememberKoinInject` syntax:
```
val viewModel = rememberKoinInject<SomeViewModel> { parametersOf(coroutineScope) }
```

**Comment by flopshot** [comment]
Also seeing this bug in 1.0.3

**Comment by arnaudgiuliani** [comment]
yes, a tricky issue 👍 will look at it

**Comment by hoc081098** [comment]
I think that is expected behavior, since the lambda refs to unstable vars (such as scope), that makes this lambda unstable as well, so the compiler will not remember lambda automatically.

**Comment by hoc081098** [comment]
See https://github.com/slackhq/circuit/pull/466

**Comment by arnaudgiuliani** [comment]
interesting 👍

**Comment by arnaudgiuliani** [comment]
Let's see on koin-compose 1.1.0 how it goes 👍
