### ISSUE TITLE
ScopeId is not generated correctly for AndroidScopeComponent 

### ISSUE THREAD

**Issue by rustamsmax** [InsertKoinIO/koin#1603]
An Activity class implementing AndroidScopeComponent using activityScope() extension function is creating wrong scopeName.
For that reason Koin can not find scoped dependencies and throws NoBeanDefFoundException

`koin-core version 3.4.1`

`kotlin version 1.8.21`

![telegram-cloud-photo-size-2-5467770990655293943-y](https://github.com/InsertKoinIO/koin/assets/36570577/4457ec08-3368-45f0-a046-90336c1a0a67)

**Comment by rustamsmax** [comment]
As a workaround I've created my own extension functions:

![telegram-cloud-photo-size-2-5467770990655293946-y](https://github.com/InsertKoinIO/koin/assets/36570577/2143593c-48a8-45c0-8e90-aa9be0bf035a)

**Comment by arnaudgiuliani** [comment]
duplicated from https://github.com/InsertKoinIO/koin/issues/1600

**Comment by rustamsmax** [comment]
The new release fixes the issue. Thanks
