### ISSUE TITLE
Koin Annotations generates code that doesn't compile from version 1.2.1

### ISSUE THREAD

**Issue by Nohus** [InsertKoinIO/koin#1604]
### Generated code on 1.2.0 :heavy_check_mark: 

```
implementation "io.insert-koin:koin-annotations:1.2.0"
ksp "io.insert-koin:koin-ksp-compiler:1.2.0"
```
![image](https://github.com/InsertKoinIO/koin/assets/11064768/c0969c37-1797-4605-9abb-5f6d2e926f4c)

### Generated code on 1.2.1 :x: 

```
implementation "io.insert-koin:koin-annotations:1.2.1"
ksp "io.insert-koin:koin-ksp-compiler:1.2.1"
```
![image](https://github.com/InsertKoinIO/koin/assets/11064768/9a6256e7-7ab5-41a9-8876-f2fccd589c0a)

As you can see above, the generated code does not compile due to an extra comma.

All that is needed to reproduce this is to have a class like that:

```Kotlin
@Single(createdAtStart = true)
class AnyClass
```

**Comment by arnaudgiuliani** [comment]
duplicated with https://github.com/InsertKoinIO/koin/issues/1604
