### ISSUE TITLE
Koin test 3.4.2 not published

### ISSUE THREAD

**Issue by Nek-12** [InsertKoinIO/koin#1605]
```
> Could not resolve all files for configuration ':androidApp:debugUnitTestCompileClasspath'.
   > Could not find io.insert-koin:koin-test:3.4.2.
     Required by:
         project :androidApp
```

**Comment by arnaudgiuliani** [comment]
Ok. Will check or even republish a new version if needed 👍

**Comment by ScheNiDPG** [comment]
@arnaudgiuliani Do you have any updates on this? It still doesn't seem to be published.

**Comment by ScheNi** [comment]
Hi @arnaudgiuliani , do you have any updates on this? It still doesn't seem to be published.

**Comment by arnaudgiuliani** [comment]
check 3.4.3 publication, it's online 👍

**Comment by Nek-12** [comment]
Can I please ask you to take preventive measures against this happening again? This is at least 5th time that a dependency is not updated along with other deps as I'm using Koin in my work. Maybe a better CI infrastructure would work. And publishing koin-test was procrastinated on for almost 2 months.
