### ISSUE TITLE
DefinitionParameterException when using ParametersHolder.get()

### ISSUE THREAD

**Issue by jobernolte** [InsertKoinIO/koin#1607]
**Describe the bug**
After upgrading from 3.4.0 to 3.4.2 injecting instances using ParametersHolder.get() fails. 

**Example code**

```
module {
  factory { params -> LoadingViewModel(params.get(), get(), get(), get(), get(), get(), get()) }
}
```

I've looked into your code and found out, that you changed the way how getOrNull() works.

version 3.4.0:
```
    open fun <T> getOrNull(clazz: KClass<*>): T? {
        return _values.firstNotNullOfOrNull { value -> if (clazz.isInstance(value)) value as? T? else null }
    }
```

vs version 3.4.2:

```
    open fun <T> getOrNull(clazz: KClass<*>): T? {
        return if (_values.isEmpty()) null
        else {
            increaseIndex()
            val currentValue : T? = _values[index!!]?.let { if (clazz.isInstance(it)) it as? T? else null }
            if (currentValue == null){
                restoreIndex()
            }
            currentValue
        }
    }
```

At the moment when I use parametersOf(...) it does not always reflect the correct order of the parameters needed by a given constructor. So do I need to change my code, or is there a way to get back the old behavior?

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core version 3.4.2`

**Comment by arnaudgiuliani** [comment]
this is fixed in 3.4.3, where it can solve in order or on given type (like default behavior)
