### ISSUE TITLE
Fill constructor extension for auto dependency providing

### ISSUE THREAD

**Issue by Evleaps** [InsertKoinIO/koin#1612]
**Is your feature request related to a problem? Please describe.**
To have a util extension for dependency providing.

Before: 
```kotlin
single<SignInPresenter> { SignInPresenterImpl(get(), get(), get(), get(), get(), get(), get(), get(), get(), get(), get(), get(), get(), get(), get()) }

```

After: 
```kotlin
 single<SignInPresenter> { fillConstructor(::SignInPresenterImpl) }
```

For what? 

- We can forget to update the di file when we added a new dependency. Build failed, we should spend time to find an error and recompile. 
- We have to fix merge conflicts dues to di files. 
- add new get is routine

**Describe the solution you'd like**
I suggest adding extensions to the core folder. 
If you accept it, I will be glad to open a PR. 

```kotlin
inline fun <reified R, reified T1, reified T2> Scope.fillConstructor(
    constructor: (T1, T2) -> R
): R = constructor(get(), get())
```

**Comment by marcellogalhardo** [comment]
Koin supports the feature you are describing since version 3.2. Please refer to [Constructor DSL](https://insert-koin.io/docs/reference/koin-core/dsl-update).

**Comment by arnaudgiuliani** [comment]
yep already deployed since 3.2
