### ISSUE TITLE
How about use BOM?

### ISSUE THREAD

**Issue by valeriyo** [InsertKoinIO/koin#1616]
This is nuts:

<img width="473" alt="image" src="https://github.com/InsertKoinIO/koin/assets/7052801/c6c75a25-857a-4b10-97f6-c24bbeca2822">

There should be either one version for all Koin artifacts, or one BOM version that defines the latest set of compatible libraries with different versions.

**Comment by valeriyo** [comment]
Also, why is `koin-compose` showing `v1.0.3` as latest, when there is `3.4.5` available ?

https://central.sonatype.com/artifact/io.insert-koin/koin-androidx-compose/3.4.5

Makes no sense.

**Comment by arnaudgiuliani** [comment]
Sure :)

**Comment by arnaudgiuliani** [comment]
BOM projects added, will be deployed in Koin 3.5.0
https://github.com/InsertKoinIO/koin/issues/1519
