### ISSUE TITLE
Home site is marked as unsecure and phishing

### ISSUE THREAD

**Issue by vygiszs** [InsertKoinIO/koin#1622]
Hello,

This is not an issue with code, but site itself.

https://insert-koin.io/  Site is marked as not secure inside https://www.abuseipdb.com/ and our security team has blocked it. 
 Can you explain what is happening, because where is a lot of phishing and scamming reports on this site.
 
 Thank you,

**Comment by arnaudgiuliani** [comment]
Nothing was noticed on our side.
