### ISSUE TITLE
Inject by Class instance

### ISSUE THREAD

**Issue by stasbar** [InsertKoinIO/koin#163]
I'm wondering if it is possible to inject by Class ?
Something like 

```kotlin
    val adapter by injectByClass(MyAdapter::class.java)
```

Use case: 
I want to create generic `Activity` with `RecyclerView` that can show any type of `Adapter`. The `Adapter` type, can not be pass as generic type. But what about class instance passed in `intent.extras` ? But then I need some way to resolve the adapter instance from koin without generic type.

```kotlin
    enum class Adapter(val clazz: Class<out RecyclerView.Adapter<*>>) {
        FOO(FooAdapter::class.java), 
        BAR(BarAdapter::class.java)
    }
    override fun onCreate(savedInstanceState: Bundle?) {
        val adapterType = intent.getStringExtra("adapterType")
        val adapterClass = Adapter.valueOf(adapterType).clazz
        val adapter by injectByClass(adapterClass)
        ....
    }
```

**Comment by arnaudgiuliani** [comment]
Hello,

it's actually possible but tricky. It demands to use the `getWith()` function from `KoinComponent` with a `CustomRequest` parameter. In this last you can give the needed `Class`, but you have also to specify a definition filter from the registry (`(BeanRegistry) -> List<BeanDefinition<*>>`). This filter can be neutral/do nothing.

**Comment by stasbar** [comment]
Sorry, but I can't find `getWith()` function in [KoinComponent](https://github.com/InsertKoinIO/koin/blob/94829c87f4adabc30ad8c0fba9722aa7636d5385/koin-core/src/main/kotlin/org/koin/standalone/KoinComponent.kt)

**Comment by arnaudgiuliani** [comment]
Use this from KoinComponent:

```
fun <T : Any> KoinComponent.get(
    name: String = "",
    clazz: KClass<*>,
    scope: Scope? = null,
    parameters: ParameterDefinition = emptyParameterDefinition()
)
```

**Comment by mochadwi** [comment]
> Hello,
> 
> it's actually possible but tricky. It demands to use the `getWith()` function from `KoinComponent` with a `CustomRequest` parameter. In this last you can give the needed `Class`, but you have also to specify a definition filter from the registry (`(BeanRegistry) -> List<BeanDefinition<*>>`). This filter can be neutral/do nothing.

@arnaudgiuliani would you mind explaining to us, what this means? and how to use it?

`val adapter by get(clazz = MyAdapter::class)`

Is this correct way to use it?
