### ISSUE TITLE
BuildConfig is enabled for koin Android and Koin Compose

### ISSUE THREAD

**Issue by Nek-12** [InsertKoinIO/koin#1631]
I'm tired of seeing BuildConfig of koin in all my modules. Build config should be disabled for library modules as it's an anti-pattern in library development.

![image](https://github.com/InsertKoinIO/koin/assets/46318640/dc334f92-8c3f-4a09-9caa-2ba7e653ed68)

The solution is to disable buildconfig for koin modules.

**Comment by 5peak2me** [comment]
This question can be closed.
