### ISSUE TITLE
Add Wasm support

### ISSUE THREAD

**Issue by ygdrasil-io** [InsertKoinIO/koin#1634]
**Is your feature request related to a problem? Please describe.**
We would like to experiment the replacment of an old IoC system to Koin. https://github.com/korlibs/korge/issues/1702
But the required Wasm target is not supported by koin.

**Describe the solution you'd like**
Add Wasm target.

**Describe alternatives you've considered**
Disabling Wasm as target but that will be counterproductive as we need to assess the technology.

**Target Koin project**
koin-core

**Comment by arnaudgiuliani** [comment]
I will be happy to help. Wasm target has also been demanded in the community

**Comment by arnaudgiuliani** [comment]
@ygdrasil-io would be available to test deidcated release?

**Comment by joreilly** [comment]
I have a few samples that use Wasm as well....would also be happy to test

**Comment by arnaudgiuliani** [comment]
oh yeah, thanks @joreilly

**Comment by mkonkel** [comment]
I am building compose Multiplatform app with the **wasm**, is there possibility to test the proposed solution?

**Comment by Ariessanea1** [comment]
I want to a app for people that can't talk face to face about their problems personally

**Comment by arnaudgiuliani** [comment]
I need a separated branch build for it. I will post here the RC releases that will be published

**Comment by sunildhiman90** [comment]
We are waiting for Wasm support. When new version will be released with Wasm support?

**Comment by nowiwr01w** [comment]
+1

**Comment by lekalina** [comment]
+1

**Comment by arnaudgiuliani** [comment]
> We are waiting for Wasm support. When new version will be released with Wasm support?

actively on it :)

**Comment by wagnod** [comment]
+1

**Comment by mahramane** [comment]
I am also waiting for Koin-wasm :)

**Comment by nowiwr01w** [comment]
+++++

**Comment by cryptrr** [comment]
+1. Having good dependency support for kotlin-wasm will revolutionize the web.

**Comment by nowiwr01w** [comment]
@arnaudgiuliani How is it going?

**Comment by sadiqueWiseboxs** [comment]
+1

**Comment by dimagor555** [comment]
+1

**Comment by andres04** [comment]
Any news?

**Comment by stephen2earth** [comment]
Any update?

**Comment by arnaudgiuliani** [comment]
`3.6.0-wasm-alpha1` is out 🎉

**Comment by c4software** [comment]
Hi @arnaudgiuliani could you update the 3.6.0 version to use the newer ComposePlugin 1.6.0-rc2 tag? 

The previous one is binary incompatible with rc1 and up and causing problems during the build of iOS target. 

See
 https://github.com/JetBrains/compose-multiplatform/issues/4277#issuecomment-1945922199

**Comment by arnaudgiuliani** [comment]
Ok, yes 👍

**Comment by hoc081098** [comment]
Compose 1.6.0 released.

**Comment by arnaudgiuliani** [comment]
good news. Let's see fot official release. But it will land in Koin 3.6 branch

**Comment by sureshmaidaragi1919** [comment]
Is koin started supporting Jetpack compose v1.6.0?, I tried accessing [3.6.0-alpha3](https://github.com/InsertKoinIO/koin/releases/tag/3.6.0-alpha3) seeing below issue


![Uploading Screenshot 2024-03-06 at 6.32.11 PM.png…]()

**Comment by joreilly** [comment]
The koin-compose version is 1.2.0-alpha3

**Comment by arnaudgiuliani** [comment]
will update 3.6 soon :)

**Comment by arnaudgiuliani** [comment]
3.6.0-Beta5 is out. 4.0.0 will continue with wasm
