### ISSUE TITLE
Suggestion: add named arguments to parametersOf

### ISSUE THREAD

**Issue by jullien** [InsertKoinIO/koin#1637]
Suggestion to add named arguments to method parametersOf to improve the legibility of the koin code and help developers to quick find and fix problem with declarations:

Before:
```
parametersOf(a, b)
```

After:
```
parametersOf(a = a, b = b)
```

**Comment by arnaudgiuliani** [comment]
that mean that you have to suggest a type somewhere, to help destructure them with arguments later. Currently all of this is generic

**Comment by arnaudgiuliani** [comment]
THe otehr way to do that is to pass a data class as parameter

**Comment by arnaudgiuliani** [comment]
let's reopen in you see something else :)
