### ISSUE TITLE
Setting up koin in iOS in multiplatform - cannot find file in scope

### ISSUE THREAD

**Issue by blonsky95** [InsertKoinIO/koin#1647]
I am following the [guide ](https://insert-koin.io/docs/quickstart/kmm/#injecting-dependencies-in-ios) to inject koin into iOS side, (It works on Android) .I have this error:

_/projectDirectory/iosApp/iosApp/iOSApp.swift:6:11: error: cannot find 'HelperKt' in scope
          HelperKt.doInitKoin()_

My set up is as follows:

In commonMain/shared I have **Helper.kt** with the initKoin function:
```
fun initKoin(appDeclaration: KoinAppDeclaration = {}) =
  startKoin {
    appDeclaration()
    modules(koinModules)
  }
```
And in iosApp (not shared) I have **iOSApp.swift**:
```
@main
struct iOSApp: App {
  init() {
          HelperKt.doInitKoin()
      }
	var body: some Scene {
		WindowGroup {
			ContentView()
		}
	}
}
```
In the official Koin guide their file is called HelperKt.kt, I have also tried this to no avail.
 
 Koin version: 3.4.3

**Comment by blonsky95** [comment]
Was missing "import shared" in the iOS App file. Nevermind.

**Comment by LaPockett** [comment]
The same thing happens to me, but I have the module's import

**Comment by codejockie** [comment]
> The same thing happens to me, but I have the module's import

```diff
- import shared
+ import Shared
```

Note the difference between them the first character is capitalised.
