### ISSUE TITLE
Instances seem not to be released

### ISSUE THREAD

**Issue by StephaneBg** [InsertKoinIO/koin#165]
**Description**
I need to release all instances to load again the modules. After the use of release(PATH), I get an error because I try to override a definition:
`Caused by: org.koin.error.BeanOverrideException: Try to override definition Single [class='com.sbgapps.sandwich.model.Bread', path:'com.sbgapps'] with Single [class='com.sbgapps.sandwich.model.Bread', path:'com.sbgapps'], but override is not allowed.`

**To Reproduce**
I wrote a sample to show the behavior: https://github.com/StephaneBg/sandwich
Crash occurs when a click is performed on the button.

**Expected behavior**
Release of all resources and ability to load them again.

**Koin version**
org.koin:koin-android:1.0.0-beta-3

**Comment by arnaudgiuliani** [comment]
Hi @StephaneBg ,

thanks, I'll check that 👍

**Comment by arnaudgiuliani** [comment]
First thing to note: if you use `release()`, it will release instances from the given module path not definitions. Then, if you try to reload modules definitions, you won't be able because definitions are already there.

**Comment by StephaneBg** [comment]
Hi, thanks for the speedy feedback.
Is there a way to release all definitions?

**Comment by StephaneBg** [comment]
Thanks, this method should be added to the documentation :)

**Comment by arnaudgiuliani** [comment]
You're right!

**Comment by StephaneBg** [comment]
Hello,
by the way it is not logical to name the method closeKoin. You can't close something you start, it should be stopKoin. Its is the counterpart of startKoin.
