### ISSUE TITLE
KoinApplication has not been started in iOS

### ISSUE THREAD

**Issue by darwineee** [InsertKoinIO/koin#1652]
**Describe the bug**
Hi everyone. Here is my issue:
- I follow this guide to setup Koin in both Android and ios: https://insert-koin.io/docs/quickstart/kmm/
- In iOS I tried 2 ways: init Koin application in init() block or UIApplicationDelegate:
<img width="539" alt="image" src="https://github.com/InsertKoinIO/koin/assets/70632828/d7a77160-807b-4896-a3d3-e62214339f5d">
and
<img width="769" alt="image" src="https://github.com/InsertKoinIO/koin/assets/70632828/325de3a1-ae59-4ced-8180-3c1a57d0e382">
- Android is running well, but iOS always crashes with the error: Uncaught Kotlin exception: kotlin.IllegalStateException: KoinApplication has not been started

**To Reproduce**
1. File Helper in iOS
![image](https://github.com/InsertKoinIO/koin/assets/70632828/ceec37ac-d3d1-4212-ab61-3a65d2683440)
2. Calling it in the init() block as the same as the instruction in the documentation.
3. App crash.

**Koin project used and used version (please complete the following information):**
- Tested in iOS simulator + iPhone 8 plus
- Koin latest version: core (3.4.3), android compose (3.4.6), compose multiplatform (1.0.4)
- Kotlin 1.9.10
Please help!

**Comment by arnaudgiuliani** [comment]
this is followed on slack, isn't it?

**Comment by darwineee** [comment]
Yes

**Comment by arnaudgiuliani** [comment]
let's reopen if needed

**Comment by softcleandev** [comment]
Same happens in my project in iOS.
koin-bom: 3.5.1
kotlin: 1.9.10

**Comment by arnaudgiuliani** [comment]
@softcleandev can you open a new issue?

**Comment by softcleandev** [comment]
There is no need anymore. I have fundamentally changed the classes so that the error no longer occurs.

**Comment by darwineee** [comment]
@softcleandev can you share your solution or the root cause? I still have this issue.

**Comment by softcleandev** [comment]
my init-methods and other class are like these dummy classes:

```
fun initKoin(
    appDeclaration: KoinAppDeclaration = {}
) {
    startKoin {
        appDeclaration()
        modules(
            appModule()
            dataModule()
            networkModule()
        )
    }
}

fun initKoinInIOS() = initKoin() {}

class A {
    var onFoo: (() -> Unit)? = null

    fun foo() {
        onFoo?.invoke()
    }

    fun getBar(): String {
        Data.user.get(1L)
        // -> At this point the "KoinApplication has not been started" error occurred in iOS even though I did called "doInitKoinInIOS()" method in my IOSApp.swift
    }
}

interface UserRepositoryInterface {
    fun put(user: User)
    fun get(id: Long): User?
    // ...
}


interface DataInterface {
    val user: UserRepositoryInterface
    // ...
}

object Data: DataInterface, KoinComponent {
    private val userRepository: UserRepositoryInterface by inject()

    overrider val user: UserRepositoryInterface = userRepository
}
```

I've splitted the A class into:

```
class AModel {
    var onFoo: (() -> Unit)? = null

    fun foo() {
        onFoo?.invoke()
    }
}

object AUtils {
    fun getBar(): String {
        Data.user.get(1L)
    }
}
```

And the error never occurred 🤷‍♂️

**Comment by anncode1** [comment]
I'm facing with the same error in iOS only.

The error occurs when I triy to get this ViewModel.
It launches the exception: 
`Uncaught Kotlin exception: kotlin.IllegalStateException: KoinApplication has not been started`
```
object KoinHelper : KoinComponent {

    fun getEmployeesViewModel() = getKoin().get<EmployeesViewModel>()
}

```
I'm trying to inject this viewmodel not sure how can I fix or split the method as you did @softcleandev could help me to clarify please?

**Comment by anncode1** [comment]
Hi @devzv sorry I’m not get what you saying.
Are you having same issue? Or this is how you fixed?

**Comment by devzv** [comment]
@anncode1 Hello!
Yes, I have the same issue.
Let me assume that you have a multi-module project?

**Comment by anncode1** [comment]
Right is a multi module project, but nobody answer :( 
@devzv what it means this:

> org.koin.mp.KoinPlatformTools@1f401150
> org.koin.mp.KoinPlatformTools@1a001110

**Comment by arnaudgiuliani** [comment]
@anncode1 are you using KMMViewModel?
