### ISSUE TITLE
Is it possible to inject repository to the service?

### ISSUE THREAD

**Issue by alishir** [InsertKoinIO/koin#166]
Hi,

I have a service class and I want to access the singletone repository. I'm going to use viewmodel with repository architecture and need to update view based on received data from service. Is it possible to inject for example repository to the service? something like this:

```kotlin
class MyService : Service() {
     private lateinit var repository: MsgRepository;

     fun onReceiveMsg(msg: Message) {
            repository.append(msg)
     }
}

**Comment by arnaudgiuliani** [comment]
Hello @alishir ,

you can use `by inject()` as you were in an Activity class.

**Comment by alishir** [comment]
Thanks for your reply, as I found if class constructor doesn't accept arguments I should use `by inject()`, am I right?

**Comment by arnaudgiuliani** [comment]
Exact!
