### ISSUE TITLE
Unable to inject new viewmodel instances in XML

### ISSUE THREAD

**Issue by snaum47** [InsertKoinIO/koin#1661]
**Is your feature request related to a problem? Please describe.**
https://github.com/InsertKoinIO/koin/issues/1477
https://github.com/InsertKoinIO/koin/pull/1592
Even though issues were fixed, we are still facing the same problem described here https://github.com/InsertKoinIO/koin/issues/1578. To be honest this seems also like a bug, or at least someone forgot to add the following option described below.

**Describe the solution you'd like**
As some are still using the XML views, there's no way to provide a key to the viewmodel, so the fixes to the bug mentioned above are not relevant. 
Why is it that the key can be passed when injecting a viewmodel in composables but not in fragments/activities?
I'd expect something like the following in order to have a different viewmodel instance every time:
`
private val exampleViewModel: ExampleViewModel by viewModel(key = UUID.randomUUID().toString())
`
Also I'd expect `getViewModel()` to also take a key as a parameter.

**Describe alternatives you've considered**
Possibility is to use the `resolveViewModel` but we need to opt in `KoinInternalApi` , which should be avoided of course.

**Target Koin project**
Internal project.

If there's any other solution/pointers/guidance to this, it would be great if you can share it

**Comment by arnaudgiuliani** [comment]
There is also the `viewModelForClass` function ,to let you handle advanced case of ViewModel

**Comment by snaum47** [comment]
That is handy and fixed our problem, thanks!
