### ISSUE TITLE
Compose Multiplatform Project upgrade from 3.4.3 to 3.50

### ISSUE THREAD

**Issue by JoaoPint0** [InsertKoinIO/koin#1664]
**Describe the bug**
I was trying to upgrade the current version of koin. in my project and now the app immediately crashes on launch. I can't find any documentation of what changed that could affect this.

**To Reproduce**
https://github.com/JoaoPint0/Koin-Compose-Multiplatfform

1 .Update koin library from 3.4.3 to 3.5.0
2 . Crash on app Launch

**Expected behavior**

**Koin module and version:**
3.4.3

**Comment by MitjaHenner** [comment]
I'm getting
`org.koin.compose.error.UnknownKoinContext: No Koin context has been provided`
with koin 3.5.0 and koin-compose 1.1.0.
koin 3.5.0 and koin-compose 1.0.4 works fine (tested on android and desktop).
