### ISSUE TITLE
Set or allow us to set GlobalContext for Ktor

### ISSUE THREAD

**Issue by chrisjenx** [InsertKoinIO/koin#1672]
**Describe the bug**
`GlobalContext` is now not set by the Ktor `KoinPlugin`

**To Reproduce**
Access `GlobalContext` after intalling koin plugin with ktor
Crash (ktorapplication not started)

**Expected behavior**
Either still set `GlobalContext`, or let us set it.

**Koin module and version:**
koin 3.5.x

**Snippet or Sample project to help reproduce**

`val equineService by GlobalContext.get().inject<ServiceObject>()`
will crash

**Comment by arnaudgiuliani** [comment]
you mean let Ktor plugin use any existing default Global context?

**Comment by chrisjenx** [comment]
By default it should probably set the `GlobalContext`, or at least give us a public method to set it if we choose. This was a pretty big breaking change for us and we had to revert back to 3.4.
BTW, this is something that should probably be noted under breaking changes in change logs

**Comment by arnaudgiuliani** [comment]
Yes, I understand. Certainly a too big change.

**Comment by arnaudgiuliani** [comment]
This issue has the same source of #1674. Let's continue there. I will publish rc build
