### ISSUE TITLE
createdAtStart does not work with loadKoinModules

### ISSUE THREAD

**Issue by derekpitts28** [InsertKoinIO/koin#1676]
**Describe the bug**
loadKoinModules createdAtStart property does not work/instantiate the correct classes when used.

**To Reproduce**

Run startKoin
Run this:
```
        loadKoinModules(
            listOf(
                module(createdAtStart = true) {
                    singleOf(::ClassA) { createdAtStart() }
                }
            )
        )
```
Put a print in the init function of ClassA.
See that it is not created.

**Expected behavior**
ClassA should be instantiated when createdAtStart is true.

**Koin module and version:**

    def koin_android_version = "3.4.0"
    implementation "io.insert-koin:koin-android:$koin_android_version"

**Comment by arnaudgiuliani** [comment]
did you checked in koin 3.5.0?

**Comment by mmadjer** [comment]
It seems like we are experiencing the same issue. Was there any outcome or progress on that issue?

**Comment by mmadjer** [comment]
Actually, just came across this function 'createEagerInstances' which if called after the loadKoinModules seems to resolve the issue.

**Comment by derekpitts28** [comment]
Thanks @mmadjer I will check that out and see if it resolves my issue!
