### ISSUE TITLE
"No Compose Koin context setup" warning on startup after koin version upgrade

### ISSUE THREAD

**Issue by StylianosGakis** [InsertKoinIO/koin#1677]
**Describe the bug**
Not necessarily a bug, but after updating Koin, I've started receiving the warning "[Warning] - No Compose Koin context setup, taking default. Use KoinContext(), KoinAndroidContext() or KoinApplication() function to setup or create Koin context and avoid such message." every time, which comes from here https://github.com/InsertKoinIO/koin/blob/06de70adae578b8734a8c3b77b7314f3c890f2a1/compose/koin-compose/src/commonMain/kotlin/org/koin/compose/KoinApplication.kt#L93-L95

Are there any docs regarding why we would need to make this change? We're not using any sort of koin context isolation in our composables, and the solution we've had before had worked well, since we only have the global koin context in our app.

So I am not sure if this warning applies for us, and if it does, what would be the right steps moving forward to make this warning go away? Is there something in the docs where I could be pointed to in order to understand what is the best way forward?

**Koin module and version:**
 [e.g]: `koin-bom:3.5.1`

**Comment by bsinou** [comment]
I have the exact same problem since upgrading to latest koin and would greatly appreciate any hint on how to tackle this.

**Comment by BapNesS** [comment]
I got the same issue. I fixed it using `KoinContext()` over my theme.

[Koin documentation](https://insert-koin.io/docs/reference/koin-compose/compose/#starting-koin-with-android-jetpack-compose---koinapplication-or-koinandroidcontext-since-110) says :
> Most of the time, startKoin function is used to start Koin in your application. This is done before running any Composable function. You need to setup Compose with your current Koin instance. Use KoinContext() to do so:

```kotlin
@Composable
fun App() {
    // Set current Koin instance to Compose context
    KoinContext() {

        MyScreen()
    }
}
```

**Comment by arnaudgiuliani** [comment]
Yes, the problem here is to let Compose catch the right Koin application context. The source code warning code is here to highlight the fact that you are running implicitly with the current Koin context.

Something I was looking is either take default context, but no warning.

**Comment by StylianosGakis** [comment]
Yes, if the new behavior is just that the default context is used, which is exactly what was happening before too, which would mean that practically for apps which do not want to do any sort of scoped koin providers the behavior is the exact same, then the warning is not needed. Or at least there should be a way to acknowledge this situation and continue on without having this warning forever.

**Comment by arnaudgiuliani** [comment]
>Or at least there should be a way to acknowledge this situation and continue on without having this warning forever.
yes agree, thanks

**Comment by arnaudgiuliani** [comment]
Pushing it back to log. Let's see if I can propose at API side 👍
