### ISSUE TITLE
Module.singleOf(crossinline constructor: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) Need MORE! 

### ISSUE THREAD

**Issue by Morons** [InsertKoinIO/koin#1678]
I have 19 repositories currently to inject
I NEED MORE pretty please 
OR alternative way 

I have written a single procedure to visit all my Data table by table and do common cleanup/archiving etc.  the issue is I need to inject mote than the 10 allowed!

Is there an Alternative way?

**Comment by Morons** [comment]
Any solutions?

**Comment by bigman212** [comment]
@Morons 
You can refactor and extract some of your dependencies to a class and inject that class as described here https://refactoring.guru/smells/long-parameter-list. 
You write your extension on the `Scope` class.

**Comment by arnaudgiuliani** [comment]
In Kotlin language, the arbitrary number of arguments for a function is 22. This is the maximum number of dependencies you can have. I encourage you to refactor your dependencies in your case

**Comment by mealinux** [comment]
**### temporarily**

example:
```
scope(named("chat_screen")) {
    viewModel{
        ChatViewModel(
            get(), get(), get(), get(), get(), get(), get(), get(), get(), get(), get(), get(),
            get(), get(), get(), get(), get(), get(), get(), get()
        )
    }
}
```
