### ISSUE TITLE
Inject context as parameter and unit testing

### ISSUE THREAD

**Issue by pavelbay** [InsertKoinIO/koin#168]
Hi! I'm using `1.0.0-beta-3` and have the following question:
Is it not recommended to use koin for injecting some context depending stuff? For example, I have a class, which is depending on context and then I hava a lambda inside of a module like this:
```
(context: Context) ->
            ClassImpl(context, get()) as AbtractStuff<*>
```
so the first question is: is something like this ok?
the second: in the case of yes, how can I then proceed with the unit testing? If I'm running `check` or `dryRun` I'm getting `Parameter element #0 is empty`. What would you recommend? Thank you in advance.

**Comment by pavelbay** [comment]
I'm updating my question: will instrumented tests be supported? Now if'm using `androidContext` the tests fail, sure because unit tests does not know anything about android components

**Comment by arnaudgiuliani** [comment]
Hello,
if you want to use `check` or `dryRun`, try to avoid dependency to Android context. It will be difficult to unit test against it.
You can use Koin as well in your instrumented tests. Be sure to use `koin-test` project.

**Comment by arnaudgiuliani** [comment]
Closing question issue - Please reopen it or post your next question on stackoverflow: https://stackoverflow.com/questions/tagged/koin
