### ISSUE TITLE
Unneccessary warning when using scopes

### ISSUE THREAD

**Issue by tzugen** [InsertKoinIO/koin#1680]
When using ScopeFragment I get frequent log entries of the severity "warn":
` | Scope 'q:'org.example.exampleFragment'' not defined. Creating it ...`

If i am expected to create those manually somehow, the message should let us know.
Otherwise I don't understand why its marked as a warning.

**Comment by arnaudgiuliani** [comment]
yes, can get rid of this warning 👍
