### ISSUE TITLE
@Singleton defined as a method inside @Module does not bind to its supertypes

### ISSUE THREAD

**Issue by NorbertSandor** [InsertKoinIO/koin#1681]
**Koin module and version:**

core: 3.5.0
annotations: 1.3.0

**Snippet or Sample project to help reproduce**

```kotlin
interface Service1

interface Service2: Service1

@Module
@ComponentScan
class ServiceModule {

    @Singleton // (binds = [Service1::class, Service2::class])
    fun service(): Service2 = ...
}

...

get<Service1>() // Fails with 'NoBeanDefFoundException' if the annotation argument 'binds' is not specified explicitly (see above)

```

**Comment by arnaudgiuliani** [comment]
To use automatic binding, you need to tag a class. Here you use an inner module expression to declare `service()`. It binds only the type from the resulting expression.

Also please add this issue in https://github.com/InsertKoinIO/koin-annotations/issues
