### ISSUE TITLE
 No instance for key AttributeKey: KOIN with Koin 3.5 in integration tests

### ISSUE THREAD

**Issue by andrashatvani** [InsertKoinIO/koin#1683]
**Describe the bug**
Merely upgraded from 3.4.3 to 3.5 and got this exception:
```
Caused by: java.lang.IllegalStateException: No instance for key AttributeKey: KOIN
	at io.ktor.util.Attributes$DefaultImpls.get(Attributes.kt:62)
	at io.ktor.util.AttributesJvmBase.get(AttributesJvm.kt:15)
	at org.koin.ktor.ext.ApplicationExtKt.getKoin(ApplicationExt.kt:34)
	at at.wrwks.bef.monitoring.plugins.HTTPKt.configureHTTP(HTTP.kt:44)
	at at.wrwks.bef.monitoring.domain.SystemLoadHandlerIntegrationTest$test$1$2.invoke(SystemLoadHandlerIntegrationTest.kt:71)
```

After downgrading to 3.4.3 the tests are successful.

**To Reproduce**
Upgrade from 3.4.3 to 3.5. Tried both, explicit version specification and the BOM-way.

**Expected behavior**
The integration tests succeed as usual

**Koin module and version:**
 [e.g]: `koin-core:3.5.0`

**Comment by andrzej-talarek** [comment]
Have exactly same error after upgrade. Application starts, server works fine (responds to requests), but tests fail.

**Comment by atollk** [comment]
Upgrading io.insert-koin:koin-ktor to 3.5.1 fixed this for me.

**Comment by arnaudgiuliani** [comment]
yes upgrade to koin-3.5.1

**Comment by andrashatvani** [comment]
@arnaudgiuliani No, it doesn't solve it for me:
`
    <properties>
        <koin.version>3.5.1</koin.version>
        <koin-test.version>3.5.0</koin-test.version>
    </<properties>
    <dependencies>
        <dependency>
            <groupId>io.insert-koin</groupId>
            <artifactId>koin-ktor</artifactId>
            <version>${koin.version}</version>
        </dependency>

        <dependency>
            <groupId>io.insert-koin</groupId>
            <artifactId>koin-test</artifactId>
            <version>${koin-test.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.insert-koin</groupId>
            <artifactId>koin-test-junit5</artifactId>
            <version>${koin-test.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
`
I still get the same error message:
`Exception in thread "main" java.lang.IllegalStateException: KoinApplication has not been started
	at org.koin.core.context.GlobalContext.get(GlobalContext.kt:36)`

**Comment by andrashatvani** [comment]
@arnaudgiuliani It works with the latest rc, even with the bom:
```xml
            <dependency>
                <groupId>io.insert-koin</groupId>
                <artifactId>koin-bom</artifactId>
                <version>3.5.2-RC1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

**Comment by arnaudgiuliani** [comment]
Great 💪
