### ISSUE TITLE
What does `(*) Created` means in logcat output?

### ISSUE THREAD

**Issue by alishir** [InsertKoinIO/koin#169]
Hi,

I used `val mode ny viewModel<TestViewModel>` in my activity, each time I switch back to my activity from other activity or applications I got `(*) Created` in logcat, does it create new instance on model when I resume to my activity? Here is the koin module and viewmodel class:

```kotlin
val hypoModule = applicationContext {
    viewModel { TestViewModel(get()) }
    bean { TestRepositoryImp() as TestRepository }
}
```

```kotlin
class TestViewModel(val repository: TestRepository): ViewModel() {
    fun getTest(): LiveData<Int> {
        return repository.testValue()
    }
}
```

**Comment by arnaudgiuliani** [comment]
This effectively means that an instance is created

**Comment by alishir** [comment]
Thanks.
