### ISSUE TITLE
Upgrade from 3.4.3 to 3.5.0 breaks tests in KoinTest

### ISSUE THREAD

**Issue by JerryPreissler** [InsertKoinIO/koin#1690]
**Describe the bug**
Tests that succeed under koin 3.4.3 stop to work after upgrading to 3.5.0 

**To Reproduce**
1. Check out https://gitlab.com/JerryPreissler/aktenordner
2. Run 'gradle clean test' -> tests should succeed
3. In gradle.properties, change 'koin_ktor_version=3.4.3' to 'koin_ktor_version=3.5.0'
4. Rerun 'gradle clean test' -> tests in org.codeshards.aktenordner.adapter.incoming.rest.DokumentRestControllerTest fail

**Expected behavior**
I expect the tests to succeed after upgrading to koin 3.5.0

**Koin module and version:**
Working: 
  koin_ktor_version=3.4.3
Failing:
  koin_ktor_version=3.5.0
 
   implementation("io.insert-koin:koin-ktor:$koin_ktor_version") // Koin for Ktor
    implementation("io.insert-koin:koin-logger-slf4j:$koin_ktor_version")
    testImplementation("io.insert-koin:koin-test-junit5:$koin_ktor_version")

**Snippet or Sample project to help reproduce**
https://gitlab.com/JerryPreissler/aktenordner

**Comment by JerryPreissler** [comment]
Here are the stacktraces for the failing tests:
[stacktrace.txt](https://github.com/InsertKoinIO/koin/files/13209787/stacktrace.txt)
You can see the source at https://gitlab.com/JerryPreissler/aktenordner/-/blob/main/src/test/kotlin/org/codeshards/aktenordner/adapter/incoming/rest/DokumentRestControllerTest.kt

**Comment by arnaudgiuliani** [comment]
can you try with ktor 3.5.1?

**Comment by JerryPreissler** [comment]
(I guess you mean koin_ktor_version, right?)
I can't just bump koin_ktor_version to 3.5.1 since I'm using
   ` testImplementation("io.insert-koin:koin-test-junit5:$koin_ktor_version")`
which is only available up to 3.5.0.
If I keep `io.insert-koin:koin-test-junit5` at 3.5.0 and bump the other Koin dependencies to 3.5.1 the tests run successfully.

**Comment by arnaudgiuliani** [comment]
You could, 3.5.1 is only for ktor this time

**Comment by JerryPreissler** [comment]
Ok, then I have a working solutions. Thanks a lot, I'll close the issue.

**Comment by JerryPreissler** [comment]
And just for the record: using 3.5.2-RC1 everything works fine for me.
@arnaudgiuliani  - thanks a lot for fixing the issues - and your work in general.

**Comment by arnaudgiuliani** [comment]
that's great, thanks
