### ISSUE TITLE
Koin Beta & proguard issue

### ISSUE THREAD

**Issue by mgrzechocinski** [InsertKoinIO/koin#170]
Hi,

starting with Koin 1.0.0-beta3 I stared having issues with proguarded (obfuscated) app. 
According to #26, I have no special rules for Koin and it was working pretty well until I've upgraded to 1.0.0-beta3 from 0.9.3.

Now, when trying to inject view model into an activity, Koin throws:
```
Caused by: myapp.cur: No compatible definition found for type 'com.myapp.common.viewmodel.PanelActivityViewModel'. Check your module definition
        at myapp.cua.a(SourceFile:135)
        at myapp.ctv.a(SourceFile:90)
        at myapp.ctx.a(SourceFile:64)     
```
`PanelActivityViewModel` is a class in a library module which has it's own Koin module declared as:
```
val commonModule = module {
//...
  viewModel { PanelActivityViewModel() }
//...
}
```
I start Koin in a custom Application class onCreate():
```
startKoin(this, listOf(
  //...
  commonModule,
  //...
))
```
For non obfuscated APK, everything works fine. According to `mapping.txt`, `PanelActivityViewModel` class name was not changed and it actually exists in the APK. When I build my APK with proguard but without obfuscation (`-dontobfuscate`), it also works fine.

This is how part of `KoinModuleKt.java` lookg like for for non obfuscated build:
```
BeanDefinition beanDefinition = new BeanDefinition(BuildConfig.FLAVOR, Reflection.getOrCreateKotlinClass(PanelActivityViewModel.class), null, null, false, false, false, AnonymousClass13.INSTANCE, 12, null);
moduleDefinition.getDefinitions().add(beanDefinition);
beanDefinition.bind(Reflection.getOrCreateKotlinClass(ViewModel.class));
```
and the same for an obufscated build:
```
cui myapp_cui = new cui(BuildConfig.FLAVOR, cne.a(PanelActivityViewModel.class), null, null, false, false, false, AnonymousClass5.a, 12, null);
myapp_cuh.a().add(myapp_cui);
myapp_cui.a(cne.a(y.class));
```
Has anything change in terms of Proguard support between 0.9.3 and 1.0.0 in Koin? Thanks in advance for any help.

**Comment by mgrzechocinski** [comment]
After some investigation in seems that something has changed in final my proguard rules used by Proguard/D8. Seems like it has nothing in common with Koin. Adding [this](https://gist.github.com/brownsoo/9b11a823360c9cf184263df3e669375c) rules fixes the problem. I have to find out why it worked before.

**Comment by SharpMobileCode** [comment]
@mgrzechocinski, I had the same issue as you.  Went from 0.9.3 to Beta 3.  Proguard was working before, but after the upgrade, I would get 
>No compatible definition found for type 'com.myapp.viewmodels.myViewModel'. Check your module definition
The only thing that changed was updating to the latest Koin beta.  Adding the rules you linked fixed the issue for me as well.  Not definitive proof I guess, but something changed between versions.

**Comment by tukak** [comment]
Hi,
same here, but with Koin I Jetified my project as well.

Adding this rules for proguard helped.

-keepclassmembers class androidx.lifecycle.** { *; }
-keep class androidx.lifecycle.** { *; }
-dontwarn androidx.lifecycle.**

**Comment by erickok** [comment]
Yes, we also got an issue with the ViewModel being stripped. Must be because there is no longer a hard reference to them. We also added an explicit keep rule (but allowed optimizations!).

**Comment by erickok** [comment]
Forgot to say, the rule I am using now us
`-keep,allowshrinking,allowoptimization class android.arch.lifecycle.*`
Not sure yet why Koin needs the name to be kept.
