### ISSUE TITLE
ViewModel injection issue when using Compose Preview

### ISSUE THREAD

**Issue by SirFilbido** [InsertKoinIO/koin#1705]
**Describe the bug**
I'm having problems using Compose's Preview on screens that require a ViewModel and are injected via Koin as the [documentation](https://insert-koin.io/docs/reference/koin-compose/compose) recommends.

`java.lang.IllegalStateException: KoinApplication has not been started
`

Is there already a solution that doesn't use external libraries?

**Expected behavior**
What is expected is the preview loading the screen elements as expected

**Koin module and version:**
`koin-androidx-compose:3.5.0`

**Snippet or Sample project to help reproduce**

```
@Composable
fun MyScreen(navController: NavController) {

    val viewModel = koinViewModel<MyViewModel>()

```

![image](https://github.com/InsertKoinIO/koin/assets/25982091/e9043777-76d0-4da5-a290-a56cf3d4ebef)
![image](https://github.com/InsertKoinIO/koin/assets/25982091/967f221f-e9ed-4b1a-a8e1-0bed9db0d448)
![image](https://github.com/InsertKoinIO/koin/assets/25982091/0d084fd3-81e0-4785-bb73-3e4b22e1aae7)

**Comment by arnaudgiuliani** [comment]
You need to wrap your preview with `KoinApplicaion` and run a small instance of Koin, else it won't find your ViewModel

**Comment by SirFilbido** [comment]
Thank you for your response @arnaudgiuliani.

I adjusted the preview of my screen, injecting the main module that groups the other modules for injection

That was the result:
```
@Preview
@Composable
fun MyScreenPreview() {
     KoinApplication(application = {
        modules(appModule()) //Function that groups all DI modules
    }) {
        MyScreen(navController = rememberNavController())
    )
}
```

I took advantage and abstracted this configuration to another function. I believe it will make it easier to use and I leave it as a tip.
```
@Preview
@Composable
fun MyScreenPreview() {
    ScreenPreview{
        MyScreen(navController = rememberNavController())
    }
}
```
```
@Composable
fun ScreenPreview(
    screen: @Composable () -> Unit
) {
    KoinApplication(application = {
        modules(appModule())
    }) { screen() }
}
```

I will take advantage and link the other issues so that other people in the future can reach this solution
