### ISSUE TITLE
Koin Beta: use the Deprecated annotation

### ISSUE THREAD

**Issue by dpreussler** [InsertKoinIO/koin#171]
Koin 1.0 brings breaking changes. 
Lot of developers already use Koin, let's make it easy for them.
Android Studio is confused with this kind of changes, I gave up after 20min as errors show on commandline but AS still shows the old imports and pretends not to see the new ones and have a small project only.

So suggestion:
Can you keep (at least while in beta) the old names (bean, applicationContext) and add the Deprecated annotation with details so that Android Studio can do the changes via refactoring options itself.

**Comment by arnaudgiuliani** [comment]
Hi @dpreussler,

old `applicationContext`, `context` & `bean` are kept, but perhaps with a new signature. Can you confirm that?
(I'll check on my side to help for the DSL migration 0.9 -> 1.0)

**Comment by arnaudgiuliani** [comment]
Things will be ok to help refactoring in `1.0.0-beta-6` 👍 

Params & replacewith/deprecated annotation should be ok now.
