### ISSUE TITLE
`checkModules()` throws NoBeanDefFoundException when module contains a declaration with parameters

### ISSUE THREAD

**Issue by okycelt** [InsertKoinIO/koin#1710]
**Describe the bug**
I have three classes, two of which are declared in a module. In test, I provide the third class mock using `withInstance<Outsider>()`. But for some reason, `checkModules()` throws `NoBeanDefFoundException: No definition found for type 'com.test.di.Outsider'. Check your Modules configuration and add missing type and/or qualifier!`. It seems to be related to the factory for `First` having a parameter. If I remove that parameter, `checkModules()` doesn't find any problems. Am I doing something wrong or is this a bug?

**To Reproduce**
Just run the attached test.

**Expected behavior**
`checkModules()` shouldn't find any problems.

**Koin module and version:**
`koin-android`, `koin-test-junit4` (`koin-bom:3.5.0`)

**Snippet or Sample project to help reproduce**
```kotlin
data class Outsider(val version: String)
data class First(val outsider: Outsider, val booleanParam: Boolean)
data class Second(val first: First)
```

```kotlin
val testModule = module {
  factory { (booleanParam: Boolean) ->
    First(
      outsider = get(),
      booleanParam = booleanParam
    )
  }

  factory {
    Second(
      first = get { parametersOf(true) }
    )
  }
}
```

```kotlin
class TestModuleTests {
  @get:Rule
  val mockProvider = MockProviderRule.create { clazz ->
    mockkClass(clazz, relaxed = true)
  }

  @Test
  fun checkModules() {
    koinApplication {
      modules(testModule)
      checkModules {
        withInstance<Outsider>()
        withParameters<First> { parametersOf(false) }
      }
    }
  }
}
```

**Comment by okycelt** [comment]
It's also reproducible in `core/koin-test-junit4/src/test/kotlin/org/koin/test/CheckModulesTest.kt`. If you add a boolean param to `Simple.ComponentB` the following test fails.

```kotlin
class Simple {
    class ComponentB(val a: ComponentA, val b: Boolean)
}

@Test
fun `check module - dependency and param in one class`() {
    val modules = module {
        factory { p -> Simple.ComponentB(get(), p.get()) }
    }

    koinApplication {
        modules(modules)
        checkModules {
            withInstance<Simple.ComponentA>()
            withParameter<Simple.ComponentB> { true }
        }
    }
}
```

**Comment by okycelt** [comment]
@arnaudgiuliani, would you mind taking a look?

**Comment by arnaudgiuliani** [comment]
yep 👍

**Comment by arnaudgiuliani** [comment]
It's a current limitation of `checkModules`. You can't mix `withInstance` and `withParameter` for now. Looking for it.

**Comment by arnaudgiuliani** [comment]
`checkModules` is too complex to cover easily the configuration check. This will be deprecated in 3.6

**Comment by arnaudgiuliani** [comment]
Let open a new message thread if needed
