### ISSUE TITLE
KoinComponent with KoinApplication composable not working

### ISSUE THREAD

**Issue by farhazulmullick-pw** [InsertKoinIO/koin#1719]
If i call this `KoinApplicationComposable` from MainActivity then if i try to inject any dependency  using `by inject()` in any class with `KoinComponent` interface implemented. I get a runtime exception `java.lang.IllegalStateException: KoinApplication has not been started`. 

Further this runtime exception is not thrown if startKoin {} is called in Application class.

```

@Composable
fun KoinApplicationComposable(
    application: Application,
    appContent: @Composable () -> Unit
) {
   org.koin.compose.KoinApplication(application = {
        androidContext(application.applicationContext)
        modules(getKoinModules())
    }){
        appContent()
        Test.testInstace    // throws java.lang.IllegalStateException KoinApplication has not been started.
    }
}

fun getKoinModules() = module {
      single<SomeClass> { ... }
}

public object Test: KoinComponent {
    val instance by inject<SomeClass>()

    fun testInstance() = instance

}
```

**Comment by shohrab-swl** [comment]
Same problem, can anyone fix it?

**Comment by arnaudgiuliani** [comment]
your Koin instance is not yet start while you use `Test`, which is extending `KoinComponent`. Either you delay it elsewhere, after the KoinApplication block. Either you can start Koin with `startKoin` before using `KoinApplication`
