### ISSUE TITLE
shared in activitys

### ISSUE THREAD

**Issue by BarderBet** [InsertKoinIO/koin#1727]
**Is your feature request related to a problem? Please describe.**
How to share ViewModel in more than one activitys, and maybe used the ViewModelStore of Application

**Comment by arnaudgiuliani** [comment]
Did you check https://developer.android.com/topic/libraries/architecture/viewmodel/viewmodel-apis#vm-api-navgraph ?
Koin can help with nav graph ViewModel if needed
