### ISSUE TITLE
koin-logger-slf4j 1.0.0-beta.3 is not available in jcenter

### ISSUE THREAD

**Issue by panjiesw** [InsertKoinIO/koin#173]
**Describe the bug**
Can't resolve `org.koin:koin-logger-slf4j:1.0.0-beta.3` with only gradle `jcenter()` repositories configuration. Confirmed that there is no such version here https://jcenter.bintray.com/org/koin/koin-logger-slf4j/ 

**To Reproduce**
1. Follow guide on [gradle setup](https://beta.insert-koin.io/docs/1.0/documentation/reference/index.html#_gradle_setup)
2. Add `implementation("org.koin:koin-logger-slf4j:1.0.0-beta.3")` to gradle  `dependencies`
3. Sync gradle
4. Error can't resolve the package

**Expected behavior**
Package resolved

**Koin project used and used version**
`koin-logger-slf4j version 1.0.0-beta.3`

**Additional context**
work around:

```kotlin
repositories {
  ...
  // add this
  maven("https://dl.bintray.com/ekito/koin")
  ...
}
```

**Comment by arnaudgiuliani** [comment]
Should be available: https://bintray.com/ekito/koin/koin-logger-slf4j/1.0.0-beta-4#files/org%2Fkoin%2Fkoin-logger-slf4j%2F1.0.0-beta-4

**Comment by jcornaz** [comment]
Apparently only `1.0.0-alpha-20` is available on `jcenter` for `koin-logger-slf4j`: https://jcenter.bintray.com/org/koin/koin-logger-slf4j/

Could it be the same kind of issue: https://stackoverflow.com/questions/44371758/bintray-does-not-link-new-artifact-to-jcenter?

**Comment by arnaudgiuliani** [comment]
argh, yes :/

**Comment by jcornaz** [comment]
Thanks @arnaudgiuliani. It seems solved in `1.0.0-beta-6`.

gradle correctly downloaded the artifacts without the need of `maven { url "https://dl.bintray.com/ekito/koin" }`

```
Download https://jcenter.bintray.com/org/koin/koin-core/1.0.0-beta-6/koin-core-1.0.0-beta-6.pom
Download https://jcenter.bintray.com/org/koin/koin-logger-slf4j/1.0.0-beta-6/koin-logger-slf4j-1.0.0-beta-6.pom
Download https://jcenter.bintray.com/org/koin/koin-logger-slf4j/1.0.0-beta-6/koin-logger-slf4j-1.0.0-beta-6.jar
Download https://jcenter.bintray.com/org/koin/koin-core/1.0.0-beta-6/koin-core-1.0.0-beta-6.jar

BUILD SUCCESSFUL
```

**Comment by arnaudgiuliani** [comment]
Yes :)

**Comment by panjiesw** [comment]
Thanks for resolving this guys! :+1:
