### ISSUE TITLE
Koin Annotation with KMP fails to generate the default Module without explicit package declaration

### ISSUE THREAD

**Issue by Ynnck123** [InsertKoinIO/koin#1734]
**Describe the bug**
As the title Koin Annotation implies, in a Kotlin Multiplatform project Koin Annotation fails to generate the default Module for classes without package declaration in the Kotlin folder.

**To Reproduce**
1. Setup Koin Annotations in a basic KMP project with Android and iOS target _(probably doesn't matter)_
2. Have the following package structure in the `commonMain` module (so you place your files simply in `../kotlin` like for example in the [Compose Multiplatform for iOS and Android template project](https://github.com/JetBrains/compose-multiplatform-ios-android-template):
<img width="511" alt="image" src="https://github.com/InsertKoinIO/koin/assets/38558339/d3bbf7a1-af7b-459a-aeba-0127f13518b0">

3. Create the `SampleClass` you can see above in the `kotlin` package:

  ```
  import org.koin.core.annotation.Single
  
  @Single
  class SampleClass
  ```

4. Execute the Koin KSP compiler process / build the project

**Expected behavior**
The `Default.kt` should properly contain the `SampleClass` definition

**Actual behavior**
The build fails because the generated `Default.kt` file looks like the following:
```
package org.koin.ksp.generated

import org.koin.core.KoinApplication
import org.koin.core.module.Module
import org.koin.dsl.*

public fun KoinApplication.defaultModule(): KoinApplication = modules(defaultModule)
public val defaultModule : Module = module {
	single() { .SampleClass() } 
}
```

As you can see it adds a `.` in front of the `SampleClass` which causes a syntax error.

**Observation**
When I add an additional folder into the `../koin` folder like `../koin/example/` in which I move the `SampleClass`, the `Default.kt` file gets properly generated.

**Koin module and version:**
- koin-bom:3.5.1 with koin-core and koin-compose
- koin-annotations:1.3.0

**Comment by arnaudgiuliani** [comment]
Can you reopen it on https://github.com/InsertKoinIO/koin-annotations please? 🙏

**Comment by Ynnck123** [comment]
Sorry for the mistake, I reopened it here: https://github.com/InsertKoinIO/koin-annotations/issues/111
