### ISSUE TITLE
Add bean/module destructor for Annotation-defined bean/module

### ISSUE THREAD

**Issue by vdshb** [InsertKoinIO/koin#1736]
**Is your feature request related to a problem? Please describe.**

My bean is defined with annotation:

```kotlin
@Module
class AppModule {
  @Single(createdAtStart = true)
  fun sqlDriver() : SqlDriver {
    //...
  }
}
```

I want to define bean/module close strategy to it. 
Effecitvely I want to run `sqlDriver.close()` during `KoinApplication::close` call.

**Describe the solution you'd like**
The design might be something like this:

```kotlin
@Module
class AppModule {
  @Single(createdAtStart = true)
  fun sqlDriver() : SqlDriver {
    //...
  }
  @OnClose
  fun closeModule(sqlDriver: SqlDriver) {
    sqlDriver.close()
  }
}
```

**Describe alternatives you've considered**
If bean is `AutoClosable` the bonus design might be something like this:

```kotlin
@OnClose(closeAutoClosable = true)
@Single(createdAtStart = true)
fun sqlDriver() : SqlDriver {
  //...
}
```

But conflicts resolution strategy with  `@OnClose`  and close order of dependant beans must be designed additionally.

**Target Koin project**
Koin-Annotations

**Comment by arnaudgiuliani** [comment]
Hello, can you reopen it on https://github.com/InsertKoinIO/koin-annotations repo please? 🙏

**Comment by vdshb** [comment]
Done: https://github.com/InsertKoinIO/koin-annotations/issues/112

Feel free to close this one if there is no need for it.

**Comment by arnaudgiuliani** [comment]
thx
