### ISSUE TITLE
Koin documentation has an erratum

### ISSUE THREAD

**Issue by soldier4443** [InsertKoinIO/koin#174]
**Describe the bug**
So the documentation has a minor typo issue.
"There is no import features: all definitions are lazy and executed at runtime. This means that you can compose definitions with **mdultiple** modules. "

**To Reproduce**
See [here](https://beta.insert-koin.io/docs/1.0/quick-references/koin-dsl/#multiple-modules)

**Expected behavior**
I think that should be "multiple".

**Comment by arnaudgiuliani** [comment]
Hello,
can you point the page or file of the documentation please?

**Comment by arnaudgiuliani** [comment]
Thanks. Fixed.
