### ISSUE TITLE
missing watchosDeviceArm64 target

### ISSUE THREAD

**Issue by suau** [InsertKoinIO/koin#1747]
**Describe the bug**
Since XCode14 the `ARCHS_STANDARD` for watchOS includes arm64. KMP already has added the target watchosDeviceArm64, but koin hasn't included it yet

**To Reproduce**
1. Create a KMP project
2. Add Koin
3. Add a watchOS app to the ios app
4. Add watchosArm64(), watchosDeviceArm64(), watchosSimulatorArm64() to the shared build.gradle.kts
5. Build for release
6. Release build will fail with default settings

**Expected behavior**
watchos should build with default settings

**Koin module and version:**
`koin-core:3.5.3`

**Comment by arnaudgiuliani** [comment]
Thanks, let's continue with the PR 👍
