### ISSUE TITLE
[koin-core-coroutines] Pass a custom Dispatcher to the Koin coroutines engine

### ISSUE THREAD

**Issue by cpaleop** [InsertKoinIO/koin#1754]
**Is your feature request related to a problem? Please describe.**
The current implementations of `KoinPlatformCoroutinesTools` return a hardcoded value of `CoroutineDispatcher` with no option to either modify this value or bypass it and use a custom one.

**Describe the solution you'd like**
To be able to define the `CoroutineDispatcher` Koin will use when using the Koin coroutines engine.
The API for this could be something like:
```kotlin
startKoin {
    dispatcher(Dispatchers.Default)
}

// or

startKoin {
    lazyModules(dispatcher = Dispatchers.Default, listOfLazyModules)
}
```
If not defined, then the dispatcher from `KoinPlatformCoroutinesTools` implementations can be used as default.

**Describe alternatives you've considered**
None.

**Target Koin project**
`core`

**Comment by arnaudgiuliani** [comment]
Yes, good catch 👍

**Comment by arnaudgiuliani** [comment]
Let's see for 3.5.4-rc-1 build. Will be soon available
