### ISSUE TITLE
Android setup docs link's broken

### ISSUE THREAD

**Issue by imtheaman** [InsertKoinIO/koin#1759]
**Describe the bug**

**To Reproduce**
1. Go to https://insert-koin.io/docs/setup/v3.2#android
2. Click on 'Android setup link'
3. See error

**Expected behavior**

**Koin module and version:**
 [e.g]: `koin-core:3.4.3`

**Snippet or Sample project to help reproduce**
Add a snippet or even a small sample project to hel reproduce your case.

**Comment by arnaudgiuliani** [comment]
It's has been changed to more general versioning: https://insert-koin.io/docs/setup/koin
