### ISSUE TITLE
"scopedWith" for nested activities of the same class name (QUESTION)

### ISSUE THREAD

**Issue by genaku** [InsertKoinIO/koin#176]
For example I have activity class FolderActivity. It can open next FolderActivity with proper parameters (for example id or path or something else of this nested folder) and it can open next FolderActivity and so on. I want to inject into FolderActivity proper object of ScopePresenter class (who knows what folder it represents) by passing there that parameters. How to declare and use ScopePresenter class so that Koin would clear presenter object of finished FolderActivity but would keep presenters of parent FolderActivities?

**Comment by arnaudgiuliani** [comment]
Hello,

did you try to declare your presenter with `factory`? It should ask a new presenter each time you need it, and drop it when Activity is leaving.

**Comment by arnaudgiuliani** [comment]
Closing question issue - Please reopen it or post your next question on stackoverflow: https://stackoverflow.com/questions/tagged/koin
