### ISSUE TITLE
Suggestion: consistent api method naming

### ISSUE THREAD

**Issue by dant3** [InsertKoinIO/koin#177]
**Is your feature request related to a problem? Please describe.**
To start a koin context you issue `startKoin()` method call. But to stop it you call `closeKoin()`. 
I expect it either to be `start`/`stop` or `open`/`close`, but not `start`/`close`. It's not clear what you're closing since you haven't opened anything - hence api is not consistent.

**Describe the solution you'd like**
I would like to have a clear method names: either `start`/`stop` or `open`/`close`. The former makes more sense. From my POV an ideal solution however would be for `start` method to return started context you can use, and then just drop it then you're done.

**Target Koin project**
core

P.S.:
I also not sure why you really need this `Koin` suffix. It should be clear enough what you work with koin already, so this suffix looks like unexpected PR in the actual code. Class/package names should be quite enough.

**Comment by erickok** [comment]
On the suffix: not really, because you typically (statically) import the function so there is no context.

**Comment by arnaudgiuliani** [comment]
For me, ok to name it `stopKoin()` to better refer as `startKoin` opposite as you mentioned.

**Comment by arnaudgiuliani** [comment]
fixed in `1.0.0-beta-4`
