### ISSUE TITLE
ClosedScopeException on Device Rotation with koinInject

### ISSUE THREAD

**Issue by gecko10000** [InsertKoinIO/koin#1773]
**Describe the bug**
When using `koinInject()` in a Composable, rotating the device causes a ClosedScopeException and crashes the application.

**To Reproduce**
Run [this minimal reproducible example](https://github.com/gecko10000/KoinCrashMRE) and rotate the device.

**Expected behavior**
The rotation should succeed and the application should continue running.

**Koin module and version:**
 `koin-android:3.5.3`
 `koin-androidx-compose:3.5.3`

**Comment by hoc081098** [comment]
@gecko10000 try wrap the composable with `KoinContext { ... }`

**Comment by gecko10000** [comment]
That fixes it, but it would be helpful to mention in the documentation, probably around [here](https://insert-koin.io/docs/reference/koin-compose/compose#starting-koin-with-android-jetpack-compose---koinapplication-or-koinandroidcontext-since-110). I assumed `androidContext(this@MainActivity)` would be enough in the `startKoin` block (since it mostly worked).

**Comment by arnaudgiuliani** [comment]
Cool. I'll update the documentation 👍

**Comment by arnaudgiuliani** [comment]
Doc added 👍
