### ISSUE TITLE
Docs are not sync on the koin website.

### ISSUE THREAD

**Issue by GrzegorzBobryk** [InsertKoinIO/koin#1776]
**Describe the bug**
Docs are not sync on the koin website.

**To Reproduce**
1. Go to https://insert-koin.io/docs/setup/koin/
2. Compare it with https://github.com/InsertKoinIO/koin/blob/main/docs/setup/koin.md
3. Go to https://insert-koin.io/docs/reference/koin-core/dsl-update
4. Compare it with https://github.com/InsertKoinIO/koin/blob/main/docs/reference/koin-core/dsl-update.md
etc.

**Expected behavior**
We are able see latest fixes in documentation using https://insert-koin.io website.

**Koin module and version:**
N/A

**Snippet or Sample project to help reproduce**
N/A

**Comment by pedrofsn** [comment]
I think that exists some extra step to publish doc written in https://github.com/InsertKoinIO/koin. Probably the docs in github need to be "compiled" and published in somewhere.

The webpage is using [Docusaurus](https://docusaurus.io/) to generate a beautiful doc.

**Comment by GrzegorzBobryk** [comment]
All good now
