### ISSUE TITLE
Can't startKoin from custom class

### ISSUE THREAD

**Issue by sough** [InsertKoinIO/koin#179]
Hello, as startKoin is extension for ComponentCallbacks, I can't use in in class, that don't implement that interface, is it ok?)

**Comment by arnaudgiuliani** [comment]
That's right. Or use `KoinComponent` interface.

**Comment by arnaudgiuliani** [comment]
You can use the `startKoin()` from core project (`StandAloneContext`). Check also the `KoinComponent`: https://beta.insert-koin.io/docs/1.0/quick-references/koin-core/#inject-with-koincomponents

**Comment by arnaudgiuliani** [comment]
Closing question issue - Please reopen it or post your next question on stackoverflow: https://stackoverflow.com/questions/tagged/koin
