### ISSUE TITLE
Use ktor-koin3.5.2-RC1, with ktor auto-reload, not working ktor-server.

### ISSUE THREAD

**Issue by momosetkn** [InsertKoinIO/koin#1792]
**Describe the bug**

becomes unresponsive after ktor auto-reload.

**To Reproduce**
1. git clone https://github.com/momosetkn/koin-ktor-auto-reload-bug
2. `./gradlew build and `./gradlew -t compilekotlin`
3. execute below command in another console. `./gradlew run`
4. when you change the code, It becomes unresponsive, like below.
```
curl localhost:8080
# curl: (52) Empty reply from server
```

**Expected behavior**
server was respond

**Koin module and version:**

ktor-koin version: 3.5.2-RC1
(3.5.1 version is works)

**Snippet or Sample project to help reproduce**

https://github.com/momosetkn/koin-ktor-auto-reload-bug

**Comment by arnaudgiuliani** [comment]
Follow up PR has been merged 👍
