### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by zafar-apk** [InsertKoinIO/koin#1793]
**Describe the bug**
Hi. I found a typo inside of the https://insert-koin.io/docs/reference/koin-core/context-isolation page. The word "the" is written as "teh". The whole sentence "This uses teh default Koin context to register your dependencies."

**To Reproduce**
1. Go to 'https://insert-koin.io/docs/reference/koin-core/context-isolation'
2. See the typo

**Comment by anvaya-solanki** [comment]
The typo has been corrected.
<img width="600" alt="image" src="https://github.com/InsertKoinIO/koin/assets/140819414/2654db4a-7b7a-4494-9f84-90d4a1863182">

**Comment by DarkTechPirate** [comment]
Yea , it has been corrected
