### ISSUE TITLE
Update koin-compose to use Compose 1.6.0

### ISSUE THREAD

**Issue by jan-tennert** [InsertKoinIO/koin#1803]
**Is your feature request related to a problem? Please describe.**
Compose libraries which are built with Compose 1.5.X are not compatible with apps using Compose 1.6.0, as described in the release notes:
> Libraries which depend on earlier Compose Multiplatform version are not compatible with 1.6.0 anymore. This is because decoys generation was disabled. Projects which apply Compose Compiler plugin manually need to remove this argument: plugin:androidx.compose.compiler.plugins.kotlin:generateDecoys=true.

**Describe the solution you'd like**
A new version for koin-compose with Compose 1.6.0.

**Comment by hoc081098** [comment]
I think it is duplicated, #1634

**Comment by abdallahmehiz** [comment]
good to know since i also just faced this issue (wasted 6hours on it)

**Comment by arnaudgiuliani** [comment]
Yes, it's taken in 3.6
