### ISSUE TITLE
org.koin.error.NoBeanDefFoundException: No definition found to resolve type 'android.content.Context'. Check your module definition error

### ISSUE THREAD

**Issue by tugcekeser** [InsertKoinIO/koin#181]
Hi,
I am trying to run DryRunTest and getting following error from the compiler.

**ERROR:**
org.koin.error.BeanInstanceCreationException: Can't create bean Bean[class=com.zumepizza.app.pielot.utils.ZumeSharedPreferences] due to error :
	org.koin.error.NoBeanDefFoundException: No definition found to resolve type 'android.content.Context'. Check your module definition

**My module class:**
val appModule: Module = applicationContext {
    bean { ZumeSharedPreferences(get()) }
    bean { APIClient(get()) }
}

**ZumeSharedPreferences class:**
class ZumeSharedPreferences(context: Context) {

    private val PREFERENCE_NAME = "ZSharedPreferences"
    private val preference: SharedPreferences

    init {
        preference = context.getSharedPreferences(PREFERENCE_NAME, Context.MODE_PRIVATE)
    }
...

I need to inject Context to initialize ZumeSharedPreferences according to my current code.  How can I inject Context? Or what is the best way to inject a SharedPreferences class to my application?

Thanks,

**Comment by asannes** [comment]
You could use androidContext() in your ZumeSharedPreferences bean:
`bean { ZumeSharedPreferences(androidContext()) }`

If you are writing tests, you may need to mock the Application (with say mockito):
`
startKoin(listOf(appModule)) with mock(Application::class.java)
dryRun()
closeKoin()
`

**Comment by tugcekeser** [comment]
Thank you for the answer @asannes . But, I guess "bean { ZumeSharedPreferences(get()) }"  is doing same job as "bean { ZumeSharedPreferences(androidContext()) }" . Am I right? I am having trouble while I am testing. "with mock(Application::class.java)" part does not change anything. I am still getting error.

**Comment by arnaudgiuliani** [comment]
in Koin `1.0.0` you have `declareMock` to help you: https://beta.insert-koin.io/docs/1.0/quick-references/koin-test/#bring-koin-powers-to-your-test-class

In 0.9.x, you have to use the `with` operator at start to give it a `Application` instance. It will help you inject this instance later.

**Comment by arnaudgiuliani** [comment]
Closing question issue - Please reopen it or post your next question on stackoverflow: https://stackoverflow.com/questions/tagged/koin
