### ISSUE TITLE
State is not restored correctly when using `koinNavGraphViewModel`

### ISSUE THREAD

**Issue by JozefCeluch** [InsertKoinIO/koin#1828]
**Describe the bug**

The state in a VM created using `koinNavGraphViewModel` doesn't seem to be restored correctly from the  `SavedStateHandle`

**To Reproduce**
I added a more detailed description and a workaround that seems to be working fine using `activityViewModel` in the sample project linked below

**Expected behavior**
keys inside `SavedStateHandle` should contain values when state is restored after process was killed by the system

**Koin module and version:**
`koin-androidx-navigation:3.6.0-alpha3` (I first noticed it in `3.5.3`)

**Snippet or Sample project to help reproduce**
https://github.com/JozefCeluch/koin-state-loss

**Comment by oleksandrbalan-etn** [comment]
We've encountered the same issue. Is there another workaround besides using `activityViewModel`?
