### ISSUE TITLE
Koin 3.5 is not binary-compatible with 3.4

### ISSUE THREAD

**Issue by gsprdev** [InsertKoinIO/koin#1829]
**Describe the bug**

If a library is compiled using Koin 3.4, and an app using Koin 3.5 tries to use that library, a runtime exception can occur.

Koin 3.5 appears to be source-compatible with 3.4, but is not binary-compatible.

This appears to be because Koin 3.5 violates [kotlinlang.org's "Don't add arguments to existing API functions﻿" guideline for libraries](https://kotlinlang.org/docs/jvm-api-guidelines-backward-compatibility.html#don-t-add-arguments-to-existing-api-functions)

**To Reproduce**

1. Declare a library with a dependency on Koin 3.4.2
2. Define an entrypoint which uses the `koinApplication { }` API as instructed in [insert-koin.io's "Context Isolation" documentation](https://insert-koin.io/docs/reference/koin-core/context-isolation)
3. Define an app with a dependency on both the test library and Koin 3.5.3 (using BOM)
4. Invoke the library's entrypoint in an app

An exception similar to the following will be produced:

> No static method koinApplication(Lkotlin/jvm/functions/Function1;)Lorg/koin/core/KoinApplication; in class Lorg/koin/dsl/KoinApplicationKt; or its super classes (declaration of 'org.koin.dsl.KoinApplicationKt' appears in […]) 

**Expected behavior**
Maven dependency resolution will select 3.5.3 over 3.4.2 because they are theoretically semver-compatible and 3.5.3 is higher.
Library will continue to function as expected, with isolated context.

**Koin module and version:**
koin-core:3.5.3

**Snippet or Sample project to help reproduce**
~No standalone set of projects created, but a PR will follow.~
https://github.com/gsprdev/koin1829

**Comment by gsprdev** [comment]
Repro example: https://github.com/gsprdev/koin1829

**Comment by arnaudgiuliani** [comment]
Thanks for the feedback. What's the fix you had to apply? 🤔
