### ISSUE TITLE
Fragment's ViewModel injection in nested Fragment

### ISSUE THREAD

**Issue by roccadev** [InsertKoinIO/koin#183]
With the new Navigation APIs, the role of the Activity has been structurally overtaken by Fragments; it is not uncommon now to have a parent Fragment with nested Fragments. In this scenario, when injecting a ViewModel into the nested Fragments, we would want to inject a shared ViewModel owned by the parent Fragment. Currently, using `by sharedViewModel()` inside the nested Fragment returns an instance of ViewModel owned by the overlaying Activity, which outlives the scope of the parent Fragment when navigating away from it.

Feature request:
A way to specify the owner of the shared ViewModel we are requesting for injection, something like

    val viewModel: MyViewModel by viewModel(from = parentFragment)

The current working way I'm using to achieve this result is something like this:

    val viewModel: MyViewModel by lazy { parentFragment!!.viewModel<MyViewModel>().value }

Being `parentFragment` `null` during initialization, it's necessary to add a second `lazy` layer which is not very elegant.
I haven't tried other options like using a key. If there's a better way to do this, or even an already implemented one, I must have missed it.

Target Koin project:
koin-androidx-viewmodel

**Comment by arnaudgiuliani** [comment]
Fixed in `beta-9`

See https://github.com/InsertKoinIO/koin/pull/209
