### ISSUE TITLE
Update mockito version (koin-test)

### ISSUE THREAD

**Issue by jcornaz** [InsertKoinIO/koin#184]
**Is your feature request related to a problem? Please describe.**
If an interface contains `suspend` functions, then it is not possible to use `declareMock` for it.

**Describe the solution you'd like**
This problem has already been solved in Mockito in https://github.com/mockito/mockito/pull/1032.
Koin should simply use a more recent version of mockito.

**Describe alternatives you've considered**
The user may explicitly declare a more recent of mockito in his/her build. 

**Target Koin project**
koin-test

**Comment by arnaudgiuliani** [comment]
Will be updated to `2.18.3`

**Comment by arnaudgiuliani** [comment]
fixed in `1.0.0-beta-4`
