### ISSUE TITLE
KoinAppAlreadyStartedException after changing theme

### ISSUE THREAD

**Issue by Cuyer** [InsertKoinIO/koin#1840]
**Describe the bug**
When changing from light to dark theme or vice versa, following error is thrown:

`KoinAppAlreadyStartedException: A Koin Application has already been started`

**To Reproduce**
1. Change theme to from light mode to dark mode or vice versa
2. App crashes

**Expected behavior**
App doesn't crash

**Koin module and version:**
I suppose its koin-compose:3.6.0-wasm-alpha2

I am working on a project that uses compose multiplatform. I've tried using documentation to start koin, but its lacking information regarding compose multiplatform.

**Snippet or Sample project to help reproduce**
```kotlin
class MainActivity : FragmentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        this.enableEdgeToEdge()
        super.onCreate(savedInstanceState)
        startKoin {
            androidContext(this@MainActivity)
            modules(
                appModule(),
                androidModule()
            )
            logger(PrintLogger())
        }
        setContent {
            AppTheme {
                App()
            }
        }

    }
}
```

**Comment by gamer3dx** [comment]
You initializing Koin inside onCreate in Activity, which is recreated on theme change.
Try to initialize it inside onCreate in Application.

**Comment by Cuyer** [comment]
I've tried it as such:

```kotlin
class MainApp : Application() {

    override fun onCreate() {
        super.onCreate()

        startKoin {
            androidContext(this@MainApp)
            modules(
                appModule(),
                androidModule()
            )
            logger(PrintLogger())
        }
    }
}
```

But I get error java.lang.IllegalStateException: KoinApplication has not been started

**Comment by gamer3dx** [comment]
Interesting. What are you doing to get this exception? I remember that I encountered this error on first inject call in my pet project when I forgot to register my application class in Manifest file.

**Comment by Cuyer** [comment]
Yes, that's exactly the issue. I had to register application class in manifest file and everything works now.

**Comment by kopoh** [comment]
Omg I have the same problem, I do initKoin() in Common Main: 
```
@Composable
internal fun App() {
    AppTheme {
        initKoin()
        Napier.base(DebugAntilog())
    
        Navigator(screen = FirstScreen)
    }
}
```

and my application crashes already when switching themes using the theme switch button in the status bar.
