### ISSUE TITLE
Override does not clear InstanceFactory cache

### ISSUE THREAD

**Issue by zoopolitic** [InsertKoinIO/koin#185]
**Describe the bug**
I have dependencies graph that provides some dependencies as `single`, in Instrumentation test I want to replace some of the dependencies with mock, by providing module that overrides that dependencies:

Original module:
```
val myDependencies = module {
     single {RepositoryImpl() as Repository}
}

```
in my test I have:
```
 fun beforeActivityLaunched() {
       val mockDependencies = module {
                single(override = true, definition = { MockRepository() as Repository })
       }
       loadKoinModules(listOf(mockDependencies))
   }
```

**Expected behavior**
after `beforeActivityLaunch` I expect any module or client that requests Repository through `get()` to receive mockRepository instead of original one since I've overridden this dependency. Instead `InstanceFactory` does `findInstance<T>(def)` and finds old instance since it is not overrides when `override=true` flag provided

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-android version 1.0.0-beta-3`

**Comment by arnaudgiuliani** [comment]
How did you start Koin? Did you list your dependencies in order?

**Comment by arnaudgiuliani** [comment]
Yes, for both `startKoin()` or `loadKoinModules()` order matters. Specify in last, the module that will override the others.

**Comment by zoopolitic** [comment]
I don't see the code for clearing the `InstanceFactory` cache, does it clear this cache somehow after `loadKoinModules` call ?

**Comment by jakob-grabner** [comment]
What worked for me is releasing all instances manually after overwriting the module
```            
loadKoinModules(
    module(override = true) {
        single(definition = { MockRepository() as Repository })
    }
)
release("")
```

**Comment by zoopolitic** [comment]
@jakob-grabner yeah, that worked for me too, but I created issue because I think that overriding module should invalidate cache

**Comment by arnaudgiuliani** [comment]
Ok, got it 👍

**Comment by arnaudgiuliani** [comment]
Fixed in `beta-9`

**Comment by zoopolitic** [comment]
👍
