### ISSUE TITLE
Kotlin Multiplatform ViewModel support in Koin

### ISSUE THREAD

**Issue by mahramane** [InsertKoinIO/koin#1858]
Hi
Now Kotlin multiplatform support [ViewModel](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-lifecycle.html#viewmodel-implementation).
Please support [ViewModel](https://insert-koin.io/docs/reference/koin-android/compose/#viewmodel-for-composable) in Koin.

**Comment by arsildo** [comment]
@arnaudgiuliani Would koinViewModel() work in in common main now?

**Comment by frankois1234** [comment]
See : https://github.com/InsertKoinIO/koin/issues/1826

**Comment by arnaudgiuliani** [comment]
work in progress https://github.com/InsertKoinIO/koin/issues/1826
