### ISSUE TITLE
Missing Source Code

### ISSUE THREAD

**Issue by ynsok** [InsertKoinIO/koin#1859]
**Describe the bug**
Trying to read the source code of the function koinViewModel I can see just Decompiled .class file 

<img width="1641" alt="image" src="https://github.com/InsertKoinIO/koin/assets/30358511/6f3e33d9-35ab-4a09-be45-f0ae6f54b279">

![image](https://github.com/InsertKoinIO/koin/assets/30358511/2177d314-bfb4-4169-9996-cc5a45bca22a)

**Expected behavior**
I would like to see the source code of the functions

**Koin module and version:**
 [e.g]: `3.6.0-alpha3`

**Comment by arnaudgiuliani** [comment]
can you check with latest beta version?

**Comment by arnaudgiuliani** [comment]
Fixed since 3.6.0 - beta-3
