### ISSUE TITLE
SLF4JLogger is using the wrong level when printing to logger

### ISSUE THREAD

**Issue by swermin** [InsertKoinIO/koin#1870]
From my experimentations I found that the `SLF4JLogger` always prints in what ever level the class has been configured for instead of the incoming level from the function, [see this link](https://github.com/InsertKoinIO/koin/blob/3a99eb0cab63d9eb8d6df0cdc448f52993ac3d32/projects/ktor/koin-logger-slf4j/src/main/kotlin/org/koin/logger/SLF4JLogger.kt#L34)

From my test code, I added the logger like this
```
install(KoinIsolated) {
    slf4jLogger()
    createEagerInstances()
}
```

With that it always printed `info`, even if the log level was supposed to be `warn`.

**Comment by arnaudgiuliani** [comment]
Fixed in RC2
