### ISSUE TITLE
Cannot run on iOS

### ISSUE THREAD

**Issue by robertmktg** [InsertKoinIO/koin#1874]
**Describe the bug**
When running on iOS I am receiving this error
```
error: Could not find "co.touchlab:stately-concurrent-collections" in [/Users/robertlevonyan/StudioProjects/inn/countries-kmp, /Users/robertlevonyan/.konan/klib, /Users/robertlevonyan/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.23/klib/common, /Users/robertlevonyan/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.23/klib/platform/ios_simulator_arm64]
error: Compilation finished with errors
```

**To Reproduce**
Add koin-compose dependency to your multiplatform project and try to run on iOS emulator

**Expected behavior**

**Koin module and version:**
`koin-compose:3.6.0-wasm-alpha2`

**Comment by charles-mutabazi** [comment]
@robertmktg  I was facing the same issue - i installed **`co.touchlab:stately-common:2.0.5`** and fixed my issue, i guess Koin is pulling an outdated version or something idk

**Comment by robertmktg** [comment]
@charles-mutabazi thanks in fact I needed to add both `"co.touchlab:stately-common:2.0.5"` and
`"co.touchlab:stately-concurrent-collections:2.0.6"` and also downgrade to `3.6.0-wasm-alpha1`
