### ISSUE TITLE
Promote Koin 3.6.0 and Koin-Compose 1.2.0 to Stable

### ISSUE THREAD

**Issue by egorikftp** [InsertKoinIO/koin#1885]
**Is your feature request related to a problem?**

Since release Kotlin 2.0 and Compose Multiplatform 1.6.10 is it possible to make a stable release for Koin 3.6.0?

**Comment by arnaudgiuliani** [comment]
Publishing 4.0-RC1 to help test it 👍

**Comment by egorikftp** [comment]
Will close for now, waiting 4.0 stable 🙂
