### ISSUE TITLE
Improve extendability (plugin support?)

### ISSUE THREAD

**Issue by dshatz** [InsertKoinIO/koin#1890]
**Is your feature request related to a problem? Please describe.**
I am developing a ksp processor for generating a koin module from ktorfit declarations.
https://github.com/dshatz/ktorfit-koin

The user creates a class:
```kotlin
@ServiceModule(scan="com.example.services")
class NetworkModule
```
My library generates:
```kotlin
val NetworkModule.module: Module = networkModule
val networkModule = module {
   // all ktorfit services discovered by my ksp processor.
}
```

Then, import the generated module into a normal Koin module.
```kotlin
@Module(includes=[NetworkModule::class])
class AppModule
```

The problem is that koin config check doesn't allow this. The error I get is: 
`Fix your configuration: add @Module annotation on <Module class generated by ktorfit-koin>`

**Describe the solution you'd like**
Optionally disable `@Module` annotation presence check. Or implement some plugin mechanism?

**Describe alternatives you've considered**
Disabling koin config check.

**Target Koin project**

**Comment by arnaudgiuliani** [comment]
can you open in koin annotations repo?

**Comment by dshatz** [comment]
https://github.com/InsertKoinIO/koin-annotations/issues/192
