### ISSUE TITLE
activityRetainedScope and fragmentScope are failing when activity is recreated due to configuration change.

### ISSUE THREAD

**Issue by 0x-cell** [InsertKoinIO/koin#1903]
**Describe the bug**
When you rotate your phone an Activity is recreated due to configuration change. If we use the `activityRetainedScope` and `fragmentScope` we will have a definition crash:

`Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for type 'com.example.myapplication4.Foo'. Check your Modules configuration and add missing type and/or qualifier!`

**To Reproduce**
1. 
```
class MainFragment : Fragment(), AndroidScopeComponent {
    override val scope: Scope by fragmentScope()

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        return inflater.inflate(R.layout.main_fragment, container, false)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        view.findViewById<TextView>(R.id.textView).text = get<Foo>()()
    }
}
```
2. 
```
class MainActivity : FragmentActivity(), AndroidScopeComponent {

    override val scope: Scope by activityRetainedScope()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.main_activity)
    }
}
```
3. 
```
class App : Application() {

    override fun onCreate() {
        super.onCreate()
        startKoin {
            androidLogger()
            androidContext(this@App)
            modules(
                module {
                    scope<MainActivity> {
                        scoped<Foo> { Foo() }
                    }
                }
            )
        }
    }
}
```
4. Rotate your device, split screen or popin it. Crash occurs.

**Expected behavior**
To not crash

**Koin module and version:**
 `koin-android:3.5.6`

**Reason**
1. When `activityRetainedActivity` (in Activity#A1) is used, we store newly created scope (Scope#Activity#A1) in `ScopeHandlerViewModel`.
2. Fragment calls `fragmentScope` which uses `Activity.getScopeId` to retrieve the correct id (Scope#Activity#A1) 
3. When Android recreates the Activity (Activity#2) the `activityRetainedActivity` retrieves stored scope (Scope#Activity#A1).
4. Fragment also gets recreated and calls the `fragmentScope` which insides tries to find Activity scope (Scope#Activity#A2) which is not present. Causing a dependency issue.

The implementation of `fragmentScope` retrieves parent (Activity) scope using following method:
```fun ComponentActivity.getScopeOrNull(): Scope? = getKoin().getScopeOrNull(getScopeId())```
where `getScopeId()` is ```fun <T : Any> T.getScopeId() = this::class.getFullName() + "@" + this.hashCode()```

When Android re-creates Activities (ie. spawns new Activity) due to configuration changes the `getScopeId` results in different values:
1. `MainActivity com.example.myapplication4.MainActivity@845bb25 - Foo com.example.myapplication4.Foo@c2f96c6`
2. Rotate screen
3. `MainActivity com.example.myapplication4.MainActivity@b67ace9 - Foo com.example.myapplication4.Foo@c2f96c6`

In my opinion fragmentScope shouldn't use the `this::class.getFullName() + "@" + this.hashCode()` to find Activity scope.
I was able to fix this by creating my own `fragmentScope` in following format:

```
fun Fragment.createFragmentScope(useParentActivityScope : Boolean = true): Scope {
    if (this !is AndroidScopeComponent) {
        error("Fragment should implement AndroidScopeComponent")
    }
    val scope = getKoin().getScopeOrNull(getScopeId()) ?: createScopeForCurrentLifecycle(this)
    if (useParentActivityScope){
        val activityScope = (requireActivity() as? AndroidScopeComponent)?.scope
        if (activityScope != null) {
            scope.linkTo(activityScope)
        } else {
            scope.logger.debug("Fragment '$this' can't be linked to parent activity scope")
        }
    }
    return scope
}
```

Which uses the ` val activityScope = (requireActivity() as? AndroidScopeComponent)?.scope` instead of `val activityScope = requireActivity().getScopeOrNull()`.

Please let me know if this is really an issue or my lack of understanding how scopes work in koin. 

Thanks :)

**Comment by arnaudgiuliani** [comment]
Ok interesting. Closing Activity + Fragment should closes both. I don't remelber in the lifecycle if the fragment can survive over an activity? 🤔

**Comment by 0x-cell** [comment]
Hey, I think there is a small misunderstanding. 

> Ok interesting. Closing Activity + Fragment should closes both.
And this is what is occurring.

The problem is how we retrieved the scope of Activity from a Fragment point of view -
`activityRetainedActivity` stores Scope in  `ScopeHandlerViewModel` . When Activity is recreated the scope is retrieved. But recreated Fragment tries to find wrong/missing/not-created scope.

**Comment by arnaudgiuliani** [comment]
> When Activity is recreated the scope is retrieved. But recreated Fragment tries to find wrong/missing/not-created scope.

Ok, let me check.

**Comment by arnaudgiuliani** [comment]
fixed in RC2
