### ISSUE TITLE
Any plans to move from KSP to kotlin compiler plugin? 

### ISSUE THREAD

**Issue by sureshg** [InsertKoinIO/koin#1918]
Are there any plans to move out of KSP to kotlin compiler plugin? Recently the kotlinx-rpc team has moved from [ksp to compiler plugin](https://github.com/Kotlin/kotlinx-rpc/pull/105#issuecomment-2228052742) because of the following advantages

- KSP Gradle plugin needs to be added explicitly by the user, that's a friction in UX
- KSP does not support Gradle configuration caches
- KSP exposes generated code, which we often don't want to do to keep the sources clean
- KSP does not allow for existing code modifications, so we need a compiler plugin anyway
- K2 frontend compiler plugins will allow for IDE integration for generated declarations in future, so we might make use of it too

I am not sure all of these are applicable for koin, but the first two will have an impact on build speed and UX.

**Comment by arnaudgiuliani** [comment]
Thanks for your feedback. It depends where we want to go: we have 2 ways to deal with compile time safety: Annotation processing + ksp checks or Typesafe DSL + compiler plugin.

It's a good challenge for Koin Annotations to change the ksp compiler to kotlin compiler. Let's see how it goes with KSP2
