### ISSUE TITLE
Documentation Bug: "Application" Should Be "Activity"

### ISSUE THREAD

**Issue by commonsguy** [InsertKoinIO/koin#1925]
**Describe the bug**
The wrong class is used in a code snippet in the documentation.

**To Reproduce**
1. Go to https://insert-koin.io/docs/setup/why#ready-for-android
2. Read the second code snippet, notice that the class is named `MyActivity` and that injected object is a "presenter"

**Expected behavior**
`MyActivity` to extend `Activity`, not `Application`. IOW, it should be:

```kotlin
class MyActivity : Activity() {

  val myPresenter : MyPresenter by inject()

} 
```

(if you would prefer `ComponentActivity` or `AppCompatActivity`, that's cool too)

**Koin module and version:**
The current version of Koin is `4.0.0-RC1`

Thanks for considering this!

**Comment by arnaudgiuliani** [comment]
Fixed in e592cf21fa9f9230a05627c33ec2ef3f62cf22e6 👍
