### ISSUE TITLE
`androidContext()` swallows/hides underlying exceptions

### ISSUE THREAD

**Issue by yogurtearl** [InsertKoinIO/koin#1932]
If the `get()` for a context throws an exception, the cause is discarded. 
(same applies for `Scope.androidApplication()`)

The `e` here is discarded.

See this code: 
https://github.com/InsertKoinIO/koin/blob/5fab1ca74add39339e281aaa822c618a2da5baa3/projects/android/koin-android/src/main/java/org/koin/android/ext/koin/ModuleExt.kt#L30-L34

Instead it should be something like this: 

```kotlin
class MissingAndroidContextException(message: String, cause: kotlin.Throwable?)
     : kotlin.Exception(message, cause)

fun Scope.androidContext(): Context = try {
    get()
} catch (e: Exception) {
    throw MissingAndroidContextException("Can't resolve Context instance. $ERROR_MSG", e)
}
```

**Comment by arnaudgiuliani** [comment]
Thanks
