### ISSUE TITLE
Breaking changes in Koin 4.0.0-rc1

### ISSUE THREAD

**Issue by pedrofsn** [InsertKoinIO/koin#1938]
## Problem
The file `CheckModules.kt` was deleted in https://github.com/InsertKoinIO/koin/compare/3.5.6...4.0.0-RC1. But in changelog description there is only informing about a deprecation https://github.com/InsertKoinIO/koin/releases/tag/4.0.0-RC1.

I think that could be some mistake in code deletion or missing information in description. I expect that be the first case cause it will bring a huge refactor in the project that working on it.

## Suggestion
If the idea is really delete this class because it's problematic, I suggest to deprecate it first to the entire Koin ecosystem and just in a future release, really delete it.

## Sample
This is a print of what I've changed to support (just in compile time) the Koin 4.0.
![image](https://github.com/user-attachments/assets/64f4f162-02ba-4ebb-a656-5ca6ed561c2c)

We've literally thousand of modules and we're using checkModules() function combined with startKoin, stopKoin and providing mocked dependencies required for the tested module.

**Comment by pedrofsn** [comment]
A side effect is the obligation to use `verify()` to test modules. In my opinion, this API is incomplete cause it just check the constructor parameters if the module is written based in constructor DSL. It's impact in a "fake test" for modules written in old-fashion DSL.

I commented about it [here](https://github.com/InsertKoinIO/koin/issues/1509#issuecomment-2271454930).

**Comment by pedrofsn** [comment]
I've created an PR restoring check modules as suggestion, https://github.com/InsertKoinIO/koin/pull/1939.

**Comment by arnaudgiuliani** [comment]
Ok, let's follow up on the PR. thanks for your feedback
