### ISSUE TITLE
What does bind exactly do?

### ISSUE THREAD

**Issue by ArcherEmiya05** [InsertKoinIO/koin#1943]
I am still not clear what is the difference between using `bind` vs not. Is it for readability and style only or the one improves code performance or perhaps it differs based on how we access it later?

```
single<WordPressPostsRepository> {
   WordPressPostsRepositoryImpl(get(), get(), get())
}
```

vs 

`singleOf(::WordPressPostsRepositoryImpl).bind<WordPressPostsRepository>()`

**Comment by arnaudgiuliani** [comment]
> singleOf(::WordPressPostsRepositoryImpl)
`singleOf` take the same as `single`, but fill all your dependencies with `get()`.  Problem is that you can't directly a bound type like `single<WordPressPostsRepository> { WordPressPostsRepositoryImpl ... }`

Then `singleOf` requires the `bind` operator, to bind explicitly the desired type.
