### ISSUE TITLE
Inject collection of injectable types

### ISSUE THREAD

**Issue by CLOVIS-AI** [InsertKoinIO/koin#1949]
**Is your feature request related to a problem? Please describe.**
I have a service "Trigger" that triggers an action in other services. The services that must be triggered implement a marker interface "Trigerrable".

I would like to declare the "Trigger" service without specifying all implementations of Triggerable manually.

**Describe the solution you'd like**

If a service is declared as such:
```kotlin
class Trigger(
    val services: List<Triggerrable>
) { … }
```

then `singleOf(::Trigger)` should automatically find all Triggerrable instances.

**Describe alternatives you've considered**

This currently works, but seems like a hack / isn't clear to understand:
```kotlin
single<List<Triggerrable>> {
    getAll(Triggerable::class)
}

singleOf(::Trigger)
```

**Target Koin project**

Koin Core

**Comment by arnaudgiuliani** [comment]
> then singleOf(::Trigger) should automatically find all Triggerrable instances.

Hello, yes this is a limitation of current `singleOf`

The New DSL project should help with that. For now, this is a limitation. Stick to the classic DSL 👍
