### ISSUE TITLE
May be an option to Make @KoinViewModel default as @Factory on Not Android Platfrom

### ISSUE THREAD

**Issue by mny459** [InsertKoinIO/koin#1967]
When use Koin on a KMP project with native ui on both android and ios.

I always use  annotation, but when I use @KoinViewModel in shared code. It will not work.

I have to write di code on both android and ios like this

Android actual
```
viewModelOf(::ArchivedBookViewModel)
```

iOS actual

```
factoryOf(::ArchivedBookViewModel)
```

So is there any option to make @KoinViewModel default as @Factory on Not Android Platfrom. So I do not need to write more di code. It's really easy to forget.

**Comment by arnaudgiuliani** [comment]
Please open in koin-annotations repo - https://github.com/InsertKoinIO/koin-annotations/issues

Yes, that's a good remark. Did you try to use `@Factory` directly instead? You will call it via ViewModel API, it should stick to the lifecycle on Android.

**Comment by mny459** [comment]
Thank you, I will try this.
