### ISSUE TITLE
Potential mistake in koin-ktor documentation

### ISSUE THREAD

**Issue by dAnjou** [InsertKoinIO/koin#1982]
In https://insert-koin.io/docs/reference/koin-ktor/ktor, it says:

> ### Resolve from Ktor Request Scope (since 3.5.0)
> 
> You can declare components to live within Ktor request scope timeline. For this, you just need to declare your component inside a `scope<ScopeRequest>` section. Given a `ScopeComponent` class to instantiate on RequestScope, let's declare it:
> 
> ```kotlin
> scope<RequestScope>{
>     scopedOf(::ScopeComponent)
> }
> ```

Is it `ScopeRequest` or `RequestScope`?

I think it's the latter, because the former doesn't show up anywhere in the code.

**Comment by arnaudgiuliani** [comment]
It's `RequestScope`. Could be a `dsl` keyword update for Koin 4.1. 

Fixed in f511b17a1f2751f84ee7f2f19f277cd4bbbffed3
