### ISSUE TITLE
More documentation for onClose

### ISSUE THREAD

**Issue by AlexStarc** [InsertKoinIO/koin#1988]
**Is your feature request related to a problem? Please describe.**
Looks like doing onClose / clearing objects is a basic good practice due to multiple reasons: safety, memory-wise

**Describe the solution you'd like**
It would be great to have more description for onClose usage in the documentation. May be some best practices.

**Target Koin project**
koin

**Comment by arnaudgiuliani** [comment]
Doc added `bb0a33b29f651720e894ed1dba1799620e1e0014`
