### ISSUE TITLE
Better docs for lazy modules

### ISSUE THREAD

**Issue by GrzegorzBobryk** [InsertKoinIO/koin#1997]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I cannot learn new features. I do not get how it suppose to utilize `lazyModule`.
I see that this feature is created to enable background loading. Lets say I do not want to block main thread with starting of some basic reporting classes, but I want them to start them ASAP. I care about app performance and I want this reporters to start asynchronously after koin start. I am using it like that:

```kotlin
// class itself

class Reporter {

    init {
        GlobalScope.launch {
            repeat(10) {
                delay(3.seconds)
                println("[Test] hello: $it")
            }
        }
    }
}

// lazy module

val lazyReporter = lazyModule {
    single(createdAtStart = true) { Reporter() }
}

// koin start in application

         startKoin {
            androidLogger()
            androidContext(this@TestApp)
            modules(mainModule)
            lazyModules(lazyReporter)
        }
```
None of dependencies in `mainModule` require `Reporter` but is is eager instance. It should trigger `init` block. Should we have possibility to set `createdAtStart` to `true` inside of `lazyModule`? If yes, is it a bug?

**Describe the solution you'd like**

Please add better description of how should we use lazy modules feature.

**Describe alternatives you've considered**

You can make short video or article about it also. Maybe add some sample app.

**Target Koin project**
Specify the Koin project than will embed the feature.

[docs](https://github.com/InsertKoinIO/koin/tree/main/docs)

**Comment by arnaudgiuliani** [comment]
The problem is somehow more deep, as `lazyModule` can't check for dependencies. Other Koin mechanism for module check should help on that. Let's count on later internal design.
