### ISSUE TITLE
Get error while injecting inside Route in ktor

### ISSUE THREAD

**Issue by mhdabbaghy** [InsertKoinIO/koin#2008]
**Describe the bug**
In ktor when i want to inject a class inside my Route I'm getting exception:

Exception in thread "main" java.lang.NoClassDefFoundError: io/ktor/server/routing/RoutingKt
	at org.koin.ktor.ext.RouteExtKt.getKoin(RouteExt.kt:74)

Here is my code:
`
fun Route.authRoutes() {

    val authService: AuthService by inject()

    route("/auth") {
        loginRoute(authService)
    }
}
`

but when I change code to

`
fun Route.authRoutes() {

    val authService: AuthService by application.inject()

    route("/auth") {
        loginRoute(authService)
    }
}
`
 It works fine

Koin version: 4.0.0
Ktor version: 3.0.0-rc-1
kotlin version: 2.0.20

**Comment by Nek-12** [comment]
Duplicate of #1716

**Comment by sschuberth** [comment]
> Duplicate of #1716

Indeed, please close this issue @mhdabbaghy.
