### ISSUE TITLE
@deprecated annotion does wrong replace for closeKoin

### ISSUE THREAD

**Issue by dpreussler** [InsertKoinIO/koin#201]
**Describe the bug**
given a method like:
```
fun stopInjection() {
    closeKoin()
}
```

when using Android Studio to change it will do:
```
fun stopInjection() {
    this.stopKoin()
}
```
where `this` is wrong

**Koin project used and used version (please complete the following information):**
`1.0.0-beta-4"`

**Additional context**
latest Android Studio 3.1

**Comment by arnaudgiuliani** [comment]
Yeah :/ 
The replaceWith don't actually get the idea that's a extension function. We'll check it!

**Comment by mattmook** [comment]
To me this looks more like a bug in the way IntelliJ performs the autofix as if the code to replace is written as `StandAloneContext.closeKoin()` the refactoring works. As such I've raised an issue for JetBrains https://youtrack.jetbrains.net/issue/KT-26361 to take a look.

**Comment by arnaudgiuliani** [comment]
Argh... effectively. This is exactly the problem :/

A temporary solution could be to remove the `replaceWith` argument to let people replace `closeKoin` by `stopKoin`.

**Comment by arnaudgiuliani** [comment]
Simplified deprecated annotation in `beta-9`, to avoid propose something wrong :/
