### ISSUE TITLE
[Improvements] koin-androidx-startup setup and documentation

### ISSUE THREAD

**Issue by santimattius** [InsertKoinIO/koin#2012]
I have reviewed the new Koin startup implementation using App Startup and I think it's excellent that they have added this support. Some time ago I wrote a post about it _["Koin Startup Extension: Configuring Koin using App Startup in Android"](https://medium.com/@santimattius/koin-startup-extension-configuring-koin-using-app-startup-in-android-e0facd2fd943)_.

What caught my attention, and the reason I'm addressing this here, is the [KoinStartup](https://github.com/InsertKoinIO/koin/blob/4.0.0/projects/android/koin-androidx-startup/src/main/java/org/koin/androix/startup/KoinStartup.kt) object. This is used to maintain the reference of the Koin declaration, and the documentation indicates that we should call the onKoinStartup method in the init of our Application class. I think we could improve it by using the same [strategy](https://developer.android.com/develop/background-work/background-tasks/persistent/configuration/custom-configuration) that WorkManager employs. Below, I share some code to visualize this idea.

First, we would need an interface to infer the declaration when the Initializer is executed

```kotlin
interface KoinDeclaration {

    fun declaration(): KoinAppDeclaration
}
```

We could also name it KoinStartup.

Then, we would have the implementation in our Application class:

```kotlin
class MainApplication : Application(), KoinDeclaration {

    override fun declaration(): KoinAppDeclaration = {
      androidLogger(Level.DEBUG)
      androidContext(this@MainApplication)
      modules(myModules)
    }
}
```

Once we have the implementation of `KoinDeclaration` in our Application class, we could perform the following verification in our Initializer

```kotlin
class KoinSingleInitializer : Initializer<Unit> {

    override fun create(context: Context) {
        if (context !is KoinDeclaration) {
            error("KoinInitializer can't start Koin configuration. Please implement KoinDeclaration interface in your Application class")
        }
        startKoin(context.declaration())
    }

    override fun dependencies(): List<Class<out Initializer<*>>> {
        return emptyList()
    }
}
```

At this point, we could also configure the `androidContext`, ensuring that it's always initialized.

## Documentation

While the koin-startup functionality is still experimental, it would be beneficial to include information on how to use Koin in other initializers. This is especially relevant since App Startup allows specifying the dependency order. An illustrative example could be:

```kotlin
class CrashTrackerInitializer : Initializer<Unit>, KoinComponent {

    private val crashTrackerService: CrashTrackerService by inject()

    override fun create(context: Context) {
        crashTrackerService.configure(context)
    }

    override fun dependencies(): List<Class<out Initializer<*>>> {
        return listOf(KoinInitializer::class.java)
    }

}
```

I hope these ideas and suggestions are helpful. If you have any comments or additional proposals, please feel free to share them.

**Comment by arnaudgiuliani** [comment]
Yes I like your proposal. I tunned it like this:

```kotlin
@KoinExperimentalAPI
interface KoinStartup {

    /**
     * startKoin with AndroidX startup Initializer
     * @see startKoin function
     */
    @KoinApplicationDslMarker
    fun onKoinStartup() : KoinAppDeclaration
}
```

```kotlin
class KoinInitializer : Initializer<Koin> {

    @OptIn(KoinExperimentalAPI::class)
    override fun create(context: Context): Koin {
       return if (context is KoinStartup){
            startKoin(context.onKoinStartup()).koin
        } else error("Can't start Koin configuration on current Context. Please use KoinStartup interface to define your Koin configuration with.")
    }

    override fun dependencies(): List<Class<out Initializer<*>>> {
        return emptyList()
    }
}
```

And yes, documentation must be added to extend it to allow precise some dependency on it.

@santimattius do you have any feedback regarding impact with https://developer.android.com/google/play/integrity?

**Comment by arnaudgiuliani** [comment]
PR in follow: https://github.com/InsertKoinIO/koin/pull/2039

**Comment by santimattius** [comment]
Thanks @arnaudgiuliani! Regarding app integrity, I was reviewing the [issue](https://github.com/InsertKoinIO/koin/issues/2018) but I did not find any information on what could cause the error when app integrity is activated.

**Comment by arnaudgiuliani** [comment]
thanks @santimattius 👍
