### ISSUE TITLE
Koin 4.0.0: Regression of `Warning] - No Compose Koin context setup ...` error log

### ISSUE THREAD

**Issue by hakonschia** [InsertKoinIO/koin#2019]
**Describe the bug**
After bumping to BOM 4.0.0 we are seeing these messages being logged when using Compose on Android

`[Warning] - No Compose Koin context setup, taking default. Use KoinContext(), KoinAndroidContext() or KoinApplication() function to setup or create Koin context and avoid such message.`

This seems to be the same as https://github.com/InsertKoinIO/koin/issues/1677, where the message was then changed from error to debug. Was it intentional to change it back to error? We log errors to Crashlytics so it will become very noisy if we bump to 4.0.0

**Comment by kmbisset89** [comment]
If you wrap the ComposeApp in KoinContext() {
}

You should be able to eliminate ATO.

**Comment by hakonschia** [comment]
Sure we can do that, but I don't really see why we would need to if it has no behiavour impact other than removing a log message, unless it is now a strict requirment to use `KoinContext {}` (which I can't see mentioned anywhere in the release notes). The original issue also mentioned this solution and then also agreed to make it a debug log instead of error

**Comment by arnaudgiuliani** [comment]
I fixed it back in 4.0.1-Beta1. I will dive into more clearer requirements for start 👍

**Comment by hakonschia** [comment]
Cool, thanks :)
