### ISSUE TITLE
overrides should not care about previous definition type

### ISSUE THREAD

**Issue by dpreussler** [InsertKoinIO/koin#202]
**Is your feature request related to a problem? Please describe.**
It seems single can only be overridden by single and vice versa
this is bad as it ties to implementation details
For my team it blocks the migration as our tests now need to define every single one how to override.
At least tests should be allowed to override however the original definition was done

**Describe the solution you'd like**
when using loadKoinModules it should not be matter if item was single or factory

**Target Koin project**
"1.0.0-beta-4"

```
Can't create definition 'Factory [class='tv.sporttotal.android.settings.SettingsInteractor']' due to error :
   │  │                   Multiple definitions found for type 'tv.sporttotal.android.navigation.NavigationViewModel' - Koin can't choose between :
   │  │           Single [class='tv.sporttotal.android.navigation.NavigationViewModel']
   │  │           Factory [class='tv.sporttotal.android.navigation.NavigationViewModel']
```

**Comment by arnaudgiuliani** [comment]
Thanks @dpreussler 

Until now, we didn't have much use cases in this way. Will be fixed in `beta-9` 👍

**Comment by arnaudgiuliani** [comment]
Fixed in `beta-9`
