### ISSUE TITLE
check method should have better name

### ISSUE THREAD

**Issue by dpreussler** [InsertKoinIO/koin#204]
**Is your feature request related to a problem? Please describe.**
it's really hard to import the check method in tests.

Reason: kotlin itself has one 
```
package kotlin
...
public inline fun check
...
```

**Describe the solution you'd like**
rename to `moduleCheck` or `koinCheck`

**Target Koin project**
1.0.0-beta-8

**Comment by arnaudgiuliani** [comment]
fixed in `beta-9`.

Renamed as `checkModules()`
