### ISSUE TITLE
Scope has no source by default

### ISSUE THREAD

**Issue by NyanSten** [InsertKoinIO/koin#2059]
When creating a scope with `T.newScope()`, the scope has no source by default because `T.createScope()`'s `source` defaults to `null` instead of `this`.

https://github.com/InsertKoinIO/koin/blob/main/projects/android/koin-android/src/main/java/org/koin/android/scope/ComponentCallbacksExt.kt#L25

If this is intentional then:
1. This needs to be documented
2. `newScope` needs to be able to pass `source`

**Comment by arnaudgiuliani** [comment]
The initial idea was to not leak the source in the scope. It should be explicit yes.

**Comment by arnaudgiuliani** [comment]
Adding documentation details 👍
