### ISSUE TITLE
check() method overrides logger

### ISSUE THREAD

**Issue by dpreussler** [InsertKoinIO/koin#212]
**Describe the bug**
the new `check` method always logs everything

**To Reproduce**
call `org.koin.test.check()`

**Expected behavior**
should either accept parameter of Logger or use the default static one

**Koin project used and used version (please complete the following information):**
1.0.0-beta-8

**Additional context**
see implementation:
```
fun StandAloneContext.check(list: List<Module>) {
    Koin.logger = PrintLogger(showDebug = true)
    Koin.logger.info("[Sandbox]")
    koinContext =
            KoinContext(InstanceManager(BeanRegistry(), SandboxInstanceFactory(), PathRegistry()), PropertyRegistry())
```

**Comment by arnaudgiuliani** [comment]
fixed in `beta-9`
function `checkModules` as a `logger` parameter.
