### ISSUE TITLE
No compatible definition found for type 'android.content.Context' in Project Module

### ISSUE THREAD

**Issue by luxw** [InsertKoinIO/koin#215]
I have an android application purely in java  and added a pure Kotlin module that uses Koin.
I was using Koin 0.9.7. However, in order to start Koin from the java application I needed Koin-java 1.0.0-beta7. 
Since the two libraries didn't communicate, I also upgraded Koin version inside my module.
I also updated my Koin module definitions but now it seems there's a Android Context mismatch.

Caused by: org.koin.error.BeanInstanceCreationException: Can't create definition 'Factory [class='com.motorola.ttm.location.LocationPickerViewModel', binds~(android.arch.lifecycle.ViewModel)]' due to error :
    		Can't create definition 'Single [class='com.motorola.ttm.location.MapLocationService']' due to error :
    		No compatible definition found for type 'android.content.Context'. Check your module definition

My module definition:

```kotlin 
@JvmField
val locationModule = module {
    // Location Repository
    single { get<LocationDatabase>().locationDao() }
    single { LocationRepository(get()) }
    single { Room.databaseBuilder(get(), LocationDatabase::class.java, "locations.db")
        .fallbackToDestructiveMigration()
        .build()
    }

    // Location Services
    factory { Geocoder(get()) }
    single { MapLocationService(androidContext(), Geocoder(get()), get(), get(), get()) }
    factory { LocationServices.getFusedLocationProviderClient(androidContext()) }
    factory { SettingsClient(androidContext()) }

    // Permissions
    factory { PermissionHelper() }

    // Location
    viewModel { LocationPickerViewModel(get(), get(), get()) }
}```

**Comment by arnaudgiuliani** [comment]
Hello, Did you use the `startKoin()` from koin-android to start?

**Comment by arnaudgiuliani** [comment]
Closing question issue - Please reopen it or post your next question on stackoverflow: https://stackoverflow.com/questions/tagged/koin

**Comment by luxw** [comment]
@arekz-mj I changed how I was starting koin
I was using startKoin from koin-java in my Application class, but it didn't work. So instead of doing this, I decided to use startKoin from koin-android in my module entry points, which is one activity and one service.
