### ISSUE TITLE
Injecting factory functions

### ISSUE THREAD

**Issue by bj0** [InsertKoinIO/koin#216]
# Injecting factory functions

I was trying to figure out how to inject a factory function so I can dynamically create objects on demand, for instance:

    interface Connection {}

    module {
        single<??> { {server -> ConnectionImpl(server) } }
    }

    val function = koinContext.get<??>
    val connection = function(SomeServer)

I can't find anything like this in the documentation.  Most DI frameworks I've used in the past handle function types for this:

    typealias Factory = (Int) -> String

    val myModule = module {
        single<Factory> { {i -> i.toString()} }
    }

But koin seems to see every function as the same class: `kotlin.jvm.functions.Function1`.  So if you have more than one factory, it can't tell the difference between the two:

    typealias Factory = (Int) -> String
    typealias Factory2 = (Int) -> Int

    val myModule = module {
        single<Factory> { {i -> i.toString()} }
        single<Factory2> { {i -> i*2} }
    }

and you get: 

    BeanOverrideException: Try to override definition Single [class='kotlin.jvm.functions.Function1'] with Single [class='kotlin.jvm.functions.Function1'], but override is not allowed. Use 'override' option in your definition or module.

Is there a way to implement this pattern?  In my specific I would like to dynamically create (abstracted) network connection objects based on user input.

**Comment by bj0** [comment]
the string thing was just an example to show what it was doing.  As I mentioned my use case was to generate connection objects.  `factory` doesn't work because that is just called to create an object on injection, I need to create a number of objects based on user input, so I need a generating function that I can call multiple times.

Maybe I can create some sort of type and interface to hold the function, it just seems like a lot of extra abstraction to decouple a constructor.

**Comment by erickok** [comment]
Right. Indeed there is 'overhead' but its very tiny (imho) and due to the restriction of jvm type erase.
```
interface Connection
object ConnectionCreator { fun create(server: Int) = ConnectionImpl(server) }

val myModel = module {
    single { ConnectionCreator }
}
```

Here it is really too bad that Kotlin doesn't do SAM conversion for Kotlin interfaces, or you could have written the much nicer
```
val databaseModel = module {
    single { ConnectionCreator { server -> ConnectionImpl(server) } }
}
```
(which still works, annoyingly, when you write the ConnectionCreator interface in Java)

**Comment by bj0** [comment]
True, and their reason for not supporting SAM on kotlin interfaces is "just use function types"....

**Comment by arnaudgiuliani** [comment]
Closing question issue - Please reopen it or post your next question on stackoverflow: https://stackoverflow.com/questions/tagged/koin
