### ISSUE TITLE
Support nullable injection parameters

### ISSUE THREAD

**Issue by ptrbrynt** [InsertKoinIO/koin#219]
**Is your feature request related to a problem? Please describe.**
Currently I'm not able to include nullable arguments in the `parametersOf` method when using injection parameters.

**Describe the solution you'd like**
I'd like to be able to do so!

**Describe alternatives you've considered**
I'm currently working around the issue by not injecting this particular dependency.

**Target Koin project**
Koin core

**Comment by Dmitry-Borodin** [comment]
should parametersOf() support nullable arguments, or we should have peremetersOrNullOf for them?

**Comment by wojteko22** [comment]
I fixed it: https://github.com/InsertKoinIO/koin/pull/242/files
It should be released in Koin 1.0.2

**Comment by arnaudgiuliani** [comment]
That's it
