### ISSUE TITLE
Memory leak with sharedViewModel and parameter

### ISSUE THREAD

**Issue by rubengees** [InsertKoinIO/koin#220]
**Koin version:** `1.0.0-RC-2`

I experience a memory leak reported by [LeakCanary](https://github.com/square/leakcanary) when using `sharedViewModel` with a parameter.

I have a `ViewModel` like this:

```kt
class MainViewModel(private val someParameter: String) : ViewModel() {

    fun hello() {
    }
}
```

and inject it like this in my `Fragment`:

```kt
private val parameter = "hello"
private val viewModel by sharedViewModel<MainViewModel> { parametersOf(parameter) }
```

My module description is this:

```kt
val mainModules = module {
    viewModel { (someParameter: String) -> MainViewModel(someParameter) }
}
```

`LeakCanary` shows me this leak ([hprof](https://github.com/InsertKoinIO/koin/files/2364155/hprof.zip)):

![screenshot_20180909-124035](https://user-images.githubusercontent.com/8021265/45263671-2fe78f00-b42e-11e8-9ee8-fda3a3309cb5.jpg)

[Here](https://github.com/rubengees/koin-memory-leak) is a minimal Android project for reproduction. Just install the debug variant, open and close the app; the leak will show up.

If you need anything else, please ask.
Thanks for this great library and looking into this!

**Comment by arnaudgiuliani** [comment]
Hello,

just ran your code but didn't trigger any memory leak :/ (Pixel 2, Nexus 5X)
had a background crash on setContent from Activity.

**Comment by arnaudgiuliani** [comment]
(used API 25 & 27)

**Comment by rubengees** [comment]
Hmm, I just tried it again with an API 25 emulator.
I checked out the repository, ran `./gradlew runDebug` and closed the app.
The leak(s) did show up...

**Comment by arnaudgiuliani** [comment]
Got it.

**Comment by arnaudgiuliani** [comment]
Try with `RC-3`

**Comment by rubengees** [comment]
Works perfectly, thanks!
