### ISSUE TITLE
Can't inject BehaviorSubject as Observable

### ISSUE THREAD

**Issue by ukevgen** [InsertKoinIO/koin#222]
So, I have a UseCase (DeletePostUseCase) with Observable and presenter that have a Observer 
Why can help me?
`class HomePresenter(
                    private val postToDeleteObserver: Observer<String>,
                    private val deletePostUseCase: DeletePostUseCase
)`
`class DeletePostUseCase(
                        private val postToDeleteObservable: Observable<String>
)`

And I would like to have one reference for this subject , and  I created the next module 

`val homeFragmentModule = module {

    module(Scope.HOME_FRAGMENT_SCOPE) {
        single("A") { BehaviorSubject.create<String>() }

        factory<Observer<String>> {
            get("A")
        }

        factory<Observable<String>> {
            get("A")
        }

        factory(name = Scope.HOME_FRAGMENT_SCOPE) {
            HomePresenter(get(), get(), get(), BehaviorSubject.create<String>(), get())
        }
        factory(name = Scope.HOME_FRAGMENT_SCOPE) {
            DeletePostUseCase(get(), get(), get(), get())
        }
    }
}`

And my presener injection 
`init {
        scope = getKoin().getOrCreateScope(Scope.HOME_FRAGMENT_SCOPE)
    }

    override val presenter = get<HomeContract.Presenter>()`

And my stack 

`09-11 21:53:40.334 13550-13550/com.moja E/KOIN: [ERROR] - Error while resolving instance for class 'io.reactivex.Observer' - error: org.koin.error.NotVisibleException: Can't proceedResolution 'interface io.reactivex.Observer (Kotlin reflection is not available)' - Definition is not visible from last definition : Factory [name='Presenter',class='com.moja.flow.main.home.HomeContract.Presenter'] 
09-11 21:53:40.335 13550-13550/com.moja E/KOIN: [ERROR] - Error while resolving instance for class 'com.moja.flow.main.home.HomeContract.Presenter' - error: org.koin.error.BeanInstanceCreationException: Can't create definition for 'Factory [name='Presenter',class='com.moja.flow.main.home.HomeContract.Presenter']' due to error :
                                                		Can't proceedResolution 'interface io.reactivex.Observer (Kotlin reflection is not available)' - Definition is not visible from last definition : Factory [name='Presenter',class='com.moja.flow.main.home.HomeContract.Presenter']`

**Comment by arnaudgiuliani** [comment]
Seems your problem come from namespace visibility problem:

``` 
Definition is not visible from last definition : Factory [name='Presenter',class='com.moja.flow.main.home.HomeContract.Presenter']
```

**Comment by ukevgen** [comment]
And... what I do wrong?

**Comment by ukevgen** [comment]
I resolved it 
`val homeFragmentModule = module {

    single { BehaviorSubject.create<String>() }

    factory<Observer<String>> {
        get<BehaviorSubject<String>>()
    }

    factory<Observable<String>> {
        get<BehaviorSubject<String>>()
    }

    factory {
        HomePresenter(get(), get(), get(), get(), get())
    }
    factory {
        DeletePostUseCase(get(), get(), get(), get())
    }
}`
