### ISSUE TITLE
koin-reflect-android?

### ISSUE THREAD

**Issue by Narayane** [InsertKoinIO/koin#223]
https://github.com/InsertKoinIO/koin/blob/master/koin-projects/koin-reflect/src/docs/asciidoc/reflect-api.adoc

Very good first step to reduce Koin "boilerplate code", it will be great to generalize this approach to Android specifics, like viewModel for example :)

Thanks.

**Comment by arnaudgiuliani** [comment]
Will be added to `koin-android-viewmodel` in `1.0.0`.  Use the `org.koin.android.viewmodel.experimental.builder` import.
