### ISSUE TITLE
Replacing top-level dependencies in espresso tests

### ISSUE THREAD

**Issue by zoopolitic** [InsertKoinIO/koin#225]
Espresso tests run different activities, and `Application` class launched only once for all tests. Almost every android application has top level dependencies instantiated once at application level. If we want to replace one of this dependencies in some test - is there any way to put back previous `Definition`'s so next test or test files will use original `Definition` created in `Application`?

**Comment by arnaudgiuliani** [comment]
You can interact in 2 ways with definitions:
- `loadKoinModules()` - load new modules definitions
- `stopKoin()` - close everything from Koin, and allow start/load new ones

**Comment by zoopolitic** [comment]
but `startKoin()` is being called in Application.onCreate() so if I will call `stopKoin` in any test - there is no way to start it again, because Application class is created only ones per all tests

**Comment by arnaudgiuliani** [comment]
Use the `loadKoinModules()` to reload/load new definitions.
