### ISSUE TITLE
'Can't find property SERVER_URL' with onlineWeatherApp modules

### ISSUE THREAD

**Issue by slavipetrov** [InsertKoinIO/koin#227]
**Description**
When I try to use the onlineWeatherApp modules in `MainApplication.kt`, there is an exception 'Can't find property SERVER_URL'.

**To Reproduce**
1. Open `MainApplication.kt`.
2. Replace `startKoin(this, offlineWeatherApp)` with `startKoin(this, onlineWeatherApp)`.
3. In the configurations drop-down select `android-mvvm`.
4. Try to run the project on a device.
5. The app will crash with a long error message, but the key part is this `Can't find property SERVER_URL`.

**Expected behavior**
The project should successfully build when `offlineWeatherApp` is replaced with `onlineWeatherApp` in `MainApplication.kt`.

**Solution**
I was able to achieve a successful build when I replaced `getProperty(SERVER_URL)` (located in `remote_datasource_module.kt` at line `20`) with `SERVER_URL`.

**Koin project used and used version (please complete the following information):**
`koin-android:1.0.0-RC-3`
`koin-android-viewmodel:1.0.0-RC-3`

**Comment by arnaudgiuliani** [comment]
Did you used the `loadKoinProperties` boolean at start?

**Comment by slavipetrov** [comment]
No, I didn't. I've added it and now the project builds without errors. Thank you!

**Comment by alexandru-calinoiu** [comment]
Docs could be improved here, there is no mention of `loadKoinProperties` in here https://insert-koin.io/docs/1.0/documentation/reference/index.html#_loading_properties_at_start
