### ISSUE TITLE
Bean Visibility and Scope

### ISSUE THREAD

**Issue by KolinLoures** [InsertKoinIO/koin#228]
**Describe the bug**
Main thing is that visibility is not restraint against with the scope.

**To Reproduce**
To reproduce this bug:
1. Declare two different implementations with common interface in your koin module
```
val appModule = module {
    scope("UserScope") { UserToaster(androidContext()) as Toaster }
    scope("AnonScope") { AnonToaster(androidContext()) as Toaster }
}
```
2. Start Koin and create scope:
```
startKoin(this, listOf(appModule))
getKoin().getOrCreateScope("AnonScope")
```
3. Try to get **AnonToaster**:
 
`private val toaster: Toaster by inject()`

```
Caused by: org.koin.error.DependencyResolutionException: Multiple definitions found for type 'interface com.example.nkirilov.playground.Toaster (Kotlin reflection is not available)' - Koin can't choose between :
    Scope [name='UserScope',class='com.example.nkirilov.playground.Toaster']
    Scope [name='AnonScope',class='com.example.nkirilov.playground.Toaster']
    Check your modules definition, use inner modules visibility or definition names.
```

**Expected behavior**
Koin will automatically create necessary implementation of Toaster interface depend on what scope was created.

**Koin lib version**
`koin-core version 1.0.0-RC-3`

**Sample project with this problem**
[Problem is here](https://github.com/KolinLoures/TestScopeKoin)

**Comment by arnaudgiuliani** [comment]
Will be fixed in `1.0.0`

you will be able to resolve you `Toaster` by giving which scope to resolve with:

```kotlin
val userScope = koin.createScope("UserScope")
val session = get<Session>(scope = userScope)
```
