### ISSUE TITLE
Use different scopes for one fragment

### ISSUE THREAD

**Issue by ukevgen** [InsertKoinIO/koin#230]
I can't use different scopes for one Fragment,  can I ?
`
09-13 18:32:04.083 31366-31366/com.moja E/KOIN: [ERROR] - Error while resolving instance for class 'com.moja.flow.main.cart.user.ordersubmitted.OrderSubmittedContract.OrderSubmittedPresenter' - error: org.koin.error.DependencyResolutionException: Multiple definitions found for type 'interface com.moja.flow.main.cart.user.ordersubmitted.OrderSubmittedContract$OrderSubmittedPresenter (Kotlin reflection is not available)' - Koin can't choose between :
                                                	Factory [name='OrderSubmittedPresenter',class='com.moja.flow.main.cart.user.ordersubmitted.OrderSubmittedContract.OrderSubmittedPresenter']
                                                	Factory [name='Order_Details_Activity.OrderSubmittedPresenter',class='com.moja.flow.main.cart.user.ordersubmitted.OrderSubmittedContract.OrderSubmittedPresenter', path:'Order_Details_Activity']
                                                	Check your modules definition, use inner modules visibility or definition names.
`

**Comment by RomanKapshuk** [comment]
You can use different scopes for one fragment. 
According to the error, you provide a different implementation of the same OrderSubmittedPresenter interface. Try to use get(name = "name of provided instance") or inner modules visibility (as mentioned in the error)
