### ISSUE TITLE
Create scopes with arguments 

### ISSUE THREAD

**Issue by RomanKapshuk** [InsertKoinIO/koin#231]
How can I create a scope with given arguments? E.g if I want to create a scope in onCreate of Activity, and want to get its scope in fragments on this activity without passing parameters in inject delegate? Maybe something like parent scope mechanism?
```
// In activity something like
getOrCreateScope("myActivity")) { parametersOf(this, 'SomeKeyOrFlagOrElse') }
```

```
// in module
scope("myActivity") {
it.getScopeParam<AppCompatActivity>()
}

scope("fragmentScope") {
SomeObjectDependsOnActivity(activity = get())
}

```

```
// in fragment 
getOrCreateScope("fragmentScope", parent = getScope("myActivity"))

```

**Comment by Tapchicoma** [comment]
I am also interested in this feature. This will allow to provide scope configuration that will be used in lifetime of scope.

**Comment by 0xcaff** [comment]
This could be really useful when using koin in android services.

**Comment by 0xcaff** [comment]
I think this could be accomplished with the injection parameters feature.

**Comment by arnaudgiuliani** [comment]
interesting proposal 👍

**Comment by arnaudgiuliani** [comment]
To give an answer of the next proposal, Scope instances will have `properties`. this is hashmap key/values to help you embed anything

**Comment by arnaudgiuliani** [comment]
you will be able also to use directly scope properties from DSL in functions. Injection param for Scope set definition is not applicable here.

**Comment by moizalidv** [comment]
Hey for anyone still struggling with it, I found myself passing activity as an argument. My Fragment failed to initialize as I was not using lazy operator. 
val myScope = getKoin().getOrCreateScope(
        "sessionID", named("Hello")
    )
Previous one:
    val viewModel: MyViewModel =
        myScope.getScope("sessionID").get { parametersOf(requireActivity()) }

The one which passed:

val viewModel: MyViewModel by lazy {
        myScope.get<TransactionDetailViewModel> { parametersOf(requireActivity()) }
    }
