### ISSUE TITLE
Multiple scope instances of the same type.

### ISSUE THREAD

**Issue by aartikov** [InsertKoinIO/koin#234]
It would be nice to be able to create multiple scope instances of the same type.
For example, to make per-request scope, where each request has its own context.

```
module {
    scope("request") { RequestContext() }
}

val request1 = getKoin().createScope("request")
val request2 = getKoin().createScope("request")

val context1 = get<RequestContext>(scope = request1)
val context2 = get<RequestContext>(scope = request2)
```

**Comment by arnaudgiuliani** [comment]
included in koin 2.0. You can create multiple instance of the same scope.
