### ISSUE TITLE
`toString()` called on scope's instances

### ISSUE THREAD

**Issue by AlexSviridov** [InsertKoinIO/koin#240]
Implicit call `toString()` occurs for dependencies in all scopes (https://github.com/InsertKoinIO/koin/blob/master/koin-projects/koin-core/src/main/kotlin/org/koin/core/instance/ScopeInstanceHolder.kt#L26).

This behavior adds problems in using service interfaces of https://square.github.io/retrofit/, https://github.com/Tinder/Scarlet or similar (dependency throws corresponding exception).
 
Expected behavior: DI does't call any methods of dependencies.

Module: koin-core version 1.0.0

**Comment by arnaudgiuliani** [comment]
Fixed in `1.0.2`
