### ISSUE TITLE
merge inject and declareMock

### ISSUE THREAD

**Issue by dpreussler** [InsertKoinIO/koin#243]
**Is your feature request related to a problem? Please describe.**
I don't like that declareMock is separate from the definition of the mock.
I normally try to do both in one call since Kotlin makes it so easy:

```
  val useCase = mock<LeaguesUseCase>().apply {
        whenever(getTeams()).thenReturn(Single.just(emptyList()))
    }
```
it' even better with Kotlin-Mockito:
```
  val useCase = mock<LeaguesUseCase> {
        on{ getTeams() } doReturn Single.just(emptyList())
    }
```

**Describe the solution you'd like**
My idea would be sth similar to that approach. 

```
inline fun <reified T: Any> KoinTest.mock(
    name: String = "",
    noinline parameters: ParameterDefinition = emptyParameterDefinition(),
    crossinline stubbing: T.() -> Unit = {}
) = lazy {
    declareMock<T>()
    getKoin().get<T>(name, parameters).also {
        stubbing(it)
    }
}
```
This function combines the code from `inject`, `delareMock` and the stubbing
usage:
```
val useCase: LeaguesUseCase by mock {
        whenever(getTeams()) doReturn Single.just(emptyList())
    }
```
I believe this would look much nicer.

2nd part:

As we use Kotlin Mockito, as shown above, I would rather have a version for that.
Would look similar:
```
inline fun <reified T: Any> KoinTest.mock(
    name: String = "",
    noinline parameters: ParameterDefinition = emptyParameterDefinition(),
    crossinline stubbing: KStubbing<T>.(T) -> Unit = {}
) = lazy {
    declareMock<T>()
    getKoin().get<T>(name, parameters).also {
        KStubbing(it).stubbing(it)
    }
}
```

usage:
```
val useCase: LeaguesUseCase by mock {
        on {getTeams()} doReturn Single.just(emptyList())
    }
```
I understand you don't want to add Kotlin Mockito as a dependency. Maybe you have an idea how to combine both? Or in addition of the first version have one similar to on{} of Kotlin mockito. Its not complex, just needs to return `OngoingStubbing` from Mockito

**Target Koin project**
koin-test

**Comment by arnaudgiuliani** [comment]
This feature is very interesting but a bit problematic because a lazy property won't be triggered at start. And if we want to predeclare mocks, we will have problems with overrides from the original and other stuff like that (because you predeclare a mock, and you load your original config).

A first approach is to extend the declareMock like that:

```kotlin
class CoffeeMakerTest : AutoCloseKoinTest() {

    val coffeeMaker: CoffeeMaker by inject()
    val heater: Heater by inject()

    @Before
    fun before() {
        startKoin(listOf(coffeeAppModule))
        declareMock<Heater> {
            given(isHot()).will { true }
        }
    }

    @After
    fun after() {
        stopKoin()
    }

    @Test
    fun testHeaterIsTurnedOnAndThenOff() {
        coffeeMaker.brew()

        verify(heater, times(1)).on()
        verify(heater, times(1)).off()
    }
}
```

**Comment by dpreussler** [comment]
understand but we still can pass the stubbing to declare mock right?
