### ISSUE TITLE
Cannot create two scopes with the same name

### ISSUE THREAD

**Issue by Buckstabue** [InsertKoinIO/koin#260]
I'm creating a new project and want to configure my dependencies with at least 3 module-scopes App -> UserSession -> Screen. The problem is that when my screen is used twice in a backstack, I get an error 
`Already created scope with id 'UserProfileScreen'`
How do I solve that?

**Comment by Tapchicoma** [comment]
I am somewhat having similar case:
- module defines scope with name for particular flow
- first android activity uses this flow, creates scope in `onStart()` and closes it in `onDestroy()`
- second android activity that can be started after first is also using the same flow, also creating the same scope.
As transitioning between activites is async - second activity `onCreate()` is called before first activity `onDestroy()` - leading to provide exception.

Possible solution is have `createScope(name: String, class: KClass)`, that will create scope only related to passed class.

**Comment by Tapchicoma** [comment]
Possibly related to #235

**Comment by Buckstabue** [comment]
@Tapchicoma it is a similar issue, but the solution you proposed will not fix this. Because if some activity(say UserProfileActivity) appears in a backstack twice, it will still crash. Probably it would be better to define scopes  by module name and creating a new scope would lead to creating a new separated hashmap of decencies of the module
It is probably related to  #248

**Comment by zoopolitic** [comment]
@Buckstabue agree, because currently `ScopeRegistry` contains HashMap<String,Scope> so there is no way to provide several scopes from the same module. I ended up creating modules at runtime with unique scopeId and loading them with `loadKoinModules(override=true`) but it breaks tests because now my fragment loads modules

**Comment by Tapchicoma** [comment]
It was just a quick possible solutions out of my head. We can iterate on possible improvements/solutions in the linked ticket.

**Comment by Buckstabue** [comment]
The problem is still reproducible in 1.0.2.

**Comment by arnaudgiuliani** [comment]
Sure. The `detachScope` feature will bring the possibility to create several scope of the same id.
