### ISSUE TITLE
Error returning to parent activity class='android.content.Context'

### ISSUE THREAD

**Issue by georgesxi** [InsertKoinIO/koin#265]
Hello, 

I am new to Koin and I have defined my module as follows : 

```
val apiModule = module (override=true)  {
    single <ApiService> {ApiService.create() }
}

 val activityModule = module (override=true) {

         single { SomeActivity() }
     single { SomeActivityViewModel(ApiService.create()) }
  }
```

In my Activity I initiate Koin like this:
`val presenter: SomeActivityViewModel by inject()`

and inside my onCreate method:
` startKoin(this, listOf(apiModule, activityModule ))`

The app stars normally when run but when I try to apply changes or if I enter another activity and return to my main activity I get the following error:

> Caused by: org.koin.error.BeanOverrideException: Try to override definition with Single [class='android.content.Context'], but override is not allowed. Use 'override' option in your definition or module.

Even with the override option in my module I am still getting this...any idea what I am doing wrong?
If more code is needed just let me know.

**Comment by arnaudgiuliani** [comment]
You're doing something else that try to declare `Context` definition. `startKoin()` help to declare `Context` & `Application` instances.

**Comment by georgesxi** [comment]
Sorry it's not clear to me what you mean but I tried this approach and it works now:
1) I created an application class and started Koin from there  ->
`class MyClass : Application() {
     override fun onCreate() {
        super.onCreate()
             startKoin(this, listOf(
                appModule,
                apiModule
                ))    } }`
2) Declared this class to my manifest under application 
` <application
        android:name="com.example.application.MyClass"
<activity android:name="com.example.application.MyActivity  </activity>
</application>`
3) removed startKoin() from my initial activity.

Thanks!
