### ISSUE TITLE
I am having a problem when using viewmodel

### ISSUE THREAD

**Issue by UCodeUStory** [InsertKoinIO/koin#266]
hi.
 I use koin version 1.0.1. I met a problem

e: Caused by: java.lang.IllegalStateException: Can't getByClass ViewModel 'class com.ustory.relax_business_component.login.viewmodel.LoginViewModel (Kotlin reflection is not available)' on com.ustory.relax_business_component.login.view.LoginActivity@bf8036d - Is not a FragmentActivity nor a Fragment neither a valid ViewModelStoreOwner

please help me ,Thank you

**Comment by arnaudgiuliani** [comment]
What is exactly your `LoginViewModel` class? How do you call viewModel feature?
Do you have a sample?

**Comment by UCodeUStory** [comment]
I found the cause of the problem. it is appcompat V7 26 version of bug. I have push a request

**Comment by arnaudgiuliani** [comment]
Ok, I saw your PR about it 👍

**Comment by arnaudgiuliani** [comment]
Let's go with it: https://github.com/InsertKoinIO/koin/pull/268

**Comment by UCodeUStory** [comment]
Please you merge, I don't have permission; could I join the contributor, I really appreciate your project.Looking forward to joining
