### ISSUE TITLE
Use Koin injection inside Spek tests

### ISSUE THREAD

**Issue by AHarazim** [InsertKoinIO/koin#269]
Hey,
I'm relative new in the topic of DI and I started to use koin with android development. I also want to write test with the Spek framework because I like the idea to write tests in BDD-Style. 
I'm asking my self how I can inject something inside a Spek class? Or is it even possible to inject stuff inside tests without using koin-test?

**Comment by arnaudgiuliani** [comment]
You can just use the `koin-core` package to have the `KoinComponent` interface tag & `startKoin()` function. The `koin-test` will add you `declareMock` & `checkModules` functions.

**Comment by AHarazim** [comment]
@arnaudgiuliani Works! Thx a lot!

**Comment by miyuki-onuma** [comment]
@arnaudgiuliani @AHarazim 
Hey,
How I can inject object inside a Spek Test class?

**Comment by apontini** [comment]
I had the same issue and I came up with this:
```
internal class UserServiceTest : Spek({
    object : KoinTest {
        operator fun invoke() {
            startKoin {
                modules(
                    module {
                        single { mockk<UserRepository>() }
                    }
                )
            }

            val repository: UserRepository by inject<UserRepository>()

            describe("User creation") {
                context("Normal execution") {
                    it("saves the user to the repository") {
                        //Do something
                    }
                }

                context("The email already exists") {
                    it("throws an IllegalArgumentException") {
                        //do something
                    }
                }
            }
        }
    }()
})
```
I simply declare an anonymous class, I override its invoke operator and then i invoke it. It's not the most elegant thing in this world though.
