### ISSUE TITLE
Koin ParameterList.get() with type inference

### ISSUE THREAD

**Issue by gorbuvla** [InsertKoinIO/koin#270]
I have a smaller feature reuqest related to dynamic parameter injection

right now, to get my parameter from `ParameterList` i have to do something like this

``` viewModel { params -> AppFeatureViewModel(feature = params.get<OnboardingFeature>() as OnboardingFeature) } ```

wouldn't it be better for `.get()` from ``ParameterList` to look like following:

``` inline fun <reified T> get() = values.first { it is T } as T ```

?

as of version 1.0.1 ``` as T ``` at the end is missing and T can't be inferred

**Comment by arnaudgiuliani** [comment]
The main usage suggested is to use `destructured` declaration from Kotlin.
`(p1,p2) -> MyComponent(p1,p2)`
