### ISSUE TITLE
Allow to declare Android ViewModel by its interface

### ISSUE THREAD

**Issue by mzgreen** [InsertKoinIO/koin#276]
Assuming I have a `ViewModel` class like this:

`class FooViewModel : ViewModel(), FooViewModelInterface`

I would like to be able to inject it like this:

`val myViewModel: FooViewModelInterface by viewModel()`

Right now it's not possible because DSL expects a `ViewModel` type.

**Comment by fredy-mederos** [comment]
The problem is that ViewModelProviders only work with ViewModel subclasses so you need to pass a valid subclase.

Check out the ViewModelProvider get function:
```java
/**
     * Returns an existing ViewModel or creates a new one in the scope (usually, a fragment or
     * an activity), associated with this {@code ViewModelProvider}.
     * <p>
     * The created ViewModel is associated with the given scope and will be retained
     * as long as the scope is alive (e.g. if it is an activity, until it is
     * finished or process is killed).
     *
     * @param modelClass The class of the ViewModel to create an instance of it if it is not
     *                   present.
     * @param <T>        The type parameter for the ViewModel.
     * @return A ViewModel that is an instance of the given type {@code T}.
     */
    @NonNull
    @MainThread
    public <T extends ViewModel> T get(@NonNull Class<T> modelClass) {.....}
```

**Comment by arnaudgiuliani** [comment]
Hello, the Android Architecture ViewModelFactory don't allow us to ask ViewModel by a class that is not a `ViewModel`.  To help you, it would heavily complexify the use of viewModel() injection.

Sorry.
