### ISSUE TITLE
How can I get Android ViewModel in Java code?

### ISSUE THREAD

**Issue by yisiang** [InsertKoinIO/koin#278]
**I know in Kotin code**
```java
class UserProfileActivity : AppCompatActivity() {
    private val viewModel: UserProfileViewModel by viewModel()
}
```
**But how would I code it in Java?**
```java
public class UserProfileActivity extends AppCompatActivity() {
    private UserProfileViewModel viewModel ...
}
```

**Comment by gvsharma** [comment]
ViewModelProviders.of(this).get(UserProfileViewModel.class);

this should work..?

**Comment by arnaudgiuliani** [comment]
Extension function can be used by KoinComponent, from `koin-android-viewmodel` but complex to add it to `koin-java` :/

**Comment by China77** [comment]
private UserProfileViewModel viewModel = get(UserProfileViewModel.class);
