### ISSUE TITLE
Should I use module path or scope?

### ISSUE THREAD

**Issue by CyberRay** [InsertKoinIO/koin#279]
Let's say I have an Activity and a Fragment(contains in Activity's layout). both of them hold an injected instance of DummyClass, and the fragment would like to access activity's instance of DummyClass. So I do the following

```
class ParentActivity:Activity() {
    val SCOPE_NAME = this::class.java.canonicalName + hashCode()
    val mCurrentScope: Scope
    val TAG = "[ParentActivityScope]"
    val dummyClass:DummyClass by inject(scope = mCurrentScope)

    init {
        loadKoinModules(getModule())
        mCurrentScope = getCurrentScope()
    }

    fun getCurrentScope(): Scope {
        return getOrCreateScope(SCOPE_NAME)
    }

    override fun getModule(): Module {
        Log.d(TAG, "create module of activity: $SCOPE_NAME" )
        return module {
            scope(SCOPE_NAME) {
                DummyClass()
            }
        }
    }

    class DummyClass

    override fun onCreate(savedInstanceState: Bundle?) {
        Log.d(TAG, "ActivityScope: ${mCurrentScope.id}" )

        super.onCreate(savedInstanceState)
        Log.d(TAG, "dummyClass: ${dummyClass}")
    }
}
```
```
class ChildBFragment:Fragment() {
    val SCOPE_NAME = this::class.java.canonicalName + hashCode()
    val mCurrentScope:Scope
    var mParentScope:Scope? = null
    var mParentScopeName:String? = null

    val parentDummyClass: ParentActivity.DummyClass by inject(scope = mParentScope)
    val childDummyClass: ParentActivity.DummyClass by inject(scope = mCurrentScope)

    init {
        loadKoinModules(getModule())
        mCurrentScope = getOrCreateScope(SCOPE_NAME)
    }

    override fun onAttach(context: Context) {
        super.onAttach(context)
        mParentScopeName = (context as BaseActivity).SCOPE_NAME
        mParentScope = getOrCreateScope(context.SCOPE_NAME)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        textview_caption.text = "parentDummyClass: ${parentDummyClass.toString()} childDummyClass: ${childDummyClass}"
    }

    override fun getLayoutId(): Int {
        return R.layout.fragment_child
    }


    override fun getModule(): Module {
        return module {
            scope(SCOPE_NAME) {
                ParentActivity.DummyClass()
            }
        }
    }

}
```
 But it happens to KOIN throws exception at Fragment#onViewCreated line 2
>Koin can't choose between 
>Scope [name='DummyClass',class='xxx.playground.ParentActivity.DummyClass']
>Scope [name='DummyClass',class='xxx.playground.ParentActivity.DummyClass']

The childDummyClass is okay, but KOIN cannot determine which the parentDummyClass instance is

what am I doing wrong? isn't this what scopes are made for?

**Comment by arnaudgiuliani** [comment]
Why not a shared ViewModel instance? Else best is to use a scope based on your Activity's lifecycle.

**Comment by CyberRay** [comment]
> Why not a shared ViewModel instance? Else best is to use a scope based on your Activity's lifecycle.

Actually, what I do is using a scope based on activity life cycle.
 
After tracing the error all day long, I found that ```inject<T>(scope = SomeScope)``` tries to find `T` in  `scope` beans if `SomeScope` wasn't determined yet. That is why the error `Koin can't choose between...` comes out .

But should It be some error like `no bean definition can be found `?  
Why should a scoped bean be treated as a global bean

**Comment by arnaudgiuliani** [comment]
The Koin registry keeps references for all definitions and instances allocation. If the Scope is not created, you should have `NoScopeException` or `ClosedScopeException`.

**Comment by CyberRay** [comment]
Thats is not what I mean.
> var mParentScope:Scope? = null
>var mParentScopeName:String? = null
>val parentDummyClass: ParentActivity.DummyClass by inject(scope = mParentScope)
>val childDummyClass: ParentActivity.DummyClass by inject(scope = mCurrentScope)


`mCurrentScope` refers to fragment scope which looks like Scope[id = ChildBFragmentXXXX}]
`mParentScope` refers to  activity scope which looks like Scope[id = "ParentActivityXXXXX"]
Both scopes are created at `init {}`
But `mParentScope` will not be assigned until ChildFragment is attached to ParentActivity

and because of that, the following line 
>val parentDummyClass: ParentActivity.DummyClass by inject(scope = mParentScope)

actually runs like
>val parentDummyClass: ParentActivity.DummyClass by inject(null) 

And I think it should at least return a `no bean definition found`, because DummyClass is only declared in scopes
