### ISSUE TITLE
How can I use several scopes simultaneously ?

### ISSUE THREAD

**Issue by AndZp** [InsertKoinIO/koin#280]
Hi, I have two questions, but I think they are related to each other:

1)  I have a scope (gameSession in my case) that bind to Fragment lifecycle. One fragment (with inner fragments and shared elements, handlers and controllers) - one game session and everything works great. 
 Now I need to use the same fragment class a several time in Fragment Pager and each fragment should control his scope.  Any advice ? Can I use some dynamic ID for scope Id ?

2) If I bind Scope to Activity lifecycle - it can cause problem in case if we open-close-open-close activity a couple of time (especially when UI thread is busy). I paid attention that scope closing is happened together with activity on Destroy - which can be called with delay (In my test with have webP animations - it takes up to 5 seconds !!!) . In this case app got crashed.   
I succeed to fix it by controlling the scope by myself and closing it manually in onPause method: 

```
override fun onPause() {
        super.onPause()
        if (isFinishing)  {        
            myScope.close()
        }
    }
```

**Comment by zoopolitic** [comment]
possible duplicate https://github.com/InsertKoinIO/koin/issues/260
