### ISSUE TITLE
Can we inject ViewModel Interfaces na

### ISSUE THREAD

**Issue by alexandru-calinoiu** [InsertKoinIO/koin#288]
**Is your feature request related to a problem? Please describe.**
I don't want to inject the ViewModel implementations in my Activity/Fragment

**Describe the solution you'd like**
Inject interfaces for my ViewModel

**Describe alternatives you've considered**
So far my solution look like this

I will have an interface for my viewModel:

```kotlin
    interface ViewModel {
        val events: LiveData<ViewModelEvent>

        fun getLastWeather()
    }
```

I will have my ViewModel inherit the interface and livecycle.ViewModel:

```kotlin
class SplashViewModel : ViewModel(), SplashContract.ViewModel {

    override val events = SingleLiveEvent<ViewModelEvent>()

    override fun getLastWeather() {
    }
}
```

I will register my ViewModel like usual:

```kotlin
val weatherAppModule = module {
    viewModel { SplashViewModel(get(), get()) }
}
```

And use it in the Activity via this line:

```kotlin
    private val splashViewModel: SplashContract.ViewModel by viewModelByClass(SplashViewModel::class)
```

**Target Koin project**
not sure

**Comment by Linus-Weiss** [comment]
Any updates on this? Thanks!

**Comment by CeH9** [comment]
```kotlin
viewModel { FooBarImpl() as FooBar }
```

**Comment by erickok** [comment]
@alexandru-calinoiu It looks like you ar enot using the Android `ViewModel` but instead define your own interface. In that case you don't need the `viewModel {}` definitions at all - a simple `factory {}` suffices. You inject them with `by inject()`.

**Comment by liminal** [comment]
You can't use an interface for `viewModel` since unfortunately the base `ViewModel` is an abstract class and the `ViewModelProvider.Factory` methods require the provided viewmodel inherits from `ViewModel`. 

But you can achieve the separation of interface and implementation by making the interface an abstract class instead.

```kotlin
// "interface"
abstract class FooViewModel {
    abstract val events: LiveData<ViewModelEvent>

    abstract fun getLastWeather()
}

// implementation
class FooViewModelImpl : FooViewModel() {
    override val events = SingleLiveEvent<ViewModelEvent>()

    override fun getLastWeather() {
    }
}

```
and then 

    viewModel<FooViewModel> { FooViewModelImpl() }
   
That is probably the closest you will get without some hacky workarounds

**Comment by arnaudgiuliani** [comment]
this last message is the best way to do that IMO

**Comment by nijat-ahmadli** [comment]
I found a way to do this, by overriding Koin extension functions. Please check my [stackoverflow answer](https://stackoverflow.com/a/60783118/3873867). Although I think abstract class is the way to go.
