### ISSUE TITLE
Scope.close() always references StandAloneContext

### ISSUE THREAD

**Issue by stanleyguevara** [InsertKoinIO/koin#290]
**Describe the bug**
Seems like there's an issue/bug when using dedicated Koin instance (introduced in 1.0.2 https://github.com/InsertKoinIO/koin/issues/224) along with `Scope`, stemming from a fact that `Scope.close()` under the hood has hardcoded `StandAloneContext`

**To Reproduce**
```
val myKoinKontext  = Koin.create().loadModules(listOf(getModules())).koinContext
val scope = myKoinKontext.createScope("mySession")
scope.close()
```
will throw
```
java.lang.IllegalStateException: StandAloneContext Koin instance is null
```
because `Scope.close()`
```
fun close() {
   val koin = StandAloneContext.getKoin()
   removeInstanceHolders(koin)
   removeAddedDefinitions(koin)
   removeScope(koin)
}
```
Not really sure if it's a bug or I'm not grasping something about how `Scope` works. As far as I understand the `StandAloneContext` is the singleton-default-entity that we're trying to avoid with solution introduced in 1.0.2 and described in https://github.com/InsertKoinIO/koin/issues/224

**Expected behavior**
`scope` is closed without exception

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core version 1.0.2`

**Additional moduleDefinition**
Irrelevant

**Comment by arnaudgiuliani** [comment]
please check for Koin 2.0 Scope API
