### ISSUE TITLE
Clear dependencies before scope closes

### ISSUE THREAD

**Issue by scraplesh** [InsertKoinIO/koin#299]
I need to dispose some objects before scope closed. I wanted to use `ScopeCallback` for that, but it works after scope is closed and all dependencies are cleared.

As a temporary solution I created an alternative version of `bindScope` function that takes as the last parameter a callback and invokes this callback before `scope.close()`.

**Comment by arnaudgiuliani** [comment]
You mean, be able to be notified with the Android lifecycle?

**Comment by scraplesh** [comment]
I use it on Android, but my question is - can i get access to dependencies before scope closes, not after as it in the `ScopeCallback`?

**Comment by arnaudgiuliani** [comment]
added ScopeCallback interface in beta-2
