### ISSUE TITLE
Different instances for same Scope but different ParameterList

### ISSUE THREAD

**Issue by DimaSkopiuk** [InsertKoinIO/koin#301]
I use `Scope` to create database instances for every user login cycle.
I need few database instances depends on name (`name` is parameter I use for injecting):

Module:
```Kotlin
scope(SIGNED_IN) { (databaseName: String) -> Database(databaseName) }
```

Test:
```Kotlin
getKoin().createScope(SIGNED_IN)
val database1 = get<Database> { parametersOf("local") }
val database2 = get<Database> { parametersOf("remote") }
assertNotEquals(database1, database2)
```

This test fails because I always receive same database instance (that was created with `local` parameter in current case).

I even can create second database without parameters at all and it will work without errors:
```Kotlin
val database1 = get<Database> { parametersOf("abc") }
val database2 = get<Database>()
```

Expected: 
Single scoped instance for unique `ParameterList`.
Different scoped instances for different `ParameterList`s.

**Koin project used and used version:**
`koin-android`: `1.0.1` and `1.0.2`

**Comment by arnaudgiuliani** [comment]
please check the Scope API from Koin 2.0
