### ISSUE TITLE
Single instance destroyed after activity is killed in the background

### ISSUE THREAD

**Issue by josephbnb** [InsertKoinIO/koin#302]
**Description:**
I have a class `GlobalProvider` declared as `single` which contains a `wallet` that I use all across the app. This `wallet` needs a long time to be loaded, so I am loading it only once, in the splash activity.

`
module {
    single { GlobalProvider() }
}`
`class GlobalProvider {
    private var wallet: Wallet? = null
}
`

Sometimes when the user returns to the app from the background, the `GlobalProvider` instance is being killed and re-initialised, with a null `wallet` of course. At the moment I am forced to check if `wallet` is null when any of my activities is started, and if that is the case, restart the app so it can be loaded again.

Is there any way to tell Koin to preserve this `GlobalProvider` no matter what? Or is there any other way to achieve what I'm trying to do using Koin?

**Steps to reproduce:**
1. Put the app in the background.
2. Open the settings and manually turn off a permission granted for this app.
3. Open the app again.

OR

1. Put the app in the background.
2. Go to developer options and set "Background process limit" to "No Background Processes".
3. Open the app again.

**Version 1.0.2**

**Comment by arnaudgiuliani** [comment]
You can use the Scope API to define a component with a limited lifetime duration - https://insert-koin.io/docs/1.0/documentation/koin-core/index.html#_using_scopes

You can also bind a scope to an Android lifecycle component: https://insert-koin.io/docs/1.0/documentation/reference/index.html#_scope_features_for_android

**Comment by HanvSolo** [comment]
Hello, I`m not sure, but it seems like @josephbnb meants something else than scopes. I have the same problem with single (when activity recreates, my single class AppData become empty again like it was on a start of app)
Is there any possibilty to make it live for whole app life?
