### ISSUE TITLE
Koin 2.0.0 - ParameterList with more than 5 parameters

### ISSUE THREAD

**Issue by rubengees** [InsertKoinIO/koin#303]
Koin version: `2.0.0-alpha-2`

I have a complex `ViewModel` which requires 11 parameters. In versions before 2.0.0, this was possible by creating a `ParameterList` as usual and then accessing the parameters with the `get(position)` method:

```kt
viewModel { parameterList ->
    SomeViewModel(
        parameterList[0], parameterList[1], parameterList[2], parameterList[3], 
        parameterList[4], parameterList[5], parameterList[6], parameterList[7], 
        parameterList[8], parameterList[9], parameterList[10]
    )
}
```

In Koin 2.0.0, there is now a defensive check, to prevent usage of the new `ParameterHolder` with more than 5 parameters. Of course i could have a wrapping object for my parameters, but the old behaviour was way more practial in my specific case (I could declare the parameters directly in the constructor of my `ViewModel` and did not have to add additional setters). Is there the possibility to get the old behaviour back or to at least increase the amount of allowed parameters?

**Comment by arnaudgiuliani** [comment]
5 params at maximum

**Comment by rubengees** [comment]
Why? A reasoning would be nice.

**Comment by rubengees** [comment]
Good points, thanks for the explanation!

**Comment by mslagle-gd** [comment]
@arnaudgiuliani, 5 is the number of component functions included (which is totally fine, you guys have to cutoff somewhere), but is there a reason for adding the check and throwing a runtime exception? I needed 7 params, so I added 2 more component functions (via kotlin extension).

```
operator fun <T> DefinitionParameters.component6(): T = get(5)
operator fun <T> DefinitionParameters.component7(): T = get(6)
```

If the compiler will catch that you have more parameters than component functions, and the destructuring will scale with the number of component functions you add on, could we remove the runtime error and allow expansion of this via extensions?

**Comment by mslagle-gd** [comment]
I will gladly submit a PR for this if it would actually be merged

**Comment by mslagle-gd** [comment]
In the meantime for anyone who comes here looking for a solution, here is what I am doing. Hopefully they can remove the manual so we can just add the extension functions I talked about above.

*Add a file _MultiParameter.kt_ with this in it:*

```
@Suppress("UNCHECKED_CAST")
class MultiParameter(vararg val parameters: Any?) {
    operator fun <T> component1(): T = get(0)
    operator fun <T> component2(): T = get(1)
    operator fun <T> component3(): T = get(2)
    operator fun <T> component4(): T = get(3)
    operator fun <T> component5(): T = get(4)
    operator fun <T> component6(): T = get(5)
    operator fun <T> component7(): T = get(6)
    // Add more component functions as needed here

    operator fun <T> get(i: Int) = parameters[i] as T

    inline fun <reified T> get() = parameters.first { it is T }
}

fun multiParametersOf(vararg parameters: Any?) = parametersOf(MultiParameter(*parameters))
```

*Usage in module:*
```
// be sure to destructure the MultiParameter here
viewModel { (parameters: MultiParameter) ->
        val (
            firstValue: Int,
            secondValue: () -> Unit,
            thirdValue: Boolean,
            ...
            nValue: YourClass,
        ) = parameters

        YourViewModel(
            firstValue,
            secondValue,
            thirdValue,
            ...
            nValue,
        )
    }
```

**Comment by mslagle-gd** [comment]
@rubengees I'm sure you have moved on, but I have a way around this^

**Comment by rubengees** [comment]
@mslagle-gd Thnaks! I'm currently using a different hack to get around this, but this one looks good, too.
