### ISSUE TITLE
KoinTest.checkModules skips module definitions with parameters

### ISSUE THREAD

**Issue by ncipollo** [InsertKoinIO/koin#304]
**Describe the bug**
If a module definition contains a parameter it will not be verified by `KoinTest.checkModules` (in most cases). Here's what seems to be happening:
1. Depending upon how the parameter is accessed, a `NoParameterFoundException`, a `NoSuchElementException`, or a `IndexOutOfBoundsException` is thrown.
2. This exception is caught and logged in `SandboxInstanceHolder.create`.
3. We jump up the call stack before verifying the actual module definition.

Here is a unit test which demonstrates the issue:
https://github.com/ncipollo/koin/blob/97f5c74d32187e4f264e002951e756dcad5843ed/koin-projects/koin-test/src/test/kotlin/org/koin/test/module/CheckModulesTest.kt#L143

**To Reproduce**
Run the unit test found here: https://github.com/ncipollo/koin/blob/97f5c74d32187e4f264e002951e756dcad5843ed/koin-projects/koin-test/src/test/kotlin/org/koin/test/module/CheckModulesTest.kt#L143

**Expected behavior**
The parameters list ideally won't throw an exception in this case and we can properly validate the module definition. We could maybe mock the parameter list and have it return a mock for any type requested?

**Comment by ncipollo** [comment]
I think we can resolve this issue by passing in a mock of ParameterList instead of an empty one. The mock can return a mock of the request object type.

**Comment by arnaudgiuliani** [comment]
as @erickok clearly say, `checkModules()` is here to check if your definitions are calling already defined definitions. We have to skip the parameters part, as we should provide any sample of parameters for each definition which is a good solution also.

A fix here is to trap this kind of error and hide it for you, to avoid any suspicion.

No problem if you want to propose an alternative to `checkModules()` if you have a good idea :)

**Comment by erickok** [comment]
We do not use the `koin-test` project (among other things, we don't want the mockito dependency). Instead, we have a test like this:
```
    private fun checkModules(modules: List<Module>, parameterCreators: Map<KClass<*>, ParametersDefinition>) {

        // Start Koin, testing module definitions for loops and duplicates
        val koin = startKoin {
            modules(modules)
            logger(level = Level.DEBUG)
        }

        // Try to acquire every dependency
        koin.koin.beanRegistry.getAllDefinitions().forEach {
            val scope = if (it.isScoped()) koin.koin.createScope(it.getScopeName()!!, it.getScopeName()) else null
            koin.koin.get<Any>(it.primaryType, it.name, scope, parameterCreators[it.primaryType])
            scope?.close()
        }
    }
```
which is called somewhat as such:
```
        val overrides = module(override = true) {
            // Android Context is stubbed in JVM tests
            single { context }
            single { application }
            // ... other mocks of dependencies that need Android APIs
          }

        // Factories for definitions that require parameter injection
        val parameterCreators = mapOf<KClass<*>, ParametersDefinition>(
                SomePresenterWithParameters::class to { parametersOf("some", "parameters") },
                SomeOtherPresenterWithParameters::class to { parametersOf(false) }
        )

        checkModules(realModules + overrides, parameterCreators)
```

Happy to make a PR if you dig this approach.

**Comment by ncipollo** [comment]
Hey @erickok,
Yeah I think an approach like that would work (though we probably need to factor in the optional dependency name as well).

**Comment by ncipollo** [comment]
Hey @arnaudgiuliani,
I just want to make sure I've clearly described the issue (sorry for the noise!). I understand and agree with the use case for `checkModules`. The problem is that it is skipping over modules which rely upon parameters. So If I have messed up the non-parameter dependencies it will not catch that. Effectively any module which contains a parameter will not be verified by checkModules.

**Comment by arnaudgiuliani** [comment]
@erickok interesting also, as your solution does not need mocked sandboxing. Your  `parameterCreators` is interesting and could be even more lighter.

You can open a PR @erickok

**Comment by ncipollo** [comment]
Awesome, thanks for taking a stab at that @erickok! 
One thing I wanted to note is we may want to also consider the optional dependency name when mapping to a parameter creator. In our project we use that a fair bit to disambiguate interfaces we are providing.

**Comment by erickok** [comment]
@ncipollo So you have dependencies that are named _and_ have parameters? Yes, we'd ideally deal with that. I'll give it a try today.

**Comment by ncipollo** [comment]
Yep, exactly. We have a view level interface in our app which can take in android components we don't want in the dependency graph.

Thanks for taking a look, you rock!

**Comment by erickok** [comment]
I pushed in my fork an example of how this would work: https://github.com/erickok/koin/blob/9e04626c791ba3e17639865763f90b56f416d1e1/koin-projects/koin-test/src/main/kotlin/org/koin/test/check/CheckModules.kt
I also updated all tests, and made changes appropriatedly. Notably, in android-mvp and android-mvvm projects' `ModuleCheckTest` you can see how several features are now actually tests (scoping, parameters, properties). (https://github.com/erickok/koin/blob/9e04626c791ba3e17639865763f90b56f416d1e1/koin-projects/examples/android-mvp/src/test/java/fr/ekito/myweatherapp/ModuleCheckTest.kt)

Because your dependencies will actually be instantiated now, it is quite more aggressive and you might need to manually mock some more.

I have made a PR but probably we want to discuss first. Also, no named parameter creation supported yet. I wonder though @ncipollo why you need the depdenency name in the creator? Please check if the current approach is sufficient.

**Comment by ncipollo** [comment]
Hey @erickok,
In my specific use case we have an interface called ViewBinding. The concrete implementations usually depends upon one or more Android views. I can't really provide those android views via a koin module so they must be passed in via params.

When we define the koin module which provides the ViewBindings we give each a name and bind to the interface.

Each of the interface implementations may require a different set of views in the params. So defining a single paramCreator against the interface type wouldn't work in my case. We would need to map to the name & interface type. 

Hope that makes sense. Let me know if you have any additional questions.

**Comment by erickok** [comment]
@ncipollo Okay I have added support for this, for example
```kotlin
        koinApplication {
            modules(
                    module {
                        single("text")<ViewBinding> { (view: View, text: String) -> TextViewBinding(view, text) }
                        single("image")<ViewBinding> { (view: View, uri: Uri) -> ImageViewBinding(view, uri) }
                    }
            )
        }.checkModules(parameterCreatorsOf {
            create<ViewBinding>("text") { named -> parametersOf(mockedView, named) }
            create<ViewBinding>("upper") { named -> parametersOf(mockedView, Uri.parse(named)) }
        })
```

**Comment by ncipollo** [comment]
Hey @erickok,
That looks like it will do the trick for my usecase. Thanks for much for taking a look at this!
