### ISSUE TITLE
Add qualifiers

### ISSUE THREAD

**Issue by helmbold** [InsertKoinIO/koin#305]
Different implementations of an interface can be distinguished by string identifiers (aka "names"). This is prone to spelling errors. This problem could be avdoided by defining strings constants, but it encourages to just use strings in place.

I suggest to add a `Qualifier` interface of which implementing objects could be used instead of strings to identifiy a certain implementation.

```kotlin
interface Qualifier // part of Koin

object Default : Qualifier // define your own qualifier

single<Service>(Default) { ServiceImpl() } // usage
```
The qualifier should be usebale in other places, too.

**Alternatives**

[Annotations like in CDI](https://docs.jboss.org/weld/reference/latest/en-US/html/injection.html#_qualifier_annotations) could be used too, but they wouldn't fit to the current Koin programming model.

**Comment by arnaudgiuliani** [comment]
I was thinking about a `named<>()` function to fulfill any type as a name.

What do you think? @erickok @helmbold

**Comment by erickok** [comment]
It's a good alternative, yes. I suppose that is similar to the `scope<ClassName>` Koin already has for scoping. However, you can also reverse this logic and have the name be a `Qualifier` with a helper function `named("default")` which would return a unique instance for uniqueness, e.g.
```kotlin
class NamedQualifier(val name: String)
fun named(name: String) = NamedQualifier(name)

single<Service>(named("default")) { ServiceImpl() }
```

**Comment by arnaudgiuliani** [comment]
@erickok good idea. I can add this to the current beta devs 👍 

I'm reviewing Scope API to make it very simple to use. I'm not far from final proposal. With qualifiers will be perfect!

**Comment by helmbold** [comment]
@arnaudgiuliani What would be the return type of the suggested `named` method? Would just translate the object in a string? I'd prefer to enforce objects of the type `Qualifier` at the API level for the sake of robustness and clarity.

The suggestion of @erickok is essentially what Guice does with [@Named](https://github.com/google/guice/wiki/BindingAnnotations#named): a typed qualifier is the default, but you can circumvent this approach by using named qualifiers, which are basically wrapped strings. However the default should be a properly typed qualifier in my opinion.

**Comment by arnaudgiuliani** [comment]
this is it, all API now is based on `Qualifier` instead of String. Check beta-3

**Comment by MikeSoft** [comment]
I just qualified a call class with kotline : 

`
    single(named("core")) {
        retrofit(get(), "http://yourweb.org/api")
    }

    single {
        get<Retrofit>(qualifier = named("core")).create(RetrofitServiceInterface::class.java)
    }
`

**Comment by helmbold** [comment]
I'm happy that qualifiers are available now. However, this feature lacks documentation.  The documentation talks only about about `named(String)`, what misses the point of type safety.
