### ISSUE TITLE
KoinTest.checkModules does not report when using interfaces with ModuleDefinition.create

### ISSUE THREAD

**Issue by ChristopherZhong** [InsertKoinIO/koin#311]
**Describe the bug**
In the `koin-core-ext` project, interfaces or abstract classes can be used as types to the `ModuleDefinition.create` function. This case will always result in an exception. However, the `KoinTest.checkModules` does not report this case.

**To Reproduce**
1. With the following code:
```kotlin
interface Component

   @Test
    fun `should fail`() {
        val list = listOf(module {
            single { create<Component>() }
        })
        try {
            checkModules(list)
            fail()
        } catch (e: Exception) {
        }
    }
```

**Expected behavior**
The `KoinTest.checkModules` function should detect this case and throw an exception.

**Koin project used and used version (please complete the following information):**
`koin-core version 1.0.2`
`koin-core-ext version 1.0.2`
`koin-test version 1.0.2`

**Additional module definition**
Add any other moduleDefinition about the problem here.

**Comment by ChristopherZhong** [comment]
@arnaudgiuliani may I start a PR and add a failing test case?

**Comment by arnaudgiuliani** [comment]
@ChristopherZhong sorry for the delay. You can make a proposal for Koin 2.0

**Comment by arnaudgiuliani** [comment]
Please check latest API. thanks
