### ISSUE TITLE
Detached Scopes don't support nested, scoped dependencies

### ISSUE THREAD

**Issue by jhorvat** [InsertKoinIO/koin#312]
**Describe the bug**
Maybe I'm misunderstanding how to use the ```Scope``` API but when trying to do a ```get()``` call with a detached scope a runtime exception occurs. Digging deeper it seems this is because ```get()``` is hardcoded to use the scope registry and doesn't consider detached scopes. 

**To Reproduce**
I modified the ```AdvancedScopeAPI``` test to illustrate the problem

```kotlin
val mod = module {
    scope("request") { Request(get()) }
    scope("request") { "test" }
}

@Test
fun `create detached scope requests`() {
    startKoin(listOf(mod), logger = PrintLogger(showDebug = true))

    val request1Scope = getKoin().detachScope("request")
    val request2Scope = getKoin().detachScope("request")

    val request1 = get<Request>(scope = request1Scope)
    request1.name = "request1"
    val request2 = get<Request>(scope = request2Scope)
    request2.name = "request2"

    assertNotEquals(request1, request2)

    assertRemainingInstanceHolders(2)

    request1Scope.close()

    try {
        get<Request>(scope = request1Scope)
        fail()
    } catch (e: ClosedScopeException) {
    }

    assertRemainingInstanceHolders(1)

    request2Scope.close()

    try {
        get<Request>(scope = request2Scope)
        fail()
    } catch (e: ClosedScopeException) {
    }

    assertRemainingInstanceHolders(0)
}
```
This produces the following exception
```
2018-12-11 11:02:32:425 (KOIN)::[e] Error while resolving instance for class 'org.koin.test.scope.AdvancedScopeAPI.Request' - error: org.koin.error.BeanInstanceCreationException: Can't create definition for 'Scope [name='Request',class='org.koin.test.scope.AdvancedScopeAPI.Request']' due to error :
		Definition 'Scope [name='String',class='java.lang.String']' has to be used with a scope. Please create and specify a scope to use with your definition
```

**Expected behavior**
I would expect that this doesn't produce a runtime exception and instead uses either the scope registry or the detached scope. I'm attempting this because I have been exposed to #235 in the wild and I also have a dependency that I want to live as scoped single because the same instance is required in multiple, injected classes.

**Koin project used and used version (please complete the following information):**
```koin-core version 1.0.2```

**Comment by arnaudgiuliani** [comment]
Interesting, I will throw an eye to your example.

**Comment by arnaudgiuliani** [comment]
should be better supported with Koin Scope instances. Check the Koin 2.0 Scope API
