### ISSUE TITLE
Reloading a module?

### ISSUE THREAD

**Issue by jmiecz** [InsertKoinIO/koin#313]
Hello,

Is there a way to reload modules on the library side? An example would be, a network lib that uses retrofit + koin. When you first init the lib, it will use the default url but if someone wanted to change the environment (say go from a prod url to dev), how do we reload the modules with retrofit to use the new urls without making them just be factories?

**Comment by jmiecz** [comment]
Is there a way to create a group scope? Or do I need to make a scope for each of my retro interfaces?

**Comment by arnaudgiuliani** [comment]
in Koin 2.0 you can have a group of scope. Else you can do like:

```kotlin
with("your_scope_id"){
    scope(it) { def1() }
    scope(it) { def2() }
    //...
}
```

**Comment by Xerus2000** [comment]
How do I use this in practice?
