### ISSUE TITLE
small spelling correction needed in documentation

### ISSUE THREAD

**Issue by karadkar** [InsertKoinIO/koin#314]
> by inject() & get() - function to retrieve yoru instances from Koin

In the documentation of [Making your test a KoinComponent with KoinTest](https://insert-koin.io/docs/1.0/documentation/reference/index.html#_making_your_test_a_koincomponent_with_kointest) "your" is spelled as "yoru" which I believe is sourced [here](https://github.com/InsertKoinIO/koin/blob/master/koin-projects/koin-test/src/docs/asciidoc/starting-with-koin-test.adoc)

Please let me know if I can open a pull request.

**Comment by z3ntu** [comment]
There are also typos on https://insert-koin.io/docs/1.0/quick-references/koin-dsl/: I found `You an aslo give a name to a definition` and `You can sepcify extra binding with`

**Comment by commonsguy** [comment]
Also:

- In "Making your test a KoinComponent with KoinTest", "hceck" probably should be "check".
- In "Mocking out of the box", there is "if you wan", which I suspect should be "if you want".
- In "Checking your Koin configuration", there is "if you Koin modules", which might need to be "if your Koin modules"

**Comment by arnaudgiuliani** [comment]
Check the new master branch. All doc (ref, quick refs from website) is here
thanks
