### ISSUE TITLE
KoinJavaComponent not available in Koin-android

### ISSUE THREAD

**Issue by asdk-vmw** [InsertKoinIO/koin#315]
I'm currently using Koin for Android and I'm importing core and Koin-android projects. 
According to https://insert-koin.io/docs/1.0/getting-started/android-java/

I should be able to call inject (org.koin.java.standalone.KoinJavaComponent.inject) in any Java class but I don't see KoinJavaComponent class at all. Am I missing something? Should I include more projects?

I'm using version 1.0.2

**Comment by erickok** [comment]
You also need the koin-java project.
