### ISSUE TITLE
Module definition of Hello-ktor incompatible with mocking

### ISSUE THREAD

**Issue by fjlopez** [InsertKoinIO/koin#325]
[hello-ktor](https://github.com/InsertKoinIO/koin/blob/master/koin-projects/examples/hello-ktor/src/main/kotlin/org/koin/sample/KtorApplication.kt) contains instances created at start (`createOnStart` is set to `true` in `KtorApplication.kt`). As the objective of this example is to show how the `installKoin` feature works the following test:
```kotlin
@Test fun testMockService() = withTestApplication(Application::main) {
  declareMock<HelloService>()
  given(get<HelloService>().sayHello()).willReturn("Other")
  with(handleRequest(HttpMethod.Get, "/hello")) {
    assertEquals(HttpStatusCode.OK, response.status())
    assertEquals("Other", response.content)
  }
}
```
will fail with the following message
```
org.mockito.exceptions.misusing.MissingMethodInvocationException: 
when() requires an argument which has to be 'a method call on a mock'.
For example:
    when(mock.getArticles()).thenReturn(articles);
```
It works only when `createOnStart` is set to `false` it works. If this is the intended behaviour, it should be documented that `createOnStart` is set to `true` is incompatible with mocking.

**Comment by arnaudgiuliani** [comment]
Please reopen if it's still the case
