### ISSUE TITLE
[Team] reshaping the scope API

### ISSUE THREAD

**Issue by arnaudgiuliani** [InsertKoinIO/koin#328]
Hello all :)

I've finally rewritten the scope API for Koin, to allow a real usage of it. It's available in `koin-2.0.0-alpha-6`and here is how to use it:

this defines a definition that will exist only in a scope
```kotlin
val myModule = module {
    // MyComponent only exists during a scope
    scoped { MyComponent() }
}
```

to create a scope and retrieve our dependency, let's do:

```kotlin
// get current Koin instance
val koin = getKoin()
// create a scope with an id
val myScope : ScopeInstance = koin.createScope("myScopeName")
// retrieve instance from scope
val myComponent = myScope.get<MyComponent>()
// or equivalent expression
val myComponent = koin.get<MyComponent>(scope = myScope)
```

The `MyComponent` instance will survive until the scope `myScope` is closed (`myScope.close()`).

We can also define a logical group of `scoped` definitions. This means that those defintion will share the same scope context, and then will allow easy injection into definition without having to fill the `scope` attribute on each get.

```kotlin
class UserData
class ServiceUsingUserData(val userData : UserData)

val myModule = module {
    // Define a logical scoped group 
    scope("Session"){
       scoped { UserData() }
       scoped { ServiceUsingUserData(get()) }
    }
}
```

To create a scope for a given scope group definition:

```kotlin
// get current Koin instance
val koin = getKoin()
// create a scope with an id and scope name
val mySession : ScopeInstance = koin.createScope("mySession","Session")
// retrieve instance from scope
val myService = mySession.get<ServiceUsingUserData>()
```

In previous version we couldn't create several scopes for a given scope group definition. You can forget it now:

```kotlin
// get current Koin instance
val koin = getKoin()
// create a scope with an id and scope name
val mySession1 : ScopeInstance = koin.createScope("mySession1","Session")
// create a scope with an id and scope name
val mySession2 : ScopeInstance = koin.createScope("mySession2","Session")

// different instances & scopes
val myService1 = mySession1.get<ServiceUsingUserData>()
val myService2 = mySession2.get<ServiceUsingUserData>()
```

Good news for Android users: this will allow us to make more smart scope things! :)  In last update `koin-android-scope` & `koin-androidx-scope modules` we can now create real scopes bound on our activities and fragments (we allow scope group names as types). Let's define a component that will be used only for a `DetailActivity`:

```kotlin
val weatherAppModule = module {
    // Presenter for Detail View in scope
    scope<DetailActivity> {
        scoped<DetailContract.Presenter> { (id: String) -> DetailPresenter(id, get(), get()) }
    }
}
```

And in our `DetailActivity`, let's use our scope: 

```kotlin
class DetailActivity : AppCompatActivity(), DetailContract.View {
    // inject dependency from current scope
    override val presenter: DetailContract.Presenter by getActivityScope().inject { parametersOf(detailId) }

   override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_detail)
        // Bind our current scope to its lifecycle 
        bindScope(getActivityScope())
    }

//...
}
```

We have now: `getActivityScope()` and `getFragmentScope()` that get/retrieve scope for current activity or fragment and let you play with it! :)

Hope you'll like it. I think scopes are more usable with such approach. Give your feedback 👍

**Comment by IVIanuu** [comment]
Looks good but what about nested scopes? For example i wanna get a activity scoped instance in multiple fragments how would i do that?

**Comment by arnaudgiuliani** [comment]
just reuse your activity scope instance, and give it to your fragments. even more, you can use the injection parameters to propagate your scope where you want.

**Comment by IVIanuu** [comment]
Makes sense. But i think there should be a way to define a parent scope per scope so that we can implicitly access parent scopes definitions in child scope modules without using the parameters api

**Comment by IVIanuu** [comment]
Another thing that i would love to see is a way to add modules to scopes so that we can include definitions for activities fragments and so on while the scope is open. Basically something similar like the Scope.addInstance function on koin 1.0.0.

**Comment by arnaudgiuliani** [comment]
You can find your scope with `getKoin().getScopeWithType()`. Also try something like `parentActivity.getActivityScope()`

**Comment by erickok** [comment]
I have tried the new scoping API today in 2 different settings/places and it works well. I espeically like hte variant where type is used (instead of String), making the code much cleaner. 

Only the usage from Java was a bit tricky. In a Java Fragment I needed to get the activity scope to inject a presenter, but that is not yet available until adter the scope is created (in Activity onCreate), so there was some custom lazy logic I had to apply.

**Comment by erickok** [comment]
```
  private Lazy<MyFragmentPresenter> presenter = LazyKt.lazy(new Function0<MyFragmentPresenter>() {
        @Override
        public MyFragmentPresenter invoke() {
            return get(MyFragmentPresenter.class, null, LifecycleOwnerExtKt.getActivityScope(getBaseActivity()));
        }
    });
```

**Comment by arnaudgiuliani** [comment]
Thanks for your feedback, I'll try to make it more java friendly
