### ISSUE TITLE
Retrofit circular dependency instances creation

### ISSUE THREAD

**Issue by UngureanEugen** [InsertKoinIO/koin#334]
**Describe the bug**
I'd like to chain retrofit call when I received 401 error code.  
When I create `okHttpClient` I need `service` instance and when I create a `service` I need a `okhttpClient`.
How to solve this circular dependency in koin? 
```
val networkDataSourceModule = module {
    single { createOkHttpClient(get()) }
    single { createApiService(get()) }
}

fun createOkHttpClient(apiService: ApiService): OkHttpClient {
    return OkHttpClient.Builder()
         .addNetworkInterceptor(tokenInterceptor(apiService))
        .build()
}

fun createApiService(okHttpClient: OkHttpClient): ApiService =
    createService(okHttpClient, "myUrl")

inline fun <reified T> createService(okHttpClient: OkHttpClient, url: String): T {
    val retrofit = Retrofit.Builder()
        .baseUrl(url)
        .client(okHttpClient)
        .build()
    return retrofit.create(T::class.java)
}

```

**Comment by erickok** [comment]
Not really a Koin issue. I suggest taking out the token logic/storage code
into its own class which both service and interceptor can depend on. The
hacky way to to make one of them lazily injected into the other instead
(via field injection).

**Comment by UngureanEugen** [comment]
Created separate class with service and interceptor. Thanks @erickok

**Comment by luangs** [comment]
can you provide some code? @UngureanEugen
