### ISSUE TITLE
Koin 2.0 Slow logging

### ISSUE THREAD

**Issue by jakob-grabner** [InsertKoinIO/koin#338]
**Describe the bug**
Module loading during startKoin{...} is slower than it needs to be because of the following log statement:

`logger.info("bind type:'${type.getFullName()}' ~ $definition")`

in `org.koin.core.registry.BeanRegistry#saveDefinitionForType`.
Most of the time `saveDefinitionForType` takes is used to get the `canonicalName `of the class in `org.koin.ext.KClassExtKt#saveFullName`

One possibility would be to wrap all logs into a if condition to allow to **disable logging**.
Another solution could be to remove all log statements using proguards `assumenosideeffects`

**Koin project used and used version (please complete the following information):**
 `org.koin:koin-core:2.0.0-alpha-6`

Android Studio Trace:
[koin2_module_loading.zip](https://github.com/InsertKoinIO/koin/files/2786420/koin2_module_loading.zip)

**Comment by arnaudgiuliani** [comment]
if you don't use any logger, which is the default state for your `KoinApplication` config, you should not trigger any log call.
But perhaps still some `log.info` ... at start maybe like you are pointing.

**Comment by jakob-grabner** [comment]
If I don't use a logger I think we would avoid the actual logging ( e.g. call to android.util.Log ) but we would still build the String and call 'type.getFullName'. So I think this is not enough to solve this issue.

**Comment by arnaudgiuliani** [comment]
Sure, that's not what I said :)
