### ISSUE TITLE
Support injection of interface delegates

### ISSUE THREAD

**Issue by speekha** [InsertKoinIO/koin#343]
Extensions functions provided by Koin allow to inject objects inside classes that extend Andoid framework objects (Activities, Fragments...) or implement the KoinComponent interface. But if you want to declare a class that implements an interface through delegation, the injection needs to be called in a static context. Say for instance : 

`class MyActivity : Activity, MyInterface by get()`

The compiler will not allow this unless you add a companion object inside that activity that implements KoinComponent : 

`class MyActivity : Activity, MyInterface by get() {
    companion object : KoinComponent
}`

The other option is to declare a function that directly uses the StandaloneContext and calls get on that context. Both of those options look like dirty workarounds to me. Could it be possible to have a cleaner way to do that for classes that extend the Android Framework objects?

**Comment by arnaudgiuliani** [comment]
In Koin 2.0, we have the `GlobalContext` that hold your instance of Koin if you want to use it in a global/general manner (no SDK).

Could you directly use it for the delegate?

**Comment by arnaudgiuliani** [comment]
@speekha any more proposal?

**Comment by speekha** [comment]
Not really. This issue wasn't really a limitation since it's possible to achieve the desired result with a current API. It was just a suggestion for a dedicated API instead of something that looked like a workaround...

**Comment by arnaudgiuliani** [comment]
Ok. closing then 👍

**Comment by P1NG2WIN** [comment]
Can you provide example? And what to do with fragments? @arnaudgiuliani 

Example 

`ScanFragment: Fragment(R.layout.fragment_scan), ZxingScannerDelegate by get(ZxingScannerDelegateImpl::class.java)`

How i can access delegate instance then? if i need to override some methods.

```
    override fun initZxing() {
        delegateInstance.initZxing() //no instance, i must keep empty constructor for fragment

        toggleFlashlight(false)
        toggleScanZxing()
    }
```
