### ISSUE TITLE
koin 2.0 getProperty(key: String) missing defaultValue : T

### ISSUE THREAD

**Issue by stasbar** [InsertKoinIO/koin#344]
**Describe the bug**
I don't know if it was intended redesign, but I really miss `getProperty(key: String, defaultValue : T)` from koin 1.0.2 

previously
```kotlin
getProperty("googlebooks_base_url", "https://www.googleapis.com")
```
now
```kotlin
    val baseUrl: String = try {
      getProperty("googlebooks_base_url")
    } catch (e: MissingPropertyException) {
      "https://www.googleapis.com"
    }
```
Now I need to wrap my `getProperty(key)` with tryCach , which is quite ugly.

**Koin project used and used version:**
`koin-core version 2.0.0-beta-1`

**Comment by arnaudgiuliani** [comment]
included in 2.0
