### ISSUE TITLE
Provide a shutdown hook for koin-ktor

### ISSUE THREAD

**Issue by viniciusccarvalho** [InsertKoinIO/koin#348]
Currently there's no hook from ktor to allow `StandaloneContext` to stop. Ktor however provides ApplicationEvents: https://ktor.io/servers/lifecycle.html#monitor-events that could be used to subscribe to stop events and then gracefully stop the `StandaloneContext`

**Comment by arnaudgiuliani** [comment]
@viniciusccarvalho if you have any proposal about better Ktor integration, just go 👍

**Comment by viniciusccarvalho** [comment]
@arnaudgiuliani it will be my pleasure to contribute. I also noted that ktor is on a very old version currently (at least on master) 0.9.2, I can also raise a PR to bump its version and repo locations

**Comment by arnaudgiuliani** [comment]
Let's go with your PR then 👍
