### ISSUE TITLE
Allow registration of "destroy" method on beans

### ISSUE THREAD

**Issue by viniciusccarvalho** [InsertKoinIO/koin#349]
**Problem:**

Instances created by Koin currently do not have a way to gracefully terminate upon context closing. After a Context is terminated, instances are only set to `null` to allow memory recycling, but at some times it's important to have destructor style of semantics.

** Use Case: ** A lot of temporary resources that beans uses such as subscriptions to queue/brokers that are created on startup, and should be deleted on shutdown are left orphaned on servers because there's no way to clean those resources.

** Proposal ** : Modify the `single` and other factory methods to allow one extra parameter to be passed such as `destroy: T.()->Unit` so that during closing, the instance registry could invoke such function before setting the instance to null

**Comment by arnaudgiuliani** [comment]
I will detail the API when ready 👍

**Comment by arnaudgiuliani** [comment]
in next beta version, you can use `onRelease` and `onClose` function on your definition to catch when definition is releasing or closing.

Note: scoped definition are releasing only. Single return its value on onClose. Factory sends null to onClose/onRelease

Check next release for more info.
