### ISSUE TITLE
Cannot change language on app instantiate

### ISSUE THREAD

**Issue by ZombieD** [InsertKoinIO/koin#351]
**Describe the bug**
I want to create a multilanguage application so I need to override attachBaseContext and onConfigurationChanged in the Application and all of the Activitiy class, somehow like this: 

    override fun attachBaseContext(base: Context) {
       //Here i got a crash: kotlin.UninitializedPropertyAccessException: lateinit property koinContext has not been initialized
        super.attachBaseContext(languageHelper.setLocale(base) else base)
    }

    override fun onConfigurationChanged(newConfig: Configuration) {
        super.onConfigurationChanged(newConfig)
        languageHelper.setLocale(this)
    }

**Expected behavior**
I guess I ain't the first who want to create multilanguage app with Koin, so if I made something wrong can you help me? Although, in another project it's working perfectly (that project is use Dagger for dependency injection).

**Koin project used and used version (please complete the following information):**
 org.koin:koin-android:1.0.0
 ext.kotlin_version = '1.3.11'

**Comment by Mbt925** [comment]
I have a similar problem.

**Comment by magnumrocha** [comment]
@ZombieD have you find a solution for this?
