### ISSUE TITLE
Cyclic call while resolving Factory

### ISSUE THREAD

**Issue by jubarim** [InsertKoinIO/koin#353]
I am getting "Cyclic call while resolving Factory" in the second time a ViewModel is injected in my Fragment. The first time it works perfectly.

Here is how I use injection in my Fragment - I pass two observers as parameters:

- Fragment:

```kotlin
class CustomSettingsFragment : Fragment() {
    private val myViewModel: CustomSettingsViewModel by viewModel {
        parametersOf(stateObserver, profileObserver)
    }

...

    private val stateObserver = Observer<Unit> {
        activity?.onBackPressed() // I already tried finish() with the same issue
    }
```

- My module definition:
```kotlin
val appModule = module {
    // Custom Settings View Model
    viewModel { (stateObserver: Observer<Unit>, profileObserver: Observer<Unit>) ->
        CustomSettingsViewModel(get(), get(), get(), stateObserver, profileObserver)
    }
```

- How I start my fragment from my activity (using ktx):
```kotlin
        supportFragmentManager.transaction {
            replace(R.id.containerView, CustomSettingsFragment())
        }
```

**To Reproduce**
1. Open my fragment for the first time, perfect!
2. An event occurs and stateObserver is called in fragment, exiting it!
3. Enter the fragment again

`
2019-02-08 09:38:56:914 (KOIN)::[e] Error while resolving instance for class 'com.test..customsettings.CustomSettingsViewModel' - error: org.koin.error.DependencyResolutionException: Cyclic call while resolving Factory [name='CustomSettingsViewModel',class='com.test..customsettings.CustomSettingsViewModel']. Definition is already in resolution in current call:
 	Factory [name='CustomSettingsViewModel',class='com.test..customsettings.CustomSettingsViewModel'] 
 2019-02-08 09:38:56:926 (KOIN)::[e] Error while resolving instance for class 'com.test..customsettings.CustomSettingsViewModel' - error: org.koin.error.BeanInstanceCreationException: Can't create definition for 'Factory [name='CustomSettingsViewModel',class='com.test..customsettings.CustomSettingsViewModel']' due to error :
 		Cyclic call while resolving Factory [name='CustomSettingsViewModel',class='com.test..customsettings.CustomSettingsViewModel']. Definition is already in resolution in current call:
 	Factory [name='CustomSettingsViewModel',class='com.test..customsettings.CustomSettingsViewModel']
 		org.koin.core.stack.ResolutionStack.checkStackEnter(ResolutionStack.kt:56)
 		org.koin.core.stack.ResolutionStack.resolve(ResolutionStack.kt:41)
`

**Koin project used and used version (please complete the following information):**
    org.koin:koin-android:1.0.2
    org.koin:koin-androidx-viewmodel:1.0.2

Thanks very much!

**Comment by arnaudgiuliani** [comment]
Cycle call detection is a bit rude in 1.0.x. try throw an eye in 2.0
