### ISSUE TITLE
stopKoin doesn't clear single/scoped instances (Koin 2.0)

### ISSUE THREAD

**Issue by erickok** [InsertKoinIO/koin#354]
**Describe the bug**
When stopping Koin, singleton instances are not cleared (released). Starting again will hence return the old instances. We consider this a bug, since we explicitly stop the Koin GlobalContext.

**To Reproduce**
```
fun main(args: Array<String>) {
    // Start first time
    startKoin { modules(modules) }
    val thing = GlobalContext.get().koin.get<Thing>()
    println("Have a $thing")

    // Stop and start again
    stopKoin()
    startKoin { modules(modules) }
    val newThing = GlobalContext.get().koin.get<Thing>()
    println("Have a $newThing")
}

val modules = module {
    single { Thing() }
}

class Thing
```
This prints:
```
Have a Thing@30dae81
Have a Thing@30dae81
```

The cause is that singleton values are stored inside their `SingleInstance`, which are never released since these are bound to their (module) definitions, as long as you have a static definition (i.e. `val myModules = module {}` which is the advertised/recommend way e.g. https://beta.insert-koin.io/ ). In other words, since my definition is not renewed, the singleton value is always kept.

One 'fix' is to create new definitions every invocation of `startKoin { modules(...) }`.
```
val modules get() = module {
    single { Thing() }
}
```
Nnotice the `get()` here. This prints as expected:
```
Have a Thing@30dae81
Have a Thing@1b2c6ec2
```

**Expected behavior**
Stopping the global context (via `stopKoin()`) should release all instances of my singletons.

**Koin project used and used version (please complete the following information):**
koin-core version 2.0.0 beta 1

**Comment by arnaudgiuliani** [comment]
sure 👍

**Comment by arnaudgiuliani** [comment]
I published a fix while you worked on it also. Check the current code.
