### ISSUE TITLE
KoinJavaComponent has moved packages in Koin 2.0

### ISSUE THREAD

**Issue by kenyee** [InsertKoinIO/koin#357]
**Describe the bug**
This class has moved packages in 2.0.
Docs say to use this import (which includes a .standalone package subpath):

import static org.koin.java.standalone.KoinJavaComponent.*;

Which is also invalid syntax on Android.

The correct path seems to be missing the standalone piece.  I downloaded the 2.0 beta 1 koin-java package

```
jar -tvf koin-java-2.0.0-beta-1.jar 
     0 Fri Jan 25 14:56:16 EST 2019 META-INF/
    25 Fri Jan 25 14:56:16 EST 2019 META-INF/MANIFEST.MF
     0 Fri Jan 25 14:54:52 EST 2019 org/
     0 Fri Jan 25 14:54:52 EST 2019 org/koin/
     0 Fri Jan 25 14:54:52 EST 2019 org/koin/java/
  5670 Fri Jan 25 14:54:52 EST 2019 org/koin/java/KoinJavaComponent.class
  1591 Fri Jan 25 14:54:52 EST 2019 org/koin/java/KoinJavaComponent$inject$1.class
    16 Fri Jan 25 14:54:52 EST 2019 META-INF/koin-java.kotlin_module
```

**Comment by erickok** [comment]
`KoinJavaComponent` in Koin 2 is situated in the `org.koin.java` package indeed (in the `org.koin:koin-java:xxx` dependency).

From Java code you import it like this:
`import static org.koin.java.KoinJavaComponent.get;`
From Kotlin you shouldn't use it.
