### ISSUE TITLE
How can I get sharedViewModel in java classes?

### ISSUE THREAD

**Issue by dinhthaidaica** [InsertKoinIO/koin#358]
**In Kotlin classes (extends Fragment) , I can use below code to get an instance of SharedViewModel**

`val viewModel: MyViewModel by sharedViewModel()`

**How can I retrieve SharedViewModel in .java classes? (extends Fragment)?**
I have tried with below solution but it doesn't work.

`private Lazy<MyViewModel> myViewModel = inject(MyViewModel.class);`

**Comment by arnaudgiuliani** [comment]
koin-java only target basic Koin functions. A Kotlin/java compat for API should be used, but not sure to have a good result.

**Comment by dinhthaidaica** [comment]
as far as my last checking, it doesn't work :(
