### ISSUE TITLE
Mutliple definitions in scope 

### ISSUE THREAD

**Issue by mahmed1987** [InsertKoinIO/koin#359]
**Describe the bug**
A scope just works with one definition.

**To Reproduce**
scope("session") {  
       Something() 
     AnotherThing()
}

**Expected behavior**
In my activity I should see both of the members being injected. However i just see the first one injected called Something. Is this by design ? . If I am creating a scope which requires two objects to act as singletons inside it , how would i go about achieving that?

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core version 1.0.1`

**Comment by arnaudgiuliani** [comment]
sorry for Scope API has greatly change from 1.0 to 2.0. Please prepare your app for migration.
