### ISSUE TITLE
Viewholder doesn't get cleared upon activity exit

### ISSUE THREAD

**Issue by mahmed1987** [InsertKoinIO/koin#362]
This is my simple view model

`class  TestViewModel() : ViewModel()
{
    fun employees()= listOf("Richard","Farhan","Zeb")
    override fun onCleared() {
        super.onCleared()
        println("ViewModel is dying")
    }
}

`

This is my module for it

`val myAppModule = module {

    viewModel { TestViewModel() }

}`

This is my activity in which I inject this view model

`class TestActivity : BaseActivity()
{

    val testViewModel:TestViewModel by viewModel()
    override fun attachListeners() {

    }

    override fun onScreenInitializationComplete(activityArgs: Intent) {
    }

    override fun onScreenInitializationComplete(activityArgs: Intent, savedInstanceState: Bundle) {
    }

    override fun attachView() {
    }

    override val layoutResourceId: Int = R.layout.test_frag
    override val menuResourceId: Int = 0
}`

Run this application. Make sure TestActivity is not the first activity in the test application. Land on test activity and press back .

The onCleared of the viewModel is not called. This is dangerous. What is the scope of viewmodel ?

**Comment by arnaudgiuliani** [comment]
Please check the viewModel lifecycle. `onCleared` is called when destroying the underlying view.
