### ISSUE TITLE
Param VIEW_MODEL_KEY can't be refered by lazy

### ISSUE THREAD

**Issue by pietrini** [InsertKoinIO/koin#364]
**Describe the bug**
by navArgs() is a new lazy initializer from android jetpack [navigation library](https://developer.android.com/jetpack/androidx/releases/navigation#1.0.0-alpha10) if you try to put one of the args params in by viewModel for VIEW_MODEL_KEY, lazy instantiation doesn't work and you have to use getViewModel to initialize your viewModel when you want to use it.

     Caused by: java.lang.IllegalStateException: Fragment FeedFragment{f1e2bbd (7c2d6856-a950-4761-bc85-80592c94f195)} has null arguments
        at ch.rts.rtsinfo.ui.feed.FeedFragment$$special$$inlined$navArgs$1.invoke(FragmentNavArgsLazy.kt:42)
        at ch.rts.rtsinfo.ui.feed.FeedFragment$$special$$inlined$navArgs$1.invoke(Unknown Source:0)
        at androidx.navigation.NavArgsLazy.getValue(NavArgsLazy.kt:44)
        at androidx.navigation.NavArgsLazy.getValue(NavArgsLazy.kt:34)
        at ch.rts.rtsinfo.ui.feed.FeedFragment.getArgs(Unknown Source:9)
        at ch.rts.rtsinfo.ui.feed.FeedFragment.<init>(FeedFragment.kt:39)

**To Reproduce**

    class FeedFragment : Fragment() {
        private val args: FeedFragmentArgs by navArgs()
        private val viewModel: FeedViewModel by viewModel(args.path) { parametersOf(args.path) }

        override fun onActivityCreated(savedInstanceState: Bundle?) {
            super.onActivityCreated(savedInstanceState)
            //Do something with your viewModel
        }
    }

**Expected behavior**
I dont think this is related to navigation lib by navArgs() feature as it works fine if you do

    private val viewModel: FeedViewModel by viewModel { parametersOf(args.path) }

We should be able to use a viewModel key referenced by a lazy.
A common use case of this feature is if you have multiple same fragments classes using a different id/path/param and you want to be sure to have a fresh and new viewHolder for each param.

**Koin project used and used version (please complete the following information):**

    org.koin:koin-android:2.0.0-beta-1
    org.koin:koin-androidx-scope:2.0.0-beta-1
    org.koin:koin-androidx-viewmodel:2.0.0-beta-1

**Additional moduleDefinition**

    val appModule = module {
        single { HummingbirdRepository(androidContext()) }
        single { PushDefaultNotificationFactory(androidContext(), get()) }
        single(createdAtStart = true) { PushNotificationProxy(androidApplication(), get(), get()) }
        viewModel { (path: String) -> FeedViewModel(get(), path) }
        viewModel { (articleId: Int) -> ArticleViewModel(get(), articleId) }
        viewModel { (articleId: Int) -> GalleryViewModel(get(), articleId) }
        viewModel { AppViewModel(androidApplication(), get()) }
    }

**Comment by arnaudgiuliani** [comment]
conflict with `navArgs()` function delegate then :/

**Comment by arnaudgiuliani** [comment]
fix in next beta
