### ISSUE TITLE
More Koin 2.0 documentation issues (getOrCreateScope)

### ISSUE THREAD

**Issue by kenyee** [InsertKoinIO/koin#367]
The Koin 2.0 docs here:
https://beta.insert-koin.io/docs/2.0/documentation/reference/index.html#_scope_features_for_android

describe using getOrCreateScope which doesn't have an extension in LifecycleOwnerExt.kt
There is a private getOrCreateAndroidScope() extension.

They're also missing documention for

scope<YourActivity> {
}

and whether you need to create it or whether it does it automatically.  It doesn't seem to get created automatically even though it should be able to be?

**Comment by arnaudgiuliani** [comment]
Updated in Koin 2.0.0-GA3
