### ISSUE TITLE
Failed to resolve: io.ktor:ktor-server-core:0.9.2

### ISSUE THREAD

**Issue by hdtuan87** [InsertKoinIO/koin#369]
Implementation into my project with version 2.0.0-beta-1 of 1.0.2 error

1. implementation androidx, kotlin, viewmodel version 2.0.0-beta-1 or 1.0.2
2. Click on sync gradle
3. See error : 
`ERROR: Failed to resolve: io.ktor:ktor-server-core:0.9.2
Show in Project Structure dialog
Affected Modules: app`

**Comment by arnaudgiuliani** [comment]
don`t understand why you try to resolve ktor while using androix dependencies

**Comment by hdtuan87** [comment]
I think it like reactivex. it need implement rxjava, rxandroid, rxkotlin.
I try implement only ktor but same error

**Comment by arnaudgiuliani** [comment]
can you provide a sample project to help us investigate?
