### ISSUE TITLE
can't find sharedViewModel

### ISSUE THREAD

**Issue by pedromassango** [InsertKoinIO/koin#373]
I'm trying to get a sharedViewModel but Android Studio give me error, see the image bellow:

![screenshot 2019-02-20 at 12 08 17 pm](https://user-images.githubusercontent.com/33294549/53087800-4ed36c80-3508-11e9-866a-fab25ab39b41.png)

Koin version: 1.0.2

Inside my gradle:
implementation 'org.koin:koin-android-viewmodel:1.0.2'

**Comment by pedromassango** [comment]
Please any help, I can't keep working until I solve this problem

**Comment by arnaudgiuliani** [comment]
available only on fragments. The fragment share the activity's viewmodel 👍

**Comment by pedromassango** [comment]
Can we have this on activity too?

**Comment by arnaudgiuliani** [comment]
in activity you only need get/by viewModel. Sharing instances between activities is either single or scopes.
