### ISSUE TITLE
startKoin logger dsl overrides level

### ISSUE THREAD

**Issue by erickok** [InsertKoinIO/koin#374]
When startin Koin with a custom logger, the level gets overridden.
```kotlin
startKoin {
  logger(logger = PrintLogger(Level.ERROR))
}
assertEquals(KoinApplication.logger.level, Level.ERROR)
```
```
java.lang.AssertionError: 
Expected :INFO
Actual   :ERROR
```
While easily fixable, this feels very unnatural to me and I suspect would suprise most users.

I suggest to remove the log level parameter, to remove any doubt, make the API simple and any desired logger level requires a non-empty explicit logger anyway (PrintLogger, AndroidLogger, custom, slf4j, while the defualt shoudl IMHO be EmptyLogger).

(`koin-core version 2.0.0 master branch`)

**Comment by arnaudgiuliani** [comment]
continue this with your PR
