### ISSUE TITLE
Rename get() to distinguish it from in-build `operator get`

### ISSUE THREAD

**Issue by voddan** [InsertKoinIO/koin#377]
**Usability Problem**
Function `get()` has a confusing name and is usually hard to read in its context. Methods like `get` are used for getters in java projects, for `operator get()`, for HTTP method GET. Often it is hard to distinguish all those "gets". 

Compare it Koin's `inject()`: it is immediately clear that is is a part of DI, and the risk of naming clash with the business logic is minimal. I wish `get()` would get depricated and renamed into something like `inject()` or `injectEager()` or `getInjected()`.

My current workaround is to leave the generic type in the code even when it can be inferred:

    fun foo(service: Service = get<Service>()) {...}

**Koin project used and used version**
`koin-core version 1.0.2`

**Comment by arnaudgiuliani** [comment]
sorry, but get() is just an extension about `koin.get()`. The real thing is to allow generic inferred type here.

**Comment by voddan** [comment]
> sorry, but get() is just an extension about `koin.get()`

Sorry, I don't get how this is that relevant to my problem.

> The real thing is to allow generic inferred type here. 

The generics *are* inferred there. I just can't use that inference because it harms readability.


Please reopen this ticket and let us discuss what con be done about this.

**Comment by erickok** [comment]
In my personal experience I have not found it unreadable or clashing with existing code, but of course ymmv. Perhaps in your case you can simply define alternative naming in the project?
```
inline fun <reified T> Koin.injectEager() = get<T>()
```
(and/or other target classes than Koin of course, depending on what you use)

**Comment by voddan** [comment]
@erickok That would certainly be a workaround for my projects. However renaming the `get()` function in Koin should certainly be discussed anyways.

**Comment by arnaudgiuliani** [comment]
Perhaps one question is more about: "do people are using the get() extension or not"

**Comment by voddan** [comment]
I had to use `get()` in my modules when describing interdependent components.
