### ISSUE TITLE
Use standard Ktor Install feature

### ISSUE THREAD

**Issue by viniciusccarvalho** [InsertKoinIO/koin#378]
**Is your feature request related to a problem? Please describe.**
Ok this may be a bit of a pet peeve of mine, but is there a reason why Koin can't be a Feature for Ktor and then just be installed like any other feature?

The proposal is instead of having something like:

```
install(DefaultHeaders)
    installKoin(listOf(common, repositories, services))
```

Have something like 
```
install(DefaultHeaders)
install(Koin){
koin -> {
modules = listOf(common, repositories, services))
}
}
```

It makes it look more aligned with Ktor API, it's a not a big deal I get it, but with 2.0 coming soon, this seems to be something people may look into it.

I volunteer to even submit a PR with the change if this feature makes sense.

Regard

**Comment by viniciusccarvalho** [comment]
@arnaudgiuliani If you are interested I have this running already on my branch. Currently master seems to have issues with the koin-ktor, it needs to first have its dependencies bumped to 1.1.x, then I can add the Feature class to allow the `install(Koin)` style of bootstraping. 
Following up with the `ApplicationEvents` stopping hook as well

**Comment by arnaudgiuliani** [comment]
Let's go with your PR then 👍
