### ISSUE TITLE
StandAloneContext Koin instance is null - With ViewModel in multi module project

### ISSUE THREAD

**Issue by orogersilva** [InsertKoinIO/koin#380]
**Describe the bug**
I'm implementing instrumented tests with Espresso framework and Koin. But, when I run one test method, this error is shown:

![error in instrumented tests with koin](https://user-images.githubusercontent.com/8772916/53360481-60f04900-3914-11e9-89f3-04ceb4250a10.png)

The error occurs when the flow reachs the viewModel contained in the Activity:

`private val signUpStepOneViewModel by viewModel<SignUpStepOneViewModel>()`

![standalonecontext koin instance is null](https://user-images.githubusercontent.com/8772916/53360564-9d23a980-3914-11e9-8068-714d6326050c.png)

**To Reproduce**
I created a sample project with similar characteristics to the project in which occured the error: https://github.com/orogersilva/appforusingkoin-android

Inside it, there is a class test named `MainActivityTest`. When we run the test method, it is shown a exact error that I exposed before.

I noticed that when the project contains just one module (`app`), everything works perfectly. But, when we break the project in multiple modules, the error happens.

So I think that the problem is related to multi module projects.

**Expected behavior**
The `mainViewModel` had been injected.

**Koin project used and used version (please complete the following information):**
`koin-core version 1.0.2`

**Comment by pablodeafsapps** [comment]
Same problem here, even using `startKoin` instead of `loadKoinModules`. I also think this has to do with having _multi-module_ applications.
Contrary, this problem does not happen on simple Unit Tests.
Upgrading to the most recent version 2.0.1 does not solve this issue.

**Comment by arnaudgiuliani** [comment]
this is part of the package change for internals. Api stay the same.

**Comment by pablodeafsapps** [comment]
Sorry @arnaudgiuliani, does this solve the problem referred above?
Thanks!
