### ISSUE TITLE
How to update retrofit 'baseurl' at a runtime using koin (Recreate or update value)?

### ISSUE THREAD

**Issue by kajalgondaliya** [InsertKoinIO/koin#384]
How to update retrofit 'baseurl' at a runtime using koin 
koin module class:

```ruby
val networkModule = module(override = true) {
scope("baseURL") { provideBaseUrlHolder(Conts.BASE_URL) }
single { createOkHttpClient(get()) }
single { createTokenWebService(get(), get()) }
}
```

Application class:
onCreate of application class call startKoins()

```ruby
fun startKoins() {
    startKoin(this, listOf(appModule, networkModule, preferencesModule))
    scope = getKoin().getOrCreateScope("baseURL")
}
```
refreshScope() called while we want to change the baseurl at a runtime
```ruby
fun refreshScope() {
    scope.close()
    scope = getKoin().getOrCreateScope("baseURL")
    provideBaseUrlHolder(Conts.BASE_URL)
}
```

Login Class:
Calling login API and after getting successful response of login api change baseurl to

```ruby
Conts.BASE_URL = 'new baseurl'
refreshScope()
```

and call same api with updated baseurl.

**Note:** For changing baseurl at runtime, we call the refreshScope() function of application class but still it does not modify baseurl and the old value of baseurl only gets called.

**Comment by erickok** [comment]
The idea is right, but it depends on how you declared your modules. By the way, you may even opt to recreate your Koin graph entirely, instead of just the scope, as I bet you end up haveing to scope almost everything to that "baseURL" scope otherwise.

Note, you might have un into issue #354 which is fixed but no new release has been made yet.

**Comment by arnaudgiuliani** [comment]
reworking scope API to make it very simple to use. Please wait beta-2 & RC builds 👍

**Comment by birkanfirat** [comment]
is the problem solved? If so, how should I go about it?

**Comment by arnaudgiuliani** [comment]
Please check again with new scope API in Koin 3.0.1 or 2.3.0.

**Comment by birkanfirat** [comment]
Hello, I have code like below but after changing the baseurl, the request I made goes with the old baseurl again. Where am I making a mistake?

Koin version:
![Screen Shot 2021-03-12 at 11 43 16](https://user-images.githubusercontent.com/26115864/110930937-c4524580-833a-11eb-97aa-0e33b8cd4286.png)


Network module:
val networkModule = module(override = true) {
    scope(named("baseURL")) { scoped { provideBaseUrlHolder() } }
    factory { authInterceptor(get()) }
    factory { provideOkHttpClient(get()) }
    factory { provideRetrofitFor(get()) }
    single(override = true) { provideApi(get()) }

}

fun provideOkHttpClient(authInterceptor: AuthInterceptor): OkHttpClient {
    return OkHttpClient().newBuilder().connectTimeout(180, TimeUnit.SECONDS)
        .writeTimeout(180, TimeUnit.SECONDS)
        .readTimeout(180, TimeUnit.SECONDS).addInterceptor(authInterceptor)
        .build()
}

fun provideRetrofitFor(okHttpClient: OkHttpClient): Retrofit {
    val scope = getKoin().getOrCreateScope(
        "baseUrlId", named("baseURL"))
    val baseUrl = scope.getScope("baseUrlId").get<String>()
    val gson = GsonBuilder().setLenient().create()
    return Retrofit.Builder().baseUrl(baseUrl).client(okHttpClient)
        .addConverterFactory(ScalarsConverterFactory.create())
        .addConverterFactory(GsonConverterFactory.create(gson)).build()
}

fun provideApi(retrofit: Retrofit): Api = retrofit.create(Api::class.java)

fun provideBaseUrlHolder() = Constants.BASE_URL

Application Class:
fun startKoins() {
       startKoin {
            androidLogger()
            androidContext(this@App)
            modules(listOf(networkModule, repositoryModule, viewModelModule))
        }

       scope =  getKoin().getOrCreateScope("baseUrlId", named("baseURL"))
    }

    fun refreshScope() {
        scope?.close()
        scope = getKoin().getOrCreateScope("baseUrlId", named("baseURL"))
        provideBaseUrlHolder()
      
/*     provideRetrofitFor(get())
        stopKoin()
        startKoins() // I've also tried these functions but they don't work
*/
    }

Login Class:
Calling login API and after getting successful response of login api change baseurl to

 Constants.BASE_URL = it.baseUrl
                    getBaseApplication().refreshScope()

**Comment by birkanfirat** [comment]
@arnaudgiuliani
