### ISSUE TITLE
Koin 2.0 unit test doc should mention stopKoin() should be done in @Before

### ISSUE THREAD

**Issue by kenyee** [InsertKoinIO/koin#389]
**Describe the bug**
If you don't include stopKoin, startKoin will complain that Koin is already started on the 2nd test and unit tests will fail.
This should be documented (stopKoin is not mentioned in the unit test section.

**Expected behavior**
Documentation should be more clear.  I couldn't find the V2 docs on the site or I would have submitted a PR instead.

**Koin project used and used version (please complete the following information):**
 `koin-core version 2.0.0.beta-1`  but this is more of an issue w/ the site.

**Comment by arnaudgiuliani** [comment]
fixed in next 2.0.0-GA3
