### ISSUE TITLE
java.lang.NoClassDefFoundError version Beta

### ISSUE THREAD

**Issue by jignacioh** [InsertKoinIO/koin#393]
Hi, i have small issue with Koin

I define this lines how modules

`val appModule = module {`
    `viewModel{ UiViewModel(get()) }`
    `viewModel{ DetailViewModel(get()) }`
`}`

`val appModules = listOf(appModule)`

And in my application

`override fun onCreate() {`
           `super.onCreate()`
           ` startKoin{androidContext(this@BaseApp)`
           `androidLogger()`
           `modules(appModules)}`
     `}`

I define in my activity
`val model: DetailViewModel by viewModel()`

I got the next error:

 `Process: com.arch.core.arquetype, PID: 5498`
   `java.lang.NoClassDefFoundError: Failed resolution of: Lorg/koin/standalone/KoinComponent;`
`at com.arch.core.arquetype.viewmodelui.ViewModelActivity.getViewModel(ViewModelActivity.kt:54)`

Some help in advance?

**Comment by arnaudgiuliani** [comment]
dependencies resolution problem. Checked your gradle?
