### ISSUE TITLE
Beta 2 - ViewModel registration must have definition

### ISSUE THREAD

**Issue by fonix232** [InsertKoinIO/koin#394]
**Describe the bug**
In 2.0.0 beta 1 and 2, registering a ViewModel via `viewModel<vmType>()` is not possible - it requires a specified definition. Documentation says the old, definition-less, type-specifying variant should still work.

**To Reproduce**
1. Go to your module
2. Try to register a ViewModel via `viewModel<MyViewModel>()`
3. AS will show an error saying that `definition` is required
4. Replace `viewModel<MyViewModel>()` with `viewModel { MyViewModel() }`
5. AS will accept the call

**Expected behavior**
I'd expect `viewModel<MyViewModel>()` to be an acceptable statement within a `module`

**Koin project used and used version (please complete the following information):**
`koin-androidx-viewmodel version 2.0.0-beta-1`
`koin-androidx-viewmodel version 2.0.0-beta-2`

**Comment by erickok** [comment]
Are you (consiously) trying to use the (experimental) reflection-based API?

**Comment by fonix232** [comment]
Yes, I am. It worked fine in v1.0.0 (and even in v0.x versions), however it's gone in v2.x. The reflection based system works perfectly fine for me as I use zero-argument constructors and every injection happens as class body property injection, e.g.:

```
class BaseViewModel: ViewModel(), KoinComponent) {
    internal val context: Context by inject() // Yes, I'm intentionally not using AndroidViewModel here
    internal val navigation: NavigationManager by inject()
}

class MainViewModel: BaseViewModel() {
    private val userManager: UserManager by inject()
    private val repo: WhateverRepository by inject()
}

val appModule = {
    single<NavigationManager>()
    single<UserManager>()
    single<WhateverRepository>()

    viewModel<MainViewModel>() /*  <- this call doesn't work anymore */
}
```

**Comment by waqas117** [comment]
I faced same issue but resolved it with [this](https://github.com/InsertKoinIO/koin/issues/383#issuecomment-470212691)

**Comment by fonix232** [comment]
@waqas117 your solution would be perfect if the trouble was with injection - however my issue is not with that, but registration instead.

**Comment by arnaudgiuliani** [comment]
reflection api has been removed from viewmodel package to avoid too much wrong usage

**Comment by fonix232** [comment]
@arnaudgiuliani An understandable step, however some indication would've been useful - maybe in the migration guide, as a footnote?

**Comment by arnaudgiuliani** [comment]
yep, and also because API is still really experimental

**Comment by arnaudgiuliani** [comment]
won't fix in code, but rather will add documentation for that
