### ISSUE TITLE
Handle casting to ComponentCallbacks graciously

### ISSUE THREAD

**Issue by fonix232** [InsertKoinIO/koin#395]
**Describe the bug**
At the moment, `LifecycleOwner.getKoin()` tries to redirect to `ComponentCallbacks.getKoin`, however, not all LifecycleOwners implement ComponentCallbacks. Perfect example is the current implementation of LifecycleOwner controllers (`LifecycleController`)

**To Reproduce**
1. Have a custom class implement LifecycleOwner, but not ComponentCallbacks
2. Inject a ViewModel using `by viewModel()`
3. Launch app and initiate custom class
4. Watch the crash

**Expected behavior**
The ViewModel gets injected appropriately

**Koin project used and used version (please complete the following information):**
`koin-androidx-viewmodel version 2.0.0-beta-2`

The source of the problem is the following statements:

```
private fun LifecycleOwner.getKoin() = (this as ComponentCallbacks).getKoin()

fun ComponentCallbacks.getKoin(): Koin = GlobalContext.get().koin
```

Recommendation: replace `LifecycleOwner.getKoin()` with the following call:

```
private fun  LifecycleOwner.getKoin() = when(this) {
    is ComponentCallbacks -> (this as ComponentCallbacks).getKoin()
    is KoinComponent -> this.getKoin()
    else -> GlobalContext.get().koin
}
```

This way the appropriate call is always made, no matter what the given LifecycleOwner inherits from.

**Comment by arnaudgiuliani** [comment]
added to beta-3 👍

**Comment by pawelmarchewka** [comment]
But it will be better to switch two first lines in `when` statement
```
fun LifecycleOwner.getKoin(): Koin = when (this) {
    is KoinComponent -> this.getKoin()
    is ComponentCallbacks -> (this as ComponentCallbacks).getKoin()
    else -> GlobalContext.get().koin
}
```
so it will work with custom contex out of the box if `LifecycleOwner` implements custom `KoinComponent`.

**Comment by kingori** [comment]
+1 to @pawelmarchewka . Under current implementation, using custom context in activity along with LifecycleObserver extension is impossible.

**Comment by kingori** [comment]
I've checked ComponentCallbacks and In `ComponentCallbacks.getKoin()`, function check whether ComponentCallbacks is instance of KoinComponent. So, `LifecycleOwner.getKoin()` implementation no issue. 

https://github.com/InsertKoinIO/koin/blob/2.0.0-beta-5/koin-projects/koin-android/src/main/java/org/koin/android/ext/android/ComponentCallbackExt.kt
```
fun ComponentCallbacks.getKoin() = when (this) {
    is KoinComponent -> this.getKoin()
    else -> org.koin.core.context.GlobalContext.get().koin
}
```

**Comment by BuddahLD** [comment]
Hello!
Why did you get back to the:
`private fun LifecycleOwner.getKoin() = (this as ComponentCallbacks).getKoin()` ?

In beta-5 I can still find:
``` kotlin
private fun LifecycleOwner.getKoin() = when (this) {
    is ComponentCallbacks -> (this as ComponentCallbacks).getKoin()
    is KoinComponent -> this.getKoin()
    else -> GlobalContext.get().koin
}
```

While in 2.0.1 it's rolled back to:
`private fun LifecycleOwner.getKoin() = (this as ComponentCallbacks).getKoin()`

Why I'm asking - I have an object that implements `LifecycleOwner`, but it's not a `ComponentCallbacks`, so when I'm trying to inject like `currentScope.inject()` - I'm having a `MyObject cannot be cast to android.content.ComponentCallbacks`.

Thank you!
