### ISSUE TITLE
Wrong order of context and property init

### ISSUE THREAD

**Issue by fonix232** [InsertKoinIO/koin#396]
**Describe the bug**
Starting Koin with `androidFileProperties()` is impossible - Koin tries to initialize the properties before the Context instance is registered.

**To Reproduce**
1. Follow the guide for v2.0
2. Add `androidFileProperties()` to `startKoin { }` after `androidContext(this@App)`
3. Launch app
4. Observe crash on launch, with the following exceptions:

```
Instance creation error : could not create instance for [type:Single,class:'android.content.Context']: java.lang.IllegalStateException: ScopeInstance ScopeInstance[id:'-GLOBAL-'] is not registered

java.lang.RuntimeException: Unable to create application net.fonix232.app.App: org.koin.core.error.InstanceCreationException: Could not create instance for [type:Single,class:'android.content.Context']
```

**Expected behavior**
The app launches, and loads the properties from the file (if it exists).

**Koin project used and used version (please complete the following information):**
`koin-androidx-viewmodel version 2.0.0-beta-2 `

**Comment by arnaudgiuliani** [comment]
fixed for next stage 👍

**Comment by fonix232** [comment]
Awesome, thanks!

Will rc-1 be pushed once the build issues (those two tests failing) have been corrected? It would also be nice if you tagged the specific commits for each release, to make debugging and version checking a bit easier :)
