### ISSUE TITLE
Add support for AndroidX SavedState ViewModels

### ISSUE THREAD

**Issue by mzgreen** [InsertKoinIO/koin#398]
AndroidX added a feature called SavedState. There is `SavedStateVMFactory` which I think could be supported by Koin. 

https://developer.android.com/jetpack/androidx/releases/lifecycle#viewmodel-savedstate-1.0.0-alpha01

**Target Koin project**
Probably `koin-androidx-viewmodel`.

**Comment by mzgreen** [comment]
The doc showed up: https://developer.android.com/topic/libraries/architecture/viewmodel-savedstate

**Comment by ychescale9** [comment]
hmm I had a quick look and I'm not sure how we can support this right now as `SavedStateVMFactory` is final and we can't override its `<T : ViewModel> create()` function 🤔

**Comment by mzgreen** [comment]
Here is a nice blogpost showing how to integrate SavedState with Dagger: https://proandroiddev.com/saving-ui-state-with-viewmodel-savedstate-and-dagger-f77bcaeb8b08

it seems that it needs to use AssistedInject. Does Koin have a thing that acts like AssistedInject?

**Comment by arnaudgiuliani** [comment]
Have to check with `AbstractSavedStateVMFactory` - https://developer.android.com/reference/androidx/lifecycle/AbstractSavedStateVMFactory.html

**Comment by arnaudgiuliani** [comment]
in progress : https://github.com/InsertKoinIO/koin/pull/496
