### ISSUE TITLE
Koin 2.0: checkModules fails on module with scope

### ISSUE THREAD

**Issue by Tapchicoma** [InsertKoinIO/koin#399]
**Describe the bug**
I have following simple Koin module with `scope` inside:
```kotlin
data class One(val item: String)
data class Two(val one: One)

val testModule = module {
    scope("TEST_SCOPE") {
        scoped { One("zzz") }
        scoped { Two(get()) }
    }
}
```

When I am running a test with `checkModules()` method call:
```kotlin
fun checkKoinDI() {
    koinApplication { 
        modules(listOf(testModule)) 
    }.checkModules()
}
```

I always got `org.koin.core.error.ScopeAlreadyCreatedException: A scope with id 'sandbox_scope' already exists. Reuse or close it.`.

**Expected behavior**
Above test should pass.

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core` and `koin-test` version `2.0.0-beta4`

**Comment by arnaudgiuliani** [comment]
found in beta-3, fixed in beta-4
