### ISSUE TITLE
2.0 reference documentation is wrong about named dependencies

### ISSUE THREAD

**Issue by Pitel** [InsertKoinIO/koin#401]
https://insert-koin.io/docs/2.0/documentation/koin-core/index.html#_dealing_with_generics

```kotlin
single(name = "")
```

is now

```kotlin
single(named(""))
```

**Comment by Pitel** [comment]
Also `get("")` is now `get(named(""))`.

**Comment by arnaudgiuliani** [comment]
@Pitel wip for documentation 👍

**Comment by arnaudgiuliani** [comment]
fixed in next 2.0.0-GA3
