### ISSUE TITLE
Default scope id using Qualifier

### ISSUE THREAD

**Issue by kacperhreniak** [InsertKoinIO/koin#403]
Hi, I\`ve explored a Scope API in version 2.0.0-beta4 and I think that you\`ve made a good job to provide a scope using LifecyclerOwner. What do you think about doing it for all scopes? I mean creating a default Qualifier and mark `scopeId` as nullable with default value `null` in method. 

`Koin` class
**Before**: 
``` kotlin
fun createScope(scopeId: ScopeID, qualifier: Qualifier? = null): Scope
```  
**After**: 
``` kotlin
fun createScope(scopeId: ScopeID? = null, qualifier: Qualifier? = null): Scope
```
Koin creates `scopeId` in `createScope()` method relying on `qualifier` or `scopeId`, for example:
``` kotlin
val scopeId = scopeId ?: qualifier?.toString() ?: throw NullPointerException("You need to provide a scopeId or qualifier to create a Scope")
```

**Adventage:**
- in module use qualifier as before: 
``` kotlin
scope(named("test")) {
    scoped { Test() }
}
``` 
or
 ``` kotlin
scope(TestQualifier) {
        scoped { Test() }
}
```
- When you need to create a scope you can use only a Qualifier but you can still add a special scopeID:
Create:
``` kotlin
getKoin().createScope(qualifier = named("test"))
```
Get scope:
```
getKoin().getScope(named("test").toString()).get<Test>()
```
- if you don\`t like using a hardcoded strings as value you can create object implements `interface Qualifier`: 
``` kotlin
object TestQualifier : Qualifier
```
Get Scope: 
``` kotlin
// of course getScope have to be changed for example--> getScope(scopeId: ScopeId? =null, qualifier: Qualifier = DefaulQualifier )  //or null
getKoin().getScope(TestQualifier.toString()).get<Test>()
```

Of course, this is an example. To create the perfect solution, changes in other methods are required: get, delete, ect are required. I think it can be more transparent and intuitive for new library users.

**Comment by erickok** [comment]
Indeed on LifecycleOwner a short-hand notation exists to create a scope based on it (it's instance); `private fun LifecycleOwner.getScopeId() = this.toString()` The `.toString()` will certianly not work for all objects though, which is surely why you opted to use the `Qualifier.toString()` instead. I agree with that choice.

I played around with it a bit and am liking the suggestion. Just one addition in that I would create a seperate function for it, perhaps `fun createQualifiedScope(qualifier: Qualifier): Scope`?

**Comment by kacperhreniak** [comment]
I think that creating a extra method it\`s good idea, but what about the ScopeId object used in other methods? It seems to be not a consistent Behavior. I\`m a user of Dagger library too and creating a annotation class to create a scope is a very friendly - I know that Dagger uses an annotation processor but using a Qualifier in Koin library to creating scope it\`s something what I expect for and for me sounds great :D

**Comment by arnaudgiuliani** [comment]
if I sum up, it's about having default id when creating socpe?

**Comment by kacperhreniak** [comment]
Yes, it`ll be more intuitive. More improvement: using Kotlin`s object class or kind of Qualifier instead of hardcoded String as a scope ID could be more practical.

**Comment by arnaudgiuliani** [comment]
ScopeID is also source of the problem then here. Could be also a qualifier directly

**Comment by arnaudgiuliani** [comment]
default ScopeID is not considered for now. Please reopen later if you want to propose something 👍
