### ISSUE TITLE
"Page Not Found" when open links for documentation v1.0 from google

### ISSUE THREAD

**Issue by kyryloz** [InsertKoinIO/koin#404]
**Describe the bug**
When googling Koin related stuff google provides links to the documentation version 1.0 which is not opened.

**To Reproduce**
1. Go to google.com
2. Type something like "koin getting started android"
3. Observe links, which lead to the documentation v1.0.
![image](https://user-images.githubusercontent.com/16967676/54682189-e5e71080-4b16-11e9-9720-ceb0a54a14fe.png)

![image](https://user-images.githubusercontent.com/16967676/54682203-ef707880-4b16-11e9-8310-4176f558cbba.png)

**Expected behavior**
Documentation should work for v1.0 or redirected to v2.0.

**Comment by arnaudgiuliani** [comment]
Old API is on https://old.insert-koin.io 👍

**Comment by arnaudgiuliani** [comment]
seems to be more indexed around 2.0 doc
