### ISSUE TITLE
How to inject a repo into FirebaseMessagingService class

### ISSUE THREAD

**Issue by FarshidABZ** [InsertKoinIO/koin#408]
Hi 
I want to send client FCM token to my server when the token is ready, so I need my user repository in MyFirebaseMessagingService.
The problem is FirebaseMessagingService needs default empty constructor.

so How can inject my userRepo in the MyFirebaseMessagingService class?

**Comment by floschu** [comment]
```
class FCMService: FirebaseMessagingService(), KoinComponent {
  private val userRepository: UserRepository by inject()
  ...
}
```

**Comment by arnaudgiuliani** [comment]
seems to be ok
