### ISSUE TITLE
Remove dependency on KoinComponent

### ISSUE THREAD

**Issue by asdk-vmw** [InsertKoinIO/koin#411]
Problem:
I like the idea of KoinComponent to make use of extension functions but they're turning out to be a problem for classes that are exposed outside of a library. For example, in my case, I work on a framework library that uses Koin while the application doesn't. All the public classes/methods that implements KoinComponent are not usable by the application without depending on Koin at the application level. 

**Describe the solution you'd like**
Java way of using KoinJavaComponent is turning out to be life-saver in such scenarios as there is not dependency on KoinComponent. 

Can something better be done for this problem? It's becoming a deal-breaker for Kotlin-only projects with no Java dependency. I'm being forced to use Koin-Java even when there are no Java classes in the project only to avoid KoinComponent.

**Comment by erickok** [comment]
First, as your library depends on Koin, 'the application' consuming your library _will_ get the (transitive) dependency, regardless whether you use KoinComponent or not. I think what you mean is that 'the application' (consumer of your library) gets access to the properties exposed by KoinComponent as well, if it uses your library classes, and you don't like that.

KoinComponent is not magical; all it does is give some convenience methods (by defining extension properties). If you would directly access what KoinComponent normally exposes for you, you do not have to implement KoinComponent.

So just directly use `GlobalContext.get().koin` and you do not expose ('leak') anything.
