### ISSUE TITLE
Change LifecycleOwner.getScopeId() implementation

### ISSUE THREAD

**Issue by kingori** [InsertKoinIO/koin#423]
**Is your feature request related to a problem? Please describe.**
In koin-android-scope module, `LifecycleOwner.getScopeId()` is implemented like below.
```kotlin
private fun LifecycleOwner.getScopeId() = this.toString()
```

`LifecycleOwner.toString()` is rarely overridden, but if someone override it, he'll get same id for all instance for that type. If Activity's `toString()` is overridden and get `ViewModel` from scope, he'll get same ViewModel instance in every Activity instances and this will make problems.

**Describe the solution you'd like**
What about changing id by using `Object.identityHashCode()` ? By using this, unique id per instance is guaranteed. I just copied sample implementation from Java's `Object.toString()`.

```kotlin
private fun LifecycleOwner.getScopeId() = getClass().getName() + "@" + identityHashCode(this)
```

**Describe alternatives you've considered**

**Target Koin project**
2.0.0 rc-2

**Comment by arnaudgiuliani** [comment]
interesting proposal.

**Comment by arnaudgiuliani** [comment]
added to 2.0.0-GA 👍
