### ISSUE TITLE
Website: broken search results

### ISSUE THREAD

**Issue by WarrenFaith** [InsertKoinIO/koin#424]
**Describe the bug**
search results link to not existing 1.0 documentation

**To Reproduce**
1. Go to the koin website
2. Type something into the search bar (like "scope")
3. Select a result
4. Opened website returns a 404 page with "1.0" in the url
5. If you replace the "1.0" with "2.0" the url works

**Expected behavior**
The result should open 2.0 documentation links

**Comment by arnaudgiuliani** [comment]
yep, search engine still has some old links. Have to check that

**Comment by arnaudgiuliani** [comment]
Documentation is now deployed with docsify:

- https://start.insert-koin.io/
- https://doc.insert-koin.io/
