### ISSUE TITLE
ViewModel - Activity observer is not notified when reopening

### ISSUE THREAD

**Issue by GauvainSeigneur** [InsertKoinIO/koin#425]
**Describe the bug**
After reopen an activity, the observer is not notified when LiveData change

**To Reproduce**
I have to activity : A and B. Each subscribe to a ViewModel A and B. Each View Model have singleton dependencies. Each ViewModel are injected in Activity thanks to  "val mMyViewModel by viewModel< MyViewModel >()"
1. On Activity A. I click on button to go on activity B
2. On first opening in Activity B the observer of LiveData is notified. Even in configuration change.
3. I go back on activity A thanks to back system button 
4. I click again on the button to go on Activity B
5. The activity B observer is not notified (But the LiveData value change in viewModel)

**Expected behavior**
Activity observer get notified when I'm reopening the activity.

**Koin project used and used version (please complete the following information):**
  def koin_version = '2.0.0-rc-2'
    // Koin for Android
    implementation "org.koin:koin-android:$koin_version"
    // AndroidX (based on koin-android)
    // Koin AndroidX Scope feature
    implementation "org.koin:koin-androidx-scope:$koin_version"
    // Koin AndroidX ViewModel feature
    implementation "org.koin:koin-androidx-viewmodel:$koin_version"

Thank you

**Comment by arnaudgiuliani** [comment]
can you provide a more complete sample?

**Comment by GauvainSeigneur** [comment]
I will make a repo by the end of the week
