### ISSUE TITLE
Koin qualifiers 1.0.2 -> 2.0.0-rc-2 migration

### ISSUE THREAD

**Issue by akotsuba** [InsertKoinIO/koin#426]
I try to migrate the app from koin 1.0.2 to 2.0.0-rc-2 version. As far as I understand, an old qualifier description like
`single(name = "name") { ... }`
should be replaced with 
`single((named("name"))) { ... }`

I use it to mark different implementations of the same datasources (like local, remote etc).
So, after I migrated the project, the exception occurs:
    ` Caused by: org.koin.core.error.DefinitionOverrideException: Already existing definition or try to override an existing one with qualifier 'DS_MEMORY' with [type:Single,name:'DS_MEMORY', class:'com.example.IDeliveryDataSource'] but has already registered [type:Single,name:'DS_MEMORY', class:'com.example.IPaymentMethodsDataSource']`

Why can't I use the same qualifier name for different types as I did before? Or I missed something? Thanks!

**Comment by arnaudgiuliani** [comment]
yes, a qualifier is unique. Can't use one quailifier for several definitions

**Comment by akotsuba** [comment]
@arnaudgiuliani Thanks for the answer! But won't it be great to compare types also? Or this mechanism is used for scopes also? Anyway please confirm whether this behavior leave the same in release version, and I will make more qualifiers in this case.

**Comment by arnaudgiuliani** [comment]
for 2.0.0, we will use unique qualifier. Have to see for next version if we can have something better
