### ISSUE TITLE
Scope close() doesn't destroy an object

### ISSUE THREAD

**Issue by BulatMukhutdinov** [InsertKoinIO/koin#427]
Env: koin rc-3
Assuming I have class MyClass and module
```
module {
    scoped {
        MyClass()
    }
```
I have code below
```
val scope1 = getKoin().createScope("Scope")
val myClass1: MyClass = scope1.get()
scope1.close()

val scope2 = getKoin().createScope("Scope")
val myClass2: MyClass = scope2.get()
```

In this case myClass1 == myClass2. But since they belong to different scopes they should also differ. Otherwise what is different between this scoped and single?

**Comment by yarkh** [comment]
Checked for 2.0.0-rc-2 & rc-3, it works correctly.

In Kotlin == is structural equality. Try referential equality with ===.
https://kotlinlang.org/docs/reference/equality.html

**Comment by BulatMukhutdinov** [comment]
Please check this gist https://gist.github.com/BulatMukhutdinov/0e0a373f7cb1c818c9e6dc2171e329d8

When you start this application, koin scope should provide instance with ```number = 1```


Then you click home button. Koin scope is closed


When you click to go back to the app koin should create a new scope with the same name. This time it should provide instance with ```number = 2```. But in fact it provides an instance with ```number = 1```. Moreover the reference of the instance remains the same (something like ProvidedClass@11286)

**Comment by yarkh** [comment]
I have made some research. 
Releasing scoped definitions works only for named scope:
```
scope(named("MY_SCOPE") {
        scoped { ComponentA() }
}
```
Scope without Qualifier created without ScopeSet where all scoped definitions are registered (ScopeRegistry):
```
fun createScopeInstance(id: ScopeID, scopeName: Qualifier? = null): Scope {
    val definition: ScopeSet? = scopeName?.let {
        definitions[scopeName.toString()]
               ?: throw NoScopeDefinitionFoundException("No scope definition found for scopeName '$scopeName'")
    }
...
definition?.let { instance.set = it }
```
Scope closing does not release definition instances:
```
fun close() = synchronized(this) {
        set?.release(this)
..
```
I see two ways to solve this issue:
1. Remove scoped definitions for Module and make scope qualifier non-nullable
2. Use default scope Qualifier for Module

@BulatMukhutdinov use named scope as workaround

Cheers

**Comment by BulatMukhutdinov** [comment]
Thanks for your response. Yes, I had to use named scope because scopes without qualifiers don't work as I expected
I am just wondering what is use case for unnamed scopes?

**Comment by erickok** [comment]
```
module {
    scoped { MyClass() }
}
```
doesn't really make sense, because indeed no scope is defined (using `scoped {}`). Or am I missing something @arnaudgiuliani ? If so, we should improve the DSL a bit such that the `scoped` keyword is not usable outside of `scope`.

**Comment by arnaudgiuliani** [comment]
a `scoped` definition without `scope` structure can be attached to any scope instance. But clearly yes, make problem for release. Should avoid to allow that then. Only scope/scoped structure.

**Comment by green-nick** [comment]
I've just wasted few hours trying to solve this until seen this issue. You definitely should deny such declaration! It really works like `single`.
But in general - great job, love it 👍

**Comment by green-nick** [comment]
What about adding name qualifier to `scoped` in Module context and make it working like `scope` for single declaration?
Sth like that (just mine workarround):
```
module {
    scopeOf(name("Cool scope")) {
        SomeObjectsConstructor()
    }
}

inline fun <reified T> Module.scopeOf(
    name: Qualifier,
    qualifier: Qualifier? = null,
    override: Boolean = false,
    noinline definition: Definition<T>
) {
    scope(name) {
        scoped(qualifier, override, definition)
    }
}
```
But replace `scopeOf` with `scoped`
I can't do this, because it's occupied by library

**Comment by arnaudgiuliani** [comment]
can be a good idea, but we need 2 qualifiers then: 1 for the scope and 1 for the definition.

For now let's stay with the scope/scoped definition 👍
