### ISSUE TITLE
Using Koin with FragmentScenario

### ISSUE THREAD

**Issue by Linus-Weiss** [InsertKoinIO/koin#434]
I am having trouble injecting my Koin viewmodel into a Fragment that is used in combination with a FragmentScenario to test that Fragment in isolation. How would I apporach this?

**Comment by Sottti** [comment]
Has this one been answered? I'm trying to find out how to use Koin with FragmentScenario as well...

**Comment by arnaudgiuliani** [comment]
Need more details here, with a example app.
