### ISSUE TITLE
[2.0.0-GA] Just before the release!

### ISSUE THREAD

**Issue by arnaudgiuliani** [InsertKoinIO/koin#440]
Hi Koin users,

the Koin `2.0.0-GA` has been published with the last changes for the final release. I need now to polish/update/write documentation to help you use all of that.

You can check the last changes in the changelog: https://github.com/InsertKoinIO/koin/blob/master/CHANGELOG.md

Some latest updates:
- `injectOrNull` & `getOrNull` to retrieve a potential instance
- `bind`/`binds` operator has been simplified to tag secondary types for definition. This secondary type can be reached with `getAll` & `bind` functions 
- `getAll` to request all definitions regarding primary & secondary types
- `bind` to request an entity thanks to its primary and secondary type `single { MyComponent() } bind Component::class` can be found via `bind<MyComponent,Component>()`
- internals has been reworked to use scope mechanism as primary primitive work level: Koin works now with its root scope by default. If you want to request a dependency from a scope, just create/retrieve it and use it directly.
- Scope DSL has been limited. Now you can't try to declare single/factory in scope section. 
- now possible to declare a type in different scopes

```
val koin = koinApplication {
            modules(
                    module {
                        scope(named("B")) {
                            scoped { Simple.ComponentA() }
                        }
                        scope(named("A")) {
                            scoped { Simple.ComponentA() }
                        }
                    }
            )
        }.koin

        val scopeA = koin.createScope("A", named("A")).get<Simple.ComponentA>()
        val scopeB = koin.createScope("B", named("B")).get<Simple.ComponentA>()
        scopeA & scopeB => are different!
```

If you find a problem, help us & give your feedback! 

Final release `2.0.0` is on the road 👍 

Cheers.

**Comment by darkrossi** [comment]
Good morning Arnaud,

_I can't use the scope feature with my MVVM architecture_.

It has been said that the instance of my view model can't be created.
```java
Could not create instance for [type:Factory,class:'MyActivityViewModel']
```

**More precisely**, the first error in the stacktrace concerns the definition of the view model constructor's parameter which is not found : 
```java
No definition found for 'EventCollectorInterface' has been found. Check your module definitions.
```

My injections file
```kotlin
    scope(named<MyActivity>()) {
        scoped { EventCollectorService() as EventCollectorInterface }
        viewModel { MyActivityViewModel(get()) }
    }
```

My activity
```kotlin
class MyActivity : AppCompatActivity() {
    private val viewModel by viewModel<MyActivityViewModel>()
    ...
}
```

My view model definition
```kotlin
class MyActivityViewModel(
    private val eventCollectorInterface: EventCollectorInterface
) : ViewModel()
```

**Comment by arnaudgiuliani** [comment]
A ViewModel is not tied to a scope. You can't declare a viewModel in a scope. To use a scoped definition instance from a ViewModel, pass it the scopeId that you need:
```
// Your ViewModel that use a defintion from a scope
viewModel { (scopeId : ScopeID) -> MyActivityViewModel(getScope(scopedId).get()) }

// Your scope
scope(named<MyActivity>()) {
    scoped { EventCollectorService() as EventCollectorInterface }
}

// retrieve your ViewModel by passing the scopeId
val viewModel by viewModel<MyActivityViewModel> { parametersOf(currentScope.id) }
```

**Comment by knordbo** [comment]
It looks like qualifiers are not cached in combination with the type, making this code fail:
```
module {
    single<String>(named("foo")) { "hello world" }
    single<Long>(named("foo")) { 1L }
}
```

```org.koin.core.error.DefinitionOverrideException: Already existing definition or try to override an existing one with qualifier 'foo' with [type:Single,name:'foo', class:'java.lang.Long'] but has already registered [type:Single,name:'foo', class:'java.lang.String']
at org.koin.core.registry.BeanRegistry.saveDefinitionForName(BeanRegistry.kt:110)
```

This worked before, and I would expect it to still work since the same qualifiers are typically used across domains.

**Comment by darkrossi** [comment]
> A ViewModel is not tied to a scope. You can't declare a viewModel in a scope. To use a scoped definition instance from a ViewModel, pass it the scopeId that you need:
> 
> ```
> // Your ViewModel that use a defintion from a scope
> viewModel { (scopeId : ScopeID) -> MyActivityViewModel(getScope(scopedId).get()) }
> 
> // Your scope
> scope(named<MyActivity>()) {
>     scoped { EventCollectorService() as EventCollectorInterface }
> }
> 
> // retrieve your ViewModel by passing the scopeId
> val viewModel by viewModel<MyActivityViewModel> { parametersOf(currentScope.id) }
> ```

It works perfectly 👍 

Thank you for all your work!

**Comment by dkrivoruchko** [comment]
`module { single { SettingsImpl(get()) as Settings } bind SettingsReadOnly::class }`
in Android Fragment 
`private val settingsReadOnly: SettingsReadOnly by inject()`
got 

> NoBeanDefFoundException: No definition found for 'info.dvkr.screenstream.data.settings.SettingsReadOnly' has been found. Check your module definitions.

**Comment by arnaudgiuliani** [comment]
yes, secondary types are now found by `bind` & `getAll`. You will find your component by: `getKoin().bind< Settings,SettingsReadOnly>()`

This way you can have several components bound  your secondary type, here `SettingsReadOnly`

**Comment by arnaudgiuliani** [comment]
but let me check to get it back in `get()`... to allow you to retrieve it naturally if you only have one component for a secondary type.

**Comment by arnaudgiuliani** [comment]
publishing `2.0.0-GA2` with several fixes for additional types:

To sum up:
```
module {
    single { Simple.Component1() } bind Simple.ComponentInterface1::class
    single { Simple.Component2() } bind Simple.ComponentInterface1::class
    single { Simple.UserComponent(bind<Simple.Component1, Simple.ComponentInterface1>()) }
}
```
- you can get directly the instances with `get<Simple.Component1>()`, `get<Simple.Component2>()`
- `get<Simple.ComponentInterface1>()` will throw an error and tell you to use `bind` because can’t choose between the 2 definitions
- you can use `bind<>()` to resolve a component in the DSL
- `getAll<Simple.ComponentInterface1>()` give us the 2 instances

In a situation with only one definition for a secondary type, get would return the right instance directly:
```
module {
    single { Simple.Component1() } bind Simple.ComponentInterface1::class
}

//
get<Simple.ComponentInterface1>() returns the right instance
```

**Comment by REPLicated** [comment]
@arnaudgiuliani : Regarding your last point above, the following does not work for me (self-contained example):
```
interface TransactionManager
interface ConnectionProvider
class TransactionManagerImpl: TransactionManager, ConnectionProvider

val koinDbModule = module {
    single<TransactionManager> { TransactionManagerImpl() } bind ConnectionProvider::class
}

class AppTest: KoinComponent {
    @Test
    fun run() {
        startKoin {
            modules(koinDbModule)
        }

        val connectionProvider: ConnectionProvider = get()

    }
}
```
Results in:
```
No definition found for 'koinplayground.ConnectionProvider' has been found. Check your module definitions.
org.koin.core.error.NoBeanDefFoundException: No definition found for 'koinplayground.ConnectionProvider' has been found. Check your module definitions.
	at org.koin.core.scope.Scope.findDefinition(Scope.kt:146)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:140)
	at org.koin.core.scope.Scope.get(Scope.kt:131)
	at koinplayground.AppTest.run(AppTest.kt:39)
```

Why is that? I only have one definition for the secondary type.

**Comment by arnaudgiuliani** [comment]
check with `2.0.0-GA2`

**Comment by REPLicated** [comment]
@arnaudgiuliani : Ok, I will try to upgrade as soon as you publish those artifacts.

**Comment by arnaudgiuliani** [comment]
already online: https://bintray.com/ekito/koin

**Comment by REPLicated** [comment]
Sorry, I missed that. It would be nice if you could always publish to JCenter and create a release on Github (like you did for 2.0.0-GA).

**Comment by alexbchr** [comment]
@arnaudgiuliani In RC2, we had possibility to pass a scope reference to `KoinJavaComponent` `get` and `inject` methods. As of GA2, it is no longer possible? How can I reference a scoped instance from Java code from now on?

**Comment by arnaudgiuliani** [comment]
@alexbchr you have to create a scope, but API is less Java friendly. Can you open a ticket?

**Comment by erickok** [comment]
Yeah we have the same issue, extremely tricky to get a scope from Java and to get a dependency with it.

**Comment by alexbchr** [comment]
For future reference, here is the related issue #451

**Comment by arnaudgiuliani** [comment]
@alexbchr thanks 👍

**Comment by arnaudgiuliani** [comment]
`KoinJavaComponent` fixed back with scope property in `2.0.0-GA3`

**Comment by renaudcerrato** [comment]
Removing the scope parameter from get() / inject() is definitely a nice step forward. It was confusing at best and, worst, could introduce some nasty side effects since the scope was lazily evaluated using inject().

**Comment by lucaspommateau** [comment]
Any ideas on when the final 2.0.0 will be published?

**Comment by arnaudgiuliani** [comment]
normally, before the end of the month 👍

**Comment by nksaroj** [comment]
Below is the code I was using for using Koin components in some legacy Java classes with Koin 1.0.

```
import org.koin.core.KoinContext
import org.koin.core.instance.InstanceRequest
import org.koin.core.parameter.ParameterDefinition
import org.koin.core.parameter.ParameterList
import org.koin.core.parameter.emptyParameterDefinition
import org.koin.standalone.StandAloneContext
import kotlin.jvm.internal.Reflection


object KoinJavaUtils {

    /**
     * inject lazily given dependency
     */
    @JvmOverloads
    @JvmStatic
    fun <T : Any> inject(clazz: Class<T>, name: String = ""): Lazy<T> {
        return lazy { get(clazz, name) }
    }

    /**
     * Retrieve given dependency
     */
    @JvmOverloads
    @JvmStatic
    fun <T : Any> get(clazz: Class<T>, name: String = ""): T {
        val kclazz = Reflection.getOrCreateKotlinClass(clazz)
        val koinContext = (StandAloneContext.koinContext as KoinContext)
        return koinContext.instanceRegistry.resolve(InstanceRequest(name, kclazz, null, emptyParameterDefinition()  ) ,null) as T
    }

    /**
     * inject lazily given property
     */
    @JvmOverloads
    @JvmStatic
    fun <T> property(key: String, defaultValue: T? = null): Lazy<T?> {
        return lazy { getProperty(key, defaultValue) }
    }

    /**
     * Retrieve given property
     */
    @Suppress("UNCHECKED_CAST")
    @JvmOverloads
    @JvmStatic
    fun <T> getProperty(key: String, defaultValue: T? = null): T? {
        val koinContext = (StandAloneContext.koinContext as KoinContext)
        return koinContext.propertyResolver.properties[key] as T? ?: defaultValue
    }

}

```

During the process of migration to 2, I've get to see lot of unresolved reference. It would be great if anyone can give me a hand for this class migration. I ran out of options due to not much doco. Appreciated your help!
