### ISSUE TITLE
How to inject datarepository instance in Content provider using insert-koin

### ISSUE THREAD

**Issue by numanbutt777** [InsertKoinIO/koin#441]
Facing Issues insert ContentProvider in AppModule.

My app level Module is

module {
        single { TinyDB.getInstance(get()) }
        single { DataRepository(get()) }
        viewModel { HomeViewModel(get()) }
    }
I have no idea how to use ContentProvider in Module

I have tried Code

val dataRepo = inject(DataRepository::class.java) 
I add this Code in  Content provider after this  My app Start crashes 
and logcat show Error Massage 
Process: wastickerapps.newemojistickers.stickersforwhatsapp, PID:26598 java.lang.RuntimeException: Unable to get provider wastickerapps.newemojistickers.stickersforwhatsapp.whatsappUsages.StickerContentProvider: java.lang.IllegalStateException: StandAloneContext Koin instance is null``

**Comment by jacob-chapman** [comment]
I am not sure if I'm understanding your issue completely. If you could give me the constructor for the StickerContentProvider class that could help, but I can guess.
If you want to use you StickerContentProvider in the module you can just add it like so:
`single { StickerContentProvider(get())`
Same way as you added everything else, that is if the params required as given in the module or another module you are starting as well. So if the param is the DataRepository class that you already have added then you should be fine.
