### ISSUE TITLE
[2.0.0-GA] getKoin().bind() Proguard/R8 NoBeanDefFoundException

### ISSUE THREAD

**Issue by dkrivoruchko** [InsertKoinIO/koin#443]
**Code:**
module { single { SettingsImpl(get()) as Settings } bind SettingsReadOnly::class }
private val settingsReadOnly: SettingsReadOnly = getKoin().bind<Settings,SettingsReadOnly>()

**To Reproduce**
Debug build (no proguard/r8) - ok
Release build with Proguard/R8 got:
> NoBeanDefFoundException: No definition found for 'info.dvkr.screenstream.data.settings.SettingsReadOnly' has been found. Check your module definitions.

**Comment by arnaudgiuliani** [comment]
Arg. But I see. Main problem comes from the fact that we are looking for current KCLass. Need to build a secondary types tree to handle this.

**Comment by arnaudgiuliani** [comment]
Fixed in `2.0.0-GA2`. Can you try @dkrivoruchko?

**Comment by dkrivoruchko** [comment]
Now it work as this:
```
module { single { SettingsImpl(get()) as Settings } bind SettingsReadOnly::class }
private val settingsReadOnly: SettingsReadOnly by inject()
```
In debug and release builds.
Thanks!

**Comment by erickok** [comment]
Thanks for fixing - we were also affected.
