### ISSUE TITLE
How to add a Koin module inside a Koin module?

### ISSUE THREAD

**Issue by VictorAlbertos** [InsertKoinIO/koin#444]
We have next modules:

```kotlin
val module1 = module {
  // lot's of factory and single providers
}
internal val module2 = module  {
  // lot's of factory and single providers
}
```

But I want to expose outside this unit compilation (Gradle module) only the `module1`, and keep `module2` as an internal detail. What's the proper way to achieve this? I tried next approach: 

```kotlin
val module1 = module { 
  // lot's of factory and single providers
  module { module2 }
}
```

But even that this compiles it produces a runtime error as all the dependencies provided in `module2` are not actually added to Koin graph.

**Comment by erickok** [comment]
What's wrong with your first approach?

**Comment by VictorAlbertos** [comment]
Sorry, but I don't follow you. I only posted one approach which is using `module { module2 }` to load a module into Koin graph trough another module. But as I said, this leads to a "runtime error as all the dependencies provided in module2 are not actually added to Koin graph".
