### ISSUE TITLE
Avoid DefinitionOverrideException on specific cenarios

### ISSUE THREAD

**Issue by RodrigoAmaroEng** [InsertKoinIO/koin#448]
Hi guys, although Koin is great for testing, found myself struggling with a specific use case 
I'm using Robolectric for Android tests and one of my necessities it to provide injected dependencies as soon as the application starts.
This is necessary because our flow has some situations like this:
```
onCreate { (Application on create)
   startKoin { ... }
   val someDependency = get()
   someDependency.use()
}
```
So any dependency override on my test needs to occur between `startKoin` and `get()` to produce the intended behaviour.

I was able to achieve it by extending my application class and putting a hook method between both instructions and telling Robolectric to use this implementation. Well it works but seems kind of hackish and as matter of fact i don't like having to change the Application class for this to work.

I was playing with `startKoin` and `loadKoinModules` to draw how this flow should be.
It seems that the best way to achieve it, would be to load the mocked dependencies before the application even is started and, when it does start, just add the dependencies that were not previously provided.

Today if i do this i have 2 problems to address. 
First i have to deal with the fact that i'm trying to call `startKoin` after it was already called.
I can bypass this with a `try catch` but just to get a  `DefinitionOverrideException`. For this, i guess a simple property over the `module` instruction like:

```
module(keepPreviousDependencies = true) {
   ...
   // Or alternativetly
   single<SomeInterface>(ifNotProvided = true) { ... }
}
```
would do the job.

Any thoughts about it?

**Comment by arnaudgiuliani** [comment]
I'm looking for a better moduel semantic to prevent reload an already existing definition.
