### ISSUE TITLE
[2.0.0-GA4] Declare instance on the fly

### ISSUE THREAD

**Issue by arnaudgiuliani** [InsertKoinIO/koin#453]
One of the last backport feature from Koin 1.0 is the ability to declare an instance on the fly. This is now available on `Koin.declare()` or `Scope.declare()`

```kotlin
val koin = koinApplication {
    // no def
    modules()
}.koin

// Create an instance
val a = Simple.ComponentA()

// declare it
koin.declare(a)

// retrieve it
assertEquals(a, koin.get<Simple.ComponentA>())
```

You can also use a `qualifier` or `secondary types` to help create your definition:
- `koin.declare(myInstance, named("qualifier"))`
- `koin.declare(myInstance, secondaryTypes = listOf())`

Should be ok now to launch Koin 2.0 👍

**Comment by renaudcerrato** [comment]
Switched from rc2 to ga4 and got `Unresolved reference: scoped` - why?

**Comment by arnaudgiuliani** [comment]
we need a name of the scope definitions structure and an ID for the scope instance

**Comment by renaudcerrato** [comment]
Got it. Mandatory qualifier for scope make sense.
