### ISSUE TITLE
Implement Closeable

### ISSUE THREAD

**Issue by erikhuizinga** [InsertKoinIO/koin#456]
**Is your feature request related to a problem? Please describe.**

Because `KoinApplication` has a `close` function, but doesn't implement the `Closeable` interface, I cannot use Kotlin's `Closeable#use`.

**Describe the solution you'd like**

I'd like `KoinApplication` to implement the `Closeable` interface so I can use `use`, e.g.:

```kotlin

koinApplication { /* config / setup ... */ }
    .use { /* use this: KoinApplication */ }
```

**Describe alternatives you've considered**

Currently I do:

```kotlin
val koinApplication = koinApplication { /* config / setup ... */ }

/* use koinApplication: KoinApplication */

koinApplication.close()
```

**Target Koin project**

An Android library that uses local KoinApplication instances (instead of the global `startKoin`/`stopKoin` instance).

**Comment by arnaudgiuliani** [comment]
each definition can specify `onRelease` and `onClose`. `onClose` is used for factory and single definitions. `onRelease` when releasing a scope instance.

**Comment by glasser** [comment]
I'm not sure how the comment above addresses the request. `Koin` and `KoinApplication` do have `close()` methods, but because they don't officially implement `Closeable`, you can't use `use` with them, which would be nice.
