### ISSUE TITLE
ViewModelSavedState when lazy injection

### ISSUE THREAD

**Issue by mochadwi** [InsertKoinIO/koin#458]
**Is your feature request related to a problem? Please describe.**
To leverage the power of viewmodel-savedstate google io '19, and also to reduce the step to configure and retain state using savedInstance no more

**Describe the solution you'd like**
Reducing the boilerplate to configure savedInstanceState, also to get savedstate feature from koin would be great. Currently lazy injection and similar use the plain `ViewModelProviderFactory` or for the next milestone to support [SavedStateVMFactory](https://medium.com/androiddevelopers/viewmodels-persistence-onsaveinstancestate-restoring-ui-state-and-loaders-fc7cc4a6c090) by default

**Describe alternatives you've considered**

**Target Koin project**
with lazy injection. e.g: `val vm: CustomVM by [viewModelState|sharedViewModelState]`

**Comment by arnaudgiuliani** [comment]
duplicate from https://github.com/InsertKoinIO/koin/issues/398
