### ISSUE TITLE
Is there any way to refer the qualifier inside the definition? 

### ISSUE THREAD

**Issue by RodrigoAmaroEng** [InsertKoinIO/koin#462]
Hey guys, i was wondering if is there a way to refer the qualifier to avoid code duplication on my module.

Let's consider the following construction:

```
module {
   single<ClassA>(QualifierA1) { ClassA(get<ClassB>(QualifierB1)) }
   single<ClassA>(QualifierA2) { ClassA(get<ClassB>(QualifierB2)) }
   single<ClassB>(QualifierB1) { ClassB(1) }
   single<ClassB>(QualifierB2) { ClassB(2) }
}
...
get<ClassA>(QualifierA1)
get<ClassA>(QualifierA2)
```
I consider that this construction have some "issues":

1. I'm obligated to create a different qualifier for the same purpose (QualifierA1 and QualifierB1). This is only necessary because when i use a qualifier, it binds to the type meaning i can't use the same qualifier to another type
2. I need to duplicate the ClassA construction even it being the same for both qualifiers just because its dependencies have different qualifiers

In my opinion it would be better if i could write this:

```
module {
   single<ClassA>(proxyQualifier = true) { ClassA(get<ClassB>(qualifier)) }
   single<ClassB>(Qualifier1) { ClassB(1) }
   single<ClassB>(Qualifier2) { ClassB(2) }
}
...
get<ClassA>(QualifierA1)
get<ClassA>(QualifierA2)
```
This way, even thought ClassA injector does not define a qualifier, i could pass it to its dependencies and avoid both code duplication and unnecessary qualifiers. Besides the fact that this example only skips one line of code, i have bigger dependency trees on my project where it would really decrease the amount of code needed

In this example `proxyQualifier` is just a property name to identify that this scope can receive a qualifier to use it on its dependencies.

So i don't know if it's already possible but, if not, would be a great feature to have

**Comment by erickok** [comment]
Can't you use two scoped instances instead of two singletons?

**Comment by arnaudgiuliani** [comment]
also using `bind` operator?

**Comment by RodrigoAmaroEng** [comment]
@erickok, @arnaudgiuliani 
In this example i used `single` just to elaborate the problem. 

I confess i got a little confused on how it can be more "readable" and offer a less verbose solution, but i'm pretty sure i just have to experiment with these proposed solution to clarify on this. After doing i will post my impressions here

**Comment by RodrigoAmaroEng** [comment]
So i've read the documentation about `scope` and `bind` features.

Although the concept of scope appears to be exactly what i want, the `scope` the documentation states:

> Scope is a fixed duration of time or method calls in which an object exists. Another way to look at this is to think of scope as the amount of time an object’s state persists. When the scope context ends, any objects bound under that scope cannot be injected again (they are dropped from the container).

Somehow it seems to not be the solution for what i'm looking for, cause:
1. I don't expect my objects to exists for just a duration
2. Neither to exists only on that specific context. Most of the samples i saw use the scope on the "top class" and my scenario relies on change the bottom class, assuming that

Top Class _(depends on)_ Some Class _(depends on)_ Bottom Class

Anyway would be nice if could do this:

```
module {
   factory<ClassA>(proxyQualifier = true) { ClassA(get<ClassB>(qualifier)) }
   scope(Qualifier1) {
      scoped<ClassB> { ClassB(1) }
   }
   scope(Qualifier2) {
      scoped<ClassB> { ClassB(2) }
   }
}
...
get<ClassA>(scope(Qualifier1)) // Would return ClassA injected with ClassB(1)
get<ClassA>(scope(Qualifier1)) // Would return ClassA injected with ClassB(2)
```

Now on the bind documentation it says:

> But here you won’t be able to request an instance with get<Simple.ComponentInterface1>(). You will have to use koin.bind<ComponentInterface1,Component1>() to retrieve an instance of ComponentInterface1, with the Component1 implementation.

So i would have to be specific when asking which version to get and that would lead me to propagate this choices to all the injections for classes above the Bottom Class, meaning they would have to duplicate their codes which would lead to:

```
module {
   single<ClassA>(QualifierA1) { ClassA(get<ClassB>(QualifierB1)) } // Unnecessary code duplication
   single<ClassA>(QualifierA2) { ClassA(get<ClassB>(QualifierB2)) } // Unnecessary code duplication
   single<ClassB>(QualifierB1) { ClassB(1) }
   single<ClassB>(QualifierB2) { ClassB(2) }
}
...
get<ClassA>(QualifierA1)
get<ClassA>(QualifierA2)
```

In the sample i wrote on my first post i've messed the part where i'm to get the dependency i need. This is what i expect to achieve:

```
module {
   factory<ClassA>(proxyQualifier = true) { ClassA(get<ClassB>(qualifier)) }
   factory<ClassB>(Qualifier1) { ClassB(1) }
   factory<ClassB>(Qualifier2) { ClassB(2) }
}
...
get<ClassA>(Qualifier1) // Would return ClassA injected with ClassB(1)
get<ClassA>(Qualifier2) // Would return ClassA injected with ClassB(2)
```
Here, the proposed attribute `proxyQualifier` exists just to let the Qualifier informed when retrieving ClassA to be used as parameter to get ClassB

**Comment by c-b-h** [comment]
I stumbled upon the issue migrating to Koin. Initially I thought that – just like in Dagger – `Qualifier`s could be reused for differentiating also a set of types.

```kotlin
val koinModule = module(override = true) {
    single { provideBaseClient() }
    single { provideBaseRetrofit() }

    single(qualifier = named<Q1>()) {
        provideQ1Client(get(), get())
    }
    single(qualifier = named<Q1>()) {
        provideQ1Retrofit(get(qualifier = named<Q1>()))
    }
}
```

In the example above I have two unqualified types of `OkHttpClient` and `Retrofit`. I would like to define two qualified (Q1) types of `OkHttpClient` and `Retrofit`. Loading this module causes a `StackOverflowError` unless I define another `Qualifier` return type for my `provideQ1Retrofit`.
