### ISSUE TITLE
Koin 2 missing viewModelByClass

### ISSUE THREAD

**Issue by chilleddev** [InsertKoinIO/koin#463]
**Describe the bug**
In Koin 1.0.2 I was able to define base fragment:
```
abstract class BaseFragment<Binding : ViewDataBinding, VM : BaseViewModel>(val clazz: KClass<VM>) : Fragment() {

//and use
protected val viewModel: VM by viewModelByClass(clazz, parameters = viewModelParameters())
}

```
Now with version Koin 2.0.0-GA4 it is not possible. When I use:

`protected val viewModel: VM by viewModel<VM>(qualifier = TypeQualifier(clazz), parameters = viewModelParameters())`

I'm getting error 'Cannot use VM as reified type parameter. Use a class instead.

**Expected behavior**
I would expect to have possibility to use `by viewModel` in my code. I think one way how to solve it is adding another method accepting KClass in LifecycleOwnerExt.kt:

```
inline fun <reified T : ViewModel> LifecycleOwner.viewModel(
        clazz: KClass<T>,
        qualifier: Qualifier? = null,
        noinline parameters: ParametersDefinition? = null
): Lazy<T> = lazy { getViewModel<T>(clazz, qualifier, parameters) }
```

**Koin project used and used version (please complete the following information):**
```
implementation 'org.koin:koin-core:2.0.0-GA4'
implementation 'org.koin:koin-androidx-scope:2.0.0-GA4'
implementation 'org.koin:koin-androidx-viewmodel:2.0.0-GA4'
```

**Comment by arnaudgiuliani** [comment]
will be back in `2.0.0` 👍

**Comment by arnaudgiuliani** [comment]
check it in the final release
