### ISSUE TITLE
Inject into parent class.

### ISSUE THREAD

**Issue by Jorikua** [InsertKoinIO/koin#464]
**Question**
Is there a way to inject objects into a parent class?

Right now what I'm trying to do is to have a common class, that has some common injections. Also, it's scoped to this class.

```
val videoPaywallModule = module {
  scope(named<AbsVideoPaywallFragment>()) {
    scoped(named<AbsVideoPaywallFragment>()) { (playerView: PlayerView) ->
      VideoPlayerWrapper(get(), playerView)
    }
  }
}
```

Next, I have an parent class:
```
abstract class AbsVideoPaywallFragment : Fragment() {

  private val videoPlayerWrapper by currentScope.inject<VideoPlayerWrapper>(named<AbsVideoPaywallFragment>()) { parametersOf(playerViewVideoPaywall) }
}
```

And inheritor:
```
class OnboardingVideoPaywallFragment : AbsVideoPaywallFragment() 
```

It crashes with this exception:

`Caused by: org.koin.core.error.NoScopeDefinitionFoundException: No scope definition found for scopeName 'com.example.ui.paywall.video.OnboardingVideoPaywallFragment'`

So it wants me to define the exact scope of inheritor but not the parent.

**Comment by arnaudgiuliani** [comment]
The thing here is that you have a scope created for `OnboardingVideoPaywallFragment`, not `AbsVideoPaywallFragment`. 

You can try to create the scope manually from the root component and pass it the childs.

```kotlin
// create a scope instance for AbsVideoPaywallFragment with the current fragment scope id
val parentScope = getKoin().createScope(getScopeId(),named<AbsVideoPaywallFragment>())
// bind it to your lifecycle to close it at the end of the fragment
createAndBindScope(parentScope)
// inject
val videoPlayerWrapper by parentScope.inject<VideoPlayerWrapper>(named<AbsVideoPaywallFragment>()) { parametersOf(playerViewVideoPaywall) }
```

but it will create a scope for `OnboardingVideoPaywallFragment`

If you want something that is tied to your generic component, use a static scope id instead of `getScopeId()`
