### ISSUE TITLE
Take a single instance of Retrofit with Single and an interceptor for dynamic headers

### ISSUE THREAD

**Issue by rezaiyan** [InsertKoinIO/koin#466]
**Describe the bug**
I am providing a Retrofit single instance with Single
also an Okhttp instance needed for Retrofit and this is provided too as usual
since a token authentication needs when a user logged in. the Retrofit instance doesn't anymore comeback to read the token by Okhttp.
To solve this I have to change the providing method of the Retrofit to Factory, 
but I think it's a bad solution.

Does Koin have any solution for this situation? 

**To Reproduce**
1. define a Retrofit provider with Single
2. A user logged in and Okhttp have to set an authentication header
3. Because the Retrofit is Single the previous step only does in the first initialization

**Expected behavior**
Have a single instance of the Retrofit with dynamic headers by Okhttp

**Koin project used:**
```
    val koinVersion = "1.0.0"
    "org.koin:koin-androidx-viewmodel:$koinVersion"
    "org.koin:koin-android:$koinVersion"
    "org.koin:koin-core:$koinVersion"
```

**Comment by stelma** [comment]
Hi,

I would like to expand upon this question. We have a similar situation and actually unload and load our complete network module to solve changes for user and language settings.

```
fun reinitOkHttp(token: String, language: String) {
        unloadKoinModules(networkModule)
        val newNetworkModule = module {
                single { createOkHttpClient(ContentLanguageInterceptor(language), BaseAuthInterceptor(token)) }
                single { createWebService<SomeApi>(get(), BuildConfig.BASE_URL) }
                single { ApiWrapper(get(), get(), get()) as IService }
        }
        loadKoinModules(newNetworkModule)
    }
```

This does not work reliably, and we don't really have an explanation for it. What could be an obvious issue that we miss? Apparently koin just retains the original instances. This might be related to the behavour described below.

During the single creation, when we step through the code, we move on towards
```
 inline fun <reified T> single(
            qualifier: Qualifier? = null,
            createdAtStart: Boolean = false,
            override: Boolean = false,
            noinline definition: Definition<T>
    ): BeanDefinition<T> {
        ... 
 }
```
... then into 
```
  inline fun <reified T> createSingle(
            qualifier: Qualifier? = null,
            scopeName: Qualifier? = null,
            noinline definition: Definition<T>
    ): BeanDefinition<T> {
        return createDefinition(qualifier, definition, Kind.Single, scopeName)
    }
```
... and from there to 
```
 inline fun <reified T> createDefinition(
            qualifier: Qualifier?,
            noinline definition: Definition<T>,
            kind: Kind,
            scopeName: Qualifier?
    ): BeanDefinition<T> {
        val beanDefinition = BeanDefinition<T>(qualifier, scopeName, T::class)
        beanDefinition.definition = definition
        beanDefinition.kind = kind
        return beanDefinition
    }
}

```
After the line 
```
        val beanDefinition = BeanDefinition<T>(qualifier, scopeName, T::class)
```

There is always an exception:
```
"Method threw 'kotlin.UninitializedPropertyAccessException' exception. Cannot evaluate org.koin.core.definition.BeanDefinition.toString()
```

Even a nice suggestion how to debug this more easily would be much appreciated.

**Comment by arnaudgiuliani** [comment]
This is a regular case about http client instance .. did you think about unloading/loading the given module?

**Comment by QuarK264** [comment]
I have similar problem, but in my case when I try to relogin from default user to a new one, Authorization header is just missing.
