### ISSUE TITLE
The latest code base not included into 2.0.0

### ISSUE THREAD

**Issue by egorikftp** [InsertKoinIO/koin#469]
**Describe the bug**
I want to try the scoped feature with ViewModel. But in the release version 2.0.0, we still have old code with deprecation. 

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/16294951/58454895-89acf800-8128-11e9-8943-9ef427bee252.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Update to the stable 2.0.0 version
2. See error

Also, I see that something wrong version semantic in maven. The latest version now is 2.0.0-GA6.

![image](https://user-images.githubusercontent.com/16294951/58454854-6bdf9300-8128-11e9-84f0-2e1dfde5b251.png)
https://mvnrepository.com/artifact/org.koin/koin-androidx-viewmodel

**Expected behavior**
The latest stable version should contain the latest codebase.

**Comment by arnaudgiuliani** [comment]
Codebase is published on jcenter: https://bintray.com/ekito/koin/koin-android

Don't forget to include the jcenter() repository in your gradle config.
