### ISSUE TITLE
Use in Android application containing contentProviders

### ISSUE THREAD

**Issue by sebastienrouif** [InsertKoinIO/koin#470]
**Is your feature request related to a problem? Please describe.**
My application has multiple contentProvider which require injection. Therefore Koin needs to be started before. However, I can't make the contentProviders or my application class start Koin as it might get started multiple times and result in a `org.koin.core.error.KoinAppAlreadyStartedException: A Koin Application has already been started`

**Describe the solution you'd like**
The only approach I found, so far, is to create a specific content provider for injection with a high `initOrder` so that it happens first (a hacky approach used by firebase: https://firebase.googleblog.com/2016/12/how-does-firebase-initialize-on-android.html )
```
        <provider
            android:name=".InjectionProvider"
            android:authorities="${applicationId}.injection"
            android:initOrder="100000" />
``` 
But I was wondering if soemone thought about another one, and mybe that could be documented.

**Describe alternatives you've considered**
I don't see any other way

**Target Koin project**
2.0

**Comment by erickok** [comment]
Sounds like a good solution to me. What's the problem with it?

In general this is an Android question, rather than a Koin question.

**Comment by sebastienrouif** [comment]
I agree that it's more an Android question
However, the documentation says it should start from the application which is not always correct. Should I create a PR to update the documentation?
