### ISSUE TITLE
Test checkModules() fail for definition with parameter

### ISSUE THREAD

**Issue by asdfv** [InsertKoinIO/koin#473]
**Describe the bug**
Test checkModules() fail for definition with parameter:

`org.koin.core.error.InstanceCreationException: Could not create instance for [type:Single,primary_type:'com.example.koinchecktestfail.KoinDependenciesTest.MyPresenter']`
`Caused by: org.koin.core.error.NoParameterFoundException: Can't get parameter value #0 from org.koin.core.parameter.DefinitionParameters@424c0bc4`

**To Reproduce**
Run this test:
```kotlin
    @Test
    fun `check Modules`() {
        startKoin {
            modules(
                module { single { (repository: Repository) -> MyPresenter(repository) } }
            )
        }.checkModules()
    }

    class MyPresenter(private val repository: Repository) {
        fun takeLabel() = repository.getData()
    }

    class Repository {
        fun getData() = "Big data"
    }
```

**Expected behavior**
Test passed successfully

**Koin version:** 2.0.0

**Comment by Yazazzello** [comment]
But you don't pass the parameter. Take a look at test '`check a module with params`' in [CheckModulesTest.kt](https://github.com/InsertKoinIO/koin/blob/master/koin-projects/koin-test/src/test/kotlin/org/koin/test/CheckModulesTest.kt)

**Comment by asdfv** [comment]
@Yazazzello thanks, its works after this change:
```kotlin
    @Test
    fun `check Modules`() {
        startKoin {
            modules(
                module { single { (repository: Repository) -> MyPresenter(repository) } }
            )
        }.checkModules {
            create<MyPresenter> { parametersOf(Repository()) }
        }
    }
```
