### ISSUE TITLE
import org.koin.standalone.StandAloneContext is unresolved.  

### ISSUE THREAD

**Issue by techartist** [InsertKoinIO/koin#476]
**Describe the bug**
I'd like to use StandAloneContext.startKoin, but this is unresolved.  

**To Reproduce**

in my unit tests:  

StandAloneContext.startKoin { repositoryModule }

gradle files:

ext {
    koin_version = '2.0.0'
}
dependencies {  
   implementation "org.koin:koin-android:$koin_version"
    // Koin for Android Scope feature
    implementation "org.koin:koin-androidx-scope:$koin_version"
    implementation "org.koin:koin-androidx-viewmodel:$koin_version"
    testImplementation "org.koin:koin-test:$koin_version"
    androidTestImplementation "org.koin:koin-test:$koin_version"
}

**Expected behavior**
Able to use the standalone features.

**Comment by arnaudgiuliani** [comment]
`StandAloneContext` has been reworked as `GlobalContext` which is more understable

**Comment by techartist** [comment]
How do you start the application?  I can't find anything online that gives an example.

**Comment by cortinico** [comment]
> How do you start the application? I can't find anything online that gives an example.

Just use the `startKoin{ ... }` function: 
https://insert-koin.io/docs/2.0/quick-references/starting-koin/#how-to-start-koin

**Comment by techartist** [comment]
Actually, I am doing this from within an instrument test, that's why I am interested in using StandAloneContext (now GlobalContext).  How do I start Koin using GlobalContext?

**Comment by cortinico** [comment]
If you use `startKoin{...}` it will use the `GlobalContext` to start the application.
Source: https://github.com/InsertKoinIO/koin/blob/master/koin-projects/koin-core/src/main/kotlin/org/koin/core/context/GlobalContext.kt#L71
