### ISSUE TITLE
Dependency Graph Generator

### ISSUE THREAD

**Issue by tentenponce** [InsertKoinIO/koin#479]
I don't know if this is where I should raise this, but it seems that there's no other place to put this. This is actually not that much related in terms of actual feature for Koin to have. 

This is more of related on documentation and (coding principles, maybe). Is there any software or feature to generate a graph from my project integrated with Koin? There's one for [dagger](https://github.com/dvdciri/daggraph).

Advantages of this:

- You can easily check what are the classes that will affect if you modify a certain dependency.
- It will also serve as a documentation of the project, specially for new devs.
- You can also check your project architecture for improvement (easily identify cohesion and coupling).

If there's none, I'm thinking of creating this using p5.js (to render graph) and node.js (to read the project files).

**Comment by arnaudgiuliani** [comment]
Old logging system was doing it. But we remove it from the runtime to improve perfs.

Should be interesting to print the graph yeah.

**Comment by tentenponce** [comment]
Alright, I can't promise because I still didn't scope out everything. I might encounter problems specially on reading the project files. I'm too dumb on basic linux commands lol. But I'll try this one.

**Comment by tentenponce** [comment]
Hi @arnaudgiuliani , just a quick update on this, I've managed to create 3 graphs (like the one on daggraph), you can actually give it a try [here](https://github.com/tentenponce/KoinGraph#how-to-use).

It is not done yet though:

- Limitations:
  - modules registered with aliases (this is a bit hard)
  - reflections (this is easy, it should be... lol)
- Unit tests, of course
- Interactive CLI
- Thinking of publishing it also on NPM

Looking forward (and hoping I guess 🙏) for it to be the official Koin's UI graph generator 😄 😄.

Any feedback (positive or negative), suggestions or improvements are highly appreciated!

**Comment by tentenponce** [comment]
Sample images using KoinGraph on [koin-samples](https://github.com/InsertKoinIO/koin-samples):

![bubble-graph](https://user-images.githubusercontent.com/5518758/59149695-76b0f680-8a4b-11e9-889a-f4224c44773e.PNG)
![link-node-graph](https://user-images.githubusercontent.com/5518758/59149696-76b0f680-8a4b-11e9-8ffa-d44fd76a564d.PNG)
![tree-graph](https://user-images.githubusercontent.com/5518758/59149697-77498d00-8a4b-11e9-96b7-962f45fb1af2.PNG)

**Comment by tentenponce** [comment]
Closing this issue as this was already done. Any issues can be raised [here](https://github.com/tentenponce/KoinGraph/issues). Thanks 😄

**Comment by arnaudgiuliani** [comment]
Hi @tentenponce really interesting to see (sorry for the delay)

Is it still active? I can add you (at least) on the main page, as referred as tool for Koin 👍

**Comment by tentenponce** [comment]
> Hi @tentenponce really interesting to see (sorry for the delay)
> 
> Is it still active? I can add you (at least) on the main page, as referred as tool for Koin 👍

Yes, this is still active 😄 

That would be nice! I will highly appreciate it 😄
