### ISSUE TITLE
ViewModel injection from Java class.

### ISSUE THREAD

**Issue by paolop** [InsertKoinIO/koin#480]
I'm not able to properly retrieve a ViewModel from a Java class. I'm following this guide https://insert-koin.io/docs/2.0/getting-started/android-java/ I suspect this approach does not work for ViewModels since I'm receiving a new instance every time thus loosing the LiveData payload after the Activity gets recreated after a configuration change. Is there somewhere a documentation for injecting ViewModels in Java classes?

This is how the module is declared: 
val unlockScreenViewModelModule: Module = module {
   viewModel { UnlockScreenViewModel<DomainObject>(androidApplication(), get()) } // get() asks Koin to find the dependency among the declared modules (See Koin.kt)
   single {
      @Suppress("UNCHECKED_CAST")
      BusinessRepositoryImpl(get()) as BusinessRepository<DomainObject>
   }
}

**Comment by arnaudgiuliani** [comment]
The `koin-java` package doesn't cover the ViewModel features for now. Best would be to document what we have to help and/or provide some JVM friendly functions.

**Comment by arnaudgiuliani** [comment]
Has been integrated into 2.1.0.
