### ISSUE TITLE
Koin 2.0.1 is introducing breaking changes in modules(vararg Module)

### ISSUE THREAD

**Issue by cortinico** [InsertKoinIO/koin#482]
(thanks for the great library @arnaudgiuliani )

**Describe the bug**
Looks like Koin version `2.0.1` has breaking changes. I don't know if this was expected given the patch version bump, so that's why I'm reporting it (it's basically breaking the semantic versioning of the library).

Apparently the method in `KoinApplication`
```
fun modules(vararg modules: Module): KoinApplication
```
Has been removed. 

Ideally we should probably deprecate it instead of removing. Removing this method should probably imply a major/minor version bump and not a patch version bump.

The method have been removed here: b0a7592cc69df243ab1047936073e038941c3014
It would be helpful to understand why exactly the method was removed and if the API change was intentional.

**To Reproduce**
The following code complies with Koin `2.0.0` and it doesn't with Koin `2.0.1`
```kotlin
fun main() {
    val moduleA = module { single { arrayListOf("a") } }
    val moduleB = module { single { arrayListOf(1) } }

    startKoin {
        modules(moduleA, moduleB)
    }
}
```

**Expected behavior**
Either the `modules(vararg Modules)` should be deprecated or it should be re-introduced in a future version (e.g. `2.0.2` so going from `2.0.0` -> `2.0.2` won't be a breaking change?)

**Koin project used and used version (please complete the following information):**
`koin-core version 2.0.0` & `2.0.1`

**Related Issues**
Definitely related to #481 (reintroducing the `module(vararg Module)` method).

**Comment by arnaudgiuliani** [comment]
Hi @cortinico 

you can use the "+" operator with modules. it make a list directly for you.

`modules(moduleA + moduleB)`

In terms of performances, it avoids the * operator with vararg table. If people really missed it, no problem to put it back.

**Comment by cortinico** [comment]
> In terms of performances, it avoids the * operator with vararg table. If people really missed it, no problem to put it back.

Thanks for the heads up.

Actually, I opened this issue more to discuss and understand what's the versioning policy of Koin. Is there a reason why this change was included in a `2.0.1` and not a `2.1.+` or `3.+`?

**Comment by TSurkis** [comment]
Hi @arnaudgiuliani 

I think it is best to have both ways - the "," and "+" ways. Furthermore, the "+" method seems a bit unnatural in my opinion so most users might want the old comma separated way.

I opened a pull request which was referenced in this issue.
I would love to hear your input.

**Comment by arnaudgiuliani** [comment]
ok thanks @TSurkis , will check that for next patch 👍

**Comment by redwarp** [comment]
@cortinico raises a good question about the meaning of patch vs minor vs major.

This is a breaking change, should a patch introduce a breaking change?
For my own app, I'm updating from 2.0.0-GA to 2.0.1 so I expected things to break, but not because of a patch version update :-)

**Comment by arnaudgiuliani** [comment]
closing this, as we continue on PR
