### ISSUE TITLE
typeOf<reified T>() Kotlin 1.3.40

### ISSUE THREAD

**Issue by IVIanuu** [InsertKoinIO/koin#484]
Kotlin 1.3.40 will introduce a typeOf<reified T>() function which allows to get the real type of T including generic parameters.

It would be cool if koin makes use of it in some way.

https://youtrack.jetbrains.com/issue/KT-29915

**Comment by arnaudgiuliani** [comment]
Hi @IVIanuu , effectively very interesting.

A good try should be done, to help the resolution engine and check also performances impact.

**Comment by drieks** [comment]
We should wait until `typeOf` is supported by native and javascript. Otherwise, we will introduce more problems for multi platform support / koin 3.0.0 (#524)

**Comment by arnaudgiuliani** [comment]
sure, and it's heavily reflection oriented ... I'm waiting a clear usecase for that

**Comment by arnaudgiuliani** [comment]
let's keep it in mind for later 👍
