### ISSUE TITLE
beta.insert-koin.io/docs/2.0/quick-references/ page is 404

### ISSUE THREAD

**Issue by curliq** [InsertKoinIO/koin#489]
**Describe the bug**
Page at https://beta.insert-koin.io/docs/2.0/quick-references/ is 404

**To Reproduce**
1. Go to https://beta.insert-koin.io/docs/2.0/quick-references/

**Expected behavior**
Documentation page

**Actual behavior**
404

**Comment by arnaudgiuliani** [comment]
you can use the main website instead. But yeah, would require a redirect.

**Comment by arnaudgiuliani** [comment]
`beta` website is offline. Please use the https://insert-koin.io/ website

**Comment by dave-kennedy** [comment]
So where would I find https://insert-koin.io/docs/2.0/quick-references/upgrade/ for instance?
