### ISSUE TITLE
Injecting functions

### ISSUE THREAD

**Issue by jjrodcast** [InsertKoinIO/koin#495]
Is it possible to inject functions in Koin 2.0.1 from a kotlin file. For example to create retrofit instances.

     private fun createRetrofit(httpClient: OkHttpClient, baseUrl: String): Retrofit {
        return Retrofit.Builder()
            .client(httpClient)
            .baseUrl(baseUrl)
            .addConverterFactory(GsonConverterFactory.create())
            .build()
    }

    private fun createRetrofit1(httpClient: OkHttpClient): Retrofit {
        return createRetrofit(httpClient, BuildConfig.URL1)
    }

    private fun createRetrofit2(httpClient: OkHttpClient): Retrofit {
        return createRetrofit(httpClient, BuildConfig.URL2)
    }

     private fun createOkHttpClient(): OkHttpClient{ ... }

I would like to have something like this:

`     

    val apiModule = module {
    single(named("Client1)) { createOkHttpClient()  }

    single(named("Client2)) { createOkHttpClient()  }

    single(named("Retrofit1")) {  createRetrofit1(get(named("Client1))))  }

    single(named("Retrofit2")) {  createRetrofit2(get(named("Client2))) }
    }

`

**Comment by cortinico** [comment]
Hey @jjrodcast 
That is already doable with Koin. You can create your apiModule in this way:

```
val apiModule = module {
    single(named("Client1")) { createOkHttpClient()  }
    single(named("Client2")) { createOkHttpClient()  }
    single(named("Retrofit1")) {  createRetrofit1(get(named("Client1")))  }
    single((named("Retrofit2")) {  createRetrofit2(get(named("Client2"))) }
}
```

**Comment by jjrodcast** [comment]
@cortinico for some reason im getting an error when testing the dependencies, I debuged and koin can't resolve because of some scope or class definition.

**Comment by cortinico** [comment]
@jjrodcast Can you provide the error message?
I tested the code I suggested you and I got no problem running it.

**Comment by jjrodcast** [comment]
Ok I will send the error

**Comment by jjrodcast** [comment]
@cortinico this is the error:

    org.koin.core.error.NoBeanDefFoundException: No definition found for 
    'pe.com.swipe.data.network.BinService' has been found. Check your module definitions.
     at org.koin.core.scope.Scope.findDefinition(Scope.kt:170)
     at org.koin.core.scope.Scope.resolveInstance(Scope.kt:164)
     at org.koin.core.scope.Scope.get(Scope.kt:128)
     at pe.com.swipe.merchant.KoinModulesTest.probando test de api Bin(KoinModulesTest.kt:26)
     ....

**Comment by cortinico** [comment]
So the error you have is descriptive enough:
`No definition found for '....data.network.BinService' has been found. Check your module definitions`

So in your `KoinModulesTest.kt` you're initializing a Koin application and you're not providing any instance of type `BinService`. 

I advice you check your module configuration and make sure you're providing all the needed dependencies for your module.

**Comment by jjrodcast** [comment]
For sure, testing dependencies it doesn't fail.
