### ISSUE TITLE
Different behaviour for lifecycleOwner.getViewModel

### ISSUE THREAD

**Issue by dapacheco** [InsertKoinIO/koin#497]
**Describe the bug**
In Koin v2 `LifecycleOwner.getViewModel` behaves differently than the equivalent `LifecycleOwner.getViewModelByClass` call.

**To Reproduce**
Steps to reproduce the behaviour:
Checkout the sample project that shows the different behaviour between Koin v1.0.2 and Koin v2.0.1

https://github.com/dapacheco/Koin-ViewModel-Sample

There are two branches for the different versions. The sample app makes use of two ViewModels that are defined in a module

```
viewModel(name = "TileA") { TileAViewModel("A") }
viewModel(name = "TileB") { TileBViewModel("B") }
```

Four instances, two each, of the ViewModels are then created using the LifeCycleOwner extension functions (see links below to the different Provider classes).

In v1 API it is possible to pass a key in addition to a name qualifier and doing so results in four different instances being created.

In v2 it is no longer possible to pass a key, just the name qualifier and so only two instances are created.

https://github.com/dapacheco/Koin-ViewModel-Sample/blob/koin2/app/src/main/java/com/davepacheco/koinsample/model/ProviderKoin2.kt

https://github.com/dapacheco/Koin-ViewModel-Sample/blob/koin1/app/src/main/java/com/davepacheco/koinsample/model/ProviderKoin1.kt

**Expected behaviour**
v2 API should allow for providing a key when calling `ViewModelProvider.get` which is different from the name qualifier as was the case in v1.

**Koin project used and used version (please complete the following information):**
`koin-core version 2.0.1`

**Comment by arnaudgiuliani** [comment]
in Koin 2.x, the ViewModel key instance attribute is given by the qualifier of the ViewModel:

```
viewModel(named("vm1")) { (id: String) -> SimpleViewModel(id, get()) }
viewModel(named("vm2")) { (id: String) -> SimpleViewModel(id, get()) }
```

here we use 2 keys to isolate each ViewModel instance.

**Comment by arnaudgiuliani** [comment]
we continue on linked issue about Key handling #782
