### ISSUE TITLE
paramterized injection inside viewmodel

### ISSUE THREAD

**Issue by droidluv** [InsertKoinIO/koin#498]
suppose I have  a module
```
val module = module {
scope(named<SomeActivty>()){
viewModel { SomeViewModel(get(), get()) }
scoped { (lifecyclescope, someparam) -> SomeClass(lifescyclescope, someparam, get())}
}
}
```

and viewModel
```
SomeViewModel(val injectedDependency1, val injectedDependency2): ViewModel{

val someObject: SomeClass by inject(viewModelScope, identifier) //How to do this or something similar

}
```
 how do I do this 
val someObject: SomeClass by inject(viewModelScope, identifier) //This part

I tried making viewmodel extend KoinComponent but the injection is just failing, is there a correct way of doing this?

**Comment by arnaudgiuliani** [comment]
did you check that? https://insert-koin.io/docs/2.0/documentation/reference/index.html#_injection_parameters

**Comment by droidluv** [comment]
@arnaudgiuliani I have checked it, infact you can see I am attempting parameterized injection, by passing the viewModelScope which is available only for a viewModel with a lifecycle, the thing is I can't extend the ViewModel class with KoinComponent,and because the viewmodel itself is injected by the view controller(activity or fragment by using "by viewModel{}")
