### ISSUE TITLE
viewModel definitions are not properly reloaded

### ISSUE THREAD

**Issue by Pantkowsky** [InsertKoinIO/koin#501]
**Describe the bug**
`viewModel` definitions are not properly reloaded. Calling unloadKoinModules() followed by loadKoinModules() does reload the `single` instances, but not viewModels. The `viewModel` definitions after said reloading, when accessed hold the same reference as prior to the reloading, and furthermore hold the cached data they may or may not held prior to the koin module reloading.  

**To Reproduce**
1. Load a given koin module, that includes a `single` and `viewModel` definitions
2. Inject the `viewModel` in the given context (bug appears specifically in the `Fragment` environment). 
3. Make sure to navigate away from the given context
4. Reload the given koin module, by calling `unloadKoinModule(your_module)` followed by `loadKoinModule(your_module)` 
5. Navigate to the context in which the `viewModel` is injected.
6. See that the `single` definition has been `init` again and therefore reloaded -> see that the `viewModel` definition has not been `init` again, and the injected `viewModel` holds the same reference as prior to reloading the module

**Expected behavior**
The expected behavior is for all definitions that are members of the given module that is to be reloaded, to be re-instantiated. The expected behavior holds for `single` definitions, however not for the `viewModel` definitions. By calling `unloadKoinDependencies()` followed by `loadKoinDependencies()`, I expect to get a new instance of the injected dependencies.

**Koin project used and used version (please complete the following information):**
 `koin-android 2.0.0-GA3`
 `koin-viewmodel 2.0.0-GA3`

**Additional moduleDefinition**
 The module is defined as
`myModule = module(override = true) {
   single { ComponentA() }
   viewModel { ViewModelA() }
}`

**Comment by Pantkowsky** [comment]
After digging much more into this issue, I've found that this particular problem exists **only** with the _sharedViewModel_ delegate. The module gets reloaded just fine for `single` and `viewModel` definitions, however in case where the viewModel gets injected with using `by sharedViewModel`, then the reloading of the module does not work.

**Comment by arnaudgiuliani** [comment]
this case is "normal", as Koin don't hold any instances for ViewModels. If we reload, we loose everything

**Comment by Pantkowsky** [comment]
Not sure if I follow -> after reloading the koin modules, I can determine, that viewmodels loaded through `by viewModel()` delegate get re-initialized, however the viewmodels that are loaded through `by sharedViewModel` are not. By re-initialized I mean that the `init{}` block will be executed. 

Is that the expected behaviour? If so, then why does it differ between viewModels and sharedViewModels? How can a `sharedViewModel` be reloaded then?

Let's say that I have a flow:

`FragmentA -> FragmentB -> FragmentC`

They are contained in a sort-of coordinator component that has three triggers:
`onStart` -> launches `FragmentA` and loads necessary koin dependencies
`onFinish` -> unloads necessary koin dependencies
`onRestart` -> reloads koin dependencies and launches `FragmentA` ultimately resetting the flow. 

Let's assume that `onRestart` can be called from `FragmentC`. `FragmentC` contains a `viewModel` that is injected with `by sharedViewModel`. How can this viewmodel be reloaded as a koin module when calling `onRestart` then? 

In the above example, when calling `onReset`, all of the instances from the provided koin modules will be reloaded and re-initialized, except the `sharedViewModel`.

**Comment by arnaudgiuliani** [comment]
We can't "reload" as is. We have to drop instances and recreated it. Your sharedViewModel instances are still kept by your current component.

**Comment by Pantkowsky** [comment]
I understand that and that is precisely what I'm trying to find out how to do -> how to drop and recreate an instance of a `sharedViewModel`. By "reloading" I mean dropping and recreating an instance of an injected component. I can see that the `sharedViewModel` is attached to the current `Activity` -> how can it be recreated if I only have a single `Activity` in my project?

**Comment by Pantkowsky** [comment]
@arnaudgiuliani would you be able to add your comment to the above? :)

**Comment by arnaudgiuliani** [comment]
then shared ViewModel is not what you need, if you have only one Activity :)

Better is to consider perhaps Scope API instead? 🤔 Or even perhaps more load/unload module for definitions & instances

**Comment by Pantkowsky** [comment]
Thanks for the comments @arnaudgiuliani 

From what I understood about the documentation, `sharedViewModel` was what I was looking for, however it is possible that I misunderstood it.

I'm using the `sharedViewModel` for a usecase in which a list of items is displayed, and clicking on each displays that single item details view. For that reason I went with `sharedViewModel`, since it contains a great portion of logic _shared_ by both views, which I did not want to duplicate, if I went with a separate `viewModel` per each of these views.

Will look closer into the Scope API. I'm not sure what exactly do you have in mind by _"more load/unload module for definitions & instances"_ -> could you elaborate?

**Comment by arnaudgiuliani** [comment]
sharedViewModel with share a ViewModel instance with the parent Activity. Then your ViewModel won't be recreated until your parent activity has been completely recreated. Perhaps here a solution: try to finish & start your Activity to restart it.

Else Koin offers 2 ways to deal with definitions other than single:
- Scope API - https://insert-koin.io/docs/2.0/quick-references/scopes/
- Dealing with modules definitions directly, by load and unload of definitions with `single` - https://insert-koin.io/docs/2.0/quick-references/modules-definitions/#dropping-definitions--modules---definitions-unload

**Comment by Pantkowsky** [comment]
I can't really finish & restart the `Activity`, since I only have one activity in the project, and I need that functionality to be triggered on user logout -> one of the features in my project is that the user should be able to logout from his account. This where I need these instances to be droped and recreated, but since the app session is still ongoing, the activity won't be destroyed. 

Thanks for your suggestions, appreciate the effort and help :) will look closer into the Scope API and if I come up with anything good, will post it here for future reference

**Comment by arnaudgiuliani** [comment]
keep us in touch 👍

**Comment by 7alma9z** [comment]
> I can't really finish & restart the `Activity`, since I only have one activity in the project, and I need that functionality to be triggered on user logout -> one of the features in my project is that the user should be able to logout from his account. This where I need these instances to be droped and recreated, but since the app session is still ongoing, the activity won't be destroyed.
> 
> Thanks for your suggestions, appreciate the effort and help :) will look closer into the Scope API and if I come up with anything good, will post it here for future reference

have you found any way to do this ? i am also stuck in this issue with single activity arch.
