### ISSUE TITLE
infinite recursion

### ISSUE THREAD

**Issue by valeriyo** [InsertKoinIO/koin#504]
**Describe the bug**
This BeanRegistry method (called by `Scope.resolveInstance`) returns an instance of a wrong type - that happens to have the same qualifier:
```
    /**
     * Find a definition
     * @param qualifier
     * @param clazz
     */
    fun findDefinition(
            qualifier: Qualifier? = null,
            clazz: KClass<*>
    ): BeanDefinition<*>? {
        return if (qualifier != null) {
            findDefinitionByName(qualifier.toString())
        } else {
            findDefinitionByType(clazz) ?: findDefinitionBySecondaryType(clazz)
        }
    }
```
This seems just plain wrong. The type and qualifier should be AND'ed, not OR'ed.

**Koin project used and used version (please complete the following information):**
  version 2.0.1

**Comment by valeriyo** [comment]
repro:
```
val mainModule = module {
  single<Int>(named("foo")) {
    123
  }

  scope(named("bar")) {
    scoped<String>(named("foo")) {
      val foo: Int = get(named("foo"))
      foo.toString()
    }
  }
}
```

and then

```
    loadKoinModules(mainModule)
    val bar = getKoin().createScope("bar", named("bar"))
    val foo = bar.get<String>(named("foo"))
```

Without "bar" scope, this would generate a "DefinitionOverrideException: Already existing definition or try to override an existing one with qualifier 'foo' ... ".  So, it looks like two different things cannot be `named` the same? Why? What's the thinking there?

**Comment by arnaudgiuliani** [comment]
> So, it looks like two different things cannot be named the same? Why? What's the thinking there?
Yes, for now a qualifier (`named()` function dsl) is unique. The only way to override this is to redefine it in a scope.
