### ISSUE TITLE
Testing Ktor application fails with "A Koin Application has already been started"

### ISSUE THREAD

**Issue by RoRoche** [InsertKoinIO/koin#507]
I am trying to unit test a ktor application powered by koin, described as follows:

- The `gradle.properties`:

```
ktor_version=1.2.2
kotlin_version=1.3.40
logback_version=1.2.1
```

- The `build.gradle`'s dependencies:

```kotlin
dependencies {
    compile("org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version")
    compile("io.ktor:ktor-server-netty:$ktor_version")
    compile("ch.qos.logback:logback-classic:$logback_version")
    compile("org.koin:koin-ktor:2.0.1")
    testCompile("io.ktor:ktor-server-tests:$ktor_version")
    testCompile("org.koin:koin-test:0.9.3")
}
```

- The `resources/application.conf`:

```
ktor {
    deployment {
        port = 8080
    }
    application {
        modules = [com.example.MainApplicationKt.main]
    }
}
```

- The `com.example.MainApplication.kt`:

```kotlin
package com.example

// imports...

interface HelloController {
    suspend fun onGetHello(call: ApplicationCall)
}

class DefaultHelloController() : HelloController {
    override suspend fun onGetHello(call: ApplicationCall) {
        call.respondText("Hello World!")
    }
}

fun main(args: Array<String>) {
    embeddedServer(Netty, commandLineEnvironment(args)).start()
}

fun Application.main() {
    install(DefaultHeaders)
    install(CallLogging)
    install(org.koin.ktor.ext.Koin) {
        modules(helloModule)
    }
    val helloController: HelloController by inject()
    routing {
        get("/hello") {
            helloController.onGetHello(call)
        }
    }
}
```

- and finally the `MainApplicationTest.kt`:

```kotlin
class MainApplicationTest {

    private object MockHelloController : HelloController {
        override suspend fun onGetHello(call: ApplicationCall) {
            call.respondText("Mocked Hello World!")
        }
    }

    @Before
    fun setup() {
        val mockHelloModule = module {
            single<HelloController> { MockHelloController }
        }
        startKoin {
            listOf(mockHelloModule)
        }
    }

    @After
    fun teardown() {
        stopKoin()
    }

    @Test
    fun testRequestsOK() = withTestApplication(Application::main) {
        with(handleRequest(HttpMethod.Get, "/hello")) {
            assertEquals(HttpStatusCode.OK, response.status())
            assertEquals("Mocked Hello World!", response.content)
        }
    }
}
```

When running the unit test, I get the following exception:

```
org.koin.core.error.KoinAppAlreadyStartedException: A Koin Application has already been started
```

What is the proper way to setup my unit tests?

Thanks in advance,
Regards,
Romain

**Comment by arnaudgiuliani** [comment]
`withTestApplication(Application::main)` already run your app, try to use `loadKoinModules` instead of starting Koin

**Comment by RoRoche** [comment]
Thanks, it works but:
- I can't do it in the `@Before` because of a `IllegalStateException: KoinApplication has not been started`
- I have to explicitely unload the production module before loading the mock one

**Comment by arnaudgiuliani** [comment]
> I have to explicitely unload the production module before loading the mock one

Another way is to close koin and start it with the needed modules?

**Comment by bio007** [comment]
I'm facing similar problem with robolectric. See this issue https://github.com/robolectric/robolectric/issues/3108

I think it's a problem Koin is having some static variables remembering previous runs (tests). This way the tests are not isolated and something can go wrong...

**Comment by iRYO400** [comment]
@bio007 did you find a workaround?

**Comment by iRYO400** [comment]
I found why Koin is being started in my not-Koin tests. It's because of `ApplicationProvider.getApplicationContext()`. As described [here](https://developer.android.com/training/testing/junit-runner#app-context) `If you've created a custom subclass of Application in your app, this method returns your custom subclass's context.`

I have init Koin function call in my Application class.

**Comment by iRYO400** [comment]
Oops, that was easier than I thought.
Just add `stopKoin()` inside
```
    @After
    fun tearDown() {}
```

**Comment by Bennik2000** [comment]
If there are several test cases per test class use:

```
@AfterEach
fun tearDown() {
    stopKoin()
}
```
