### ISSUE TITLE
CustomSDK example - AndroidContext?

### ISSUE THREAD

**Issue by fernandospr** [InsertKoinIO/koin#508]
What if you need the android context in your isolated SDK for Android?
For example, a Repository class that needs the context to save to `SharedPreferences`.

I couldn't see an example here:
https://github.com/InsertKoinIO/koin/blob/master/koin-projects/examples/android-samples/src/main/java/org/koin/sample/android/components/sdk/CustomSDK.kt

Please, can you kindly suggest how to do that?

**Comment by arnaudgiuliani** [comment]
just build your KoinApplication instance with a `Context` argument:

```kotlin
fun createKoin(context : Context){
val koinApp = koinApplication {
        printLogger(Level.DEBUG)
        androidContext(context)
        modules(sdkModule)
    }
//...
}
```

**Comment by fernandospr** [comment]
@arnaudgiuliani Thanks. This is how I solved it, based on the SDK sample and the internals of Koin.

```kotlin
// Custom Koin instance Holder
object CustomSDK {
    internal var app: KoinApplication? = null

    @JvmStatic
    fun start(applicationContext: Context) {
        app = buildKoinApplication(applicationContext)
    }

    @JvmStatic
    fun stop() = synchronized(this) {
        app?.close()
        app = null
    }

    @JvmStatic
    fun get(): KoinApplication = app
            ?: error("KoinApplication for CustomSDK has not been started")

    private fun buildKoinApplication(applicationContext: Context): KoinApplication {
        return koinApplication {
            androidContext(applicationContext)
            modules(sdkModule)
        }
    }
}

val sdkModule = module {
    single<Service> { ServiceImpl() }
    single { SDKService() }
    viewModel { SDKVIewModel(get()) }
}

// Custom KoinComponent
interface CustomKoinComponent : KoinComponent {
    override fun getKoin(): Koin = CustomSDK.get().koin
}

class CustomService : CustomKoinComponent {
    val service: Service by inject()
}
```

It's **important** to call `CustomSDK.start(this)` inside the Application's `onCreate()` to make sure that it's always started even when the app is restarted by Android.

```kotlin
class BaseApplication : Application() {
    override fun onCreate() {
        super.onCreate()
        ...
        CustomSDK.start(this)
    }
}
```

Maybe you'd like to mention that [here](https://insert-koin.io/docs/2.0/documentation/reference/index.html#_koin_context_isolation).

Also [here](https://insert-koin.io/docs/2.0/quick-references/starting-koin/#starting-koin-for-android), it states that you should start Koin 'In any Android class'. However, the safest place to start Koin is in Application's `onCreate()`. If you don't do it there, for example, you start Koin (globally or isolated) in ActivityA, then go to ActivityB and you switch to other app or go to home, Android may kill your app and when you go back to your app, it will recreate ActivityB, but Koin is not started, so it will crash.

**Comment by ritesh-singh** [comment]
@fernandospr I am using the same approach to have multiple dependency graph. 
However, my dryRunTest() (extending from kointest) which does checkModule() fails.

**Comment by arnaudgiuliani** [comment]
@ritesh-singh please open a ticket for that topic
