### ISSUE TITLE
NoBeanDefFoundException for beans defined in another module without explicit super type.

### ISSUE THREAD

**Issue by nocach** [InsertKoinIO/koin#509]
**Describe the bug**
NoBeanDefFoundException is thrown for beans defined in another module without explicit super type.

**To Reproduce**
```
interface Repository
class DataRepository : Repository
interface Presenter
class MyPresenter(val repository : Repository) : Presenter

val module1 = module {
 //this throws NoBeanDefFoundException 
    single { DataRepository() }
//this works
//    single { DataRepository() } bind Repository::class 
}
val module2 = module {
    factory<Presenter> { MyPresenter(get()) }
}

fun main(vararg args: String) {

    // Start Koin
    startKoin {
        modules(listOf(module1, module2))
    }.koin.get<Presenter>()

}
```

**Expected behavior**
If moduleB defines bean B that implements super type A used in module A, Koin should wire B as a dependency A in moduleA without additional info. Currently you have to modife moduleB with explicit `bind A` for this to work

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core version 2.0.1`

**Comment by arnaudgiuliani** [comment]
Normal case, as you have to be explicit to provide types: Koin doesn't guess type by introspection.

either use `single<Repository> { DataRepository() }` or `single { DataRepository() } bind Repository::class`

1st give a definition for the `Repository` strictly
2nd give a definition that matches both types
