### ISSUE TITLE
[What's next] Releases 2.1.x & 3.x

### ISSUE THREAD

**Issue by arnaudgiuliani** [InsertKoinIO/koin#510]
Hello all :)

Hope you enjoy this [new version of Koin](https://medium.com/koin-developers/ready-for-koin-2-0-2722ab59cac3). Here is how we will handle the next versions and what we will develop and each of them. Begin to gather feature proposals & requests:

[2.1.x](https://github.com/InsertKoinIO/koin/milestone/14) - will target minor features:
- will mainly gather bugfixes for the current version, as tagged in the current board
- android viewmodel factory handling states (proposal already open here: https://github.com/InsertKoinIO/koin/pull/496
- android fragment factory?
- more global viewModel dsl factory for Android? optimise viewmodel factory to avoid recreate it each time
- inject for navGraph - https://github.com/InsertKoinIO/koin/issues/442
- viewModel functions for Java - https://github.com/InsertKoinIO/koin/issues/480
- integration for TornadoFX
- better koin-ext features / better performances
- better mocking - https://github.com/InsertKoinIO/koin/issues/450
- better logging - https://github.com/InsertKoinIO/koin/issues/421

About Koin as a multiplaform library, we have to check if it breaks lots of what we have. In that case, we would plan it for [3.0.0](https://github.com/InsertKoinIO/koin/milestone/16).

All of this is open to contribution. Feel free to propose your contributions (contact us by posting below or via Kotlin slack).

This post will be regularly updated. 

Cheers.

**Comment by drieks** [comment]
Hi, I started to work on 3.0.0 in #519

**Comment by kpgalligan** [comment]
Good place to talk about multiplatform? Tracking issue? Slack? I have thoughts.

**Comment by arnaudgiuliani** [comment]
Will ship directly a `2.1.0` to gather latest fixes & updates (all contribution around), and queeze `2.0.2` in it 👍

**Comment by giorgosTh** [comment]
Any eta for 2.1.0? Wanna try the saved state handle with koin!

**Comment by arnaudgiuliani** [comment]
I will manage to publish some alpha for the current 2.1.0 soonly, in the next days.

**Comment by TurKurT656** [comment]
is there an example for navGraph implementation?

**Comment by arnaudgiuliani** [comment]
Hey @TurKurT656
 
> is there an example for navGraph implementation?
not for now, an external contribution can be done for that 👍

**Comment by TheScriptan** [comment]
Any reason why org.koin:koin-java is at 2.1.0-alpha-2 while other packages are at alpha-6?

**Comment by arnaudgiuliani** [comment]
`koin-java` helpers will be integrated into koin-core for 2.1.0

**Comment by arnaudgiuliani** [comment]
Changelog has to be updated to help understand last changes
