### ISSUE TITLE
Add License block to pom.xml

### ISSUE THREAD

**Issue by EmmettWilson** [InsertKoinIO/koin#511]
**Is your feature request related to a problem? Please describe.**
Many projects use plugins to generate their Open Source Licenses attribution page in their application. A common way to do this is to inspect the `pom.xml` in the `.aar` or `.jar`. Please add the license block when releasing the project so it is picked up by the tooling. 

See:
https://github.com/jaredsburrows/gradle-license-plugin
https://github.com/google/play-services-plugins/tree/master/oss-licenses-plugin

**Target Koin project**
All sub projects should include this in their deployed `.jar` or `.aar`

**Comment by arnaudgiuliani** [comment]
ok, effectively. Not really really blocking ...
