### ISSUE TITLE
Nested Scopes

### ISSUE THREAD

**Issue by valeriyo** [InsertKoinIO/koin#513]
**Is your feature request related to a problem? Please describe.**
Currently, with Koin 2.0 it's possible to declare nested scopes:

```
module {
    scope(A) {
        scoped(NUMBER) { 123 }

        // nested scope!
        scope(B) {
            scoped(STRING) { get(NUMBER).toString() }
        }
    }
}
```

With implied understanding that:
1) An instance of scope B can be created from an instance of scope A (but not from the global Koin),
2) Scope B "sees" all bindings from scope A.
3) Closing an instance of scope A would close all instances of B, which were created from it (i.e. child scopes)

However, that's not what's happening. In Koin 2.0, the above DSL is equivalent to:

```
module {
    scope(A) {
        scoped(NUMBER) { 123 }
    }

    // actually, it's not nested :(
    scope(B) {
        scoped(STRING) { get(NUMBER).toString() }
    }
}
```

... and at runtime, the `get(NUMBER)` will throw a `NoBeanDefFoundException`.

Koin should do better than that.

**Describe the solution you'd like**
Nested scoped should be supported. For that, two things are necessary:
  1. `ScopeSet` needs to define `fun scope` similar to `Module`.
  2. `Scope` needs to define `fun createScope` similar to `Koin` - for the nested scopes.

**Describe alternatives you've considered**
An alternative to nested scopes is doing extra work (like duplicating same bindings across multiple scopes - but that will break singletons)

**Comment by valeriyo** [comment]
The approach I settled on is:

```
module {
    scope(A) {
        scoped(NUMBER) { 123 }
    }

    // actually, it's not nested :(
    scope(B) {
        // poking into the A scope, since nested scopes do not work
        scoped(NUMBER) { scopeA.get<Int>(NUMBER) }

        scoped(STRING) { get(NUMBER).toString() }
    }
}
```

where `scopeA` is doing something like `GlobalContext.get().koin.getScope("A")` - assuming, there is an instance of scope A with name "A".

**Comment by arnaudgiuliani** [comment]
the most difficult part here is to avoid mixing scope instance id and scope qualifier: The DSL allow you to define a scope with a qualifier. A scope instance id is created/given at runtime.

**Comment by arnaudgiuliani** [comment]
this will be redesign as "Scope Links", to let you establish links between your scope instances.

**Comment by aisanu** [comment]
What's the status of this "Scope Links" stuff? Anywhere i could read the docs or at least the implementation code/related PR and the architecture design for this feature?

**Comment by kepovilaitis** [comment]
any news?

**Comment by nschwermann** [comment]
Says complete in 2.1 but still not working. calling linkTo in checkModules test throws koinContext not created exception
