### ISSUE TITLE
Does koin support dynamic type binding?

### ISSUE THREAD

**Issue by kobevaliant** [InsertKoinIO/koin#514]
Hi,
I need to bind type which is only known in runtime.
In module defination
```
val mod = module {
  val kls:KClass<*> = ... //to get in runtime
  val inst:Any = ...//to get in runtime of type kls
  //here how can I bind them?
}
```

**Comment by cortinico** [comment]
Hey @kobevaliant 
Have you tried using `declare()`?

**Comment by kobevaliant** [comment]
Hi, Sorry but I can not find the `declare` method, where is it?

**Comment by cortinico** [comment]
You can use the one inside the `Koin` class

https://github.com/InsertKoinIO/koin/blob/1566605f8e8046f67579e414138e771dd5453624/koin-projects/koin-core/src/main/kotlin/org/koin/core/Koin.kt#L119-L126

or the one inside the `Scope` class:

https://github.com/InsertKoinIO/koin/blob/1566605f8e8046f67579e414138e771dd5453624/koin-projects/koin-core/src/main/kotlin/org/koin/core/scope/Scope.kt#L197-L211

**Comment by arnaudgiuliani** [comment]
anything else?
