### ISSUE TITLE
Where is the setProperty() at latest stable 2.0.1 version?

### ISSUE THREAD

**Issue by zhombie** [InsertKoinIO/koin#523]
First of all, I want to say thank you.

How I can add dynamic parameters, there was a feature at version 1.0.2, extension function setProperty(), which allows to send parameters into injected constructor()

**Comment by akotsuba** [comment]
@zhombie Use getKoin().setProperty(...)

**Comment by zhombie** [comment]
@akotsuba i have also found the another way:
viewModel { (parameter: Object) -> ViewModel(parameter) }
val viewModel by viewModel<ViewModel> { parametersOf(parameter) }

something like this. thank you
