### ISSUE TITLE
Migrating to Koin 2.0 in Modular Android Application

### ISSUE THREAD

**Issue by vmoskvyak** [InsertKoinIO/koin#526]
I have a question about implementation of Koin Modules in an Android multi module application. 

Before, Koin Module was a typealias which can be extended by a class and each Android Module(library) could have own implementation of Koin Module
Now how can it be implemented when Koin Module is just a variable?

Also second question about Scopes. Before, scope was a part of Koin and it was possible to inject instances without having to access the scope directly. Now we have to keep a static global variable to the scope in order to inject from it in Android Multi Module Application. How can we avoid this:

```kotlin
var exampleScope: Scope? = null

inline fun <reified T> KoinComponent.injectFromExample() : Lazy<T> {
    if (exampleScope == null) {
        throw Exception("Example scope is not initialised")
    }

    return exampleScope?.inject<T>() ?: getKoin().inject<T>()
}
```

**Comment by vmoskvyak** [comment]
It's true that the Module is still a class but it's final now, before it was extendable witch gives possibility for each Android Module(library) to have own implementation of Koin Module

**Comment by arnaudgiuliani** [comment]
the design has changed to preferd extend dsl and internal instead of classes
