### ISSUE TITLE
DeclareMock not working with instrumentation test android

### ISSUE THREAD

**Issue by hardikp888** [InsertKoinIO/koin#527]
**Describe the bug**
declareMock<>() in koin not working with instrumentation test-case, Same test case working in Junit.

**To Reproduce**

my gradle file contain

```
implementation "org.koin:koin-android:2.0.1"
testImplementation "org.koin:koin-test:2.0.1"
androidTestImplementation "org.koin:koin-test:2.0.1"
```

My testcase

```
class DemoTest : KoinTest {

    class ComponentA
    class ComponentB(val a: ComponentA)

    @Test
    fun runDemoTest() {
        startKoin {
            modules(
                module {
                    single { ComponentA() }
                    single { ComponentB(get()) }
                })
        }
        declareMock<ComponentA>()

        // retrieve mock
        assertNotNull(get<ComponentA>())

        // is built with mocked ComponentA
        assertNotNull(get<ComponentB>())
    }
}
```

DemoTest is available in both androidTest and test Directory.But testcase in test directory working fine while testcase in androidTest fail with below error.

`org.koin.core.error.InstanceCreationException: Could not create instance for [type:Single,primary_type:'com.hardik.demos.DemoTest$ComponentA'] at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:61) at org.koin.core.instance.SingleDefinitionInstance.get(SingleDefinitionInstance.kt:40) at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:70) at org.koin.core.scope.Scope.resolveInstance(Scope.kt:165) at org.koin.core.scope.Scope.get(Scope.kt:128) at com.hardik.demos.DemoTest.runDemoTest(DemoTest.kt:73) at java.lang.reflect.Method.invoke(Native Method)`

**Expected behavior**
DeclareMock should be work with androidTest also.

**Comment by arnaudgiuliani** [comment]
for this problem, I would require some help to investigate 👍 
thanks

**Comment by erickok** [comment]
Mocking on Android (instrumented tests) does not work with vanilla Mockito, as it would try to modify class byte data, yet Android uses dex. Specifically, Koin's koin-test project declares `org.mockito:mockito-inline` as dependency, but you'll need `mockito-android`.

You can override the mockito dependency and use `mockito-android`. After that it will still work as expected. See #604 for example (and actual test that tests this is possible).
