### ISSUE TITLE
how to use parametersOf in java code

### ISSUE THREAD

**Issue by jsseal** [InsertKoinIO/koin#529]
I checked how to  injection parameter API. 
val myModule = module {
   single { (view : View) -> Presenter(view)) }
}

class View {
    val presenter : Presenter by inject{ parametersOf(this) }
}

But it's difficult to how to inject it in java code.
Would you show me how to inject in java code?

**Comment by arnaudgiuliani** [comment]
not possible in Java, have to check if we can provide something for java :/

**Comment by arnaudgiuliani** [comment]
In java, instead of `by inject ( parametersOf(this))` you should write something like `KoinJavaComponent.inject(YourClass.class, ... , () -> parametersOf(this));`

**Comment by anhduy5689h** [comment]
Please provide code detail if can.

**Comment by leimenghao1991** [comment]
> Please provide code detail if can.

private Lazy<YourClass> mInjectInstance = KoinJavaComponent.inject(
            YourClass.class,
            null,
            () -> DefinitionParametersKt.parametersOf(instanceOfParameter1, instanceOfParameter2..)
    );

**Comment by remerico** [comment]
@leimenghao1991 thank you for this sample code. This should have been included in the official Koin doc!

**Comment by VitKap** [comment]
With version 3.1.1, try `ParametersHolderKt.parametersOf(...)`.
