### ISSUE TITLE
How does scope works for DialogFragments?

### ISSUE THREAD

**Issue by vfernandess** [InsertKoinIO/koin#530]
Hi,

How does scope works for DialogFragments? When the objects are cleaned?

**Comment by arnaudgiuliani** [comment]
Scope are "manual" subset of definition.  Did you try to bind it with Scope/Android extensions?

https://insert-koin.io/docs/2.0/quick-references/koin-for-android/#extended-scope-api-for-android-koin-android-scope-or-koin-androidx-scope-projects

**Comment by arnaudgiuliani** [comment]
I close this question issue. Reopen it if needed 👍
