### ISSUE TITLE
Single instance for the different interfaces

### ISSUE THREAD

**Issue by BulatMukhutdinov** [InsertKoinIO/koin#531]
Assume I have 2 interfaces ```InterfaceA``` and ```InterfaceB```. Also, I have a class implementing 2 these interfaces ```class C : InterfaceA, InterfaceB```

And in my module I have
```
single<InterfaceA> { C() }
single<InterfaceB> { C() }
```

My expectation that both ```inject InterfaceA``` and ```inject InterfaceB``` would give the same instance of class C but it is not. Is it worthy to introduce new keyword for this behavior?

**Comment by erickok** [comment]
You may use the bind keyword for that.

**Comment by BulatMukhutdinov** [comment]
Exactly what I searched for. Many thanks 👍
