### ISSUE TITLE
How to know if scope has been closed

### ISSUE THREAD

**Issue by mnayef95** [InsertKoinIO/koin#533]
I have a View in my presenter I need to set the view to null if the scope has been closed, how I can know if the scope has closed from presenter?

**Comment by arnaudgiuliani** [comment]
Hello,

from a scope object instance itself you can't. But can use `Koin.getScopeOrNull` to check it. Should return null if closed.

**Comment by mnayef95** [comment]
@arnaudgiuliani It's not helpful because I need a listener when scope has been closed so I can destruct objects inside a scoped object

**Comment by tir38** [comment]
I was just about to ask on S.O. if Koin had any such functionality. I have a similar problem with Dagger and this feature would definitely get me to jump ship ;)

**Comment by ralfgehrer** [comment]
Scope.registerCallback(object : ScopeCallback {
            override fun onScopeClose(scope: Scope) { }
        })

**Comment by arnaudgiuliani** [comment]
On a definition you can already use `onClose`:

`scoped { MyClass } onClose { ... doSomething }`

**Comment by arnaudgiuliani** [comment]
but the idea is interesting.

**Comment by MadnessThreshold** [comment]
@arnaudgiuliani , hello. I want to use `Koin.getScopeOrNull`, which need parameter scopeId. And I can't get `LifecycleOwnerExt.getScopeId`, because it's private. How can I get scopeId?

**Comment by AramKocharyan** [comment]
@arnaudgiuliani , hello. I want to use `Koin.getScopeOrNull`, but it needs the parameter `scopeId` to be passed. And I can't get `LifecycleOwnerExt.getScopeId`, because it's a private function. So how to get scopeId?

**Comment by arnaudgiuliani** [comment]
A scope now has `isClosed` and can't work anymore once closed
