### ISSUE TITLE
koin dsl i need help 

### ISSUE THREAD

**Issue by kldMohammed** [InsertKoinIO/koin#536]
**Describe the bug**
I use koin with retrofit to fetch data from a remote server, and i declare my api interface in a module as a single , api interface depend on a class called a token manager(ordinary shared preference class to manage token ) and i declared it as single too. my problem is when its first time for user and he open app and sign up when he go to in another activity that have an api call he need to send his token and i declared as single, so i changed to factory so every time , and then i figured that api interface also shouldn't be single to do this operation cause it didn't work for me and i changed my api interface to be factory , but when i declared it as factory there multiple instance of it and the request was sent more than one time .
i don't know how to fix this , correct me if i use koin dsl wrong.

**Koin project used and used version (please complete the following information):**
  `koin-android version 2.0.1`

**Additional moduleDefinition**

- `val mainModule = module(override = true) {

     factory { TokenManager(androidContext()) }
    factory { SessionManager(androidContext(), get
()) }

    factory { ApiService.invoke(get()) }
}`

**my api definition **

`interface ApiService {
   // ...
    companion object {
        val gson = GsonBuilder()
            .setLenient()
            .create()
        
        private val builder = Retrofit.Builder()
            .baseUrl(BASE_URL)
            .addConverterFactory(GsonConverterFactory.create(gson))
        
        var retrofit: Retrofit? = builder.build()
        
        private val logging = HttpLoggingInterceptor()
            .setLevel(HttpLoggingInterceptor.Level.BODY)
        
        private val httpClient = OkHttpClient.Builder()
        
        
        operator fun invoke(tokenManager: TokenManager): ApiService {
            val token = tokenManager.loadToken()
            if (token != "") {
                httpClient.addInterceptor { chain: Interceptor.Chain ->
                    val original = chain.request()
                    val request = original.newBuilder()
                        .header("Authorization", "Bearer $token")
                        .build()
                    chain.proceed(request)
                }
            }
            httpClient.followRedirects(false)
                .followSslRedirects(false)
            
            httpClient.addInterceptor(logging)
            httpClient.readTimeout(30, TimeUnit.SECONDS)
            httpClient.connectTimeout(30, TimeUnit.SECONDS)
            builder.client(httpClient.build())
            if (retrofit != null) {
                retrofit = builder.build()
            }
            return retrofit?.create(ApiService::class.java)!!
        }
        
    }
    
    
}

`

**Comment by erickok** [comment]
Not really a Koin question but...

One solution I propose is to simple have the Retrofit and other dependencies declared as a `single` but have the `Interceptor` add a the token header only of it has a token initialzed (shared state) already. So everything is a single, including your interceptor, and in your interceptor you only add the toiken header in case the `TokenManager` has one. Otherwise you leave the request chain untouched.

**Comment by kldMohammed** [comment]
sorry , can provide sample code i didn't get it

**Comment by erickok** [comment]
Just make everything `singleton` (TokenManager, SessionManager, ApiService). In your OkHttp builder add an interceptor like this:
```
httpClient.addInterceptor(tokenInterceptor)
```
The `tokenInterceptor` would have been injected via Koin.
```
class TokenInterceptor(val tokenManager: TokenManager): Interceptor {
```
In the implementation you add the token header (via `.header("Authorization", "Bearer $token")` as per your code above) on every `Request`, as long as `tokenManager` has a token.

Only code I can link to would be https://github.com/erickok/borefts2015/blob/master/android/app/src/main/java/nl/brouwerijdemolen/borefts2013/gui/Modules.kt though it doesn't 100% match your use case perhaps.

**Comment by kldMohammed** [comment]
Thanks bro 🤝
