### ISSUE TITLE
AndroidContext when initializing Koin in App

### ISSUE THREAD

**Issue by Gvetri** [InsertKoinIO/koin#537]
When initializing Koin in Application there is no Java alternative to ```androidContext(this@MainApplication)``` method, this cause that the androidApplication() in modules fail.

Would've great if we can add an .androidContext(context) in the KoinApp builder, like this:
```
KoinApplication koinApp = KoinApplication.create()
                .printLogger()
                .modules(modules)
               .androidContext(context);
        start(koinApp);
```

Note: I didn't know if i should create this as a bug or feature, depends on how you see it.

**Comment by arnaudgiuliani** [comment]
`androidContext` is an extension, then you can't call it from java like that.

We can try improve builder for Java developers 👍

**Comment by arnaudgiuliani** [comment]
I finally made the `KoinAndroidApplication` class to help Java developer bootstrap Koin. It will help create Koin with an Android context:

```java
KoinApplication koin = KoinAndroidApplication
                .create(this)
                .printLogger()
                .modules(new ArrayList(...));

start(koin);
```

**Comment by arnaudgiuliani** [comment]
available in `alpha-11` and beta
