### ISSUE TITLE
Passing Activity/Parameters through different Modules

### ISSUE THREAD

**Issue by julianfalcionelli** [InsertKoinIO/koin#538]
Hi there,

I need to pass an Activity through different Modules in order to resolve my dependencies graph.

I have 2 Classes that needs the current Activity instance, the `PermissionsManager` and `LocationManager` classes. The `LocationManager` is injected in the` MainContract.Presenter` which is injected in my Activity, so I am passing the Activity through the presenter module.

My intuition tell me to do something like this:

 ```
 private val managersModule = module {
        factory<PermissionsManager> { (activity: Activity) -> PermissionsManagerImpl(activity) }
        factory<LocationManager> { (activity: Activity) ->
            LocationManagerImpl(LocationServices.getFusedLocationProviderClient(get()),
                get(),
                get { parametersOf(activity) },
                activity)
        }
    }
    private val uiModule = module {
        scope(named<MainActivity>()) {
            factory<MainContract.Presenter> { (view: MainContract.View, activity: Activity) ->
                MainPresenter(view, get { parametersOf(activity) })
            }
        }
    } 
```

My view:

```
class MainActivity : BaseActivity(), MainContract.View {

    private val presenter: MainContract.Presenter by currentScope.inject { parametersOf(this, this) }

```

My presenter:

```
class MainPresenter(
    private val view: MainContract.View,
    private val locationManager: LocationManager
) : MainContract.Presenter {
}
```

Off-course that is not working, I am getting this:
`     Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for 'android.app.Activity' has been found. Check your module definitions.
`

Any clue?

Thanks :)

**Comment by arnaudgiuliani** [comment]
Are you resolving directly an `Activity` in one of your constructors? 
It seems to you try to resolve an Activity instead of making a resolution with it.

**Comment by julianfalcionelli** [comment]
Sorry @arnaudgiuliani , I am not sure what you mean, all the code that I tried is over there, I am passing the MainActivity instance to the module resolver (  `by currentScope.inject { parametersOf(this, this) }` ) in order to be able to use it in the PermissionsManagerImpl and LocationManagerImpl, both dependencies receives requires an Activity instance in their constructor.

Probably the `get {}` method doesn't work as I expected, I thought that I was able to pass any parameters as I want over there.

**Comment by julianfalcionelli** [comment]
The PermissionsManager is the dependency that requires an Activity instance and this one is used by the LocationManager which is injected in the MainActivity.
