### ISSUE TITLE
Introducing ViewModelProvider.Factory DSL Extension

### ISSUE THREAD

**Issue by ciriti** [InsertKoinIO/koin#540]
PROBLEM:
injecting the view model with ViewModel DSL, does not prevent the creation of a new ViewModel every time android change configuration (when you rotate the phone)

SOLUTION:
using the ViewModelProvider.Factory  to control the lifecycle

Target Koin project: 2.0

I already have a working solution, I would be happy to help with that.

**Comment by ychescale9** [comment]
Koin already uses [ViewModelProvider.Factory](https://github.com/InsertKoinIO/koin/blob/1566605f8e8046f67579e414138e771dd5453624/koin-projects/koin-androidx-viewmodel/src/main/java/org/koin/androidx/viewmodel/ViewModelResolution.kt#L64).

How are you injecting the ViewModel?

`private val viewModel by viewModel<MyViewModel>()` works in both Fragment and Activity (or anything that's a `LifecycleOwner`).

**Comment by ciriti** [comment]
@ychescale9 right, it works fine!
