### ISSUE TITLE
How to get Context when using Koin in an Android library?

### ISSUE THREAD

**Issue by cassioso** [InsertKoinIO/koin#542]
Hi,

I'm creating an android library that contains UI components and I've managed to use Koin by implementing a custom KoinComponent:

KoinKomponent.kt
```
import org.koin.android.ext.koin.androidLogger
import org.koin.core.Koin
import org.koin.core.KoinComponent
import org.koin.dsl.koinApplication

private val koinInstance = koinApplication {
    androidLogger()
    modules(modules)
}

interface CustomKoinComponent : KoinComponent {
    override fun getKoin(): Koin = koinInstance.koin
}
```

And this is my modules list so far:

KoinModule.kt
```
import com.google.firebase.analytics.FirebaseAnalytics
import com.google.firebase.perf.FirebasePerformance
import org.koin.android.ext.koin.androidContext
import org.koin.dsl.module

private val firebaseModule = module {
    single { FirebasePerformance.getInstance() }
    single { FirebaseAnalytics.getInstance(get()) } // Can't resolve Context instance.
}

val modules = listOf(
    firebaseModule
)
```

But then I get an error `Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for 'android.content.Context' has been found. Check your module definitions.`. What is fair since I'm not starting Koin from an Application nor declaring a context instance.

My question is, how do I get Context in this scenario? Is there a proper way using Koin or should I find a way to parametrize the context from the main module?

I'm using `org.koin:koin-android:2.0.1`.

Thanks!

**Comment by pawegio** [comment]
Add `Context` instance to Koin container invoking `KoinApplication.androidContext()` extension function:
```kotlin
koinApplication {
    androidLogger()
    androidContext(this@YourApp)
    modules(modules)
}
```

**Comment by cassioso** [comment]
Hi @pawegio this is the normal way when using Koin in an app module, right? But the thing is that I'm using it in a library module, so I don't have access to the application context via `this@YourApp`.

Basically, I've tried to achieve the configuration described in this document https://beta.insert-koin.io/docs/2.0/documentation/reference/index.html#_koin_context_isolation + providing context.

From this other question https://github.com/InsertKoinIO/koin/issues/390 I see that @pawelmarchewka has one `init` method that receives a context and he uses it to create the Koin application. I'm going to try this way.

**Comment by pawelmarchewka** [comment]
Hi @cassioso 

Yes, I use it that way in commercially available SDK and it works 🙂

```
object TcxKoinContext {
    private lateinit var appContext: Context

    val koin: Koin by lazy {
        koinApplication {
            androidContext(appContext)
            if (Log.ON) androidLogger()
            modules(KoinModules.all())
        }.koin
    }

    @Synchronized
    fun init(context: Context) {
        check(!::appContext.isInitialized) { "Already initialized!" }

        appContext = context.applicationContext
    }
}
```
and
```
interface TcxKoinComponent : KoinComponent {
    override fun getKoin(): Koin = TcxKoinContext.koin
} 
```

**Comment by andor201995** [comment]
Hello,
i have two module's one's lifecycle should be attached to application Context and the other's to the Activities lifecycle.

But, if i do following then All my module's will be attached to Application lifecycle

```
koinApplication {
    androidLogger()
    androidContext(this@YourApp)
    modules(modules)
}
```
In `Dagger2` i can initiate the Component's with argument's and i used to send Context to each Module's by Constructing it's Component with the correct lifecycle `Context`.

- How Can i do above  using Koin?

**Comment by ThePredators** [comment]
> Hi @cassioso
> 
> Yes, I use it that way in commercially available SDK and it works 🙂
> 
> ```
> object TcxKoinContext {
>     private lateinit var appContext: Context
> 
>     val koin: Koin by lazy {
>         koinApplication {
>             androidContext(appContext)
>             if (Log.ON) androidLogger()
>             modules(KoinModules.all())
>         }.koin
>     }
> 
>     @Synchronized
>     fun init(context: Context) {
>         check(!::appContext.isInitialized) { "Already initialized!" }
> 
>         appContext = context.applicationContext
>     }
> }
> ```
> 
> and
> 
> ```
> interface TcxKoinComponent : KoinComponent {
>     override fun getKoin(): Koin = TcxKoinContext.koin
> } 
> ```

that worked for me pretty well !! 

from the application that use the AAR containing Koin, you just need to call : TcxKoinContext.init(context) // where context is application context. and of course do not forget to extend the TcxKoinComponent in your Class that use injections !

**Comment by pbs009** [comment]
I am getting error for `androidContext`, it's saying unresolved reference to androidContext. I am using `    implementation "org.koin:koin-core:2.1.5"
`
