### ISSUE TITLE
Is there any way to profile instances creation times with Koin for Android?

### ISSUE THREAD

**Issue by maxtracking** [InsertKoinIO/koin#544]
This is a question and maybe a feature request.

We have quite a few modules (~25 at the moment, Koin v2.0.1) and many objects we inject in the project at different stages. What I'd like to be able to do is to have a way to trace/profile how long does it take to inject them as there is a visible lag (and the higher the log level the longer the delay). Our hardware is not the top-end by far so every single improvement in performance is important.

I can of course put the logs in each and every `single {}` etc blocks but that's not very elegant :)

**Comment by arnaudgiuliani** [comment]
if you activate `debug` log level, you can see timing for each resolution.

Graph tracing is more a new feature then.

**Comment by maxtracking** [comment]
Hi @arnaudgiuliani ,

Yes, that's where I started - `if (BuildConfig.DEBUG) androidLogger(Level.DEBUG)` in `startKoin` DSL. But the next step is what I'm after, as on our hardware it is literally crawling, sadly, and I'd like to see the whole graph.

**Comment by arnaudgiuliani** [comment]
Ok I see. Do think something like Koin 1.x tracing graph is ok?

**Comment by maxtracking** [comment]
Hmm, I have to recall how it was in Koin 1.x as at that time the app wasn't so big :) But I guess anything like `./gradlew dependencies` would do. I think Koin 1.x produced the graph traces in similar manner. Even only for debug level.

**Comment by arnaudgiuliani** [comment]
yes exactly. But that was badly CPU consuming

**Comment by maxtracking** [comment]
Any suggestions are more than  welcome. If it is for debug level only it'd be somewhat helpful.
At the moment I've resolved to adding a bunch of `TimingLogger` calls to modules components to see how Koin resolves them.

**Comment by erickok** [comment]
If instance creation is extremely slow, surely it's just your own code. To
debug that, why isn't a (slow) debug logging sufficient?

**Comment by maxtracking** [comment]
Because I want to know where is the instance of the object resolved from. It is my own code, yes, and of course I can add all necessary traces / logs myself. The original question I had is if anything like that exists in Koin, that’s it.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by erickok** [comment]
Fair enough.

**Comment by arnaudgiuliani** [comment]
with androidLogger & DEBUG log, Koin is logging how much time it takes to resolve an instance
