### ISSUE TITLE
Ktor Install(Koin) doesn't trigger createEagerInstances

### ISSUE THREAD

**Issue by antohaby** [InsertKoinIO/koin#547]
**Describe the bug**
When using koin as Ktor feature beans that defined with "createAtStart=true" attribute doesn't actually start.

**To Reproduce**
1. Create simple ktor application
2. Install Koin with any bean with `createdAtStart=true` and call `println` for example inside the body.
3. Start the application
4. Nothing happened
5. Get bean explicitly, a message is printed.

**Expected behavior**
Bean has to be created at the start of Ktor application

**Koin project used and used version (please complete the following information):**
`koin-core version 2.0.1`
`koin-ktor version 2.0.1`

**Cause**
Installation function (https://github.com/InsertKoinIO/koin/blob/7cd226d85b6d4efce90d16f8bd717792cdae87db/koin-projects/koin-ktor/src/main/kotlin/org/koin/ktor/ext/KoinFeature.kt#L37) doesn't trigger `createEagerInstances`

As for example `GlobalContext.startKoin` (https://github.com/InsertKoinIO/koin/blob/master/koin-projects/koin-core/src/main/kotlin/org/koin/core/context/GlobalContext.kt#L69) does

**Workaround**
Call `createEagerInstances()` during installation

```
    install(Koin) {
        /*...*/
        modules(/*...*/)
        // Call after modules are set
        createEagerInstances()
    }
```

**Possible fix**
In `Koin.install` instead `GlobalContext.start(application)` use `GlobalContext.startKoin(configure)`

```
class Koin {
/* ... */
        override fun install(pipeline: Application, configure: KoinAppDeclaration): Koin {
            startKoin(configure)
            pipeline.environment.monitor.subscribe(ApplicationStopping) {
                GlobalContext.stop()
            }
            return Koin()
        }
    }
}
```

**Comment by BorzdeG** [comment]
it works in version `2.1.0-alpha-7`

**Comment by arnaudgiuliani** [comment]
Let's continue there #548 then 👍
