### ISSUE TITLE
Lazy injection crashes from the class starts Koin

### ISSUE THREAD

**Issue by budius** [InsertKoinIO/koin#550]
**Describe the bug**
Lazy injections `by inject()` crash if created before starting Koin

**To Reproduce**
Check the [attached minimum reproducible example](https://github.com/InsertKoinIO/koin/files/3500493/KoinBugReport.zip).  

tl;dr (snippet below shouldn't crash, but it does)
```
fun main() {
   val crashy = CrashyInjection(context)
   startKoin {  ... etc }
   Log.d("TAG", "Injected `${crashy.component1}`")
}

class CrashyInjection(context: Context) : KoinComponent {
    val component1: Component1 by inject()
}
```

**Expected behavior**
If the injection is lazy, it should be really lazy and not try to access the Koin component from its declaration

**Koin project used and used version (please complete the following information):**
Used `org.koin:koin-android:2.0.1`, but AFAIK it's on `koin-core`

**Comment by budius** [comment]
See pull request with fixes here https://github.com/InsertKoinIO/koin/pull/551

**Comment by arnaudgiuliani** [comment]
resolved in PR 👍
