### ISSUE TITLE
"No cast needed" warning when declaring an interface implementation in module

### ISSUE THREAD

**Issue by FunshoFab** [InsertKoinIO/koin#556]
I have an interface ```CoroutineDispatcherProvider``` and a class ```DefaultCoroutineDispatcherProvider```  that implements the interface. When I declare this class in a module, Android studio shows "No cast needed" as shown here:

![Screenshot from 2019-08-21 20-32-33](https://user-images.githubusercontent.com/17772736/63462500-019e6c00-c453-11e9-88fb-e095e10c0aba.png)

The problem is, whenever I perform "Code cleanup" in Android studio, it removes the cast (since it feels it is unnecessary)

I use:
- koin-android-viewmodel version 2.0.1
- Kotlin 1.3.41
- Gradle 3.5.0
- Android studio 3.5

What am I doing wrong?

**Comment by keresmi** [comment]
Hi @FunshoFab, in koin 2.0 you can define a type of your single or factory in this way: 
`single<TypeOfYourInterface> { ImplementationOfYourInterface() }`.

**Comment by FunshoFab** [comment]
Thank you, @keresmi.
