### ISSUE TITLE
Setting a property to null

### ISSUE THREAD

**Issue by jmiecz** [InsertKoinIO/koin#557]
Hello, 

Could we update the api for setting properties to accept nullable? When we call get property, it runs a nullable object but we are unable to set a nullable object. 

Or is there already an api to remove a property?

**Comment by illuzor** [comment]
@arnaudgiuliani 
It would be useful for example for NavController.
This is ugly:
![image](https://user-images.githubusercontent.com/1530314/68997338-5288f980-08b6-11ea-9ad5-e641c6d96db3.png)

Maybe I can help to implement?

**Comment by arnaudgiuliani** [comment]
`deleteProperty` is now part of the property API in 2.1.0.

**Comment by illuzor** [comment]
@arnaudgiuliani thank you!
