### ISSUE TITLE
Koin binds type when activity is closed. 

### ISSUE THREAD

**Issue by keresmi** [InsertKoinIO/koin#558]
Hello guys! I created a module and declared a scope inside it. 

```
scope(named<LoginActivity>()) {
    viewModel { LoginViewModel(get(), get(), get()) }
    factory { LoginUserUseCase(get()) }
    factory { PhoneValidator() }
    factory { NotEmptyValidator() }
}
```

In my `LoginActivity` I get a view model instance in this way: 

```
override val viewModel: LoginViewModel
    get() = currentScope.getViewModel(this)
```

When the `LoginActivity` is launched all dependencies inside the scope are binded (I can see it in the Logcat) and it is quite logical. But when I closed the activity the Logcat prints the same messages. It seems that dependencies inside a scope are binded when a scope is created and also when it is closed. Maybe I misunderstood something, but is it a proper behavior? I would be most of grateful if some would explain me how does it work or what am I doing wrong. 

My koin dependecies: 

```
def KoinVersion = '2.0.1'

diDependencies = [
        koin     : "org.koin:koin-android:${KoinVersion}",
        viewmodel: "org.koin:koin-android-viewmodel:${KoinVersion}"
]
```

**Comment by rexih** [comment]
>  It seems that dependencies inside a scope are binded when a scope is created and also when it is closed

what is the meaning?

you can check insight `currentScope`

it is a extend of LifecycleOwner , the scope will observe the lifecycle , and when activity/fragment to onDestory ,scope will invoke `scope.close()` to destory the objects create in the related scope.
you can check the details in  the doc [using_scopes](https://insert-koin.io/docs/2.0/documentation/reference/index.html#_using_scopes)
