### ISSUE TITLE
Named BeanDefinition not using 'primary_type'

### ISSUE THREAD

**Issue by bovquier** [InsertKoinIO/koin#563]
**Describe the bug**
When defining two objects with same `named` string, it fails with `DefinitionOverrideException`

**To Reproduce**
1. Create definitions like:
```
factory(named("statusOne")){ StatusObject(get(named("statusOne"))) }
single(named("statusOne")){ StatusObjectConstructorParam() }
```
2. start app... `startKoin{...}`

**Expected behavior**
`named` definitions also check `primary_type` to determine object definition

**Koin project used and used version (please complete the following information):**
```
    implementation "org.koin:koin-androidx-scope:2.0.1"
    implementation "org.koin:koin-androidx-viewmodel:2.0.1"
    implementation "org.koin:koin-androidx-ext:2.0.1"
```

this appeard after migrating from `1.0.2` to `2.0.1` - on 1.x it such definitions were working fine, on 2.x every named (eg. based on enums) definitions should be changed, which is painful job ;)
or there is some other way I didn't in docs?

**Comment by arnaudgiuliani** [comment]
Hello @bovquier,

this behavior is intended: a qualifier is unique for all definitions. What is your use case behind reusing the same qualifier?

**Comment by altairmizuchi** [comment]
Hello @bovquier 
I can give you an example.
Let's assume we have a base fragment class with different interfaces expected to be injected. And they are injected on based on some string key passed via constructor by child fragment class.

```
class BaseFragment(nameKey: String) {
       private val listAdapter: BaseAdapter by inject(named(nameKey))
       private val viewModel: BaseViewModel by viewModel(named(nameKey))

      ....
}

class ChildFragment1 : BaseFragment("key1") {...}

class ChildFragment2 : BaseFragment("key2") {...}
```

**Comment by erickok** [comment]
While this might read intuitive, I tend to agree, there is no reason why you can't use distinct qualifiers. There is no logical reason why the same qualifier should be used.

**Comment by altairmizuchi** [comment]
Logic is to avoid having next
```
factory(named("one_vm")){ ... }
factory(named("one_adapter")){ ... }
factory(named("one_controller")){ ... }
factory(named("one_vm")){ ... }

factory(named("two_vm")){ ... }
factory(named("two_adapter")){ ... }
factory(named("two_controller")){ ... }
factory(named("two_vm")){ ... }
```
This way people will end writing their tool functions like namedVm, namedController.

Could you suggest something more "koin native" instead?

**Comment by bovquier** [comment]
@arnaudgiuliani the reason is eg. I'm using `ItemKeyedDataSource` and `DataSource.Factory` from jetpack paging, and same implementations for few source types (eg. based on item status), this doesn't allow me to make them defined in simple way like in Kotlin1 (have such setup for that). In Koin2, this will need to create `ActiveDataSource`/`PendingDataSource`/`LockedDataSource`, to match the requirements. 
In Koin1 I have something like:
```
        MyProjectsAdapter.ProjectsPagesItems.values().forEach { page -> single(page.name) { ProjectsDataSourceFactory() } }
        MyProjectsAdapter.ProjectsPagesItems.values().forEach { page -> factory(page.name) { ProjectsDataSourceManager(get(page.name)) } }
```
and I have 2 lines, and do not think about how many PagesTypes there will be, all adapter pages will have its sources injected. But couldn't achive that in K2, but I may be missing something in docs, and you, guys, can give some hint, if there is such simple approach for that.
