### ISSUE TITLE
Documentation references to closeKoin() instead of stopKoin()

### ISSUE THREAD

**Issue by Gvetri** [InsertKoinIO/koin#572]
**Describe the bug**
In the following documentation (https://insert-koin.io/docs/2.0/getting-started/junit-test/). **closeKoin()** is mentioned instead of **stopKoin()** . 

**To Reproduce**
1. Go to https://insert-koin.io/docs/2.0/getting-started/junit-test/
3. Scroll down to writing-our-first-test

**Expected behavior**
The documentation and the code should use stopKoin() instead of closeKoin()

**Koin project used and used version (please complete the following information):**
Koin 2.0.1

**Comment by cortinico** [comment]
Apparently this looks like a deployment issue as the Markdown file is correct:
https://github.com/InsertKoinIO/koin/blob/master/koin-projects/koin-website/getting-started/junit-test.md#L87 

I have the feeling the website hasn't been redeployed after the last change.

**Comment by arnaudgiuliani** [comment]
fixed with new documentation in https://start.insert-koin.io/#/quickstart/junit-test
