### ISSUE TITLE
[QUESTION] Multi-module application

### ISSUE THREAD

**Issue by lucaspommateau** [InsertKoinIO/koin#575]
Hello, I have a question regarding loading of koin modules across a multi-module application.

Example:
Application use Module A. 
Module A used Koin to inject Component.
Module A has a Kt file with his module koin.
When I initialize Module A from Application, I don't want to know about Koin. I would like Module A could startKoin himself.

With only one Module A, it's easy. I put the startKoin directly in Module A.

But what if Application used multi-module which required Koin.
If Module A startKoin.
Module B can't start Koin too, I would get a KoinAppAlreadyStartedException.

Question is: where should I put the startKoin method? Or is there a solution to check if Koin is already started? (Without catch the exception please 😄)

Thanks!

**Comment by ArturBorowy** [comment]
As I see, you can't create two independent instances of Koin. Object GlobalContext provides Koin instance and holds only one 
![image](https://user-images.githubusercontent.com/24584689/64552915-9d2b4a00-d338-11e9-94ba-f47a190b9895.png)

**Comment by ArturBorowy** [comment]
`startKoin(...)` function saves Koin instance in `GlobalContext` object, which holds only one instance of Koin. That means, you don't want to use `startKoin(...)` in Module A. 

You have to create yours `KoinApplication` manually by `KoinApplication.create()`, then you access Koin methods like that:
`val yourProperty : SomeType by yourKoinApplication.koin.inject()`

@arnaudgiuliani Is that correct?

I have just created pull request with changes like that in my logging library, you can check:
https://github.com/ArturBorowy/ultimate-logger-mp/pull/1

**Comment by ArturBorowy** [comment]
And of course you have to stop Koin not by `stopKoin()` function, but `yourKoinApplication.koin.stop()`

**Comment by lucaspommateau** [comment]
Thanks for your answer.
Why do I have to create my own KoinApplication? It's not recommended to use the same instance of Koin across different modules?

**Comment by ArturBorowy** [comment]
Are you sure, you want to share Koin component across Modules? Module A probably should be responsible for own DI.

You also asked about checking if Koin is started without try-catch. Check if GlobalContext.koin is null. If true - Koin isn't started.

**Comment by wyaeld** [comment]
Best way I've found of writing code that isn't too coupled to Koin is to build your components using primarily constructor arguments for passing in all their dependencies.

Then in some `configureModules` method, read in your config and link them all together, making use of `get()` primarily.  This also means components are unaware of the framework and are relatively easy to test independently or recombine in different ways.

For your module A components, you could have a both a `configureModules` method which uses Koin and `configure` method which wires them together without Koin, for use in a root project that doesn't have Koin.

**Comment by arnaudgiuliani** [comment]
In a multi modules app, child modules should rather use `loadKoinModules()` to load their own modules definition.

From the host app, you just have to know an entry point class that will run this `loadKoinModule`. Host app is also dedicated to run `startKoin { }`

**Comment by deepanshuplank** [comment]
Hi in a multi modules app, I am loading child modules using loadKoinModules() and unloading it using unloadKoinModules() in feature module my code looks like 
```
class FeatureActivity:AppCompatActivity(){
    private val loadFeatures by lazy { loadKoinModules(featureModule) }
    private fun injectFeatures() = loadFeatures

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        injectFeatures()
    }

   override fun onDestroy() {
        super.onDestroy()
        unloadKoinModules(featureModule)
    }
} 
```

Everything works fine but problem start when another instance on same activity is loaded. While current activity is in background. App crash due to error below
```
org.koin.error.BeanOverrideException:  Try to override definition with Factory
```
Is there a way to avoid this error

**Comment by NkD** [comment]
please see to https://github.com/InsertKoinIO/koin/pull/688
