### ISSUE TITLE
FragmentFactory support

### ISSUE THREAD

**Issue by matpag** [InsertKoinIO/koin#576]
[Fragment](https://developer.android.com/jetpack/androidx/releases/fragment#1.1.0) library has been released with 1.1.0 and stable support for `FragmentFactory`.

Can we have something in koin to easily support `FragmentFactory` and `Fragment` scoping?

Thank you

**Comment by ronjunevaldoz** [comment]
Is there a workaround

**Comment by arnaudgiuliani** [comment]
fixed in 2.1.0

**Comment by TheReprator** [comment]
@arnaudgiuliani , thanks for this nice framework, but can u please let me know, how can i do it for child fragments i.e.

Activity(koinfragmentfactory)-> a)LoginFragment 
   -> b)DashboardFragment(newkoinfragmentfactory)
             b.1)HomeFragment
             b.2)ProfileFragment
How can i achieve the above one
