### ISSUE TITLE
Koin/Ktor: Configure stopping behaviour

### ISSUE THREAD

**Issue by wyaeld** [InsertKoinIO/koin#577]
Currently the Ktor Koin feature does this

```kotlin
override fun install(pipeline: Application, configure: (KoinApplication).() -> Unit): Koin {
    val application = KoinApplication.create()
    application.apply(configure)
    GlobalContext.start(application)
    pipeline.environment.monitor.subscribe(ApplicationStopping) {
        GlobalContext.stop()
    }
    return Koin()
}
```
the problem I have run into is that during the ApplicationStopping lifecycle, I may have other components which need to be shutdown, and which are resolved via Koin.

I can work around it by eager loading all of the components, but the root issue is that I want to ensure I can manage all their shutdowns before the GlobalContext is stopped.

Would it be acceptable to have a configurable property that controls this behaviour, eg.

```kotlin
install(Koin) {
      autostop = false   // defaults to true to maintain existing intuitive behaviour
      modules(appModule)
}
```

```kotlin
if (autostop) {
    pipeline.environment.monitor.subscribe(ApplicationStopping) {
        GlobalContext.stop()
    }
}
```

this enables me to do things like
```kotlin
environment.monitor.subscribe(ApplicationStopping) {
    environment.log.info("Stopping services")
    elasticService.disconnect()
    GlobalContext.stop()
}
```

**Comment by arnaudgiuliani** [comment]
Hello @wyaeld, did you tried to use `onClose` dsl on a definition?

let you define what to do when the definition is closed.

**Comment by wyaeld** [comment]
no I haven't yet, but just doing a search for it, appears to be the sort of thing I need.
It's only mentioned in your changelog, could prob do with an example in docs so people like me know it exists.
Thanks :-)

**Comment by wyaeld** [comment]
Had a look at it, appears to be useful enough in simple cases, but for a complex application I decided its better to keep all the startup and shutdown behaviour directly on the ktor lifecycle, partly because my services launch a number co-routines to sync up and talk to external components, and its just easier to manage their interactions in a single place.

**Comment by arnaudgiuliani** [comment]
it's more an `stop` behavior for Koin globally then?

**Comment by wyaeld** [comment]
yes, that would be the ideal.  I like the idea of being able to control per-module behaviour, but in order to manage interdependencies or concurrent startup/shutdowns I really want to be able to just deal Koin to let me handle it, and no have to attempt to work around the Koin context having being shutdown already.

**Comment by BorzdeG** [comment]
in PR #666 added Koin events:

* KoinApplicationStarted
* KoinApplicationStopPreparing
* KoinApplicationStopped

**Comment by wyaeld** [comment]
@BorzdeG looks fantastic, from reading the code appears to solve every issue I had.  I'm going to close this issue.
