### ISSUE TITLE
Gradle won't sync when project contains jitpack repository

### ISSUE THREAD

**Issue by guymclean** [InsertKoinIO/koin#581]
Gradle sync will fail  when maven jitpack repository is included in project.

E.G.
repositories {
    jcenter()
}
With the above gradlew sync succeeds

repositories {
    maven { url "https://jitpack.io" }
    jcenter()
}
With the above gradlew sync fails with error: **Could not HEAD 'https://jitpack.io/org/koin/koin-android/2.0.1/koin-android-2.0.1.pom'. Received status code 522 from server: Origin Connection Time-out**

koin_version = '2.0.1'

**Comment by erickok** [comment]
What if you put jcenter first? (Which you should always prefer.) Also, it
depends on how you define your dependencies.

**Comment by qwertyfinger** [comment]
Looks similar to this issue in Jitpack: https://github.com/jitpack/jitpack.io/issues/3973

**Comment by guymclean** [comment]
Fixed by putting jcenter dependency above jitpack, thanks.

**Comment by DanGdl** [comment]
discussion about same problem: https://github.com/jitpack/jitpack.io/issues/3973
