### ISSUE TITLE
missing getViewModel in Koin 2.0

### ISSUE THREAD

**Issue by namdroid** [InsertKoinIO/koin#582]
in KOIN 1.0.x i used:
val myViewModel = getViewModel(fragmentOrActivity, ViewModelOptions())
How can i do it in KON 2.0.1 ?

Where fragmentOrActivity is the LifecylerOwner

**Comment by saad129** [comment]
Its is in the package package `org.koin.androidx.viewmodel.ext.android`
and its not removed!. May be you're missing something!
