### ISSUE TITLE
Why Android ViewModel injected as 'viewModel' in Koin's module is being destroyed when configuration changed in Fragment?

### ISSUE THREAD

**Issue by iRYO400** [InsertKoinIO/koin#583]
`init()` method of viewModel is being triggered

**Comment by nyinyiz** [comment]
same issue

**Comment by nyinyiz** [comment]
> `init()` method of viewModel is being triggered

it's cause of fragment recreated. not about viewModel.  You can check in Fragment's activity beginTransaction() methods. Like : =>

if (savedInstanceState == null) {
fm.beginTransaction().add. . . . . .
}

**Comment by arnaudgiuliani** [comment]
same behavior without Koin? Seems not related to Koin.

**Comment by nyinyiz** [comment]
> same behavior without Koin? Seems not related to Koin.

Yes this case not related Koin. when you complete koin viewModel usage.
