### ISSUE TITLE
how i can refresh network module ?

### ISSUE THREAD

**Issue by wahyupermadie** [InsertKoinIO/koin#585]
I want to ask, how to refresh network module ? I need to pass Bearer token after user is logged in, so i need to refresh my retrofit module.

`fun remoteModule(baseUrl: String, apiVersion: String, clientId: String) = module {

    single(named(TOKEN)) { get<SharedPreferences>().getString(TOKEN, "") }

    single<Interceptor>(named(LOGGING_INTERCEPTOR)) {
        val httpLoggingInterceptor = HttpLoggingInterceptor()
        httpLoggingInterceptor.apply { level = HttpLoggingInterceptor.Level.HEADERS }
    }

    single(named(HEADER_INTERCEPTOR)) {
        Interceptor { chain ->
            val lOriginalRequest = chain.request()
            val lRequest = lOriginalRequest.newBuilder()
                .header("Authorization", String.format("Bearer ", get(named(TOKEN))))
                .header(Key.key_api_version, apiVersion)
                .header(Key.key_client_id, clientId)
                .method(lOriginalRequest.method(), lOriginalRequest.body()).build()

            chain.proceed(lRequest)
        }
    }

    single {
        GsonBuilder()
            .registerTypeAdapterFactory(DataTypeAdapterFactory())
            .setDateFormat(Key.fmt_date)
            .setLenient()
            .create()
    }

    factory {
        OkHttpClient.Builder()
            .connectTimeout(TIMEOUT, TimeUnit.SECONDS)
            .writeTimeout(TIMEOUT, TimeUnit.SECONDS)
            .readTimeout(TIMEOUT, TimeUnit.SECONDS)
            .addInterceptor(get(named(LOGGING_INTERCEPTOR)))
            .addInterceptor(get(named(HEADER_INTERCEPTOR)))
            .retryOnConnectionFailure(true)
            .build()
    }

    single {
        Retrofit.Builder()
            .client(get())
            .baseUrl(baseUrl)
            .addConverterFactory(GsonConverterFactory.create(get()))
            .build()
    }

    factory { get<Retrofit>().create(AuthService::class.java) }
    factory { get<Retrofit>().create(ProfileService::class.java) }
}
`

**Comment by erickok** [comment]
There are many ways to solve this, but to answer your original quastion: 'how can I refresh (a) module' is that the easiest is probably to stop and (re)start Koin. I would not do that though, instead I'd make the header interceptor mutable, that is, have a var property on it on which you set the bearer token (and have the headers only set if that token is not empty).

**Comment by wahyupermadie** [comment]
> There are many ways to solve this, but to answer your original quastion: 'how can I refresh (a) module' is that the easiest is probably to stop and (re)start Koin. I would not do that though, instead I'd make the header interceptor mutable, that is, have a var property on it on which you set the bearer token (and have the headers only set if that token is not empty).

thank you, I solved this by doing this https://stackoverflow.com/questions/43051558/dagger-retrofit-adding-auth-headers-at-runtime
