### ISSUE TITLE
Object chaining in Koin module

### ISSUE THREAD

**Issue by asterixorobelix** [InsertKoinIO/koin#586]
Hi - Thanks for the awesome library! I have successfully setup Koin and am using a number of modules.

I am working with a third party library which only exposes interfaces (but which obviously resolves to concrete types at runtime). 
In one of my modules I have the following:

```
val sDKModule = module {

    single { sDK.init(androidApplication()) }

   single { sDK.get().getService("9e42-c2635ab1c21f") } //sDK class provides object which implements the Service interface 
}
```

What I would like is to be able to access objects on the Service object in the sDKModule.
So, something like the following:
```
single {Service.certificate}
```

I was hoping for something like this:
```
val sdkService = single { sDK.get().getService("9e42-c2635ab1c21f") }

single { (sdkService.instance as Service).certificate}
```

Would you be able to help me achieve this?

**Comment by erickok** [comment]
````
val sDKModule = module {
   single { sDK.get().getService("9e42-c2635ab1c21f") as Service }
  single { get<Service>.certificate }
}
````

**Comment by asterixorobelix** [comment]
@erickok thank you sir!

I believe that you mis-typed and that it should be:
```
single { get<Service>().emCert }
```

**Comment by asterixorobelix** [comment]
I would suggest that this is added to the documentation because it was not made clear to me.
