### ISSUE TITLE
A Question For My Understanding

### ISSUE THREAD

**Issue by AhsenSaeed** [InsertKoinIO/koin#587]
I have this question in what situation or scenario we can use stop koin- to close all resources.

**Comment by erickok** [comment]
Whenever you see a use for it. For example to close all resources because
you want to restart from scratch. Or to stop a Koin instance that contains
the definitions only of a part of your app, which is no longer needed.

**Comment by AhsenSaeed** [comment]
Now let's say I want to restart from scratch and close my koin resource. Then how would my Application onCreate method run and I'm able to register my modules?

And for the second don't you think unloadModule will do the job?

**Comment by erickok** [comment]
No you don't go through the App onCreate, you have a separate method for it.

unloadModule can work,it depends on your use case
