### ISSUE TITLE
Unresolved reference :  inject

### ISSUE THREAD

**Issue by Jaosrikate** [InsertKoinIO/koin#588]
**Unresolved reference: inject**
Hi, I'm a newbie for DI. Trying to use KOIN to test modules in my Android apps.

```
import org.junit.After
import org.junit.Before
import org.junit.Test
import org.koin.core.context.startKoin
import org.koin.core.context.stopKoin
import org.koin.test.KoinTest
import org.koin.test.declareMock

class ModuleTest : KoinTest {

    val userInfoRepo: UserInfoRepository by inject()


    @Before
    fun before() {
        startKoin {
            modules(userInfoModule)
        }
    }

    @After
    fun after() {
        stopKoin()
    }

    @Test
    fun testKoinComponents() {

        val responseExample =
            UserInfoResponse("test", "Pablo",
                "losangelist", "username", "givenname",
                "famolyname","zoneinfo","updateAt", "ermRole")

        declareMock<UserInfoRepository> {
            given(this.getUserInfo()).willReturn { responseExample }
        }
    }
}
```

But i cant use *inject()*

My app dependencies
`//Di`
    `implementation "org.koin:koin-androidx-scope:2.0.1"`
    `implementation "org.koin:koin-androidx-viewmodel:2.0.1"`
    `implementation "org.koin:koin-androidx-ext:2.0.1"`
 `// Koin testing tools`
   ` testImplementation 'org.koin:koin-test:1.0.2'`
    `testImplementation 'com.nhaarman:mockito-kotlin:1.5.0'`

Its because I am a beginner for this.
I hope someone here help me to resolve my problem
best regards,

**Comment by erickok** [comment]
Use import 
```
import org.koin.test.inject
```

**Comment by Jaosrikate** [comment]
Thank you Eric,
I found the solution is 
Change the

`testImplementation 'org.koin:koin-test:1.0.2'`

to

`testImplementation 'org.koin:koin-test:2.0.1'`
