### ISSUE TITLE
Not able to load module while testing 

### ISSUE THREAD

**Issue by pollux-** [InsertKoinIO/koin#589]
```
val appModule = module {
    single { FirebaseAnalyticsHelper(get()) }
    single { FirebaseAnalytics.getInstance(get()) }
    single { AppKeystore() }
    single { PreferenceHelper(androidApplication()) }
    single { InactivityTracker() }
    single { AuthorizationTokenTimer() }
    single { BearerTokenTimer() }
    factory { TextFieldInfo() }
    factory { PhotoHelper(get()) }
    single { SessionPublisher(BehaviorSubject.create()) }
    viewModel { TokenRefreshViewModel(get(), get(), get(), get(), get()) }
}
```

```
startKoin {
            androidContext(mockedAndroidContext)
            androidLogger()
            modules(
                listOf(
                    networkingModule, accountModule, authenticationModule, configurationModule,
                    appModule, dashboardModule, oprModule, profileModule, healthRecordModule, accountDetailsModule
                )
            )
        }

```
Failing with exception:

> .koin.core.error.InstanceCreationException: Could not create instance for [type:Single,primary_type:'com.hcahealthcare.mhom.domain.account.AccountUseCaseImpl']
> 
> 	at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:61)
> 	at org.koin.core.instance.SingleDefinitionInstance.get(SingleDefinitionInstance.kt:40)
> 	at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:70)
> 	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:165)
> 	at org.koin.core.scope.Scope.get(Scope.kt:128)
> 	at com.hcahealthcare.mhom.domain.account.AccountUseCaseImplTest$$special$$inlined$inject$1.invoke(KoinTest.kt:51)
> 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
> 	at com.hcahealthcare.mhom.domain.account.AccountUseCaseImplTest.getUnderTest(AccountUseCaseImplTest.kt)
> 	at com.hcahealthcare.mhom.domain.account.AccountUseCaseImplTest.request_oauth_login_account_with_mfa(AccountUseCaseImplTest.kt:182)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
> 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
> 	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
> 	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
> 	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
> Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [type:Single,primary_type:'com.hcahealthcare.mhom.util.PreferenceHelper']
> 	at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:61)
> 	at org.koin.core.instance.SingleDefinitionInstance.get(SingleDefinitionInstance.kt:40)
> 	at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:70)
> 	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:165)
> 	at org.koin.core.scope.Scope.get(Scope.kt:128)
> 	at com.hcahealthcare.mhom.di.account.AccountModuleKt$accountModule$1$9.invoke(AccountModule.kt:133)
> 	at com.hcahealthcare.mhom.di.account.AccountModuleKt$accountModule$1$9.invoke(AccountModule.kt)
> 	at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:54)
> 	... 32 more
> Caused by: java.lang.IllegalStateException: applicationContext.getSh…ontext.MODE_PRIVATE
>     ) must not be null
> 	at com.hcahealthcare.mhom.util.PreferenceHelper.<init>(PreferenceHelper.kt:13)
> 	at com.hcahealthcare.mhom.di.AppModuleKt$appModule$1$4.invoke(AppModule.kt:21)
> 	at com.hcahealthcare.mhom.di.AppModuleKt$appModule$1$4.invoke(AppModule.kt)
> 	at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:54)
> 	... 39 more
> 
> 
> 
> 
>

**Comment by erickok** [comment]
See the end of your stacktrace. 

> Caused by: java.lang.IllegalStateException: applicationContext.getSh…ontext.MODE_PRIVATE
) must not be null

Looks like this is a unit test but you are using Android platform classes. Also, this is not related to Koin.

**Comment by pollux-** [comment]
Anyone knows how to solve this

**Comment by erickok** [comment]
The stack trace literally says what the problem is. It's not related to
Koin but instead because you use Android platform classes in unit tests.
That doesn't work.
