### ISSUE TITLE
How to inject custom ViewModel in BaseFragment ?

### ISSUE THREAD

**Issue by VahidGarousi** [InsertKoinIO/koin#590]
### Issue
I use MVVM architecture.
Is there a way to inject dependency into the BaseFragment?
My ViewModel does not extend the original  android ViewModel class.
My BaseActivity Basic class works without any problems
But I have this problem in the ObserverFragment
### Excepted
I want to inject all the View Models in ObserverFragment and only use them in child fragments

Here are all the classes I have here :

### **BaseFragment**
this is abstract fragment for fragments that have no connection to the server or database
```
abstract class BaseFragment : Fragment() {
    protected var rootView: View? = null
    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        if (rootView == null) {
            rootView = LayoutInflater.from(context).inflate(getLayoutRes(), container, false)
        }
        return rootView
    }
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        setupViews()
    }
    abstract fun getLayoutRes(): Int
    abstract fun setupViews()
}
```

### ObserverFragment 
this is abstract fragment for  fragments associated with the server or database
```
abstract class ObserverFragment : BaseFragment() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
    }
    protected var isSubscribeCalled = false
    protected var compositeDisposable = CompositeDisposable()
    abstract fun subscribe()
    fun unSubscribe() {
        compositeDisposable.clear()
    }

    override fun onStart() {
        super.onStart()
        if (!isSubscribeCalled) {
            subscribe()
            isSubscribeCalled = true
        }
    }
    override fun onStop() {
        super.onStop()
        unSubscribe()
    }
}
```
### App
```
class App : Application() {

    val appModule = module {
        single { provideRetrofit() }
        single { provideExamApiService(provideRetrofit()) }
        single { ExamCloudDataSource(get(ExamApiService::class.java)) }
        factory { ExamRepository(get(ExamCloudDataSource::class.java)) }
        single { ExamViewModel(get(ExamRepository::class.java)) }
    }


    override fun onCreate() {
        super.onCreate()
        startKoin {
            androidLogger()
            androidContext(this@App)
            modules(listOf(appModule))
        }
    }

    fun provideRetrofit(): Retrofit {
        return Retrofit.Builder()
            .baseUrl(BuildConfig.API_URL)
            .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
            .addConverterFactory(GsonConverterFactory.create())
            .build()
    }

    fun provideExamApiService(retrofit: Retrofit): ExamApiService =
        retrofit.create(ExamApiService::class.java)

}
```
### BaseActivity
```
abstract class BaseActivity : AppCompatActivity() {
    protected val examViewModel by inject<ExamViewModel>()
    fun showMessage(message: String) =
        Toast.makeText(applicationContext, message, Toast.LENGTH_SHORT)

    abstract fun getLayoutId(): Int
    fun showSnackBar(message: String) =
        Snackbar.make(findViewById(getLayoutId()), message, Snackbar.LENGTH_LONG)
}
```

**Comment by krasavello13** [comment]
Hi, this is my base Fragment

abstract class BaseMVVMFragment<out VM : ViewModel>(@LayoutRes layoutResourceId: Int, viewModelClass: KClass<VM>) : BaseFragment(layoutResourceId) {

    protected open val viewModel: VM by lazy { getViewModel<VM>(viewModelClass) }

    @CallSuper
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        onBindLiveData()
    }

    /**
     * Here we may bind our observers to LiveData if some.
     * This method will be executed after parent [onCreateView] method
     */
    protected open fun onBindLiveData() {
        //Optional
    }

    protected fun <T, LD : LiveData<T>> observeNullable(liveData: LD, onChanged: (T?) -> Unit) {
        liveData.observe(viewLifecycleOwner, Observer {
            onChanged(it)
        })
    }

    protected fun <T, LD : LiveData<T>> observe(liveData: LD, onChanged: (T) -> Unit) {
        liveData.observe(viewLifecycleOwner, Observer {
            it?.let(onChanged)
        })
    }
}

**Comment by isamotiuc** [comment]
@krasavello13 Unfortunately this solution will not work correctly on restore fragment, because fragment should have an empty constructor.
