### ISSUE TITLE
Is there a way to have a sharedViewModel for a Fragment's Scope?

### ISSUE THREAD

**Issue by arctouch-carlosottoboni** [InsertKoinIO/koin#593]
I'm using Android Navigation Component, in a Single-Activity App, there is a ViewModel that I want to be re-created and it's shared between some DialogFragments that compose this specific flow. I want to know if there is a way to have a `sharedViewModel` tied to this FragmentScope

I would like to use a Scoped `sharedViewModel`, I think that this will improve the library capacities

As an alternative, I would like to know if there is a way to clear a viewModel instance when the fragment is destroyed

`koin-android`

**Comment by krasavello13** [comment]
Yes, you can set the scope like this:

sharedViewModel<ViewModel>(from = {//your scope})

**Comment by arctouch-carlosottoboni** [comment]
I'm trying to pass a scope that I've created in the `sharedViewModel(from = {})` but it expects a `ViewModelStoreOwner`. 

The way that you uses it, doesn't work for me, once the `parentFragment` of my `DialogFragments` is the `NavHostFragment` from the `Navigation`

So what I need is to have a way to get a sharedViewModel for a specific scope.

**Comment by arnaudgiuliani** [comment]
Perhaps more check around a dedicated scope, not something tied to a Fragment nor an activity. You can create a scope instance by hand, and retrieve it elsewhere by its id.

**Comment by arctouch-carlosottoboni** [comment]
About that, I'm trying to define the scope in my module, like this: 

```
scope(named("fragment_scope")) {
        scoped { factory { MyScopedClass() } }

        viewModel { MyScopedViewModel(get<MyScopedClass>(), get<NotScopedClass>()) }
}
```
And retrieve it like this: 

`private val fragmentScope = getKoin().getOrCreateScope("fragment_scope_id", named("fragment_scope"))`

But it's not working.

**Comment by arnaudgiuliani** [comment]
More details?

**Comment by arctouch-carlosottoboni** [comment]
I'm getting an exception when I try to retrieve the viewModel instance from this scope:

`private val viewModel: MyScopedViewModel by fragmentScope.viewModel(parentFragment!!)`

With this I'm getting this exception: 
`Unable to instantiate fragment  ScopedFragment: calling Fragment constructor caused an exception`

I'll edit the previous message to add this line.

**Comment by arctouch-carlosottoboni** [comment]
@arnaudgiuliani Any idea?

**Comment by arnaudgiuliani** [comment]
Can you pass again your complete code, your case is a bit complex :)
Send even a gists

**Comment by izackp** [comment]
Store a weak reference to the fragment in the activity in the onCreated function.

```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        (activity as? MainActivity)?.myFragment= WeakReference(this)
    }
```

use it to create the sharedViewModel in other fragments 

```
val myFrag= (activity as? MainActivity)?.myFragment?.get() ?: return
viewModel = sharedViewModel<MyViewModel>(from = {myFrag}) { parametersOf(abc) }.value
```

As long as the fragment is in the back stack I believe its pretty much guaranteed to be alive.

**Comment by arctouch-carlosottoboni** [comment]
> Can you pass again your complete code, your case is a bit complex :)
> Send even a gists

We found out a way to overcome this issue, with NavigationComponent we have access to the ViewModelStoreOwner for a graph, so we created a new graph for this flow in order to get the right ViewModel with: `by sharedViewModel(from = { findNavController().getViewModelStoreOwner(R.id.flavor_scan_graph)})`

**Comment by MRoyDroid** [comment]
I think I'm facing a kinda similar problem as @arctouch-carlosottoboni 

I have Fragment A and B. And Fragment A is using ViewModel A and Fragment B is using ViewModel B. (Note: I'll be navigating from Fragment A to B)

So in my 'di' it structured kinda like this.

val module = module {
        scope(named("some_name")) {
              viewModel { A() }
              viewModel { B() }
         }
}

I get the viewModel using:
getKoin().createScope("some_unique_id", named("some_name"))

This is so far so good. But here comes the problem.

The moment I want to access the ViewModel A on my Fragment B, I write this code on my Fragment B.

val scope = getKoin().getScope("some_unique_id") // no problem, I get the same scope I get on Fragment A

val expectingSameViewModelA = scope.viewModel<A>(this) 
// problem: here I get a new instance of ViewModel A

Note: I'm inside the same activity and navigating Fragment A -> Fragment B

I did fix the problem with a trick, but I think this could be better. I changed my 'di' like this:

Previously:
val module = module {
        scope(named("some_name")) {
              viewModel { A() }
              viewModel { B() }
         }
}

Now:
val module = module {
        scope(named("some_name")) {
              scoped { A() }
              viewModel { B() }
         }
}

I've replaced the 'viewModel' with 'scoped'. And I can get the ViewModel with the same code previously mentioned.

But now I'm missing out things like: viewModelScope.launch() is not working when I switch tabs on my application (If I replace scope with viewModel I know I won't be facing this issue).

It would be great if @arnaudgiuliani can help me tackle this issue.

**Comment by hendrep** [comment]
> Yes, you can set the scope like this:
> `sharedViewModel<ViewModel>(from = {//your scope})`
> 
> In my case I have ViewPager, and i use the same viewModel for internal Fragments like:
> `val viewModel by sharedViewModel<MyViewModel>(from = { parentFragment!! })`

Does this still work? I have the exact same usecase.
I use Android Navigation Components (so single activity, I don't want to use the Activity as scope becuase the activity is never destroyed)
I have a fragment with a viewpager with fragments. I want the viewpager fragmetns to use the same viewmodel isntance as the parent fragment.
Struggling to get this right.. Any help would be appreciated.
Having a custom scope for this seems overcomplicated? I would just like to use the parent fragment as the scope if possible.

**Comment by krasavello13** [comment]
Hi, currently I'm using: Koin 2.1.0-beta-1 
and this version of library have more elegant way to do it.

So, try to do like this :
```
private val viewModel by lazy { 
     requireParentFragment().viewLifecycleOwner.getViewModel<MyViewModel>()
} 
```
To more deep understanding how it works, please check the **package org.koin.androidx.viewmodel.ext.android** of Koin library

**Comment by hendrep** [comment]
@krasavello13 Thank you for the reply.
Unfortunately I get the following error when trying that:
`java.lang.ClassCastException: androidx.fragment.app.FragmentViewLifecycleOwner cannot be cast to android.content.ComponentCallbacks`

Any ideas what could cause this?

**Comment by hendrep** [comment]
@krasavello13 Thank you for the reply.
Unfortunately I get the following error when trying that:
`java.lang.ClassCastException: androidx.fragment.app.FragmentViewLifecycleOwner cannot be cast to android.content.ComponentCallbacks`

Any ideas what could cause this?

**Comment by krasavello13** [comment]
Oh, excellent
Have a nice coding

**Comment by igorka48** [comment]
Will it works with Navigation Library?

**Comment by hendrep** [comment]
I guess it depends on your own use case, but I am using it with the
Navigation library without issue

**Comment by krasavello13** [comment]
> Will it works with Navigation Library?

No, its will work only if you have parent and child fragments

For correct work with navigation features (as nested navigation graph)use this extension:

```
inline fun <reified VM : ViewModel> Fragment.sharedGraphViewModel(
    @IdRes navGraphId: Int,
    qualifier: Qualifier? = null,
    noinline parameters: ParametersDefinition? = null
) = lazy {
    val store = findNavController().getViewModelStoreOwner(navGraphId).viewModelStore
    getKoin().getViewModel(ViewModelParameter(VM::class, qualifier, parameters, null, store, null))
}
```

**Comment by igorka48** [comment]
thnx

**Comment by krasavello13** [comment]
No problem, if you will have some question, please let me know
Have a nice coding

> thnx

No problem, if you will have some question, please let me know
Have a nice coding

**Comment by SergeyBurlaka** [comment]
> Store a weak reference to the fragment in the activity in the onCreated function.
> 
> ```
> override fun onCreate(savedInstanceState: Bundle?) {
>         super.onCreate(savedInstanceState)
>         (activity as? MainActivity)?.myFragment= WeakReference(this)
>     }
> ```
> 
> use it to create the sharedViewModel in other fragments
> 
> ```
> val myFrag= (activity as? MainActivity)?.myFragment?.get() ?: return
> viewModel = sharedViewModel<MyViewModel>(from = {myFrag}) { parametersOf(abc) }.value
> ```
> 
> As long as the fragment is in the back stack I believe its pretty much guaranteed to be alive.
> 
> The alternative is to have a regular unscoped (Activity) sharedViewModel then call a reset() and init(my constructor params) function on the model before navigating to the desired fragment
> 
> --- Edit
> Now that I'm thinking about it, I don't even see what's stopping you from just putting a weak reference of the sharedViewModel on the activity instead.
> 
> In the end, sharing data between fragments is just a huge pain on android. And ultimately, dumb.

looks awful

**Comment by lpetroli** [comment]
The feature request https://github.com/InsertKoinIO/koin/issues/442 would achieve the desired outcome

**Comment by aldrinjoemathew** [comment]
I have 3 fragments in an activity in the order A -> B -> C and I need to use a particular viewmodel shared between two fragments B and C. If I use shared view model in the activity even when I go back to the first fragment (A) the viewmodel instance is retained. How do I tackle this? Can I use scope for this and if so, how?

**Comment by arnaudgiuliani** [comment]
#442  will be considered

**Comment by Wokrey** [comment]
@aldrinjoemathew use findFragmentByTag(FragmentATag)

**Comment by NahroTo** [comment]
@Wokrey findFragmentByTag on what? parentFragmentManager?

**Comment by Wokrey** [comment]
> @Wokrey findFragmentByTag on what? parentFragmentManager?

First time I'm hearing about parentFragmentManager). I guess just fragmentManager is enough

**Comment by AramKocharyan** [comment]
Can't we just use
`getKoin().getScope(scopeId).getSource<ParentFragment>().getViewModel<ParentFragmentViewModel>()` ?
The only problem is to share scopeId or specify custom scopeId when creating a scope. Is there such a possibility?

**Comment by AramKocharyan** [comment]
Aren't these solutions too complicated? Can't we just use
getKoin().getScope(scopeId).getSource<ParentFragment>().getViewModel<ParentFragmentViewModel>() ?
The only problem is to share the scopeId of the ParentFragment or specify custom scopeId when creating a scope (I prefer this one). Is there such a possibility? If not, maybe we should move in this direction?

**Comment by mahmed1987** [comment]
> > Will it works with Navigation Library?
> 
> No, its will work only if you have parent and child fragments
> 
> For correct work with navigation features (as nested navigation graph)use this extension:
> 
> ```
> inline fun <reified VM : ViewModel> Fragment.sharedGraphViewModel(
>     @IdRes navGraphId: Int,
>     qualifier: Qualifier? = null,
>     noinline parameters: ParametersDefinition? = null
> ) = lazy {
>     val store = findNavController().getViewModelStoreOwner(navGraphId).viewModelStore
>     getKoin().getViewModel(ViewModelParameter(VM::class, qualifier, parameters, null, store, null))
> }
> ```

Any Idea how to use this in code ? 
private val newsViewModel: NewsViewModel by lazy {
        sharedGraphViewModel(R.navigation.news_navigation)
    }
     Doesn't seem to work

**Comment by Diegolotr99** [comment]
> Hi, currently I'm using: Koin 2.1.0-beta-1
> and this version of library have more elegant way to do it.
> 
> So, try to do like this :
> 
> ```
> private val viewModel by lazy { 
>      requireParentFragment().getViewModel<MyViewModel>()
> } 
> ```
> 
> To more deep understanding how it works, please check the **package org.koin.androidx.viewmodel.ext.android** of Koin library

I tried this and it was working, **BUT** it creates **two** separate instances of the ViewModel....

**Comment by Tetr4** [comment]
We solved this in our app for Koin v3.1.2 like this:
```kotlin
import androidx.fragment.app.Fragment
import androidx.lifecycle.ViewModel
import org.koin.android.ext.android.getDefaultScope
import org.koin.androidx.viewmodel.ViewModelOwner.Companion.from
import org.koin.androidx.viewmodel.scope.getViewModel
import org.koin.core.parameter.ParametersDefinition
import org.koin.core.qualifier.Qualifier

/** Creates or retrieves a viewmodel, whose lifecycle is scoped to a relative fragment of type [F]. */
inline fun <reified VM : ViewModel, reified F : Fragment> Fragment.sharedViewModel(
    qualifier: Qualifier? = null,
    noinline parameters: ParametersDefinition? = null
): Lazy<VM> = lazy(LazyThreadSafetyMode.NONE) {
    getDefaultScope().getViewModel(qualifier, null, { from(findRelative<F>()) }, VM::class, parameters)
}

/** Finds a relative fragment of type [F] via BFS. */
inline fun <reified F : Fragment> Fragment.findRelative(): F {
    val visited = mutableListOf<Fragment>()
    val queued = mutableListOf(this.rootFragment)
    while (queued.isNotEmpty()) {
        val current = queued.removeFirst()
        when {
            current is F -> return current
            visited.contains(current) -> continue
        }
        visited.add(current)
        queued.addAll(current.childFragmentManager.fragments)
    }
    throw IllegalStateException("Fragment does not have a relative fragment of type ${F::class.java}")
}

val Fragment.rootFragment: Fragment
    get() {
        var root = this
        while (root.parentFragment != null)
            root = root.requireParentFragment()
        return root
    }
```

Usage example (sharing a viewmodel between a fragment and dialog):
```kotlin
class LoginFragment : Fragment() {
    private val viewModel: LoginViewModel by viewModel()
    ...
}

class LoginDialog : BottomSheetDialogFragment() {
    private val viewModel by sharedViewModel<LoginViewModel, LoginFragment>()
    ...
}
```

**Comment by clauub** [comment]
@Tetr4  Hi, how can we use this with Navigation Library from Jetpack?

**Comment by Thanasis17m** [comment]
> > Hi, currently I'm using: Koin 2.1.0-beta-1
> > and this version of library have more elegant way to do it.
> > So, try to do like this :
> > ```
> > private val viewModel by lazy { 
> >      requireParentFragment().getViewModel<MyViewModel>()
> > } 
> > ```
> I tried this and it was working, **BUT** it creates **two** separate instances of the ViewModel....

@Diegolotr99 Hi, this is working for me as well. Are you sure about the two separate instances? Do you know if this is still an issue or could you provide me more info on how you found out about this so I can test this myself? I've used the Android Studio debugger, but to me it seems that there's only one instance created. 🤔
