### ISSUE TITLE
Add support for manual closure of objects at unload

### ISSUE THREAD

**Issue by fonix232** [InsertKoinIO/koin#600]
**Is your feature request related to a problem? Please describe.**

In certain cases, one might want to run some closing logic when certain objects are disposed (e.g. closing a CoroutineContext when its instance is dropped on `unloadModule()`). This is currently not possible via Koin. 

Initialisation is solved via constructors, but Kotlin does not have a default dispose/close function attached to Any types, which makes this a bit harder to implement.

**Describe the solution you'd like**

I see two possible solutions. 

## Solution one

A global callback on the Koin instance, something like this:

```
startKoin {
    [...]
    onUnload { object: Any, type: KClass<*>, instanceType: Koin.InstanceType -> 
        [call your unload/dispose/close call on object]
    }
}
```

This callback would be called whenever an unload of a module's instance happens. `Koin.InstanceType` determines what sort of registration occurred (`single`, `factory` or `viewModel`, possibly even include scopes?), `type` is obviously the type of the object, and `object` is the instance itself. Then the user can define unload logic per item - call a function on it, etc.

This could possibly be moved to the `module` instances themselves, to avoid having a massive god callback in the Koin global registration call.

Obviously this is the easy and hacky way to solve things, maybe as an interim solution, but definitely not suitable for final implementations.

## Solution two

A custom interface in the Koin package, say, `KoinCloseable`, that has a single method, say, `closeKoinInstance()`. Upon unloading the objects, they can be easily iterated through, and this method called on each that implements `KoinCloseable`. An example:

```
interface KoinCloseable {
    fun closeKoinInstance()
}
```

```
class MySuperDuperInjectedDependency: WhateverBaseClass(), KoinComponent, KoinCloseable {
    [...]

    override fun closeKoinInstance() {
        // Finish up whatever this object is doing and get it ready for disposal
        // E.g. in case of an Rx object, call dispose()
       // Or if it's a Coroutine context/job, call close()
    }
}
```

**Describe alternatives you've considered**

Currently there's no alternative to this, as I understand it.

**Target Koin project**

Any Koin implementation (this should be completely platform-agnostic as it's Koin internal logic).

**Comment by aschattney** [comment]
You can use the `onClose` api from bean definitions to get notified when an instance is closed.

```
module {
    single { Component() } onClose { instance ->
        if (instance is Closeable) {
            instance.close()
        }
    }
}
```
Extracting the definition into separate function:
```
inline fun <reified T> Module.closeableSingle(
            qualifier: Qualifier? = null,
            createdAtStart: Boolean = false,
            override: Boolean = false,
            noinline definition: Definition<T>) {
        single(qualifier, createdAtStart, override, definition) onClose { instance ->
            if (instance is Closeable) {
                instance.close()
            }
        }
    }
```
And here its usage in form of a test:
```
    @Test
    fun `does call onClose callback on bean definitions when module is unloaded`() {
        class CloseableInstance: Closeable {
            override fun close() { }
        }

        val module = module {
            closeableSingle { Mockito.spy(CloseableInstance()) }
        }
        val koin = startKoin {
            modules(module)
        }.koin

        val instance = koin.get<CloseableInstance>()
        unloadKoinModules(module)

        Mockito.verify(instance).close()
    }
```

**Comment by JanVomlel** [comment]
Is it possible with AutoCloseable interface instead of KoinCloseable? I would prefer not to have Koin dependencies in my services.
