### ISSUE TITLE
Error - BeanRegistry.java line 113 (org.koin.core.bean.BeanRegistry.searchByClass)

### ISSUE THREAD

**Issue by GabrielAzevedo88** [InsertKoinIO/koin#612]
**Describe the bug**
I am using StandAloneContext.loadKoinModules (in Activity) to start some classes as factory. It happens that sometimes when the views (fragmens or Activities) will use the variables the error occurs:
"Caused by org.koin.error.NoBeanDefFoundException
No compatible definition found for type 'MyClass'. Check your module definition
org.koin.core.bean.BeanRegistry.searchByClass"

Only the error happens occasionally. And without a pattern.

**To Reproduce**
 StandAloneContext.loadKoinModules with override flag (in Activity)

**Expected behavior**
happens that sometimes when the views (fragmens or Activities) will use the variables

**Koin project used and used version (please complete the following information):**
Koin version 1.0.1 (I didn't upgrade to v2. The refactory will be big)

**Comment by arnaudgiuliani** [comment]
Koin 1.0.x is not maintained. Please upgrade 👍
