### ISSUE TITLE
[Android] Unit Tests parallelization support

### ISSUE THREAD

**Issue by olivierg13** [InsertKoinIO/koin#613]
Hello everyone,

I am considering using Koin for a professional app, but I found one potential issue that could limit its usage in my case (I might be wrong, also asking if the hypothesis is right).

**Is your feature request related to a problem? Please describe.**
In a gradle world, you can specify the `--parallel` command which would parallelize the gradle tasks between all modules. It is particularly interesting for large apps and can make you gain a lot of time.
More specifically on Android, if you are using Robolectric in combination with `--parallel`, it will start multiple Application in the same JVM.

Hence my problem: Looking at Koin internals, it looks like a kotlin object `GlobalContext` is used to register the KoinApplication instance, and an Exception is thrown if it's already registered.

In this particular case, Robolectric tests ran in parallel would fail (or if removing the Exception, they would be flaky because sharing the same graph).

**Describe the solution you'd like**
Would there be a way to link the graph to the application, without keeping a pointer to the application in a static singleton?
Maybe I'm totally wrong there and it's already handled somewhere?

Thank you in advance!

Cheers,

Olivier

**Comment by aschattney** [comment]
Hey @olivierg13, 

1. Use `koinApplication` instead of `startKoin` when setting up the container in your application class.
2. Implement the `KoinComponent` interface in classes which use koin to resolve dependencies. This interface is already available in Koin.

```kotlin
interface KoinComponent {

    /**
     * Get the associated Koin instance
     */
    fun getKoin(): Koin = GlobalContext.get().koin
}
```
Example:
```kotlin
class MainActivity : AppCompatActivity(), KoinComponent {
    // Calls to getKoin() must be lazy, because application 
    // might not be attached to the activity yet.
    val propertyTitle: String? by lazy { getKoin().getProperty<String>("app.title") }

   override fun getKoin(): Koin = (this.application as MyApplication).koinApplication.koin

}
```

And this can be more generalized with this:
```kotlin
interface KoinApplicationProvider: KoinComponent {
    val koinApplication: KoinApplication
    override fun getKoin(): Koin = koinApplication.koin
}

interface KoinProvider: KoinComponent {
    override fun getKoin(): Koin {
        return when(this) {
            is Context -> this.applicationContext.getKoin()
            is Fragment -> requireContext().getKoin()
            else -> throw Error("Don't know how to resolve koin instance for ${this::class}")
        }
    }

    private fun Context.getKoin(): Koin  {
        return when (this) {
            is KoinApplicationProvider -> this.getKoin()
            else -> this.applicationContext?.getKoin()
                    ?: throw IllegalStateException("applicationContext not set at this stage.")
        }
    }
}
```
Usage:
```kotlin
class MainApplication : Application(), KoinApplicationProvider {

    private lateinit var koinApp: KoinApplication
    override val koinApplication: KoinApplication
        get() = this.koinApp

    override fun onCreate() {
        super.onCreate()

        this.koinApp = koinApplication {
            androidLogger(Level.DEBUG)
            androidContext(this@MainApplication)
            androidFileProperties()
            modules(listOf(appModule, mvpModule, mvvmModule, scopeModule))
        }
    }
}

class MainActivity : AppCompatActivity(), KoinProvider {
    // Calls to getKoin() must be lazy, because application 
    // might not be attached to the activity yet.
    val propertyTitle: String? by lazy { getKoin().getProperty<String>("app.title") }
}
```

**Comment by olivierg13** [comment]
Hey @aschattney 

Thanks for the answer!
I see so that's the workaround so that each Koin is linked to an application.
Unfortunately it seems like a little more work than the default implementation.
