### ISSUE TITLE
Remove single function from ScopeSet class.

### ISSUE THREAD

**Issue by Raiden18** [InsertKoinIO/koin#615]
Remove single function from ScopeSet class.

**Describe the solution you'd like**
Just remove single function from ScopeSet class. This method is depricated, throws IllegalStateException  and does nothing. Moreover ScopeSet doesn't even implement any interfaces that lead it to implementing the single method. It seems that single function is just useless.

**Target Koin project**
Koin-Core.

**Comment by arnaudgiuliani** [comment]
Hello,

check my answer here: https://github.com/InsertKoinIO/koin/pull/618#issuecomment-544950163
