### ISSUE TITLE
Autoreload feature of ktor breaking koin

### ISSUE THREAD

**Issue by ssijak** [InsertKoinIO/koin#625]
**Describe the bug**
When I enable autoreload feature of ktor like this in the conf file : 
```
autoreload = true
watch = [ pwnboards ]
```
And make a change to the code, after it is reloaded, koin loses bean bindings

**To Reproduce**
1. enable ktor autoreload
2. change the code
3. try some action that has koin binded services in it

**Expected behavior**
Koin should still work

**Koin project used and used version (please complete the following information):**
koin_version=2.0.1
ktor_version=1.3.0-beta-1
kotlin_version=1.3.50

**Additional moduleDefinition**
```
 install(Koin) {
        SLF4JLogger()
        modules(di(ktorApp))
    }
```

```
fun di(ktorApplication: Application): Module {

    return module {
        single { Database(ktorApplication) }
        singleBy<PlayerRepositoryQueries, PlayerRepositoryQueriesImpl>()
        singleBy<PlayerRepositoryWrites, PlayerRepositoryWritesImpl>()
        singleBy<PlayerRegistrationUseCase, PlayerRegistrationUseCaseImpl>()
    }

}
```

**Comment by arnaudgiuliani** [comment]
is it still in 2.1.5?
