### ISSUE TITLE
sharedViewmodel with parameters reuses other instances

### ISSUE THREAD

**Issue by CaptnBlubber** [InsertKoinIO/koin#627]
**Describe the bug**
When using sharedViewModel that takes a parameter and injecting another instance with a different parameter the old instance is getting reused.

**To Reproduce**

Module definition:
```
viewModel { (id: Int) -> UserViewModel(id) }
```

Fragment A/B
```
val details: UserViewModel by sharedViewModel { parametersOf(1) }
```

Fragment C/D
```
val details: UserViewModel by sharedViewModel { parametersOf(2) }
```

Launching A creates a new Instance with the expected parameter 1, launching B resues that instance. Thats fine so far. However: Launching C reuses the same instance and the id is not changed as expected. same for D. 

**Expected behavior**
A new instance should be created when the parameters are different

**Koin project used and used version (please complete the following information):**
 `koin-androidx-viewmodel version 2.0.1`

**Comment by arctouch-carlosottoboni** [comment]
I'm having this problem too.

**Comment by arnaudgiuliani** [comment]
normal case here, as it is reuseing the VM instance that you already created. Then you can pass any new argument, it wont recreate a new instance with that.

**Comment by Swordsman-Inaction** [comment]
For this scenario, I think it's better to use a `setter` like `setId(id: String)` instead of parameter injection.
 
Injection normally happens when create the dependency object, since `UserViewModel` is a shared object, it will only be created once, so the parameter will be only injected once.

If `id` can be changed, then a `setter` makes more sense than injection.

**Comment by thilahavanan** [comment]
I also facing same issue . is anyone have latest sample working code to try out.

**Comment by StenSoft** [comment]
I think it makes sense to create multiple instances with different arguments. E.g. I have a product detail fragment with another fragment showing more detail, it makes sense to have one view model for each product (with different arguments), just as there are multiple fragment instances created by Android Navigation Component for different arguments, and to share this view model between the detail fragment and the more detail fragment.

**Comment by desgraci** [comment]
What if I want to NOT change the parameter, but have multiple instances of the `sharedViewModel` based in the id passed the first time, as @StenSoft mentioned, I could have an scenario where I have multiple fragments presenting different ids, and I can also go to their respective details. I cannot be setting the value cause all the instances will be altered as well
