### ISSUE TITLE
Module override not working for instrumented tests

### ISSUE THREAD

**Issue by roliveiravictor** [InsertKoinIO/koin#629]
**Describe the bug**

Override of `restclient` module doesn't not work for instrumented test.

**To Reproduce**

1. Download [repo-branch](https://github.com/roliveiravictor/demo-free-moving/tree/fix/koin_module_override)

2. Run instrumented test `CarPoolViewTest`

3. Logs will show that real API is being called.

4. Removing `module(override = true)` at `CarPoolViewTest` shows `DefinitionOverrideException` since module is already delcared.

5. Break pointing `RestClient` at `CarPoolRepositoryImpl` it's possible to see that module was not override, actually the one being loaded is from production code at `Injector` class. 

**Expected behavior**

1. `HttpClientStub` should replace `CoreHttpClientImpl` in order to mock API calls

**Koin project used and used version**

`koin-androidx-viewmodel 2.0.1`
`koin-test version 2.0.1`

**Comment by roliveiravictor** [comment]
After further development, it was possible to conclude that the issue is not related to `koin`. Module's override feature is working properly.

**Comment by tuinui** [comment]
i have same problem then what is your solution?

**Comment by pedrofsn** [comment]
I have same problem here 😢

**Comment by slmyldz** [comment]
same problem single(override=true) {} was working well. Maybe you can define same function on koin test library?
