### ISSUE TITLE
documentation missing parts

### ISSUE THREAD

**Issue by ahmed56734** [InsertKoinIO/koin#633]
I can't find that part in the docs that explains how to use nested modules.
I remember this topic existed before

**Comment by egorikftp** [comment]
There area no more nested modules since 2.0 version

**Comment by ahmed56734** [comment]
why Inner modules are no longer supported ?

**Comment by arnaudgiuliani** [comment]
too much complex feature, leading to complex DSL writing for people.

I prefer to think to another way of combining scopes.
