### ISSUE TITLE
Can't find getProperty()/setProperty() 

### ISSUE THREAD

**Issue by quanseesaa** [InsertKoinIO/koin#634]
I want to use the getProperty()/setProperty() just like in the Koin document 

https://insert-koin.io/docs/2.0/documentation/reference/index.html#_read_property_from_a_module

I'm trying in multiple projects in the past few months but it never show up in the import dialog

here is my gradle:

```
implementation "org.koin:koin-android:2.0.1"
    implementation "org.koin:koin-androidx-scope:2.0.1"
    implementation "org.koin:koin-androidx-viewmodel:2.0.1"
    implementation "org.koin:koin-androidx-ext:2.0.1"
```

I have tried 2.0.0-beta-1, 2.0.0 and 2.0.1, and also tried to add  "koin-core" but not success.

But if I downgrade the version to 1.0.1  it shows up and I can use both the method

where am I doing wrong? I dont want to use the old version. 

I tried to search but there is no result, here is other issue that say it was working fine 
https://github.com/InsertKoinIO/koin/issues/344

**Comment by rockar06** [comment]
You should add `fileProperties()` method when starting koin
```kotlin
class App : Application() {

    override fun onCreate() {
        super.onCreate()
        startKoin {
            androidLogger()
            androidContext(this@App)
            fileProperties()
            modules(appModules)
        }
    }
}
```

For more reference, you can take a look at [https://insert-koin.io/docs/2.0/quick-references/starting-koin/](url)

**Comment by quanseesaa** [comment]
@rockar06 
I could add androidFileProperties()
but the getProperty()/setProperty() still havent showing up

Am I importing the correct gradle ?
```

implementation "org.koin:koin-android:2.0.1"
    implementation "org.koin:koin-androidx-scope:2.0.1"
    implementation "org.koin:koin-androidx-viewmodel:2.0.1"
    implementation "org.koin:koin-androidx-ext:2.0.1"
```

**Comment by arnaudgiuliani** [comment]
Since Koin 2.x, it's in getKoin(), not attached as extensions directly anymore
