### ISSUE TITLE
Qualifiers as addition instead of replacement

### ISSUE THREAD

**Issue by tynn** [InsertKoinIO/koin#639]
**Is your feature request related to a problem? Please describe.**
With our projects scaling, we ran into issues providing our implementations. We've chosen a very abstract architecture, utilizing generics to its fullest extend. But it wasn't possible to define beans with generic parameters, due to the use of `KClass<*>`.

    factory<List<Int>> { listOf(1) }      // @Key = List::class
    factory<List<String>> { listOf("a") } // @Key = List::class

We also tried to use qualifiers to add back the generic parameter which was strip from the class. We assumed this should work, because a qualifier is
> a word, especially an adjective or adverb, that describes another word in a particular way

But since the qualifiers are used as keys, we received duplication errors soon.

    factory<List<String>>(named<String>()) { listOf("b") } // @Key = "kotlin.String"
    factory<Set<String>>(named<String>()) { setOf("a") }   // @Key = "kotlin.String"

This then boils down to: `@Key = @Qualifier | @Type`

**Describe the solution you'd like**
A solution should be to build a key from both qualifier and class instead of a single collection for each: `@Key = [@Qualifier] @Type`.

    internal data class Key(
      val type: KClass<*>,
      val qualifier: Qualifier?
    )

As a result, all unique definitions will remain unique, while it opens _Koin_ for many more use-cases and even more abstraction.

As a next step with _Kotlin_ 1.4, [`typeOf()`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.reflect/type-of.html) could be used to replace `KClass` with `KType`. It'll be available for all platforms and efficient, as it's inlined at compile time.

**Describe alternatives you've considered**
For now we've created duplicates of each DSL method to rely on a custom `@Qualifier @Type` implementation utilizing the current `Qualifier` interface. But it would be nicer to have _Koin_ not constrain the bean definitions.

**Target Koin project**
`koin-core`

**Comment by tynn** [comment]
This relates to #484, #563 and #571

If you're interested, I'll gladly provide implementations maintaining backwards-compatibility.

**Comment by arnaudgiuliani** [comment]
not sure, it's still up to date regarding last changes

**Comment by tynn** [comment]
@arnaudgiuliani I think with `indexKey(KClass<*>,Qualifier?)` the issue should be resolved.
