### ISSUE TITLE
Use internal for most implementation details

### ISSUE THREAD

**Issue by tynn** [InsertKoinIO/koin#641]
**Is your feature request related to a problem? Please describe.**
Right now many types and functions are public, due to the inlining DSL. It exposes a larger API, which needs to be maintained for a longer term. Using the `inline` modifier where possible and designing APIs to hide as much implementation detail as possible.

**Describe the solution you'd like**
Provide a method to delegate inlined DSLs to:

    fun single(type: KClass<*>) { ... }
    inline fun <reified T> single() = single(T::class)

Use abstract return types where possible:

    fun named(name: String): Qualifier = StringQualifier(name)

**Describe alternatives you've considered**
Koin reduces its footprint, but the DSL should not change. It's mostly internal as a result.

**Target Koin project**
All projects - maybe for Koin3

**Comment by arnaudgiuliani** [comment]
current 2.1.0 alpha has been reviewed a bit more in this sense

**Comment by arnaudgiuliani** [comment]
Good catch @tynn 

rewritten many API with internal 👍
