### ISSUE TITLE
Cant bind viewModel to fragments lifecycle

### ISSUE THREAD

**Issue by fhntvb** [InsertKoinIO/koin#642]
ViewModel's onCleared method does not invoked.
I created sample project to reproduce the problem.
Single Activity app with two fragments.

My simple di:
`val appModule = module {`
         `     viewModel { MainViewModel() }`
   `      viewModel { SecondViewModel() }`
`}`
If i used koin 2 to inject SecondViewModel(... by viewModel()) to fragment, onCleared did not invoked when i returned to the first fragment by back pressed, otherwise, if i used
`viewModel = ViewModelProviders.of(this).get(SecondViewModel::class.java)`
everything worked.

I have a feeling that viewModel is attached to activity, and not to a fragment
Maybe I'm doing something wrong?

**Comment by personshelldon** [comment]
Are You using `by inject()` call? View models must be injected via `by viewModel()` call.

**Comment by fhntvb** [comment]
Sure. Sample project: [(https://github.com/fhntvb/testViewModelOnCleared)]
You can see both approaches there(ViewModelProviders, by viewModel)

**Comment by personshelldon** [comment]
Are You sure that `SecondViewModel` is created in Your flow? As I can see in Your example, there is no any calls to View Model from `SecondFragment`. Because `by viewModel()` is a lazy operator, if there is no any calls to injected field, object will not be created.

**Comment by fhntvb** [comment]
You're right. My bad. Thank you so much!
