### ISSUE TITLE
How to get SavedStateHandle without passing empty bundle to viewModel?

### ISSUE THREAD

**Issue by personshelldon** [InsertKoinIO/koin#646]
Hello! First of all, I very like Koin and it is very simple and cool! 

I tested alpha version of Koin with `SavedStateHandle` support for `ViewModel` and the behaviour to get `SavedStateHandle` is strange for me:
if I call `by viewModel` without parameters I can not get `SavedStateHandle`, to get it I have to pass empty  bundle into call `by viewModel` as parameter. But how to get `SavedStateHandle` without default args?

I think, that a better approach is to use something like this:
```
inline fun <reified T : ViewModel> SavedStateRegistryOwner.savedStateViewModel(
    qualifier: Qualifier? = null,
    defBundle: Bundle = bundleOf(),
    noinline parameters: ParametersDefinition = { parametersOf() }
): Lazy<T> = viewModel(qualifier) {
    parametersOf(defBundle, *(parameters.invoke().values))
}

// Get view model with def args or not 
private val viewModel by savedStateViewModel<MainActivityViewModel>(
        defBundle = bundleOf("test1" to "result1")
    ) {
        parametersOf(
            bundleOf("test2" to "result2")
        )
    }
```

In this case, parameters always passed as they are, but `defBundle` passed into `SavedStateViewModelFactory` as default values and converted to `SavedStateHandle`. 

Thank You in advance!

**Comment by arnaudgiuliani** [comment]
Please check the latest version here: https://github.com/InsertKoinIO/koin/issues/648

**Comment by arnaudgiuliani** [comment]
for now you can't, we have to choose how to allow that a bit better
