### ISSUE TITLE
[AndroidX] Introducing koin-androidx-fragment with Koin fragmentFactory

### ISSUE THREAD

**Issue by arnaudgiuliani** [InsertKoinIO/koin#647]
Hi All,

the `2.1.0-alpha-3` contains a new package: `koin-androidx-fragment`

This will allow to inject your `Fragment` with Koin 👍 

How to use that?

1. setup your `KoinFragmentFactory` at start with `fragmentFactory()`:

```kotlin
 startKoin {
    androidLogger(Level.DEBUG)
    androidContext(this@MainApplication)

    // setup a KoinFragmentFactory instance
    fragmentFactory()

    modules(...)
}
```

2. Use constructor for you `Fragment` class:

```kotlin
class MyFragment(val myService: MyService) : Fragment()
```

3. Declare it in Koin (factory or scoped instance):

```kotlin
val appModule = module {
    
    factory { MyFragment(get()) }
}
```

4. Setup the factory from your activity & just use it:

Setup the Koin factory from your activity:
```kotlin
class MyActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        // Koin Fragment Factory
        setupKoinFragmentFactory()

        super.onCreate(savedInstanceState)
        //...
    }
}
```

Get your Fragment:

```kotlin
supportFragmentManager.beginTransaction()
            .replace(R.id.mvvm_frame, MyFragment::class.java, null, null)
            .commit()
```

For more details (like using it with scope): https://doc.insert-koin.io/#/koin-android/fragment-factory

The package should be available soon 🎉

**Comment by mqueiroz1995** [comment]
Amazing work!

For some reason, the package contains `org.koin.androidx.viewmodel.BuildConfig`.

This results in the following error when adding both `koin-androidx-fragment` and `koin-androidx-viewmodel` as dependencies:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class org.koin.androidx.viewmodel.BuildConfig found in modules classes.jar (org.koin:koin-androidx-fragment:2.1.0-alpha-3) and classes.jar (org.koin:koin-androidx-viewmodel:2.1.0-alpha-3)
```

Am I doing anything wrong?

**Comment by arnaudgiuliani** [comment]
nothing, manifest is buggy in alpha-3. Check alpha-4 soon this week for a fix 👍

**Comment by anuragdalia** [comment]
alpha-6 is here and the duplicate class issue seems to persist?
Is there something I should be doing ?

**Comment by arnaudgiuliani** [comment]
Yep sorry. The commit has been screwed :/ 
I will repush with right manifest fix 👍 

Check `alpha-7`

**Comment by anuragdalia** [comment]
Can you elaborate on this 
setupKoinFragmentFactory() this doesnt exist?!

> Setup the Koin factory from your activity:
> 
> class MyActivity : AppCompatActivity() {
> 
>     override fun onCreate(savedInstanceState: Bundle?) {
>         // Koin Fragment Factory
>         setupKoinFragmentFactory()
> 
>         super.onCreate(savedInstanceState)
>         //...
>     }
> }

**Comment by arnaudgiuliani** [comment]
`setupKoinFragmentFactory()` this is an extension function. Be sure to have your cache clear if you had previous glitched version.
