### ISSUE TITLE
[AndroidX] Simple way to use state bundle with your ViewModel

### ISSUE THREAD

**Issue by arnaudgiuliani** [InsertKoinIO/koin#648]
Hi All,

in `koin-androidx-viewmodel:2.1.0-alpha-3` we reviewed a cleaner way to deal with state bundle for your `ViewModel`.

It's very simple, just pass a `Bundle` object as init state for your `ViewModel` as injection param 👍 

1. Add a new property typed `SavedStateHandle` in your constructor:

```kotlin
class MyStateVM(val handle: SavedStateHandle, val myService : MyService) : ViewModel()
```

2. In Koin module, use parameter injection:

```kotlin
viewModel { (handle: SavedStateHandle) -> MyStateVM(handle, get()) }
```

3. In Your Activity/Fragment, pass the default state as parameter:

```kotlin
val myStateVM: MyStateVM by viewModel { parametersOf(Bundle(), "vm1") }
```

We do all the magic for you ;)

**Comment by jgavazzisp** [comment]
Question if I were to have only 

`class MyStateVM(val handle: SavedStateHandle) : ViewModel()`

Would I still need to pass the empty Bundle or something like below would work?

val myStateVM: MyStateVM by viewModel()

Thanks

**Comment by arnaudgiuliani** [comment]
If you don't pass a Bundle, VM factory will be the default one. Then yes, always pass a default Bundle.

**Comment by ttiganik** [comment]
Im new to Koin and at first the the Intent extras were null:

```
// Activity:
private val viewModel: MainViewModel by viewModel { parametersOf(Bundle(), "vm1") }

// VM
class TestVMM(savedStateHandle: SavedStateHandle, repository: UserRepository) : ViewModel() {
    val userId: String = savedStateHandle[intentExtraUserId] ?: throw IllegalArgumentException("missing user id")
```

to access the intent extras I needed to use `intent.extras` in the Activity

```private val viewModel: MainViewModel by viewModel { parametersOf(intent.extras, "vm1") }```
