### ISSUE TITLE
Unable to create a dependency only for the lifetime of the activity.

### ISSUE THREAD

**Issue by 85vmh** [InsertKoinIO/koin#649]
I have an activity with multiple fragments, that gets opened in the app during a flow. 
In that activity I have multiple fragments, each of those have their own viewmodel, in which I inject the dependencies in the constructor. 
However, these viewmodels need a shared account object in which they write data. 
I want to inject this object into each viewmodel of the fragments that are constructing the flow.
If in the module I do  
single { UserAccountModel() }  - the object remains alive even when closing the activity, so when reopening it, I get the same instance.
I have not figured out how to create a dependency that's alive only while the activity is alive.
Please advice!

**Comment by jeziellago** [comment]
@85vmh maybe you can take a look about `scope` on https://doc.insert-koin.io/#/koin-android/scope

**Comment by 85vmh** [comment]
👍
