### ISSUE TITLE
Unable to get scopeId

### ISSUE THREAD

**Issue by AramKocharyan** [InsertKoinIO/koin#654]
Hello. I want to use `Koin.getScopeOrNull`, but it needs the parameter `scopeId` to be passed. And I can't use `LifecycleOwnerExt.getScopeId`, because it's a private function. So how can I get `scopeId`?

If I can't, can we have these lines of code in `LifecycleOwnerExt`:

```
val LifecycleOwner.currentScope: Scope? 
    get() =  getKoin().getScopeOrNull(getScopeId())

fun LifecycleOwner.getOrCreateCurrentScope(): Scope {
    val scopeId = getScopeId()
    return getKoin().getScopeOrNull(scopeId) ?: createAndBindScope(scopeId, getScopeName())
}
```

Or maybe we can just make public `LifecycleOwnerExt.getScopeId` function.

**Comment by arnaudgiuliani** [comment]
check latest 2.1.5
