### ISSUE TITLE
DI viewModel into generic class (Android)

### ISSUE THREAD

**Issue by artecoop** [InsertKoinIO/koin#655]
Hello everyone!
I'm working with Koin and I'm fairly n00b, but I love this library-
I need to know if it is possible to inject viewmodels inside a generic class. In my case I create a class which extends androidx.lifecycle.Observer.
This could be a sample code:

```
class ResourceObserver<T> : Observer<T> where T : Resource<T> {
        private val myViewModel: MyViewModel by viewModel()
    override fun onChanged(t: T) {
        when (t.status) {
            Status.LOADING -> myViewModel.loading()
            Status.ERROR -> myViewModel.error(t.error)
            Status.SUCCESS -> { ... }
        }
    }
}
```

Obviously, `by viewModel()` (or `by sharedViewModel()` fwiw) isn't available.

There is a way to achieve this behavior?

Thanks!

**Comment by HarryMMR** [comment]
Let your class extend KoinComponent. Then you can inject.

https://doc.insert-koin.io/#/koin-core/koin-component?id=unlock-the-koin-api-with-koincomponents

**Comment by artecoop** [comment]
Thank you!
