### ISSUE TITLE
How to set different modules for testing (other than for prod) in Koin Android?

### ISSUE THREAD

**Issue by NurseyitTursunkulov** [InsertKoinIO/koin#657]
I want to inject Koin in this project https://github.com/android/architecture-samples/tree/usecasesrename/app/src/main/java/com/example/android/architecture/blueprints/todoapp. They have a RealRepository for prod and FakeRepository for testing purposes. I can easily change modules in Application
`
     class MainApplication : Application() {

        override fun onCreate() {
        super.onCreate()

          startKoin {
        // module list
        modules(Repository())
        //modules(FakeRepository())
        }
     }
  }
`
but it is manual work and means that every time I want to run tests I have to substitute it here. Is there a way such depending on the use cases Koin would give me the right modules?

**Comment by HarryMMR** [comment]
Create a BaseTest. Inside it, you create another instance of startKoin with modules(FakeRepository())

**Comment by Quentinvk** [comment]
@NurseyitTursunkulov I'm working on the same project. Could you share your progress?

@HarryMMR They are complaining that it is not the right repository (org.koin.core.error.NoBeanDefFoundException: No definition found for 'ActualRepository'
I tried this :
` @Test
    fun `should inject my components`() {
        startKoin {
            modules(
                module {
                    single { FakeRepository() }
                    single { Application() }
                    single { MainViewModel(get(), get()) }
                })
        }

        // directly request an instance
        val fakeRepository = declareMock<FakeRepository>(){
            val task1 = Task("Title1", "Description1")
            val task2 = Task("Title2", "Description2", true)
            val task3 = Task("Title3", "Description3", true)
            tasksRepository.addTasks(task1, task2, task3)
        }
        assertNotNull(fakeRepository)
        assertEquals(fakeRepository, mainViewModel.repo)
    }`

**Comment by NurseyitTursunkulov** [comment]
Could you please show an example in a GitHub?
