### ISSUE TITLE
Don't use thread lazy for all injection and make synchronization for resolving a dependency inside the dependency graph

### ISSUE THREAD

**Issue by kirich1409** [InsertKoinIO/koin#669]
**Is your feature request related to a problem? Please describe.**
All dependency injections under-the-hood use a thread-safe lazy delegate. It has an impact on the performance of dependencies resolution, especially when you work in a single thread.

**Describe the solution you'd like**
I propose to make synchronization for `scoped` and `single` dependencies inside the dependencies graph. The `factory` always create a new one and doesn't need synchronization
After that all injection can be migrated to `lazy(LazyThreadSafeMode.NONE) {}`

**Target Koin project**
Every project that declares any injection

**Comment by arnaudgiuliani** [comment]
Sync is done at tree resolution level. We can avoid locking on lazy then.

@kirich1409 you can check https://github.com/InsertKoinIO/koin/pull/670 👍
