### ISSUE TITLE
[Team] Becoming a Koin contributor

### ISSUE THREAD

**Issue by arnaudgiuliani** [InsertKoinIO/koin#672]
> Want to help to work/improve Koin? Any a proposal about Koin? A problem with a specific feature?

Come help us 👍 
- Come talk on slack [#koin-dev channel](https://kotlinlang.slack.com/?redir=%2Fmessages%2Fkoin_dev), let's chat about your issue
- Open an issue to explain the issue you want to solve, and gather discussion around it
- After discussion to validate your ideas, you can open a PR or even a draft PR if the contribution is a big one Current PRs

Additional readings about basic setup: https://github.com/InsertKoinIO/koin/blob/master/CONTRIBUTING.adoc

**Comment by shalva97** [comment]
Hi, maybe a dumb question but how do I log in to Slack? I click on "create account" and Continues with Google but it complains that "The email address must match one of the domains listed below. Please try another email.". 

What domain should it match? or why?

**Comment by DavidFaermanPendo** [comment]
Hi, i am also trying to find how to join the slack.
Thanks

**Comment by shalva97** [comment]
fill the form here https://surveys.jetbrains.com/s3/kotlin-slack-sign-up, after they approve you should be able to log in
