### ISSUE TITLE
Restarting single instances in Koin 

### ISSUE THREAD

**Issue by luispereira** [InsertKoinIO/koin#676]
I'm trying to implement a session mechanism, where the user can logout and login at any moment with other account. In order to avoid having inconsistent information, I wanted to restart some instances within a module that I like this:
```
 val sessionRepositories = module {
     single { UserSessionRepository(androidApplication(), get(), get()) } bind AbstractSessionRepository::class
}
``` 

To this I tried to do: 
```
unloadKoinModules(sessionRepositories)
loadKoinModules(sessionRepositories)
```

And for what I know, this will drop the previous UserSessionRepository instance and will create a new one, creating a leak with the previous UserSessionRepository. Therefore, I tried to do: 
```
MyApplication.getInstance().stopKoinInstance()  //calls GlobalContext.stop()
MyApplication.getInstance().startKoinInstance() //restarts all instances, just to see if there was something with load and unload
``` 

And this keeps leaking, is there a way, where I can really restart my instances

**Comment by HarryMMR** [comment]
I did a session management like what you want using a custom scope. It works pretty well. After user logins, you can start scope, and when user logouts, you can close the session.
https://doc.insert-koin.io/#/koin-core/scopes?id=using-a-scope

**Comment by MoustafaElsaghier** [comment]
any direct update from koin for doing the restart?

**Comment by sureshmaidaragi1919** [comment]
@luispereira any workaround for your usecase
