### ISSUE TITLE
Koin Test Application

### ISSUE THREAD

**Issue by robertpicsart** [InsertKoinIO/koin#677]
Hi,

I am trying to create a unit test to check my modules.

`koinApplication {
 ....
}.checkModules()`

This is creating an instance of my Application, which is loading some stuff other then koin modules. 
Is it possible to avoid creating the Application instance and create an Android Application instance instead.

**Comment by arnaudgiuliani** [comment]
best is to provide a mock of `Application` when specifying `androidContext`

**Comment by iRYO400** [comment]
@arnaudgiuliani 
hi! What do you think? Make `checkModules()` unit test using AndroidJUnit4 that delegates to Robolectric? It's necessary because of Room dependency
