### ISSUE TITLE
Read bean registy

### ISSUE THREAD

**Issue by robertpicsart** [InsertKoinIO/koin#678]
Hello,

I'd like to know, is there a way to read the Koin bean registry, to see all dependencies.

**Comment by arnaudgiuliani** [comment]
In koin 2.0, you have to check in your `Koin` instance for `BeanRegistry`

In koin 2.1, you have to check in your `Koin` instance for `ScopeRegistry` and `_rootScope`

**Comment by blundell** [comment]
I'm on 2.0.1 

getKoin().beanRegistry is undefined

getKoin().scopeRegistry is valid but not what I wanted.

`getKoin().rootScope.beanRegistry` works

**Comment by robertpicsart** [comment]
thanks
