### ISSUE TITLE
extension property LifecycleOwner.lifecycleScope is also defined by lifecycle-runtime-ktx

### ISSUE THREAD

**Issue by Ccixyj** [InsertKoinIO/koin#679]
![image](https://user-images.githubusercontent.com/6183506/71234726-d65e5780-2334-11ea-9e6b-b3c8192cb896.png)

**Comment by DakotaWhipple** [comment]
As a workaround, I added this: 
`import org.koin.androidx.scope.lifecycleScope as koinLifecycleScope`

**Comment by arnaudgiuliani** [comment]
Hello @Ccixyj 

thanks, I will propose another name for that 👍 Let's call it `koinScope`

Will be added in `alpha-10`
