### ISSUE TITLE
Switch between retrofit instance

### ISSUE THREAD

**Issue by rooneyviet** [InsertKoinIO/koin#683]
I want to create 2 retrofit instances, different baseurl and okhttp

the idea I get from here 
https://stackoverflow.com/a/56668505/6272568

but with modification

 ```
single<Retrofit>(named(RETROFIT_LOGGED_NAMESPACE)) {
        Retrofit.Builder()
            .client(get(named(OKHTTP_CLIENT_AUTHEN_NAMESPACE)))
            .addCallAdapterFactory(get<RxJava2CallAdapterFactory>())
            .addConverterFactory(get<GsonConverterFactory>())
            .baseUrl(AppConfig.AUTHENTICATED_BASE_URL)
            .build()
    }

    single<Retrofit>(named(RETROFIT_NOT_LOGGED_NAMESPACE)) {
        Retrofit.Builder()
            .client(get(named(OKHTTP_CLIENT_UNAUTHEN_NAMESPACE)))
            .addCallAdapterFactory(get<RxJava2CallAdapterFactory>())
            .addConverterFactory(get<GsonConverterFactory>())
            .baseUrl(AppConfig.UNAUTHENTICATED_BASE_URL)
            .build()
    }


    single<PostsServiceAPI> {
        providePostService(
            get<Retrofit>(named(getProperty(RETROFIT_CHOOSE_NAMESPACE))
            )
        )
    }
```

then in Activity oncreate I call

```
if(SharedPreferenceSingleton.isAccessTokenSaved()){
            getKoin().setProperty(RetrofitObject.RETROFIT_CHOOSE_NAMESPACE, RetrofitObject.RETROFIT_LOGGED_NAMESPACE)
        } else {
            getKoin().setProperty(RetrofitObject.RETROFIT_CHOOSE_NAMESPACE, RetrofitObject.RETROFIT_NOT_LOGGED_NAMESPACE)
        }
```

but the problem is, for example I'm not logged in, it will choose RETROFIT_NOT_LOGGED_NAMESPACE  of retrofit, later, in the same activity, after logging in, I want to switch retrofit to RETROFIT_LOGGED_NAMESPACE 

I call 
`
getKoin().setProperty(RetrofitObject.RETROFIT_CHOOSE_NAMESPACE, RetrofitObject.RETROFIT_LOGGED_NAMESPACE)`

it doesnt do anything

**Comment by arnaudgiuliani** [comment]
Hey

> it doesnt do anything

yes because you have to retrieve your other instance. Her, you are just changing a variable in Koin. You need to retrieve/use the right instance.

**Comment by rooneyviet** [comment]
@arnaudgiuliani 

how to retrieve/use the instance? 

if I move this to a new module, any way to restart a module so that it can switch to the instance I set in setProperty
```
single<PostsServiceAPI> {
       providePostService(
           get<Retrofit>(named(getProperty(RETROFIT_CHOOSE_NAMESPACE))
           )
       )
   }
```

the providePostService method : 
```
private fun providePostService(retrofit: Retrofit): PostsServiceAPI =
    retrofit.create(PostsServiceAPI::class.java)
```

other code: 

```
val postsModule: Module = module {
    factory<Datasource> { DatasourceImpl(postsServiceAPI = get()) }
    viewModel { PostsViewModel(datasource = get()) }
}
```

**Comment by arnaudgiuliani** [comment]
If we come back to your first snippet, you just need to use the right retrofit instance. This logic to choose your right instance is written by you.

You just need to get or inject your instance: `get<Retrofit>(RETROFIT_LOGGED_NAMESPACE)` or `get<Retrofit>(RETROFIT_NOT_LOGGED_NAMESPACE)`

Not sure it's a good thing to use factory for repository components. Either you encapsulate your connection state around your Retrofit object, either you inject the right instance "by hand"

**Comment by rooneyviet** [comment]
Could you show me an example of code how to use the right retrofit instance :(
because I don't call retrofit directly from activity, I call ViewModel

**Comment by GemiDroid** [comment]
> Could you show me an example of code how to use the right retrofit instance :( because I don't call retrofit directly from activity, I call ViewModel


  Just inject/provide your retrofit instancelike below one:
 

```
 single<Retrofit>(named("//app")) {
        Retrofit.Builder()
            .baseUrl(APP_BASE_URL)
            .addCallAdapterFactory(CoroutineCallAdapterFactory())
            .addConverterFactory(GsonConverterFactory.create(get()))
            .client(get(named("//app_okhttp")))
            .build()
    }
```

 And try to use it like this:
`    get<Retrofit>(named("//app").create(//Your API Interface::class.java)`
