### ISSUE TITLE
Access scope reified type instance from scoped dsl

### ISSUE THREAD

**Issue by DakotaWhipple** [InsertKoinIO/koin#684]
**Is your feature request related to a problem? Please describe.**
In the context of kotlin coroutines, koin, and lifecycle components. I have many services bound to the lifecycle of MainActivity. I'm trying to move these to Koin but I've found that many of my services require access to the MainActivity. 

**Describe the solution you'd like**
I'd like to be able to define a MainActivity scope like this and have it's scoped objects have access to MainActivity on creation.
```
scope<MainActivity> {
  scoped { 
    AuthService(get<MainActivity>().lifecycleScope, get<MainActivity>().navController)
  }
}
```
```
scope<MainActivity> {
  scoped {
    MediaService(get<AuthService>())
  }
}
```
**Describe alternatives you've considered**
Using parameters would mean MediaService would need to create a new instance.
```
scope<MainActivity> {
  scoped {
    (a: MainActivity) -> AuthService(a.lifecycleScope)
  }
}
```

**Target Koin project**
koin-core because it'd be adding an instance to Scope without the need of a definition.

**Comment by arnaudgiuliani** [comment]
you can already request from Root entity & function is targeting current scope
