### ISSUE TITLE
Shared viewmodel creates new instance for each fragment

### ISSUE THREAD

**Issue by fvilarino** [InsertKoinIO/koin#685]
I have an app with 2 fragments, each with a viewmodel and a shared viewmodel at the activity scope. What I see is that the shared viewmodel is instantiated for each fragment instead of using the Activity instance.
What I want to do is have a viewmodel on each fragment, and pass the shared viewmodel as a constructor argument, and I'm using the `parametersOf` for this.

This is how the viewmodels are defined in the fragments:
```
    private val viewModel: PresetViewModel by viewModel { parametersOf(sharedViewMModel) }
    private val sharedViewModel: PresetSharedViewModel by sharedViewModel()
```
I've also defined the viewmodel in the Activity, although I do not use it there, to make sure it gets instantiated when the Activity starts.

It appears that the fact I'm using the shared viewmodel in the `parametersOf` is the root of the issue, a new instance is created instead of reusing the Activity instance.

**Comment by Swordsman-Inaction** [comment]
@fvilarino  I tried to reproduce the issue, but I couldn't. Could you please create a simple GitHub project which could reproduce the issue? Or provide more info like the lib version and set up process. Thanks

**Comment by fvilarino** [comment]
I have created a sample project and it works as expected there, I'll revisit the project where I saw the problem to figure out why it's not working there.
Feel free to close this ticket.
