### ISSUE TITLE
Factory called twice

### ISSUE THREAD

**Issue by scraplesh** [InsertKoinIO/koin#689]
**Describe the bug**
While getting instance via factory in a root scope, the factory called only once per each get. But when factory defined in a root scope and got in a custom scope, that factory called twice per each get, for a custom scope and for a root scope.

**To Reproduce**
```
val fooModule = module {
    factory { "Some string" }  // called twice for each scope ("foo" and root scope)
    scope(named="foo") {
        scoped {
            val someString: String = get()  // called only once
            Foo(someString)
        }
    }
}
```
**Expected behavior**
I expect factory called only once.

**Koin project used and used version (please complete the following information):**
`koin-core version 2.1.0-alpha-8`
`koin-androidx-scope version 2.1.0-alpha-8`

**Comment by arnaudgiuliani** [comment]
Hello,

a `factory` definition is not tied to a scope. Use a `scoped` definition instead, to retain the required instance.

**Comment by scraplesh** [comment]
> Hello,
> 
> a `factory` definition is not tied to a scope. Use a `scoped` definition instead, to retain the required instance.

In my rare use case I have complicated constructor with lots of parameters. And I use this class in different scopes, then I pass scope id to another scope and get an instance from scope.
I don't want to create same providers in each scope where I need this complicated provider.
Here is the example:

```
val featuresModule = {
    factory { (a: A, b: B, c: C) -> D(a, b, c) }
}

val fooModule = module {
    scope(named="foo") {
        scoped {
            val d: D = get { parametersOf(A(), B(), C()) }
            declare(d)

            Foo(d)
        }
    }
}

val barModule = module {
    scope(named="bar") {
        scoped { (scopeId: ScopeID) ->
            val d: D = getScope(scopeId).get()
            
            Bar(d)
        }
    }
}

val foo1Scope = koin.createScope("foo1", named("foo"))
val bar1Scope = koin.createScope("bar1", named("bar"))
val bar1 = bar1Scope.get { parametersOf(foo1Scope.id) }

val foo2Scope = koin.createScope("foo2", named("foo"))
val bar2Scope = koin.createScope("bar2", named("bar"))
val bar2 = bar2Scope.get { parametersOf(foo2Scope.id) }
```

**Comment by arnaudgiuliani** [comment]
Linked scopes could help you also: https://github.com/InsertKoinIO/koin/pull/688#issuecomment-571169162

**Comment by scraplesh** [comment]
That's an interesting feature, but I don't think it could solve the problem. I need to create and declare instance in different scopes. I don't want to duplicate provider, that's why I created factory. Than I get instance from factory in some scope, declare that instance and pass scope id to a target scope to get certain instance.
All is working correctly besides calling factory twice.

**Comment by arnaudgiuliani** [comment]
Would you call this scoped factory twice? Even a scoped factory, called twice, will give you 2 different instances.

**Comment by scraplesh** [comment]
Yes, I call this factory multiple times and passing scope ids to get concrete instances, when needed.

**Comment by scraplesh** [comment]
Upgraded to 2.1.5 version. Problem still exists. If I get instance factory instance declared in root scope from another scope, that factory called twice.

**Comment by arnaudgiuliani** [comment]
We continue on your PR then 👍
