### ISSUE TITLE
Koin - Problem with nested scopes for Android

### ISSUE THREAD

**Issue by nitinshambhu** [InsertKoinIO/koin#690]
**Koin Version used : 2.1.0-alpha-8**

I have a FeatureActivity that hosts two Fragments 1) `FirstFragment` and 2) `SecondFragment`

My Module looks like this

```
val featureModule = module {

    scope<FeatureActivity> {

        // FeatureDao
        scoped {
            val appDatabase: AppDatabase = get()
            appDatabase.featureDao()
        }

        scope(named(FirstFragment.SCOPE_ID)) {
            scoped { FirstFragmentRepository(get()) }
            viewModel { FirstFragmentViewModel(get()) } // needs FeatureDao
            scoped { FirstFragmentAdapter(get()) }
        }

        scope(named(SecondFragment.SCOPE_ID)) {
            scoped { SecondFragmentRepository(get()) }
            viewModel { SecondFragmentViewModel(get()) } // needs FeatureDao
            scoped { SecondFragmentAdapter(get()) }
        }

    }
```

With <FeatureActivity> scope, I want to restrict access to `FirstFragmentRepository`, `FirstFragmentViewModel`etc. to FirstFragment alone and `SecondFragmentRepository`, `SecondFragmentViewModel`etc. to SecondFragment alone.

**Question 1:** However, my ViewModels need FeatureDao to be injected. How do I access `FeatureDao`, given it's a part of parent scope [ FeatureActivity scope]? `FeatureDao` is in ActivityScope because it is necessary for both `FirstFragment` and `SecondFragment`

My Activity looks like this

```
class FeatureActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
         loadKoinModules(featureModule)
    }

    override fun onDestroy() {
        super.onDestroy()
        unloadKoinModules(featureModule)
    }

}
```

and my FirstFragment looks like this

```
class FirstFragment : Fragment() {

    companion object{
        const val SCOPE_ID = "FirstFragment"
    }

    val scope = getKoin().getOrCreateScope(SCOPE_ID, named(SCOPE_ID))
    val viewModel   by lazy {  scope.get<FirstFragmentViewModel>()}
    val adapter  by lazy { scope.get<FirstFragmentAdapter>() }

}

```

When I do this `getKoin().getOrCreateScope(SCOPE_ID, named(SCOPE_ID))`, the app crashes

```
Caused by: org.koin.core.error.NoScopeDefFoundException: No Scope Definition found for qualifer 'FirstFragment'
        at org.koin.core.registry.ScopeRegistry.createScope(ScopeRegistry.kt:128)
        at org.koin.core.Koin.createScope(Koin.kt:181)
        at org.koin.core.Koin.getOrCreateScope(Koin.kt:203)
        at com.temp.testkoin.FirstFragment.<init>(FirstFragment.kt:24)
```

However, if I use `val scope = getKoin().getScopeOrNull(SCOPE_ID)`, scope is set to null.

I went through a few questions on this forum and none of them are similar to what I want to achieve.

 - **Question 2:** My Scopes are already created. Why then does `getScopeOrNull()` return null?
 - **Question 3:** I even tried doing this and `getScopeOrNull()` still returns null?

```
val featureModule = module {

    scope<FeatureActivity> {

        // FeatureDao
        scope(named("featureDao")) {
            scoped {
                val appDatabase: AppDatabase = get()
                appDatabase.featureDao()
            }
        }

        scope(named(FirstFragment.SCOPE_ID)) {
            scoped { FirstFragmentRepository(get()) }
            viewModel { FirstFragmentViewModel(getScope("featureDao").get()) }
            scoped { FirstFragmentAdapter(get()) }
        }

       ...
       ...

    }
```
 - **Question 4:** What's the right way to get a handle on my scope & inject my dependencies properly?
 - **Question 5:** Are scopes stable? Removing nested scopes `scope(named(FirstFragment.SCOPE_ID))` and `scope(named(SecondFragment.SCOPE_ID))` gets it going. Works as expected. However, accessing a Bean from another Scope in a given Scope isn't yet supported or so it seems. No matter how much I try, it keeps complaining `org.koin.core.error.NoBeanDefFoundException: No definition found for class`

**Comment by nikhil-thakkar** [comment]
Did you try using the following code for getting the scope for the fragment:
`val scope = requireActvity().currentScope.getOrCreateScope(SCOPE_ID, named(SCOPE_ID))`

This is because your `Fragment` is scoped to `Activity` and hence not available on GlobalContext when you call `getKoin()`.

**Comment by phileo** [comment]
@nitinshambhu  does this answer your question:
https://github.com/InsertKoinIO/koin/issues/418

**Comment by nitinshambhu** [comment]
@phileo and @nikhil-thakkar - thanks for the suggestions. I shall try & let you guys know in a couple of days

**Comment by nitinshambhu** [comment]
@phileo and @nikhil-thakkar 

I tried the solution you have. One problem is solved ( I think as I no longer get NullPointerException), but another still exists

This is my module

`val scheduleListModule = module {

    scope<ScheduleActivity> {

        // FeatureDao
        scoped {
            val appDatabase: AppDatabase = get()
            appDatabase.scheduleDao()
        }

        scoped { ScheduleListRepository(get()) }

        scope(named(ScheduleListFragment.SCOPE_ID)) {
            viewModel { ScheduleViewModel(get()) }
            scoped { ScheduleListAdapter(androidContext()) }
        }

        scope(named(AddScheduleFragment.SCOPE_ID)) {
            viewModel { AddScheduleViewModel(get()) }
        }

    }
}`

As you can see, ScheduleListRepository definition is already provided. But, I get - "no bean definition found" exception

```
 Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'com.medicine.scheduler.schedule.ScheduleListRepository'. Check your definitions!
        at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:220)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:194)
        at org.koin.core.scope.Scope.get(Scope.kt:151)
        at com.medicine.scheduler.schedule.di.ScheduleModulesKt$scheduleListModule$1$1$3$1.invoke(ScheduleModules.kt:58)
        at com.medicine.scheduler.schedule.di.ScheduleModulesKt$scheduleListModule$1$1$3$1.invoke(Unknown Source:4)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
```
