### ISSUE TITLE
Licenses not included in pom

### ISSUE THREAD

**Issue by pplusplus** [InsertKoinIO/koin#694]
**Describe the bug**
Licenses section of maven pom is not defined

**To Reproduce**
1. Go to https://bintray.com/ekito/koin/download_file?file_path=org%2Fkoin%2Fkoin-core%2F2.0.1%2Fkoin-core-2.0.1.pom
2. Open pom file in text editor
3. See missing licenses section

**Expected behavior**
Licenses section should be defined in the .pom file for this dependency e.g.
```
<licenses>
    <license>
        <name>The Apache Software License, Version 2.0</name>
        <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        <distribution>repo</distribution>
    </license>
</licenses>
```
**Koin project used and used version (please complete the following information):**
koin-core version 2.0.1

**Comment by BorzdeG** [comment]
fixed in #698 PR
