### ISSUE TITLE
Kointest checkModules instance creation error on init 

### ISSUE THREAD

**Issue by abalta-mobven** [InsertKoinIO/koin#701]
**Describe the bug**
I have a PreferenceHelper class with injected in Koin. In applicationModule following,

`val applicationModule = module(override = true) {

    single { PreferencesHelper(androidContext()) }

}
`

PreferenceHelper.kt class

`init {
        prefs = context.getSharedPreferences(PREF_PACKAGE_NAME, Context.MODE_PRIVATE)
    }`

When I checkModules, I got an error like below.

[DEBUG] [Koin] | create instance for [type:Single,primary_type:'com.mobven.adidaskiosk.cache.PreferencesHelper']
[DEBUG] [Koin] +- get 'android.content.Context'
[DEBUG] [Koin] +- got 'android.content.Context' in 0.004189 ms
[ERROR] [Koin] Instance creation error : could not create instance for [type:Single,primary_type:'com.mobven.adidaskiosk.cache.PreferencesHelper']: java.lang.IllegalStateException: context.getSharedPrefere…ME, Context.MODE_PRIVATE) must not be null
	com.mobven.adidaskiosk.cache.PreferencesHelper.<init>(PreferencesHelper.kt:22)

**Koin project used and used version (please complete the following information):**
`koin-core version 2.0.1`

**Comment by erickok** [comment]
Is this a unit test? The `checkModules` function will try to instantiate all your dependencies, and you are using Android classes (`Context`) which do not exist in unit tests. My advise would be to override the `Context` and inject a dependency. 

Unfortunatly the examples nowadays don't include this any more but [here is an example](https://github.com/erickok/koin/blob/master/koin-projects/koin-android/src/test/java/org/koin/test/android/AndroidModuleTest.kt) on a slightly older version of the project (but exact same code shoud still work)
