### ISSUE TITLE
Stopping Koin does not close created Scopes

### ISSUE THREAD

**Issue by tuscland** [InsertKoinIO/koin#702]
**Describe the bug**
We start Koin in a test environment with some modules and instantiated scopes. When calling `stopKoin()`, we assume the started scopes would be closed, but found we had to close them manually.

Is this expected behavior?

**To Reproduce**
- Define a module with a scope in a class adopting the `KoinTest` interface. Make sure some of the `scoped` definitions have an `onClose` callback. Put a breakpoint or a logging statement in the callback to check it has been called.
- Instantiate the scope. 
- Stop Koin

The `onClose` callback is not called.

**Expected behavior**
The `onClose` callback is called, showing that all instantiated scoped were also closed.

**Koin project used and used version (please complete the following information):**
`koin-core version 2.1.0-alpha-8`

**Comment by arnaudgiuliani** [comment]
fixed in `alpha-11` 👍
