### ISSUE TITLE
2.1.x Saved state handle suggestions

### ISSUE THREAD

**Issue by Rosomack** [InsertKoinIO/koin#707]
Hi,

I'm implementing the new saved state handle in our [MVI library](https://github.com/babylonhealth/orbit-mvi) sample and found the Koin API for handing saved state view models slightly too implicit.

Passing in a `bundle` like
``` kotlin
private val viewModel by viewModel<TodoViewModel> { parametersOf(Bundle()) }
```
feels slightly too "magic" (pass in a bundle to make it work). In my case the view models would handle their own initial state, meaning I have to pass in an empty bundle every time. Looking at `androidx.lifecycle.SavedStateHandle#createHandle` null default state bundles are allowed though.

**Comment by arnaudgiuliani** [comment]
Hello,

I agree, it's a bit "magical" in this way. 

You still need to express the fact that your receive a `SavedStateHandle `: 

```kotlin
viewModel { (handle: SavedStateHandle) -> MyStateVM(handle, get()) }
```

but API can be more explicit than forcing you to pass a bundle param `val myStateVM: MyStateVM by viewModel { parametersOf(Bundle(), "vm1") }`
 
perhaps we could simply add 2 params: `useSavedState` and `stateBundle` to allow you to specify if you use it explicitly and allow to pass some base data.

Or do you want a dedicated viewModel api like `by stateViewModel(bundle = ...)`?

**Comment by Rosomack** [comment]
Thanks for the response!

I think either params or an explicit API would be a definite improvement. I can't decide which is better but from a user's POV I'm erring on the side of an explicit API, it clearly states that you are dealing with a state saving view model.

It would also be great if the bundle were optional in case you do not want a default state.
i.e. 
``` kotlin
private val viewModel by stateViewModel<TodoViewModel>()
```

**Comment by arnaudgiuliani** [comment]
> It would also be great if the bundle were optional in case you do not want a default state.
i.e.

I think this a good way to write yes:

```kotlin
val viewModel by stateViewModel<TodoViewModel>()
```

**Comment by arnaudgiuliani** [comment]
just added the new API in `alpha-11` ... soon the beta 👍

**Comment by Rosomack** [comment]
Thanks!
