### ISSUE TITLE
Runtime crash when the app instance is recreated after getting destroyed by the system

### ISSUE THREAD

**Issue by Turbozanik** [InsertKoinIO/koin#709]
It would be great to have an option to serialize and deserialize koin instances, so they would be restored instead of recreation, to prevent crashes and info lose.

In my case, we are developing a helper app for specific system installers, there are a lot of settings that are configured from the app, and if in the middle of installation we will lose all the progress it would be a local disaster. 
So maybe you can suggest me something that can help achieving my goals. I need to somehow save this info, and prevent screen crash to leave the user on the same page as he was before he has minimized the app.

Maybe I have missed something in the documentation, to make koin save its data. Or the only way to save data, is to save it to shared prefs, and read it every time we start koin?

Right now i am creating scope for activity like this:
```
if (getScopeIdentifier().isNotEmpty()) {	
	bindScope(getKoin().getOrCreateScope(getScopeIdentifier(),named(getScopeIdentifier())))
}
```
koinVersion = "2.0.1"

**Comment by arnaudgiuliani** [comment]
Did you check the ViewModel state bundle? https://doc.insert-koin.io/#/koin-android/viewmodel?id=viewmodel-and-state-bundle

**Comment by Turbozanik** [comment]
Nope, i will try it now, thank you.

**Comment by Turbozanik** [comment]
Is there any way I can persist SingleLiveEvent instead of MutableLiveData? As far as I see SavedStateHandle works only with MutableLiveData.
