### ISSUE TITLE
Inject FragmentStatePagerAdapter

### ISSUE THREAD

**Issue by abalta** [InsertKoinIO/koin#711]
**Describe the bug**
I have a FragmentStatePagerAdapter class called name OnboardingAdapter like below.

`class OnboardingAdapter(fm: FragmentManager) : FragmentStatePagerAdapter(fm, BEHAVIOR_RESUME_ONLY_CURRENT_FRAGMENT)
`
**Additional moduleDefinition**
I use module like below.
` factory<FragmentStatePagerAdapter> { OnboardingAdapter(get()) }`

Then I have an exception: Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for 'com.mobiaxe.onboarding.presentation.OnboardingAdapter' has been found. Check your module definitions.

**Comment by jeziellago** [comment]
Hi @abalta, could you show how the  `OnboardingAdapter` is used? (by inject or get)

**Comment by makaroffandrey** [comment]
In order for that to work, you need to have a `FragmentManager` in your Koin dependency tree, but as far as I know, there is no easy way to add it and have it properly scoped. I would suggest that instead of injecting your `OnboardingAdapter` directly, you inject a function that provides it.
Like this:
```kotlin
factory<(FragmentManager) -> FragmentStatePagerAdapter> {
    { fm: FragmentManager ->
        OnboardingAdapter(fm)
    }
}
```

And then in your `Activity` you do
```kotlin
val fragmentStatePagerAdapterFactory: (FragmentManager) -> FragmentStatePagerAdapter by inject()

override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    val onboardingAdapter = fragmentStatePagerAdapterFactory.invoke(supportFragmentManager)
}
```

**Comment by abalta** [comment]
I have successfully injected pager adapter. Thanks for you all.
