### ISSUE TITLE
Documentation mistake: koin-androidx-fragment:2.0.1 - available only from 2.1.0-alpha3 

### ISSUE THREAD

**Issue by PavelPetkevich** [InsertKoinIO/koin#714]
**Describe the bug**
Gradle project sync failed because of the problem which I described below.
Please look through this ERROR: Failed to resolve: org.koin:koin-androidx-fragment:2.0.1.

Other dependencies are works entirely.
Thanks.

**Comment by cortinico** [comment]
Looks like `koin-androidx-fragment` is available only from `2.1.0-alpha3`: https://bintray.com/ekito/koin/koin-androidx-fragment#

**Comment by PavelPetkevich** [comment]
Hello, @cortinico, definitely you are right(I already tested), nevertheless in Koin documentation no any word about that. This case is producing confusion during the integration process.

This is not directly a bug of 'koin library', but the suggestion for improvements in the documentation.

**Comment by arnaudgiuliani** [comment]
Let me precise this in the doc. You can have access also, it's pure markdown: https://github.com/InsertKoinIO/koin/tree/master/koin-projects/docs/reference
