### ISSUE TITLE
stopKoin() not working with Ktor and Unit Tests

### ISSUE THREAD

**Issue by marcelorcorrea** [InsertKoinIO/koin#715]
Hi there,
I'm having trouble when I try to run a unit test with koin injecting dependencies. But only when using `install(Koin)` feature in the Ktor Application.
The thing is that when Koin is installed by feature in Ktor, the `stopKoin()` method doesn't stop the 
Koin Application.
I got this error:
org.koin.core.error.KoinAppAlreadyStartedException: A Koin Application has already been started

But if I call `startKoin()` to inject dependencies before calling the ktor `io.ktor.server.netty.EngineMain.main(args)` method, it's possible to stop Koin Application. This way it's possible to unit test it.

```
class ApplicationTest {

    @Before
    fun setup() {
        val testModule = module {
            single { FakeImplementation }
        }
        startKoin { modules(listOf(testModule)) }
    }

    @After
    fun teardown() {
        stopKoin()
    }

    @Test
    fun testRoot() = testApp {
        handleRequest(HttpMethod.Get, "/").apply {
            assertEquals(HttpStatusCode.OK, response.status())
            assertEquals("Server is up", response.content)
        }
    }

    private fun testApp(callback: TestApplicationEngine.() -> Unit) {
        withTestApplication({
            module()
        }, callback)
    }
```
And here's the Application which throws `org.koin.core.error.KoinAppAlreadyStartedException: A Koin Application has already been started`
```
fun Application.module() {
    install(Koin) {
        printLogger()
        modules(listOf(realModule))
    }
}
```
And the Application that works:
```
fun main(args: Array<String>){
    startKoin {
        modules(listOf(realModule))
    }
    io.ktor.server.netty.EngineMain.main(args)
}
...
``` 
`stopKoin()` method should stop the Koin Application the same way as injecting dependencies without using `install` ktor's feature.

I'm using:
`koin-core version 2.0.1`

I'm not sure if there's a better way to accomplish that.

Thanks!

**Comment by arnaudgiuliani** [comment]
2.1.5 should solve it
