### ISSUE TITLE
Is it not intended to pass a Bundle to a ViewModel?

### ISSUE THREAD

**Issue by matsudamper** [InsertKoinIO/koin#721]
https://github.com/InsertKoinIO/koin/issues/648
This change converts Bundle to SavedStateHandle. Therefore, Bundle can no longer be passed.

Or like this
```
viewModel { (handle : SavedStateHandle, bundle : Bundle) ->
    MyViewModel(bundle)
}
MyViewModel(bundle : Bundle) : ViewModel()
```

I can't think passing Bundle. But is this the intended behavior?

**Comment by arnaudgiuliani** [comment]
this has been updated in last fixes - https://doc.insert-koin.io/#/koin-android/viewmodel?id=viewmodel-and-state-bundle

**Comment by matsudamper** [comment]
Thank you. I think it's a great solution.

**Comment by blundell** [comment]
the docs link is dead
