### ISSUE TITLE
Android using sharedviewmodel causes app crash

### ISSUE THREAD

**Issue by vivekwolf123** [InsertKoinIO/koin#726]
I am using -  `implementation "org.koin:koin-androidx-viewmodel:2.1.0"` in my project.

In my modules, I declare it as - 

```
private val viewModelModules = module {
        viewModel { MySharedViewModel(get()) }
}
```

I have a MainActivity who has bottom navigation bar with 3 tabs. On clicking each tab, fragment A or B or C is opened.

And in my fragment A, B, C I inject the viewModel as - 

`private val viewModel by sharedViewModel<MySharedViewModel>()`

I get an exception like this and app crashes - 

`java.lang.RuntimeException: Unable to start activity ComponentInfo: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'com.client.example.ui.MySharedViewModel'. Check your definitions!`

**Comment by krasavello13** [comment]
Hi, try this solution: 

https://github.com/InsertKoinIO/koin/issues/593#issuecomment-590831789

**Comment by vivekwolf123** [comment]
@krasavello13 I saw your solution, thank you. But in my case I use a MainActivity who has bottom navigation bar with 3 tabs. On clicking each tab, fragment A or B or C is opened. So I really don't have a parent fragment. How do I fix it?

**Comment by krasavello13** [comment]
> @krasavello13 I saw your solution, thank you. But in my case I use a MainActivity who has bottom navigation bar with 3 tabs. On clicking each tab, fragment A or B or C is opened. So I really don't have a parent fragment. How do I fix it?

So, you can try this cheat method: 
```
private val viewModel by lazy { 
     requireActivity().getViewModel<MyViewModel>()
} 
```
But be careful, because you will be binding to your MainActivity **viewModelStore**, and ViewModel will be leave while this Activity alive.

For more info about sharing ViewModels please check this link: https://doc.insert-koin.io/#/koin-android/viewmodel?id=shared-viewmodel

**Comment by vivekwolf123** [comment]
@krasavello13 still the same issue

`java.lang.RuntimeException: Unable to start activity ComponentInfo: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'com.client.example.ui.MySharedViewModel'. Check your definitions!`

**Comment by krasavello13** [comment]
Interestingly, could you share more code for a deeper understanding of the situation, please ?

**Comment by vivekwolf123** [comment]
Sure,

Here is my app module definition -

```
private val viewModelModules = module {
        viewModel { MySharedViewModel(get()) }
}
```

Here I start koin like this -

```
class MyApp : Application() {

    override fun onCreate() {
        super.onCreate()
        startKoin {
            androidContext(this@MyApp)
            AppModules.appModules
        }
    }
}
```

Here is my MainActivity -

```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        val navView: BottomNavigationView = findViewById(R.id.nav_view)
        navView.setOnNavigationItemSelectedListener(onNavigationItemSelectedListener)
        navView.selectedItemId = R.id.navigation_home
    }

    private val onNavigationItemSelectedListener =
        BottomNavigationView.OnNavigationItemSelectedListener { item ->
            when (item.itemId) {
                R.id.navigation_home -> {
                    //fragment transaction to open home fragment 
                    return@OnNavigationItemSelectedListener true
                }
                R.id.navigation_weather -> {
                    //fragment transaction to open weather fragment 
                     return@OnNavigationItemSelectedListener true
                }
                R.id.navigation_climate -> {
                   //fragment transaction to open climate fragment 
                     return@OnNavigationItemSelectedListener true
                }
            }
            false
        }
```

Here are my fragments -

```
class HomeFragment : Fragment(R.layout.fragment_home) {

    private val viewModel by lazy {
        requireActivity().getViewModel<MySharedViewModel>()
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        viewModel.getHomeDetails().observe(viewLifecycleOwner, Observer {
               //Handle response here
        })
    }
}
```

```
class WeatherFragment : Fragment(R.layout.fragment_weather) {

    private val viewModel by lazy {
        requireActivity().getViewModel<MySharedViewModel>()
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        viewModel.getWeatherDetails().observe(viewLifecycleOwner, Observer {
               //Handle response here
        })
    }
}
```

```
class ClimateFragment : Fragment(R.layout.fragment_climate) {

    private val viewModel by lazy {
        requireActivity().getViewModel<MySharedViewModel>()
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        viewModel.getClimateDetails().observe(viewLifecycleOwner, Observer {
               //Handle response here
        })
    }
}
```

Here is the view model code -

```
class MySharedViewModel(private val myUseCase: MyUseCase) : ViewModel() {
      //implementation
}
```

**Comment by krasavello13** [comment]
Maybe problem here:

```
class MyApp : Application() {

    override fun onCreate() {
        super.onCreate()
        startKoin {
            androidContext(this@MyApp)
            AppModules.appModules
        }
    }
}
```

Try add `modules()`:

```
class MyApp : Application() {

    override fun onCreate() {
        super.onCreate()
        startKoin {
            androidContext(this@MyApp)
            **modules(**AppModules.appModules### )
        }
    }
}
```

**Comment by vivekwolf123** [comment]
Tried this but still same issue :(

`org.koin.core.error.NoBeanDefFoundException: No definition found for class:'com.client.example.ui.MySharedViewModel'. Check your definitions!`

**Comment by krasavello13** [comment]
Okay, let's continue our investigation :)

Show me your **AppModules** class, please

**Comment by vivekwolf123** [comment]
```
object AppModules {

    private val useCaseModules = module {
        factory<MyUseCase> { MyUseCaseImpl(get()) }
    }

    private val repositoryModules = module {
        single<MyRepository> { MyRepositoryImpl(get(), get()) }
    }

    private val viewModelModules = module {
        viewModel { MySharedViewModel(get()) }
    }

    val appModules = module {
        listOf(
            viewModelModules,
            useCaseModules,
            repositoryModules
        )
    }
}
```

**Comment by krasavello13** [comment]
So, lets try:

In Application we will stay: 
```
startKoin {
     androidContext(this@MyApp)
     modules(AppModules.appModules)
}
```
And modify AppModules like:
```
val appModules = listOf( viewModelModules, useCaseModules, repositoryModules)
```

**Comment by vivekwolf123** [comment]
Now I get error as -

```
org.koin.core.error.NoBeanDefFoundException: No definition found for class:'com.client.example.ui.MySharedViewModel'. Check your definitions!

org.koin.core.error.InstanceCreationException: No definition found for class:'com.client.example.usecase.MyUseCase'. Check your definitions!

org.koin.core.error.InstanceCreationException: No definition found for class:'com.client.example.repository.MyRepository'. Check your definitions!
```

**Comment by krasavello13** [comment]
Show me your constructors for this classes:

**MyUseCaseImpl, MyRepositoryImpl**

**Comment by vivekwolf123** [comment]
class MyUseCaseImpl(private val myRepository: MyRepository) : MyUseCase {
        //Implementation
}

class MyRepositoryImpl(private val cache: Cache, prival val remote: Remote) : MyRepository {
        //Implementation
}

**Comment by krasavello13** [comment]
So, how Koin have to know, how to create this parameters in constructor:
**(private val cache: Cache, private val remote: Remote)**

You have to declare Cache, Remote classes in your Koin module

**Comment by vivekwolf123** [comment]
I have it already. Sorry I forgot to put it above. I just copied it to my notepad++ and pasted it here and during this got removed. 

```
object AppModules {

    private val useCaseModules = module {
        factory<MyUseCase> { MyUseCaseImpl(get()) }
    }

    private val repositoryModules = module {
        single<MyRepository> { MyRepositoryImpl(get(), get()) }
    }

    private val viewModelModules = module {
        viewModel { MySharedViewModel(get()) }
    }

    private val dataModules = module {
        single{ Cache() }
        single{ Remote() }
    }

    val appModules =  listOf(
            viewModelModules,
            useCaseModules,
            repositoryModules,
            dataModules 
    )
}
```

**Comment by nikhil-thakkar** [comment]
@vivekwolf123 If I'm not wrong you didn't do this in your activity:

`private val viewModel: MySharedViewModel by viewModel()`

If you didn't do this the `viewModel` instance is never created and hence the definition is not found.
Let me know if this works. I'm curious.

**Comment by vivekwolf123** [comment]
@nikhil-thakkar I did the same way in MainActivity as you recommended and still the same problem :( 

`org.koin.core.error.NoBeanDefFoundException: No definition found for class:'com.client.example.ui.MySharedViewModel'. Check your definitions!`

**Comment by nikhil-thakkar** [comment]
I hope you called `startKoin` with your modules:
`startKoin{ modules(list of modules) }`

**Comment by vivekwolf123** [comment]
Yes I called like this way as you suggested -

```
startKoin {
     androidContext(this@MyApp)
     modules(AppModules.appModules)
} 
```

Still same issue :(

**Comment by nikhil-thakkar** [comment]
Did you mention `MyApp` in your `AndroidManifest.xml`?
I don't see any other options as to why this shouldn't work.
Maybe a github sample would help.
