### ISSUE TITLE
Android app crash due to org.koin.core.error.InstanceCreationException

### ISSUE THREAD

**Issue by vivekwolf123** [InsertKoinIO/koin#728]
I updated the koin library to the latest stable -

`implementation "org.koin:koin-androidx-viewmodel:2.1.0"`

I declare the viewModel in appModules as - 

```
private val viewModelModules = module {
        viewModel { (handle: SavedStateHandle) -> MyViewModel(handle, get()) } 
 }
```

I use it in MyActivity as - 

```
private val viewModel: MyViewModel by viewModel {
        parametersOf(
            Bundle(),
            "myViewModel"
        )
}
```

And  I get a crash -

```
java.lang.RuntimeException: Unable to start activity ComponentInfo: org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'com.example.view.viewmodel.MyViewModel']

Caused by: java.lang.ClassCastException: android.os.Bundle cannot be cast to androidx.lifecycle.SavedStateHandle
```

**But removing saved state handle works?**

If I remove the saved state handle meaning if I declare the viewModel in appModules as -

```
private val viewModelModules = module {
        viewModel {MyViewModel(get()) } 
 }
```

And in MyActivity -

I use it in MyActivity as - 

```
private val viewModel: MyViewModel by viewModel()
```

**Comment by svrlopatrik** [comment]
Check [ViewModel and State Bundle](https://doc.insert-koin.io/#/koin-android/viewmodel?id=viewmodel-and-state-bundle) documentation. It works for me. 

But I have similar problem with `sharedViewModel` and `SavedStateHandle` it throws `java.lang.ClassCastException: android.os.Bundle cannot be cast to androidx.lifecycle.SavedStateHandle`. 

So how to use `sharedViewModel` with `SavedStateHandle`? Is there something like `sharedStateViewModel`?

**Comment by vivekwolf123** [comment]
@svrlopatrik I do the same as per the documentation? or do I do anything wrong? It used to work for me when I use `2.1.0-alpha10` but when I upgraded to stable version `2.1.0`, it is not working anymore.

**Comment by svrlopatrik** [comment]
I use `2.1.0` where `stateViewModel` works ok.
You can try `public SavedStateHandle()` or `public SavedStateHandle(@NonNull Map<String, Object> initialState)`

```
private val viewModel: MyViewModel by viewModel {
        parametersOf(
            SavedStateHandle(),
            "myViewModel"
        )
}
```

**Comment by vivekwolf123** [comment]
Yes this works for me. Thanks @svrlopatrik
