### ISSUE TITLE
Why did you remove posibility send ViewModelStoreOwner to sharedViewModel() ?

### ISSUE THREAD

**Issue by kodal** [InsertKoinIO/koin#734]
**Is your feature request related to a problem? Please describe.**
I use SingleActivity approach. There is I need a parent fragment to hold common data in child fragments 

**Target Koin project**
koinx-androidx-viewmodel

**Comment by krasavello13** [comment]
It's still possible, only renamed methods

Check this link: https://github.com/InsertKoinIO/koin/issues/593#issuecomment-592593293

**Comment by michael-paystack** [comment]
This update broke my project in so many places. I'm just going to go to sleep.

**Comment by MichaelObi** [comment]
This update broke my project in so many places. I'm just going to go to sleep.
