### ISSUE TITLE
Warnings when apply koin in Gradle

### ISSUE THREAD

**Issue by iRYO400** [InsertKoinIO/koin#736]
Getting some warnings when do `apply 'koin'`.
Koin version is 2.1.0
Android Studio 3.5.3

1. Setup root Gradle with `classpath "org.koin:koin-gradle-plugin:$koin_version"`
2. Add `apply 'koin'`
3. Sync gradle
4. See warnings

![изображение](https://user-images.githubusercontent.com/12654767/75453061-7ff93f00-599d-11ea-8220-6ff938d3b4de.png)

**Comment by gabrielbunselmeyer** [comment]
Same thing is happening here.

**Comment by gabrielperes97** [comment]
I'm using koin 2.1.6 with gradle 6.1.1 and android gradle plugin 4.0.0. When I sync the project on Android Studio i have this warning:
<ij_msg_gr>Tests model errors<ij_msg_gr><ij_nav>/run/media/gabriel/arquivos/MEGA/Documentos/arpia/Workspaces/tricard/2/lojista-business-android/app/build.gradle<ij_nav><i><b>project ':app'</b><eol>Details: java.lang.NullPointerException: null</i>

When I remove the koin plugin the warning desappears.

**Comment by rakesh-sh2020** [comment]
Same here. Its been outstanding for a while.
