### ISSUE TITLE
Wrong koin-java version in readme

### ISSUE THREAD

**Issue by henningBunk** [InsertKoinIO/koin#743]
**Describe the bug**
koin-java is not on 2.1.2 yet but the readme suggests it.

**To Reproduce**
The readme kind of suggests to use one version number for all dependencies:

```
koin_version = '2.1.2'
...
implementation "org.koin:koin-core:$koin_version"
implementation "org.koin:koin-core-ext:$koin_version"
testImplementation "org.koin:koin-test:$koin_version"
implementation "org.koin:koin-java:$koin_version"
```

If I implement it like this it won't sync because `koin-java` isn't on version 2.1.2 yet but on on 2.0.1:
https://bintray.com/ekito/koin/koin-java

Mixing version numbers also isn't trivial because then you get version conflicts:
```
Duplicate class org.koin.java.KoinJavaComponent found in modules jetified-koin-core-2.1.2.jar (org.koin:koin-core:2.1.2) and jetified-koin-java-2.0.1.jar (org.koin:koin-java:2.0.1)
Duplicate class org.koin.java.KoinJavaComponent$inject$1 found in modules jetified-koin-core-2.1.2.jar (org.koin:koin-core:2.1.2) and jetified-koin-java-2.0.1.jar (org.koin:koin-java:2.0.1)
```
**Expected behavior**
All versions are in sync or the readme does not suggest they are. If they are not in sync, a hint is shown how implement the dependencies without conflicts.

**Comment by Jeff11** [comment]
Newest version of org.koin:koin-java is 2.1.0-alpha-2. Looks like a bug. I'm getting the same error.

**Comment by egorikftp** [comment]
@arnaudgiuliani Could you please assist? The same issue from our side. Thanks

**Comment by arnaudgiuliani** [comment]
there is no more koin-java. Java helpers part is now part of koin-core

**Comment by henningBunk** [comment]
Thanks for the info!
Commit https://github.com/InsertKoinIO/koin/commit/3b7861de776120bc57c2d60bd90db1e44e9129af fixes the issue I guess. Also I found it in the changelog:

```
Java

    [REMOVED] - project is now part of koin-core
```
