### ISSUE TITLE
SharedViewModel with navigation component causing app crash

### ISSUE THREAD

**Issue by OleksandrGrument** [InsertKoinIO/koin#744]
**Describe the bug**
I'm using new navigation component and all was fine till the moment when I have to use sharedViewModel

I have 2 fragments A->B

In A I have viewmodel 
and in B i want to use the same viewModel 

in Fragment A is use code to inject viewmodel 
val viewModel: DetailsViewModel by viewModel { parametersOf(args.cityId, args.tourId) }

and in Fragment B i have this code 
val viewModel:DetailsViewModel by sharedViewModel ()

This line causing crash 
`E/[Koin]: Instance creation error : could not create instance for [Factory:'com.myapp.android.mobileapp.view.tour.details.DetailsViewModel']: org.koin.core.error.NoParameterFoundException: Can't get parameter value #0 from org.koin.core.parameter.DefinitionParameters@227292e
    	org.koin.core.parameter.DefinitionParameters.elementAt(DefinitionParameters.kt:32)
    	org.koin.core.parameter.DefinitionParameters.component1(DefinitionParameters.kt:34)
    	com.freetour.android.mobileapp.di.TourDiManager$tourModule$1$18.invoke(Unknown Source:14)
    	com.myapp.android.mobileapp.di.TourDiManager$tourModule$1$18.invoke(TourDiManager.kt:34)
    	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
    	org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:36)
    	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:87)
    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:209)
    	org.koin.core.scope.Scope.get(Scope.kt:177)
    	org.koin.androidx.viewmodel.ViewModelFactoryKt$defaultViewModelFactory$1.create(ViewModelFactory.kt:50)
    	androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
    	androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
    	org.koin.androidx.viewmodel.ViewModelResolutionKt.get(ViewModelResolution.kt:21)
    	org.koin.androidx.viewmodel.ViewModelResolutionKt.resolveInstance(ViewModelResolution.kt:10)
    	org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:70)
    	org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:56)
    	org.koin.androidx.viewmodel.koin.KoinExtKt.getViewModel(KoinExt.kt:34)
    	org.koin.androidx.viewmodel.ext.android.FragmentExtKt.getSharedViewModel(FragmentExt.kt:57)`

**Koin project used and used version (please complete the following information):**
implementation "org.koin:koin-android:2.1.1"
implementation "org.koin:koin-androidx-viewmodel:2.1.1"

**Comment by OleksandrGrument** [comment]
Also checked on newer version 2.1.3. The same bug

**Comment by lpetroli** [comment]
Adding support in Koin to https://github.com/InsertKoinIO/koin/issues/442 would solve this issue while also applying the correct Android idiom when using Navigation Components.

With navigation components, Android now has a view model builder callled navGraphViewModels. This is the way to share the same view model between 2 fragments in the same navigation flow.
