### ISSUE TITLE
 MonoClock deprecated in stdlib:1.3.70

### ISSUE THREAD

**Issue by PetkevichPavel** [InsertKoinIO/koin#745]
**Describe the bug**

Since Kotlin updated on 1.3.70, in Koin existing few deprecations which produce fails after updating the project onto Kotlin version 1.3.70.

Please replace **typealias MonoClock** by direct using of **"TimeSource.Monotonic".**

**Place of using:** *Measure.kt.*

Also, look through other deprecated things if they exist ;)

**Comment by egorikftp** [comment]
Already fixed in 2.2.3
