### ISSUE TITLE
KoinTest.declare 

### ISSUE THREAD

**Issue by jgavazzisp** [InsertKoinIO/koin#748]
**Describe the bug**
The declare component on the fly for tests seems not to be working. For instrumentation tests, I rely on that to config the tests and also for a unit test (changing coroutine dispatcher for Roboeletric, etc ...).

**To Reproduce**
1. Create simple Roboeletric test;
2. Create a simple module;
3. Overwrite any component of that module using the "declare" in the test class;
4. Fetch the component.

**Expected behavior**
Overwritten component to be given, but instead, we get the original component.

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core version 2.1.3`

**Comment by jgavazzisp** [comment]
Here is a JUnit 5 test case to exemplify the issue:

`
import com.google.common.truth.Truth.assertThat
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.koin.core.context.startKoin
import org.koin.core.context.stopKoin
import org.koin.dsl.module
import org.koin.test.KoinTest
import org.koin.test.inject
import org.koin.test.mock.declare

class TestKoin : KoinTest {

    private val subject by inject<Component>()

    @BeforeEach
    fun beforeEach() {
        val appModule = module {
            single<Component> { RealComponent() }
        }

        startKoin {
            modules(appModule)
        }

        declare<Component> { FakeComponent() }
    }

    @Test
    fun testFakeComponentIsGiven() {
        assertThat(subject).isInstanceOf(FakeComponent::class.java)
    }

    @AfterEach
    fun afterEach() {
        stopKoin()
    }

    // # component declaration #

    interface Component {
        fun doSomething()
    }

    class RealComponent : Component {
        override fun doSomething() {
            println("doSomethingReal")
        }
    }

    class FakeComponent : Component {
        override fun doSomething() {
            println("doSomethingFake")
        }
    }
}
`

So the result is:

`
value of            : getSubject()
expected instance of: nz.co.test.TestKoin$FakeComponent
but was instance of : nz.co.test.ui.TestKoin$RealComponent
with value          : nz.co.test.ui.TestKoin$RealComponent@2f112965
`

**Comment by jgavazzisp** [comment]
So from my test, if we change 

`
inline fun <reified T : Any> KoinTest.declare(
    qualifier: Qualifier? = null,
    noinline instance: () -> T
): T {
    val koin = KoinContextHandler.get()
    koin.declare(
        instance(),
        qualifier,
        override = true
    )
    return get(qualifier)
}
`

to 

inline fun <reified T : Any> KoinTest.declare(
    qualifier: Qualifier? = null,
    noinline instance: () -> T
): T {
    val koin = KoinContextHandler.get()
    koin.declare(
        instance(),
        qualifier,
        override = true,
        secondaryTypes = listOf(T::class)
    )
    return get(qualifier)
}

it would work.

**Comment by arnaudgiuliani** [comment]
fixed in 2.1.5
