### ISSUE TITLE
Create singleton object which implements 2 interfaces

### ISSUE THREAD

**Issue by NurseyitTursunkulov** [InsertKoinIO/koin#749]
`        single<ObserveLifeCycleState> {
            Communicator(
                domain = get(),
                repositoryMessanger = get()
            )
        }`

`        single<NewMessageListener> {
            Communicator(
                domain = get(),
                repositoryMessanger = get()
            )
        }`

As you can see I am instantiating the same 2 objects because it implements both interfaces. But this creates 2 different objects.  How can I do it with only one initialization?

**Comment by luxw** [comment]
I believe `single { Communicator() }.binds(ObserveLifeCycleState::class, NewMessageListener::class)` should do it

**Comment by mjordan-gpfw** [comment]
alternately, `singleOf(::Communicator).binds(listOf(ObserveLifeCycleState::class, NewMessageListener::class))`
