### ISSUE TITLE
Qualifiers, why `toString()` has s`q:`

### ISSUE THREAD

**Issue by alorma** [InsertKoinIO/koin#754]
**Is your feature request related to a problem? Please describe.**
We are adding custom `Qualifiers` to our app, and we started to create our objects copying the impl of `TypedQualifier` and `StringQualifier`... and we have seen something that we are curious about:

```kotlin
data class TypeQualifier(val type: KClass<*>) : Qualifier {
    override val value: QualifierValue = type.getFullName()
    override fun toString(): String {
        return "q:'$value'"
    }
}
```

We want tp ask why is the reason of override `toString()` and add `"q:'$value'"` instead of just value.

Thanks

**Comment by arnaudgiuliani** [comment]
fixed in 2.1.5
