### ISSUE TITLE
SharedViewModel from parent fragment

### ISSUE THREAD

**Issue by Christian89C** [InsertKoinIO/koin#755]
Hi, I was using sharedViewModel extension and now I see that the parameter "from" was deleted on latest version. Now the sharedviewmodel only works with hosting activity. Is not possible now to use this feature with another owner than the activity?

**Comment by Huangjiaqi0421** [comment]
+1， i can't get viewmodel from  parentFragment

**Comment by adisiji** [comment]
Well, you can use `requireParentFragment()` just like this:
```
private val filterControlViewModel: FilterControlViewModel by lazy {
        requireParentFragment().getViewModel<FilterControlViewModel>()
    }
```
