### ISSUE TITLE
Android Fragment lifecycle

### ISSUE THREAD

**Issue by TooLazyy** [InsertKoinIO/koin#757]
Let's say I have a `fragment A` with defined module
```
val mainFragmentModule = module {
    scope<A> {
        scoped { MyDataClass() }
    }
}
```
Inside the fragment I get MyDataClass like this:
`private val myDataClass: MyDataClass by currentScope.inject()`

**The problem:** after orientation change I'm getting the new instance instead of getting the old one.

**The docs say:** "This scope is created & bound to the component’s lifecycle." But on orientation change fragment is not destroyed completely (even `ViewModel` live through it).
Is there any way to make scoped instance outlive orientation change like VM does?

**Comment by nikhil-thakkar** [comment]
The scope is destroyed when the fragment is re-created in this case after being rotated. If you observe the code for `currentScope` specifically the `ScopeObserver`, it cleared when activity/fragment is re-created during a configuration change.

**Comment by TooLazyy** [comment]
SO is there any way to keep scoped instances alive?

**Comment by nikhil-thakkar** [comment]
There are a couple of ways I could think of :
1. Use a singleton if fits your use-case OR
2. Create a custom scope and don't clear it onDestroy by checking `isChangingConfigurations` on Activity instance. And how to get the Activity in Fragment? It's easy `requireActivity()` or `getActivity()`.

Something like this maybe in Fragment A:
```

onCreate(bundle) {
  if(bundle == null) {
     val scope = getKoin().getOrCreateScope("some-id", "some-qualifier")
     scope.inject()
  }
}
onDestroy() {
   if(!requireActivity().isChangingConfigurations()) {
     getKoin().getOrCreateScope("some-id", "some-qualifier").close()
  }
super.onDestroy()
}
```
This is just pseudo code but you should get an idea.

**Comment by iandreyshev** [comment]
@nikhil-thakkar 
Is there way to get navigation graph scope when work with NavComponents?
UseCase:
I have SingleActivity application with nav_graph and nested_nav_graph (nested_nav_graph in nav_graph)
How can I get scope for nav_graph (which is global scope for app) and scope for nested_nav_graph (which is scope for some feature) ?

**Comment by nikhil-thakkar** [comment]
@iandreyshev I haven't work with Nav Graph scope extensively so I probably won't be the best person to answer :(
