### ISSUE TITLE
Updating koin-androidx-viewmodel cause ERROR: Failed to resolve: androidx.lifecycle:lifecycle-viewmodel-savedstate:2.1.0

### ISSUE THREAD

**Issue by Like-fire** [InsertKoinIO/koin#764]
**Describe the bug**
Before i used koin-androidx-viewmodel with koin-core version 2.0.1
But it cause bugs with coroutines viewModelScope, hoping solve this issue i tried to update koin-core and koin-androidx-viewmodel to version 2.1.5, but this led to following build process issue: 
ERROR: Failed to resolve: androidx.lifecycle:lifecycle-viewmodel-savedstate:2.1.0
As i investigate, view-model-savedstate 2.1.0 was removed from all google maven repositories.

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core version 2.1.5`

**Comment by mehrdaddolatkhah** [comment]
I have the same problem my friend @arnaudgiuliani

**Comment by arnaudgiuliani** [comment]
Dep issue? 🤔

**Comment by arnaudgiuliani** [comment]
gradle issue
