### ISSUE TITLE
Not clear checkModules instruction: Gradle Plugin fails with NPE

### ISSUE THREAD

**Issue by Perfomer** [InsertKoinIO/koin#767]
**Describe the bug**
I found out very interesting feature — checkModules Gradle plugin from Koin.
But unfortunately executing Gradle task "checkModules" leads to NPE.
I'm sure the guide is not clear.

That's the error:
```
C:\Development\Projects\Pet\Ubily>gradlew checkModules
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':checkModules'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 693ms
```

**To Reproduce**
1. Define multimodule Android project.
2. Define Koin modules for each one.
3. Make sure it works correctly.
4. Apply next build.gradle file:
```groovy
apply plugin: 'koin'

buildscript {
    ext.kotlin_version = '1.3.71'

    repositories {
        google ()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.koin:koin-gradle-plugin:2.1.5"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
5. Write JUnit Test:
```Kotlin
@Category(CheckModuleTest::class)
class KoinModulesTest : KoinTest {

    @Test
    fun checkAllModules() = checkModules {
        modules(koinModules) // there are all modules of the project
    }

}
```
6. Then run command from Android Studio terminal:
`gradlew checkModules`

**Expected behavior**
Correct work of the command "checkModules", without NPE.

**Koin project used and used version (please complete the following information):**
- ```
    org.koin:koin-gradle-plugin:2.1.5
- ```
    implementation "org.koin:koin-androidx-scope:2.1.5"
    implementation "org.koin:koin-androidx-viewmodel:2.1.5"
    testImplementation "org.koin:koin-test:2.1.5"

**Comment by kirich1409** [comment]
For Android projects to proper check DI graph, you need to run the test using Robolectric or run it on an Android device

**Comment by Perfomer** [comment]
> For Android projects to proper check DI graph, you need to run the test using Robolectric or run it on an Android device

Yeap, now it works without NPE & says that modules are checked. Thank you.

Although the guide remain **incomplete**. 

I purposely remove one of my dependencies from the DI-graph, 'cause I want to see an error message about missing dependency. And... nothing. Test completed successfully.

So I don't understand what's the point of the Gradle script & tests.

**Comment by arnaudgiuliani** [comment]
The Koin Gradle offers a `checkModules` task to run unit tests tagged with `CheckModulesTest` category. Unfortunately for Android projects, this task is not working (NPE like here). We need to hook on `unitTestDebug` Android Gradle task.

I've just done the fix for `2.1.6`

**Comment by fmatosqg** [comment]
I'm running 2.1.6 but I still find errors in my module `sample`.
It happens with both targets `checkModules` and `:sample:checkModules`.
> Could not determine the dependencies of task ':sample:checkModules'.
> java.lang.NullPointerException (no error message)

Running with `--info` gives
> Configure project :sample
Evaluating project ':sample' using build file '/home/fabiomint/code/crocmedia/android/libs/bardeen/sample/build.gradle.kts'.
Creating configuration androidTestUtil
> . . .
> Selected primary task 'checkModules' from project :
Could not execute [class org.jetbrains.kotlin.gradle.plugin.statistics.DefaultKotlinBuildStatsService.buildFinished]


When I do `./gradlew connectedAndroidTest` it still runs it and throws the same errors as I'd get from running from inside Android Studio, so I got that covered for me. 


Maybe I need to wait for `checkAndroidModules` to land on 2.17?

**Comment by fmatosqg** [comment]
I think I found the reason, it may be because I have flavors on my sample module.

> ./gradlew checkAndroidModules
> . . .
>  What went wrong:
Could not determine the dependencies of task ':sample:checkAndroidModules'.
> Task with path 'testDebugUnitTest' not found in project ':sample'.

Sounds like a candidate for a separate issue, right?
