### ISSUE TITLE
Check DI Graph failed: SavedStateHandle is unknown parameter for stateViewModel injections

### ISSUE THREAD

**Issue by kirich1409** [InsertKoinIO/koin#771]
Checking a DI graph with `checkModules` is unsuccessful for an Android project where `stateViewModel` is injected. The issue is a declaration of `viewModel` with `SavedStateHandle` parameter is invalid for the tests.

**Expected behavior**
Injection of a ViewModel via `stateViewModel` must accept `SavedStateHandle` as a valid parameter

**Koin project used and used version (please complete the following information):**
koin-test 2.15

***Sample***
```kotlin
class SampleViewModel(savedStateHandle : SavedStateHandle) : ViewModel()
```
```kotlin
class SampleFragment() : Fragment() {
    val viewModel by stateViewModel<SampleViewModel>()
}
```
```kotlin
module {
   viewModel { (savedStateHandle : SavedStateHandle) ->
      SampleViewModel(savedStateHandle)
   }
}
```

**Comment by arnaudgiuliani** [comment]
Did you try to add default parameters?

**Comment by cyberrob** [comment]
What's default parameters?

**Comment by arnaudgiuliani** [comment]
now with 2.2.0 shoould be a bit better. You can use `defaultValue<SavedStateHandle>()`

not yet great experience 🤔
