### ISSUE TITLE
Koin Viewmodel don't cleared in fragment

### ISSUE THREAD

**Issue by congdcit** [InsertKoinIO/koin#774]
I use one activity using Navigation in Android. In detail fragment:

```
private val viewModel: SettingsVM by viewModel {
    parametersOf(item.settingModel)
}
```
First, in Main fragment navigate to details fragment, ViewModel is created. Later go back, then go to details the viewModel didn't create new instance. It using same previous instance.
Note: in details fragment using some children fragments and using sharedViewModel.

The expected create new instance depend on item in arguments of fragment.
Koin: 2.1.5
I also check issues [#532](https://github.com/InsertKoinIO/koin/issues/532)
Someone help me please.

**Comment by arnaudgiuliani** [comment]
is it done with Navigation framework?

**Comment by patelkathan** [comment]
Facing the same with `viewmodel:2.1.3` and android navigation components.

**Comment by arnaudgiuliani** [comment]
Ok
