### ISSUE TITLE
Define viewModel's key independently from qualifier 

### ISSUE THREAD

**Issue by hrach** [InsertKoinIO/koin#782]
**Is your feature request related to a problem? Please describe.**

We have one viewModel instantiated multiple times for different views, so we are using the viewModelKey to utilize such functionality. 
```kotlin
ViewModelProvider(...).get(ourViewModelKey)
```

It is possible to use Qualifier that will be used as a key but that also affects how the dependency should be defined.

So currently we cannot call simple `stateViewModel()` or `viewModel()` and we copy-fast few Koin's internal functions to do this.

**Describe the solution you'd like**

An optional property in these functions that will allow this.
It could be sufficient just in get(State)ViewModel functions.

**Describe alternatives you've considered**

```kt
/**
 * This method helps to use Koin's VM factory and store VM using a custom key.
 */
inline fun <reified T : ViewModel<*>> SavedStateRegistryOwner.getStateViewModel(
  viewModelKeyPrefix: String,
  bundle: Bundle?,
  noinline parameters: ParametersDefinition?
): T {
  val viewModelStore = (this as ViewModelStoreOwner).viewModelStore
  val koin = (this as ComponentCallbacks).getKoin()
  val scope = koin._scopeRegistry.rootScope

  val javaClass = T::class.java
  val bundleOrDefault = bundle ?: Bundle()
  val vmParams = ViewModelParameter(
    clazz = T::class,
    qualifier = null,
    parameters = parameters,
    bundle = bundleOrDefault,
    viewModelStore = viewModelStore,
    stateRegistryOwner = this
  )

  val viewModelFactory = scope.stateViewModelFactory(vmParams)
  val viewModelProvider = ViewModelProvider(viewModelStore, viewModelFactory)
  val viewModelKey = "$viewModelKeyPrefix:${javaClass.canonicalName}"
  return viewModelProvider.get(viewModelKey, javaClass)
}
```

**Target Koin project**

koin-androidx-viewmodel

**Comment by hrach** [comment]
This issue is similar to #497. The proposed workaround is not much applicable for us, we create the key dynamically depending on the view.id.

**Comment by pchmielowski** [comment]
From my investigation of Koin code, seems like output of `toString()` method of the qualifier is passed as a `key` parameter to `androidx.lifecycle.ViewModelProvider::get` method.
Therefore, if I'm not mistaken, there is a simpler workaround for the issue reported by @hrach:

1. In module, define `viewModel` as following:
```
viewModel(named("QualifierName")) { MyViewModel(get()) }
```
2. Create custom qualifier class:
```
data class ViewModelKeyQualifier(val key: String) : Qualifier {

    override val value = "QualifierName"

    override fun toString() = key
}
```
3. Use custom qualifier when getting view model:
```
val model by viewModel<MyViewModel>(ViewModelKeyQualifier(key = "key"))
```

@arnaudgiuliani Is my approach correct?

**Comment by hrach** [comment]
@pchmielowski Oh yes, that is one possible workaround. But we don't want to force our devs to declare viewModels with (any internal) qualifier, our definitions have already state and other piece of knowledge would make it more difficult to define.

**Comment by arnaudgiuliani** [comment]
yes, if you consider different qualifier & key yes 🤔
