### ISSUE TITLE
Problem with Use koin with room orm in androidx

### ISSUE THREAD

**Issue by mehrdaddolatkhah** [InsertKoinIO/koin#783]
**Describe the bug**
I try to use Koin with room database, I have app, domain and data layer. in the data layer, I try to make database and domain layer inside repository try to use DatabaseDao with inject(). 

this is my database: 

`
import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import com.chaparnet.rakeb.data.network.models.response.CitiesResponseModel

@Database(entities = [CitiesResponseModel::class], version = 1, exportSchema = false)
abstract class RakebDatabase : RoomDatabase() {

    abstract fun rakebDatabaseDao(): RakebDatabaseDao

    companion object {
        @Volatile
        private var INSTALNCE: RakebDatabase? = null

        fun getInstance(context: Context): RakebDatabase {
            synchronized(this) {
                var instance = INSTALNCE

                if (instance == null) {

                    instance = Room.databaseBuilder(
                        context.applicationContext,
                        RakebDatabase::class.java,
                        "rakeb_database"
                    )
                        .fallbackToDestructiveMigration()
                        .build()
                    INSTALNCE = instance
                }

                return instance
            }
        }

    }
}`

`import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import com.chaparnet.rakeb.data.network.models.response.CitiesResponseModel

@Dao
interface RakebDatabaseDao {

    /* Method to insert the movies fetched from api
     * to room */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    fun insertCities(cities: List<CitiesResponseModel>): LongArray

    /* Method to fetch the movies stored locally */
    @Query("SELECT * FROM `city_table`")
    fun getCities(): List<CitiesResponseModel>
}`

`import androidx.room.Room
import com.chaparnet.rakeb.data.cache.database.RakebDatabase
import org.koin.dsl.module

val databaseModule = module {
    factory { Room.databaseBuilder(get(), RakebDatabase::class.java, "rakeb-db")
        .build()  }

    factory {  get<RakebDatabase>().rakebDatabaseDao() }
}`

`
  private val rakebDatabaseDao: RakebDatabaseDao by inject()

 rakebDatabaseDao.insertCities(response.value?.apiObjects ?: arrayListOf())
`
when I try start application I got this error:
  Caused by: org.koin.core.error.DefinitionOverrideException: Definition '[Single:'com.chaparnet.rakeb.data.cache.database.RakebDatabaseDao']' try to override existing definition. Please use override option or check for definition '[Factory:'com.chaparnet.rakeb.data.cache.database.RakebDatabaseDao']'

may please guide me on how to fix this

**Comment by niom** [comment]
As far as I undestand that it is not a good idea to use factory for the database and for the dao. These files can be singletons and there for use single.  

So what happens here is that every time that you inject the DAO to a file it will first create an instance of the RakeDatabase and after that it will get the rakebDatabaseDao from the newly created instance.

What causes the definitionOverrideException is that you are doing something really funky when you start the koin context. That error indicates that you have double definition for RakebDatabaseDao. Unfortynately there's not enough code to indicate what is happening and how you build up the Koin context.

Try this:
``` 
val databaseModule = module {
   single { Room.databaseBuilder(get(), RakebDatabase::class.java, "rakeb-db").build() }

   single {  get<RakebDatabase>().rakebDatabaseDao() }
}
```

**Comment by wax911** [comment]
Just to add onto what @niom suggested, not really sure what might be causing the `org.koin.core.error.DefinitionOverrideException`, could be another module not directly tied to the sample code provided. You could make things a little bit easier for yourself by doing the following:

## Room database
```kotlin
@database(entities = [CitiesResponseModel::class], version = 1, exportSchema = false)
abstract class RakebDatabase : RoomDatabase() {

    abstract fun rakebDatabaseDao(): RakebDatabaseDao

    companion object {
        fun newInstance(context: Context): RakebDatabase {
            return Room.databaseBuilder(
                context,
                RakebDatabase::class.java,
                "rakeb-db"
            ).fallbackToDestructiveMigration()
                .build()
        }
    }
}
```
> You could also create an interface for your rake databases that has methods for accessing DAOs for better decoupling .e.g:
```kotlin
interface IRakeDatabase {
   fun rakebDatabaseDao(): RakebDatabaseDao
}

@database(entities = [CitiesResponseModel::class], version = 1, exportSchema = false)
abstract class RakebDatabase : RoomDatabase(), IRakeDatabase {

    companion object {
        fun newInstance(context: Context): IRakeDatabase {
            return Room.databaseBuilder(
                context,
                RakebDatabase::class.java,
                "rakeb-db"
            ).fallbackToDestructiveMigration()
                .build()
        }
    }
}
```
The above would mean you wouldn't have to depend on the a type of `RoomDatabase` in your koin definitions, but this is just a suggestion


## Koin extensions

```kotlin
// An extension function to access our database type. 
// If you are using the suggestion above 
// RakeDatabase would be replaced by IRakebDatabase
fun Scope.db() = get<RakebDatabase>()
``` 

## Koin modules

```kotlin
val databaseModule = module {
   single { RakebDatabase.newInstance(context = androidContext() ) }

   single { db().rakebDatabaseDao() }
}
```
> Instead of creating singleton instances of your DAOs it might be better to have these injected 
in the constructor of your repository. e.g.
```kotlin
val databaseModule = module {
   single { RakebDatabase.newInstance(context = androidContext() ) }
}

val repositoryModule = module {
   factory { RakeRepository(dao = db().rakebDatabaseDao()) }
}
```

**Comment by valentineRutto** [comment]
This solution worked for me , i was using koin 3.4.6 and room 2.5.2. I kept getting nobeandefinition and instance creation errors on Room.
