### ISSUE TITLE
Bring back the `from` parameter in SharedViewModel property delegate

### ISSUE THREAD

**Issue by PiotrPrus** [InsertKoinIO/koin#785]
**Is your feature request related to a problem? Please describe.**
In the newest version of Koin: 2.1.3 I cannot easily make a custom scope for my ViewModel.

**Describe the solution you'd like**
In version 2.0.1 of Koin, which I am using right now, there is a parameter `from` in SharedViewModel property delegate. In the newest version, 2.1.3 this parameter is gone. 

**Describe alternatives you've considered**
As discussed in this topic: #442, the current solution is: 
val owner = requireParentFragment().requireParentFragment().findNavController().getViewModelStoreOwner(navGraphId)
But is is not elegant. I liked the `from` parameter much more.

**Target Koin project**
Do not know. :)

**Comment by samuelhalim1** [comment]
@arnaudgiuliani hey, i dont know why.. when i use koin-androidx-viewmodel:2.0.1 the `from` parameter was still there.
But when i update it to koin-androidx-viewmodel:2.1.6.. its gone..

**Comment by arnaudgiuliani** [comment]
it's back in 2.2 ... confusing API. Sorry :/

**Comment by samuelhalim1** [comment]
> it's back in 2.2 ... confusing API. Sorry :/

wow really" thanks for the reply and hearing our problem.. love ya..

**Comment by LambergaR** [comment]
@arnaudgiuliani can't see the param in `2.2.0-rc-2`, will it be available in RC-3 or shall we wait for GA? Also, might I ask why that parameter was removed in the first place?

**Comment by arnaudgiuliani** [comment]
This param is `owner` not `from` 👍

![image](https://user-images.githubusercontent.com/2360688/95507123-3fd95080-09b1-11eb-90e4-a8ad2843e6a2.png)

**Comment by samuelhalim1** [comment]
@arnaudgiuliani could u give some example on how to use this `owner` param? please.. :(

**Comment by Kenny50** [comment]
for those who didn't find answer owner param without findNavController()

I currently facing one parent fragment and three child fragment, and the solution is
```
//parent
    private val parentViewModel by viewModel<TripParentViewModel>()

//child
private val viewModel: TripParentViewModel by viewModel(owner = { ViewModelOwner.Companion.from(requireParentFragment().requireParentFragment().viewModelStore)})
```

BE CAUTION: I call requireParentFragment twice because i use fragmentContainerView in parent fragment.
depend on your project, you might need to change to once or whatever situation you facing.
