### ISSUE TITLE
myScopeContainerObject.scope.close() is not working?

### ISSUE THREAD

**Issue by elye** [InsertKoinIO/koin#786]
**Describe the bug**
Koin version: `2.1.5`

`myScopeContainerObject.scope.close()` behave differently from
```
val scope = myScopeContainerObject.scope
scope.close
```

**To Reproduce**
I have an the below scope Object
```
scope<MyObject> {
    scoped { Presenter() }
}
```

When I close it, getting it on will crash as expected.

```
val myScope = myObject.scope
val presenter = myScope.get<Presenter>(Presenter::class.java)
myScope.close()
val presenter2 = myScope.get<Presenter>(Presenter::class.java) // Crash here.
```

However if I don't assign out, but close it too. It still works.
```
val presenter = myObject.scope.get<Presenter>(Presenter::class.java)
myObject.scope.close()
val presenter2 = myObject.scope.get<Presenter>(Presenter::class.java) 
// presenter1 == presenter2
```
I still can get my `presenter` the same copy as I get before I close it.

I think there's a bug somewhere.

More description in 
https://stackoverflow.com/questions/61321896/koin-why-after-myobject-scope-close-it-still-works

**Comment by erickok** [comment]
I might be wrong, but it reads like `.scope` creates a new scope instance, so it makes sense that in the first case (where a single instance is used) the scope is closed yet in the second case using `.scope` the second time creates a whole new instance, one that is therefor not closed.

**Comment by elye** [comment]
If that's the case, then to close, one has to assign the scope to a variable to close it. That doesn't sound right.

**Comment by arnaudgiuliani** [comment]
`.scope` is more a shortcut for `getOrCreateScope` for the given instance

**Comment by elye** [comment]
So in another word, can I say that it is very important one not to use  `myObject.scope` directly, and always assign to something before using it i.e. `val myScope = myObject.scope` especially for closing it?

**Comment by elye** [comment]
I still think it make sense for `myObject.scope.close()` to close properly, as `myObject.scope` will always bring out the same scope if it is already created.

**Comment by elye** [comment]
After trying further, the `myObject.scope.close()` do work. And the previously assigned `myScope` will not work anymore. Just that when one perform `myObject.scope`, it will generate a new one. 

This make sense. One just have to be careful, else it will be confusing. Closing the issue.
