### ISSUE TITLE
Single is Scoped, and Scoped is Single... why introduce 2 terminologies?

### ISSUE THREAD

**Issue by elye** [InsertKoinIO/koin#788]
Koin version: `2.1.5`

As we know we have `single` and `factory`

```
    module {
        single { SingeDependency() }
        factory { SingeDependency() }
   }
```

However when we have scope
```
    module {
        scope<Object> {
            scoped { SingeDependency() }
            factory { SingeDependency() }
        }
   }
```

To  me, `scoped` and `single` is the same thing... one is within the `module`, and the other is within the `scope<Object>`.
Why introduce two name and confuses many the usage. Why not just `single` or `scoped`....

I think just make the below, would be meaningful enough... people could understand it's single within the `scope<Object>`.
```
    module {
        scope<Object> {
            single { SingeDependency() }
            factory { SingeDependency() }
        }
   }
```

**Note** `single` within `module` is not really singleton as well
```
    module {
        single { SingeDependency() }
        factory { SingeDependency() }
   }
```

This is because a could load `loadKoinModules(myModule)` and `unloadKoinModules(myModule)`, and hence it is destroyed and recreated when the module is loaded again.

**Comment by arnaudgiuliani** [comment]
at the beginning of the project, it wasn't so clear. Now effectively, scoped and single are the same.

**Comment by arnaudgiuliani** [comment]
please check latest code source again and check. Those concepts don't apply anymore like that
