### ISSUE TITLE
State Shared View Model

### ISSUE THREAD

**Issue by josephbnb** [InsertKoinIO/koin#791]
Is there a way to have a state shared view model? I tried to use `by stateViewModel()` is the activity and `by sharedViewModel()` in the fragments but I keep getting this crash:

```
org.koin.core.error.NoParameterFoundException: Can't get parameter value #0 from org.koin.core.parameter.DefinitionParameters@f41855c
    	org.koin.core.parameter.DefinitionParameters.elementAt(DefinitionParameters.kt:32)
    	org.koin.core.parameter.DefinitionParameters.component1(DefinitionParameters.kt:34)
    	[...].di.ViewModelsModuleKt$viewModels$1$3.invoke(Unknown Source:10)
    	[...].di.ViewModelsModuleKt$viewModels$1$3.invoke(Unknown Source:4)
    	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
    	org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:36)
    	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:87)
    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:214)
    	org.koin.core.scope.Scope.get(Scope.kt:181)
    	org.koin.androidx.viewmodel.ViewModelFactoryKt$defaultViewModelFactory$1.create(ViewModelFactory.kt:50)
    	androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
    	androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
    	org.koin.androidx.viewmodel.ViewModelResolutionKt.get(ViewModelResolution.kt:21)
    	org.koin.androidx.viewmodel.ViewModelResolutionKt.resolveInstance(ViewModelResolution.kt:10)
    	org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:70)
    	org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:56)
    	org.koin.androidx.viewmodel.koin.KoinExtKt.getViewModel(KoinExt.kt:34)
    	org.koin.androidx.viewmodel.ext.android.FragmentExtKt.getSharedViewModel(FragmentExt.kt:57)
```

**Comment by cyberrob** [comment]
I got exactly THE SAME exception.

**Comment by HombreTech** [comment]
Have a same exception.

**Comment by arnaudgiuliani** [comment]
the thing here is that your should use `sharedStateViewModel` when willing to use a shared instance. I think a fix is currently in 2.1.6

**Comment by arnaudgiuliani** [comment]
Keep passing bundle as param, to initiate state.

**Comment by arnaudgiuliani** [comment]
Fix in 2.1.6 to allow lazy bundle parameter.

**Comment by acolombo25** [comment]
> the thing here is that your should use `sharedStateViewModel` when willing to use a shared instance. I think a fix is currently in 2.1.6

It isn't there anymore in 2.2.2. What's the alternative?

**Comment by arnaudgiuliani** [comment]
it's back in 3.0.1

**Comment by JurajKuliska** [comment]
I started facing the same issue after upgrading from 3.1.6 to 3.2.0 that cyberrob reported earlier - https://github.com/InsertKoinIO/koin/issues/791#issuecomment-621690700

The viewModels that require a SavedStateHandle just crash with that stacktrace right on initialization

**Comment by JurajKuliska** [comment]
> did you check `sharedStateViewModel` ?

Thanks so using `sharedStateViewModel` in all of the fragments while using `stateViewModel` in the hosting activity resolves the issue

**Comment by arnaudgiuliani** [comment]
great
