### ISSUE TITLE
Issue with Dynamically loading modules in a release/signed APK

### ISSUE THREAD

**Issue by pkondamudi** [InsertKoinIO/koin#792]
**Describe the bug**
I am trying to load modules dynamically using loadKoinModules() on activity create and the modules are not getting overriden after signing APK. It still picks the module loaded during startKoin{}. The same code is working for a debug APK, i am able to override the modules with out any issues.
**To Reproduce**
@arnaudgiuliani I am trying to using loadKoinModules() in a signed APK and it doesn't seem to be working. If i build a debug APK, i am able to override modules. Is there any specific setting which needs to be set to make it work with signed APKs?

```
class MainActivity : AppCompatActivity() {

    val dynamicFeatures by lazy { loadKoinModules(dynamicHttpModule) }
    fun overrideKoinModules() = dynamicFeatures

override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
       unloadKoinModules(httpModules)
        overrideKoinModules()
}
}
```

**Expected behavior**
Should be able to override modules also in Signed APK without any issue.

**Koin project used and used version (please complete the following information):**
org.koin:koin-core:2.1.5

**Additional moduleDefinition**
Add any other moduleDefinition about the problem here.
@arnaudgiuliani

**Comment by arnaudgiuliani** [comment]
There should be any problem regarding signed APK or not. Any special content on your dynamic module?

**Comment by pkondamudi** [comment]
Closing this issue as there was issue with Async logic but not really Koin logic
