### ISSUE TITLE
createAtStart should also work when loadKoinModules() is called

### ISSUE THREAD

**Issue by bseib** [InsertKoinIO/koin#801]
**Is your feature request related to a problem? Please describe.**

In our application we create a bare-bones KoinApplication that knows just enough to assess and setup a local environment to get it into a stable, well known state. Once in that known state, then more modules are loaded, based on the conditions of what happened in the assessment/setup phase. It looks like this:

```kotlin
        val bootstrapModule = module {
            single { AAA(get()) }
            single { BBB() }
            single(createdAtStart = true) { CCC(get()) }
        }
        startKoin {
            modules(bootstrapModule)
        }

        val moduleDDD = buildDDDModule( ... using AAA, BBB or CCC ... )
        val moduleEEE = module {
          single(createdAtStart = true) { ZZZ() }
        }
        val moduleFFF = module { ... }
        loadKoinModules(listOf(
          moduleDDD,
          moduleEEE,
          moduleFFF
        ))

```

The problem is that `ZZZ` does not get created when `loadKoinModules` is called. When `ZZZ` is something that we want to "fail fast", we won't know there is a problem until it gets instantiated later.

**Describe the solution you'd like**

The desired behavior is to have `loadKoinModules()` honor the `createAtStart` flag. The meaning of `createAtStart` would perfectly fit with the intent.

**Describe alternatives you've considered**

The current workaround is to place some dummy code that calls upon `ZZZ` early in the application.

**Comment by holgerbrandl** [comment]
The workaround does not apply when building a library, where ZZZ is usercode that is outside of the control of the library developer.  Consider the following example 

```
import org.koin.core.context.startKoin
import org.koin.dsl.module

class Core {
    init{ println("Init Core")}
}

class ZZZ {
    init{ println("Init ZZZ")}
}

fun main() {
    val coreModule = module { single(createdAtStart = true) { Core() } }


    val ka = startKoin { modules(coreModule) }

    // module definition is just inlined here for illustration, but would be provided by user when using the library built using koin
    val userModule = module { single(createdAtStart = true) { ZZZ() } }

    ka.koin.loadModules(listOf(userModule))

    println("finished setup")

    val foo = ka.koin.get<ZZZ>()
}
``` 
Because `loadKoinModules()` does not yet honor `createAtStart`, the initialization happens too late when the object is retrieved but not during setup. The output is
```
Init Core
finished setup
Init ZZZ
```
but the intent would be
```
Init Core
Init ZZZ
finished setup
```

Is there another workaround (like iterating all registered objects to force instantiation) until the bug is fixed?

**Comment by bseib** [comment]
Warning -- This hack/workaround is *just a guess* by just poking through the latest Koin code on github for a few minutes. I found a function `createEagerInstances()` that is responsible for carrying out the `createdAtStart` business. Assuming you have only a single scope, then the following would attempt to call that function again on the root scope.

```kotlin
loadKoinModules(listOf( ... ))
KoinContextHandler.get()._scopeRegistry.rootScope.createEagerInstances()
```

I have not actually tried this, nor do I know if there are any side effects of calling that function late in the game. So it's only a suggestion of where to poke while you look for a workaround.

----

I thought I might look at a proper solution and opening a PR, but after 20 minutes I couldn't get past having the right android stuff setup in my local environment to do a build. ☹️  So perhaps another time. 😃

**Comment by holgerbrandl** [comment]
Thanks @bseib for your help. However it currently does not work because `createEagerInstances` is tagged as `internal`, that is it can not be used outside of the koin codebase.

**Comment by arnaudgiuliani** [comment]
added `createEagerInstances` parameter to `loadModules` function, in Koin 2.2.0

**Comment by iamriajul** [comment]
> added `createEagerInstances` parameter to `loadModules` function, in Koin 2.2.0

Can you please give me an example for Android? 

I'm trying this way, but it's an internal function 
`getKoin().createEagerInstances()`

I have seen that KoinApplication has the createEagerInstances method as public, but I couldn't find a way to get the current KoinApplication instance!

Thanks.
