### ISSUE TITLE
Spelling in Talking about Koin section

### ISSUE THREAD

**Issue by IgorTorbaDebitoor** [InsertKoinIO/koin#802]
**Describe the bug**
Hey, sorry to say, but you have a typo in _Talking about Koin. Video&Podcasts_ section.
![image](https://user-images.githubusercontent.com/52786526/81380501-b547a900-9113-11ea-8653-75873e86061a.png)

Instead of _Urkaine_ should be _Ukraine_

**To Reproduce**
1. Go to https://github.com/InsertKoinIO/koin
2. Scroll down to _Talking about Kotlin_
3. Scroll down to _Video & Podcasts_

**Expected behavior**
Name of country in last row should be _Ukraine_ instead of _Urkaine_

**Comment by arnaudgiuliani** [comment]
👍
