### ISSUE TITLE
KointTestRule doesn't catch potential exceptions in tests

### ISSUE THREAD

**Issue by mottl-jan** [InsertKoinIO/koin#803]
**Description**
When the exception is thrown in the JUnit test which uses `KoinTestRule`, it fails other tests as well because the exception is not caught in the rule.

**To Reproduce**
I created a simple demo to illustrate the issue. 
```
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
class KoinTest {

    @get:Rule
    val koinRule = KoinTestRule.create {}

    @Test
    fun first() {
        throw Exception()
    }

    @Test
    fun second() {}
}
```
Second test should pass but fails with `java.lang.IllegalStateException: A KoinContext is already started`.

Here is the implementation in the `KoinTestRule`.
```
override fun apply(base: Statement, description: Description): Statement =
            object : Statement() {
                override fun evaluate() {
                    _koin = startKoin(appDeclaration = appDeclaration).koin
                    base.evaluate()
                    stopKoin()
                    _koin = null
                }
            }
```
`base.evaluate()` throws an exception from the test which is not caught and Koin is not properly stopped. Solution is to catch the exception or extend `TestWatcher` instead of `TestRule` because `TestWatcher` already handles exceptions internally.

**Koin project used and used version**
`koin-test version 2.1.5`

**Comment by arnaudgiuliani** [comment]
Closing this. Continuing to PR 👍
