### ISSUE TITLE
IllegalStateException: InstanceRegistry when app restarts

### ISSUE THREAD

**Issue by extmkv** [InsertKoinIO/koin#809]
**Describe the bug**
`java.lang.IllegalStateException: InstanceRegistry already contains index 'okhttp3.Interceptor'` when the app restarts after a crash.

**To Reproduce**
1. Force a crash inside the app
2. Restarts the app.
3. App crashes starting Koin

**Expected behavior**
The app restarts and and Koin starts with success.

**Koin project used and used version (please complete the following information):**
`koin-core version 2.1.5`

**Additional moduleDefinition**

```
single { AuthInterceptor(get()) } bind Interceptor::class
single { DeviceInfoInterceptor(get()) } bind Interceptor::class`
```

Works fine in version 2.0.1

**Comment by arnaudgiuliani** [comment]
Could you test with last 2.2.0?

**Comment by heitorri** [comment]
Hello, 

I have the same problema in 2.2.0

**Comment by arnaudgiuliani** [comment]
I'm closing it due to inactivity. Please reopen if you still have the case.
