### ISSUE TITLE
Can we check koin is started?

### ISSUE THREAD

**Issue by Chayangkoon37** [InsertKoinIO/koin#810]
i want to check koin is started

**Comment by egorikftp** [comment]
https://github.com/InsertKoinIO/koin/issues/254

```
if (KoinContextHandler.getOrNull() == null) {
        startKoin {
          
        }
    }
```

**Comment by YoussefHachicha** [comment]
`KoinContextHandler` is deprecated. Use the following code instead:

```
if (GlobalContext.getOrNull() == null) {
    startKoin {
        // do some initialization
    }
}
```

**Comment by frangulyan** [comment]
> `KoinContextHandler` is deprecated. Use the following code instead:
> 
> ```
> if (GlobalContext.getOrNull() == null) {
>     startKoin {
>         // do some initialization
>     }
> }
> ```

This doesn't work in multiplatform, seems like GlobalContext is not available there.

**Comment by egorikftp** [comment]
@frangulyan 
Looks like this can help https://github.com/InsertKoinIO/koin/blob/32c43ac2c9ffda3c988a290f5e15047dfed940e8/projects/core/koin-core/src/commonMain/kotlin/org/koin/mp/KoinPlatform.kt#L59

**Comment by arnaudgiuliani** [comment]
even use `KoinPlatform` API that is Multiplatform
