### ISSUE TITLE
How can i pass current activity context to the normal helper class with koin?

### ISSUE THREAD

**Issue by vandit067** [InsertKoinIO/koin#812]
Hey, i just start using koin and facing one issue in which my helper class like FragmentHelper and Dialog Helper class required activity context. how can i pass the activity context using koin in these kind of classes? See below classes.

class FragmentHelper constructor(private val context: Context) 
class DialogHelper constructor(private val context: Context) : DialogView

**Comment by arttttt** [comment]
https://doc.insert-koin.io/#/koin-core/injection-parameters

**Comment by vandit067** [comment]
Hey @arttttt , Thanks for sharing the link with me. i am already currently passing the activity context using by parameter injection but i am thinking like is there any other way through which i don't need to do parameter injection and by using get() or through some other function koin passed me the current activity context?

**Comment by arttttt** [comment]
you can try something like that

`
scope.declare(this) //'this' is your activity
`

`
scope {
    factory/single<T> {
        get<Context>() // will return your activity context
    }
}
`
