### ISSUE TITLE
get the scope of an activity inside module not working

### ISSUE THREAD

**Issue by ahmadmssm** [InsertKoinIO/koin#815]
I have an activity that hosts some fragments and each fragment has its own view model and there is only one repo scoped to the life cycle of the activity like this.

```
scope<AuthenticationActivity> {
      scoped { AuthenticationRepo(authenticationAPIs = get()) }
}
```
Now when i try to get the the repo inside the view model like this 

```
viewModel { LoginViewModel(authenticationRepo = getOrCreateScope()) }
```
OR 
```
viewModel { LoginViewModel(authenticationRepo = get()) }
```

I got this error: Can't use Scope source for AuthenticationRepo - source is:null

`koin version 2.1`

**Comment by arttttt** [comment]
Fragment scope know nothing about your activity by default. You need connect fragment and activity scopes.

https://doc.insert-koin.io/#/koin-core/scopes?id=scope-linking-210
