### ISSUE TITLE
Let ViewModel state or not don't affect its user

### ISSUE THREAD

**Issue by baoti** [InsertKoinIO/koin#820]
**Is your feature request related to a problem? Please describe.**

I'd like to remove `stateViewModel()` and `sharedStateViewModel()`, just use `viewModel()` and `sharedViewModel()` instead.

**Describe the solution you'd like**

```kotlin
// without SavedStateHandle
class MyVM(val myService: MyService) : ViewModel()

// with SavedStateHandle
class MyStateVM(val handle: SavedStateHandle, val myService: MyService) : ViewModel()
```

In Koin module:
```kotlin
// without SavedStateHandle
viewModel { MyVM(get()) }

// with SavedStateHandle
stateViewModel { MyStateVM(savedState(), get()) }

// or just
viewModel { MyStateVM(savedState(), get()) }
```

In Activity/Fragment, use the `by viewModel()` or `by sharedViewModel()` API:
```kotlin
val myVM: MyVM by viewModel()

// no different with MyVM
val myStateVM: MyStateVM by viewModel()
val mySharedStateVM: MyStateVM by sharedViewModel()
```

**Describe alternatives you've considered**

I hope API just like `by viewModels()` and `by activityViewModels` in [viewmodel-savedstate](https://developer.android.google.cn/topic/libraries/architecture/viewmodel-savedstate).

**Target Koin project**

koin-androidx-viewmodel

**Comment by Zhuinden** [comment]
You need to use the `AbstractSavedStateViewModelFactory` to obtain a reference to a `SavedStateHandle` that is managed by an associated saved state controller.

If `stateViewModel` were removed, that would mean that `by viewModels`/`by activityViewModels` should be replaced with whatever `stateViewModel` is doing internally to get the reference to the SavedStateHandle. Which, I think is actually a good thing.

**Comment by arnaudgiuliani** [comment]
Something that would help simplify the API, yes clearly 👍

**Comment by arnaudgiuliani** [comment]
New API is helping with that: https://doc.insert-koin.io/#/koin-android/viewmodel?id=viewmodel-and-state-bundle
