### ISSUE TITLE
Calling inject() extension within @Composable functions  

### ISSUE THREAD

**Issue by henrikhorbovyi** [InsertKoinIO/koin#823]
Playing around with Koin + Jetpack Compose, I would like to inject a dependency within a `@Composable` function.   

``` kotlin
@Composable
fun AppContent() {
    val newsRepository: NewsRepository by inject() // <~ it does not copile
    NewsScreen(newsRepository)
}
```
In this case, you get an error, because inject is an extension on `KoinComponent`, and there is no `KoinComponent` in this scope. 

So, I thought about a `@Composable` function that provides a `KoinComponent` scope.

 ``` kotlin 
object InjectableComponent : KoinComponent

@Composable
fun Injectable(child: @Composable InjectableComponent.() -> Unit) {
    child(InjectableComponent)
}
```
Using this `@Composable` would be like this:

``` kotlin
@Composable
fun AppContent() {
    Injectable { 
        val newsRepository: NewsRepository by inject()
        NewsScreen(newsRepository)
    }
}
``` 

I'd like to discuss this topic and hear opinions from you all

**Comment by arnaudgiuliani** [comment]
If you use a standard Koin context, you can simply get Koin anywhere with `KoinContextHandler.get()`

**Comment by henrikhorbovyi** [comment]
`KoinContextHandler` is in the `org.koin:koin-android`?

**Comment by arnaudgiuliani** [comment]
in the main `koin-core` yes

**Comment by henrikhorbovyi** [comment]
I'm using `core`

![image](https://user-images.githubusercontent.com/5937963/85034698-b4655680-b158-11ea-8e04-8ea1e485ceff.png)

But I can't find the `KoinContextHandler` :thinking:

**Comment by arnaudgiuliani** [comment]
in 2.0.x, it's `KoinContext.get()`

**Comment by henrikhorbovyi** [comment]
I don't know what I'm doing wrong, but I can't find KoinContext.get().

![image](https://user-images.githubusercontent.com/5937963/86145639-8d4e4380-bacd-11ea-811c-f86423fdeb98.png)

The most near that I get was: `GlobalContext`, is it the same? can I use it? :thinking:

**Comment by henrikhorbovyi** [comment]
@arnaudgiuliani we've started a thread on [koin-dev](https://kotlinlang.slack.com/archives/CRF31N2HW/p1593531679064100). I'd like to hear your opinion :smile:

**Comment by henrikhorbovyi** [comment]
@arnaudgiuliani. I check out my branch from `master` so now I can use `val context = KoinContextHandler.get()` in my PR. 
Do you think it's better to use `GlobalContext` instead because it's a new way or I can use KoinContextHandler with no problem?

**Comment by arnaudgiuliani** [comment]
`KoinContextHandler` is the context handler, that help us prepare the land for Kotlin MP & otehr Koin context handling strategies. `GlobalContext` is not accessible anymore I guess 🤔 

We have started to speak about a compose project for Koin on #koin-dev
