### ISSUE TITLE
Fragment injected inside activity scope is recreated every time.

### ISSUE THREAD

**Issue by ahmadmssm** [InsertKoinIO/koin#824]
Sample code

```
val appModule = module {
    scope<MyActivity> {
        fragment { MyFragment(get()) }
    }
}
```

**Comment by arnaudgiuliani** [comment]
You need to provide your Activity's code. I believe that you are mixing Scope & Fragment factory.

**Comment by ahmadmssm** [comment]
Thanks for your reply @arnaudgiuliani.
Here is my code:
```
// Injection
 scope<AuthenticationActivity> {
        fragment { LoginFragment() }
        fragment { SignUpFragment() }
        fragment { ForgotPasswordFragment() }
}

// Activity
class AuthenticationActivity: AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        setupKoinFragmentFactory(lifecycleScope)
        super.onCreate(savedInstanceState)
    }

    protected fun <F: Fragment>openFragment(fragmentClass: Class<F>, args: Bundle? = null) {
        // My code to switch fragment
    }

    override fun onBackPressed() {
        if (supportFragmentManager.backStackEntryCount == 1)
            finish()
        else
            super.onBackPressed()
}
```

**Comment by arnaudgiuliani** [comment]
Don't use Scope for your injected Fragment. Just declare them as `fragment`

**Comment by arnaudgiuliani** [comment]
Possible that Scope API can conflict with Fragment Factory

**Comment by ahmadmssm** [comment]
Thanks, 
Tries this solution now but still, It returns a new instance every time,
Also according to the [documentation](https://doc.insert-koin.io/#/koin-android/fragment-factory) I can use this feature.
I'm also was wondering if this solution worked, how the life cycle of the fragment will be tied to the current activity if i'm not working with Single activity ?

**Comment by ahmadmssm** [comment]
@arnaudgiuliani

**Comment by arnaudgiuliani** [comment]
take care that your Activity scope will follow how your activity is restarted. 

Can you check without a Scope here. Not sure you need a scope to handle your fragments.

**Comment by ahmadmssm** [comment]
@arnaudgiuliani 
Yes, I know that the activity scope follows the lifecycle of the activity.
I will tell you about my use case, I have a fragment that is a container to other fragments so i need something to be scoped to the life cycle fo the container fragment and be removed when the fragment is destroyed.

**Comment by ahmadmssm** [comment]
@arnaudgiuliani

**Comment by arnaudgiuliani** [comment]
> so i need something to be scoped to the life cycle fo the container fragment and be removed when the fragment is destroyed.

`factory` definition is not enough?

**Comment by ahmadmssm** [comment]
@arnaudgiuliani I think in this case no, because factory definition can only be accessed from the Fragment itself but what if I want to access it from a child Fragment, for example, a Fragment with a view pager that holds other Fragments, so how to access the definition from one of those children ?
