### ISSUE TITLE
Properly casting an injected interface

### ISSUE THREAD

**Issue by mpivchev** [InsertKoinIO/koin#825]
I have the following provided interface:
```kotlin
single<ISpotifyModule> { SpotifyModule(get(), getWith("SpotifyModule"))}
```

Since some components need the implementation class, I cast it this way:
```kotlin
private val iSpotifyModule: ISpotifyModule by inject()
private val spotifyModule = iSpotifyModule as SpotifyModule
```

Is this the only way to do it? Looks very messy. Some classes need the interface and some need the actual implementation, so I am forced to cast the interface whenever it's needed.

**Comment by arttttt** [comment]
`
single { SpotifyModule(get(), getWith("SpotifyModule"))} bind ISpotifyModule::class
`
