### ISSUE TITLE
Android: ru.terrakok.cicerone + org.koin:koin-test = Can't get instance for androidx.appcompat.app.AppCompatActivity

### ISSUE THREAD

**Issue by frist008** [InsertKoinIO/koin#826]
**Describe the bug**
Cannot add activity to parameters during testing.

**To Reproduce**
1. Create empty project
2. Create Test
```kotlin
@RunWith(RobolectricTestRunner::class)
@Config(manifest = Config.NONE, sdk = [Build.VERSION_CODES.P])
@Category(CheckModuleTest::class)
class CheckCoffeeModuleTest {
    @Test
    fun checkCoffeeModule() {
        checkModules(
            parameters = {
                create<MainActivityNavigator> { parametersOf(AppCompatActivity()) }
            }, appDeclaration = {
                modules(activitiesModule)
            })
    }
}
```
3. Create Navigator for cicerone
```kotlin
class MainActivityNavigator(activity: AppCompatActivity) :
    SupportAppNavigator(
        activity,
        activity.supportFragmentManager,
        R.layout.activity_main
    )
```
4. Create koin module
```kotlin
val activitiesModule = module {
    scope<MainActivity> {
        scoped { Cicerone.create(Router()) }
        scoped { get<Cicerone<Router>>().navigatorHolder }
        scoped { get<Cicerone<Router>>().router }
        scoped { MainActivityNavigator(get()) } // get() -> MainActivity as AppCompatActivity
    }
}
```
5. Create MainActivity
```kotlin
class MainActivity : AppCompatActivity() {
    
    private val router: Router by lifecycleScope.inject()
    private val navigatorHolder: NavigatorHolder by lifecycleScope.inject()
    private val navigator: MainActivityNavigator by lifecycleScope.inject { parametersOf(this) } // provide AppCompatActivity
    
    override fun onResumeFragments() {
        super.onResumeFragments()
        navigatorHolder.setNavigator(navigator)
    }
    
    override fun onPause() {
        navigatorHolder.removeNavigator()
        super.onPause()
    }
}
```
6. run app -> Everything works without errors.
7. run app test -> 

> [ERROR] [Koin] Can't get instance for androidx.appcompat.app.AppCompatActivity
> [ERROR] [Koin] Instance creation error : could not create instance for [Single:'com.koin.myapplication.MainActivityNavigator',scope:q:'com.koin.myapplication.MainActivity']: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'androidx.appcompat.app.AppCompatActivity'. Check your definitions!
> 	org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:247)
> 	org.koin.core.scope.Scope.resolveInstance(Scope.kt:216)
> 	org.koin.core.scope.Scope.get(Scope.kt:181)
> 	com.koin.myapplication.ActivitiesModuleKt$mainActivityScope$1$1.invoke(ActivitiesModule.kt:26)
> 	com.koin.myapplication.ActivitiesModuleKt$mainActivityScope$1$1.invoke(ActivitiesModule.kt)
> 	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
> 	org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:40)
> 	org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:48)
> 	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:87)
> 	org.koin.core.scope.Scope.resolveInstance(Scope.kt:214)
> 	org.koin.core.scope.Scope.get(Scope.kt:181)
> 	org.koin.test.check.CheckModulesKt.runDefinition(CheckModules.kt:86)
> 	org.koin.test.check.CheckModulesKt.runScope(CheckModules.kt:78)
> 	org.koin.test.check.CheckModulesKt.checkScopedDefinitions(CheckModules.kt:70)
> 	org.koin.test.check.CheckModulesKt.checkModules(CheckModules.kt:50)
> 	org.koin.test.check.CheckModulesKt.checkModules(CheckModules.kt:32)
> 	org.koin.test.check.CheckModulesKt.checkModules(CheckModules.kt:40)
> 	org.koin.test.check.CheckModulesKt.checkModules$default(CheckModules.kt:37)
> 	com.koin.myapplication.CheckCoffeeModuleTest.checkCoffeeModule(CheckCoffeeModuleTest.kt:21)
> 
> org.koin.core.error.InstanceCreationException: Could not create instance for [Single:'com.koin.myapplication.MainActivityNavigator',scope:q:'com.koin.myapplication.MainActivity']
> 
> 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:59)
> 	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:40)
> 	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:48)
> 	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:87)
> 	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:214)
> 	at org.koin.core.scope.Scope.get(Scope.kt:181)
> 	at org.koin.test.check.CheckModulesKt.runDefinition(CheckModules.kt:86)
> 	at org.koin.test.check.CheckModulesKt.runScope(CheckModules.kt:78)
> 	at org.koin.test.check.CheckModulesKt.checkScopedDefinitions(CheckModules.kt:70)
> 	at org.koin.test.check.CheckModulesKt.checkModules(CheckModules.kt:50)
> 	at org.koin.test.check.CheckModulesKt.checkModules(CheckModules.kt:32)
> 	at org.koin.test.check.CheckModulesKt.checkModules(CheckModules.kt:40)
> 	at org.koin.test.check.CheckModulesKt.checkModules$default(CheckModules.kt:37)
> 	at com.koin.myapplication.CheckCoffeeModuleTest.checkCoffeeModule(CheckCoffeeModuleTest.kt:21)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
> 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
> 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
> 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
> 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
> 	at org.junit.runners.Suite.runChild(Suite.java:128)
> 	at org.junit.runners.Suite.runChild(Suite.java:27)
> 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
> 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
> 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
> 	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
> 	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
> 	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
> Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'androidx.appcompat.app.AppCompatActivity'. Check your definitions!
> 	at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:247)
> 	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:216)
> 	at org.koin.core.scope.Scope.get(Scope.kt:181)
> 	at com.koin.myapplication.ActivitiesModuleKt$mainActivityScope$1$1.invoke(ActivitiesModule.kt:26)
> 	at com.koin.myapplication.ActivitiesModuleKt$mainActivityScope$1$1.invoke(ActivitiesModule.kt)
> 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
> 	... 47 more

**Expected behavior**
I get `parameters `from `checkModules `to `it `in `scoped { it -> MainActivityNavigator(get())}`.
I expect them to automatically fall into `get()`.

**Koin project used and used version (please complete the following information):**
```gradle
    implementation "ru.terrakok.cicerone:cicerone:5.1.1"
    implementation "org.koin:koin-android:2.1.5"
    implementation "org.koin:koin-androidx-scope:2.1.5"
    implementation "org.koin:koin-androidx-ext:2.1.5"
    testImplementation "org.koin:koin-test:2.1.5"
```

Any ideas?

**Comment by arttttt** [comment]
try to do it with this

**Comment by frist008** [comment]
> try to do it with this
> 
> https://mockk.io/

I don't understand what I should mock at in order to verify the correct injection of koin.

**Comment by frist008** [comment]
I found another solution. This issue can be closed.

```kotlin
@RunWith(RobolectricTestRunner::class)
@Config(manifest = Config.NONE, sdk = [Build.VERSION_CODES.P])
@Category(CheckModuleTest::class)
class KoinModuleTest {

    @Test
    fun koinModulesTest() {
        checkModules {
            val activity = mockk<AppCompatActivity>(relaxed = true)

            KoinContextHandler.register(GlobalContext().apply { setup(this@checkModules) })

            androidLogger(Level.DEBUG)
            modules(
                module {
                    single { ApplicationProvider.getApplicationContext<Context>() }
                    single { activity }
                },
                executionModule,
                activitiesModule
            )
        }
    }

}
```
