### ISSUE TITLE
Create a SharedviewModel with Parameters not working

### ISSUE THREAD

**Issue by thilahavanan** [InsertKoinIO/koin#827]
**Describe the bug**
I have FragmentA and BottomSheetFragment both fragment need to share the same viewModel.
in FragmentA I am creating instance of viewModel as below

**Approach A**
`viewModel = getSharedViewModel<FragmentAViewModel>{parametersOf("id")}`

- Same viewModel Instance is getting ,viewModel instance not changing based on parameter values.

**Approach B**
`viewModel = getViewModel<FragmentAViewModel>{parametersOf("id")}`
`val viewModel:FragmentAViewModel by inject/viewModel/sharedViewModel {parametersOf("id")}`

- ViewModel instances creating based on parameters - No issue with this.

But When using the same viewModel instance in BottomSheetFragment as below
**For Approach A**
`viewModel = getViewModel<FragmentAViewModel>()`
`viewModel = getSharedViewModel<FragmentAViewModel>()`
`viewModel = getSharedViewModel<FragmentAViewModel>({parentFragment})`

- Expecting non null parameters definitions while accessing viewModel 

**Expected behavior**
I need to use same viewModel instance in BottomSheetFragment and ViewModel should be dynamic based on input parameters .
**Koin project used and used version (please complete the following information):**
 `koin-core version 2.0.1`

**Additional moduleDefinition**
`viewModel(override=true) { (id:String)->
               FragmentAViewModel(
              id,get(),get() )
}`

**Comment by YonatanSegura97** [comment]
I have the same problem :c

**Comment by ildar2** [comment]
@arnaudgiuliani are there any updates on this?
I've tried this:
```
    private val viewModel: MyViewModel by sharedViewModel(
        owner = { from(requireParentFragment()) }
    )
```
but still got 
`Caused by: org.koin.core.error.NoParameterFoundException: Can't get injected parameter #0 from DefinitionParameters[] for type 'java.lang.Integer'`
version 2.2.0-rc-4
