### ISSUE TITLE
sharedViewModel inside fragment causes a crash

### ISSUE THREAD

**Issue by tkintonis** [InsertKoinIO/koin#828]
**Describe the bug**
I'm using two seperate fragments.In the first one i create a viewmodel 

   ```private val viewModel: ProfileViewModel by stateViewModel(qualifier = named("sharedProfileVM")) ```

Inside the second fragment (childfragment of the mentioned one) i inject a sharedViewModel
``` private val viewModel: ProfileViewModel by sharedViewModel(qualifier = named("sharedProfileVM")) ```

and this is my module declaration 
``` private val profileModule = module {
        viewModel (qualifier = named("sharedProfileVM")) { (state: SavedStateHandle) -> ProfileViewModel(state) }
    } ```

**To Reproduce**
Steps to reproduce the behavior:
1. Go to the first fragment 
2. Launch the second fragment

**Expected behavior**
Get a sharedViewModel in the second fragment.

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core version 2.1.5`

Stack trace definition :
E/[Koin]: Instance creation error : could not create instance for [Factory:'...ProfileViewModel',qualifier:sharedProfileVM]: org.koin.core.error.NoParameterFoundException: Can't get parameter value #0 from org.koin.core.parameter.DefinitionParameters@759ac75

**Comment by arnaudgiuliani** [comment]
seems that you need to pass parameters injection. You are using a StateViewModel, then prefer to opt for `saveStateViewModel` API for now. 2.2.0 will bring better API.
