### ISSUE TITLE
"Disable property type cast" should be marked as breaking

### ISSUE THREAD

**Issue by Pitel** [InsertKoinIO/koin#831]
This change forced me to change couple of things in my code. So this should be marked as `[BREAKING]` in changelog. Even in the linked pull request, the author says it's breaking change.

Also, according to semantic version (which I'm not sure you use) any braking chage should cause major version increase (so, Koin 3.0.0).

I know, it has happened, but please be carefulk next time. :+1:

**Comment by arnaudgiuliani** [comment]
Agree with you, it's more a breaking one. as 2.1.6 was intended to bring mostly fixes on current API. Really sorry.

I can revert this contribution to cherry pick it in 2.2.x. 3.0.x is the branch for Koin MP. I'm waiting more stable things around MP world to make it the main branch.

**Comment by Pitel** [comment]
I would prefer to keep it as it is. Damage was done, and reverting it would cause only more.

**Comment by arnaudgiuliani** [comment]
sorry

**Comment by arnaudgiuliani** [comment]
thanks for the feedback 👍
