### ISSUE TITLE
Access in a multimodule project

### ISSUE THREAD

**Issue by TheReprator** [InsertKoinIO/koin#835]
Hi thanks for this easy framework, 
I want to injection in module itself in a multimodule project rather than doing it a application level or single module i.e.

1) App module()
val mod = module

2)Activity module
val activityModule = module{}

3)Fragment Module
val fragment = module{}

where 3 can access 2, 1

**Comment by nikhil-thakkar** [comment]
@TheReprator If I understand your question correctly, you need to use `loadKoinModules` from [here](https://doc.insert-koin.io/#/koin-core/start-koin?id=loading-modules-after-startkoin). All the dependencies which are injected in `GlobalContext` would be available across the board. 
I hope this answers your question.

**Comment by TheReprator** [comment]
@nikhil-thakkar Thanks for the response buddy, but i want to restrict the access to a scope rather than declaring everything in a global context

**Comment by nikhil-thakkar** [comment]
@TheReprator Ahh!! That means you need scope linking. This is relatively a new feature. Here is some [doc](https://doc.insert-koin.io/#/koin-core/scopes?id=scope-linking-210) that could help you. But mind well it has been tested in the wild.

**Comment by TheReprator** [comment]
@nikhil-thakkar , i mean to say, every module is a library don't have knowledge of each other, So, i want to know, how can load modules in respective modules, i don't want a god module encapsulator like application or activity.
