### ISSUE TITLE
add preScopeClose to ScopeCallback

### ISSUE THREAD

**Issue by Swordsman-Inaction** [InsertKoinIO/koin#840]
**Is your feature request related to a problem? Please describe.**
I'd like to do some cleanup job before a scope is closed, but existing `onScopeClose` is called after the scope is closed.

**Describe the solution you'd like**
Add `preScopeClose` to `ScopeCallback` which will be called before scope is closed.

**Describe alternatives you've considered**
Just call `onScopeClose` before `_closed` is set to `true` in `clear()`. 

**Target Koin project**
All.

**Comment by naoyamakino** [comment]
+1
