### ISSUE TITLE
Koin Android Runtime crash

### ISSUE THREAD

**Issue by rahulr4** [InsertKoinIO/koin#854]
Koin-Android  is crashing at runtme because I forgot to add a dependency in the module.
Is there any way to detect this at compile time ?

**Comment by sergeyfitis** [comment]
@rahulr4 Probably this could help you https://start.insert-koin.io/#/quickstart/junit-test?id=verifying-modules

**Comment by rahulr4** [comment]
@sergeyfitis I have added this unit test but if i remove any dependency from any module, it still passes so this test case always PASSES

**Comment by sergeyfitis** [comment]
Have you set up correctly Koin Gradle plugin?
