### ISSUE TITLE
Incorrect synchronization in SingleInstanceFactory

### ISSUE THREAD

**Issue by KidNox** [InsertKoinIO/koin#861]
In some rare cases koin returns multiple instances of an object defined as single.

Simplified code from our android app:

    class MustBeSingleton

    startKoin {
        modules(
            module { single { MustBeSingleton() } }
        )
    }

    fun calledFromThread1() {
        val instance1: MustBeSingleton = get()
    }

    fun calledFromThread2() {
        val instance2: MustBeSingleton = get()
    }

So basically, instance1 may be unequal to instance2, I observe this behaviour in production.

Further investigation of koin internals led to SingleInstanceFactory, where writes to "value" field non-synchronized.

I wrote test that consistently reproduce this issue on my system (MBP 2019 i9), but due to multithreading-related things for other systems it may be tweaked.
Fix for this issue also provided.
https://github.com/KidNox/koin/commit/c9f29e0f34087cf801d747d91b8c2cc2c0e670cb

**Comment by arnaudgiuliani** [comment]
Fixed in 2.2.0 👍
