### ISSUE TITLE
koin-android-viewmodel depends on legacy support libraries

### ISSUE THREAD

**Issue by outadoc** [InsertKoinIO/koin#870]
**Describe the bug**
Checking if I can disable Jetifier with [plnice/can-i-drop-jetifier](https://github.com/plnice/can-i-drop-jetifier), I get this:

```
========================================
Project foo-bar
========================================

Cannot drop Jetifier due to following external dependencies:

* org.koin:koin-android-viewmodel:2.1.6
  \-- android.arch.lifecycle:extensions:1.1.1
  \-- org.koin:koin-android-scope:2.1.6
   \-- com.android.support:appcompat-v7:28.0.0
  \-- org.koin:koin-android-scope:2.1.6
   \-- android.arch.lifecycle:common:1.1.1
```

**To Reproduce**
1. Install `canidropjetifier` plugin
2. Run `./gradlew -Pandroid.enableJetifier=false canIDropJetifier` on a project that depends on `koin-android-viewmodel`
3. See error

**Expected behavior**
`koin` should only depend on Jetpack `androidx` libraries, if possible, allowing me to drop `jetifier` and gaining some build speed.

**Koin project used and used version (please complete the following information):**
`koin-android-viewmodel:2.1.6`

**Comment by egorikftp** [comment]
Please use koin-androidx-viewmodel

**Comment by outadoc** [comment]
Thank you 🙏 Didn't notice the androidx version, my mistake!
