### ISSUE TITLE
Koin multiplatform with kotlin plugin 1.4.0

### ISSUE THREAD

**Issue by pucherd** [InsertKoinIO/koin#874]
Hello, are you guys planning to release koin multiplatform which will be compiled with kotlin 1.4.0?
Current version 3.0.0-alpha-2 cannot be build in Xcode:
`Skipping ".gradle/caches/modules-2/files-2.1/org.koin/koin-core-iosx64/3.0.0-alpha-2/ca908dfd3d4856a982ee1244cace9426f45e42ca/koin-core.klib" as it is a pre 1.4 library`

**Comment by rio258k** [comment]
I'm also running into this issue.

**Comment by nachtien** [comment]
See the PR here: https://github.com/InsertKoinIO/koin/commit/a36bd56e21f07d7160e33c211816209504537d6b

**Comment by ge-org** [comment]
Touchlab is hosting a version containing the fix.
Take a look at the [KaMPKit](https://github.com/touchlab/KaMPKit) build files to see how to use it.
