### ISSUE TITLE
Singleton wasn't finalized if it was created as `by inject` in Android

### ISSUE THREAD

**Issue by aliaksandr-chaulytka** [InsertKoinIO/koin#882]
**To Reproduce**
1. startKoin()
2. Start new activity 
3. Init singleton as `by inject`
4. Destroy activity (finish)
5. Call stopKoin() 
6. Singleton wasn't finalized (see code example1 below)

(Note: Singleton will finalized if will do again step 1,2,3 )

**Expected behavior**
Singleton must finalize

**Koin project used and used version (please complete the following information):**
implementation("org.koin:koin-android:2.1.5")
implementation("org.koin:koin-android-scope:2.1.5")
implementation("org.koin:koin-androidx-viewmodel:2.1.5")
implementation("org.koin:koin-core:2.1.5")

**Code example1:**
```
class DataInteractor {
    
    val data = "Some data"

    init {
        Logger.w("${this.hashCode()}")
    }

    protected fun finalize() {
        Logger.w("${this.hashCode()}")
    }
}

class TestActivity : AppCompatActivity() {

    private val dataInteractor by inject<DataInteractor>()

    override fun onCreate(savedInstanceState: Bundle?) {    
        ...
        
    
        // initialization DataInteractor
        dataInteractor.data
    }
    
    ...
}

Logs:
W/TestActivity start
W/(DataInteractor.kt.18) <init>: 94060940
W/TestActivity onDestroy
W/MainActivity stopKoin
```

**Another example that works well:**
```
class TestActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {    
        ...
        
    
        // initialization DataInteractor
        get<DataInteractor>().data
    }
    
    ...
}

Logs:
W/TestActivity start
W/(DataInteractor.kt.18) <init>: 591051784
W/TestActivity onDestroy
W/MainActivity stopKoin
W/(DataInteractor.kt:22) finalize: 591051784
```

**Comment by arnaudgiuliani** [comment]
Single is kept with the main Application scope. It will be destroyed with the end of your main process. Use Factory instead of Single.

**Comment by aliaksandr-chaulytka** [comment]
> Single is kept with the main Application scope. It will be destroyed with the end of your main process. Use Factory instead of Single.

Thanks for answer but why `Single` was destroyed if it was declared with `get<...>` (Another example)
Could you explain this?
