### ISSUE TITLE
How should I create a variable that allows null？

### ISSUE THREAD

**Issue by kdsrsl** [InsertKoinIO/koin#892]
I have a variable defined as follows：
```
var answerTarget: IAnswerTarget? = null
```
use:
```
answerTarget?.start()
```
When answerTarget is null, start() is not executed. In line with expectations✅. 

-----

But when I use koin,
```
val answerTarget: IAnswerTarget? by inject()
```
use:
```
answerTarget?.start()
```

when I defined module
```
single<IAnswerTarget> { AnswerTargetImpl() }
```
start() is ok.

when i don't define module：

start() crash, throw exception:
```
org.koin.core.error.NoBeanDefFoundException: No definition found for class:'xxx.IAnswerTarget'. Check your definitions!
```
----

At this point, I want to allow answerTarget to be null without crashing.

Does koin support this?

Thx.

**Comment by madroidmaq** [comment]
You can use the following methods:

```kotlin
val answerTarget: IAnswerTarget? by getKoin().injectOrNull()
```

At the same time, in order to simplify this process, I submitted a PR(#902) for more convenient use:

```kotlin
val answerTarget: IAnswerTarget? by injectOrNull()
```

**Comment by senRsl** [comment]
> You can use the following methods:
> 
> ```kotlin
> val answerTarget: IAnswerTarget? by getKoin().injectOrNull()
> ```
> 
> At the same time, in order to simplify this process, I submitted a PR(#902) for more convenient use:
> 
> ```kotlin
> val answerTarget: IAnswerTarget? by injectOrNull()
> ```

This doesn't solve my problem.
