### ISSUE TITLE
Koin crashes when i build the release apk

### ISSUE THREAD

**Issue by james04gr** [InsertKoinIO/koin#897]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core version 0.9.2`

**Additional moduleDefinition**
Add any other moduleDefinition about the problem here.

I am not sure if this is the right place to put it down however i am facing a problem that i cannot understand and struggling many days now.

I have built my project using koin v2.1.6 which in debug mode runs perfect. When i try to build the release variant (WITHOUT PROGUARD) then the first component that i want to create throws an exception.

The problem is when i try to create my network manager which ends up in the okhttp3.OkHttpClient provide.
```
val networkModule = module {
single {
        val loggingInterceptor = get<Interceptor?>()
        val httpClientBuilder = OkHttpClient().newBuilder().apply {
            connectTimeout(60, TimeUnit.SECONDS)
            readTimeout(60, TimeUnit.SECONDS)
            writeTimeout(60, TimeUnit.SECONDS)
            addInterceptor(get<HeaderInterceptor>())
            loggingInterceptor?.let {
                addInterceptor(loggingInterceptor)
            }
        }

        return@single httpClientBuilder.build()
    }
...
}
```

That is where the app crashes. I dont have any explanation for that issue. Please tell me what do you need me to post so i can figure it out!
Thank you

**Comment by james04gr** [comment]
The problem solver. It seems that Koin is not able to return a null instance on a single component. In my case LogginInterceptor is null when BuildConfig == Release.

**Comment by mochadwi** [comment]
did you use `getOrNull<LoggingInterceptors?>()` for the workaround instead of `get<LoggingInterceptors?>()`?

**Comment by james04gr** [comment]
Yes. That was the problem. Thank you very much!
