### ISSUE TITLE
How should I inject viewmodel in a cutomView just like in an Activity or Fragment by viewmodels?

### ISSUE THREAD

**Issue by WinWang** [InsertKoinIO/koin#899]
How should I inject viewmodel in a cutomView just like in an Activity or Fragment by viewmodels? I want to get  a viewmodel in a customView  so that i can write my logic lonely,I put my view into Activity and there is no more link with Activity

**Comment by egorikftp** [comment]
It looks very strange.
Where have you found this recommendation?

**Comment by WinWang** [comment]
No，I have this idea because the logic of my activity page may be very complex. Each function module is made into an independent custom view with its own independent network request. Therefore, it may be necessary to have a ViewModel so that it can be completely decoupled from the activity
