### ISSUE TITLE
[Perf] Scope linkScope 

### ISSUE THREAD

**Issue by chuyun923** [InsertKoinIO/koin#906]
A ----> B means "Scope A linkTo ScopeB"。

There is such a scene：
A ----> B ----> RootScope
A ----> C ----> RootScope
A ----> D ----> RootScope

if a instance define in ScopeD，inject instance:  
- RootScope will invoke resolveInstance() **three times**

A ----> B ----> C -----> D ----->RootScope
Same as above

**Comment by arnaudgiuliani** [comment]
Resolution is indexed. No worry about perf here. Apart if you need another memory mechanism.
