### ISSUE TITLE
State on Koin 3.0

### ISSUE THREAD

**Issue by slipdef** [InsertKoinIO/koin#910]
Last version of Koin 3.0 is still marked as alpha. Alpha is not safe for production use, everyone knows it. However it's already a year or even more since Koin doesn't have official Kotlin Native support that I decided to ask if this alpa is somehow eligible for production use?

**Comment by arnaudgiuliani** [comment]
The Koin 3.0 alpha is also used by Touchlab in their kamp kit and some projects around are using it. We need also people to help test it and help see any problem with that. 

we need to take care about incoming new memory model from jetbrains, on the native side.

It's still in alpha, as it has to be merged with 2.2.x branch once this one has been released. The 2 branches will converged in the next weeks.

**Comment by slipdef** [comment]
Thanks!
