### ISSUE TITLE
Check if instantiated

### ISSUE THREAD

**Issue by Pitel** [InsertKoinIO/koin#912]
**Is your feature request related to a problem? Please describe.**
I have class, and it's instantiating has side effects and it is also `Closeable`. So I need to write a check if it's instantiated, and if it is, close it.

**Describe the solution you'd like**
```kotlin
Scope.isInstantiated()
```

**Describe alternatives you've considered**
I used to have this code, but it stopped working with 2.2.0-beta2, because `_instanceRegistry` became `internal`. (I understand the change and I agree with it, but I need to have the requested functionality.)
```kotlin
if (scope._instanceRegistry.instances[indexKey(
        Deferred::class,
        STREAMER
    )]?.isCreated() == true
) {
    scope.get<Deferred<WebRTCStreamer>>(STREAMER).await().close()
}
```

Now I'll probably have to use reflection.

**Target Koin project**
Core/Scope

**Comment by pramodshri-tgsys** [comment]
I have a need for this too. On Android, we instantiate an instance of MediaPlayer when a Media is played (audio or video). When the application terminates, we need to release the player resources. We need to release it **only if** the MediaPlayer is instantiated. There is no way to check if it is instantiated or not.
