### ISSUE TITLE
GetOrNull covers possibly important exceptions

### ISSUE THREAD

**Issue by hrach** [InsertKoinIO/koin#913]
**Describe the bug**

This already happended to us twice. This time we had to release production build with more debugging to realize what is actually happening, because the current stack trace is not sufficient for us. 

The root cause is implementation of getOrNull and findInOtherScope where getOrNull silences all possible exceptions.

**To Reproduce**

1. Have a scope and MAIN dependency in it.
2. The MAIN dependency requires ANOTHER dependency in root scope.
3. Constructor of the ANOTHER depency throws.

**Actual behavior**

```
Caused by org.koin.core.error.NoBeanDefFoundException
No definition found for class:'xxx.AnotherDependency'. Check your definitions!
```

**Expected behavior**

```
Caused by xxx.CustomException
```

**How to fix**

Catch only NoBeanDefFoundException exceptions in getOrNull.

This may introduce BC break since somebody may rely on this behaviour. So alternatively also findInOtherScope should be reworked not to utilize getOrNull.

**Koin project used and used version (please complete the following information):**

```
implementation "org.koin:koin-core:v2.1.5"
implementation "org.koin:koin-android:v2.1.5"
implementation "org.koin:koin-androidx-scope:v2.1.5"
implementation "org.koin:koin-androidx-viewmodel:v2.1.5"
implementation "org.koin:koin-androidx-fragment:v2.1.5"
implementation "org.koin:koin-androidx-ext:v2.1.5"
```

**Comment by arnaudgiuliani** [comment]
Thanks, fix added to 2.2.0 branch

**Comment by hrach** [comment]
Thanks you! Could you please point me to the fix? I can't find it.

**Comment by hrach** [comment]
@arnaudgiuliani Could you please point me to the fix? Thanks :)

**Comment by arnaudgiuliani** [comment]
here you have the fix: https://github.com/InsertKoinIO/koin/blob/master/koin-projects/koin-core/src/main/kotlin/org/koin/core/scope/Scope.kt#L164

**Comment by hrach** [comment]
❤️ 👍 thanks
