### ISSUE TITLE
Dependency cycles are hard to find/debug

### ISSUE THREAD

**Issue by roschlau** [InsertKoinIO/koin#918]
I just did a rather large refactoring, and in the process of that accidentally introduced a few dependency cycles. Most were trivial (A -> B -> A), but one was a bit more involved (A -> B -> C -> A).

Now, of course cyclical dependencies can't work like this so I had to fix them, but Koin makes it really hard to actually find the specific cycles - it just crashes with a StackOverflowException, whose stacktrace doesn't contain any lines that give me a hint towards what classes are causing the problem.

It would be great if Koin would detect such cycles when it tries to resolve a dependency that is already being resolved right now further up in the tree, and output a corresponding error message that helps me pinpoint at least one of the classes involved in the cycle.

I might also be missing something here that actually makes this easier to debug already, if so, pointers are appreciated.

**Comment by wujek-srujek** [comment]
I just got caught by this and it took me ages to learn that it was a cycle (I didn't get a StackOverflowException).
