### ISSUE TITLE
Compose lazy viewModel initialisation fails

### ISSUE THREAD

**Issue by nrobi144** [InsertKoinIO/koin#919]
**Describe the bug**
Using `by viewModel()` inside a composable fails with the following exception:
`Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'java.lang.Object'. Check your definitions!`

`getViewModel()` works as expected

**Koin project used and used version:**
`koin-core 2.2.0-rc-2`
`koin-android 2.2.0-rc-2`
`koin-android-viewmodel 2.2.0-rc-2`
`koin-androidx-compose 2.2.0-rc-2`

`kotlin 1.4.10`

**EDIT:** Here's the relevant koin module setup:

```
@Composable
fun HomeScreen() {
    val viewModel  by viewModel<HomeViewModel>()
```

```
@OptIn(ExperimentalCoroutinesApi::class)
class HomeViewModel internal constructor(
    private val getCategories: GetCategoriesUseCase,
    private val fetchCategories: FetchCategoriesUseCase
) : CoroutineViewModel() {
```

```
val viewModelModule = module {
    viewModel { HomeViewModel(get(), get()) }
    ....
}
```

```
private fun getApiModule(context: Context) = module {
    factory { CategoryApi() }
    single { DatabaseFactory.getInstance(context).create() }
}

private fun getRepositoryModule() = module {
    factory { CategoryLocalSource(get()) }
    factory { CategoryRemoteSource(get()) }
    single { CategoryRepository(get(), get()) }
}

private fun getUseCaseModule() = module {
    factory { GetCategoriesUseCase(get()) }
    factory { FetchCategoriesUseCase(get()) }
}
```

**Comment by arnaudgiuliani** [comment]
Can you add more code snippet please?

**Comment by nrobi144** [comment]
@arnaudgiuliani just edited the description

**Comment by arnaudgiuliani** [comment]
I will check if the lazy delegate is really usable here 🤔

**Comment by arnaudgiuliani** [comment]
For now, we need to avoid Lazy delegate in remember block. We need to wait a bit to let the Compose internal design stabilise.

I propose to remove for now `inject` & `viewModel` from koin-androidx-compose extensions
