### ISSUE TITLE
Could not find org.koin:koin-core-jvm:3.0.0-alpha-4

### ISSUE THREAD

**Issue by petarmarijanovicfive** [InsertKoinIO/koin#923]
**Describe the bug**
I want to set up Koin as my DI library for my Kotlin Multiplatform project. After I add the dependencies I can't build the project and the error is `Could not find org.koin:koin-core-jvm:3.0.0-alpha-4`

**Steps To Reproduce:**
1. Configure the project by following https://doc.insert-koin.io/#/setup/koin_mp
2. Sync gradle
3. Build project

**Expected behavior**
Ability to build the project and use Koin in shared, Android and iOS codebases.

**Koin project used and used version:** `koin-core 3.0.0-alpha-4`

**Additional moduleDefinition**
Here is my root `build.gradle.kts` buildscript

```
    repositories {
        gradlePluginPortal()
        jcenter()
        google()
        mavenCentral()

        maven(url = "https://dl.bintray.com/ekito/koin")
    }
```

And I added the dependency in `commonMain` sourceSets for the shared module I have
`implementation("org.koin:koin-core:3.0.0-alpha-4")`

While trying to build the project I get
```
Execution failed for task ':androidApp:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':androidApp:debugRuntimeClasspath'.
   > Could not find org.koin:koin-core-jvm:3.0.0-alpha-4.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/org/koin/koin-core-jvm/3.0.0-alpha-4/koin-core-jvm-3.0.0-alpha-4.pom
       - https://dl.google.com/dl/android/maven2/org/koin/koin-core-jvm/3.0.0-alpha-4/koin-core-jvm-3.0.0-alpha-4.pom
       - https://jcenter.bintray.com/org/koin/koin-core-jvm/3.0.0-alpha-4/koin-core-jvm-3.0.0-alpha-4.pom
       - https://repo.maven.apache.org/maven2/org/koin/koin-core-jvm/3.0.0-alpha-4/koin-core-jvm-3.0.0-alpha-4.pom
     Required by:
         project :androidApp > project :shared > org.koin:koin-core:3.0.0-alpha-4

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

It looks to me like the `jvm` version of the library is not released, and also I don't understand why my `core` library depends on the `jvm` library. Am I doing something wrong?

**Comment by petarmarijanovicfive** [comment]
The issue was on my side, but in my defense, the https://doc.insert-koin.io/#/setup/koin_mp could have this information written in it 😄 

Long story short I added `maven(url = "https://dl.bintray.com/ekito/koin")` to `buildscript.repositories` but should've added it to `allprojects.repositories`.

Closing the issue.

**Comment by azurh** [comment]
I have this issue too.

Where exactly did you add the custom maven repository? 

I added `maven(url = "https://dl.bintray.com/ekito/koin")` in:
- top level `build.gradle.kts` in `buildscript.repositories` and in `repositories` blocks
- shared `build.gradle.kts` in the `repositories` block

I'm using the `3.0.0-alpha-4`.

And still I get:

```
Execution failed for task ':tbellAndroid:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':tbellAndroid:debugRuntimeClasspath'.
   > Could not find org.koin:koin-core-jvm:3.0.0-alpha-4.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/org/koin/koin-core-jvm/3.0.0-alpha-4/koin-core-jvm-3.0.0-alpha-4.pom
       - https://dl.google.com/dl/android/maven2/org/koin/koin-core-jvm/3.0.0-alpha-4/koin-core-jvm-3.0.0-alpha-4.pom
       - https://jcenter.bintray.com/org/koin/koin-core-jvm/3.0.0-alpha-4/koin-core-jvm-3.0.0-alpha-4.pom
       - https://repo.maven.apache.org/maven2/org/koin/koin-core-jvm/3.0.0-alpha-4/koin-core-jvm-3.0.0-alpha-4.pom
     Required by:
         project :tbellAndroid > project :shared > org.koin:koin-core:3.0.0-alpha-4

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by petarmarijanovicfive** [comment]
@azurh 

You need to put `maven(url = "https://dl.bintray.com/ekito/koin")` in `allProjects.repositories` in the top level `build.gradle.kts`
```
buildscript {
    repositories {
        gradlePluginPortal()
        jcenter()
        google()
        mavenCentral()
    }

    dependencies {
        classpath(kotlin("gradle-plugin", Versions.kotlin))
        classpath(kotlin("serialization", Versions.kotlin))

        classpath("com.android.tools.build:gradle:4.1.0")
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()

        maven(url = "https://dl.bintray.com/ekito/koin")
    }
}

repositories {
    mavenCentral()
}
```

**Comment by vlkam** [comment]
I've faced bizarre behavior.
If I add maven(url = "https://dl.bintray.com/ekito/koin") kmm's folders desappear (screenshots below)
What can be the cause of this behavior?



![2021-01-26_184819](https://user-images.githubusercontent.com/7336057/105868543-55799100-6007-11eb-8df5-9e438ab8faa0.png)
![2021-01-26_184945](https://user-images.githubusercontent.com/7336057/105868546-56122780-6007-11eb-92fe-405fb3b24836.png)

**Comment by gchristov** [comment]
For anyone landing on this issue from Google. I spent a few hours hunting this down as the workaround here wasn't working. I finally noticed that the `groupId` of the dependency has changed to `io.insert-koin` from `org.koin`. 

My working KMM setup is now as follows:
```
val commonMain by getting {
    implementation("io.insert-koin:koin-core:3.1.2")
}
```

and there is no need for `maven(url = "https://dl.bintray.com/ekito/koin")`

**Comment by ManInTheBit** [comment]
@gchristov it worked for my issue. Thank you.
