### ISSUE TITLE
Release 2.2.0

### ISSUE THREAD

**Issue by Shusshu** [InsertKoinIO/koin#928]
Could you release 2.2.0 ? only rc-3 is available.

Thanks!

**Comment by arnaudgiuliani** [comment]
Preparing doc, website, cleaning last thing. 

Last Jetpack compose PR for alpha05 is ready

**Comment by anhanh11001** [comment]
@arnaudgiuliani it's still rc-4 now. Do you have an estimate on when would Koin release the stable version?
