### ISSUE TITLE
Koin 2.1: Nested scopes with lifecycleScope

### ISSUE THREAD

**Issue by Mbt925** [InsertKoinIO/koin#930]
I have a custom user_scope and I like to inject some objects from this scope to a ViewModel which is also scoped to a fragment.

```
Class A
Class B
ViewModel VM1(val a: A, val b: B)

module {
    single { A() }
    scope(named("user_scope")) {
        scoped { B() }
        scope<ParentFragment> {
            viewModel { VM1(get(), get()) }
        }
    }
}
```
I have multiple child fragments with their respective VMs. All these fragments are inside a parent fragment, so I like to scope the VMs to this parent fragment's lifecycle. Writing this in a child fragment doesn't work:

`getKoin().getScope("user_scope").getKoin().getScope(parentFragment.lifecycleScope.id).viewModel<VM1>()`

What am I doing wrong?

**Comment by arnaudgiuliani** [comment]
Inner scope are not designed to be written like that. For now, try to use `linkTo` on a scope instance to make it resolve other scope instances.
