### ISSUE TITLE
Injecting mock viewmodels into koin.

### ISSUE THREAD

**Issue by SamCosta1** [InsertKoinIO/koin#936]
**Describe the bug**
Upon using Koin to inject a mocked out ViewModel (Using mockito), on Koin version `2.2.0-rc-3` this causes a crash.

I believe it might be similar to this issue: https://issuetracker.google.com/issues/122273087.

The changes made in this Koin version lead to the `create` method of `AbstractSavedStateViewModelFactory` when attempting to access the `ViewModel` from a Fragment. In turn this leads to `setTagIfAbsent` being called on the mocked `ViewModel` object which is not supported by Android.

I appreciate it might be better to raise a bug with Google regarding the issue in the `ViewModel` class, but given I found this issue by upgrading Koin, I thought I'd mention it here.

**Comment by agustinsivoplas** [comment]
I have the same issue, I am using koin `2.2.0-rc-4.`

**Comment by NicholasTempleton** [comment]
Same here when using `2.2.0`. I'm sticking with Koin `2.1.6` for now, maybe it'll get fixed in `androidx.lifecycle:lifecycle-viewmodel` someday?

**Comment by morganbovi** [comment]
I am seeing the same issue with `setTagIfAbsent` being called. In my case I see a `Null reference used for synchronization`. Specifying `by viewModel(mode = LazyThreadSafetyMode.SYNCHRONIZED)` seems to resolve that issue.

What I find interesting is that the mode does have this default. If I do not specify a mode it uses a different version of the 
`viewModel` method that does not make use of the new `mode` variable.

**Comment by maruiz81** [comment]
I had the same problem ``` java.lang.NullPointerException: Cannot enter synchronized block because "this.mBagOfTags" is null``` but I have fixed it downgrading the version to 2.1.6.

**Comment by agustinsivoplas** [comment]
Any update on this? Do we have a solution for this?

**Comment by petarmarijanovicfive** [comment]
Yes, it would be great if we can provide Mockito mocks of ViewModels as dependencies.

**Comment by sarn0ld** [comment]
The same happens with Koin+Mockk+sharedViewModel(). 
Is there any solution?
Why is this issue closed?

**Comment by stephandrab** [comment]
FYI: For me this also happens with with Hilt + Mockito + a java `ViewModelProvider`. According to [this stackoverflow post](https://stackoverflow.com/questions/68351244/android-test-fragmen-with-mock-viewmodel-using-hilt), there are two workarounds: a reflection hack, or using relaxed mocks `mockk(relaxed = true)`.
