### ISSUE TITLE
Cannot create fragment with Koin inject in BG Thread

### ISSUE THREAD

**Issue by Sirelon** [InsertKoinIO/koin#937]
Hi. 
With new Koin version 2.2.0-rc-03 I face with a crash when try to create fragment in Background thread

```
java.lang.IllegalStateException: Method addObserver must be called on the main thread
        at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:172)
        at androidx.fragment.app.Fragment.initLifecycle(Fragment.java:496)
        at androidx.fragment.app.Fragment.<init>(Fragment.java:476)

```
TO reproduce: we need fragment class with some injection ( by inject() ) and than try to create it **not** in Main thread. 

It's not a big deal to create fragments in Main thread, but in big legacy project.. so, you know. 

I will be glad, if you handle it inside library :) Thanks!

**Comment by arnaudgiuliani** [comment]
Do you have different behavior we previous Koin version?
Can you do the same, without Koin? To test if it's coming from Fragment library.

**Comment by Sirelon** [comment]
Yes, you're right.. It's from Fragment Library, not from Koin. Sorry, for bother you with this.

**Comment by laalto** [comment]
I believe this is still related to koin. Getting a number of similar issues after updating to koin 2.2.0, and analyzing the dependencies graph it seems that koin libraries are bringing in beta versions of androidx dependencies that have the behavior change that causes this issue.

For example, koin-androidx-scope seems to depend on androidx.activity:activity:1.2.0-beta01 that has androidx.lifecycle:lifecycle-runtime:2.3.0-beta01 as its transitive dependency.

I don't think a stable release should have beta dependencies, at least not without big red warning signs on top.

Reverting back to koin 2.1.6 to fix the issue. Migrating app and test code to not instantiate fragment on background thread later if a stable version of androidx.lifecycle still requires it.
