### ISSUE TITLE
Alpha version of Android Gradle Plugin is used in 2.2.0-rc-3

### ISSUE THREAD

**Issue by misa** [InsertKoinIO/koin#938]
**Describe the bug**
Alpha version of Android Gradle Plugin should not be used for production version of Koin. This can possibly stop us from upgrading to this version. Koin library is already blocking upgrade to Kotlin 1.4.x and this could mean another extra delay.

**Expected behavior**
Stable version of Android Gradle Plugin should be used. Eg. **4.1.0**

**Koin project used and used version (please complete the following information):**
android_gradle_version = "4.2.0-alpha13"

**Comment by arnaudgiuliani** [comment]
Why AGP version is it affecting your project? this is used for Jetpack Compose.

I can import last rc with regular android project.
