### ISSUE TITLE
`ViewModelParameter.initialState` needs default and could be nullable

### ISSUE THREAD

**Issue by erikhuizinga** [InsertKoinIO/koin#943]
This line

https://github.com/InsertKoinIO/koin/blob/f2fb60bd7ff3719681855a5818d975e0107d3f72/koin-projects/koin-androidx-viewmodel/src/main/java/org/koin/androidx/viewmodel/ViewModelParameter.kt#L14

is only used here:

https://github.com/InsertKoinIO/koin/blob/f2fb60bd7ff3719681855a5818d975e0107d3f72/koin-projects/koin-androidx-viewmodel/src/main/java/org/koin/androidx/viewmodel/factory/StateViewModelFactory.kt#L18

It is used in `AbstractSavedStateViewModelFactory`, that accepts a _nullable_ `Bundle`. However, `ViewModelParameter` doesn't accept a nullable bundle. Furthermore, because this `initialState: Bundle` was added since v2.2.0-alpha-1 (in https://github.com/InsertKoinIO/koin/commit/584334fc7f2cc3f8c806b91dc9afb784fb6e2960), that is an API change. It isn't documented in the changelog, but it is also not necessary: the property could be nullable and be `null` by default!

Please consider making the property nullable and adding a `null` default. Otherwise clearly document its use and why a `Bundle` _must_ be provided.

**Comment by arnaudgiuliani** [comment]
Hi @erickok 

> Please consider making the property nullable and adding a null default. Otherwise clearly document its use and why a Bundle must be provided.

The strategy is to come more close to the default android `viewModels()` delegate. We use the `AbstractSavedStateViewModelFactory` by default then.
