### ISSUE TITLE
org.koin.androidx.viewmodel.compat.SharedViewModelCompat.sharedViewModel is not resolving after upgrade to 2.2.0-rc4

### ISSUE THREAD

**Issue by a-v-k** [InsertKoinIO/koin#944]
**Describe the bug**
after upgrade to 2.2.0-rc4 compiler can't found the
org.koin.androidx.viewmodel.compat.SharedViewModelCompat.sharedViewModel 

**To Reproduce**

1. use koin 2.1.6
2. use 
org.koin.androidx.viewmodel.compat.SharedViewModelCompat.sharedViewModel in your Java class
3. update koin to 2.2.0-rc4
4. See error - app will not compile anymore

**Expected behavior**
application compiles with koin 2.2.0-rc4

**Koin project used and used version (please complete the following information):**
 [e.g]: 2.2.0-rc4 + Java Fragment (trying to create sharedViewModel from Fragment written in Java)

**Comment by arnaudgiuliani** [comment]
Yep, fixed back in 2.2.0 👍

**Comment by a-v-k** [comment]
Confirmed, thanks!
