### ISSUE TITLE
How to use Scope feature 2.2.0 in DialogFragment?

### ISSUE THREAD

**Issue by egorikftp** [InsertKoinIO/koin#951]
Previously we are able to inject dependencies with following way.

1. We create scope for DialogFragment
![image](https://user-images.githubusercontent.com/16294951/99069037-a3f9c080-25be-11eb-9bed-a9b101aeba41.png)

2. Inject scoped dependencies
![image](https://user-images.githubusercontent.com/16294951/99041772-98959d80-259c-11eb-80de-3a53ca8b8a53.png)

How to achieve the same behaviour with the new library version?

**Comment by arnaudgiuliani** [comment]
use the `KoinScopeComponent`: 

https://doc.insert-koin.io/#/koin-core/scopes?id=scope-component-associate-a-scope-to-a-component-220

**Comment by egorikftp** [comment]
Worked solution is 

```kotlin
abstract class ScopeDialogFragment : AppCompatDialogFragment(), KoinScopeComponent {

    override val scope: Scope by lazy { newScope(this) }

    override fun onDestroy() {
        closeScope()
        super.onDestroy()
    }
```

```kotlin
class ThemeSettingDialogFragment : ScopeDialogFragment() {

    private val viewModel: ThemeViewModel by inject()
    
    //Other code
}
```

As for me it looks not clear why for `viewModel` I should use `inject`? 

For example in ScopeFragment I'm able to use like this

```kotlin
val photoReportModule = module {

    scope<PhotoReportFragment> {
        scoped { PhotoReportRepository(firebase = get()) }
        scoped { PhotoReportUseCase(photoReportRepository = get()) }

        viewModel {
            PhotoReportViewModel(
                    photoReportUseCase = get(),
                    analytics = get()
            )
        }
    }
}
```

```kotlin

import org.koin.androidx.viewmodel.ext.android.viewModel

class PhotoReportFragment : ScopeFragment(R.layout.fragment_photo_report), PhotoReportsFeature {

    private val viewModel by viewModel<PhotoReportViewModel>()

    //other code
}
```

**Comment by MedveDomg** [comment]
@egorikftp I'm trying to use scoped viewmodel in **just** **regular** fragment, but get an error ` Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class`, but your solution with `inject` didn't produce any error, but main feature of `viewmodel` doesn't work.

**Comment by MedveDomg** [comment]
I fixed issue on my side by changing dependency of scope library (I was using **not** android x) and extends from ScopeActivity for launch my ScopeFragment. Thanks everybody.

**Comment by sebastienrouif** [comment]
@arnaudgiuliani  is there a plan to make a `ScopeDialogFragment` ?

**Comment by sebastienrouif** [comment]
actually, we are missing contentProviders and BroadcastReceivers too as they are application components too https://developer.android.com/guide/components/fundamentals#Components
I'm happy to help with the PR

**Comment by alessandroToninelli** [comment]
I have the same issue. With This components 

```kotlin

 scope<MainActivity> {
           scope<EditCartItemDialog> {
                    viewModel<EditCartItemViewModel>()
                  }
}

```

I  have to call **inject** instead of **viewModel** otherwise i have the error: ` org.koin.core.error.NoBeanDefFoundException: No definition found for class:'com.toninelli.ton_store.ui.main.cart.EditCartItemViewModel'. Check your definitions!`


```kotlin

class EditCartItemDialog(
) : BottomSheetDialogFragment(), KoinScopeComponent {

    override val scope: Scope by lazy { newScope() }

    private val model by inject<EditCartItemViewModel>()

```

**Comment by arnaudgiuliani** [comment]
@alessandroToninelli can you try to avoid inner scope definition. Is it better?

```kotlin
scope<MainActivity> {
           
}
scope<EditCartItemDialog> {
         viewModel<EditCartItemViewModel>()
}
```

**Comment by arnaudgiuliani** [comment]
if you use `inject` for ViewModel, it won't be wired to Android lfecycle factories

**Comment by alessandroToninelli** [comment]
avoiding inner scopes the issue persists, I have to use ` inject`  otherwise the app crashes with the same exception

 ` org.koin.core.error.NoBeanDefFoundException: No definition found for class:'com.toninelli.ton_store.ui.main.cart.EditCartItemViewModel'. Check your definitions!`

**Comment by gurgen-arustamyan** [comment]
@arnaudgiuliani is there a plan to make a ScopeDialogFragment, ScopeBottomSheetDialogFragment...?
