### ISSUE TITLE
Documentation incorrect example

### ISSUE THREAD

**Issue by WiMank** [InsertKoinIO/koin#952]
[Extended Scope API](https://start.insert-koin.io/#/getting-started/koin-for-android?id=extended-scope-api)

Incorrect code block:
```
module {
    // declare a scope for DetailActivity
    scope(named<DetailActivity>)**>** {
        scoped<DetailContract.Presenter> { DetailPresenter(get(), get()) }
    }
}
```
Excess symbol for closing diamond operator.  
Function invocation 'named<DetailActivity>()' expected.

**Comment by arnaudgiuliani** [comment]
fixed 👍
