### ISSUE TITLE
Unnecessary code

### ISSUE THREAD

**Issue by weikaiyun** [InsertKoinIO/koin#954]
![image](https://user-images.githubusercontent.com/20124328/99144310-c0215e80-269f-11eb-878f-ba41f6338d01.png)
Maybe the code in the red rectangle is Unnecessary.

**Comment by arnaudgiuliani** [comment]
Not at all. This is for injecting in graph

**Comment by weikaiyun** [comment]
> Not at all. This is for injecting in graph

got it
