### ISSUE TITLE
AutoScanPackage

### ISSUE THREAD

**Issue by iso88591** [InsertKoinIO/koin#956]
#### it's hard to use when i use like:
~~~
startKoin() {
            modules(
                    module { 
                         single {
                                User()
                        }
                         ...
                    }
                     ...
            )
}
~~~
### if i can use annotation to mark class like that
~~~
@KoinComponent
class User(
)
~~~
#### only config in startKoin  method
~~~
startKoin() {
            package = "com.package.xxx"
}
~~~
### then it can auto generate code at the stage of annotation processor whick is register my modules
 if target class has params  , Set the default by 'inject' or 'get'

### more:
i mark @KoinComponent to  kotlin top level method
- return type as the config type
- method params value by inject or 'parametersOf()'
- use @KoinQualifier to distinguish diffrent instance

### an Android studio plugin for koin that easy to find dependencies

It would be great if that could be done
thank you!!!

**Comment by arnaudgiuliani** [comment]
Yes, this kind of declaration is in study currently 👍

**Comment by jeziellago** [comment]
@iso88591 and @arnaudgiuliani 
Interesting that!
Any ideas about how to differ `single` and `factory`, `scope` declaration, dynamic module load and unload? 🤔

**Comment by arnaudgiuliani** [comment]
> Any ideas about how to differ single and factory, scope declaration, dynamic module load and unload? 🤔

I plan to write some Koin Internals article, would help understand the whole picture.
