### ISSUE TITLE
Documentation doesn't mention initializing properties anywhere

### ISSUE THREAD

**Issue by mataha** [InsertKoinIO/koin#961]
Even though reading properties [is explained](https://doc.insert-koin.io/#/koin-core/properties?id=read-property-from-a-module), initializing them is not.

It would be nice to have a snippet that does that (without referring to [unit tests](https://github.com/InsertKoinIO/koin/blob/master/koin-projects/koin-core/src/test/java/org/koin/dsl/FilePropertyDefinitionTest.kt)), e.g.:

```kt
startKoin {
    // Load properties from the default location
    // (i.e. `/src/main/resources/koin.properties`)
    fileProperties()

    // Load modules and other stuff...
}
```

(Koin Android documentation [actually mentions that](https://doc.insert-koin.io/#/koin-android/start?id=properties).)

**Comment by arnaudgiuliani** [comment]
Thanks for your feedback. It's fixed.
