### ISSUE TITLE
What is "functional resolution"?

### ISSUE THREAD

**Issue by jamesonwilliams** [InsertKoinIO/koin#966]
The `README.md` for this project [states that Koin is](https://github.com/InsertKoinIO/koin/blame/master/README.md#L7):

> Written in pure Kotlin, using functional resolution only: no proxy, no code generation, no reflection.

I have never heard of _functional resolution_, so I tried to look it up.

When I do a Google search for [`"functional resolution" Kotlin`](https://www.google.com/search?q=%22functional+resolution%22+kotiln), _every single result_ is a copy of the Koin project's slogan.

In fact, [when I _filter out_ search results mentioning Koin](https://www.google.com/search?q=%22functional%20resolution%22+kotlin+-koin), there are only 13 results on the Internet. All  are still clones of Koin's tagline, the results just don't not mention Koin by name.

___TLDR___, it seems like Koin has created the phrase _functional resolution_. Could you provide a definition or explanation of this phrase, somewhere? Perhaps in the README itself?

**Comment by stackunderflows** [comment]
@jamesonwilliams I am having this same problem. Have you figured out what they're talking about?

**Comment by jamesonwilliams** [comment]
@stackunderflows Nope, still don't know!

**Comment by stackunderflows** [comment]
Seems strange that @jamesonwilliams closed the issue without addressing the question. I was thinking of trying Koin out but I don't want to invest in a community that is not likely to help people when they're starting out.

**Comment by arnaudgiuliani** [comment]
Don't struggle too much with this "home made" expression about "functional resolution", as it's perhaps a bad translation 😅. But rather think of Koin as a runtime resolution that doesn't need introspection. In other technology stacks, you won't find lots of compile-time DI.

The main value of Koin was to propose simplicity of a Kotlin DSL to help you make your DI, and the power of Kotlin extensions to help you quickly hookup your DI where you need.

**Comment by stackunderflows** [comment]
After reading this article, it makes a lot more sense. It's not actually DI, it's a service locator. They probably don't advertise that because some people consider that an anti-pattern.

https://medium.com/modulotech/dependency-injection-and-service-locator-6144ed55a8e
