### ISSUE TITLE
How to inject a viewModel into a Jetpack Compose preview

### ISSUE THREAD

**Issue by ln-12** [InsertKoinIO/koin#969]
I wonder how I could inject a viewModel into a Jetpack Compose preview as I pass it to this screen from the activity. My code looks something like this:
```
@Preview(name = "Sign in preview")
@Composable
fun SignInPreview() {

   val myViewModel = ???

    MyTheme {
        SignIn(viewModel = myViewModel) {}
    }
}
```

How would I do that? In my activity I simply call `private val appViewModel: AppViewModel by viewModel()`, but this does not work here because I have no `ViewModelStoreOwner`.

**Comment by ln-12** [comment]
@arnaudgiuliani It's not really nice to close an issue without _any_ comment.

For anyone wondering: it seems to be the best working approach to separate the code like shown now in the [official docs](https://developer.android.com/codelabs/jetpack-compose-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fcompose%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fjetpack-compose-state#3).

**Comment by arnaudgiuliani** [comment]
Found the doc here: https://insert-koin.io/docs/reference/koin-android/compose

**Comment by BulatMukhutdinov** [comment]
> @arnaudgiuliani It's not really nice to close an issue without _any_ comment.
> 
> For anyone wondering: it seems to be the best working approach to separate the code like shown now in the [official docs](https://developer.android.com/codelabs/jetpack-compose-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fcompose%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fjetpack-compose-state#3).

Are you talking about State hoisting? If yes it means you have to provide ViewModel to DefaultPreview(). But most of the time ViewModel is hard to construct (that is why we are using DI actually).

Maybe I miss something, could you please provide an example?

**Comment by jemshit** [comment]
https://jetc.dev/slack/2021-04-17-preview-viewmodel.html
