### ISSUE TITLE
[3.0.0-alpha Request] koin-androidx-viewmodel 3.0.0-alpha: ViewModel SavedStateHandle Support

### ISSUE THREAD

**Issue by irgaly** [InsertKoinIO/koin#977]
koin-androidx-viewmodel 2.1.1 has ViewModel SavedStateHandle support, but koin-androidx-viewmodel:3.0.0-alpha-4 does not have that.

I'd like to use Koin in Kotlin Multiplatform project and also Android ViewModel SavedStateHandle.

**Comment by arnaudgiuliani** [comment]
yep, 3.0.0 still need to be merged with 2.2.x branch

**Comment by arnaudgiuliani** [comment]
it will be back in 3.0.1 & 2.3.0
