### ISSUE TITLE
Cannot create viewmodel with koin inject at background thread

### ISSUE THREAD

**Issue by Jun-Hub** [InsertKoinIO/koin#980]
This bug happen in version 2.2.1

Error log : 
> addobserver must be called on the main thread

</br>

First of all, I am using Room DB, viewModel and Repository linked with Room.

When viewModel injected lazy `by viewModel()` , this bug happen.
The viewModel search Room database at background like below code

```
CoroutineScope(Dispachers.Default).launch {
    viewModel.isDataExist(dataId)
}
```

I have found some ways to avoid this error. 

👉🏻 The function that access to Room make `suspend` at dbDAO and Repository and call this suspend function by `viewModelScope.launch` at viewModel.

or

👉🏻 inject viewModel directly, not lazy `getViewModel()`

<br>
p.s. in version 2.1.6, this bug not happen.

**Comment by arnaudgiuliani** [comment]
Check in 3.0.1
