### ISSUE TITLE
Singleton provided by single<> is not Thread-safe

### ISSUE THREAD

**Issue by jemshit** [InsertKoinIO/koin#982]
**Describe the bug**
I get multiple instances of class declared with `single<MyClassInterface> { MyClass() }`. 
- It happens time to time, so it looks like race condition. (there is ~400ms between two instance creations)
- To verify if multiple instance are being created, i used [this approach](https://stackoverflow.com/a/41069117/3736955). I log this in `init{ }` block of kotlin class.
- To check if they are being created from multiple processes, i [printed process name](https://stackoverflow.com/a/55842542/3736955), they are being created in the same process.
- To check if they are being created by different threads, i printed thread names, they are created by different threads (`main` and `DefaultDispatcher-worker-xxxx`). I call this class's method in `GlobalScope.launch()` in App#onCreate which uses `DefaultDispatcher` and also in `launch(Dispatchers.Main)` in the first Activity.

So this must be race condition, because Singleton instance provided by Koin is not Thread safe.

**To Reproduce**
1. Call `GlobalScope.launch{ get<MyClassInterface >.someMethod() }` in `Application#onCreate()` method
2. Call `launch(Dispatchers.Main){ get<MyClassInterface >.someMethod() }` in first opened Activity. `launch` is extension of custom Activity coroutine scope

After writing these steps, to reproduce issue, app-kill, app-open must be repeated multiple times.

**Expected behavior**
Only one instance of MyClass must exist, regardless of which thread it is being created/called by.

**Koin project used and used version:**
- `koin-core version 2.1.6`
- `koin-android version 2.1.6`

**Comment by arnaudgiuliani** [comment]
Fixed in 2.2.0. SingleInstance  factory has been patched.
