### ISSUE TITLE
Module#isLoaded should be public visible.

### ISSUE THREAD

**Issue by kwmt** [InsertKoinIO/koin#986]
**Describe the bug**
[Module#isLoaded](https://github.com/InsertKoinIO/koin/blob/ed522336fbee550fa961ed9732c065310ee80195/koin-projects/koin-core/src/main/kotlin/org/koin/core/module/Module.kt#L41) is now INTERNAL in 2.2.0,  but I want to refer to isLoaded because I have referred it before version.
https://github.com/InsertKoinIO/koin/blob/master/CHANGELOG.md#220-beta-2

**To Reproduce**
Nothing 

**Expected behavior**
should be public visible

**Koin project used and used version (please complete the following information):**
koin-core 2.2.0

**Additional moduleDefinition**
Nothing

**Comment by arnaudgiuliani** [comment]
fixed in 3.0.1
