### ISSUE TITLE
Caused by: org.koin.core.error.NoBeanDefFoundException

### ISSUE THREAD

**Issue by aliceresponde** [InsertKoinIO/koin#987]
**Describe the bug**
When I  have a interface with **generics** 

```
interface BaseDataToDomainMapper<out DomainModel, in DataModel> {
    fun toItem(item: DataModel): DomainModel
    fun toItems(dataList: List<DataModel>): List<DomainModel> { return emptyList() }
}
```
I cant provide the dependency for **concrete implementation class**  into my nodule.

How can I do it? 

**To Reproduce**

**Expected behavior**

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core version 0.9.2`

**Additional moduleDefinition**
Add any other moduleDefinition about the problem here.

**Comment by mkotsbak** [comment]
I think it just works: https://github.com/InsertKoinIO/koin/issues/75
```
single<BaseDataToDomainMapper<SomeDomainModel, SomeDataModel> {... }
```
