### ISSUE TITLE
Kotlin/Native FreezingException

### ISSUE THREAD

**Issue by Savrov** [InsertKoinIO/koin#991]
**Describe the bug**
I'm trying to run an app in Kotlin/Native targeted to macOs. And met an exception I can not fix:
```
Uncaught Kotlin exception: kotlin.native.concurrent.FreezingException: freezing of savrov.sdk.store.client.feature.product.di.ProductModule@d0414e08 has failed, first blocker is org.koin.core.scope.ScopeDefinition@cea8c1fa
```
this is my main.kt class where exception above appears:
```
// run console app
fun main(args: Array<String>) {
    startKoin {
        modules(ProductModule.di())
    }
    // run some command in console 
    MainNavigationCommand().main(args)
}
```
`ProductModule.di()` is a Koin module def. Classes that are defined in it use Kotlin Coroutines v 1.4.2 (if this info is needed)

**I just want to be sure, if Koin supports this scenario - to be used with Kotlin/Native**

Koin project used and used version (please complete the following information): `org.koin:koin-core:3.0.0-alpha-4`

**Comment by jbruchanov** [comment]
+1

**Comment by BulatMukhutdinov** [comment]
Any updates on this?

**Comment by Savrov** [comment]
I have no solution so far

**Comment by BulatMukhutdinov** [comment]
Check this https://github.com/InsertKoinIO/koin/issues/997#event-4434783984
