### ISSUE TITLE
[Question] Injecting Functions without needing Qualifiers

### ISSUE THREAD

**Issue by TurKurT656** [InsertKoinIO/koin#994]
**Describe the question**
This is actually a question and not a bug.
I've made two functional usecases like this:
```
typealias GetVerificationCodeUseCase = (GetVerificationCodeRequest) -> Flow<Result<GetVerificationCodeResponse>>
typealias VerifyCodeUseCase = (VerifyCodeRequest) -> Flow<Result<VerifyCodeResponse>>
```
And I'm injecting them inside a module:
```
val useCaseModule = module {
    factory<GetVerificationCodeUseCase> { get<AuthRepository>()::getVerificationCode }
    factory<VerifyCodeUseCase> { get<AuthRepository>()::verifyCode }
}
```
and using them inside my `LoginViewModel`: 
```
class LoginViewModel(
    private val getVerificationCodeUseCase: GetVerificationCodeUseCase,
    private val verifyCodeUseCase: VerifyCodeUseCase,
) : BaseViewModel() {
    ...
}
```
But in onCreate of my application it gives me this error:
```Caused by: org.koin.core.error.DefinitionOverrideException: Definition '[Factory:'kotlin.jvm.functions.Function1']' try to override existing definition. Please use override option to fix it```

It's obvious that koin cannot detect difference between these two, because both of them are actually a Function1. how can I overcome this issue without making a qualifier per usecase? 

**Koin project used and used version (please complete the following information):**
`koin-core version 2.2.1`
`koin-android version 2.2.1`
`koin-android-viewModel version 2.2.1`

**Comment by JonathanDeLeon** [comment]
This may be of help and possibly might give you the answer you are looking for. 

There is an old issue related to this - https://github.com/InsertKoinIO/koin/issues/216

Since that issue, Kotlin has released support for SAM functional interfaces which could be a solution for you.
