### ISSUE TITLE
Missing variant koin-core-mingwx64

### ISSUE THREAD

**Issue by jbruchanov** [InsertKoinIO/koin#995]
Just having sample multiplatform kt project running it on windows.

There doesn't seem to be any windows (koin-core-mingwx64) variant for the 3.0.0 alpha.
Could you please release it ?

```
Execution failed for task ':test-shared:compileKotlinNative'.
> Could not resolve all files for configuration ':test-shared:nativeCompileKlibraries'.
   > Could not find org.koin:koin-core-mingwx64:3.0.0-alpha-4.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/koin/koin-core-mingwx64/3.0.0-alpha-4/koin-core-mingwx64-3.0.0-alpha-4.pom
       - https://dl.google.com/dl/android/maven2/org/koin/koin-core-mingwx64/3.0.0-alpha-4/koin-core-mingwx64-3.0.0-alpha-4.pom
       - https://repo.maven.apache.org/maven2/org/koin/koin-core-mingwx64/3.0.0-alpha-4/koin-core-mingwx64-3.0.0-alpha-4.pom
       - https://dl.bintray.com/kotlin/kotlin-js-wrappers/org/koin/koin-core-mingwx64/3.0.0-alpha-4/koin-core-mingwx64-3.0.0-alpha-4.pom
       - https://dl.bintray.com/ekito/koin/org/koin/koin-core-mingwx64/3.0.0-alpha-4/koin-core-mingwx64-3.0.0-alpha-4.pom
     Required by:
         project :test-shared > org.koin:koin-core:3.0.0-alpha-4
```

**Comment by jbruchanov** [comment]
local build works fine, so I guess it's just forgotten release variant.

**Comment by arnaudgiuliani** [comment]
any better with 3.0.1 from maven central? (`io.insert-koin` as group id)

**Comment by ncipollo** [comment]
Hey @arnaudgiuliani ,

This still appears to be an issue in `3.0.1`. Here's a project I have which is failing to resolve the artifact for windows: https://github.com/tixorg/tix-core/runs/2605441344?check_suite_focus=true

If you take a look at maven central it does in fact appear that there is no windows (`mingwx64`) artifact.

**Comment by arnaudgiuliani** [comment]
> Note: I'm not sure if publishing works the same way but I know that the kotlin multiplatform plugin will usually skip windows variants unless you are running on a windows machine, so you might need to use github actions or something to actually run your publish script(s).

Exact, can't do that on my own for now :/ I need to setup proper CI for that
